{
  "hash": "305a75b72475b16018cf0ab182e40047",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 10: Testing decisions, errors, power, and the road to regression {#b10}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 10, you can</span>\n\n- rewrite benchmark and comparison questions as tests of a zero contrast;\n- complete and communicate a two-sided test using the seven-step workflow;\n- distinguish a p-value, a significance level, and a test decision;\n- describe Type I error, Type II error, and power in context;\n- explain when a one-sided alternative is legitimate and why this course's\n  exams are two-sided;\n- separate statistical significance from magnitude, practical importance,\n  and causality;\n- interpret the zero-null test printed for a regression coefficient.\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">Launch the product or wait. Approve the loan or decline. Decisions made from data can err in two directions, and the two mistakes usually cost very different amounts.</p>\n\nEvery test can be wrong in two ways. Which wrong call is which, what makes\nwrong calls rarer, and how does all of this reappear in a regression table?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 25 minutes.</span>\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation (15 minutes)</span><br>\nReview <a href=\"https://www.youtube.com/watch?v=ti9NFdjf3sM\">Introduction to\nHypothesis Testing</a> and watch\n<a href=\"https://www.youtube.com/watch?v=JNOWWJeZBTc\">Examples Identifying\nType I and Type II Errors</a>. Focus on two-sided tests, decision errors,\nand why \"do not reject\" is not \"accept.\" All links are also listed in the\n<a href=\"../resources/video-guide.html\">External Video Guide</a>.\n</div>\n\n**Reactivate (8 minutes).** Suppose R reports the following coefficient row:\n\n| Estimate | SE | t | p-value |\n|---:|---:|---:|---:|\n| -0.290 | 0.058 | -5.00 | < 0.001 |\n\nState the hypotheses being tested and give a careful one-sentence\nstatistical conclusion.\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\nThe default two-sided coefficient test is $H_0:\\beta=0$ against\n$H_1:\\beta\\ne0$. Because the p-value is below 0.05, reject $H_0$: the data\nprovide evidence that the population-model coefficient differs from zero.\nA full interpretation still needs the outcome, predictor, units, held-fixed\nvariables, population, and causal limit.\n:::\n\n**Predict (2 minutes).** Answer the one-click Mentimeter question posted on\nCanvas before you come to class: a test at $\\alpha=0.05$ returns\n$p=0.20$. Has the study **shown that the null is true** --- yes, no, or\ncannot tell? Commit to an answer; the lecture resolves it.\n\nReview [Mathematics Refresher: zero contrasts, inequalities, and\nstandardisation](../resources/math-refresher.html) if needed.\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In class\n\nThe session opens with the usual four-minute entry quiz on the prep videos,\nthen turns to the driving question. Lecture 9 delivered one complete test.\nThis final lecture makes testing a *routine*: one recipe, an honest account\nof the two ways any decision can be wrong, and the payoff --- the same\nmachinery reappearing, unchanged, in every regression table you will read\nfrom Intermediate onwards.\n\n<p class=\"concept-video\"><strong>Video explanations (review):</strong>\n<a href=\"https://www.youtube.com/watch?v=ti9NFdjf3sM\">Introduction to Hypothesis Testing</a> and\n<a href=\"https://www.youtube.com/watch?v=JNOWWJeZBTc\">Type I and Type II Errors</a>.</p>\n\n### Why zero is the universal benchmark\n\nMany empirical questions ask whether a population contrast is absent:\n\n- difference from a target: $\\delta=\\mu-15$;\n- difference in probabilities: $\\delta_p=p-0.50$;\n- difference between two group means: $\\mu_1-\\mu_0$;\n- a regression slope: $\\beta_j$.\n\nIn every case, \"no difference\" or \"no linear association\" becomes\n\n$$\nH_0:\\theta=0\n\\qquad\\text{versus}\\qquad\nH_1:\\theta\\ne0.\n$$\n\nTesting a non-zero benchmark can always be rewritten as a test of a\nzero-valued contrast --- Lecture 9's gap device. This common structure is\nthe bridge from Basic inference to regression inference: learn to test one\nzero, and you can test them all.\n\n### The seven-step testing workflow\n\nUse the same sequence every time --- on the exam, in your EiA venture, in\nany report you ever write:\n\n1. Define the population parameter and its units.\n2. State $H_0$ and the two-sided $H_1$ **before** inspecting the result.\n3. Check the sampling and model conditions.\n4. Calculate the estimate and its SE under the null model.\n5. Standardise: $(\\text{estimate}-0)/\\text{SE}$.\n6. Calculate the two-sided p-value and compare it with the pre-specified\n   significance level $\\alpha$.\n7. Report the estimate, uncertainty, decision, contextual meaning, and\n   limits.\n\nThe significance level $\\alpha$ is a long-run decision threshold, commonly\n0.05, fixed in advance. The p-value is calculated from the observed data\nunder $H_0$. They are not the same object: one is a rule, the other a\nresult.\n\nIf $p\\le\\alpha$, reject $H_0$. If $p>\\alpha$, **do not reject** $H_0$ ---\nand do not say \"accept $H_0$.\" This resolves the prep prediction: a study\nwith $p=0.20$ has *not* shown the null is true; it may simply lack the\nprecision to distinguish a meaningful non-zero parameter from zero. The\npower section below makes that precise.\n\n::: {#exm-b10-launch-test}\n## Worked example: a proportion test by hand\n\nAn accelerator claims that half of its alumni launch a trading venture\nwithin a year. In a random sample of 400 former participants, 232 had\nlaunched. Let $p$ be the launch proportion in the alumni frame and define\n$\\delta_p=p-0.50$. Test $H_0:\\delta_p=0$ against $H_1:\\delta_p\\ne0$ at 5%,\nvoicing every arithmetic step.\n\n- **Estimate.** $\\hat p=232/400=0.58$, so the estimated gap is\n  $\\widehat\\delta_p=0.58-0.50=0.08$, eight percentage points.\n- **Conditions under the null.** $np_0=400(0.50)=200$ and\n  $n(1-p_0)=200$, both far above 10 --- the normal approximation is safe.\n- **Null SE.** Under $H_0$ the true proportion is 0.50, so\n  $\\operatorname{SE}_0=\\sqrt{0.50(0.50)/400}=\\sqrt{0.25/400}\n  =\\sqrt{0.000625}=0.025$.\n- **Standardise.** $z=0.08/0.025=3.20$: the observed gap sits 3.2 null\n  standard errors above zero.\n- **p-value and decision.** The two-sided p-value is\n  $2\\,P(Z\\le-3.20)\\approx 0.0014 < 0.05$: reject $H_0$. The sample\n  provides strong evidence that the frame launch proportion differs from\n  50%; the positive estimate places it above.\n\nNote step 4's subtlety: the SE was computed with $p_0=0.50$, not with\n$\\hat p$ --- the test measures how surprising the sample is *in the null's\nworld*, so the null supplies the spread.\n:::\n\n### The Shark Tank deal proportion, in R\n\nThe same recipe on our reproducible sample of 100: is the frame's deal\nproportion different from 50%? Every object is constructed on screen:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nset.seed(123)\nsample_rows <- sample(seq_len(nrow(sharks)), size = 100, replace = FALSE)\npitch_sample <- sharks[sample_rows, ]\n\nn <- nrow(pitch_sample)\nphat <- mean(pitch_sample$deal_on_show)   # sample deal proportion\np0 <- 0.50                                # null value\ndeal_gap <- phat - p0                     # estimated gap\n\nc(n = n, phat = phat, p0 = p0, deal_gap = deal_gap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       n     phat       p0 deal_gap \n  100.00     0.64     0.50     0.14 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_se <- sqrt(p0 * (1 - p0) / n)\nz_value <- deal_gap / null_se\ntwo_sided_p <- 2 * pnorm(-abs(z_value))\n\nc(\n  null_standard_error = null_se,\n  z_statistic = z_value,\n  two_sided_p_value = two_sided_p\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnull_standard_error         z_statistic   two_sided_p_value \n        0.050000000         2.800000000         0.005110261 \n```\n\n\n:::\n:::\n\n\n\n\nThe estimate is $\\widehat\\delta_p=0.14$, fourteen percentage points. The\nnull SE is $\\sqrt{0.50(0.50)/100}=0.05$, the statistic is $z=2.80$, and\nthe two-sided p-value is about 0.005. The success--failure condition holds\nunder the null: $np_0=50$ and $n(1-p_0)=50$. Reject the zero-gap null at\n5%: the random sample provides evidence that the recorded-pitch-frame deal\nproportion differs from 50%, and the positive estimate places it above.\n\n### Interval and test: report both\n\nStep 7 of the workflow says a decision alone is not a report. A\nlarge-sample 95% interval for the proportion uses the estimated SE:\n\n$$\n\\hat p\\pm1.96\n\\sqrt{\\frac{\\hat p(1-\\hat p)}{n}}.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimated_se <- sqrt(phat * (1 - phat) / n)\nproportion_ci <- phat + c(-1, 1) * 1.96 * estimated_se\ngap_ci <- proportion_ci - p0\n\nc(proportion_lower = proportion_ci[1],\n  proportion_upper = proportion_ci[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nproportion_lower proportion_upper \n         0.54592          0.73408 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(gap_lower = gap_ci[1], gap_upper = gap_ci[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngap_lower gap_upper \n  0.04592   0.23408 \n```\n\n\n:::\n:::\n\n\n\n\nThe proportion interval is approximately $(0.546,\\,0.734)$; the equivalent\ngap interval is $(0.046,\\,0.234)$, which excludes zero and agrees with the\ntest decision here.\n\n::: {.optional-box}\n<span class=\"label\">Optional: estimated versus null standard errors</span><br>\nLook closely: the test divided by the **null** SE\n$\\sqrt{p_0(1-p_0)/n}=0.050$, while the interval used the **estimated** SE\n$\\sqrt{\\hat p(1-\\hat p)/n}=0.048$. The test asks how surprising the sample\nis if $H_0$ were true, so the null supplies the spread; the interval makes\nno null assumption, so the data supply it. Because these are not exactly\nthe same procedure, interval and test decisions need not match perfectly\nwhen a result sits very near the boundary. Exact equivalence requires an\ninterval obtained by inverting the same test --- beyond this course. For\nthe mean-gap t procedures of Lecture 9 the same SE is used in both, so\nthere the match is exact.\n:::\n\n### What a p-value is not\n\nThe two-sided p-value is\n\n$$\nP\\!\\left(|\\text{test statistic}|\n\\ge|\\text{observed statistic}|\\mid H_0\\right)\n$$\n\n--- and nothing else. Before the break you receive four sentences about the\nlaunch test of @exm-b10-launch-test ($z=3.20$, $p\\approx 0.0014$). Each\none is wrong. In pairs, correct all four; the plenary compares repairs.\n\n::: {.callout-caution collapse=\"true\"}\n## Try it: correct the four wrong p-value sentences\n\n*Sentence 1 (you).* \"There is only a 0.14% probability that the launch\nproportion really is 50%.\"\n\n*Sentence 2 (you).* \"The result has a 0.14% probability of being due to\nchance.\"\n\n*Sentence 3 (you).* \"Such a tiny p-value shows that the launch proportion\nis far above 50%.\"\n\n*Sentence 4 (you).* \"The tiny p-value proves that the accelerator causes\nits alumni to launch ventures.\"\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. A p-value is not $P(H_0\\mid\\text{data})$. Correct: \"If the launch\n   proportion were exactly 50%, a sample gap at least this far from zero\n   in either direction would occur in about 0.14% of random samples.\"\n2. The p-value is computed *assuming* chance alone (the null model)\n   generated the gap; it is the probability of data this extreme under\n   that assumption, not the probability that the assumption holds.\n3. A p-value measures surprise, not size. The magnitude is the estimate:\n   8 percentage points, with an interval around it. A tiny p-value can\n   accompany a tiny gap when $n$ is huge.\n4. Significance says nothing about why. Alumni self-selected into the\n   accelerator; without a design that isolates its effect, \"causes\" is\n   unsupported. Correct: the frame's launch proportion differs from 50%.\n:::\n:::\n\n### Type I error, Type II error, and power\n\nA test is a decision rule, and any decision rule can be wrong in exactly\ntwo ways:\n\n| Reality | Reject $H_0$ | Do not reject $H_0$ |\n|---|---|---|\n| $H_0$ true | Type I error | Correct decision |\n| $H_1$ true | Correct decision | Type II error |\n\nThe significance level controls the first:\n\n$$\nP(\\text{reject }H_0\\mid H_0\\text{ true})=\\alpha.\n$$\n\n**Power** is the ability to avoid the second:\n\n$$\n\\text{power}=P(\\text{reject }H_0\\mid H_1\\text{ true}).\n$$\n\nFor the launch test, in context: a **Type I error** would be concluding\nthat the alumni launch proportion differs from 50% when it is exactly 50%\n--- crying wolf about a fictitious difference, embarrassing the analyst who\nadvises repricing the programme. A **Type II error** would be failing to\ndetect a launch proportion that genuinely differs from 50% --- missing a\nreal signal because the sample was too small or noisy.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\n\nz_grid <- seq(-4.5, 6.5, length.out = 1600)\ncritical <- qnorm(0.975)\npanel_levels <- c(\"Null is true\", \"An alternative value is true\")\n\ntest_curves <- rbind(\n  data.frame(z = z_grid, density = dnorm(z_grid, mean = 0),\n             panel = panel_levels[1]),\n  data.frame(z = z_grid, density = dnorm(z_grid, mean = 2.5),\n             panel = panel_levels[2])\n)\ntest_curves$panel <- factor(test_curves$panel, levels = panel_levels)\n\nrejection <- subset(test_curves, z <= -critical | z >= critical)\nrejection$side <- ifelse(rejection$z < 0, \"left\", \"right\")\n\npanel_labels <- data.frame(\n  z = c(0, 3.6),\n  density = c(0.13, 0.14),\n  label = c(\"do not reject\", \"power\"),\n  panel = factor(panel_levels[c(1, 2)], levels = panel_levels)\n)\nalpha_labels <- data.frame(\n  z = c(-2.5, 2.5),\n  density = c(0.028, 0.028),\n  label = c(\"alpha/2\", \"alpha/2\"),\n  panel = factor(panel_levels[c(1, 1)], levels = panel_levels)\n)\n\nggplot(test_curves, aes(z, density)) +\n  geom_area(data = rejection, aes(group = side, fill = panel),\n            alpha = 0.4) +\n  geom_vline(xintercept = c(-critical, critical), linetype = \"dashed\",\n             colour = \"#5B6976\", linewidth = 0.5) +\n  geom_line(aes(colour = panel), linewidth = 0.9) +\n  geom_text(data = panel_labels, aes(label = label),\n            colour = \"#17324D\", size = 3.4) +\n  geom_text(data = alpha_labels, aes(label = label), parse = TRUE,\n            colour = \"#17324D\", size = 3.1) +\n  facet_wrap(~ panel, scales = \"fixed\") +\n  scale_fill_manual(values = c(\"Null is true\" = \"#D55E00\",\n                               \"An alternative value is true\" = \"#009E73\"),\n                    guide = \"none\") +\n  scale_colour_manual(values = c(\"Null is true\" = \"#17324D\",\n                                 \"An alternative value is true\" = \"#0072B2\"),\n                      guide = \"none\") +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +\n  coord_cartesian(xlim = c(-4, 6)) +\n  labs(x = \"z statistic\", y = \"Density\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\"),\n    strip.text = element_text(colour = \"#17324D\", face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![Two-sided testing at α = 0.05. Left: when the null is true, the z statistic follows the dark curve and the orange rejection regions have total probability 0.05 — the Type I error rate. Right: when a positive alternative is true, the statistic follows the shifted blue curve; the green area is the power, and the unshaded middle is the Type II error probability. Both panels use the same axes.](b10-testing-errors-power_files/figure-html/fig-b10-errors-power-1.png){#fig-b10-errors-power width=672}\n:::\n:::\n\n\n\n\nIn both panels of @fig-b10-errors-power, the horizontal axis is the\npossible z statistic, the vertical axis is density, and probability is\narea. The dashed vertical lines mark the same two-sided critical values,\n$\\pm 1.96$. In the left panel the null is true: the two orange rejection\ntails have total probability $\\alpha=0.05$, which is exactly the Type I\nerror rate --- the test is *built* to cry wolf 5% of the time. In the right\npanel a particular positive alternative is true, so the curve has shifted:\nthe green area is the power, and whatever probability remains between the\ndashed lines is the Type II error rate.\n\nFour levers raise power:\n\n- a larger true distance from zero (an effect that is easier to see);\n- a larger sample (a smaller SE);\n- lower unexplained variation (also a smaller SE);\n- a larger $\\alpha$ --- but this lever is a trade-off, not a free gain:\n  widening the rejection region catches more true effects *and* raises the\n  Type I error rate in lockstep.\n\n### One-sided alternatives\n\nA two-sided test asks whether a parameter differs from zero in **either**\ndirection. A one-sided test asks a directional question chosen before the\nsample is examined:\n\n| Research question | Alternative | Relevant tail(s) |\n|---|---|---|\n| Does the gap differ from zero? | $H_1:\\delta\\ne0$ | both tails |\n| Is the gap below zero? | $H_1:\\delta<0$ | left tail |\n| Is the gap above zero? | $H_1:\\delta>0$ | right tail |\n\nIn all three cases the test statistic is compared with its distribution\nunder the zero boundary $H_0:\\delta=0$. What changes is which values count\nas evidence for the stated alternative --- that is, where the rejection\nregion sits.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\n\nalpha_tail <- 0.05\ntail_df <- 99\ntail_grid <- seq(-4, 4, length.out = 1400)\ncritical_two <- qt(c(alpha_tail / 2, 1 - alpha_tail / 2), df = tail_df)\ncritical_left <- qt(alpha_tail, df = tail_df)\ncritical_right <- qt(1 - alpha_tail, df = tail_df)\n\npanel_levels <- c(\"Two-sided\", \"Left-sided\", \"Right-sided\")\nnull_curve <- do.call(rbind, lapply(panel_levels, function(p) {\n  data.frame(x = tail_grid, density = dt(tail_grid, df = tail_df),\n             panel = p)\n}))\nnull_curve$panel <- factor(null_curve$panel, levels = panel_levels)\n\nrejection <- rbind(\n  cbind(subset(null_curve, panel == \"Two-sided\" & x <= critical_two[1]),\n        side = \"left\"),\n  cbind(subset(null_curve, panel == \"Two-sided\" & x >= critical_two[2]),\n        side = \"right\"),\n  cbind(subset(null_curve, panel == \"Left-sided\" & x <= critical_left),\n        side = \"left\"),\n  cbind(subset(null_curve, panel == \"Right-sided\" & x >= critical_right),\n        side = \"right\")\n)\n\ncritical_lines <- data.frame(\n  x = c(critical_two, critical_left, critical_right),\n  panel = factor(c(\"Two-sided\", \"Two-sided\", \"Left-sided\", \"Right-sided\"),\n                 levels = panel_levels)\n)\n\npanel_labels <- data.frame(\n  x = c(-2.8, 2.8, -2.8, 2.8, 0, 0, 0),\n  density = c(0.035, 0.035, 0.035, 0.035, 0.42, 0.42, 0.42),\n  label = c(\"2.5%\", \"2.5%\", \"5%\", \"5%\",\n            \"H[1] : delta != 0\", \"H[1] : delta < 0\", \"H[1] : delta > 0\"),\n  parse_me = c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE),\n  panel = factor(c(\"Two-sided\", \"Two-sided\", \"Left-sided\", \"Right-sided\",\n                   \"Two-sided\", \"Left-sided\", \"Right-sided\"),\n                 levels = panel_levels)\n)\n\nggplot(null_curve, aes(x, density)) +\n  geom_area(data = rejection, aes(group = side),\n            fill = \"#D55E00\", alpha = 0.6) +\n  geom_vline(xintercept = 0, linetype = \"dotted\",\n             colour = \"grey75\", linewidth = 0.4) +\n  geom_vline(data = critical_lines, aes(xintercept = x),\n             linetype = \"dashed\", colour = \"#5B6976\", linewidth = 0.5) +\n  geom_line(colour = \"#17324D\", linewidth = 0.8) +\n  geom_text(data = subset(panel_labels, !parse_me), aes(label = label),\n            colour = \"#17324D\", size = 2.9) +\n  geom_text(data = subset(panel_labels, parse_me), aes(label = label),\n            parse = TRUE, colour = \"#5B6976\", size = 3.1) +\n  facet_wrap(~ panel, nrow = 1, scales = \"fixed\") +\n  scale_x_continuous(breaks = c(-3, 0, 3)) +\n  scale_y_continuous(breaks = c(0, 0.2, 0.4), limits = c(0, 0.44),\n                     expand = expansion(mult = c(0, 0.02))) +\n  labs(x = \"t statistic\", y = \"Density\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\"),\n    strip.text = element_text(colour = \"#17324D\", face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![Rejection regions at α = 0.05 for the two-sided and both one-sided alternatives, on the same null t distribution (df = 99). The two-sided test places 2.5% in each tail; a one-sided test moves the full 5% into the tail named by its alternative, so its critical value is closer to zero in that direction.](b10-testing-errors-power_files/figure-html/fig-b10-one-sided-1.png){#fig-b10-one-sided width=672}\n:::\n:::\n\n\n\n\nCompare @fig-b10-one-sided with the left panel of\n@fig-b10-errors-power: same logic, different placement of the 5%. Moving\nthe full 5% into one tail pulls that critical value closer to zero, so a\none-sided test is *more* able to detect an effect in its chosen direction\n--- a power gain. The price: results in the opposite direction, however\nextreme, do not support the stated alternative at all.\n\nThat power gain is exactly why the direction must follow from the research\nquestion and be **fixed before the data are inspected**. Choosing the tail\nbecause the observed estimate happens to point that way --- or simply to\nobtain a smaller p-value --- silently doubles the true Type I error rate:\nyou would take the 5% tail on whichever side the noise landed. For\nLecture 9's equity-gap statistic, $t=-2.91$ with $df=99$:\n\n- the two-sided p-value is about 0.0045;\n- a **pre-specified** left-sided alternative $H_1:\\delta<0$ gives about\n  0.0023;\n- a **pre-specified** right-sided alternative $H_1:\\delta>0$ gives about\n  0.9977.\n\nThe negative estimate agrees with the left-sided alternative and points\naway from the right-sided one. Course convention, on the exam and in every\nchapter: **tests are two-sided**, because in business research a\ndifference in either direction is usually relevant --- and because the\nconvention removes any temptation to pick the convenient tail.\n\n### Preview: the test attached to a regression slope\n\nR applies the same zero-null logic to every regression coefficient.\nConsider the simple model of initial equity offered on season, fitted to\nall 1,441 records:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreview_model <- lm(equity_offered_pct ~ season, data = sharks)\nsummary(preview_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error   t value      Pr(>|t|)\n(Intercept) 20.4565874 0.46442667  44.04697 4.922706e-269\nseason      -0.8241241 0.04752298 -17.34159  2.514546e-61\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(preview_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept) 19.5455616 21.3676132\nseason      -0.9173458 -0.7309023\n```\n\n\n:::\n:::\n\n\n\n\nRead the `season` row with the vocabulary you now own. The **estimate** is\n$-0.824$: about 0.82 percentage points less equity offered per additional\nseason. The **SE**, 0.048, is its sampling uncertainty in the same units.\nThe **t value**, $-17.3$, is estimate divided by SE --- step 5 of the\nworkflow. The **p-value** belongs to the printed two-sided test\n\n$$\nH_0:\\beta_1=0\n\\qquad\\text{versus}\\qquad\nH_1:\\beta_1\\ne0,\n$$\n\nand the 95% **interval** $(-0.92,\\,-0.73)$ excludes zero, agreeing with\nthe rejection. Every column is a Lecture 9--10 object wearing a regression\nname. What the row does *not* say: this is an observational time\nassociation, not a causal effect of moving a pitch to a later season.\n\nIntermediate begins from this familiar estimate--SE--t--p-value structure\nand adds careful coefficient interpretation, multiple predictors, and\nmodel diagnostics.\n\n::: {.caveat-box}\n<span class=\"label\">What a significant result does and does not establish</span>\n\nThree separations to carry out of this course. **Significance is not\nmagnitude:** a tiny effect can be significant in a large sample, and a\nmeaningful effect can be non-significant in a small or noisy one --- the\np-value measures surprise under the null, the estimate measures size.\n**Significance is not causation:** none of this lecture's machinery knows\nwhether the predictor was randomly assigned. **And no test repairs the\nframe:** selection into the recorded-pitch file, measurement of \"deal\" as\nan on-air agreement, and dependence between observations are untouched by\nany p-value. The standing reporting list, for every analysis from now on:\nthe estimate in substantive units; a confidence interval; the p-value or\ndecision; whether the magnitude matters for the business question; and the\nsampling, measurement, and causal limits.\n:::\n\n### Answering the driving question\n\nThe two wrong calls: rejecting a true null (Type I, rate set by $\\alpha$)\nand missing a true effect (Type II, rate cut by power). Wrong calls become\nrarer with more data, less noise, bigger true effects --- and, for Type I\nonly, a stricter $\\alpha$, at the price of more Type II. And the\nregression table? Each coefficient row *is* a Lecture 9 test: estimate,\nSE, t, two-sided p against zero, interval.\n\nThat closes the arc of QM Basic. Ten lectures ago a Shark Tank pitch was\nan anecdote. Now you can define events and variables on a frame, describe\ntheir distributions, condition without confusing directions, model\nsampling variation, and turn \"our sample mean is 12.76\" into a defensible,\nproperly hedged claim about a population --- with its uncertainty, its\ndecision, and its limits stated. That is the difference between an opinion\nwith a spreadsheet and evidence.\n\n**Next:** Tutorial 4 rehearses Lectures 9--10 in exam format, and the Mock\nExam then integrates the whole course under exam conditions. The story itself\ncontinues next year: QM Intermediate picks up exactly where today's regression\npreview left off, and the coefficient row you can already read becomes the\ncentral object of six lectures on linear regression.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 65 minutes.</span>\n\n### Retrieval (10 minutes)\n\n1. Why can most comparison hypotheses be written as a parameter equal to\n   zero?\n2. What is the difference between $\\alpha$ and a p-value?\n3. What is a Type I error?\n4. What is a Type II error?\n5. Name three factors that increase power.\n6. Why is \"do not reject\" different from \"accept\"?\n7. What does $H_0:\\beta_j=0$ mean in a regression model?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. Subtracting the benchmark or reference value creates a contrast; \"no\n   difference\" corresponds to a zero contrast.\n2. $\\alpha$ is a pre-specified long-run decision threshold; the p-value is\n   calculated from the observed statistic under the null.\n3. Rejecting $H_0$ when it is true.\n4. Not rejecting $H_0$ when a specified alternative is true.\n5. Any three of: larger sample size, larger true effect, lower noise, or\n   larger $\\alpha$ (the last at the cost of more Type I errors).\n6. A non-significant result may simply be too imprecise to distinguish a\n   meaningful parameter from zero.\n7. Holding the other included predictors fixed, the population-model\n   coefficient for predictor $j$ is zero.\n:::\n\n### From worked to faded, then unassisted (20 minutes)\n\nRe-read the hand-worked launch test (@exm-b10-launch-test). Then complete\nthe same recipe with new numbers: in 200 independent trials there are 120\nsuccesses, and the benchmark is $p_0=0.50$.\n\n*Step 1 (given).* $\\hat p=120/200=0.60$, so $\\widehat\\delta_p=0.10$; the\nnull counts are $200(0.50)=100$ successes and 100 failures, both above 10.\n\n*Step 2 (you).* Calculate the null SE and the z statistic.\n\n*Step 3 (you).* The two-sided p-value and the 5% decision, in context.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$\\operatorname{SE}_0=\\sqrt{0.50(0.50)/200}\\approx 0.0354$, so\n$z=0.10/0.0354\\approx 2.83$ and the two-sided p-value is about 0.005.\nReject the zero-gap null at 5%: the data provide evidence that the success\nproportion differs from 50%, with the positive estimate placing it above.\n:::\n\nNow unassisted:\n\n1. A sample of $n=49$ difference scores has $\\bar d=3$ and $s_d=14$. Test\n   $H_0:\\delta=0$ against $H_1:\\delta\\ne0$ at 5%.\n2. Describe the Type I and Type II errors for the 120-of-200 test above,\n   in context.\n3. A multiple-regression coefficient is $-0.290$ percentage points per\n   €100,000, with SE 0.058 and a large $df$. Calculate its t statistic and\n   approximate 95% interval, and interpret the row.\n4. A coefficient estimate is economically negligible but has $p<0.001$.\n   Explain how both facts can be true.\n5. State two reasons the regression preview cannot support a causal\n   conclusion.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. The SE is $14/\\sqrt{49}=2$, so $t=3/2=1.50$ with $df=48$; the two-sided\n   p-value is about 0.14. Do not reject the zero mean-difference null at\n   5% --- which is not evidence that the difference is zero.\n2. Type I: concluding the population success proportion differs from 0.50\n   when it equals 0.50. Type II: failing to detect a genuine specified\n   difference from 0.50.\n3. $t=-0.290/0.058=-5.00$. With a large $df$, the 95% interval is\n   approximately $-0.290\\pm1.96(0.058)=(-0.404,\\,-0.176)$ percentage\n   points per €100,000. Holding the model's other predictors fixed, an\n   additional €100,000 requested is associated with between about 0.18 and\n   0.40 percentage points less fitted equity; reject the zero-coefficient\n   null.\n4. A very large sample or low noise makes the SE tiny, so even a\n   negligible coefficient sits many SEs from zero. Precision does not\n   confer importance.\n5. Season was not randomly assigned, and omitted factors, selection,\n   reverse direction, or measurement error can all remain.\n:::\n\n### One-sided reasoning (10 minutes)\n\nLecture 9's equity-gap test gave $t=-2.91$ with $df=99$.\n\n1. State all three p-values: two-sided, left-sided ($H_1:\\delta<0$), and\n   right-sided ($H_1:\\delta>0$).\n2. Which of the three alternatives would have been legitimate to\n   pre-specify, and what determines that?\n3. A classmate, seeing the negative estimate, switches to the left-sided\n   alternative \"because it fits the data.\" What exactly is wrong?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. Two-sided: about 0.0045. Left-sided: about 0.0023 (the single left tail\n   beyond $-2.91$). Right-sided: about 0.9977 (everything to the right of\n   $-2.91$).\n2. Any of the three --- **provided** it was fixed before inspecting the\n   sample and follows from the research question. Legitimacy is about\n   timing and motivation, not about which alternative is \"correct.\"\n3. Choosing the tail after seeing the estimate means the 5% rejection mass\n   would follow the data to whichever side the noise landed, so the true\n   Type I error rate is doubled to about 10%. The smaller p-value is\n   bought by an invalid procedure. Course convention: two-sided, always,\n   on the exam.\n:::\n\n### Spaced review: one item each from Lectures 9 and 5 (10 minutes)\n\n1. *(Lecture 9.)* A 95% confidence interval for a mean gap is\n   $(0.4,\\,5.2)$ units. State the 5% two-sided test decision without\n   computing, and name one thing the interval reports that the decision\n   does not.\n2. *(Lecture 5.)* In the full file, the correlation between season and\n   initial equity offered is about $-0.42$. Interpret this number in one\n   sentence, and state one claim it cannot support.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. The interval excludes zero, so the matched two-sided test rejects\n   $H_0:\\delta=0$ at 5%. The interval additionally shows direction,\n   plausible magnitude (0.4 to 5.2 units), and precision.\n2. Season and offered equity have a moderate negative linear association:\n   later-season pitches tend to offer less equity. It cannot support a\n   causal claim --- nothing assigned pitches to seasons, and other factors\n   changed over time.\n:::\n\n### Worked exam interpretation (10 minutes)\n\n**Question (Mock Exam Q5 pattern).** In a simple random sample of 400\nformer accelerator participants, 232 had launched a trading venture within\none year; a two-sided test of $H_0:p=0.50$ is planned. The same study\nfits a regression of monthly revenue (thousands of euros) on weekly\nmentoring hours; one row of the output is:\n\n```text\n                 Estimate  Std. Error  t value  Pr(>|t|)  95% CI\nmentoring_hours     0.80       0.25       3.20     0.0016  [0.31, 1.29]\n```\n\nComplete the proportion test at 5% (a large-sample 95% interval for $p$ is\n$(0.532,\\,0.628)$), define a Type I error for it, name two power levers\nthat hold $\\alpha$ fixed, and interpret the regression row without causal\nlanguage.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nUnder $H_0$, $np_0=n(1-p_0)=200\\ge 10$. $\\hat p=232/400=0.58$,\n$\\operatorname{SE}_0=\\sqrt{0.50(0.50)/400}=0.025$, and $z=0.08/0.025=3.20$\nwith two-sided p-value about 0.0014: reject $H_0$; the frame launch\nproportion differs from 50%, plausibly between 53.2% and 62.8% --- the\ninterval excludes 0.50, agreeing with the test. A Type I error would be\nconcluding the launch proportion differs from 50% when it equals 50%.\nWith $\\alpha$ fixed, power rises with a larger sample or lower outcome\nvariability (or a larger true gap, though that is not chosen). The\nregression row: each additional weekly mentoring hour is associated with\n0.80 thousand euros more fitted monthly revenue; $t=0.80/0.25=3.20$,\n$p=0.0016$, and the interval $(0.31,\\,1.29)$ excludes zero, so reject\n$H_0:\\beta=0$. Mentoring hours were not randomly assigned, so this is an\nassociation, not a causal effect.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA venture --- or any business you know well. Name one\nyes-or-no claim you will realistically have to defend with data (our\nconversion rate beats the sector's 3%; our average order exceeds the\nbreak-even basket), and write two sentences: first state it as a two-sided\nzero-contrast test and say which of the two errors would be more costly\nfor you and why, then name the one power lever you could actually pull\nbefore your next pitch.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"My claim: our conversion rate differs from the sector's 3% --- $H_0\\!: p = 0.03$ against a two-sided alternative. A false alarm is the costlier error, because I would sign a bigger kitchen lease on an effect that is not real; the one power lever I can pull before the next pitch is sample size, by running the tasting stand two more weeks.\"\n:::\n\nYou can discuss this task --- and any other task in this chapter --- with\n**Tilly**, the course AI assistant on Canvas: ask it to draft the\nseven-step workflow for your claim and challenge your choice of the more\ncostly error.\n::::\n\nContinue to Tutorial 4: Inference and tests against zero.\n\nFormula sheet: Lecture 10 formulas.\n\nFor a more formal explanation, consult\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapters 15 and 16.\n\n:::\n",
    "supporting": [
      "b10-testing-errors-power_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}