{
  "hash": "619d70758d61710a22ae76f8a3ea7cd8",
  "result": {
    "engine": "knitr",
    "markdown": "# Tutorial 1: Evidence and probability foundations {#b-ep01}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Tutorial 1, you can</span>\n\n- distinguish data, events, random variables, and distributions;\n- apply probability rules to the Shark Tank record-selection experiment;\n- calculate and interpret a Bernoulli PMF, CDF, and expectation;\n- calculate a variance and standard deviation from a small PMF;\n- write a concise interpretation of supplied R output.\n:::\n\nTutorials are **exam preparation sessions**: every task below follows the\nformat of the final exam. The standing routine for each task is the same ---\nthe TA states the task, pairs work on it first for a few minutes with AI use\nallowed, and the solution is then discussed in plenary, starting from the\npair attempts.\n\n::: {.course-phase .phase-before}\n\n## Before class\n\nBring your after-class work from Lectures 1--3. Without reopening the\nchapters, complete these definitions:\n\n1. An observational unit is ...\n2. An event is ...\n3. A random variable is ...\n4. A PMF is ...\n5. The variance of a random variable averages ...\n\nUse the cumulative formula sheet through Lecture 3.\n\nReview [Mathematics Refresher: sets, fractions, and\nsums](../resources/math-refresher.html) if the notation is slowing you down.\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\n1. An observational unit is the entity represented by one row of the data.\n2. An event is a specified subset of the sample space.\n3. A random variable is a real-valued function on the sample space.\n4. A PMF assigns probability $P(X=x)$ to each value in the support of a\n   discrete random variable; its masses are non-negative and sum to 1.\n5. Variance averages squared deviations from the variable's mean:\n   $\\operatorname{Var}(X)=E\\!\\left[(X-E[X])^2\\right]$.\n:::\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In class\n\nAttempt each task before opening its answer. A complete written answer should\nname the quantity, show the calculation, report the value and units, interpret\nit in context, and state an important model or measurement boundary.\n\nAll tasks use the Shark Tank teaching file. Load it once:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\n```\n:::\n\n\n\n\n### Task 1 --- Data and measurement\n\nR reports:\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                    rows                  columns                    deals \n            1441.0000000               19.0000000              882.0000000 \n         deal_proportion median_description_words \n               0.6120749                5.0000000 \n```\n\n\n:::\n:::\n\n\n\n\n1. What is the observational unit?\n2. Verify the deal proportion from 882 deals and 559 non-deals.\n3. Explain why the mean of `deal_on_show` is a proportion.\n4. Evaluate: \"The data contain 1,441 successful companies.\"\n5. What exactly does `description_words` measure?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nOne row is one recorded televised pitch. There are $882+559=1441$ records and\n$882/1441\\approx0.612$, so 61.2% reached an on-air agreement. The mean of a\n0/1 indicator equals the share coded 1 because its sum counts the 1s.\n\"Successful companies\" is incorrect: the outcome is an agreement made on the\nshow, not completed funding or later venture performance. Word count\ndescribes the written text in the source dataset, not the spoken pitch.\n:::\n\n### Task 2 --- Events and probability rules\n\nThe experiment selects one of the 1,441 records uniformly. The two events are\nbuilt exactly as in Lecture 2:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD <- sharks$deal_on_show == 1   # on-air deal\nL <- sharks$season >= 9         # late season: Seasons 9-16\n```\n:::\n\n\n\n\nR reports:\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n      P_D       P_L P_D_and_L \n0.6120749 0.5093685 0.3504511 \n```\n\n\n:::\n:::\n\n\n\n\n1. Define $\\Omega$, and distinguish an outcome from event $D$.\n2. Translate $D^c$, $D\\cap L$, and $D\\cup L$ into words.\n3. Calculate $P(D^c)$.\n4. Calculate $P(D\\cup L)$ using the addition rule.\n5. Explain why these probabilities do not automatically apply to a future US\n   entrepreneur.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe sample space is the set of 1,441 complete pitch records; one selected\nrecord is an outcome, while $D$ is the subset of 882 deal records. The\ncomplement is no on-air deal, the intersection is a late-season deal, and the\nunion is late-season, deal, or both. $P(D^c)=1-882/1441=559/1441\\approx0.388$.\nThe union is $P(D)+P(L)-P(D\\cap L)\\approx0.771$. Future use requires a\ndefined target population and comparable selection, time period, and outcome.\n:::\n\n### Task 3 --- PMF, CDF, and expectation\n\nLet $X=1$ for an on-air deal and $X=0$ otherwise. Use $p=882/1441$.\n\n1. Write the PMF and verify that its masses sum to 1.\n2. Write the full piecewise CDF $F_X(a)$.\n3. Calculate $E[X]$ from the PMF.\n4. Explain why $E[X]$ equals the observed proportion of 1s.\n5. Explain the difference between the random variable $X$ and a realised\n   value $x=1$.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$$\np_X(0)=1-p,\\qquad p_X(1)=p,\n$$\n\nand the masses total $1-p+p=1$.\n\n$$\nF_X(a)=\n\\begin{cases}\n0,&a<0,\\\\\n1-p,&0\\le a<1,\\\\\n1,&a\\ge1.\n\\end{cases}\n$$\n\nThe expectation is $E[X]=0(1-p)+1p=p\\approx0.612$. Because the indicator\ncontains 882 ones among 1,441 observations, its mean is also $882/1441$.\n$X$ is the mapping defined before selection; $x=1$ is one possible\nrealised value.\n:::\n\n### Task 4 --- Variance from a small PMF\n\nA venture studio models $N$, the number of investors who make an offer to one\nof its startups, with the PMF\n\n| $n$ | 0 | 1 | 2 |\n|---|---:|---:|---:|\n| $p_N(n)$ | 0.5 | 0.3 | 0.2 |\n\n1. Calculate $E[N]$.\n2. Calculate $\\operatorname{Var}(N)$ from the definition\n   $E\\!\\left[(N-E[N])^2\\right]$.\n3. Verify the result with the computational form\n   $E[N^2]-\\left(E[N]\\right)^2$.\n4. Report the standard deviation with its unit, and state in one sentence\n   what it measures here.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\n$E[N]=0(0.5)+1(0.3)+2(0.2)=0.7$ offers.\n\nDefinition form:\n$$\n\\operatorname{Var}(N)=(0-0.7)^2(0.5)+(1-0.7)^2(0.3)+(2-0.7)^2(0.2)\n=0.245+0.027+0.338=0.61.\n$$\n\nComputational form: $E[N^2]=0^2(0.5)+1^2(0.3)+2^2(0.2)=1.1$, so\n$\\operatorname{Var}(N)=1.1-0.7^2=1.1-0.49=0.61$. The two routes agree.\n\nThe standard deviation is $\\sqrt{0.61}\\approx0.78$ offers. It measures the\ntypical distance of the realised number of offers from the mean of 0.7,\nin the original unit (offers), whereas the variance is in squared offers.\n:::\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n### Timed individual practice --- 10 minutes\n\nAn output block describes word count:\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n     mean    median   minimum   maximum \n 4.995142  5.000000  1.000000 13.000000 \n```\n\n\n:::\n:::\n\n\n\n\nWrite no more than 100 words. Compare mean and median, calculate the range,\nand state the measurement boundary. Then explain which value equals the\nexpectation if the empirical distribution gives mass $1/1441$ to each record.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nThe written descriptions have a mean length of about 5.0 words and a median\nof 5 words. Their range is $13-1=12$ words. The thin upper tail is consistent\nwith the mildly right-skewed histogram seen in Lecture 1. If each record\nreceives probability $1/1441$, the empirical expectation is the mean, about\n5.0 words. These values describe written dataset text, not spoken-pitch\nlength or quality.\n:::\n\n### Check your understanding\n\nComplete from memory:\n\n1. An event is ...\n2. A PMF must ...\n3. A CDF at $a$ reports ...\n4. Expectation is ...\n5. Variance is ... and its square root is ...\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. An event is a specified subset of the sample space.\n2. A PMF is non-negative and sums to 1 over the support.\n3. $F_X(a)=P(X\\le a)$.\n4. $E[X]=\\sum_x x\\, p_X(x)$, the probability-weighted average of the possible\n   values.\n5. Variance is the probability-weighted average of squared deviations from\n   the mean, $\\operatorname{Var}(X)=E[X^2]-\\left(E[X]\\right)^2$; its square\n   root is the standard deviation, in the variable's original unit.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA venture --- or any business you know well. Pick one\nuncertain count that matters for it (customers who sign up in a week, offers\nreceived, orders returned), and write two sentences: first sketch a small PMF\nfor it (three or four values with rough probabilities), then say what its\nexpectation and standard deviation would tell you about a real decision.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"Weekly catering requests: 0 with probability 0.4, 1 with 0.4, 2 with 0.15, and 3 with 0.05, so I expect about 0.85 requests per week. The standard deviation tells me whether a weekend helper is justified --- with high spread, some weeks genuinely need one even though the average says no.\"\n:::\n\nYou can discuss this task --- and any other task in this tutorial --- with\n**Tilly**, the course AI assistant on Canvas.\n::::\n\nContinue to Lecture 4: Conditioning, total probability, Bayes, and\nindependence.\n\n:::\n",
    "supporting": [
      "t01-exam-prep_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}