{
  "hash": "a7f00dc185ea0ff5e340a7d484a60b57",
  "result": {
    "engine": "knitr",
    "markdown": "# Tutorial 2: Multiple regression and extensions {#i-ep02}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Tutorial 2, you can</span>\n\n- fit and interpret multiple regression in R;\n- test individual and grouped coefficients against zero;\n- interpret dummy, interaction, and polynomial terms correctly;\n- compare nested models with a partial F-test;\n- write a complete TestVision-ready analysis with design limits.\n:::\n\nTutorials are **exam preparation sessions**: every task below follows the\nformat of the final exam. The standing routine for each task is the same ---\nthe TA states the task, pairs work on it first for a few minutes with AI use\nallowed, and the solution is then discussed in plenary, starting from the\npair attempts.\n\nOne note on the order. The tasks run in course order: Task 1 rests on\nLecture 4, Task 2 on Lecture 5, and Tasks 3--4 on yesterday's Lecture 6.\nThis is deliberate --- the tutorial meets the day after Lecture 6, so you\nwarm up on settled material before testing what you learned yesterday.\n\n::: {.course-phase .phase-before}\n\n## Before class\n\nComplete the after-class practice from Lectures 4--6. Use the complete\n[QM Intermediate Code Sheet](#intermediate-code-sheet) while working, and\nreview\n[Mathematics Refresher: multivariable equations, indicators, products, and powers](../resources/math-refresher.html)\nif needed.\n\nComplete from memory:\n\n1. A multiple-regression slope is interpreted while ...\n2. A dummy coefficient compares ...\n3. An interaction coefficient is a difference in ...\n4. A partial F-test compares ...\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\n1. Holding the other included predictors fixed.\n2. A category with the named reference category.\n3. Slopes.\n4. A reduced nested model with a complete model on the same observations.\n:::\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In class\n\nAttempt each task in R before opening the answer. All tasks use the Shark\nTank teaching file and the running money unit of **thousands of dollars**.\nBuild the analysis data once --- the same constructions as Lectures 4--6:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nsharks$ask_1k <- sharks$ask_amount_usd / 1000\nknown_gender <- subset(sharks, pitcher_gender_group != \"unknown\")\nknown_gender$gender <- relevel(factor(known_gender$pitcher_gender_group),\n                               ref = \"all_men\")\nknown_gender$ask_1k <- known_gender$ask_amount_usd / 1000\nknown_gender$women <- as.integer(\n  known_gender$pitcher_gender_group %in% c(\"all_women\", \"mixed\")\n)\nknown_gender$season_c <- known_gender$season - mean(known_gender$season)\n```\n:::\n\n\n\n\n### Task 1 --- Multiple-regression coefficients (Lecture 4)\n\nFit:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(\n  equity_offered_pct ~ season + ask_1k + description_words,\n  data = sharks\n)\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = equity_offered_pct ~ season + ask_1k + description_words, \n    data = sharks)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-15.295  -4.776  -1.283   3.288  82.106 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       22.0249310  0.8878522  24.807  < 2e-16 ***\nseason            -0.8361515  0.0509825 -16.401  < 2e-16 ***\nask_1k            -0.0028975  0.0005771  -5.021 5.79e-07 ***\ndescription_words -0.1283379  0.1137527  -1.128    0.259    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.619 on 1437 degrees of freedom\nMultiple R-squared:  0.1876,\tAdjusted R-squared:  0.1859 \nF-statistic: 110.6 on 3 and 1437 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n1. Interpret all three slopes with units and conditioning.\n2. Identify which 95% coefficient interval includes zero.\n3. Interpret adjusted $R^2$ and the overall F-test.\n4. State two threats to causal interpretation.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nAt fixed values of the other included predictors, among the 1,441 recorded\npitches: one later season is associated with about 0.836 percentage points\nless initial equity; an extra \\$1,000 requested with about 0.0029\npercentage points less equity (about 0.29 points per \\$100,000); and one\nadditional description word with about 0.128 percentage points less equity.\nThe description-word interval, about $(-0.351,\\; 0.095)$, includes zero.\nAdjusted $R^2\\approx0.186$, and the overall F-test\n($F\\approx110.6$ on 3 and 1437 df) rejects the joint zero-slope null.\nSelection into the show, unmeasured venture quality, reverse relationships,\nand measurement choices are all possible causal threats.\n:::\n\n### Task 2 --- Dummy variables and a partial F-test (Lecture 5)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreduced <- lm(equity_offered_pct ~ season + ask_1k,\n              data = known_gender)\ncomplete <- lm(equity_offered_pct ~ season + ask_1k + gender,\n               data = known_gender)\nsummary(complete)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = equity_offered_pct ~ season + ask_1k + gender, data = known_gender)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-16.118  -4.778  -1.100   3.220  82.590 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     20.8388333  0.5064929  41.143  < 2e-16 ***\nseason          -0.8238940  0.0477959 -17.238  < 2e-16 ***\nask_1k          -0.0026613  0.0005822  -4.571 5.28e-06 ***\ngenderall_women  1.2835231  0.4810241   2.668  0.00771 ** \ngendermixed      0.1209343  0.5411539   0.223  0.82320    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.612 on 1429 degrees of freedom\nMultiple R-squared:  0.1913,\tAdjusted R-squared:  0.189 \nF-statistic: 84.49 on 4 and 1429 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(reduced, complete)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: equity_offered_pct ~ season + ask_1k\nModel 2: equity_offered_pct ~ season + ask_1k + gender\n  Res.Df   RSS Df Sum of Sq      F Pr(>F)  \n1   1431 83228                             \n2   1429 82792  2    436.25 3.7649 0.0234 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n1. Name the reference category.\n2. Interpret both dummy coefficients.\n3. State and decide the partial F-test.\n4. Explain why the partial test and the individual t-tests answer different\n   questions.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe reference is all-men. At the same season and requested amount,\nall-women presenting teams are fitted to offer about 1.28 equity percentage\npoints more, and mixed teams about 0.12 points more, than all-men teams ---\npercentage points, not percent. The partial null is that both dummy\ncoefficients equal zero; $F\\approx3.76$, p $\\approx$ 0.023, so reject at\n5%: the terms are jointly useful even though the mixed dummy's own t-test\n(p $\\approx$ 0.82) is far from significant. The F-test asks whether the\npair improves the model together; each t-test asks about one\nreference-group contrast. The broad source coding and observational design\nprohibit a causal gender claim.\n:::\n\n### Task 3 --- Interaction (Lecture 6)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_interaction <- lm(\n  equity_offered_pct ~ season_c * women + ask_1k,\n  data = known_gender\n)\nsummary(m_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = equity_offered_pct ~ season_c * women + ask_1k, \n    data = known_gender)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-15.871  -4.742  -1.290   3.412  82.689 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    13.6247907  0.3354522  40.616  < 2e-16 ***\nseason_c       -0.7993817  0.0663226 -12.053  < 2e-16 ***\nwomen           0.8069665  0.4117061   1.960   0.0502 .  \nask_1k         -0.0026776  0.0005834  -4.590 4.83e-06 ***\nseason_c:women -0.0614594  0.0955667  -0.643   0.5203    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.62 on 1429 degrees of freedom\nMultiple R-squared:  0.1894,\tAdjusted R-squared:  0.1871 \nF-statistic: 83.47 on 4 and 1429 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n1. Write the fitted line for `women = 0` and `women = 1` at a fixed\n   request.\n2. Calculate both season slopes.\n3. Interpret the interaction estimate and p-value without overclaiming in\n   either direction.\n4. Explain the role of centering.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nFor all-men teams the season slope is about $-0.799$ percentage points per\nseason; for teams with women represented it is\n$-0.799-0.061=-0.861$. The estimated slope difference is $-0.061$\npercentage points per season with p $\\approx$ 0.520: this model provides no\nevidence of different season trends between the two source-defined groups\n--- and no proof of equal trends, since the estimate is imprecise.\nCentering makes the lower-order group coefficient compare the groups at the\naverage season (about 8.8) instead of at the unobserved Season 0; it\nchanges neither the fitted values nor the interaction estimate.\n:::\n\n### Task 4 --- Polynomial term (Lecture 6)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_linear <- lm(equity_offered_pct ~ season + ask_1k, data = sharks)\nm_quadratic <- lm(\n  equity_offered_pct ~ season + I(season^2) + ask_1k,\n  data = sharks\n)\nsummary(m_quadratic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = equity_offered_pct ~ season + I(season^2) + ask_1k, \n    data = sharks)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-16.154  -4.549  -1.011   3.390  82.000 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 24.171681   0.820566  29.457  < 2e-16 ***\nseason      -1.713233   0.205669  -8.330  < 2e-16 ***\nI(season^2)  0.051034   0.011369   4.489 7.74e-06 ***\nask_1k      -0.002711   0.000574  -4.723 2.56e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.57 on 1437 degrees of freedom\nMultiple R-squared:  0.1981,\tAdjusted R-squared:  0.1965 \nF-statistic: 118.3 on 3 and 1437 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(m_linear, m_quadratic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: equity_offered_pct ~ season + ask_1k\nModel 2: equity_offered_pct ~ season + I(season^2) + ask_1k\n  Res.Df   RSS Df Sum of Sq      F    Pr(>F)    \n1   1438 83493                                  \n2   1437 82338  1    1154.5 20.149 7.737e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n1. Why must `I(season^2)` be used in the R formula?\n2. Decide whether the quadratic term adds fit under the classical test.\n3. Calculate the fitted change from Season 10 to Season 11.\n4. State why the curve should not be extrapolated beyond Season 16.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n`I()` tells R to square arithmetically rather than read `^` as formula\nsyntax. The partial F-test gives $F\\approx20.1$ with p $<$ 0.001, so the\nquadratic term adds detectable fit. With $b_1\\approx-1.713$ and\n$b_2\\approx0.051$, the change from Season 10 to 11 is\n$b_1+b_2(2\\times10+1)=b_1+21b_2\\approx-0.64$ percentage points --- never\nread $b_1$ alone while the squared term is in the model. Beyond Season 16\nthe fitted parabola turns upward with no data support; polynomials can\nbehave sharply outside the observed range.\n:::\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n### Timed integrated task --- 30 minutes\n\nDevelop one model of `equity_offered_pct` using season, the requested\namount in $1,000s, the three known source gender groups, and one justified\nextension.\n\nYour submission must include:\n\n1. a precise research question;\n2. reproducible data preparation;\n3. one pre-model visual;\n4. the R formula and model summary;\n5. coefficient interpretations with units and reference groups;\n6. an individual t-test and an overall or partial F-test;\n7. $R^2$, adjusted $R^2$, and residual diagnostics;\n8. one graph of fitted conditional predictions;\n9. a 150-word conclusion separating association, uncertainty, and causal\n   limits.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model structure\n\nA defensible solution could fit\n\n```r\nm <- lm(\n  equity_offered_pct ~ season * gender + ask_1k,\n  data = known_gender\n)\n```\n\nor a quadratic-season model with group dummies. Keep lower-order terms,\nname the reference group, interpret combined slopes or fitted contrasts,\ncompare a nested reduced model with `anova(reduced, complete)`, inspect\nresiduals (including `rstandard()` and Cook's distance), and plot\npredictions within Seasons 1--16. The conclusion must state that the\nsource's broad presenter classification and the selected televised records\ndo not identify a causal effect of gender or season.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA3 venture --- or any business you know well. Sketch, in\ntwo sentences, the integrated analysis you would actually run on its data:\nfirst name the outcome, two predictors, and the one extension (a dummy set,\nan interaction, or a quadratic) that a real question motivates, then say\nwhich single caveat --- selection, measurement, or omitted variables ---\nwould headline your 150-word conclusion. There is no wrong answer; the\npoint is noticing that you now own the entire pipeline.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"Outcome: weekly orders; predictors: ad spend and price, plus an exam-week dummy interacted with ad spend, because I believe ads work mainly when students are on campus. The headlining caveat is omitted variables: weather drives both my flyer effort and campus foot traffic, and nothing in my data measures it.\"\n:::\n\nYou can discuss this task --- and any other task in this tutorial --- with\n**Tilly**, the course AI assistant on Canvas: ask it to referee your\ntwo-sentence design before you invest a weekend in the data.\n::::\n\nQM Intermediate is complete. Review the\n[QM Intermediate Code Sheet](#intermediate-code-sheet), attempt the\n[QM Intermediate Mock Exam](#intermediate-mock-exam), then return to the\n[R Refresher](../resources/r-refresher.html),\n[Mathematics Refresher](../resources/math-refresher.html), or the\n[External Video Guide](../resources/video-guide.html) whenever you need a\ntargeted review.\n\n:::\n",
    "supporting": [
      "t02-exam-prep_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}