{
  "hash": "2b4f9820c7a94619132cf7d67ab8ec8b",
  "result": {
    "engine": "knitr",
    "markdown": "# Tutorial 4: Inference and tests against zero {#b-ep04}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Tutorial 4, you can</span>\n\n- construct and interpret intervals for a mean and a proportion\n- complete two-sided tests of zero-valued contrasts\n- connect a test decision with its confidence interval\n- interpret the t distribution, degrees of freedom, errors, and power\n- read a regression coefficient test without claiming more than it shows.\n:::\n\nTutorials are **exam preparation sessions**. Every task below follows the\nformat of the final exam. You first try each task in pairs. You may use AI for this, following\nAttempt, Ask, Verify, Explain. Then the solution is discussed together.\n\nThis tutorial covers Lectures 9--10: the t distribution and confidence\nintervals from Lecture 9, and the p-value, test decisions, errors, and power\nfrom Lecture 10. All tests are two-sided.\n\n::: {.course-phase .phase-before}\n\n## Before class\n\nBring your after-class work from Lectures 9 and 10. Review\n[Mathematics Refresher: intervals, degrees of freedom, and\nstandardisation](../resources/math-refresher.html) if needed.\n\nUse the cumulative formula sheet through Lecture 10.\n\nWrite from memory:\n\n1. the t confidence-interval form\n2. the t statistic for testing a mean contrast against zero\n3. why the critical value comes from the t distribution rather than the\n   normal, and the meaning of $df=n-1$\n4. the definition of a two-sided p-value\n5. the 95%-interval/5%-test decision link.\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\n1. $\\widehat\\delta\\pm t_{0.975,\\,n-1}\\widehat{\\operatorname{SE}}(\\widehat\\delta)$.\n2. $T=\\widehat\\delta/\\widehat{\\operatorname{SE}}(\\widehat\\delta)$.\n3. The population SD is replaced by the sample SD $S$, which itself varies\n   across samples. The heavier tails of the t distribution account for that\n   extra uncertainty. Once the sample mean is estimated, only $n-1$\n   deviations vary freely when spread is estimated.\n4. Under $H_0$, the probability of a statistic at least as far from zero\n   as the observed statistic in either direction.\n5. For a two-sided t test and the t interval with the same SE, reject\n   $H_0$ at 5% exactly when the 95% interval excludes zero.\n:::\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In the tutorial\n\nTry every task before you open its answer. Every conclusion must name the\nparameter, the units, the population, the direction, and the limits of the\nevidence.\n\nTasks 1, 2, and 5 use the random sample of 100 pitches (seed 123) and the\nequity gap, built as in Lectures 7 and 9:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nset.seed(123)\nsample_rows <- sample(seq_len(nrow(sharks)), size = 100, replace = FALSE)\npitch_sample <- sharks[sample_rows, ]\npitch_sample$equity_gap_pp <- pitch_sample$equity_offered_pct - 15\n```\n:::\n\n\n\n\n### Task 1: Mean contrast\n\nFor the sample of 100 pitches, define the gap between the equity offered\n(`equity_offered_pct`) and the benchmark of 15 percentage points:\n\n$$\nG=\\text{equity offered}-15.\n$$\n\n1. Calculate $\\bar g$, $s_g$, the SE, and the degrees of freedom.\n2. Construct a 95% interval for $\\delta=E[G]$.\n3. Test $H_0:\\delta=0$ against $H_1:\\delta\\ne0$.\n4. Explain why the interval and test agree.\n5. Explain why the critical value comes from `qt(0.975, df = 99)` rather\n   than `qnorm(0.975)`.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng <- pitch_sample$equity_gap_pp\nn <- length(g)\ng_bar <- mean(g)\ns_g <- sd(g)\nse_g <- s_g / sqrt(n)\ncritical <- qt(0.975, df = n - 1)\nci_g <- g_bar + c(-1, 1) * critical * se_g\nt_value <- g_bar / se_g\np_value <- 2 * pt(-abs(t_value), df = n - 1)\n\nc(estimate = g_bar, sd = s_g, se = se_g, df = n - 1,\n  lower = ci_g[1], upper = ci_g[2],\n  t = t_value, p_value = p_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    estimate           sd           se           df        lower        upper \n-2.240000000  7.707886555  0.770788656 99.000000000 -3.769411916 -0.710588084 \n           t      p_value \n-2.906114385  0.004515396 \n```\n\n\n:::\n:::\n\n\n\n\n$\\bar g=-2.24$, $s_g=7.7079$, $\\widehat{\\operatorname{SE}}=0.7708$, and\n$df=99$, all in percentage points except $df$. The 95% interval is\napproximately $(-3.77,\\,-0.71)$. The statistic is $t=-2.906$ and the\ntwo-sided p-value is about 0.0045, so reject the null hypothesis of a zero\ngap. The mean equity offered in the recorded-pitch frame differs from 15\npercentage points, and the negative estimate places it below. The interval\nexcludes zero because it uses the same t distribution and the same SE as the\ntest. The critical value is a t quantile because $\\sigma$ was estimated by\n$s_g$. With $df=99$ the value 1.984 is only slightly above the normal 1.96,\nbut the t value is the correct choice.\n:::\n\n### Task 2: Proportion contrast\n\nDefine $\\delta_p=p-0.50$, where $p$ is the proportion of pitches that end\nwith a deal (`deal_on_show`) among all 1,441 recorded pitches. Use the same\nsample of 100 pitches.\n\n1. Estimate $\\delta_p$.\n2. Check the success-failure rule and test $H_0:\\delta_p=0$ against\n   $H_1:\\delta_p\\ne0$ with the large-sample z test.\n3. Construct the large-sample 95% interval for $p$ and translate it into an\n   interval for $\\delta_p$.\n4. State why the SE of the test and the SE of the interval differ.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- nrow(pitch_sample)\nphat <- mean(pitch_sample$deal_on_show)\np0 <- 0.50\ndelta_hat <- phat - p0\n\nnull_se <- sqrt(p0 * (1 - p0) / n)\nz_value <- delta_hat / null_se\np_value <- 2 * pnorm(-abs(z_value))\n\nestimated_se <- sqrt(phat * (1 - phat) / n)\nci_p <- phat + c(-1, 1) * 1.96 * estimated_se\nci_delta <- ci_p - p0\n\nc(phat = phat, estimated_gap = delta_hat,\n  z = z_value, p_value = p_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         phat estimated_gap             z       p_value \n  0.640000000   0.140000000   2.800000000   0.005110261 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(proportion_lower = ci_p[1], proportion_upper = ci_p[2],\n  gap_lower = ci_delta[1], gap_upper = ci_delta[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nproportion_lower proportion_upper        gap_lower        gap_upper \n         0.54592          0.73408          0.04592          0.23408 \n```\n\n\n:::\n:::\n\n\n\n\n$\\hat p=0.64$, so $\\widehat\\delta_p=0.14$. The success-failure rule holds\nunder the null: $np_0=n(1-p_0)=50\\ge10$. Under the null,\n$\\operatorname{SE}_0=0.05$, $z=2.80$, and the two-sided p-value is about\n0.005. Reject the null hypothesis of a zero gap. The deal proportion in the\nrecorded-pitch frame differs from 50%, and the positive estimate places it\nabove. The proportion interval is approximately $(0.546,\\,0.734)$, which\ncorresponds to a gap interval of $(0.046,\\,0.234)$. The test calculates the\nSE with $p_0$, because it asks how surprising the sample would be if $H_0$\nwere true. The interval does not assume $H_0$, so it calculates the SE with\n$\\hat p$.\n:::\n\n### Task 3: Read a regression coefficient row\n\nSuppose a regression of the equity offered (in percentage points) on the\namount requested reports this row:\n\n| Predictor | Estimate | SE | t | p-value | 95% interval |\n|---|---:|---:|---:|---:|---:|\n| Amount requested, per $100,000 | -0.290 | 0.058 | -5.00 | <0.001 | (-0.404, -0.176) |\n\n1. State the tested hypotheses.\n2. Explain every number in units.\n3. Give the statistical conclusion at 5%.\n4. State two claims the row cannot justify.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nWrite $\\beta_{ask}$ for the population coefficient of the amount requested.\nThe test is $H_0:\\beta_{ask}=0$ against $H_1:\\beta_{ask}\\ne0$. The estimate\n$\\hat\\beta_{ask}=-0.290$ says that another \\$100,000 requested goes together\nwith 0.290 percentage points less equity offered. The SE, 0.058, measures\nthe sampling uncertainty of the estimate in the same units. The statistic is\n$-0.290/0.058=-5.00$. The interval says that plausible values of the\ncoefficient run from $-0.404$ to $-0.176$ percentage points per \\$100,000.\nThe p-value is below 0.001 and the 95% interval excludes zero, so reject the\nnull hypothesis of a zero coefficient at 5%. The row alone does not show\nthat asking for more money causes lower equity offers, and it does not show\nthat the conditions of the model hold.\n:::\n\n### Task 4: Errors and power\n\nFor Task 3:\n\n1. describe a Type I error\n2. describe a Type II error\n3. state how a larger sample affects SE and power\n4. explain why raising $\\alpha$ is a trade-off rather than a free gain.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nA Type I error is concluding that the population coefficient of the amount\nrequested differs from zero when it equals zero. A Type II error is not\nrejecting $H_0$ when the population coefficient is in fact not zero. A\nlarger independent sample usually reduces the SE and raises power. Raising\n$\\alpha$ also raises power, but it raises the probability of a Type I error\nat the same time. A wider rejection region leads to more rejections, both\nwhen $H_1$ is true and when $H_0$ is true.\n:::\n\n### Task 5 (optional): One-sided alternatives and the exam convention\n\nThis task belongs to the optional box on one-sided alternatives in\nLecture 10. It is not examined.\n\nTask 1 gave $t=-2.906$ with $df=99$ and a two-sided p-value of about\n0.0045.\n\n1. Give the p-values for the one-sided alternatives $H_1:\\delta<0$ and\n   $H_1:\\delta>0$, each fixed before the data were inspected.\n2. A student first sees the negative estimate and then proposes to report\n   the left-sided p-value \"since the direction is now known\". Explain the\n   error.\n3. State the convention of this course for tests and one reason for it.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nLeft-sided: $P(T_{99}\\le-2.906)\\approx0.0023$, half of the two-sided\np-value. Right-sided: $P(T_{99}\\ge-2.906)\\approx0.9977$, one minus that\nhalf. If the tail is chosen after seeing the estimate, the 5% always lies on\nthe side where the estimate happens to fall. The true Type I error rate is\nthen about 10%, not 5%. A one-sided alternative must follow from the\nresearch question and be fixed before the sample is inspected. The\nconvention of this course: all tests are two-sided. In business questions a\ndifference in either direction usually matters, and the convention leaves\nno room for choosing the tail afterwards.\n:::\n\n### Task 6: Repair the conclusion\n\nThe following conclusion about the row of Task 3 contains two errors. Find\nthem and write a better conclusion.\n\n> The coefficient is significant, so asking for more money causes founders\n> to offer less equity, and there is less than a 0.1% chance that the null\n> is true.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe p-value is not the probability that the null hypothesis is true, and a\nsignificant result does not show a cause. A better conclusion: \"Another\n\\$100,000 requested goes together with about 0.29 percentage points less\nequity offered (95% interval from 0.18 to 0.40 points less). If the\npopulation coefficient were zero, an estimate this far from zero would occur\nin fewer than 0.1% of samples. The pitches were not assigned to amounts at\nrandom, so this is an association, not a causal effect.\"\n:::\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n### Timed individual practice: 25 minutes\n\nSolve this task alone and with a timer, under exam conditions: no notes, no\nAI, formula sheet only. The example is invented. A random sample of 81\ncustomers of a subscription service gives a mean spending of 42 euros with\nsample SD 9 euros. Of the 81 customers, 54 renew their subscription.\n\n1. Let $\\mu$ be the population mean spending and define\n   $\\delta_\\mu=\\mu-40$. Construct a 95% interval for $\\delta_\\mu$ (use\n   $t_{0.975,80}\\approx1.99$) and test $H_0:\\delta_\\mu=0$ against\n   $H_1:\\delta_\\mu\\ne0$ at 5%. Supplied value: the two-sided p-value for\n   $t=2.00$ with $df=80$ is 0.049.\n2. Let $p$ be the population renewal proportion and define\n   $\\delta_p=p-0.60$. Construct the large-sample 95% interval for $p$ and\n   test $H_0:\\delta_p=0$ against $H_1:\\delta_p\\ne0$ at 5%. Supplied value:\n   the two-sided p-value for $z=1.22$ is 0.22.\n3. State the Type I error for each test.\n4. Explain why the mean result is only just significant although the\n   estimated mean difference is 2 euros.\n5. Write a report of six sentences. Give one sentence each to the estimate,\n   the uncertainty, the decision, the practical importance, the population,\n   and causality.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nFor the mean, $\\widehat\\delta_\\mu=2$ euros,\n$\\widehat{\\operatorname{SE}}=9/\\sqrt{81}=1$ euro, and $df=80$. With\n$t_{0.975,80}\\approx1.99$, the gap interval is approximately\n$(0.01,\\,3.99)$ euros, which is the same as a mean interval of\n$(40.01,\\,43.99)$ euros. The statistic is $t=2.00$ and the two-sided\np-value is about 0.049, so reject the null hypothesis of a zero gap, but\nonly just.\n\nFor renewal, $\\hat p=54/81=0.667$. The estimated gap is 0.067. The\nlarge-sample interval for the proportion is approximately\n$(0.564,\\,0.769)$, so the gap interval is $(-0.036,\\,0.169)$. The\nsuccess-failure rule holds under $H_0:p=0.60$, because $81(0.60)=48.6$ and\n$81(0.40)=32.4$ are both at least 10. Then\n$\\operatorname{SE}_0\\approx0.0544$ and $z\\approx1.22$. The two-sided\np-value, about 0.22, is above 0.05. Do not reject $H_0$.\n\nA Type I error would be to claim a non-zero gap in mean spending when\n$\\mu=40$, or a non-zero gap in the renewal proportion when $p=0.60$. The\nmean result is only just significant because the estimate of 2 euros lies\nalmost exactly two SEs from zero. The p-value depends on the estimate\nrelative to its SE, not on the size of the estimate alone. A complete\nreport must also say whether a difference of 2 euros (5% of the benchmark of\n40 euros) matters, and whether the sampling design supports a claim about\nthe intended population. Neither test shows a cause.\n\nA model report for the mean: \"The 81 sampled customers spend 42 euros on\naverage, 2 euros above the benchmark of 40. The 95% interval for the mean\nruns from 40.01 to 43.99 euros. The test rejects a zero gap at 5%, but only\njust (p-value 0.049). A gap of 2 euros is 5% of the benchmark, so its\nimportance depends on the margin per customer. The result holds for the\npopulation from which the customers were drawn at random. It does not show\nwhat causes the higher spending.\"\n:::\n\n### Check your understanding\n\nComplete from memory:\n\n1. A 95% confidence interval is correctly described as ...\n2. Reject $H_0$ at 5% exactly when the matched 95% interval ...\n3. A Type I error is .... Power is ...\n4. \"Do not reject $H_0$\" is different from \"accept $H_0$\" because ...\n5. A regression coefficient row tests ...\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. The result of a procedure that captures the fixed parameter in about\n   95% of random samples. It is never \"a 95% chance that the parameter is\n   inside\".\n2. Excludes zero (for a two-sided test and an interval that use the same\n   SE).\n3. Rejecting $H_0$ when it is true. The probability of rejecting $H_0$\n   when $H_1$ is true.\n4. A result that is not significant may only be too imprecise to tell a\n   real non-zero parameter from zero.\n5. $H_0:\\beta_j=0$ against $H_1:\\beta_j\\ne0$.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA venture, or any business you know well. Take the one\nclaim about it that you would most like to defend in front of an investor,\nand write two sentences: first phrase it as a zero-contrast test with a\nrealistic sample and state which error, the false alarm or the missed\neffect, would cost you more, then say what interval outcome would make\nyou change a real decision rather than just a slide.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"The claim I must defend: average order value equals the €9 break-even, tested two-sided on my next 150 orders. The missed effect would cost me more, walking away from a viable business, so an interval sitting entirely above €9 would make me order packaging stock, not just update a slide.\"\n:::\n\nYou can discuss this task, and any other task in this tutorial, with\n**Tilly**, the course AI assistant.\n::::\n\nQM Basic is complete. Next, use the [QM Basic Formula Sheet](formula-sheet.qmd) and attempt the\n[QM Basic Mock Exam](mock-exam.qmd). Continue to QM Intermediate when that course begins.\n\n:::\n",
    "supporting": [
      "t04-exam-prep_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}