{
  "hash": "e17b2ec1ecbdb5dc1c68804d1c502294",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 9: The t distribution, confidence intervals, and the two-sided test {#b09}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 9, you can</span>\n\n- explain why estimating the population SD leads to a t distribution with\n  $n-1$ degrees of freedom, and use its critical values;\n- construct a t confidence interval for a population mean;\n- express comparison with a benchmark as a parameter equal to zero;\n- state a two-sided null and alternative hypothesis;\n- calculate and interpret a t statistic and a two-sided p-value;\n- connect a 95% confidence interval to a 5% two-sided test;\n- state correctly what \"95% confidence\" is a property of.\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">A common pitch-deck rule of thumb says founders offer investors about 15 percent equity. Our data can put such a benchmark to the test --- if we account honestly for sampling noise.</p>\n\nIs the typical initial equity ask in the recorded-pitch frame really\ndifferent from 15 percent?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 30 minutes.</span>\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation (20 minutes)</span><br>\nWatch <a href=\"https://www.youtube.com/watch?v=NInNhFm046w\">Confidence\nIntervals</a>,\n<a href=\"https://www.youtube.com/watch?v=MzvRQFYUEFU\">Confidence Intervals\nWhen the Variance Is Unknown</a>, and\n<a href=\"https://www.youtube.com/watch?v=ti9NFdjf3sM\">Introduction to\nHypothesis Testing</a>. Focus on repeated-sampling coverage, the t reference\ndistribution, and the role of the null value. All links are also listed in\nthe <a href=\"../resources/video-guide.html\">External Video Guide</a>.\n</div>\n\n**Reactivate (5 minutes).** Let $X$ be initial equity offered and define the\n**equity gap**\n\n$$\nD = X - 15.\n$$\n\nWrite two-sided hypotheses for the question: \"Does population mean initial\nequity differ from 15 percentage points?\"\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\nLet $\\delta=E[D]=\\mu_X-15$. Then\n\n$$\nH_0:\\delta=0\n\\qquad\\text{versus}\\qquad\nH_1:\\delta\\ne0.\n$$\n\nThis is equivalent to testing $H_0:\\mu_X=15$ against $H_1:\\mu_X\\ne15$.\nWriting the contrast as $\\delta$ makes the central question \"is the\ndifference zero?\" --- the same structure later used for regression\ncoefficients.\n:::\n\n**Predict (5 minutes).** Answer the one-click Mentimeter question posted on\nCanvas before you come to class: in a real sample, the unknown population SD\n$\\sigma$ must be replaced by the sample SD $S$. Should that substitution\nmake a 95% interval **wider**, **narrower**, or leave it **unchanged**?\nCommit to an answer; the lecture resolves it.\n\nIf intervals, standardisation, or degrees of freedom feel rusty, review\n[Mathematics Refresher: intervals, standardisation, and degrees of\nfreedom](../resources/math-refresher.html).\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In class\n\nThe session opens with the usual four-minute entry quiz on the prep videos,\nthen turns to the driving question. Lecture 8 left us with a sample mean and\nits standard error. This lecture turns those two numbers into a defensible\nclaim: a range of plausible values for the parameter, and a yes-or-no\ndecision about a benchmark.\n\n<p class=\"concept-video\"><strong>Video explanations (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/confidence-intervals/\">20.5 Confidence Intervals</a>,\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/confidence-intervals-for-the-mean-when-the-variance-is-unknown/\">20.7 Confidence Intervals with Unknown Variance</a>, and\n<a href=\"https://www.youtube.com/watch?v=ti9NFdjf3sM\">Introduction to Hypothesis Testing</a>.</p>\n\n### From a benchmark to a zero contrast\n\nThe driving question compares a population mean to the benchmark 15. The\nprep exercise already made the key move: subtract the benchmark and study\nthe **gap**\n\n$$\nD = X - 15,\n\\qquad\n\\delta = E[D] = \\mu_X - 15.\n$$\n\n\"Is mean equity different from 15?\" becomes \"is $\\delta$ different from\n**zero**?\" This looks like a cosmetic rewrite, but it is the single most\nreusable idea of the next four weeks: every benchmark question can be turned\ninto a question about a parameter being zero. Lecture 10 shows that group\ndifferences, proportion gaps, and regression slopes all wear the same\nzero-contrast uniform. Learn the pattern once here, and every later test is\na rerun.\n\n### The price of estimating σ: the t distribution\n\nLecture 8 gave the standardised sample mean\n\n$$\nZ=\\frac{\\bar X-\\mu}{\\sigma/\\sqrt n},\n$$\n\nwhich is approximately standard normal by the CLT. But this $Z$ contains the\n*population* SD $\\sigma$ --- a number nobody knows in a real study. In\npractice we substitute the sample SD $S$, and $S$ is itself a random\nquantity: it changes from sample to sample, and in a small sample it can\nmiss $\\sigma$ badly. Standardising with an *estimated* spread therefore\nproduces a statistic that is more variable than $Z$. For independent\nobservations from a normal population,\n\n$$\nT=\\frac{\\bar X-\\mu}{S/\\sqrt n}\n\\sim t_{n-1}.\n$$\n\nThe **t distribution** is symmetric around zero like the standard normal,\nbut it has **heavier tails**: extreme standardised values are more likely,\nprecisely because $S$ sometimes underestimates the true spread. Its\n**degrees of freedom** control how much heavier:\n\n- few degrees of freedom mean $S$ is estimated imprecisely, so the tails\n  are heavier;\n- more degrees of freedom mean more information about spread;\n- as the degrees of freedom increase, the t distribution approaches\n  $N(0,1)$.\n\nFor a one-sample mean, $df=n-1$ --- the same $n-1$ you met in Lecture 7:\nonce the sample mean is estimated, the $n$ deviations must sum to zero, so\nonly $n-1$ of them vary freely when spread is estimated.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\n\nt_grid <- seq(-4, 4, length.out = 800)\ncurve_levels <- c(\"t, df = 4\", \"t, df = 10\", \"standard normal\")\nreference_curves <- rbind(\n  data.frame(x = t_grid, density = dt(t_grid, df = 4),\n             curve = curve_levels[1]),\n  data.frame(x = t_grid, density = dt(t_grid, df = 10),\n             curve = curve_levels[2]),\n  data.frame(x = t_grid, density = dnorm(t_grid),\n             curve = curve_levels[3])\n)\nreference_curves$curve <- factor(reference_curves$curve,\n                                 levels = curve_levels)\ncurve_colours <- c(\"t, df = 4\" = \"#D55E00\",\n                   \"t, df = 10\" = \"#0072B2\",\n                   \"standard normal\" = \"#009E73\")\n\nggplot(reference_curves, aes(x, density,\n                             colour = curve, linetype = curve)) +\n  geom_line(linewidth = 0.9) +\n  annotate(\"text\", x = 2.3, y = 0.375, label = \"t, df = 4\",\n           colour = \"#D55E00\", size = 3.4, hjust = 0) +\n  annotate(\"text\", x = 2.3, y = 0.335, label = \"t, df = 10\",\n           colour = \"#0072B2\", size = 3.4, hjust = 0) +\n  annotate(\"text\", x = 2.3, y = 0.295, label = \"standard normal\",\n           colour = \"#009E73\", size = 3.4, hjust = 0) +\n  scale_colour_manual(values = curve_colours, guide = \"none\") +\n  scale_linetype_manual(values = c(\"solid\", \"dashed\", \"dotted\"),\n                        guide = \"none\") +\n  scale_y_continuous(limits = c(0, 0.41),\n                     expand = expansion(mult = c(0, 0.02))) +\n  labs(x = \"Standardised value\", y = \"Density\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![The t distribution for 4 and 10 degrees of freedom against the standard normal. All three are symmetric around zero; the t curves put more probability in the tails, most visibly at low degrees of freedom.](b09-t-confidence-intervals_files/figure-html/fig-b09-t-curves-1.png){#fig-b09-t-curves width=672}\n:::\n:::\n\n\n\n\nThe difference in @fig-b09-t-curves is most visible in the tails. This is\nwhy a 95% t critical value is larger than the normal 1.96 when $df$ is\nsmall --- the reference curve must reach further out to enclose 95% of its\nprobability.\n\nThis resolves the prep prediction: replacing $\\sigma$ with $S$ makes the\ninterval **wider**, because the heavier-tailed t distribution demands a\nlarger critical value. The extra width is the honest price of estimating\none more quantity from the same data.\n\n::: {.callout-note collapse=\"true\"}\n## Check: which is larger, $t_{0.975,11}$ or $t_{0.975,99}$?\n\n$t_{0.975,11}\\approx 2.20$ is larger than $t_{0.975,99}\\approx 1.98$. With\nonly 11 degrees of freedom, $S$ is an imprecise estimate of $\\sigma$, so\nthe t distribution has heavier tails and its 97.5% quantile sits further\nfrom zero. At $df=99$ the critical value is already close to the normal\n1.96 --- with a large sample, the t and normal answers nearly coincide.\nVerify in R: `qt(0.975, df = 11)` and `qt(0.975, df = 99)`.\n:::\n\n### The interval recipe\n\nA confidence interval combines the estimate with its uncertainty. The\ngeneral form is\n\n$$\n\\text{estimate}\n\\ \\pm\\\n\\text{critical value}\\times\\text{standard error}.\n$$\n\nThe product after the $\\pm$ is the **margin of error**. A confidence\ninterval becomes:\n\n- wider when the confidence level increases (a larger critical value);\n- wider when observations are more variable (a larger SE);\n- narrower when the sample size increases, all else equal.\n\nFor an independent sample with unknown population SD,\n\n$$\n\\bar X\\pm t_{1-\\alpha/2,\\,n-1}\\frac{S}{\\sqrt n}\n$$\n\nis a $100(1-\\alpha)\\%$ confidence interval for $\\mu$. For a large\nindependent sample, the interval is also a reasonable approximation when\nthe population is not normal --- the CLT again. The same recipe applied to\nthe gap variable $D$ gives an interval for $\\delta$.\n\n::: {#exm-b09-hand-interval}\n## Worked example: a 95% interval by hand\n\nA random sample of $n=64$ ventures reports a mean score of $\\bar x = 80$\nwith sample SD $s = 16$. The industry benchmark is 75. Construct a 95%\nconfidence interval for $\\delta=\\mu-75$, voicing every arithmetic step.\n\n- **Estimate.** The estimated gap is the sample mean minus the benchmark:\n  $\\widehat\\delta = 80 - 75 = 5$.\n- **Standard error.** $\\operatorname{SE}=s/\\sqrt n = 16/\\sqrt{64}$. The\n  square root of 64 is 8, so $\\operatorname{SE}=16/8=2$.\n- **Degrees of freedom and critical value.** $df=n-1=63$, and\n  $t_{0.975,63}\\approx 2.00$ (the exam supplies this value; in R it is\n  `qt(0.975, df = 63)`, about 1.998).\n- **Margin of error.** Critical value times SE: $2.00\\times 2 = 4$.\n- **Interval.** Estimate plus and minus the margin:\n  $5 - 4 = 1$ and $5 + 4 = 9$, so the 95% interval for $\\delta$ is\n  $(1,\\,9)$.\n\nEvery plausible value of the gap is positive: the data are consistent with\na population mean between 1 and 9 points *above* the benchmark. Adding 75\nback to both endpoints gives the equivalent interval $(76,\\,84)$ for $\\mu$\nitself --- the gap form and the mean form are the same statement.\n:::\n\n### Check conditions before calculating\n\nThe formula is justified by the sampling design and distributional\nconditions, not by the presence of an R command. Before any interval or\ntest, walk this checklist:\n\n1. **Random selection.** Were the rows selected randomly from a defined\n   frame? (Ours will be: the seed-123 sample of 100 from the 1,441-record\n   frame.)\n2. **The 10% condition.** Sampling without replacement creates weak\n   dependence, but $100/1441\\approx 0.07 < 0.10$, so the usual\n   independent-sample SE is a reasonable approximation.\n3. **Shape and sample size.** Pitch-level equity is right-skewed, but\n   $n=100$ makes the t approximation for the *sample mean* far more\n   credible than it would be for a very small sample. Still check for data\n   errors or observations that dominate the mean.\n\nThese conditions support inference to the recorded-pitch frame. They do not\nmake televised pitches representative of all entrepreneurs --- the caveat\nbox returns to this.\n\n### The Shark Tank case, with nothing hidden\n\nNow the real question. The recipe runs on the reproducible sample of 100\nfrom Lecture 7, and every object is constructed on screen:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nset.seed(123)\nsample_rows <- sample(seq_len(nrow(sharks)), size = 100, replace = FALSE)\npitch_sample <- sharks[sample_rows, ]\n\nbenchmark <- 15\npitch_sample$equity_gap_pp <-\n  pitch_sample$equity_offered_pct - benchmark\n\ngap_bar <- mean(pitch_sample$equity_gap_pp)   # estimated gap\ngap_sd  <- sd(pitch_sample$equity_gap_pp)     # sample SD of the gap\nn       <- nrow(pitch_sample)\ndf      <- n - 1\ngap_se  <- gap_sd / sqrt(n)                   # standard error\n\nc(\n  sample_mean_equity = mean(pitch_sample$equity_offered_pct),\n  sample_mean_gap = gap_bar,\n  sample_sd_gap = gap_sd,\n  standard_error_gap = gap_se,\n  degrees_of_freedom = df\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsample_mean_equity    sample_mean_gap      sample_sd_gap standard_error_gap \n        12.7600000         -2.2400000          7.7078866          0.7707887 \ndegrees_of_freedom \n        99.0000000 \n```\n\n\n:::\n:::\n\n\n\n\nThe estimated population mean gap is $-2.24$ percentage points: the sample\nmean equity offer of 12.76 sits 2.24 points below the 15-point benchmark.\nNote that subtracting the constant 15 changes the mean but not the spread:\n`gap_sd` equals the sample SD of equity itself, 7.71.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncritical_t <- qt(0.975, df = df)\ngap_ci <- gap_bar + c(-1, 1) * critical_t * gap_se\nmean_ci <- benchmark + gap_ci\n\nc(critical_t = critical_t)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncritical_t \n  1.984217 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(gap_lower = gap_ci[1], gap_upper = gap_ci[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n gap_lower  gap_upper \n-3.7694119 -0.7105881 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(mean_lower = mean_ci[1], mean_upper = mean_ci[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean_lower mean_upper \n  11.23059   14.28941 \n```\n\n\n:::\n:::\n\n\n\n\nThe 95% interval for the mean gap is approximately $(-3.77,\\,-0.71)$\npercentage points. Adding 15 to both endpoints gives the equivalent\ninterval $(11.23,\\,14.29)$ for mean initial equity. Same recipe as the\nhand-worked example --- only the numbers changed.\n\n### A hypothesis test starts with a null model\n\nThe interval displays every plausible value. A **test** answers one\nquestion about one value. For a two-sided test,\n\n$$\nH_0:\\delta=0\n\\qquad\\text{versus}\\qquad\nH_1:\\delta\\ne0.\n$$\n\nThe null says there is no population mean difference from the benchmark.\nThe alternative allows a difference in either direction. Choose the\ntwo-sided alternative from the research question *before* inspecting the\nsample estimate. (Directional, one-sided alternatives exist; Lecture 10\ntreats them and explains when they are --- and are not --- legitimate.)\n\nStandardise the estimated gap using its SE:\n\n$$\nT=\n\\frac{\\widehat\\delta-0}\n{\\operatorname{SE}(\\widehat\\delta)}\n=\n\\frac{\\bar D}{S_D/\\sqrt n}.\n$$\n\nBy hand first, from the numbers already on screen: the estimate is\n$-2.24$, its SE is $0.77$, so\n\n$$\nt=\\frac{-2.24}{0.77}\\approx -2.91.\n$$\n\nThe sign records direction --- below the benchmark; the absolute value\nrecords distance from zero in standard-error units --- almost three SEs.\nNow the same calculation in R, with the p-value:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_value <- gap_bar / gap_se\np_value <- 2 * pt(-abs(t_value), df = df)\n\nc(\n  estimate = gap_bar,\n  standard_error = gap_se,\n  t_statistic = t_value,\n  degrees_of_freedom = df,\n  two_sided_p_value = p_value\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          estimate     standard_error        t_statistic degrees_of_freedom \n      -2.240000000        0.770788656       -2.906114385       99.000000000 \n two_sided_p_value \n       0.004515396 \n```\n\n\n:::\n:::\n\n\n\n\n### A two-sided p-value uses both tails\n\nThe **p-value** is the probability, assuming $H_0$, of obtaining a test\nstatistic at least as far from zero as the observed statistic in either\ndirection:\n\n$$\np=P\\!\\left(|T_{99}|\\ge|t_{obs}|\\mid H_0\\right).\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\n\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nset.seed(123)\nsample_rows <- sample(seq_len(nrow(sharks)), size = 100, replace = FALSE)\npitch_sample <- sharks[sample_rows, ]\npitch_sample$equity_gap_pp <- pitch_sample$equity_offered_pct - 15\ngap_bar <- mean(pitch_sample$equity_gap_pp)\ngap_se <- sd(pitch_sample$equity_gap_pp) / sqrt(nrow(pitch_sample))\ndf <- nrow(pitch_sample) - 1\nt_value <- gap_bar / gap_se\n\nnull_curve <- data.frame(x = seq(-4.5, 4.5, length.out = 1200))\nnull_curve$density <- dt(null_curve$x, df = df)\nleft_tail <- subset(null_curve, x <= -abs(t_value))\nright_tail <- subset(null_curve, x >= abs(t_value))\n\nggplot(null_curve, aes(x, density)) +\n  geom_area(data = left_tail, fill = \"#D55E00\", alpha = 0.85) +\n  geom_area(data = right_tail, fill = \"#D55E00\", alpha = 0.85) +\n  geom_vline(xintercept = c(-abs(t_value), abs(t_value)),\n             linetype = \"dashed\", colour = \"#D55E00\", linewidth = 0.6) +\n  geom_line(colour = \"#17324D\", linewidth = 0.9) +\n  annotate(\"text\", x = -abs(t_value), y = 0.33,\n           label = \"t == -2.91\", parse = TRUE,\n           colour = \"#17324D\", size = 3.4, hjust = 1.15) +\n  annotate(\"text\", x = abs(t_value), y = 0.33,\n           label = \"t == +2.91\", parse = TRUE,\n           colour = \"#17324D\", size = 3.4, hjust = -0.15) +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +\n  labs(x = \"t statistic under the null\", y = \"Density\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![The t distribution with 99 degrees of freedom under the null hypothesis. Dashed lines mark statistics as far from zero as the observed t = −2.91; the two orange tail areas together are the two-sided p-value, about 0.005.](b09-t-confidence-intervals_files/figure-html/fig-b09-two-sided-p-1.png){#fig-b09-two-sided-p width=672}\n:::\n:::\n\n\n\n\nRead @fig-b09-two-sided-p with the five-step sequence. (1) The curve is the\ndistribution of the t statistic **if the null were true** --- not data, a\nnull model. (2) The horizontal axis is the possible t statistic; the\nvertical axis is density, so probability is area. (3) The dashed lines mark\n$-2.91$ and $+2.91$: statistics as far from zero as the one observed.\n(4) The pattern: the two orange tail areas beyond the dashed lines are tiny\n--- together about 0.0045. (5) Takeaway: if the true mean gap were zero, a\nsample as extreme as ours would occur in roughly 5 of every 1,000 samples.\nThat is **not** the probability that $H_0$ is true, and not the size of\nthe gap.\n\nAt $\\alpha=0.05$, reject $H_0$ because $p<0.05$. The random sample\nprovides evidence that mean initial equity in the recorded-pitch frame\ndiffers from 15 percentage points; the negative estimate indicates that it\nis lower.\n\n### The confidence interval and test tell the same story\n\nFor the same two-sided t procedure:\n\n- reject $H_0:\\delta=0$ at level $\\alpha$ exactly when the\n  $100(1-\\alpha)\\%$ confidence interval excludes zero;\n- do not reject when the interval includes zero.\n\nHere the gap interval $(-3.77,\\,-0.71)$ excludes zero, matching the\nrejection. The interval adds information the p-value does not: it displays\nthe direction, plausible magnitude, and precision of the difference. Course\npolicy, from here to the end of Intermediate: **report the estimate and\ninterval alongside any test decision.**\n\n::: {.callout-caution collapse=\"true\"}\n## Try it: read the decision straight from an interval\n\nA colleague reports a 95% confidence interval for a mean gap:\n$(-1.4,\\,3.8)$ percentage points. No t statistic, no p-value.\n\n*Step 1 (given).* The matched two-sided test rejects $H_0:\\delta=0$ at 5%\nexactly when the 95% interval excludes zero.\n\n*Step 2 (you).* Does this interval exclude zero? State the test decision\nwithout computing anything.\n\n*Step 3 (you).* What may you conclude about the population mean gap ---\nand what may you *not* conclude?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nZero lies inside $(-1.4,\\,3.8)$, so the 5% two-sided test does **not**\nreject $H_0:\\delta=0$. The data are compatible with a zero gap --- and\nalso with gaps as large as 3.8 points in one direction and 1.4 in the\nother. You may *not* conclude that the gap **is** zero: \"do not reject\" is\nnot \"accept,\" a distinction Lecture 10 builds on.\n:::\n:::\n\n### Interpret 95% confidence correctly\n\nThe parameter is fixed; interval endpoints vary from sample to sample.\n\"95%\" describes the **procedure**: if the same valid recipe were repeated\non many random samples, about 95% of the resulting intervals would contain\nthe parameter.\n\nThe simulation in @fig-b09-coverage repeats the random sample and interval\ncalculation 100 times. The fixed target is the mean initial equity among\nall 1,441 recorded pitches.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\n\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nset.seed(209)\nB_coverage <- 100\nn_coverage <- 100\ntarget_mean <- mean(sharks$equity_offered_pct)\nci_lower <- ci_upper <- ci_centre <- numeric(B_coverage)\n\nfor (i in seq_len(B_coverage)) {\n  repeated_sample <- sample(\n    sharks$equity_offered_pct,\n    size = n_coverage,\n    replace = FALSE\n  )\n  repeated_mean <- mean(repeated_sample)\n  repeated_se <- sd(repeated_sample) / sqrt(n_coverage)\n  repeated_critical <- qt(0.975, df = n_coverage - 1)\n  ci_centre[i] <- repeated_mean\n  ci_lower[i] <- repeated_mean - repeated_critical * repeated_se\n  ci_upper[i] <- repeated_mean + repeated_critical * repeated_se\n}\n\nintervals <- data.frame(\n  lower = ci_lower, centre = ci_centre, upper = ci_upper,\n  covers = ifelse(ci_lower <= target_mean & ci_upper >= target_mean,\n                  \"contains the target mean\", \"misses the target mean\")\n)\nintervals <- intervals[order(intervals$centre), ]\nintervals$position <- seq_len(B_coverage)\n\nggplot(intervals, aes(y = position, colour = covers)) +\n  geom_segment(aes(x = lower, xend = upper, yend = position),\n               linewidth = 0.7) +\n  geom_point(aes(x = centre), size = 0.9) +\n  geom_vline(xintercept = target_mean, linetype = \"dashed\",\n             colour = \"#C98B2E\", linewidth = 0.7) +\n  annotate(\"text\", x = target_mean, y = B_coverage + 3.5,\n           label = \"mu == 13.21\", parse = TRUE,\n           colour = \"#17324D\", size = 3.4, hjust = -0.1) +\n  scale_colour_manual(values = c(\"contains the target mean\" = \"#009E73\",\n                                 \"misses the target mean\" = \"#D55E00\")) +\n  scale_y_continuous(breaks = c(1, 20, 40, 60, 80, 100)) +\n  labs(x = \"Mean initial equity offered (%)\",\n       y = \"Repeated sample (ordered by estimate)\",\n       colour = NULL) +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.y = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\"),\n    legend.position = \"top\"\n  )\n```\n\n::: {.cell-output-display}\n![One hundred repetitions of the same procedure: draw 100 random pitches, compute a 95% t interval for mean initial equity. Green intervals contain the fixed target mean (gold dashed line); orange intervals miss it. In this run, 96 of 100 intervals cover the target.](b09-t-confidence-intervals_files/figure-html/fig-b09-coverage-1.png){#fig-b09-coverage width=672}\n:::\n:::\n\n\n\n\nEach horizontal segment in @fig-b09-coverage is one 95% confidence\ninterval; its dot is that sample's mean. The gold dashed vertical line is\nthe fixed target mean, 13.21. In this run (seed 209), **96 of 100** intervals\ncross the line. A new run need not give exactly 95, but across many\nrepetitions the proportion approaches 95% when the procedure's conditions\nhold.\n\nOne sentence is now forbidden for the rest of your studies:\n\n> \"There is a 95% probability that the population mean is in my interval.\"\n\nThe realised interval $(11.23, 14.29)$ either contains the fixed parameter\nor it does not --- there is no probability left once the sample is drawn.\nThe correct replacement:\n\n> \"This interval was produced by a procedure that captures the fixed\n> population mean in about 95% of repeated valid samples.\"\n\n::: {.caveat-box}\n<span class=\"label\">What significance can and cannot tell you</span>\n\nThree boundaries around everything in this lecture. First, **significance\nis not importance**: $p\\approx 0.005$ says the gap is measured precisely\nenough to distinguish it from zero, not that a 2.24-point gap matters for\nany decision --- magnitude and context decide that. Second, **significance\nis not causation**: the evidence concerns a mean in an observational frame;\nnothing here says *why* equity asks sit below 15 points. Third, **a narrow\ninterval repairs nothing about selection**: the interval quantifies random\nsampling error within the recorded-pitch frame. If the frame itself is a\nproducer-curated selection of telegenic pitches --- and it is --- then no\ninterval width, however impressive, extends the conclusion to entrepreneurs\nin general. An on-air agreement is still not a completed investment.\n:::\n\n### Answering the driving question\n\nYes --- within the frame. The seed-123 sample gives an estimated gap of\n$-2.24$ percentage points with SE $0.77$; the 95% interval for mean equity\nis $(11.23, 14.29)$, which excludes 15, and the two-sided test rejects\n$H_0:\\delta=0$ at 5% ($t=-2.91$, $p\\approx 0.005$). The evidence says the\nframe's mean initial equity ask sits *below* 15 percent --- plausibly by\nbetween 0.7 and 3.8 points. Whether that gap matters commercially, and what\ncaused it, are separate questions the test cannot answer.\n\n**Next:** We can now test a benchmark and report the answer as an interval and\na p-value. But every test decision can be wrong in one of two ways ---\nrejecting a true null, or missing a real effect --- and the two mistakes\nrarely cost the same. Lecture 10 names the two error types, shows the four\nlevers that make wrong calls rarer (power), settles when a one-sided\nalternative is legitimate, and then opens the door this whole course has been\nwalking toward: the same estimate--SE--t--p--interval row, sitting in a\nregression table.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 60 minutes.</span>\n\n### Retrieval (10 minutes)\n\n1. Why does replacing $\\sigma$ with the sample SD $S$ require a t rather\n   than a normal reference distribution?\n2. Why does a one-sample t procedure use $n-1$ degrees of freedom?\n3. What are the three pieces of a confidence interval?\n4. What do $H_0:\\delta=0$ and $H_1:\\delta\\ne0$ say?\n5. Why does a two-sided p-value use two tails?\n6. What is the exact decision link between a 95% t interval and a 5%\n   two-sided t-test?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. $S$ is itself estimated and varies from sample to sample; the t\n   distribution's heavier tails represent that extra uncertainty.\n2. Estimating the sample mean imposes one constraint (deviations sum to\n   zero) before spread is estimated, leaving $n-1$ freely varying\n   deviations.\n3. Estimate, critical value, and standard error.\n4. The null states that the population contrast is zero; the alternative\n   allows a non-zero contrast in either direction.\n5. Values equally far below and above zero are both evidence against a\n   two-sided null.\n6. The test rejects exactly when the interval excludes zero, provided both\n   use the same model and SE.\n:::\n\n### From worked to faded (10 minutes)\n\nRe-read the hand-worked interval (@exm-b09-hand-interval). Then complete\nthe same calculation with new numbers: $n=25$ customers, mean satisfaction\n$\\bar x = 42$, sample SD $s = 10$, benchmark 40, so $\\delta=\\mu-40$.\n\n*Step 1 (given).* The estimated gap is $42-40=2$, and\n$t_{0.975,24}\\approx 2.06$.\n\n*Step 2 (you).* Calculate the SE and the margin of error.\n\n*Step 3 (you).* Write the 95% interval for $\\delta$ and state, without any\nfurther computation, the 5% two-sided test decision.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$\\operatorname{SE}=10/\\sqrt{25}=2$; margin of error\n$2.06\\times 2=4.13$. The interval is $2\\pm 4.13=(-2.13,\\,6.13)$. Zero lies\ninside, so the 5% two-sided test does not reject $H_0:\\delta=0$: the data\nare compatible with a zero gap --- and with gaps up to about 6 points. (For\ncompleteness, $t=2/2=1.00$, $p\\approx 0.33$.)\n:::\n\n### Practice (10 minutes)\n\n1. A sample has $n=49$, $\\bar x=110$, and $s=14$. Define $\\delta=\\mu-100$.\n   Construct a 95% interval for $\\delta$ (use $t_{0.975,48}\\approx 2.01$).\n2. Test $H_0:\\delta=0$ against $H_1:\\delta\\ne0$ at 5%. Report the\n   statistic, degrees of freedom, approximate p-value, decision, and a\n   contextual conclusion.\n3. A coefficient-like estimate is 0.42 percentage points per €100,000,\n   with SE 0.18 and $df=120$. Test a two-sided zero null and construct a\n   95% interval (use $t_{0.975,120}\\approx 1.98$).\n4. Explain why a statistically significant mean gap need not be\n   practically important or causal.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. The estimated gap is $110-100=10$, its SE is $14/\\sqrt{49}=2$, and the\n   interval is $10\\pm 2.01(2)=(5.98,\\,14.02)$.\n2. $t=10/2=5.00$, $df=48$, two-sided p-value below 0.001. Reject $H_0$:\n   the data provide strong evidence that the population mean exceeds 100\n   --- plausibly by 6 to 14 points.\n3. $t=0.42/0.18\\approx 2.33$, two-sided p-value about 0.021. The 95%\n   interval is $0.42\\pm1.98(0.18)=(0.064,\\,0.776)$ percentage points per\n   €100,000. Reject the zero null at 5%.\n4. Statistical significance concerns precision relative to zero. Practical\n   importance depends on the magnitude and the decision context, and\n   causality requires an appropriate design and assumptions --- neither is\n   delivered by a small p-value.\n:::\n\n### Rewrite the forbidden sentence (5 minutes)\n\nRewrite this claim correctly: \"There is a 95% chance that the population\nmean is in my interval $(11.23, 14.29)$.\"\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\n\"The interval $(11.23, 14.29)$ was produced by a procedure that captures\nthe fixed population mean in about 95% of repeated valid samples.\" The\nparameter is fixed; it is the interval endpoints that vary across samples,\nas in @fig-b09-coverage.\n:::\n\n### Spaced review: one item each from Lectures 8 and 4 (10 minutes)\n\n1. *(Lecture 8.)* A planned survey expects a sample SD around 24 with\n   $n=64$. Estimate the SE of the sample mean, and state what happens to\n   it if $n$ grows to 256.\n2. *(Lecture 4.)* From the 2×2 counts table,\n   $P(D\\mid L)=505/734\\approx 0.688$ while\n   $P(L\\mid D)=505/882\\approx 0.573$. Why are these two numbers different\n   even though both involve the same 505 records?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. $\\operatorname{SE}=24/\\sqrt{64}=3$. Quadrupling the sample size halves\n   the SE to 1.5 --- the square-root rule.\n2. They condition on different reference classes: the first divides the\n   505 joint records by the 734 late-season records, the second divides\n   the same 505 by the 882 deal records. Changing the event after the bar\n   changes the denominator.\n:::\n\n### Worked exam interpretation (10 minutes)\n\n**Question (Mock Exam Q4 pattern).** From a frame of 1,000 accelerator\napplicants, a simple random sample of 64 was selected. `prep_hours` is\nhours spent preparing the application; $\\mu$ is the frame mean. The sample\nhas $\\bar x=18.4$ and $s=8.0$. R produced:\n\n```text\nOne Sample t-test\n\ndata: prep_hours\nt = 2.400, df = 63, p-value = 0.0193\nalternative hypothesis: true mean is not equal to 16\n95 percent confidence interval:\n 16.40 20.40\nsample estimate:\nmean of x = 18.40\n```\n\nVerify the SE and the t statistic, explain the degrees of freedom,\ninterpret the p-value and the interval, and give the 5% decision.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\n$\\operatorname{SE}=8/\\sqrt{64}=1$ hour, so\n$t=(18.4-16)/1=2.4$, matching the output. $df=64-1=63$ because the\ndeviations from the estimated sample mean must sum to zero, leaving 63\nfree. If the frame mean were 16 hours, a sample mean at least 2.4 SEs from\n16 in either direction would occur in about 1.9% of random samples; since\n$0.0193<0.05$, reject $H_0:\\mu=16$. The interval $(16.40, 20.40)$ gives\nthe plausible range for $\\mu$ --- it excludes 16, agreeing with the test\n--- and was produced by a procedure with about 95% coverage across\nrepeated samples. The claim concerns the 1,000-applicant frame, not\napplicants in general.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA venture --- or any business you know well. Pick one key\nmetric with a published industry benchmark (conversion rate, average order\nvalue, churn), frame the comparison as a gap $\\delta = \\mu - \\text{benchmark}$,\nand write two sentences: first say what sample you could realistically\ncollect and what a 95% interval for $\\delta$ excluding zero would let you\nclaim, then say what decision would change if the interval turned out to\ninclude zero.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"The sector churn benchmark is 25% per term; from my roughly 120 subscribers I can estimate $\\delta = \\mu - 25$, and a 95% interval sitting entirely below zero would let me claim genuinely stickier customers in my pitch. If the interval included zero, I would stop pitching retention as my edge and lead with margin instead.\"\n:::\n\nYou can discuss this task --- and any other task in this chapter --- with\n**Tilly**, the course AI assistant on Canvas: ask it to check whether your\ngap is defined on a population you can actually sample.\n::::\n\nContinue to Lecture 10: Testing decisions, errors, power, and the road to\nregression.\n\nFormula sheet: Lecture 9 formulas.\n\nFor a more formal explanation, consult\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapters 15 and 16.\n\n:::\n",
    "supporting": [
      "b09-t-confidence-intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}