{
  "hash": "e8d4a55897df917c93380dbb832eae3b",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 4: Conditioning, Bayes' rule, and independence {#b04}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 4, you can</span>\n\n- calculate conditional probabilities from a counts table and identify the\n  reference class behind each one;\n- use the multiplication rule to move between joint and conditional\n  probabilities;\n- rebuild an overall probability from group-specific rates with the law of\n  total probability;\n- update a probability after new evidence with Bayes' rule, first by counting\n  on a natural-frequency tree and then with the formula;\n- check whether two events are independent and explain why disjoint is not\n  the same as independent.\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">An investor who learns a pitch is late-season updates their expectations. A bank seeing a positive fraud flag does the same. Updating chances on new information is the most used probability skill in business --- and the easiest to get backwards.</p>\n\nLate-season pitches reach deals more often. What exactly do the two possible\n\"68.8% versus 57.3%\" sentences claim, and what does a positive flag from an\nAI deal-predictor really tell us?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 30 minutes.</span>\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation (15 minutes)</span><br>\nWatch <a href=\"https://www.youtube.com/watch?v=MPRKc4UPoJk\">Conditional\nProbabilities</a> and\n<a href=\"https://www.youtube.com/watch?v=kz2tvO_ZAKI\">Bayes' Rule</a>. Be\nready to identify the reference class in a conditional probability and to\nexplain why reversing a condition changes the denominator. All links are\nalso listed in the <a href=\"../resources/video-guide.html\">External Video\nGuide</a>.\n</div>\n\n**Reactivate (10 minutes).** Lecture 2 built the 2×2 counts table for deals\nand seasons. Rebuild it --- the construction of $D$ and $L$ is the same as\nthere:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nD <- sharks$deal_on_show == 1   # on-air deal\nL <- sharks$season >= 9         # late season: Seasons 9-16\ntable(deal = D, late = L)\n```\n:::\n\n\n\n\nThen compare, in words only:\n\n- \"Among pitches in Seasons 9--16, what proportion reached an on-air deal?\"\n- \"Among pitches that reached an on-air deal, what proportion came from\n  Seasons 9--16?\"\n\nBoth questions will use the same cell of your table. Decide before class\nwhich part of the table each question restricts attention to. The lecture\nopens with exactly this exercise.\n\n**Predict (5 minutes).** Answer the one-click Mentimeter question posted on\nCanvas before you come to class: an AI classifier flags pitches likely to\nget a deal and catches 80% of actual deals. Of the *flagged* pitches, what\nshare are deals --- near 80%, near 50%, or near 30%? Commit to an answer; the\nlecture resolves it.\n\nIf fractions or the conditioning bar are unfamiliar, review\n[Mathematics Refresher: fractions, powers, and event\nnotation](../resources/math-refresher.html).\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In class\n\nThe session opens with the usual four-minute entry quiz on the prep videos,\nthen turns to the driving question. Two sentences circulate about the same\ndataset:\n\n- **Sentence A.** \"68.8% of late-season pitches reached an on-air deal.\"\n- **Sentence B.** \"57.3% of the pitches that reached a deal came from the\n  late seasons.\"\n\nBoth sentences are built on the *same* 505 records --- the late-season deals.\nYet they answer different questions and produce different numbers. By the end\nof this session you can say precisely what each sentence claims, and you can\nanswer a harder question of the same kind: when an AI classifier flags a\npitch as a likely deal, how much should that flag change your mind?\n\n### One table, five denominators\n\nEverything starts from the Lecture 2 counts table. The code constructs $D$\nand $L$ exactly as before --- run it yourself:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nD <- sharks$deal_on_show == 1   # on-air deal\nL <- sharks$season >= 9         # late season: Seasons 9-16\ntable(deal = D, late = L)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       late\ndeal    FALSE TRUE\n  FALSE   330  229\n  TRUE    377  505\n```\n\n\n:::\n:::\n\n\n\n\nWritten with row and column totals:\n\n|                    | Early ($L^c$, S1--8) | Late ($L$, S9--16) | Total |\n|--------------------|---------------------:|-------------------:|------:|\n| **No deal** ($D^c$) | 330 | 229 | **559** |\n| **Deal** ($D$)      | 377 | 505 | **882** |\n| **Total**           | **707** | **734** | **1441** |\n\nBefore any formula, do the class opening exercise: for each probability\nbelow, point --- physically, on the table --- to the count that goes on top\nand the count that goes underneath.\n\n1. $P(D)$;\n2. $P(L)$;\n3. $P(D\\cap L)$;\n4. $P(D\\mid L)$;\n5. $P(L\\mid D)$.\n\n::: {.callout-note collapse=\"true\"}\n## Check your denominators\n\n1. $P(D)$: 882 deal records out of all 1,441 records.\n2. $P(L)$: 734 late-season records out of all 1,441 records.\n3. $P(D\\cap L)$: 505 late-season deal records out of all 1,441 records.\n4. $P(D\\mid L)$: 505 late-season deal records out of the **734 late-season\n   records**.\n5. $P(L\\mid D)$: 505 late-season deal records out of the **882 deal\n   records**.\n\nThe first three all divide by 1,441. The last two divide by a *part* of the\ntable --- and that is the whole subject of this lecture.\n:::\n\n### Conditional probability\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/conditional-probabilities/\">02.2 Conditional Probabilities</a>.</p>\n\nFor events $A$ and $B$ with $P(B)>0$, the **conditional probability of $A$\ngiven $B$** is\n\n$$P(A\\mid B)=\\frac{P(A\\cap B)}{P(B)}.$$\n\nRead the definition as an instruction in three steps: keep only the outcomes\ninside $B$, rescale their total probability to 1, and then ask what fraction\nof that reduced world is also in $A$. The event after the vertical bar is the\n**reference class** --- the group you restrict attention to --- and it\nsupplies the denominator. For a fixed $B$, $P(\\cdot\\mid B)$ is itself a\nprobability law: it satisfies all three rules from Lecture 2.\n\n::: {#exm-b04-conditional}\n## Worked example: the two rival sentences, resolved\n\n**Sentence A asks about $P(D\\mid L)$.** Conditioning on $L$ means covering\neverything except the Late column:\n\n|                    | Early | **Late ($L$)** |\n|--------------------|------:|---------------:|\n| No deal            | · | **229** |\n| Deal               | · | **505** |\n| Total              | · | **734** |\n\nWithin that one column, 505 of 734 records are deals:\n\n$$P(D\\mid L)=\\frac{505}{734}\\approx 0.688.$$\n\n**Sentence B asks about $P(L\\mid D)$.** Conditioning on $D$ means covering\neverything except the Deal row:\n\n|                    | Early | Late | Total |\n|--------------------|------:|-----:|------:|\n| No deal            | · | · | · |\n| **Deal ($D$)**     | **377** | **505** | **882** |\n\nWithin that one row, 505 of 882 records are late-season:\n\n$$P(L\\mid D)=\\frac{505}{882}\\approx 0.573.$$\n\nThe numerator is 505 in both calculations --- the same intersection cell.\nThe denominators, and therefore the questions, differ: Sentence A restricts\nto the 734 late-season pitches, Sentence B to the 882 deal pitches.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Check: which sentence matches which number?\n\nSentence A (\"of late-season pitches, ... reached a deal\") conditions on the\nseason, so it is $P(D\\mid L)=505/734\\approx 68.8\\%$. Sentence B (\"of deal\npitches, ... came from late seasons\") conditions on the deal, so it is\n$P(L\\mid D)=505/882\\approx 57.3\\%$. A report that quotes \"68.8% of deal\npitches came from late seasons\" has attached the right number to the wrong\nsentence.\n:::\n\nVerification in R --- subsetting with `[L]` or `[D]` is exactly the\n\"restrict the reference class\" step:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD <- sharks$deal_on_show == 1\nL <- sharks$season >= 9\nc(\n  P_deal_given_late = mean(D[L]),\n  P_late_given_deal = mean(L[D])\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP_deal_given_late P_late_given_deal \n        0.6880109         0.5725624 \n```\n\n\n:::\n:::\n\n\n\n\n### The multiplication rule\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/the-multiplication-rule/\">02.6 The Multiplication Rule</a>.</p>\n\nMultiply both sides of the definition by $P(B)$ and the same content appears\nin a new role --- a way to *build* a joint probability from a conditional one:\n\n$$P(A\\cap B)=P(A\\mid B)\\,P(B).$$\n\nReversing the roles of $A$ and $B$ must give the same joint probability,\nbecause $A\\cap B$ and $B\\cap A$ are the same event:\n\n$$P(A\\cap B)=P(A\\mid B)\\,P(B)=P(B\\mid A)\\,P(A).$$\n\nThis one line is the algebraic reason the two rival sentences can share a\nnumerator while having different denominators: both products equal\n$505/1441$, but they factor it through different reference classes.\n\n::: {.callout-caution collapse=\"true\"}\n## Try it: verify the joint probability two ways\n\nIn class this is the pair task. Use the counts table to check the identity\nabove for $D$ and $L$.\n\n*Step 1 (given).* The direct route: $P(D\\cap L)=505/1441\\approx 0.350$.\n\n*Step 2 (given).* First factorisation:\n$P(D\\mid L)\\,P(L)=\\dfrac{505}{734}\\cdot\\dfrac{734}{1441}$. The 734 cancels\n--- carry out the cancellation and confirm you land on $505/1441$.\n\n*Step 3 (you).* Write down the second factorisation,\n$P(L\\mid D)\\,P(D)$, as a product of two fractions from the table, and show\nthat it also collapses to $505/1441$.\n\n*Step 4 (you).* Confirm all three routes in R.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$P(L\\mid D)\\,P(D)=\\dfrac{505}{882}\\cdot\\dfrac{882}{1441}=\\dfrac{505}{1441}\n\\approx 0.350$: the 882 cancels, just as the 734 did.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD <- sharks$deal_on_show == 1\nL <- sharks$season >= 9\nc(\n  direct_joint            = mean(D & L),\n  cond_on_late_times_base = mean(D[L]) * mean(L),\n  cond_on_deal_times_base = mean(L[D]) * mean(D)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           direct_joint cond_on_late_times_base cond_on_deal_times_base \n              0.3504511               0.3504511               0.3504511 \n```\n\n\n:::\n:::\n\n\n\n:::\n:::\n\n### The law of total probability\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/total-probability-theorem/\">02.7 Total Probability Theorem</a>.</p>\n\nLecture 2 introduced a partition: events that do not overlap and together\ncover every outcome. Conditioning gives the probability of $A$ *within* each\npart; the multiplication rule turns each conditional probability into a joint\npiece; and adding the pieces gives the overall probability of $A$. That chain\nof three known moves is the **law of total probability**: for a partition\n$B_1,\\ldots,B_k$ with every $P(B_i)>0$,\n\n$$P(A)=\\sum_{i=1}^{k}P(A\\mid B_i)\\,P(B_i).$$\n\n::: {#exm-b04-total}\n## Worked example: rebuilding P(D) from the period-specific rates\n\nThe early/late events $\\{L^c, L\\}$ form a partition, so\n\n$$P(D)=P(D\\mid L^c)\\,P(L^c)+P(D\\mid L)\\,P(L)\n=\\frac{377}{707}\\cdot\\frac{707}{1441}\n+\\frac{505}{734}\\cdot\\frac{734}{1441}\n=\\frac{377+505}{1441}=\\frac{882}{1441}\\approx 0.612.$$\n\nPoint to the two kinds of number: $377/707\\approx 0.533$ and\n$505/734\\approx 0.688$ are the *period-specific deal rates*, and\n$707/1441\\approx 0.491$ and $734/1441\\approx 0.509$ are the **weights** ---\nhow much of the sample space each period occupies. The overall deal\nprobability is a weighted average of the group rates, so it must lie between\n0.533 and 0.688, closer to the rate of the slightly larger group.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD <- sharks$deal_on_show == 1\nL <- sharks$season >= 9\nc(\n  direct       = mean(D),\n  from_periods = mean(D[!L]) * mean(!L) + mean(D[L]) * mean(L)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      direct from_periods \n   0.6120749    0.6120749 \n```\n\n\n:::\n:::\n\n\n\n\n@fig-b04-partition-areas shows the same computation as areas.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nD <- sharks$deal_on_show == 1\nL <- sharks$season >= 9\np_early <- mean(!L)\np_deal_early <- mean(D[!L])\np_deal_late <- mean(D[L])\n\nggplot() +\n  # light backgrounds: the two parts of the partition\n  annotate(\"rect\", xmin = 0, xmax = p_early, ymin = 0, ymax = 1,\n           fill = \"#009E73\", alpha = 0.25) +\n  annotate(\"rect\", xmin = p_early, xmax = 1, ymin = 0, ymax = 1,\n           fill = \"#D55E00\", alpha = 0.25) +\n  # solid areas: deal rate within each part, times the part's width\n  annotate(\"rect\", xmin = 0, xmax = p_early, ymin = 0,\n           ymax = p_deal_early, fill = \"#009E73\", alpha = 0.85) +\n  annotate(\"rect\", xmin = p_early, xmax = 1, ymin = 0,\n           ymax = p_deal_late, fill = \"#D55E00\", alpha = 0.85) +\n  annotate(\"segment\", x = p_early, xend = p_early, y = 0, yend = 1,\n           colour = \"#17324D\", linewidth = 0.8) +\n  annotate(\"rect\", xmin = 0, xmax = 1, ymin = 0, ymax = 1,\n           fill = NA, colour = \"#17324D\", linewidth = 0.8) +\n  annotate(\"text\", x = p_early / 2, y = 0.28, label = \"D ∩ Lᶜ\",\n           colour = \"white\", size = 4.2) +\n  annotate(\"text\", x = p_early + (1 - p_early) / 2, y = 0.36,\n           label = \"D ∩ L\", colour = \"white\", size = 4.2) +\n  annotate(\"text\", x = p_early / 2, y = 0.88, label = \"L^c\",\n           parse = TRUE, colour = \"#17324D\", size = 4.4) +\n  annotate(\"text\", x = p_early + (1 - p_early) / 2, y = 0.88,\n           label = \"L\", colour = \"#17324D\", size = 4.4) +\n  annotate(\"text\", x = 0.985, y = 0.955, label = \"Omega\",\n           parse = TRUE, colour = \"#17324D\", size = 3.8) +\n  coord_cartesian(expand = FALSE) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![Total probability as areas. The columns are the early/late partition from Lecture 2; column width is the period's probability (the weight), and the height of each coloured region is the period-specific deal rate. The two coloured areas do not overlap, and their sum is P(D).](b04-conditioning-bayes-independence_files/figure-html/fig-b04-partition-areas-1.png){#fig-b04-partition-areas width=672}\n:::\n:::\n\n\n\n\n### Bayes' rule: count first, formula second\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/bayes-rule/\">02.8 Bayes' Rule</a>.</p>\n\nReturn to your prep prediction. An AI classifier reads pitch transcripts and\nflags the pitches it considers likely to reach a deal. Three numbers describe\na (hypothetical) classifier of this kind:\n\n- the **base rate**: 10% of pitches in its target population reach a deal;\n- the **sensitivity**: among actual deals, 80% get flagged,\n  $P(\\text{flag}\\mid\\text{deal})=0.80$;\n- the **false-positive rate**: among non-deals, 20% still get flagged,\n  $P(\\text{flag}\\mid\\text{no deal})=0.20$.\n\nA pitch has just been flagged. How likely is a deal now --- near 80%, 50%,\nor 30%? Before any formula, count.\n\n::: {#exm-b04-bayes-tree}\n## Worked example: 1,000 imaginary pitches\n\nImagine 1,000 pitches from this population and push them through the three\nnumbers, as in @fig-b04-bayes-tree.\n\n1. **Split by the base rate.** Of 1,000 pitches, 100 are deals and 900 are\n   not.\n2. **Flag the deals.** Sensitivity 80%: of the 100 deals, 80 are flagged.\n3. **Flag some non-deals too.** False-positive rate 20%: of the 900\n   non-deals, 180 are flagged.\n4. **Collect the flagged.** In total $80+180=260$ pitches carry a flag ---\n   and only 80 of them are deals:\n\n$$P(\\text{deal}\\mid\\text{flag})=\\frac{80}{260}\\approx 0.31.$$\n\nThe classifier catches 80% of deals, yet fewer than a third of its flags are\ndeals. The reason is visible in the tree: the 900 non-deals are such a large\ngroup that even a modest 20% false-positive rate produces 180 false flags ---\nmore than double the 80 true ones. A flag moves the deal probability from\n10% to 31%: real evidence, but nowhere near certainty.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the drawing code (optional, not exam material)\"}\nold_par <- par(no.readonly = TRUE)\npar(mar = c(0.2, 0.2, 0.2, 0.2))\nplot(NA, xlim = c(0, 10), ylim = c(0.3, 9.7), axes = FALSE,\n     xlab = \"\", ylab = \"\", xaxs = \"i\", yaxs = \"i\")\n\ndraw_node <- function(x, y, top, bottom, fill = \"white\",\n                      border = \"#17324D\", lwd = 1.4, w = 1.05, h = 0.78) {\n  rect(x - w, y - h, x + w, y + h, col = fill, border = border, lwd = lwd)\n  text(x, y + 0.26, top, font = 2, cex = 1.0, col = \"#17324D\")\n  text(x, y - 0.30, bottom, cex = 0.8, col = \"#5B6976\")\n}\ndraw_branch <- function(x1, y1, x2, y2, label, above = TRUE) {\n  segments(x1, y1, x2, y2, col = \"#9AA7B2\", lwd = 1.6)\n  text((x1 + x2) / 2, (y1 + y2) / 2 + if (above) 0.32 else -0.32,\n       label, cex = 0.76, col = \"#5B6976\")\n}\n\n# branches first, then boxes on top\ndraw_branch(2.45, 5.35, 3.55, 7.15, \"10% deal\")\ndraw_branch(2.45, 4.65, 3.55, 2.85, \"90% no deal\", above = FALSE)\ndraw_branch(5.65, 7.75, 6.95, 8.45, \"80% flagged\")\ndraw_branch(5.65, 7.05, 6.95, 6.35, \"20% not\", above = FALSE)\ndraw_branch(5.65, 2.95, 6.95, 3.65, \"20% flagged\")\ndraw_branch(5.65, 2.25, 6.95, 1.55, \"80% not\", above = FALSE)\n\ndraw_node(1.35, 5.0, \"1,000\", \"pitches\", w = 1.15)\ndraw_node(4.6, 7.4, \"100\", \"deal\")\ndraw_node(4.6, 2.6, \"900\", \"no deal\")\ndraw_node(8.0, 8.6, \"80\", \"flagged\", fill = \"#FDE5C1\",\n          border = \"#D55E00\", lwd = 2.2)\ndraw_node(8.0, 6.2, \"20\", \"not flagged\", fill = \"#F4F7F9\",\n          border = \"#9AA7B2\")\ndraw_node(8.0, 3.8, \"180\", \"flagged\", fill = \"#FDE5C1\",\n          border = \"#D55E00\", lwd = 2.2)\ndraw_node(8.0, 1.4, \"720\", \"not flagged\", fill = \"#F4F7F9\",\n          border = \"#9AA7B2\")\n\ntext(9.55, 6.2, \"260\\nflagged\\nin total\", cex = 0.82, col = \"#D55E00\")\npar(old_par)\n```\n\n::: {.cell-output-display}\n![Natural-frequency tree for 1,000 imaginary pitches. Orange boxes are the flagged pitches: 80 + 180 = 260 flags in total, of which only 80 are deals, so P(deal | flag) = 80/260, about 31%.](b04-conditioning-bayes-independence_files/figure-html/fig-b04-bayes-tree-1.png){#fig-b04-bayes-tree width=768}\n:::\n:::\n\n\n\n\nNow the formula. The question reverses a condition: the classifier's quality\nis stated as $P(\\text{flag}\\mid\\text{deal})$, but the decision-maker needs\n$P(\\text{deal}\\mid\\text{flag})$. The multiplication rule gives the numerator\nand total probability gives the denominator:\n\n$$P(B_i\\mid A)=\\frac{P(A\\mid B_i)\\,P(B_i)}\n{\\sum_j P(A\\mid B_j)\\,P(B_j)}.$$\n\nThis is **Bayes' rule**. For the classifier, with the deal/no-deal partition:\n\n$$P(\\text{deal}\\mid\\text{flag})\n=\\frac{0.80\\times 0.10}{0.80\\times 0.10+0.20\\times 0.90}\n=\\frac{0.08}{0.08+0.18}=\\frac{0.08}{0.26}\\approx 0.308.$$\n\nEvery term is a branch of the tree, divided by 1,000:\n\n| Formula term | Value | Tree count |\n|---|---:|---|\n| $P(\\text{flag}\\mid\\text{deal})\\,P(\\text{deal})$ | $0.08$ | the 80 flagged deals |\n| $P(\\text{flag}\\mid\\text{no deal})\\,P(\\text{no deal})$ | $0.18$ | the 180 flagged non-deals |\n| the denominator (total probability of a flag) | $0.26$ | all 260 flagged pitches |\n\nThe formula is the tree, written compactly. When a Bayes question appears on\nthe exam, you may draw the tree with a convenient imaginary total and count\n--- the two routes always agree.\n\nBayes' rule also works on the Shark Tank events themselves. Reversing\n$P(D\\mid L)$ recovers $P(L\\mid D)$, and the R check makes the point that\nnothing beyond the multiplication rule and total probability is involved:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD <- sharks$deal_on_show == 1\nL <- sharks$season >= 9\nbayes_late_given_deal <- mean(D[L]) * mean(L) / mean(D)\nc(\n  from_bayes = bayes_late_given_deal,\n  from_table = mean(L[D])\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfrom_bayes from_table \n 0.5725624  0.5725624 \n```\n\n\n:::\n:::\n\n\n\n\n### Independence of events\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/independence-of-two-events/\">03.3 Independence of Two Events</a>.</p>\n\nConditioning finally makes precise an idea Lecture 2 could only promise:\nwhat it means for one event to carry *no information* about another. Events\n$A$ and $B$ (with $P(B)>0$) are **independent** when learning that $B$\noccurred does not change the probability of $A$:\n\n$$P(A\\mid B)=P(A).$$\n\nMultiplying both sides by $P(B)$ gives the symmetric **product form**, which\nalso covers zero-probability events and is the usual textbook definition:\n\n$$P(A\\cap B)=P(A)\\,P(B).$$\n\n::: {#exm-b04-independence}\n## Worked example: are D and L independent?\n\nCheck either form with the real numbers.\n\nVia conditioning: $P(D\\mid L)=505/734\\approx 0.688$, while\n$P(D)=882/1441\\approx 0.612$. Learning that a pitch is late-season *raises*\nthe deal probability, so $D$ and $L$ are **not independent**.\n\nVia the product: $P(D\\cap L)=505/1441\\approx 0.350$, while\n$P(D)\\,P(L)=\\dfrac{882}{1441}\\cdot\\dfrac{734}{1441}\\approx 0.612\\times\n0.509\\approx 0.312$. The joint probability exceeds the product, which says\nthe same thing: deals and late seasons occur together more often than\nindependence would predict.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD <- sharks$deal_on_show == 1\nL <- sharks$season >= 9\nc(\n  P_D_given_L  = mean(D[L]),\n  P_D          = mean(D),\n  P_D_and_L    = mean(D & L),\n  P_D_times_P_L = mean(D) * mean(L)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  P_D_given_L           P_D     P_D_and_L P_D_times_P_L \n    0.6880109     0.6120749     0.3504511     0.3117717 \n```\n\n\n:::\n:::\n\n\n\n\n**Disjoint is not independent --- one minute, one example.** Take the\nearly/late pair $L^c$ and $L$. They are disjoint: no pitch is in both\nperiods, so $P(L^c\\cap L)=0$. But the product\n$P(L^c)\\,P(L)\\approx 0.491\\times 0.509\\approx 0.25$ is far from zero, so they\nfail the independence check spectacularly. Disjoint events with positive\nprobability are always *dependent*: observing one tells you the other is\nimpossible --- maximal information, not none.\n\n### Second application: deal rates by team composition\n\nThe dataset classifies pitching teams as `all_men`, `all_women`, `mixed`, or\n`unknown`. Each within-category deal rate is a conditional probability:\n$P(D\\mid \\text{category})$, with the category as reference class. The\nconstruction is shown in full --- this is the live-R segment of the session:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nD <- sharks$deal_on_show == 1\nknown_gender <- sharks$pitcher_gender_group != \"unknown\"\ngender_labels <- c(\"all_men\", \"all_women\", \"mixed\")\n\ngender_deal_rates <- tapply(\n  sharks$deal_on_show[known_gender],\n  factor(sharks$pitcher_gender_group[known_gender], levels = gender_labels),\n  mean\n)\ngender_deal_rates\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  all_men all_women     mixed \n0.5808538 0.6363636 0.6630435 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nknown_gender <- sharks$pitcher_gender_group != \"unknown\"\ngender_labels <- c(\"all_men\", \"all_women\", \"mixed\")\ngender_deal_rates <- tapply(\n  sharks$deal_on_show[known_gender],\n  factor(sharks$pitcher_gender_group[known_gender], levels = gender_labels),\n  mean\n)\ngender_counts <- table(\n  factor(sharks$pitcher_gender_group[known_gender], levels = gender_labels)\n)\nrates_df <- data.frame(\n  team = paste0(c(\"All-men\", \"All-women\", \"Mixed\"),\n                \"\\n(n = \", as.integer(gender_counts), \")\"),\n  deal_rate = as.numeric(gender_deal_rates)\n)\nrates_df$team <- factor(rates_df$team, levels = rates_df$team)\n\nggplot(rates_df, aes(x = team, y = deal_rate)) +\n  geom_col(fill = \"#009E73\", alpha = 0.85, colour = \"white\",\n           width = 0.62) +\n  geom_text(aes(label = paste0(round(100 * deal_rate, 1), \"%\")),\n            vjust = -0.6, colour = \"#17324D\", size = 3.6) +\n  scale_y_continuous(limits = c(0, 0.75),\n                     breaks = seq(0, 0.75, by = 0.15),\n                     labels = paste0(seq(0, 75, by = 15), \"%\"),\n                     expand = expansion(mult = c(0, 0.05))) +\n  labs(x = \"Source classification of pitching team\",\n       y = \"Pitches with an on-air deal\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![Conditional deal proportions by the source's team-composition category, among the 1,434 pitches with a known classification. Each bar is a within-category percentage: P(deal | category).](b04-conditioning-bayes-independence_files/figure-html/fig-b04-team-deal-rates-1.png){#fig-b04-team-deal-rates width=672}\n:::\n:::\n\n\n\n\nRead @fig-b04-team-deal-rates as three conditional proportions, each with its\nown denominator: the 63.6% bar means that 63.6% of the 385 all-women pitch\nrecords reached an on-air deal. The bars use three different reference\nclasses, which is exactly why they can be compared --- each is rescaled\nwithin its own group.\n\n::: {.caveat-box}\n<span class=\"label\">What a conditional probability can and cannot say</span>\n\n**Reversing the condition does not reverse cause.** Bayes' rule converts\n$P(A\\mid B)$ into $P(B\\mid A)$ --- an accounting identity about reference\nclasses. It says nothing about which event influences which:\n$P(D\\mid L) > P(D)$ does not mean late broadcasting causes deals, and a\nflagged pitch is not made more deal-worthy by the flag.\n\n**These are selected televised records.** Every conditional proportion in\nthis lecture describes pitches that producers selected for broadcast. The\nteam-composition comparison uses the source's presenter classification (not\nevery company member, and seven records are unclassified) and does not\nisolate a causal effect of team composition. The classifier example uses\nstated hypothetical rates, not rates estimated from these data. And, as\nalways, an on-air deal is not a completed investment.\n:::\n\n### Answering the driving question\n\nThe two sentences claim different things about the same 505 records:\n\"68.8% of late-season pitches reached a deal\" is $P(D\\mid L)=505/734$, with\nthe late seasons as reference class; \"57.3% of deal pitches came from late\nseasons\" is $P(L\\mid D)=505/882$, with the deals as reference class. Both are\ncorrect; swapping their numbers is the classic conditioning error. And a\npositive flag from the AI deal-predictor tells us less than its 80%\nsensitivity suggests: with a 10% base rate and a 20% false-positive rate,\nonly $80/260\\approx 31\\%$ of flagged pitches are deals --- the flag lifts the\nprobability from 10% to 31%, no further.\n\n**Next:** We can now update the chance of one event when another is known. The\nnatural next step is to watch two numerical measurements at the same time ---\ndeals and seasons, seasons and equity asks --- because business questions are\nusually about relationships, not single variables. Lecture 5 introduces the\njoint distribution of a pair of random variables and the first summaries of\nco-movement, covariance and correlation, together with what a correlation\nnumber does and does not license us to say.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 60 minutes.</span>\n\n### Retrieval (10 minutes)\n\n1. What is the denominator of $P(A\\mid B)$?\n2. Why is $P(A\\mid B)$ generally different from $P(B\\mid A)$?\n3. What makes a collection of events a partition?\n4. What does the denominator in Bayes' rule calculate?\n5. State the two equivalent definitions of independence of events.\n6. Can two disjoint events, each with positive probability, be independent?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. $P(B)$, the probability of the conditioning event.\n2. They condition on different reference classes and therefore have\n   different denominators.\n3. The parts are mutually disjoint and their union is $\\Omega$.\n4. The total probability of the observed evidence, added across all parts of\n   the partition.\n5. $P(A\\mid B)=P(A)$ (learning $B$ does not change the probability of $A$),\n   and the product form $P(A\\cap B)=P(A)\\,P(B)$.\n6. No. Their intersection has probability 0 while the product of their\n   probabilities is positive, so the product check fails. Observing one makes\n   the other impossible.\n:::\n\n### From worked to faded: the Bayes tree (15 minutes)\n\nRe-read the worked count tree (@exm-b04-bayes-tree). Then rebuild it with new\nnumbers: base rate 20%, sensitivity 90%, false-positive rate 30%.\n\n*Step 1 (given).* Start with 1,000 imaginary pitches: 200 deals, 800\nnon-deals.\n\n*Step 2 (you).* Fill in the four leaves: flagged and unflagged counts in\neach branch.\n\n*Step 3 (you).* Collect the flagged pitches and compute\n$P(\\text{deal}\\mid\\text{flag})$.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nOf the 200 deals, 90% are flagged: 180. Of the 800 non-deals, 30% are\nflagged: 240. Flagged total $180+240=420$, of which 180 are deals:\n$P(\\text{deal}\\mid\\text{flag})=180/420\\approx 0.429$. The formula agrees:\n$\\dfrac{0.90\\times 0.20}{0.90\\times 0.20+0.30\\times 0.80}\n=\\dfrac{0.18}{0.42}\\approx 0.429$.\n:::\n\n**Unassisted.** A stricter classifier operates on a population where 5% of\npitches reach a deal; its sensitivity is 90% and its false-positive rate is\n10%. What share of flagged pitches are deals? Use either the tree or the\nformula.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nWith 1,000 pitches: 50 deals of which 45 flagged; 950 non-deals of which 95\nflagged. $P(\\text{deal}\\mid\\text{flag})=45/(45+95)=45/140\\approx 0.321$.\nEven with 90% sensitivity and a low false-positive rate, the 5% base rate\nkeeps the share of true flags below one third.\n:::\n\n### Practice (15 minutes)\n\nUse the counts table: 330, 229, 377, 505, with totals 559, 882, 707, 734,\nand 1,441.\n\n1. Use the early/late partition to verify\n   $P(D)=P(D\\mid L^c)\\,P(L^c)+P(D\\mid L)\\,P(L)$.\n2. Calculate and interpret $P(L\\mid D)$. Explain why it differs from\n   $P(D\\mid L)$.\n3. Decide by calculation whether $D$ and $L$ are independent, using the\n   product form.\n4. The events $L^c$ and $L$ are disjoint. Are they independent? Explain in\n   one sentence.\n5. Among the 1,434 pitches with a known team-composition classification, 428\n   of 661 pitches with women represented (all-women or mixed) and 449 of 773\n   all-men pitches reached an on-air deal. Calculate both conditional deal\n   proportions and interpret the difference.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. $(377/707)(707/1441)+(505/734)(734/1441)=(377+505)/1441=882/1441\n   \\approx 0.612$.\n2. $P(L\\mid D)=505/882\\approx 0.573$: among deal records, 57.3% came from\n   Seasons 9--16. It differs from $P(D\\mid L)=505/734\\approx 0.688$ because\n   the conditioning event --- and therefore the denominator --- is different.\n3. $P(D\\cap L)=505/1441\\approx 0.350$, while\n   $P(D)\\,P(L)=(882/1441)(734/1441)\\approx 0.312$. The two are not equal, so\n   $D$ and $L$ are not independent.\n4. No: $P(L^c\\cap L)=0$ but $P(L^c)\\,P(L)\\approx 0.25>0$, so the product\n   check fails --- disjoint events with positive probability are always\n   dependent.\n5. $428/661\\approx 0.648$ and $449/773\\approx 0.581$, a descriptive\n   difference of about 6.7 percentage points. The comparison uses the\n   source's presenter classification and selected televised pitches; it does\n   not establish a causal effect of team composition.\n:::\n\n### Spaced review: one item from Lecture 3 (5 minutes)\n\nA variable $Y$ has PMF $p_Y(0)=0.2$, $p_Y(1)=0.5$, and $p_Y(2)=0.3$.\nCalculate $E[Y]$ and say in one sentence what the number means, given that\n$Y$ can never equal it exactly... or can it?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$E[Y]=0(0.2)+1(0.5)+2(0.3)=1.1$. It is the probability-weighted average of\nthe possible values --- the long-run average over many repetitions --- and it\nneed not be a value the variable can take: here $Y$ is never 1.1.\n:::\n\n### Worked exam interpretation (10 minutes)\n\n**Question.** A student sees $P(D\\mid L)=0.688$ and writes, \"68.8% of deal\npitches came from late seasons.\"\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nThe calculation conditions on $L$, so the denominator is the 734 pitches in\nSeasons 9--16. The correct interpretation is that 68.8% of late-season\nrecords reached an on-air deal. The sentence the student wrote describes the\nreverse conditional, $P(L\\mid D)=505/882\\approx 57.3\\%$. Neither quantity\nmeasures completed investment or a causal season effect.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA venture --- or any business you know well. Name one signal\nit receives about customers or partners (a positive review, a signed letter\nof intent, a click on an ad) and write two sentences: first state the\nconditional probability the signal makes you want to know, in\n$P(\\cdot\\mid\\cdot)$ form with the reference class named; then say what base\nrate you would need before trusting the signal, Bayes-style. There is no\nwrong answer; the point is connecting today's tools to something you care\nabout.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"I want $P(\\text{becomes a paying customer} \\mid \\text{clicked the ad})$, where the reference class is all students shown the ad this month. Before trusting a high click count I would need the base rate of buyers among all viewers --- with a tiny base rate, most clickers still never buy, exactly the count-tree logic.\"\n:::\n\nYou can discuss this task --- and any other task in this chapter --- with\n**Tilly**, the course AI assistant on Canvas: ask it to build the\nnatural-frequency tree for your signal with numbers you consider realistic.\n::::\n\nContinue to Lecture 5: Joint random variables, covariance, and correlation.\n\nFormula sheet: Lecture 4 formulas.\n\nFor a more formal explanation, consult\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapters 7--8.\n\n:::\n",
    "supporting": [
      "b04-conditioning-bayes-independence_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}