{
  "hash": "962dae8c6fef55b655954806a030fda8",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 3: Coefficient inference, fit, and the F-test {#i03}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 3, you can</span>\n\n- read a coefficient's standard error and build its confidence interval by\n  hand, using the correct degrees of freedom\n- test a regression coefficient against zero and say what the p-value does\n  and does not establish\n- split the variation of the outcome into an explained part and a residual\n  part\n- calculate and interpret $R^2$, and correct four common misreadings\n- state and interpret the overall F-test for model usefulness\n- connect the simple-regression F-test to the slope t-test\n- distinguish fit, statistical evidence, prediction, and causality.\n:::\n\n::: {.must-know}\n<span class=\"label\">Must know</span>\n\n**Be able to do yourself:**\n\n- read a coefficient table: standard error, t value, p-value\n- build a 95% interval for a slope by hand\n- calculate $R^2$ from SST and SSE and say what it is not\n- state the null hypothesis of the overall F-test.\n\n**Enough to recognise:**\n\n- the formula of adjusted $R^2$\n- what robust standard errors fix, and what they do not fix.\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">A slope is an estimate, not a fact. Before a number goes into a pitch deck or a report, we need to know how precise it is and whether the model behind it is of any use.</p>\n\nThe valuation slope is about 0.65. How precisely do we know that number, how\nmuch of the outcome does the line explain, and is the model useful at all?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 30 minutes.</span>\n\n**Minimum path:** the video and the R task. **Full path:** everything in this section.\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation (10 minutes)</span><br>\nWatch Stanford Statistical Learning\n<a href=\"https://www.youtube.com/watch?v=3GiWpRfkSjc&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=10\">3.2\nHypothesis Testing and Confidence Intervals</a>. Focus on the standard error of\nthe slope, its confidence interval, and the test against zero. The video\nwrites RSS for the quantity this book calls SSE. All links\nare also listed in the\n<a href=\"../resources/video-guide.html\">External Video Guide</a>.\n</div>\n\n**Reactivate the recipes (5 minutes).** Write from memory the general recipe\nfor a 95% confidence interval and the two-sided test of a benchmark value.\nThen compare with the blocks for Lectures 9 and 10 of the\n[QM Basic formula sheet](../basic/formula-sheet.qmd#formula-l9).\n[Basic Lecture 9: The t distribution and confidence intervals](../basic/b09-t-confidence-intervals.qmd)\nexplains the interval, and\n[Basic Lecture 10](../basic/b10-testing-errors-power.qmd) explains the\np-value and the test decision. This lecture applies both recipes to a\nregression slope.\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\nInterval: $\\text{estimate} \\pm (\\text{multiplier}) \\times\n\\text{standard error}$, with the multiplier close to 1.96 for large samples.\nTest: $t = (\\text{estimate} - \\text{benchmark})/\\text{standard error}$,\ncompared with a t distribution. Small p-values are evidence against the\nbenchmark.\n:::\n\n**Classify (5 minutes).** Three quantities measure how well a line fits. SSE\nis the sum of squared residuals from Lecture 1. SSR is the part of the\nvariation in the outcome that the line explains. $R^2$ is the share of the\nvariation that the line explains. For a useful model, decide whether each of\nthe three should be relatively small or relatively large. Commit to your\nthree answers. The lecture material defines all three quantities precisely.\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\nFor a useful model, SSE should be relatively small, SSR relatively large,\nand $R^2$ relatively large. These are comparisons to total outcome\nvariation, not universal cut-offs.\n:::\n\n**R warm-up (10 minutes).** Rebuild the Lecture 1 model and print its\ncoefficient table. Bring the table to class:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nvals <- subset(sharks, deal_on_show == 1 & deal_equity_pct > 0)\nvals$claimed_m <- vals$requested_valuation_usd / 1e6\nvals$agreed_m <- vals$deal_valuation_usd / 1e6\nval_model <- lm(agreed_m ~ claimed_m, data = vals)\nsummary(val_model)$coefficients\n```\n:::\n\n\n\n\n**Code along (bring your laptop).** Bring a charged laptop with RStudio and\nthe course project open, so that you can run the code of this chapter\nyourself during the lecture and get the same numbers and figures.\n\nIf you are not sure about squared terms, ratios, or the interval recipe,\nreview\n[Mathematics Refresher: squares, proportions, and standardisation](../resources/math-refresher.html).\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## Lecture material\n\nThis section reads the coefficient table of the valuation model: the\nstandard error, the t value, the p-value, and the confidence interval of the\nslope. It then measures how well the line fits, with $R^2$, and tests whether\nthe model is useful at all, with the F-test.\n\n<p class=\"concept-video\"><strong>Stanford explanation (review):</strong>\n<a href=\"https://www.youtube.com/watch?v=3GiWpRfkSjc\">3.2 Hypothesis Testing and Confidence Intervals</a>.</p>\n\n### Start with a founder's question\n\nThe slope says 65 cents per claimed dollar. Would another set of deals say\n50 cents, or 80? A founder who negotiates with this number wants to know how\nfar it can be off. R and every AI assistant answer with a table of standard\nerrors, t values, and p-values. This lecture shows how to read that table\nand how to check what is said about it.\n\n### How precisely do we know the slope?\n\nThe code below is the warm-up code. It rebuilds the data and the model of\nLecture 1: the valuation agreed on air (`agreed_m`) regressed on the\nvaluation claimed by the founder (`claimed_m`), both in \\$ millions, for the\n874 Shark Tank deals for a share of the company. It then prints the\ncoefficient table.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nvals <- subset(sharks, deal_on_show == 1 & deal_equity_pct > 0)\nvals$claimed_m <- vals$requested_valuation_usd / 1e6\nvals$agreed_m <- vals$deal_valuation_usd / 1e6\nval_model <- lm(agreed_m ~ claimed_m, data = vals)\nsummary(val_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error    t value      Pr(>|t|)\n(Intercept) -0.06798986 0.06847892 -0.9928582  3.210545e-01\nclaimed_m    0.64874084 0.01106883 58.6096854 1.099793e-304\n```\n\n\n:::\n:::\n\n\n\n\nLecture 1 read only the first column, the estimates. The other three\ncolumns, and the interval that R calculates from them, complete the pentad:\nthe five quantities from QM Basic that Lecture 1 reviewed. They work here as\nin QM Basic. Only the quantity that is estimated is new, a slope:\n\n| Pentad ingredient | Where it sits | For the valuation slope |\n|---|---|---:|\n| estimate | `Estimate` column | $\\hat\\beta_1 = 0.649$ |\n| standard error | `Std. Error` column | $\\widehat{\\operatorname{SE}}(\\hat\\beta_1) = 0.0111$ |\n| t value | `t value` column | $t = 58.6$ |\n| p-value | `Pr(>|t|)` column | $< 0.001$ |\n| confidence interval | `confint()` | computed below |\n\nThe 874 deals are all the deals for a share of the company in the file, so\nnothing was sampled from it. We treat them as one outcome of a process that\ncould have produced a different set of deals. A different set of deals would\ngive a slightly different line. The standard error says how much the\nestimated slope $\\hat\\beta_1$ would vary from one such set to the next.\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**Standard error of a coefficient**,\n$\\widehat{\\operatorname{SE}}(\\hat\\beta_1)$. An estimate of how much the\nestimated coefficient would vary from sample to sample. It has the units of\nthe coefficient.\n:::\n\nHere the standard error is 0.0111, in the units of the slope: \\$ million\nagreed per \\$ million claimed. It is small compared with the slope, about 2%\nof 0.649. This number holds under the model assumptions of Lecture 2.\n\n**Degrees of freedom.** The interval multiplier comes from a t distribution\nwith $n - 2 = 874 - 2 = 872$ degrees of freedom. Two is subtracted because\ntwo coefficients, the intercept and the slope, are estimated before the\nspread of the residuals can be estimated. With $k$ slopes and an intercept,\nthe residual degrees of freedom are $n - k - 1$. This general form is needed\nfrom Lecture 4 onwards. The multiplier for a 95% interval is written\n$t_{0.975,\\,872}$. Basic Lecture 9 calls this number the critical value. It\nis the value that a t distribution with 872 degrees of\nfreedom stays below with probability 0.975, so 2.5% lies above it and 2.5%\nlies below its negative. In R it is `qt(0.975, df)`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(0.975, df = df.residual(val_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.962688\n```\n\n\n:::\n:::\n\n\n\n\nWith 872 degrees of freedom the multiplier is 1.963, almost the same as the\n1.96 of the normal distribution.\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**95% confidence interval for a slope.**\n$\\hat\\beta_1 \\pm t_{0.975,\\,n-2}\\,\\widehat{\\operatorname{SE}}(\\hat\\beta_1)$.\nIt is the range of values of the population slope $\\beta_1$ that the data\nare consistent with, under the model assumptions. In large samples the\nmultiplier is close to 1.96.\n:::\n\n::: {#exm-i03-interval}\n## Worked example: the slope interval by hand\n\nEverything comes from the coefficient table. Take the estimate and the\nstandard error with one digit more than in the table above, so that rounding\ndoes not change the result: $\\hat\\beta_1 = 0.6487$ and\n$\\widehat{\\operatorname{SE}}(\\hat\\beta_1) = 0.01107$. The multiplier is about\n1.96.\n\n$$\n\\hat\\beta_1 \\pm t_{0.975,\\,872}\\,\\widehat{\\operatorname{SE}}(\\hat\\beta_1)\n= 0.6487 \\pm 1.96 \\times 0.01107\n= 0.6487 \\pm 0.0217\n= (0.627,\\; 0.670).\n$$\n\nIn words: under the model assumptions, the data are consistent with a\npopulation slope between about 63 and 67 cents of agreed valuation per dollar\nof claimed valuation. A slope of 1, which would mean that the sharks accept\nthe claimed valuation, is far outside this range. The endpoints of the\ninterval have the units of the slope. The estimate, its standard error, and\nthe interval share these units. The t value and the p-value have no units.\n\nR agrees:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(val_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept) -0.2023926 0.06641292\nclaimed_m    0.6270162 0.67046551\n```\n\n\n:::\n:::\n\n\n\n:::\n\nThe interval describes only the variation from sample to sample, under the\nmodel assumptions. It does not cover other sources of doubt: that only\ntelevised pitches are recorded, that only pitches with a deal are analysed,\nor how the valuations are measured. No formula makes an interval wider for a\nweak design.\n\n### The t-test against zero\n\nThe standard test asks whether the data are consistent with no linear\nassociation between $X$ and $Y$, that is, with a population slope of zero.\nThe test is two-sided:\n\n$$\nH_0:\\beta_1=0\n\\qquad\\text{versus}\\qquad\nH_1:\\beta_1\\ne0,\n\\qquad\nt=\\frac{\\hat\\beta_1-0}{\\widehat{\\operatorname{SE}}(\\hat\\beta_1)}.\n$$\n\nBy hand: $t = 0.6487 / 0.01107 \\approx 58.6$. The estimate lies about 59\nstandard errors away from zero. For comparison, a t value beyond about 2 in\neither direction is already rare when the population slope is zero. The\np-value is the probability, if the population slope is zero, of a t value at\nleast this far from zero in either direction. The code below calculates it\nas in QM Basic:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef_table <- summary(val_model)$coefficients\nb1 <- coef_table[\"claimed_m\", \"Estimate\"]\nse_b1 <- coef_table[\"claimed_m\", \"Std. Error\"]\nt_value <- b1 / se_b1\np_value <- 2 * pt(-abs(t_value), df = df.residual(val_model))\nc(estimate = b1, standard_error = se_b1,\n  t_statistic = t_value, p_value = p_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      estimate standard_error    t_statistic        p_value \n  6.487408e-01   1.106883e-02   5.860969e+01  1.099793e-304 \n```\n\n\n:::\n:::\n\n\n\n\nWhat the tiny p-value does say: if the population slope were zero and the\nmodel assumptions held, a sample slope this far from zero would practically\nnever occur. This is strong evidence against a zero slope among these deals.\n\nWhat it does not say:\n\n- It does not say that the model is correct. The fan and the influential\n  deals of Lecture 2 remain a limit on everything in this table.\n- It does not say that the association is large or important. With 874\n  observations, even a very small slope can have a tiny p-value.\n- It does not say that claiming more causes a higher agreed valuation. No\n  test can turn observed deals into an experiment.\n\n::: {.callout-note collapse=\"true\"}\n## Check: the p-value is 1×10^-304^. Is this slope therefore trustworthy?\n\nNo. The p-value measures the distance from zero in standard errors, and the\nstandard error was calculated under the model assumptions, among them\nconstant error variance and independent rows. Lecture 2 showed the fan in\nthe residuals and the few deals that steer the fit, so this standard error\nis doubtful. \"Significant\" means that the data are not consistent with a\nzero slope. It does not mean that 0.0111 is the right standard error.\n:::\n\n### Decomposing variation\n\nThe second part of the driving question asks how much the line explains.\nThis needs a point of comparison. Without a predictor, the best single\nprediction for every deal is the mean agreed valuation $\\bar y$. A\nregression is useful to the extent that its fitted values $\\widehat y_i$\ncome closer to the observed values than this one mean does.\n\nFor each observation, the distance from the mean $\\bar y$ to the observed\nvalue $y_i$ is its total deviation. It splits exactly into two parts. The\npart explained by the line runs from the mean to the fitted value\n$\\widehat y_i$. The residual runs from the fitted value to the observed\nvalue.\n\n$$\n\\underbrace{y_i-\\bar y}_{\\text{total (navy)}}\n=\n\\underbrace{(\\widehat y_i-\\bar y)}_{\\text{explained by the line (green)}}\n+\n\\underbrace{(y_i-\\widehat y_i)}_{\\text{residual (blue)}}.\n$$\n\n@fig-i03-decomposition shows the split for one observation of an invented\nexample. On the left, the green bar (explained by the line) and the blue bar\n(residual) are stacked. On the right, the navy bracket (total) has the same\nheight as the two bars together.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\n# Invented data: eight points, the sixth one is highlighted\nx_d <- c(1, 2, 3, 4, 5, 7, 8.6, 9.6)\ny_d <- c(2.0, 1.7, 3.3, 3.0, 4.0, 8.3, 7.1, 8.0)\nfit_d <- lm(y_d ~ x_d)\ndecomp_df <- data.frame(x = x_d, y = y_d)\ni <- 6\nxh <- x_d[i]                       # x of the highlighted observation\nyh <- y_d[i]                       # its observed value\nfh <- unname(fitted(fit_d)[i])     # its fitted value\nmh <- mean(y_d)                    # the mean of Y\nx_parts <- xh - 2.6                # where the two stacked parts are drawn\nx_total <- xh + 0.7                # where the total is drawn\ncap <- 0.12                        # half-width of the bracket ends\n\nggplot(decomp_df, aes(x = x, y = y)) +\n  geom_hline(yintercept = mh, colour = \"#C98B2E\",\n             linetype = \"dashed\", linewidth = 0.8) +\n  geom_abline(intercept = coef(fit_d)[1], slope = coef(fit_d)[2],\n              colour = \"#D55E00\", linewidth = 0.9) +\n  # dotted guides at the fitted value and at the observed value\n  annotate(\"segment\", x = x_parts, xend = x_total, y = fh, yend = fh,\n           colour = \"#5B6976\", linetype = \"dotted\", linewidth = 0.6) +\n  annotate(\"segment\", x = x_parts, xend = x_total, y = yh, yend = yh,\n           colour = \"#5B6976\", linetype = \"dotted\", linewidth = 0.6) +\n  # the two stacked parts, left of the observation\n  annotate(\"segment\", x = x_parts, xend = x_parts, y = mh, yend = fh,\n           colour = \"#009E73\", linewidth = 2.2) +\n  annotate(\"segment\", x = x_parts, xend = x_parts, y = fh, yend = yh,\n           colour = \"#0072B2\", linewidth = 2.2) +\n  # the total, right of the observation, drawn as a bracket\n  annotate(\"segment\", x = x_total, xend = x_total, y = mh, yend = yh,\n           colour = \"#17324D\", linewidth = 1.1) +\n  annotate(\"segment\", x = x_total - cap, xend = x_total + cap,\n           y = c(mh, yh), yend = c(mh, yh),\n           colour = \"#17324D\", linewidth = 1.1) +\n  # the other observations, the fitted value, and the observed value\n  geom_point(data = decomp_df[-i, ], size = 2.6, colour = \"grey75\") +\n  annotate(\"point\", x = xh, y = fh, shape = 21, size = 3.2, stroke = 1.2,\n           colour = \"#17324D\", fill = \"white\") +\n  annotate(\"point\", x = xh, y = yh, size = 3.6, colour = \"#17324D\") +\n  annotate(\"text\", x = xh, y = yh + 0.55,\n           label = \"y[i]*' (observed)'\", parse = TRUE,\n           colour = \"#17324D\", size = 4.2) +\n  annotate(\"text\", x = xh - 0.2, y = fh + 0.38,\n           label = \"hat(y)[i]*' (on the line)'\", parse = TRUE,\n           hjust = 1, colour = \"#17324D\", size = 4.2) +\n  annotate(\"text\", x = x_parts - 0.25, y = (mh + fh) / 2,\n           label = \"'explained by the line: '*hat(y)[i] - bar(y)\",\n           parse = TRUE, hjust = 1, colour = \"#009E73\", size = 4.2) +\n  annotate(\"text\", x = x_parts - 0.25, y = (fh + yh) / 2,\n           label = \"'residual: '*y[i] - hat(y)[i]\",\n           parse = TRUE, hjust = 1, colour = \"#0072B2\", size = 4.2) +\n  annotate(\"text\", x = x_total + 0.3, y = (mh + fh) / 2,\n           label = \"'total: '*y[i] - bar(y)\",\n           parse = TRUE, hjust = 0, colour = \"#17324D\", size = 4.2) +\n  annotate(\"text\", x = 11.9, y = mh - 0.38,\n           label = \"bar(y)*' (mean of Y)'\", parse = TRUE,\n           hjust = 1, colour = \"#17324D\", size = 4.2) +\n  annotate(\"text\", x = 2.5, y = 1.2, label = \"fitted line\",\n           hjust = 0, colour = \"#D55E00\", size = 4.2) +\n  scale_x_continuous(breaks = seq(0, 12, 2)) +\n  scale_y_continuous(breaks = seq(0, 10, 2)) +\n  coord_cartesian(xlim = c(0, 12), ylim = c(0, 10.5), expand = FALSE) +\n  labs(x = \"Predictor X\", y = \"Outcome Y\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![One observation of an invented example. The dotted lines mark the fitted value and the observed value. Left: the part explained by the line (green, from the mean of Y to the fitted value) and the residual (blue, from the fitted value to the observed value). Right: the total deviation from the mean (navy). The green bar and the blue bar together are exactly as long as the navy bracket.](i03-inference-fit-ftest_files/figure-html/fig-i03-decomposition-1.png){#fig-i03-decomposition width=720}\n:::\n:::\n\n\n\n\nNow square each of the three pieces and add up over all observations. This\ngives three sums of squares. SST is the total sum of squares, SSR is the\nsum of squares explained by the regression, and SSE is the sum of squared\nresiduals from Lecture 1. For a least-squares line with an intercept, the\nsame split holds for the sums:\n\n$$\n\\underbrace{\\sum_i(y_i-\\bar y)^2}_{\\text{SST: total}}\n=\n\\underbrace{\\sum_i(\\widehat y_i-\\bar y)^2}_{\\text{SSR: explained by the line}}\n+\n\\underbrace{\\sum_i(y_i-\\widehat y_i)^2}_{\\text{SSE: residual}}.\n$$\n\nThe code below calculates the three sums for the valuation model and checks\nthat SSR and SSE add up to SST:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- vals$agreed_m\nyhat <- fitted(val_model)\nmean(y)   # mean agreed valuation, in $ millions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.217912\n```\n\n\n:::\n\n```{.r .cell-code}\nSST <- sum((y - mean(y))^2)\nSSR <- sum((yhat - mean(y))^2)\nSSE <- sum((y - yhat)^2)\n\nc(SST = SST, SSR = SSR, SSE = SSE, check = SSR + SSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      SST       SSR       SSE     check \n11926.367  9511.795  2414.572 11926.367 \n```\n\n\n:::\n:::\n\n\n\n\nThe units are squared millions of dollars, so the raw numbers (SST is about\n12,000) mean little on their own. The sums of squares matter only relative\nto each other. The next section compares them.\n\n::: {#exm-i03-sst-sse}\n## Worked example: from SST and SSE to SSR and R²\n\nA regression output reports $\\text{SST} = 500$ and $\\text{SSE} = 125$. Find\nSSR and $R^2$.\n\nBecause $\\text{SST}=\\text{SSR}+\\text{SSE}$, the explained part is\n$\\text{SSR} = \\text{SST} - \\text{SSE} = 500 - 125 = 375$. Then\n\n$$\nR^2 = \\frac{\\text{SSR}}{\\text{SST}} = \\frac{375}{500} = 0.75\n\\qquad\\text{or equivalently}\\qquad\nR^2 = 1 - \\frac{\\text{SSE}}{\\text{SST}} = 1 - \\frac{125}{500} = 0.75.\n$$\n\nThe fitted values account for 75% of the variation of the outcome in the\nsample. The other 25% remains as residual variation around the line.\n:::\n\n### R²: what 0.798 means, and four things it is not\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**$R^2$** (R squared). The share of the variation of the outcome in the\nsample that the fitted line explains:\n\n$$\nR^2=\\frac{\\text{SSR}}{\\text{SST}}\n=1-\\frac{\\text{SSE}}{\\text{SST}}.\n$$\n\nIt lies between 0 and 1.\n:::\n\nFor the valuation model:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(\n  manual = 1 - SSE / SST,\n  from_R = summary(val_model)$r.squared,\n  correlation_squared = cor(vals$claimed_m, vals$agreed_m)^2\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             manual              from_R correlation_squared \n          0.7975434           0.7975434           0.7975434 \n```\n\n\n:::\n:::\n\n\n\n\nHere $R^2 \\approx 0.798$. Among these deals, about 80% of the variation in\nthe agreed valuations is explained by the linear association with the\nclaimed valuation. The third number in the output shows a fact that holds\nin simple regression: $R^2$ is the squared correlation of $X$ and $Y$,\n$R^2 = r_{XY}^2$. Squaring removes the sign, so look at the slope or the\ncorrelation for the direction of the association.\n\n$R^2$ is often misread. Below are four things that it is not, each with a\nwrong sentence and its correction. The first two are worked out here. The\nlast two are in the Try it task.\n\n**Not the percentage of correct predictions.**\n*Wrong:* \"The model predicts 80% of agreed valuations correctly.\"\n*Corrected:* the model explains 80% of the *variation* in agreed valuations.\nSingle predictions can still miss by millions of dollars. The standard\ndeviation of the residuals is about \\$1.66 million, as the output of\n`summary()` shows later in this section.\n\n**Not proof that the assumptions hold.**\n*Wrong:* \"With $R^2$ this high, the model is clearly correct.\"\n*Corrected:* $R^2$ measures fit. It does not check the assumptions. Lecture 2\nfound a fan in the residuals and influential deals in this same model, and\nthe value 0.798 says nothing about either.\n\n::: {.callout-caution collapse=\"true\"}\n## Try it: correct the last two wrong sentences\n\nTry this with your neighbour first. Correct each sentence in one line, as\nabove.\n\n*Sentence 3 (you).* \"The claim explains 80% of the valuation, so claiming\nmore will raise your valuation.\"\n\n*Sentence 4 (you).* \"The model will explain 80% of the differences in\nvaluations in next year's pitches too.\"\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n*Sentence 3* claims causation. $R^2$ describes an association among\nobserved deals. Claims were not randomly assigned, and no measure of fit\nsays what would happen if a founder *changed* the claim.\n*Sentence 4* claims that the fit holds for new data. $R^2$ is calculated on\nthis sample. A new season, a different selection of pitches, or a change in\nhow the sharks negotiate can all lower it. The fit is evidence about these\n874 deals, not a guarantee for the next 874.\n:::\n:::\n\n### The overall F-test\n\nThe last part of the driving question asks whether the model is useful at\nall, compared with predicting the mean $\\bar y$ for every deal. The overall\nF-test answers it. It is stated here for a regression with $k$ predictors,\nbecause Lecture 4 adds more predictors. In this lecture $k=1$.\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**Overall F-test.** A test of the null hypothesis that all slopes of the\nmodel are zero, $H_0:\\beta_1=\\cdots=\\beta_k=0$, against the alternative that\nat least one slope is not zero. The test statistic is\n\n$$\nF=\\frac{\\text{SSR}/k}{\\text{SSE}/(n-k-1)}.\n$$\n\nA large F with a small p-value is evidence that the model explains more than\nthe mean alone.\n:::\n\nRead the ratio part by part. The numerator is the explained variation per\npredictor. The denominator is the residual variation per residual degree of\nfreedom. If no slope differs from zero, the two are of similar size and F is\nnear 1. A large F is evidence that the predictors together matter.\n\nAll numbers of this lecture appear together in the output of `summary()`.\nRead it from top to bottom in this order: (1) the formula and the data, (2)\nthe coefficient estimates and their units, (3) the standard errors, t\nvalues, and p-values, (4) the residual standard error, (5) $R^2$ and adjusted\n$R^2$, (6) the overall F-test. Then remember (7), which the output does not\nprint: the assumptions and the limits of the data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(val_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = agreed_m ~ claimed_m, data = vals)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-7.8172 -0.3968 -0.0064  0.1734 13.4461 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.06799    0.06848  -0.993    0.321    \nclaimed_m    0.64874    0.01107  58.610   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.664 on 872 degrees of freedom\nMultiple R-squared:  0.7975,\tAdjusted R-squared:  0.7973 \nF-statistic:  3435 on 1 and 872 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nTwo lines of this output are new. The **residual standard error**, 1.664, is\nthe standard deviation of the residuals in the units of the outcome:\n$s=\\sqrt{\\text{SSE}/(n-2)}$, here about \\$1.66 million. A few very large\nmisses drive this number: Lecture 2 showed that half of the residuals lie\nbetween $-0.40$ and $0.17$. Still, it is large next to the mean agreed\nvaluation of \\$2.22 million, so single deals can lie far from the line even\nthough $R^2$ is high. **Adjusted $R^2$** is $R^2$ with a small\npenalty for every predictor in the model, $1-(1-R^2)(n-1)/(n-k-1)$. It is\nalways a little below $R^2$. Unlike $R^2$, it can fall when a predictor that\nadds almost nothing is included. That makes it the fairer number for\ncomparing models with different numbers of predictors. With one predictor\nand 874 observations the two hardly differ (0.7975 and 0.7973).\n\nThe last line reports $F \\approx 3435$ on 1 and 872 degrees of freedom. The\np-value is printed as `< 2.2e-16`, which means practically zero. The test\nrejects the null hypothesis: under the model assumptions, the model with the\nclaimed valuation fits better than a model with only an intercept.\n\n**In simple regression, F and t answer the same question.** With one\npredictor, the null hypothesis of the F-test is $H_0:\\beta_1 = 0$, the same\nas in the two-sided t-test of the slope, and\n\n$$\nF = t^2.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_slope <- summary(val_model)$coefficients[\"claimed_m\", \"t value\"]\nf_model <- unname(summary(val_model)$fstatistic[\"value\"])\nc(t_squared = t_slope^2, F = f_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt_squared         F \n 3435.095  3435.095 \n```\n\n\n:::\n:::\n\n\n\n\nBoth equal about 3435. This holds only in simple regression. In multiple\nregression the F-test looks at several slopes together, while each t-test\nlooks at one slope. Lecture 5 uses this difference to test several slopes at\nonce.\n\n### Usefulness has more than one meaning\n\nThe question \"Is the model useful?\" has at least four different meanings,\nand a model can pass one and fail another. The four examples below are\ninvented:\n\n- **Slope clearly different from zero, low $R^2$.** A loyalty-programme\n  analysis on 400,000 customers finds a positive association between\n  mailings and spending. It is precisely estimated, and it explains 1% of\n  the variation in spending. This is useful for a decision about all\n  customers, and useless for predicting the spending of one customer.\n- **High $R^2$, no causal reading.** Store revenue regressed on the number\n  of staff fits very well, because both follow the size of the store.\n  Hiring more staff at a small store will not produce the revenue of a big\n  store.\n- **Good fit on the data used, poor prediction for new data.** A\n  travel-demand model fitted on data for 2015--2019 explained bookings very\n  well and failed in 2020. The $R^2$ of the fitted data never promised that\n  the pattern would continue.\n- **Accurate predictions, no explanation.** A complex prediction model may\n  forecast weekly orders very well while its coefficients do not explain\n  *why* orders change. That is fine for stocking decisions, and useless for\n  planning a price change.\n\nAlways judge a model by the goal: explanation, prediction, or support for a\ndecision.\n\n### Robust standard errors: what they fix {#i03-robust}\n\nHeteroskedasticity-consistent standard errors, called **robust** standard\nerrors for short, do not need the constant-variance assumption. The fitted\ncoefficients stay the ordinary least-squares values. Only the standard\nerrors change, and with them the t values, p-values, and intervals. Lecture 2\nfound a fan in the residuals of this model, so robust standard errors are a\nsensible choice here:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lmtest)\nlibrary(sandwich)\n\ncoeftest(val_model, vcov. = vcovHC(val_model, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.067990   0.087721 -0.7751   0.4385    \nclaimed_m    0.648741   0.033993 19.0846   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncoefci(val_model, vcov. = vcovHC(val_model, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %    97.5 %\n(Intercept) -0.2401587 0.1041790\nclaimed_m    0.5820233 0.7154583\n```\n\n\n:::\n:::\n\n\n\n\nThe function `coeftest()` prints the coefficient table with robust standard\nerrors, and `coefci()` prints the robust 95% confidence intervals. The\nrobust standard error of the slope is 0.034, about three times the usual\n0.0111. The robust 95% interval runs from about 0.58 to 0.72. It is three\ntimes as wide as the usual interval and still lies far below 1.\n\nRobust standard errors fix exactly one problem: an error variance that is\nnot constant. They\ndo not repair a curved relationship, confounding, dependence between rows,\ninfluential data errors, or a selected sample. A robust standard error on a\nbiased slope measures the precision of the wrong number. You do not have to\ncalculate robust standard errors by hand. You should know what they are for.\n\n::: {.caveat-box}\n<span class=\"label\">What a precise slope and a high R² can and cannot say</span>\n\n- Every number of this lecture is calculated under the assumptions of\n  Lecture 2. The fan makes the usual standard error doubtful, and a few\n  deals shape the fit.\n- The data are deals on a television show, not a random sample of\n  companies. This selection affects every estimate.\n- Precision and fit are not causation.\n\n**What you can do with it:** use the slope and its interval for the decision,\nuse the residual standard error to judge how far single cases lie from the\nline, and prefer robust standard errors when the residual plot shows a fan.\n:::\n\n### Answering the driving question\n\nThe slope is known precisely, the line explains much of the outcome, and the\nmodel is useful, all under conditions. The slope 0.649 has standard error\n0.0111. Its 95% interval $(0.627, 0.670)$ is only about four cents per\nclaimed dollar wide. With robust standard errors it is about 13 cents wide,\nfrom 0.58 to 0.72. The t-test clearly rejects a zero slope\n($t \\approx 58.6$). The line explains about 80% of the variation in agreed\nvaluations, and the overall F-test ($F \\approx 3435$) confirms that the\nmodel fits better than the mean alone. All of these statements depend on the\nassumptions checked in Lecture 2, where the residuals showed a fan and a few\ninfluential deals. None of them is causal.\n\n::: {.founder-box}\n<span class=\"label\">A founder's decision (invented example)</span>\n\nYour advertising slope is 0.15 orders per euro, with a standard error of 0.05. The 95% interval runs from 0.05 to 0.25: each 100 euros of advertising goes with between 5 and 25 extra orders. At 4 euros of margin per order, that is between 20 and 100 euros. Even the best case only breaks even. The decision: reduce the advertising budget. The model has an $R^2$ of 0.20, so it predicts single weeks badly. That does not matter here. The decision depends on the slope and its interval, not on predicting next week.\n:::\n\n**Next:** Tutorial 1 practises Lectures 1--3 in the format of the exam: fit a\nmodel in R, check its residuals, and report its coefficients with intervals,\ntests, and $R^2$. The exam is taken in TestVision with R available.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 80 minutes.</span>\n\n**Minimum path (about 35 minutes):** read the lecture material, answer the recall questions, then work for 10 minutes on the tasks that follow. **Full path:** all tasks below.\n\n### Read the lecture material (15 minutes)\n\nRead the Lecture material section above from start to end. The lecture\ncovered the core of it. The text has every step, every example, and all the\ncode, including parts that were not shown in class. Note what is still\nunclear and bring it to the next tutorial, or ask Tilly.\n\n### Recall questions (10 minutes)\n\n1. Why are the residual degrees of freedom $n-2$ in simple regression?\n2. Which pentad quantities share the slope's units, and which are\n   unit-free?\n3. What do SST, SSR, and SSE measure, and how are they related?\n4. Why is $R^2$ between 0 and 1 in an OLS model with an intercept?\n5. What is the null hypothesis of the overall F-test, and why does $F=t^2$\n   in simple regression?\n6. What single problem do robust standard errors address?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. Two coefficients, intercept and slope, are estimated before\n   residual variation can be measured, using up two pieces of information.\n2. The estimate, its SE, and the interval endpoints share the slope's\n   units. The t statistic and p-value are unit-free.\n3. Total, explained (fitted), and residual sample variation in the outcome.\n   $\\text{SST}=\\text{SSR}+\\text{SSE}$ for OLS with an intercept.\n4. SSE is non-negative and no larger than SST, so $1-\\text{SSE}/\\text{SST}$\n   lies between 0 and 1.\n5. All population slope coefficients are zero. With one predictor that is\n   the same hypothesis as the two-sided slope t-test, and $F=t^2$.\n6. An error variance that is not constant, and nothing else.\n:::\n\n### Finish a half-worked example: an interval for a new row (15 minutes)\n\nRe-read the worked slope interval (@exm-i03-interval). Then build the\ninterval for the **intercept row** of the same table.\n\n*Step 1 (given).* From the coefficient table: estimate $-0.068$, standard\nerror $0.0685$, degrees of freedom $872$, multiplier $\\approx 1.96$.\n\n*Step 2 (you).* Compute the 95% interval.\n\n*Step 3 (you).* Interpret it in one sentence, and say why this interval is of\nlittle use for a business decision (see the intercept in Lecture 1).\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$-0.068 \\pm 1.96 \\times 0.0685 = -0.068 \\pm 0.134 = (-0.202,\\; 0.066)$, in\n\\$ millions, which matches R. Under the model assumptions, the data are\nconsistent with a population intercept between about $-\\$202{,}000$ and\n\\$66,000. The interval includes zero, so the line may well pass through the\norigin. But the intercept is the fitted mean at a claimed valuation of zero,\noutside the observed range of claims. The interval is calculated correctly\nand still tells a founder little.\n:::\n\nThen four more tasks without given steps:\n\n1. A study reports a coefficient of 2.40 with standard error 0.80 in a\n   large sample. Compute the t statistic, decide the 5% two-sided test\n   against zero, and give the 95% interval.\n2. Interpret $R^2=0.20$ without calling the model \"80% wrong.\"\n3. A model has $k=3$, $n=104$, SSR = 300, and SSE = 500. Calculate $R^2$\n   and F.\n4. Explain why adding a predictor to a least-squares model cannot increase\n   its SSE.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. $t = 2.40/0.80 = 3$. Reject at 5% (well beyond 1.96). Interval:\n   $2.40 \\pm 1.96 \\times 0.80 = (0.83,\\; 3.97)$.\n2. The fitted values explain 20% of the variation of the outcome in the\n   sample. 80% remains as residual variation around the fitted line. Nothing\n   is \"wrong\". The fitted values are simply far from many single outcomes.\n3. $\\text{SST}=300+500=800$, so $R^2=300/800=0.375$.\n   $F=(300/3)/(500/(104-3-1))=100/5=20$.\n4. The larger model can reproduce the old fit by setting the new slope to\n   zero. Least squares picks the smallest SSE, so the SSE of the larger\n   model cannot be above the old one.\n:::\n\n### Practice: all steps on equity and season (20 minutes)\n\nFit `equity_offered_pct ~ season` on all 1,441 pitches. Report the slope's\n95% confidence interval, the t-test against zero, $R^2$, and the overall\nF-test, then write a 120-word conclusion that separates estimate,\nuncertainty, fit, and scope.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nequity_model <- lm(equity_offered_pct ~ season, data = sharks)\nsummary(equity_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error   t value      Pr(>|t|)\n(Intercept) 20.4565874 0.46442667  44.04697 4.922706e-269\nseason      -0.8241241 0.04752298 -17.34159  2.514546e-61\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(equity_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept) 19.5455616 21.3676132\nseason      -0.9173458 -0.7309023\n```\n\n\n:::\n\n```{.r .cell-code}\nc(r_squared = summary(equity_model)$r.squared,\n  F = unname(summary(equity_model)$fstatistic[\"value\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  r_squared           F \n  0.1728605 300.7308055 \n```\n\n\n:::\n:::\n\n\n\n\nA complete conclusion reports four things. Estimate: one later season\n(`season`) is associated with about 0.824 percentage points less equity\noffered (`equity_offered_pct`), with standard error 0.048. Uncertainty: the\n95% interval $(-0.917, -0.731)$ excludes zero, and the t-test rejects a zero\nslope ($t\\approx-17.3$, p $<$ 0.001). Fit: the season explains about 17.3%\nof the variation in the equity offered, and the overall F-test\n($F\\approx300.7 = t^2$) rejects the model with only an intercept. Scope:\nthis is a trend over time among recorded pitches, not a causal effect of\nthe season, and the standard errors rest on the assumptions of Lecture 2.\n:::\n\n### Review: one diagnostics question from Lecture 2 (5 minutes)\n\nThe residual-versus-fitted plot of the valuation model shows unequal spread,\nthe fan of Lecture 2. Which numbers of the coefficient table in this lecture\ndoes that pattern put most directly in doubt, and why?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe standard error 0.0111, and with it the t value, the p-value, and the\nconfidence interval that are built from it. The usual formula for the\nstandard error assumes one common error variance $\\sigma^2$. A fan says that\nthe variance is not constant, so the stated precision is doubtful. Robust\nstandard errors address exactly this one problem. They repair nothing else.\n:::\n\n### Worked exam interpretation (5 minutes)\n\n**Question** (mock exam Question 3 pattern). A model of venture sales\ngrowth (percentage points) on marketing spending (€10,000s), fitted on\n$n = 102$ ventures, reports a slope of 1.38 with standard error 0.46,\n$R^2 = 0.083$, and $F = 9.0$. Build the 95% interval for the slope, decide\nthe 5% test against zero, verify the F statistic from the t statistic, and\nstate in one sentence what the low $R^2$ does and does not imply.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\n$t = 1.38/0.46 = 3.0$. With $n-2 = 100$ degrees of freedom the multiplier\n`qt(0.975, 100)` is about 1.98, so the\ninterval is $1.38 \\pm 1.98\\times0.46 \\approx (0.47,\\; 2.29)$ percentage\npoints per €10,000. The interval excludes zero, so the two-sided 5% test\nrejects $H_0:\\beta_1=0$. In agreement with this, $F = t^2 = 9.0$. The low\n$R^2$ says that marketing spending explains about 8% of the variation in\ngrowth, so predictions for single ventures will be poor. It does not remove\nthe evidence that the association is not zero. Neither number makes the\nassociation causal.\n:::\n\n### Check the AI (5 minutes)\n\nYou asked an AI assistant: \"R squared is 0.80 and the p-value is below 0.001. Is my model good?\" It answered:\n\n> \"Yes. The model predicts 80% of the valuations correctly, and the tiny p-value proves that the model assumptions hold.\"\n\nFind what is wrong and write the corrected answer. This is the **Verify**\nstep of Attempt → Ask → Verify → Explain, and the exam asks for it.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nTwo errors. R squared is the share of the variation that the line explains, not a share of correct predictions. Single predictions can still miss by millions of dollars (the residual standard error is about 1.7 million). And the p-value is calculated under the assumptions. It cannot prove them. Lecture 2 showed a fan in the residuals, so the standard error behind this p-value is doubtful.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA3 venture, or any business you know well, and one\nregression you might run on its data. Write two sentences: first say which\nyou would rather have for your next decision, a precise slope (narrow\ninterval) or a high $R^2$, and why. Then name the meaning of \"useful\" from\nthe list of four in this lecture that matters most for that decision. There\nis no wrong answer. Precision and fit answer different questions.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"For setting next month's ad budget I would take a precise slope over a high $R^2$: I need to know what an extra €100 buys, even if week-to-week orders stay noisy. That is the first meaning on the list, a reliable slope with a low $R^2$: predicting individual weeks matters less to me than the payoff of an input I control.\"\n:::\n\nYou can discuss this task, and any other task in this chapter, with\n**Tilly**, the course AI assistant: ask it to invent a business\nmodel with a significant slope and a low $R^2$ and challenge you to say\nwhat the model is still useful for.\n::::\n\n[Continue to Tutorial 1: Simple regression, diagnostics, and model usefulness](t01-exam-prep.qmd).\n\n[Code sheet: Lecture 3 commands and formulas](code-sheet.qmd#lecture-3-coefficient-inference-fit-and-the-f-test).\n\nFor a more formal treatment, see James et al., *An Introduction to\nStatistical Learning*, 2nd ed., Sections 3.1.2--3.1.3, and\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapters 19--20.\n\n:::\n",
    "supporting": [
      "i03-inference-fit-ftest_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}