{
  "hash": "dce2874f2d3b5d8b963ada13072dc0eb",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 1: Simple linear regression {#i01}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 1, you can</span>\n\n- state a simple linear regression model and identify its components;\n- read the slope as a difference of conditional means, with units;\n- convert a coefficient between measurement units (dollars, $1,000s,\n  $100,000s);\n- distinguish observations, fitted values, errors, and residuals;\n- explain what least squares minimises and why;\n- compute a slope and intercept by hand on a tiny dataset;\n- fit a regression with `lm()` in R and interpret both coefficients within\n  the observed range.\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">The first question of deal-making: does asking for more get you more? A line fitted through the data turns that vague hunch into one number a founder can actually use.</p>\n\nAmong pitches that reached a deal, does asking for more money go together\nwith getting more money --- and by how much per dollar asked?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 30 minutes.</span>\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation (10 minutes)</span><br>\nWatch Stanford Statistical Learning\n<a href=\"https://www.youtube.com/watch?v=vCHtY6Me5FI&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=9\">3.1\nSimple Linear Regression</a>. Focus on the population line, the fitted line,\nand least squares. All links are also listed in the\n<a href=\"../resources/video-guide.html\">External Video Guide</a>.\n</div>\n\n**Reactivate the pentad (10 minutes).** QM Intermediate builds directly on\nthe five quantities you met at the end of QM Basic --- estimate, standard\nerror, t value, p-value, confidence interval. With the Basic formula sheet\nopen, answer the five items below.\n\n1. A study reports an estimate of 12 with standard error 4. What is the t\n   value for testing whether the underlying quantity is zero?\n2. With a large sample, what multiplier goes into a 95% confidence interval?\n3. Compute that 95% interval for the estimate in item 1.\n4. The p-value is 0.003. Complete: \"If the true value were zero, ...\"\n5. Which of the five quantities has the same units as the estimate itself?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. $t = 12/4 = 3$.\n2. Approximately 1.96 (the t multiplier is close to the normal 1.96 when the\n   degrees of freedom are large).\n3. $12 \\pm 1.96 \\times 4 = (4.2,\\; 19.8)$.\n4. \"... an estimate at least this far from zero would occur in about 0.3% of\n   samples.\"\n5. The standard error and both interval endpoints; the t value and p-value\n   are unit-free.\n:::\n\n**Define the variables (2 minutes).** For the 882 pitches with an on-air\ndeal, this lecture works in **thousands of dollars**:\n\n- $Y_i$: agreed on-air deal amount, in $1,000s;\n- $X_i$: amount initially requested, in $1,000s.\n\nA pitch that asked for \\$300,000 and agreed \\$250,000 has $X_i = 300$ and\n$Y_i = 250$.\n\n**Predict (3 minutes).** Answer the one-click Mentimeter question posted on\nCanvas before you come to class: what are the **sign** and the **unit** of\nthe slope in a regression of agreed amount on requested amount? Commit to an\nanswer; the lecture resolves it.\n\n**R warm-up (5 minutes).** The standing warm-up for every Intermediate\nlecture: run a few lines of R and bring the output to class. This week, load\nthe data, subset the deals, and plot agreed amount against requested amount:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ndeals <- subset(sharks, deal_on_show == 1)\ndeals$ask_1k <- deals$ask_amount_usd / 1000\ndeals$deal_1k <- deals$deal_amount_usd / 1000\nplot(deals$ask_1k, deals$deal_1k)\n```\n:::\n\n\n\n\nIf lines, slopes, intercepts, or subscripts are not secure, review\n[Mathematics Refresher: straight lines and indices](../resources/math-refresher.html).\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In class\n\nThe session opens with the usual four-minute entry quiz on the prep videos,\nthen turns to the driving question.\n\n<p class=\"concept-video\"><strong>Stanford explanation (review):</strong>\n<a href=\"https://www.youtube.com/watch?v=vCHtY6Me5FI\">3.1 Simple Linear Regression</a>.</p>\n\n### Begin with the data\n\nThe warm-up plot, polished. The construction is exactly the warm-up code:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ndeals <- subset(sharks, deal_on_show == 1)\ndeals$ask_1k <- deals$ask_amount_usd / 1000\ndeals$deal_1k <- deals$deal_amount_usd / 1000\nnrow(deals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 882\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ndeals <- subset(sharks, deal_on_show == 1)\ndeals$ask_1k <- deals$ask_amount_usd / 1000\ndeals$deal_1k <- deals$deal_amount_usd / 1000\ndeal_model <- lm(deal_1k ~ ask_1k, data = deals)\ndisplay_deals <- subset(deals, ask_1k <= 1000 & deal_1k <= 1000)\n\nggplot(display_deals, aes(x = ask_1k, y = deal_1k)) +\n  geom_point(alpha = 0.45, size = 1.6, colour = \"#009E73\") +\n  geom_abline(intercept = coef(deal_model)[1],\n              slope = coef(deal_model)[2],\n              colour = \"#D55E00\", linewidth = 0.9) +\n  annotate(\"text\", x = 40, y = 985,\n           label = \"Fitted regression (estimated on all 882 deals)\",\n           colour = \"#D55E00\", size = 3.4, hjust = 0) +\n  coord_cartesian(xlim = c(0, 1030), ylim = c(0, 1030), expand = FALSE) +\n  labs(x = \"Amount requested ($1,000s)\",\n       y = \"Agreed on-air deal amount ($1,000s)\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![Agreed on-air deal amount against amount requested, for the 882 pitches with a deal. Both axes in $1,000s. The display zooms in on requests and deals up to $1 million (864 of 882 records); the orange least-squares line is fitted on all 882.](i01-simple-linear-regression_files/figure-html/fig-i01-scatter-1.png){#fig-i01-scatter width=672}\n:::\n:::\n\n\n\n\nEach point in @fig-i01-scatter is one pitch with an on-air deal. Read\nrequested amount horizontally and agreed amount vertically; both axes use\nunits of $1,000. The orange line gives the fitted conditional mean, not the\noutcome of every pitch. The display shows 864 of the 882 deal records so\nthat the dense region is readable. Eighteen records above \\$1 million on at\nleast one axis are omitted from this display but retained when estimating\nthe orange line. Always say when a graph is zoomed; otherwise readers may\nmistake the displayed range for the complete data.\n\n### Units first: money in thousands\n\nEvery number this lecture produces carries the units of these two columns,\nso settle the units before any model. We divide raw dollar amounts by 1,000:\na request of \\$300,000 becomes `ask_1k = 300`. Scaling changes nothing about\nthe relationship; it only makes axes and coefficients readable\n(`ask_amount_usd = 300000` and `ask_1k = 300` are the same fact).\n\n::: {#exm-i01-units}\n## Worked example: the same coefficient in three unit systems\n\nLater in this lecture, R will print an intercept of about 27.571 with both\nvariables in $1,000s. Two lines of arithmetic read it:\n\n$$\n27.571 \\text{ (in \\$1,000s)} = 27.571 \\times \\$1{,}000 = \\$27{,}571.\n$$\n\nSuppose a published paper measures both variables in \\$100,000s instead.\nDividing both $Y$ and $X$ by a further 100 shrinks the intercept by that\nfactor but leaves the slope untouched, because the slope is a ratio of the\ntwo:\n\n$$\n\\text{intercept: } 27.571 / 100 = 0.276 \\text{ (in \\$100,000s)},\n\\qquad\n\\text{slope: } 1.0085 \\text{ (unchanged)}.\n$$\n\nAnd in raw dollars? Multiplying both variables by 1,000 gives an intercept\nof $27.571 \\times 1000 = 27{,}571$ dollars --- and again the same slope,\n1.0085 dollars per dollar. The general rule: rescaling the outcome and the\npredictor by the **same** factor moves the intercept and leaves the slope\nalone; rescaling only one of them rescales the slope by that factor. When\ntwo sources disagree about a coefficient, check the units before suspecting\nthe analysis.\n:::\n\n### The population model and the conditional mean\n\nThe simple linear regression model is\n\n$$\nY_i=\\beta_0+\\beta_1X_i+\\varepsilon_i.\n$$\n\nEquivalently, the conditional mean is\n\n$$\nE[Y_i\\mid X_i=x]=\\beta_0+\\beta_1x.\n$$\n\n- $Y_i$ is the outcome for observation $i$.\n- $X_i$ is the predictor.\n- $\\beta_0$ is the population intercept.\n- $\\beta_1$ is the population slope.\n- $\\varepsilon_i$ is the part of $Y_i$ not represented by the line.\n\nThe slope is a **difference of conditional means**:\n\n$$\n\\beta_1\n=E[Y\\mid X=x+1]-E[Y\\mid X=x].\n$$\n\nIt is the expected difference in $Y$ **associated with** a one-unit\ndifference in $X$ --- here, the expected difference in agreed amount between\npitches whose requests differ by \\$1,000. \"Associated with\" is deliberate,\nand this is the one place the phrase is flagged: a regression line alone\ncompares averages across observed groups; it does not identify what would\nhappen if a given pitch *changed* its request. The caveat box at the end of\nthe lecture collects the full scope statement.\n\n### Errors versus residuals\n\nThe population line is a model statement; nobody has seen it. What we\ncompute from data is the fitted sample line\n\n$$\n\\widehat Y_i=b_0+b_1X_i,\n$$\n\nand, for each observation, the **residual** --- the vertical difference\n\n$$\ne_i=Y_i-\\widehat Y_i.\n$$\n\nThe error $\\varepsilon_i$ and the residual $e_i$ play parallel roles in the\ntwo equations but are different objects, as @fig-i01-error-residual shows.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nset.seed(101)\nx_er <- c(1, 2.2, 3.4, 4.6, 5.8, 7.0, 8.2)\nbeta0_true <- 1; beta1_true <- 0.8\ny_er <- beta0_true + beta1_true * x_er + c(1.3, -1.5, 0.9, -0.8, 1.6, -1.2, 0.4)\nfit_er <- lm(y_er ~ x_er)\n\npanel_names <- c(\"Population line (unknown)\", \"Fitted line (computed)\")\ner_df <- data.frame(\n  panel = factor(rep(panel_names, each = 7), levels = panel_names),\n  x = rep(x_er, 2),\n  y = rep(y_er, 2),\n  line_y = c(beta0_true + beta1_true * x_er, fitted(fit_er))\n)\nline_df <- data.frame(\n  panel = factor(panel_names, levels = panel_names),\n  intercept = c(beta0_true, coef(fit_er)[1]),\n  slope = c(beta1_true, coef(fit_er)[2])\n)\nlabel_df <- data.frame(\n  panel = factor(panel_names, levels = panel_names),\n  x = x_er[5] + 0.45,\n  y = c((y_er[5] + beta0_true + beta1_true * x_er[5]) / 2,\n        (y_er[5] + fitted(fit_er)[5]) / 2),\n  lab = c(\"epsilon[i]\", \"e[i]\")\n)\n\nggplot(er_df, aes(x = x, y = y)) +\n  geom_abline(data = line_df[1, ],\n              aes(intercept = intercept, slope = slope),\n              colour = \"#5B6976\", linewidth = 0.9, linetype = \"dashed\") +\n  geom_abline(data = line_df[2, ],\n              aes(intercept = intercept, slope = slope),\n              colour = \"#D55E00\", linewidth = 0.9) +\n  geom_segment(aes(xend = x, yend = line_y),\n               colour = \"#0072B2\", linewidth = 0.8) +\n  geom_point(size = 2.6, colour = \"#009E73\") +\n  geom_text(data = label_df, aes(x = x, y = y, label = lab),\n            parse = TRUE, colour = \"#0072B2\", size = 4) +\n  coord_cartesian(xlim = c(0, 9.4), ylim = c(0, 9.4)) +\n  facet_wrap(~ panel) +\n  labs(x = \"Predictor X\", y = \"Outcome Y\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\"),\n    strip.text = element_text(colour = \"#17324D\", face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![The same seven observations twice. Left: the unknown population line with the errors ε (distances to the true line). Right: the fitted least-squares line with the residuals e (distances to the estimated line). Only the right panel can be computed from data.](i01-simple-linear-regression_files/figure-html/fig-i01-error-residual-1.png){#fig-i01-error-residual width=768}\n:::\n:::\n\n\n\n\n- $\\varepsilon_i = Y_i - (\\beta_0+\\beta_1X_i)$ measures the distance to the\n  **population** line. Because $\\beta_0$ and $\\beta_1$ are unknown,\n  $\\varepsilon_i$ is never observed.\n- $e_i = Y_i - (b_0+b_1X_i)$ measures the distance to the **fitted** line.\n  It is computed from data, one number per observation.\n\nResiduals are our window on the errors, but they are estimates, not the\nthing itself --- Lecture 2 lives entirely in that window.\n\n::: {.callout-note collapse=\"true\"}\n## Check: which object is observable?\n\nOnly the residual $e_i$. The observed data give $Y_i$ and $X_i$; the fitted\nline gives $\\widehat Y_i$, so $e_i = Y_i - \\widehat Y_i$ is a computable\nnumber. The error $\\varepsilon_i$ depends on the unknown population\ncoefficients $\\beta_0$ and $\\beta_1$, so it can be reasoned about but never\ncalculated.\n:::\n\n### Least squares: why vertical, why squared\n\nFor observation $i$, the model predicts $\\widehat Y_i$ at its observed\n$X_i$. The residual $e_i=Y_i-\\widehat Y_i$ is therefore a difference in the\n**outcome's units** --- thousands of dollars of agreed amount, not distance\non the page. A positive residual lies above the line; a negative residual\nlies below it.\n\nAdding raw residuals is not a useful score: positive and negative misses\ncan cancel. Adding absolute residuals avoids cancellation, but the resulting\nobjective has sharp corners and is harder to optimise algebraically. Squared\nresiduals are non-negative, penalise large misses more strongly, and give a\nsmooth objective with a tractable solution. This is a modelling choice, not\na claim that squared error is the only possible loss function.\n\nOrdinary least squares chooses $b_0$ and $b_1$ to minimise\n\n$$\n\\operatorname{SSE}=\\sum_{i=1}^{n}e_i^2\n=\\sum_{i=1}^{n}(Y_i-b_0-b_1X_i)^2.\n$$\n\nThe initials **OLS** stand for **ordinary least squares**: the rule that\nfits the linear model by minimising this squared-error criterion.\n\n#### Try the criterion yourself\n\nDrag either square handle. The vertical segments are residuals; the\ndisplayed SSE updates after every move. In class the widget stays open over\nthe break with a target SSE to beat; then reveal the line with the smallest\nSSE.\n\n<style>\n.ls-lab {\n  background: #fff;\n  border: 1px solid #d5dbe0;\n  border-radius: 8px;\n  margin: 1.2em 0 1.5em;\n  padding: 1em;\n}\n.ls-lab-heading,\n.ls-actions {\n  align-items: center;\n  display: flex;\n  flex-wrap: wrap;\n  gap: 0.8em 1.2em;\n  justify-content: space-between;\n}\n.ls-lab svg {\n  display: block;\n  height: auto;\n  margin: 0.5em auto;\n  max-width: 700px;\n  touch-action: none;\n  width: 100%;\n}\n.ls-controls {\n  display: grid;\n  gap: 0.8em 1.4em;\n  grid-template-columns: repeat(2, minmax(0, 1fr));\n  margin: 0.6em 0 1em;\n}\n.ls-controls label {\n  color: #17324d;\n  font-size: 0.9em;\n  font-weight: 600;\n}\n.ls-controls input {\n  display: block;\n  margin-top: 0.3em;\n  width: 100%;\n}\n.ls-actions button {\n  background: #17324d;\n  border: 1px solid #17324d;\n  border-radius: 4px;\n  color: #fff;\n  cursor: pointer;\n  font: inherit;\n  padding: 0.45em 0.8em;\n}\n.ls-actions button + button {\n  background: #fff;\n  color: #17324d;\n}\n.ls-caption {\n  color: #53606b;\n  font-size: 0.9em;\n  margin-bottom: 0;\n}\n.ls-axis { stroke: #65727e; stroke-width: 1.2; }\n.ls-tick { fill: #53606b; font-size: 13px; }\n.ls-label { fill: #263b4b; font-size: 15px; }\n.ls-point { fill: #0072b2; stroke: #17324d; stroke-width: 1; }\n.ls-fit-line { stroke: #d55e00; stroke-width: 3; }\n.ls-residual { stroke: #755f93; stroke-width: 2; stroke-dasharray: 4 3; }\n.ls-handle { fill: #f0e442; stroke: #17324d; stroke-width: 2; cursor: ns-resize; }\n.ls-handle:focus { outline: 3px solid #56b4e9; outline-offset: 2px; }\n@media (max-width: 767px) {\n  .ls-controls {\n    grid-template-columns: 1fr;\n  }\n}\n</style>\n\n<div id=\"least-squares-lab\" class=\"ls-lab\" role=\"group\" aria-labelledby=\"ls-lab-title\">\n<div class=\"ls-lab-heading\">\n<strong id=\"ls-lab-title\">Least-squares line lab</strong>\n<span id=\"ls-equation\" aria-live=\"polite\"></span>\n</div>\n<svg id=\"ls-svg\" viewBox=\"0 0 700 390\" role=\"img\" aria-label=\"Scatterplot with a draggable line and vertical residual segments\"></svg>\n<div class=\"ls-controls\">\n<label>Line height at x = 1\n<input id=\"ls-left\" type=\"range\" min=\"0\" max=\"10\" step=\"0.05\" value=\"3\">\n</label>\n<label>Line height at x = 9\n<input id=\"ls-right\" type=\"range\" min=\"0\" max=\"10\" step=\"0.05\" value=\"7\">\n</label>\n</div>\n<div class=\"ls-actions\">\n<button id=\"ls-best\" type=\"button\">Show least-squares fit</button>\n<button id=\"ls-reset\" type=\"button\">Try another line</button>\n<strong id=\"ls-sse\" aria-live=\"polite\"></strong>\n</div>\n<p class=\"ls-caption\">Squares make every contribution to SSE non-negative. Longer residuals contribute disproportionately because their lengths are squared.</p>\n</div>\n\n<script>\n(function () {\n  const root = document.getElementById(\"least-squares-lab\");\n  if (!root || root.dataset.ready) return;\n  root.dataset.ready = \"true\";\n  const svg = root.querySelector(\"#ls-svg\");\n  const left = root.querySelector(\"#ls-left\");\n  const right = root.querySelector(\"#ls-right\");\n  const equation = root.querySelector(\"#ls-equation\");\n  const sseText = root.querySelector(\"#ls-sse\");\n  const points = [\n    {x:1, y:1.8}, {x:2, y:1.4}, {x:3, y:3.2},\n    {x:4, y:4.8}, {x:5, y:4.2}, {x:6, y:6.8},\n    {x:7, y:6.4}, {x:8, y:8.6}, {x:9, y:8.2}\n  ];\n  const ns = \"http://www.w3.org/2000/svg\";\n  const box = {left:58, right:680, top:18, bottom:336};\n  const sx = x => box.left + x / 10 * (box.right - box.left);\n  const sy = y => box.bottom - y / 10 * (box.bottom - box.top);\n  const add = (name, attrs, parent=svg) => {\n    const el = document.createElementNS(ns, name);\n    Object.entries(attrs).forEach(([k,v]) => el.setAttribute(k, v));\n    parent.appendChild(el); return el;\n  };\n  add(\"line\", {x1:box.left, y1:box.bottom, x2:box.right, y2:box.bottom, class:\"ls-axis\"});\n  add(\"line\", {x1:box.left, y1:box.top, x2:box.left, y2:box.bottom, class:\"ls-axis\"});\n  [0,2,4,6,8,10].forEach(v => {\n    add(\"line\", {x1:sx(v), y1:box.bottom, x2:sx(v), y2:box.bottom+6, class:\"ls-axis\"});\n    const tx=add(\"text\", {x:sx(v), y:box.bottom+25, class:\"ls-tick\"}); tx.textContent=v;\n    add(\"line\", {x1:box.left-6, y1:sy(v), x2:box.left, y2:sy(v), class:\"ls-axis\"});\n    const ty=add(\"text\", {x:box.left-12, y:sy(v)+4, class:\"ls-tick\", \"text-anchor\":\"end\"}); ty.textContent=v;\n  });\n  const xl=add(\"text\", {x:(box.left+box.right)/2, y:382, class:\"ls-label\", \"text-anchor\":\"middle\"}); xl.textContent=\"Predictor x\";\n  const yl=add(\"text\", {x:16, y:(box.top+box.bottom)/2, class:\"ls-label\", transform:`rotate(-90 16 ${(box.top+box.bottom)/2})`, \"text-anchor\":\"middle\"}); yl.textContent=\"Outcome y\";\n  const residualGroup=add(\"g\", {class:\"ls-residuals\"});\n  const line=add(\"line\", {class:\"ls-fit-line\"});\n  const handleLeft=add(\"rect\", {width:16, height:16, rx:2, class:\"ls-handle\", \"aria-hidden\":\"true\"});\n  const handleRight=add(\"rect\", {width:16, height:16, rx:2, class:\"ls-handle\", \"aria-hidden\":\"true\"});\n  points.forEach(p => add(\"circle\", {cx:sx(p.x), cy:sy(p.y), r:5.5, class:\"ls-point\"}));\n  const meanX=points.reduce((a,p)=>a+p.x,0)/points.length;\n  const meanY=points.reduce((a,p)=>a+p.y,0)/points.length;\n  const bestSlope=points.reduce((a,p)=>a+(p.x-meanX)*(p.y-meanY),0) /\n                  points.reduce((a,p)=>a+(p.x-meanX)**2,0);\n  const bestIntercept=meanY-bestSlope*meanX;\n  const fitFromHeights = () => {\n    const y1=Number(left.value), y9=Number(right.value);\n    const slope=(y9-y1)/8, intercept=y1-slope;\n    return {intercept, slope};\n  };\n  function draw() {\n    const {intercept, slope}=fitFromHeights();\n    residualGroup.replaceChildren();\n    let sse=0;\n    points.forEach(p => {\n      const fitted=intercept+slope*p.x;\n      sse+=(p.y-fitted)**2;\n      add(\"line\", {x1:sx(p.x), y1:sy(p.y), x2:sx(p.x), y2:sy(fitted), class:\"ls-residual\"}, residualGroup);\n    });\n    line.setAttribute(\"x1\", sx(0)); line.setAttribute(\"y1\", sy(intercept));\n    line.setAttribute(\"x2\", sx(10)); line.setAttribute(\"y2\", sy(intercept+10*slope));\n    [[handleLeft,1,Number(left.value)],[handleRight,9,Number(right.value)]].forEach(([h,x,y])=>{\n      h.setAttribute(\"x\",sx(x)-8); h.setAttribute(\"y\",sy(y)-8);\n    });\n    equation.textContent=`ŷ = ${intercept.toFixed(2)} ${slope<0?\"−\":\"+\"} ${Math.abs(slope).toFixed(2)}x`;\n    sseText.textContent=`SSE = ${sse.toFixed(2)}`;\n  }\n  function drag(handle, slider) {\n    handle.addEventListener(\"pointerdown\", event => {\n      handle.setPointerCapture(event.pointerId);\n      const move = e => {\n        const rect=svg.getBoundingClientRect();\n        const svgY=(e.clientY-rect.top)*390/rect.height;\n        const y=Math.max(0,Math.min(10,(box.bottom-svgY)*10/(box.bottom-box.top)));\n        slider.value=y.toFixed(2); draw();\n      };\n      handle.addEventListener(\"pointermove\", move);\n      handle.addEventListener(\"pointerup\", () => handle.removeEventListener(\"pointermove\", move), {once:true});\n    });\n  }\n  drag(handleLeft,left); drag(handleRight,right);\n  root.querySelector(\"#ls-best\").addEventListener(\"click\",()=>{\n    left.value=(bestIntercept+bestSlope).toFixed(2);\n    right.value=(bestIntercept+9*bestSlope).toFixed(2); draw();\n  });\n  root.querySelector(\"#ls-reset\").addEventListener(\"click\",()=>{\n    left.value=3; right.value=7; draw();\n  });\n  draw();\n})();\n</script>\n\nThe line that minimises SSE has closed-form coefficients. For simple\nregression,\n\n$$\nb_1=\\frac{s_{XY}}{s_X^2},\n\\qquad\nb_0=\\bar y-b_1\\bar x,\n$$\n\nwhere $s_{XY}$ is the sample covariance of $X$ and $Y$ and $s_X^2$ is the\nsample variance of $X$. The second formula rearranges to\n$\\bar y = b_0 + b_1\\bar x$: the fitted line always passes through the point\nof means $(\\bar x,\\bar y)$.\n\n::: {#exm-i01-toy}\n## Worked example: least squares by hand on three points\n\nThree observations: $(1,2)$, $(2,5)$, $(3,5)$. Every sum written out.\n\n**Means.** $\\bar x = (1+2+3)/3 = 2$ and $\\bar y = (2+5+5)/3 = 4$.\n\n**Deviations and their products.**\n\n| $i$ | $x_i-\\bar x$ | $y_i-\\bar y$ | $(x_i-\\bar x)(y_i-\\bar y)$ | $(x_i-\\bar x)^2$ |\n|---|---:|---:|---:|---:|\n| 1 | $-1$ | $-2$ | $2$ | $1$ |\n| 2 | $0$ | $1$ | $0$ | $0$ |\n| 3 | $1$ | $1$ | $1$ | $1$ |\n| **Sum** | | | $3$ | $2$ |\n\n**Covariance and variance.** Dividing both sums by $n-1=2$:\n$s_{XY} = 3/2 = 1.5$ and $s_X^2 = 2/2 = 1$.\n\n**Slope and intercept.**\n\n$$\nb_1 = \\frac{s_{XY}}{s_X^2} = \\frac{1.5}{1} = 1.5,\n\\qquad\nb_0 = \\bar y - b_1\\bar x = 4 - 1.5\\times 2 = 1.\n$$\n\nThe fitted line is $\\widehat y = 1 + 1.5x$. @fig-i01-toy confirms the third\nfact: the line passes exactly through $(\\bar x,\\bar y)=(2,4)$. The residuals\nare $-0.5$, $+1$, $-0.5$ --- and they sum to zero, as least-squares\nresiduals always do when the model has an intercept.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nx_toy <- c(1, 2, 3); y_toy <- c(2, 5, 5)\ntoy_fit <- lm(y_toy ~ x_toy)\ntoy_df <- data.frame(x = x_toy, y = y_toy, fitted = fitted(toy_fit))\n\nggplot(toy_df, aes(x = x, y = y)) +\n  geom_abline(intercept = coef(toy_fit)[1], slope = coef(toy_fit)[2],\n              colour = \"#D55E00\", linewidth = 0.9) +\n  geom_segment(aes(xend = x, yend = fitted),\n               colour = \"#0072B2\", linewidth = 0.8, linetype = \"dashed\") +\n  geom_point(size = 3, colour = \"#009E73\") +\n  annotate(\"point\", x = 2, y = 4, shape = 5, size = 3.4, stroke = 1.1,\n           colour = \"#17324D\") +\n  annotate(\"text\", x = 2.34, y = 3.72,\n           label = \"'('*bar(x)*', '*bar(y)*')'\", parse = TRUE,\n           colour = \"#17324D\", size = 3.4) +\n  coord_cartesian(xlim = c(0.5, 3.5), ylim = c(1, 6)) +\n  labs(x = \"x\", y = \"y\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![The three-point toy dataset with its least-squares line. The open diamond marks the point of means (2, 4), which the fitted line passes through exactly.](i01-simple-linear-regression_files/figure-html/fig-i01-toy-1.png){#fig-i01-toy width=518.4}\n:::\n:::\n\n\n\n\nYou can verify the hand calculation in one line:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm(c(2, 5, 5) ~ c(1, 2, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)  c(1, 2, 3) \n        1.0         1.5 \n```\n\n\n:::\n:::\n\n\n\n\n### Fit and read the Shark Tank model in R\n\nNow the real data. The construction is repeated so this block runs on its\nown --- it is the same subset and the same $1,000-unit columns as the\nwarm-up:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ndeals <- subset(sharks, deal_on_show == 1)\ndeals$ask_1k <- deals$ask_amount_usd / 1000\ndeals$deal_1k <- deals$deal_amount_usd / 1000\n\ndeal_model <- lm(deal_1k ~ ask_1k, data = deals)\ncoef(deal_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      ask_1k \n   27.57097     1.00851 \n```\n\n\n:::\n:::\n\n\n\n\nThe fitted equation is approximately\n\n$$\n\\widehat{\\text{deal amount}}\n=27.571+1.0085\\times\\text{amount requested},\n$$\n\nwith both monetary variables measured in $1,000s.\n\n**The slope, with units.** One additional \\$1,000 requested is associated\nwith about \\$1,008.50 more in the fitted agreed amount among pitches that\nreached an on-air deal --- close to dollar-for-dollar. It does not mean that\nasking for more causes investors to offer more.\n\n**The intercept, with units.** The intercept predicts about \\$27,571 at a\nrequest of zero. A zero request lies outside the observed range (the\nsmallest request in the data is \\$10,000) and is not substantively\nmeaningful; an intercept can be mathematically necessary without having a\nuseful standalone interpretation.\n\nObserved, fitted, and residual for the first rows:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(data.frame(\n  observed = deals$deal_1k,\n  fitted = fitted(deal_model),\n  residual = residuals(deal_model)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   observed    fitted  residual\n1        50  77.99646 -27.99646\n2       460 491.48549 -31.48549\n6       500 531.82589 -31.82589\n7       250 279.69843 -29.69843\n11       35  62.86881 -27.86881\n12      250 279.69843 -29.69843\n```\n\n\n:::\n:::\n\n\n\n\nFor every row, `observed = fitted + residual`. Check it on the first row:\nthe pitch asked \\$50,000 and agreed \\$50,000; the model fits\n$27.571 + 1.0085 \\times 50 = 77.996$, and indeed\n$50 = 77.996 + (-27.996)$.\n\n### Prediction inside the evidence boundary\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(deal_model, newdata = data.frame(ask_1k = 300))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n330.1239 \n```\n\n\n:::\n:::\n\n\n\n\nFor a \\$300,000 request (`ask_1k = 300`), the fitted mean agreed amount is\nabout 330.12, that is, \\$330,124. This is a model-based average, not a\nguarantee for a new pitch. If such a pitch actually agreed \\$250,000, its\nresidual would be\n\n$$\ne = 250 - 330.12 = -80.12,\n$$\n\nabout \\$80,124 **below** the fitted conditional mean. Predictions are\ndefensible only inside the range of requests the data contain; extrapolating\nfar beyond it would rely almost entirely on the assumed line.\n\n::: {.caveat-box}\n<span class=\"label\">What this fitted line can and cannot say</span>\n\nThe slope 1.0085 describes an **association** among the 882 televised\npitches that reached an on-air deal. Three limits apply.\n\n- **Association, not causation.** Requests were not randomly assigned.\n  Pitches asking for more differ in many other ways --- stage, industry,\n  revenue --- that also move agreed amounts.\n- **Selection into deals.** The analysis conditions on reaching a deal.\n  Pitches without a deal are structurally excluded, so the line describes\n  deal records, not all pitches, and certainly not all start-ups.\n- **No advice about changing an ask.** The model does not say that a\n  founder who raises their request by \\$1,000 will walk away with \\$1,008.50\n  more. That is a claim about an intervention, which this observational\n  comparison cannot support.\n:::\n\n### Answering the driving question\n\nAmong pitches that reached a deal: yes, asking for more goes together with\ngetting more, almost one-for-one. The fitted slope is 1.0085, so each extra\n\\$1,000 requested is associated with about \\$1,008.50 more agreed on\nair --- about \\$1.01 per dollar asked --- with the caveat box's limits\nattached.\n\n**Next:** We now have a fitted line and can read its slope in money terms. But\nleast squares will draw an equally confident line through terrible data ---\nthe software never warns you. Lecture 2 lays out the assumptions under which\nthe line means what we claimed (linearity of the average, equal spread,\nindependence, and design conditions no plot can certify) and teaches the\ndiagnostics: reading residual plots, and spotting the single influential pitch\nthat can bend an entire fit.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 60 minutes.</span>\n\n### Retrieval (10 minutes)\n\n1. What is the difference between $\\varepsilon_i$ and $e_i$?\n2. What does least squares minimise?\n3. Why must a slope interpretation include units?\n4. Why can an intercept be mathematically valid but substantively unhelpful?\n5. Why is the slope not automatically causal?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. $\\varepsilon_i$ is an unobserved population-model error (distance to the\n   unknown population line); $e_i$ is the observed residual after fitting\n   the sample line.\n2. The sum of squared residuals, $\\operatorname{SSE}=\\sum_i e_i^2$.\n3. The slope is change in outcome units per one predictor unit; without\n   units the number 1.0085 could mean anything.\n4. The value $X=0$ may lie outside the observed range or lack substantive\n   meaning.\n5. The predictor was not randomly assigned and other factors may affect both\n   variables.\n:::\n\n### From worked to faded (20 minutes)\n\nRe-read the prediction calculation in the chapter (fitted value at\n`ask_1k = 300`). Then complete the same calculation for a new request.\n\n*Step 1 (given).* A pitch requests \\$400,000, so `ask_1k = 400`. The fitted\nequation is $\\widehat{\\text{deal}} = 27.571 + 1.0085 \\times \\text{ask}$.\n\n*Step 2 (you).* Compute the fitted agreed amount, in $1,000s and in dollars.\n\n*Step 3 (you).* The pitch actually agreed \\$350,000. Compute the residual\nand interpret its sign in one sentence.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nFitted: $27.571 + 1.0085 \\times 400 = 430.97$, about \\$430,975. Residual:\n$350 - 430.97 = -80.97$, about $-\\$80{,}975$. The negative sign means this\npitch agreed less than the model's fitted conditional mean for a \\$400,000\nrequest.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ndeals <- subset(sharks, deal_on_show == 1)\ndeals$ask_1k <- deals$ask_amount_usd / 1000\ndeals$deal_1k <- deals$deal_amount_usd / 1000\ndeal_model <- lm(deal_1k ~ ask_1k, data = deals)\nunname(350 - predict(deal_model, newdata = data.frame(ask_1k = 400)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -80.9749\n```\n\n\n:::\n:::\n\n\n\n:::\n\nThen the unassisted set:\n\n1. Use the fitted equation to predict the agreed amount for requests of\n   \\$100,000 and \\$500,000.\n2. Calculate the residual for a pitch that requested \\$300,000 and agreed\n   \\$250,000.\n3. Explain why `lm(y ~ x, data = df)` treats the variable left of `~` as\n   the outcome.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. Substitute `ask_1k = 100` and `ask_1k = 500`; the fitted values are about\n   128.42 and 531.83 in $1,000s --- \\$128,422 and \\$531,826.\n2. The fitted amount is about 330.12 in $1,000s, so the residual is\n   $250-330.12\\approx-80.12$, or about $-\\$80{,}124$.\n3. R formulas use `outcome ~ predictors`: the left-hand side is what the\n   model predicts, the right-hand side is what it predicts from.\n:::\n\n### Practice: a regression of your own (15 minutes)\n\nFit `equity_offered_pct ~ season` on the full dataset (all 1,441 pitches)\nand interpret both coefficients with units. State the unit of every quantity\nyou report.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ncoef(lm(equity_offered_pct ~ season, data = sharks))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      season \n 20.4565874  -0.8241241 \n```\n\n\n:::\n:::\n\n\n\n\nThe fitted intercept is about 20.46 percentage points and the slope about\n$-0.824$ percentage points per season. Later seasons are associated with\nsmaller initial equity offers on average. The outcome and intercept use\npercentage points; the predictor uses seasons; the slope uses percentage\npoints per season.\n:::\n\n### Spaced review: one pentad item from QM Basic (5 minutes)\n\nA market survey of $n = 400$ customers gives an average willingness to pay\nof €24.60 with standard error €1.10. Write down the t value for testing a\nbenchmark of €22 and the 95% confidence interval, and say in one sentence\nwhat the interval estimates.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$t = (24.60-22)/1.10 \\approx 2.36$; the interval is\n$24.60 \\pm 1.96\\times1.10 = (22.44,\\; 26.76)$ euros. It is a range of\nplausible values for the population mean willingness to pay, under the\nsampling model from QM Basic.\n:::\n\n### Worked exam interpretation (5 minutes)\n\n**Question** (mock exam Question 1 pattern). A model of venture sales\ngrowth (percentage points) on marketing spending (€10,000s) reports\n$\\widehat{\\text{growth}} = 6.60 + 1.38\\,\\text{spending}$. Interpret the\nslope with units, and calculate the fitted value and residual for a venture\nspending €30,000 with observed growth of 15 percentage points.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nEach additional €10,000 of marketing spending is associated with 1.38\npercentage points higher fitted sales growth among sampled ventures.\n€30,000 is `spending = 3`, so the fitted value is\n$6.60+1.38\\times3=10.74$ percentage points; the residual is\n$15-10.74=4.26$ percentage points --- observed growth exceeds the fitted\nvalue.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA3 venture --- or any business you know well. Name one\nnumerical outcome and one numerical input you suspect drives it, and write\ntwo sentences: first state the slope you would expect (sign and units), then\nsay what decision would change if the fitted slope turned out to be near\nzero. There is no wrong answer; the point is connecting today's tool to\nsomething you care about.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"Outcome: weekly orders; input: euros of social-media spend that week --- I expect a positive slope of a few orders per extra €100. If the fitted slope came out near zero, I would move the whole budget to campus flyers.\"\n:::\n\nYou can discuss this task --- and any other task in this chapter --- with\n**Tilly**, the course AI assistant on Canvas: ask it whether your\noutcome-input pair is more likely to suffer from selection (like analysing\nonly deals) or from reverse causation.\n::::\n\nContinue to Lecture 2: What the model assumes and how residuals betray it.\n\nFormula sheet: Lecture 1 formulas.\n\nFor a more formal treatment, see James et al., *An Introduction to\nStatistical Learning*, 2nd ed., Sections 3.1 and 3.6.2, and\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapter 19.\n\n:::\n",
    "supporting": [
      "i01-simple-linear-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}