{
  "hash": "6bdb4b1f3689d2e067f9a6408765e9e6",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 2: What the model assumes and how residuals betray it {#i02}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 2, you can</span>\n\n- state the assumptions behind ordinary least-squares estimation and\n  inference, and say what each one supports;\n- explain why the outcome itself does not need to be normally distributed;\n- inspect residual plots for non-linearity and unequal variance;\n- explain which assumptions no plot can establish, and what design\n  knowledge assesses them;\n- compute standardised residuals and Cook's distance, and identify\n  influential observations;\n- read a normal Q--Q plot and say when normality matters;\n- respond to an influential observation properly: investigate, report,\n  never silently delete.\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">Every fitted line looks authoritative --- the software draws it with equal confidence through good data and bad. Whether the line deserves trust depends on assumptions no software checks for you.</p>\n\nThe fitted line from Lecture 1 looks convincing. Under what conditions\nshould we trust it, and what do its residuals confess?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 25 minutes.</span>\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation (10 minutes)</span><br>\nWatch the first half of Stanford Statistical Learning\n<a href=\"https://www.youtube.com/watch?v=3GiWpRfkSjc&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=10\">3.2\nHypothesis Testing and Confidence Intervals</a>, focusing on what can go\nwrong in a regression rather than on the test mechanics --- Lecture 3\nhandles those. All links are also listed in the\n<a href=\"../resources/video-guide.html\">External Video Guide</a>.\n</div>\n\n**Predict (5 minutes).** Answer the one-click Mentimeter question posted on\nCanvas before you come to class: can a **steep** fitted slope still be an\n**imprecise** estimate? Commit to an answer and write one sentence\nexplaining why; the lecture resolves it.\n\n**R warm-up (10 minutes).** Rebuild the Lecture 1 model and produce its\nresidual-versus-fitted plot. Bring the plot to class:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ndeals <- subset(sharks, deal_on_show == 1)\ndeals$ask_1k <- deals$ask_amount_usd / 1000\ndeals$deal_1k <- deals$deal_amount_usd / 1000\ndeal_model <- lm(deal_1k ~ ask_1k, data = deals)\nplot(fitted(deal_model), residuals(deal_model))\nabline(h = 0, lty = 2)\n```\n:::\n\n\n\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In class\n\nThe session opens with the usual four-minute entry quiz on the prep videos,\nthen turns to the driving question --- with the class's own warm-up plots on\nscreen.\n\n<p class=\"concept-video\"><strong>Stanford explanation (review):</strong>\n<a href=\"https://www.youtube.com/watch?v=3GiWpRfkSjc\">3.2 Hypothesis Testing and Confidence Intervals</a>.</p>\n\n### The plot you brought\n\nThe warm-up code, run once more so every object on this page is built in\nthe open:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ndeals <- subset(sharks, deal_on_show == 1)\ndeals$ask_1k <- deals$ask_amount_usd / 1000\ndeals$deal_1k <- deals$deal_amount_usd / 1000\ndeal_model <- lm(deal_1k ~ ask_1k, data = deals)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ndeals <- subset(sharks, deal_on_show == 1)\ndeals$ask_1k <- deals$ask_amount_usd / 1000\ndeals$deal_1k <- deals$deal_amount_usd / 1000\ndeal_model <- lm(deal_1k ~ ask_1k, data = deals)\nresid_df <- data.frame(\n  fitted = fitted(deal_model),\n  residual = residuals(deal_model)\n)\n\nggplot(resid_df, aes(x = fitted, y = residual)) +\n  geom_hline(yintercept = 0, colour = \"#C98B2E\",\n             linetype = \"dashed\", linewidth = 0.8) +\n  geom_point(alpha = 0.45, size = 1.6, colour = \"#009E73\") +\n  annotate(\"text\", x = 5050, y = 170, label = \"residual = 0\",\n           hjust = 1, colour = \"#17324D\", size = 3.4) +\n  labs(x = \"Fitted agreed amount ($1,000s)\",\n       y = \"Residual ($1,000s)\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![Residuals against fitted values for the Lecture 1 deal model, both in $1,000s. Reading this plot --- and knowing what it cannot show --- is the whole of today's lecture.](i02-assumptions-diagnostics_files/figure-html/fig-i02-warmup-residuals-1.png){#fig-i02-warmup-residuals width=672}\n:::\n:::\n\n\n\n\nIn @fig-i02-warmup-residuals, fitted outcomes run horizontally and\nobserved-minus-fitted residuals vertically, both in the outcome's units of\n$1,000. A point above zero is a pitch that agreed more than its fitted\nvalue. Before reading patterns out of this cloud, we need to know what the\nmodel actually assumes.\n\n### What each assumption supports\n\nFor\n\n$$\nY_i=\\beta_0+\\beta_1X_i+\\varepsilon_i,\n$$\n\nseparate the conditions below rather than memorising one vague statement\nthat \"the data are normal.\" Each condition supports a different part of the\nanalysis --- take the table one row at a time.\n\n| Condition | Meaning | What it supports |\n|---|---|---|\n| Linear conditional mean | $E[Y\\mid X=x]=\\beta_0+\\beta_1x$ over the modelled range | One constant slope summarises the mean relationship |\n| Zero conditional mean | $E[\\varepsilon\\mid X]=0$ | The slope is not systematically absorbing omitted components related to $X$ |\n| Independent observations | Errors from different rows do not supply duplicate information | The usual standard-error calculation and effective sample size |\n| Positive variation in $X$ | Not all observations have the same predictor value | A slope can be estimated |\n| Constant conditional variance | $\\operatorname{Var}(\\varepsilon\\mid X)=\\sigma^2$ | Classical OLS standard errors have the stated form |\n| Conditional normality | $\\varepsilon\\mid X$ follows a normal distribution | Exact t and F reference distributions in small samples |\n\nSay it early and loudly: **the outcome does not need to be normally\ndistributed, and neither does the predictor.** Agreed deal amounts are\nstrongly right-skewed, and that alone breaks nothing. The assumptions\nconcern the conditional mean, the errors, and the sampling process --- not\nthe marginal histograms of $Y$ and $X$.\n\n### Linearity is about the average, not every point\n\nIndividual outcomes need not lie on a line. Linearity says that the\n*average* outcome at each predictor value follows a line. A systematic\ncurve in residuals means one constant slope misses part of that average\npattern.\n\nConstant variance is the vertical counterpart: homoskedasticity says the\nconditional variance is the same at each predictor value. It does not say\nall residuals have the same size. A fan-shaped residual plot --- in which\nthe vertical band widens or narrows --- suggests changing conditional\nvariance. @fig-i02-assumption-panels shows both stories.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nset.seed(802)\nn_demo <- 90\nx_demo <- runif(n_demo, 0, 10)\n\ny_linear <- 2 + 0.65 * x_demo + rnorm(n_demo, 0, 0.8)\ny_curved <- 2 + 0.10 * x_demo + 0.09 * x_demo^2 + rnorm(n_demo, 0, 0.55)\nm_curved <- lm(y_curved ~ x_demo)\nm_linear <- lm(y_linear ~ x_demo)\n\nfit_demo <- seq(1, 9, length.out = n_demo)\nres_constant <- rnorm(n_demo, 0, 0.75)\nres_fan <- rnorm(n_demo, 0, 0.18 + 0.13 * fit_demo)\n\npanel_names <- c(\"Linear mean (outcome)\", \"Curved mean (residuals)\",\n                 \"Constant spread (residuals)\", \"Changing spread (residuals)\")\ndemo_df <- data.frame(\n  panel = factor(rep(panel_names, each = n_demo), levels = panel_names),\n  x = c(x_demo, fitted(m_curved), fit_demo, fit_demo),\n  y = c(y_linear, residuals(m_curved), res_constant, res_fan)\n)\nline_df <- data.frame(\n  panel = factor(panel_names[1], levels = panel_names),\n  intercept = coef(m_linear)[1],\n  slope = coef(m_linear)[2]\n)\nzero_df <- data.frame(\n  panel = factor(panel_names[-1], levels = panel_names),\n  yintercept = 0\n)\nzero_lab <- data.frame(\n  panel = factor(panel_names[-1], levels = panel_names),\n  x = c(min(fitted(m_curved)), 1, 1),\n  y = c(max(residuals(m_curved)), max(res_constant), max(res_fan))\n)\n\nggplot(demo_df, aes(x = x, y = y)) +\n  geom_hline(data = zero_df, aes(yintercept = yintercept),\n             colour = \"#C98B2E\", linetype = \"dashed\", linewidth = 0.8) +\n  geom_abline(data = line_df, aes(intercept = intercept, slope = slope),\n              colour = \"#D55E00\", linewidth = 0.9) +\n  geom_point(alpha = 0.45, size = 1.6, colour = \"#009E73\") +\n  geom_text(data = zero_lab, aes(x = x, y = y, label = \"residual = 0\"),\n            hjust = 0, colour = \"#17324D\", size = 3) +\n  facet_wrap(~ panel, scales = \"free\") +\n  labs(x = \"Predictor (top left) or fitted value\",\n       y = \"Outcome (top left) or residual\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\"),\n    strip.text = element_text(colour = \"#17324D\", face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![Four simulated situations. Top row: a linear mean fits (left, outcome against predictor); a curved mean leaves a U-shaped residual pattern (right). Bottom row: constant vertical spread (left); spread growing with the fitted value, a fan (right). The three residual panels share the gold dashed line at residual zero.](i02-assumptions-diagnostics_files/figure-html/fig-i02-assumption-panels-1.png){#fig-i02-assumption-panels width=672}\n:::\n:::\n\n\n\n\n::: {.callout-note collapse=\"true\"}\n## Check: match each residual pattern to the assumption it challenges\n\nA **U-shaped** (curved) residual pattern challenges the **linear\nconditional mean**: the average residual is not zero everywhere, so a\nstraight line misses part of the mean relationship. A **fan** challenges\n**constant conditional variance**: the vertical spread of residuals changes\nwith the fitted value. A real plot can show both problems at once.\n:::\n\n### Reading the deal model's vertical spread\n\nNow apply the fan test to @fig-i02-warmup-residuals. At small fitted values\nthe residuals hug the zero line; at larger fitted values they range over\nhundreds of thousands of dollars. The conditional variance of agreed\namounts grows with the size of the deal --- an economically unsurprising\nfan. Classical standard errors, which assume one common $\\sigma^2$, are\ntherefore built on a doubtful assumption here. Lecture 3 returns to exactly\nthis point.\n\n::: {.callout-caution collapse=\"true\"}\n## Try it: annotate a residual plot\n\nIn class this is done in pairs on a printed copy of\n@fig-i02-warmup-residuals. On your own copy (or a sketch):\n\n*Step 1 (given).* The horizontal dashed line marks residual zero: points\nabove it agreed more than fitted, points below agreed less.\n\n*Step 2 (you).* Draw the rough envelope of the residuals --- one curve\nabove, one below --- from the left edge to the right edge of the plot. Does\nthe band stay equally wide?\n\n*Step 3 (you).* Name the assumption your envelope challenges, and write\none sentence saying whether the *average* of the residuals also drifts away\nfrom zero anywhere.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe envelope widens sharply from left to right: small fitted deals sit\nwithin tens of thousands of the line, large fitted deals within hundreds of\nthousands. That fan challenges **constant conditional variance**. The\naverage residual stays near zero across the range, so the plot does not\nshow a clear violation of the **linear conditional mean** --- two different\nassumptions, two different readings of the same picture.\n:::\n:::\n\n### What plots cannot show\n\nTwo rows of the assumptions table never appear in any residual plot.\n\n**Zero conditional mean.** Fitted OLS residuals are mechanically centred\naround the fitted line --- the least-squares algebra forces it --- so a\nresidual plot cannot reveal whether $E[\\varepsilon\\mid X]=0$ holds in the\npopulation. Unobserved confounders are, by definition, not on the plot. Ask\ninstead how the observations came about: what plausible common causes were\nomitted, whether measurement error or reverse direction is credible.\n\n**Independence.** Whether rows share information is a fact about the data\ncollection, not about the residuals. If rows are related, treating them as\nindependent makes the effective sample size look larger than it is and\nstandard errors too small.\n\nTwo short Shark Tank stories, classified:\n\n- **Repeat pitchers.** Some ventures appear in more than one season, and\n  some founders pitch multiple products. Their rows share a founder, a\n  negotiation style, a network of sharks. This is an **independence**\n  problem: the 882 deal rows carry less than 882 rows' worth of\n  information.\n- **Network ties.** Suppose founders with strong investor networks both ask\n  for more (they know the market) and get systematically better deals (the\n  sharks know them). Network strength is unrecorded, related to the\n  predictor, and moves the outcome: this is a **zero conditional mean**\n  problem --- the slope partly absorbs the omitted network effect.\n\nNeither story is visible in @fig-i02-warmup-residuals. Both come from\nknowing how the show works.\n\n### Influence: when a few rows steer the line\n\nA diagnosis can start before any plot, in one line of printed output. The\nfive-number summary of the residuals is the first thing `summary()` reports\nfor any model; here it is on its own:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(residuals(deal_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n-434.38  -30.12  -28.85    0.00  -28.21 2821.15 \n```\n\n\n:::\n:::\n\n\n\n\n::: {#exm-i02-residual-line}\n## Worked example: reading the residual line as a red flag\n\nSame five numbers, read slowly, all in $1,000s:\n\n- The **median** residual is about $-28.8$: the typical deal sits\n  \\$28,800 *below* the fitted line.\n- The middle half of all residuals --- first to third quartile --- spans\n  only $-30.1$ to $-28.2$: a band about \\$2,000 wide. Most deals sit in a\n  tight bundle just under the line.\n- The **maximum** residual is about $2821$: one deal came in \\$2.82\n  million *above* its fitted value.\n\nA symmetric, well-behaved residual distribution would have a median near\nzero and a maximum and minimum of comparable size. Here the mean is zero\n(it always is, with an intercept), but the distribution is wildly\nasymmetric: a dense mass slightly below the line, balanced by a few\nenormous positive misses. Before computing anything else, this one line\nsays the fit is being shaped by a handful of extreme pitches. The same five\nnumbers sit at the top of `summary(deal_model)`, which Lecture 3 reads in\nfull.\n:::\n\nTwo standard tools quantify the suspicion. A **standardised residual**,\n`rstandard()`, re-expresses each residual in standard-deviation units, so\nvalues beyond about $\\pm 3$ are large by any convention. **Cook's\ndistance**, `cooks.distance()`, measures how much the entire fitted line\nwould move if one observation were removed; a common screening threshold is\n$4/n$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrs <- rstandard(deal_model)\ncd <- cooks.distance(deal_model)\n\nsum(abs(rs) > 3)          # unusually large standardised residuals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(cd > 4 / nrow(deals)) # influential by the 4/n screen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21\n```\n\n\n:::\n\n```{.r .cell-code}\ndeals[order(cd, decreasing = TRUE)[1:3],\n      c(\"ask_1k\", \"deal_1k\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    ask_1k deal_1k\n836    150    3000\n671    350    2350\n364   1000    1750\n```\n\n\n:::\n:::\n\n\n\n\nTwelve pitches have standardised residuals beyond $\\pm 3$, and 21 exceed\nthe $4/n$ Cook's screen. The single most influential record asked for\n\\$150,000 and agreed \\$3,000,000 --- twenty times its request.\n@fig-i02-influence places the flagged pitches on the scatter.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ndeals <- subset(sharks, deal_on_show == 1)\ndeals$ask_1k <- deals$ask_amount_usd / 1000\ndeals$deal_1k <- deals$deal_amount_usd / 1000\ndeal_model <- lm(deal_1k ~ ask_1k, data = deals)\ncd <- cooks.distance(deal_model)\ndeals$flagged <- cd > 4 / nrow(deals)\ntop <- which.max(cd)\n\nggplot(deals, aes(x = ask_1k, y = deal_1k)) +\n  geom_point(data = subset(deals, !flagged),\n             colour = \"grey75\", alpha = 0.45, size = 1.6) +\n  geom_abline(intercept = coef(deal_model)[1],\n              slope = coef(deal_model)[2],\n              colour = \"#D55E00\", linewidth = 0.9) +\n  geom_point(data = subset(deals, flagged),\n             colour = \"#D55E00\", size = 2.2) +\n  annotate(\"text\", x = deals$ask_1k[top] + 60, y = deals$deal_1k[top],\n           label = \"ask 150, deal 3,000\",\n           hjust = 0, colour = \"#17324D\", size = 3.4) +\n  labs(x = \"Amount requested ($1,000s)\",\n       y = \"Agreed on-air deal amount ($1,000s)\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![The 882 deal records with the fitted line, full range shown. Orange points exceed the 4/n Cook's distance screen; the labelled pitch (ask $150,000, deal $3,000,000) moves the fitted line most. The $5 million ask at the far right is also influential --- not because its residual is large, but because it sits so far right that it pulls on the line like a lever.](i02-assumptions-diagnostics_files/figure-html/fig-i02-influence-1.png){#fig-i02-influence width=672}\n:::\n:::\n\n\n\n\nWhat to do with a flagged observation --- the standing rule, in order:\n\n1. **Investigate.** Is it a data error, or a real pitch? (These are real:\n   some sharks buy whole companies.)\n2. **Report.** State that results depend on a few identifiable\n   observations; show the fit with and without them if it matters.\n3. **Never silently delete.** Dropping inconvenient rows without saying so\n   is not cleaning, it is misrepresentation.\n\n### Q--Q plots: how to read them, when normality matters\n\nThe last assumption in the table is conditional normality of the errors. A\n**normal Q--Q plot** compares the ordered standardised residuals with the\nvalues expected under a normal distribution; agreement appears as points\nalong the reference line.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ndeals <- subset(sharks, deal_on_show == 1)\ndeals$ask_1k <- deals$ask_amount_usd / 1000\ndeals$deal_1k <- deals$deal_amount_usd / 1000\ndeal_model <- lm(deal_1k ~ ask_1k, data = deals)\nqq_df <- data.frame(rs = rstandard(deal_model))\n\nggplot(qq_df, aes(sample = rs)) +\n  geom_qq_line(colour = \"#D55E00\", linewidth = 0.9) +\n  geom_qq(colour = \"#009E73\", alpha = 0.4, size = 1.6) +\n  labs(x = \"Normal theoretical quantile\",\n       y = \"Standardised residual\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![Normal Q--Q plot of the standardised residuals of the deal model. The heavy departure in the upper tail is the same handful of enormous positive residuals flagged by Cook's distance.](i02-assumptions-diagnostics_files/figure-html/fig-i02-qq-1.png){#fig-i02-qq width=672}\n:::\n:::\n\n\n\n\nRead the horizontal axis as \"where a residual of this rank *should* sit if\nerrors were normal\" and the vertical axis as where it actually sits. In\n@fig-i02-qq the middle of the distribution is close to the line while the\nupper tail shoots far above it: the residual distribution has a much\nheavier right tail than a normal.\n\nWhen does this matter? Normality is used to derive **exact** t and F\ndistributions in **small samples**. With 882 reasonably independent\nobservations, central-limit arguments make the inference of Lecture 3\napproximately valid even without normal errors --- but \"approximately\" is\ndoing real work when the same few pitches that break normality also\ndominate the fit. Severe outliers distort both the line and its\nuncertainty, whatever the sample size.\n\n::: {.caveat-box}\n<span class=\"label\">What a residual check can and cannot certify</span>\n\n- **No visible pattern is not proof.** A clean residual plot is consistent\n  with the assumptions; it does not establish them. Omitted confounders and\n  dependent rows leave no trace on any plot.\n- **Diagnostics start the conversation, they do not end it.** A fan or an\n  influential pitch is a finding to investigate and report, not an\n  automatic verdict on the model --- and not a licence to delete rows until\n  the pictures look better.\n- **Keeping or dropping an influential observation is a substantive\n  decision**, made from knowledge of the data, stated openly in the\n  report --- never made silently by the software or the analyst.\n:::\n\n### Answering the driving question\n\nTrust in the Lecture 1 line is conditional. Its residuals confess two\nthings: the vertical spread grows with the size of the deal (the fan), and\na handful of extreme pitches --- flagged by standardised residuals beyond\n$\\pm3$ and Cook's distances above $4/n$ --- steer both the line and its\napparent precision. Nothing in the plots contradicts a linear conditional\nmean, but zero conditional mean and independence rest on how the show\nworks, not on any picture. Lecture 3 computes standard errors, intervals,\nand tests for this model --- and must respect exactly these two confessions.\n\n**Next:** We now know when a fitted line deserves provisional trust. What we\nstill lack is precision and worth: the slope is an estimate from one sample,\nand a model can pass every diagnostic while explaining almost nothing. Lecture\n3 brings the inference machinery from QM Basic to the coefficient --- standard\nerror, interval, t-test --- and adds the fit toolkit: the SST = SSR + SSE\ndecomposition, $R^2$, and the overall F-test for whether the model is useful\nat all.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 55 minutes.</span>\n\n### Retrieval (10 minutes)\n\n1. Which assumption concerns the conditional mean?\n2. Must the outcome variable be normally distributed? Why or why not?\n3. What does a fan shape in a residual-versus-fitted plot suggest?\n4. Which assumptions cannot be established from a residual plot alone?\n5. What do a standardised residual and Cook's distance each measure?\n6. What are the three steps for handling a flagged observation?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. The linear conditional mean, $E[Y\\mid X=x]=\\beta_0+\\beta_1x$ (and zero\n   conditional mean of the errors).\n2. No. The assumptions concern the errors conditional on the predictor and\n   the sampling process, not the marginal distribution of $Y$ or $X$.\n3. Non-constant conditional variance (heteroskedasticity).\n4. Zero conditional mean and independence; they require knowledge of the\n   design and data-generating process.\n5. A standardised residual measures how unusual one observation's vertical\n   miss is, in standard-deviation units; Cook's distance measures how much\n   the whole fitted line moves if that observation is removed.\n6. Investigate, report, never silently delete.\n:::\n\n### Diagnose three residual plots (15 minutes)\n\nFor each panel of @fig-i02-three-plots, write one sentence: which\nassumption, if any, does the plot challenge?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nset.seed(1204)\nn_p <- 120\nf_p <- seq(1, 9, length.out = n_p)\nres_a <- 1.6 * (f_p - 5)^2 / 8 - 1 + rnorm(n_p, 0, 0.55)\nres_b <- rnorm(n_p, 0, 0.15 + 0.16 * f_p)\nres_c <- rnorm(n_p, 0, 0.8)\n\nplots_df <- data.frame(\n  panel = rep(c(\"Plot A\", \"Plot B\", \"Plot C\"), each = n_p),\n  fitted = rep(f_p, 3),\n  residual = c(res_a, res_b, res_c)\n)\nzero_lab <- data.frame(\n  panel = c(\"Plot A\", \"Plot B\", \"Plot C\"),\n  x = 1,\n  y = c(max(res_a), max(res_b), max(res_c))\n)\n\nggplot(plots_df, aes(x = fitted, y = residual)) +\n  geom_hline(yintercept = 0, colour = \"#C98B2E\",\n             linetype = \"dashed\", linewidth = 0.8) +\n  geom_point(alpha = 0.45, size = 1.6, colour = \"#009E73\") +\n  geom_text(data = zero_lab, aes(x = x, y = y, label = \"residual = 0\"),\n            hjust = 0, colour = \"#17324D\", size = 3) +\n  facet_wrap(~ panel, scales = \"free_y\") +\n  labs(x = \"Fitted value\", y = \"Residual\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\"),\n    strip.text = element_text(colour = \"#17324D\", face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![Three simulated residual-versus-fitted plots for diagnosis practice. The gold dashed line marks residual zero in each panel.](i02-assumptions-diagnostics_files/figure-html/fig-i02-three-plots-1.png){#fig-i02-three-plots width=672}\n:::\n:::\n\n\n\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n**Plot A**: the residuals follow a U shape --- the average residual is\nnegative in the middle and positive at the ends --- challenging the linear\nconditional mean. **Plot B**: the vertical band widens with the fitted\nvalue --- a fan challenging constant conditional variance. **Plot C**: no\nvisible pattern; consistent with the assumptions the plot *can* speak to,\nwhich is not the same as proof that all assumptions hold.\n:::\n\n### Practice: diagnostics for your own model (15 minutes)\n\nFit `equity_offered_pct ~ season` on all 1,441 pitches. Produce the\nresidual-versus-fitted plot and the normal Q--Q plot, and interpret each in\none or two sentences.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nequity_model <- lm(equity_offered_pct ~ season, data = sharks)\nold_par <- par(no.readonly = TRUE)\npar(mfrow = c(1, 2), mar = c(4.5, 4.4, 1.3, 0.7), las = 1)\nplot(fitted(equity_model), residuals(equity_model),\n     pch = 16, col = grDevices::adjustcolor(\"#0072B2\", alpha.f = 0.30),\n     bty = \"n\", xlab = \"Fitted equity offered (pp)\",\n     ylab = \"Residual (pp)\")\nabline(h = 0, lty = 2, lwd = 2, col = \"#D55E00\")\nqqnorm(rstandard(equity_model), pch = 16,\n       col = grDevices::adjustcolor(\"#009E73\", alpha.f = 0.35),\n       bty = \"n\", main = \"\", xlab = \"Normal theoretical quantile\",\n       ylab = \"Standardised residual\")\nqqline(rstandard(equity_model), col = \"#D55E00\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](i02-assumptions-diagnostics_files/figure-html/i02-practice-equity-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(old_par)\n```\n:::\n\n\n\n\nThe residual plot shows sixteen vertical stripes --- season takes only\nwhole-number values, so only sixteen fitted values exist; that is a feature\nof the predictor, not a violation. The vertical spread is broadly similar\nacross stripes, so no strong fan. The Q--Q plot shows a heavy right tail:\na minority of pitches offered far more equity than the fitted trend (the\nmaximum residual is above 80 percentage points --- founders offering\nessentially the whole company), so the normality assumption is doubtful,\nwhich matters little for inference at $n = 1441$ but flags rows worth\ninvestigating.\n:::\n\n### Spaced review: one residual-arithmetic item from Lecture 1 (5 minutes)\n\nUsing the Lecture 1 fitted equation\n$\\widehat{\\text{deal}} = 27.571 + 1.0085 \\times \\text{ask}$ (both in\n$1,000s): a pitch asked \\$200,000 and agreed \\$180,000. Compute the fitted\nvalue and the residual.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nFitted: $27.571 + 1.0085\\times200 = 229.27$, about \\$229,273. Residual:\n$180 - 229.27 = -49.27$, about $-\\$49{,}273$ --- the pitch agreed less than\nthe model's fitted conditional mean.\n:::\n\n### Worked exam interpretation (5 minutes)\n\n**Question** (mock exam Question 2 pattern). A residual-versus-fitted plot\nfor a growth-on-marketing regression shows vertical spread increasing with\nthe fitted value. Name the pattern and the assumption it challenges, and\nstate one assumption the plot cannot assess and what information would\nassess it.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nThe pattern is a fan: residual spread grows with the fitted value,\nchallenging constant conditional variance (homoskedasticity). The plot\ncannot assess independence of observations; that requires knowledge of the\ndata collection --- for example whether some ventures appear in multiple\nrows or were sampled in clusters.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA3 venture --- or any business you know well --- and a\nregression you might one day run on its data (sales on advertising, orders\non price, sign-ups on campaign week). Write two sentences: first name the\nassumption from today's table you would worry about most for that data, then\ndescribe one observation that could dominate the fit and what you would do\nabout it --- investigate and report, not delete.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"For orders-on-price data I would worry most about zero conditional mean: I cut prices exactly in the weeks demand is already weak, so the error and the predictor move together. One 200-box catering order would dominate any fit --- I would report the model with and without it and investigate whether catering is a different business, not delete the row.\"\n:::\n\nYou can discuss this task --- and any other task in this chapter --- with\n**Tilly**, the course AI assistant on Canvas: describe your venture's data\nand ask it to argue which assumption is least plausible.\n::::\n\nContinue to Lecture 3: Coefficient inference, fit, and the F-test.\n\nFormula sheet: Lecture 2 formulas.\n\nFor a more formal treatment, see James et al., *An Introduction to\nStatistical Learning*, 2nd ed., Sections 3.1.2 and 3.3.3, and\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapters 19 and 22.\n\n:::\n",
    "supporting": [
      "i02-assumptions-diagnostics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}