{
  "hash": "7d9bd918fa981bb972992219f4685ace",
  "result": {
    "engine": "knitr",
    "markdown": "# Mock Exam: QM Basic {#basic-mock-exam}\n\n\n\n\n\n\n\n\n\nThis mock exam represents the full ten-lecture course. It contains **100\npoints**, so the exam grade is\n\n$$\n\\text{grade} = \\frac{\\text{points earned}}{10}.\n$$\n\nThe real exam is closed book. The complete [QM Basic Formula\nSheet](#formula-sheet) will be attached. Unless a question states otherwise,\nuse a 5% significance level, report units, and show enough work for your method\nto be checked. Use **180 minutes** as the practice time limit.\n\n| Question | Topic | Points | Suggested minutes |\n|---|---|---:|---:|\n| 1 | Data and a histogram | 15 | 27 |\n| 2 | Probability and a discrete random variable | 20 | 36 |\n| 3 | Continuous distributions | 15 | 27 |\n| 4 | Sampling, confidence intervals, and a mean test | 25 | 45 |\n| 5 | A proportion test, errors, power, and R output | 25 | 45 |\n| **Total** |  | **100** | **180** |\n\n## Question 1: Data and a histogram (15 points)\n\nAn entrepreneurship centre received 240 applications for its accelerator. One\nrow of its dataset represents one application. The variables are:\n\n- `funding_requested_k`: funding requested, in thousands of euros\n- `team_size`: number of people named as current venture-team members\n- `sector`: `Consumer`, `Manufacturing`, `Services`, or `Technology`\n- `accepted`: 1 if the application was accepted and 0 otherwise.\n\nThe histogram below groups the 240 values of `funding_requested_k` into\nequal-width intervals. Each bar includes its upper limit. The centre wants to describe these 240 applications.\nIt does not claim that they are a random sample of all new ventures.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\n# Self-contained: constructs everything it plots.\nlibrary(ggplot2)\nmock_breaks <- seq(0, 120, by = 20)\nmock_counts <- c(58, 88, 54, 24, 10, 6)\nmock_df <- data.frame(\n  xmin = mock_breaks[-length(mock_breaks)],\n  xmax = mock_breaks[-1],\n  count = mock_counts\n)\n\nggplot(mock_df) +\n  geom_rect(aes(xmin = xmin, xmax = xmax, ymin = 0, ymax = count),\n            fill = \"#009E73\", alpha = 0.85, colour = \"white\") +\n  scale_x_continuous(breaks = mock_breaks) +\n  scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 20),\n                     expand = expansion(mult = c(0, 0.05))) +\n  labs(x = \"Funding requested (EUR 1,000s)\",\n       y = \"Number of applications\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![Funding requested by the 240 accelerator applications.](mock-exam_files/figure-html/fig-bmock-histogram-1.png){#fig-bmock-histogram width=672}\n:::\n:::\n\n\n\n\n1. State the observational unit, the sample, and one population to which these\n   data alone should **not** automatically be generalised. **(4 points)**\n2. Classify each of the four variables as categorical or quantitative. For\n   each quantitative variable, also state whether it is discrete or\n   continuous as modelled here. **(4 points)**\n3. Explain both axes and interpret the bar covering more than €20,000\n   up to and including €40,000. **(3 points)**\n4. Describe the distribution's shape and identify the interval containing the\n   median. Briefly justify both answers. **(4 points)**\n\n::: {.callout-note collapse=\"true\"}\n## Model answer and marking guide\n\n1. The observational unit is one accelerator application (1 point). The\n   sample is the 240 received applications (1 point). A defensible example of\n   a population not automatically represented is all new ventures in the\n   Netherlands, because applications were not randomly sampled from that\n   population (2 points).\n2. `funding_requested_k` is quantitative continuous, `team_size` is\n   quantitative discrete, `sector` is categorical, `accepted` is categorical\n   binary, even though it is coded 0/1 (1 point each).\n3. The horizontal axis gives requested funding in thousands of euros. The\n   vertical axis gives application counts (1 point each). The bar says 88\n   applications requested more than €20,000 and at most €40,000 (1 point).\n4. The distribution is right-skewed because most observations are in lower\n   intervals and the counts taper toward larger requests (2 points). The\n   median lies in €20,000--€40,000: 58 observations lie at or below €20,000, while\n   $58+88=146$ lie at or below €40,000, so observations 120 and 121 are in that\n   interval (2 points).\n:::\n\n## Question 2: Probability and a discrete random variable (20 points)\n\nA separate archive contains 500 televised business pitches. Select one record\nuniformly at random. Let $D$ mean that the record shows an on-air deal and\nlet $W$ mean that at least one woman is represented among the presenters.\n\n| Presenters | On-air deal | No on-air deal | Total |\n|---|---:|---:|---:|\n| Women represented | 90 | 110 | 200 |\n| No women represented | 120 | 180 | 300 |\n| **Total** | **210** | **290** | **500** |\n\n1. Calculate $P(D)$, $P(W)$, and $P(D\\cap W)$. **(6 points)**\n2. Calculate $P(D\\mid W)$ and $P(W\\mid D)$, and explain why they answer\n   different questions. **(6 points)**\n3. Are $D$ and $W$ independent for this archive of 500 records? Show\n   a valid numerical check. **(4 points)**\n4. Define $X=1$ for an on-air deal and $X=0$ otherwise. Give the PMF of\n   $X$, $E[X]$, and $\\operatorname{Var}(X)$. **(4 points)**\n\n::: {.callout-note collapse=\"true\"}\n## Model answer and marking guide\n\n1. $P(D)=210/500=0.42$, $P(W)=200/500=0.40$, and\n   $P(D\\cap W)=90/500=0.18$ (2 points each).\n2. $P(D\\mid W)=90/200=0.45$ and\n   $P(W\\mid D)=90/210\\approx0.429$ (2 points each). The first restricts the\n   denominator to pitches with women represented. The second restricts it to\n   pitches with a deal (2 points).\n3. They are not independent: for example,\n   $P(D\\mid W)=0.45\\ne P(D)=0.42$ (4 points). Equivalently,\n   $P(D\\cap W)=0.18\\ne0.42\\times0.40=0.168$.\n4. $p_X(1)=0.42$, $p_X(0)=0.58$ (2 points),\n   $E[X]=0.42$, and $\\operatorname{Var}(X)=0.42(0.58)=0.2436$\n   (1 point each).\n:::\n\n## Question 3: Continuous distributions (15 points)\n\nLet $X\\sim U(15,40)$ represent a waiting time in minutes. Separately, let\n$Y\\sim N(120,8^2)$ represent a processing time in minutes. The following\nstandard-normal probabilities are supplied:\n\n```text\nP(Z <=  1.5) = 0.9332\nP(Z <=  1.0) = 0.8413\nP(Z <= -1.0) = 0.1587\n```\n\n1. State the PDF height of $X$, including its value outside the support.\n   **(3 points)**\n2. Calculate $P(22<X<32)$, $E[X]$, and\n   $\\operatorname{Var}(X)$. **(5 points)**\n3. Standardise 132 minutes under the model for $Y$, then calculate\n   $P(Y\\le132)$. **(3 points)**\n4. Calculate $P(112<Y<128)$. **(2 points)**\n5. Explain why a PDF height is not itself a probability. **(2 points)**\n\n::: {.callout-note collapse=\"true\"}\n## Model answer and marking guide\n\n1. $f_X(x)=1/(40-15)=0.04$ for $15\\le x\\le40$, and\n   $f_X(x)=0$ outside that interval (3 points).\n2. $P(22<X<32)=(32-22)/(40-15)=0.40$ (2 points),\n   $E[X]=(15+40)/2=27.5$ (1 point), and\n   $\\operatorname{Var}(X)=(40-15)^2/12\\approx52.08$ square minutes\n   (2 points).\n3. $z=(132-120)/8=1.5$, so $P(Y\\le132)=0.9332$ (3 points).\n4. $P(112<Y<128)=P(-1<Z<1)=0.8413-0.1587=0.6826$\n   (2 points).\n5. Probability is area over an interval: approximately density times a small\n   interval width. A point has zero width and hence zero probability for a\n   continuous variable (2 points).\n:::\n\n## Question 4: Sampling, confidence intervals, and a mean test (25 points)\n\nFrom a frame of 1,000 accelerator applicants, a simple random sample of 64 was\nselected without replacement. For each sampled applicant, `prep_hours` is the\nnumber of hours spent preparing the application. Let $\\mu$ be the mean\npreparation time among all 1,000 applicants. The sample has\n$\\bar x=18.4$ hours and $s=8.0$ hours. R produced:\n\n```text\nOne Sample t-test\n\ndata: prep_hours\nt = 2.400, df = 63, p-value = 0.0194\nalternative hypothesis: true mean is not equal to 16\n95 percent confidence interval:\n 16.40 20.40\nsample estimate:\nmean of x = 18.40\n```\n\n1. Identify the parameter, estimator, and realised estimate. **(3 points)**\n2. Calculate the estimated standard error of the sample mean. **(3 points)**\n3. State $H_0$ and $H_1$, and verify the reported t statistic. **(5 points)**\n4. Explain why $df=63$. **(3 points)**\n5. Interpret the p-value and give the test decision in context. **(5 points)**\n6. Interpret the 95% confidence interval. **(3 points)**\n7. Check the 10% condition and state what the sampling design supports. Do\n   not make a causal claim. **(3 points)**\n\n::: {.callout-note collapse=\"true\"}\n## Model answer and marking guide\n\n1. The parameter is $\\mu$, the frame's population mean preparation time, the\n   estimator is $\\bar X$, the realised estimate is 18.4 hours (1 point each).\n2. $\\widehat{\\operatorname{SE}}(\\bar X)=S/\\sqrt n=8/\\sqrt{64}=1$\n   hour (3 points).\n3. $H_0:\\mu=16$ against $H_1:\\mu\\ne16$ (2 points).\n   $t=(18.4-16)/1=2.4$ (3 points).\n4. After the sample mean is estimated, 63 of the 64 deviations can vary\n   freely. The last is fixed by their sum of zero, so $df=n-1=63$\n   (3 points).\n5. If the frame mean were 16 hours and the test conditions held, the\n   probability of a t statistic at least as far from zero as 2.4 in either\n   direction would be 0.0194 (3 points). Because $0.0194<0.05$, reject\n   $H_0$. The sample provides evidence that the frame mean differs from 16\n   hours (2 points).\n6. Under repeated valid sampling, 95% of intervals constructed by this method\n   would contain the frame mean. For this sample, plausible values run from\n   16.40 to 20.40 hours (3 points).\n7. $64\\le0.10(1000)=100$, so the course's independence approximation is\n   reasonable (1 point). The random sample supports generalisation to the\n   1,000-applicant frame, as long as all 64 sampled applicants answered and\n   the hours were recorded correctly. It does not identify a causal effect\n   because nothing was randomly assigned (2 points).\n:::\n\n## Question 5: A proportion test, errors, power, and R output (25 points)\n\nIn a simple random sample of 625 former accelerator participants, 350 had\nlaunched a trading venture within one year. Let $p$ be the launch proportion\namong all former participants in the sampling frame. A two-sided test of\n$H_0:p=0.50$ is planned.\n\nThe same study also fits a regression with monthly revenue measured in\nthousands of euros as the outcome and weekly mentoring hours as a predictor.\nOne row of the supplied R output is:\n\n```text\n                 Estimate  Std. Error  t value  Pr(>|t|)  95% CI\nmentoring_hours     0.80       0.25       3.20     0.0014  [0.31, 1.29]\n```\n\n1. Check the success-failure condition under $H_0$. **(3 points)**\n2. Calculate $\\hat p$, its null standard error, and the z statistic.\n   **(5 points)**\n3. The two-sided p-value is 0.0027. Interpret it and state the test conclusion.\n   **(4 points)**\n4. A large-sample 95% confidence interval for $p$ is $(0.521,0.599)$.\n   Interpret it and explain why it agrees with the test decision. **(4 points)**\n5. Define a Type I error in this test. State two changes that would increase\n   power while holding the significance level fixed. **(4 points)**\n6. Interpret the mentoring coefficient, its test against zero, and the limit\n   on causal language. **(5 points)**\n\n::: {.callout-note collapse=\"true\"}\n## Model answer and marking guide\n\n1. Under $H_0$, $np_0=625(0.50)=312.5$ and\n   $n(1-p_0)=312.5$, both at least 10 (3 points).\n2. $\\hat p=350/625=0.56$ (1 point), the null SE is\n   $\\sqrt{0.50(0.50)/625}=0.02$ (2 points), and\n   $z=(0.56-0.50)/0.02=3.00$ (2 points).\n3. If $p=0.50$, the probability of a z statistic at least as far from zero\n   as 3.00 in either direction is about 0.0027 (2 points). Reject $H_0$.\n   There is evidence that the frame launch proportion differs from 0.50\n   (2 points).\n4. Plausible values for the frame launch proportion range from 0.521 to 0.599\n   under the method's conditions (2 points). Zero is excluded from the\n   equivalent interval for $p-0.50$, so the interval and two-sided 5% test\n   both reject the zero difference (2 points).\n5. A Type I error is concluding that the frame launch proportion differs from\n   0.50 when it actually equals 0.50 (2 points). A larger sample and a\n   larger true difference from 0.50 earn 1 point each. Lower variability is\n   not accepted, because the spread of a 0/1 outcome is fixed by $p$. Increasing $\\alpha$ is not accepted because the question holds it\n   fixed.\n6. Among the observed participants, one additional weekly mentoring hour is\n   associated with 0.80 thousand euros (€800) higher fitted monthly revenue\n   (2 points). The row tests $H_0:\\beta=0$. The p-value, 0.0014, is below\n   0.05 and the interval excludes zero, so reject at 5% (2 points). Without random assignment or a\n   defensible causal design, this is an association rather than the causal\n   effect of adding an hour of mentoring (1 point).\n:::\n\nYour marks across the five questions should sum to 100. When practising,\ncomplete the exam before expanding the model answers, then use the marking\nguide to identify whether lost points came from calculation, interpretation,\nunits, conditions, or scope.\n",
    "supporting": [
      "mock-exam_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}