{
  "hash": "85f9164e2e3dbeb061a4a698c9bdc468",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 5: Categories as predictors and joint tests {#i05}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 5, you can</span>\n\n- encode a two-level or multi-level categorical predictor with dummy\n  variables;\n- interpret dummy coefficients relative to a named reference group, in\n  percentage points where the outcome is a percentage;\n- avoid the dummy-variable trap;\n- compute a partial F statistic by hand from an anova table and read the\n  R output;\n- separate joint usefulness from individual significance;\n- separate adjusted associations from causal or essentialist claims.\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">Markets come in categories: sales channels, customer segments, team compositions. Putting categories into a model correctly --- and judging whether they belong in it at all --- is a craft this lecture teaches.</p>\n\nAdjusted for season and ask, do all-women presenting teams offer different\nequity than all-men teams --- and are the category terms worth having in the\nmodel at all?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 25 minutes.</span>\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation (10 minutes)</span><br>\nWatch Stanford Statistical Learning\n<a href=\"https://www.youtube.com/watch?v=dEBQmiXv9fk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=13\">3.5\nExtensions of the Linear Model</a>, focusing on qualitative predictors and\nhow a reference category determines coefficient meaning. All links are also\nlisted in the <a href=\"../resources/video-guide.html\">External Video\nGuide</a>.\n</div>\n\n**Reactivate and predict (5 minutes).** With three categories --- `all_men`,\n`all_women`, and `mixed` --- how many dummy variables does a model with an\nintercept need? Commit to a number, then answer the one-click Mentimeter\nquestion posted on Canvas: at the same season and requested amount, do you\nexpect all-women teams to offer **more**, **less**, or **about the same**\nequity as all-men teams? The lecture resolves both.\n\n**R warm-up (10 minutes).** Class starts from the subset and factor you\nbuild here --- there are no hidden objects, so this warm-up *is* the setup.\nBring the contrasts table:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nknown_gender <- subset(sharks, pitcher_gender_group != \"unknown\")\nknown_gender$gender <- relevel(factor(known_gender$pitcher_gender_group),\n                               ref = \"all_men\")\nknown_gender$ask_1k <- known_gender$ask_amount_usd / 1000\nlevels(known_gender$gender)\ncontrasts(known_gender$gender)\n```\n:::\n\n\n\n\nIf indicators and reference categories are unfamiliar, review\n[Mathematics Refresher: indicators and reference categories](../resources/math-refresher.html).\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In class\n\nThe session opens with the usual four-minute entry quiz on the prep videos,\nthen turns to the driving question --- and, before any model, to the\nmeasurement behind it.\n\n### Measurement first: what the category records\n\n<p class=\"concept-video\"><strong>Stanford explanation (review):</strong>\n<a href=\"https://www.youtube.com/watch?v=dEBQmiXv9fk\">3.5 Extensions of the Linear Model</a>.</p>\n\nThe source categories describe the presenting team as all men, all women, or\nmixed. They do not measure the share of women, gender identity beyond the\nsource categories, or the composition of the full venture. Seven records with\nan `unknown` classification are excluded from every model in this lecture;\nthe reason comes at the end. Every sentence this chapter produces inherits\nthis measurement boundary.\n\n### A two-level indicator\n\nFor a binary predictor $D_i\\in\\{0,1\\}$,\n\n$$\nE[Y_i\\mid D_i]=\\beta_0+\\beta_1D_i.\n$$\n\nThen\n\n$$\nE[Y_i\\mid D_i=0]=\\beta_0,\n\\qquad\nE[Y_i\\mid D_i=1]=\\beta_0+\\beta_1.\n$$\n\nThus $\\beta_1$ is the expected difference between the 1 group and the 0\n**reference group**. A dummy regression with one indicator is exactly a\ncomparison of two group means, dressed as a regression.\n\n::: {#exm-i05-two-ticks}\n## Worked example: two group means from two coefficients\n\nRestrict to the all-men and all-women teams (1,158 records) and let\n`women_team` equal 1 for all-women teams:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nknown_gender <- subset(sharks, pitcher_gender_group != \"unknown\")\ntwo_groups <- subset(known_gender,\n                     pitcher_gender_group %in% c(\"all_men\", \"all_women\"))\ntwo_groups$women_team <- as.integer(\n  two_groups$pitcher_gender_group == \"all_women\"\n)\ncoef(lm(equity_offered_pct ~ women_team, data = two_groups))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)  women_team \n 13.1973739   0.8210677 \n```\n\n\n:::\n\n```{.r .cell-code}\ntapply(two_groups$equity_offered_pct, two_groups$women_team, mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       0        1 \n13.19737 14.01844 \n```\n\n\n:::\n:::\n\n\n\n\nRead the two coefficients as two ticks on the equity axis\n(@fig-i05-two-ticks): the intercept $\\beta_0\\approx 13.20$ *is* the all-men\nmean, and $\\beta_0+\\beta_1\\approx 13.20+0.82=14.02$ *is* the all-women mean.\nThe slope $\\beta_1\\approx 0.82$ is the gap between the ticks --- nothing\nmore.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the drawing code (optional, not exam material)\"}\nold_par <- par(no.readonly = TRUE)\npar(mar = c(3.5, 1, 1, 1))\nplot(NA, xlim = c(12.6, 14.6), ylim = c(0, 1), axes = FALSE,\n     xlab = \"\", ylab = \"\")\naxis(1, at = seq(12.6, 14.6, by = 0.4))\nmtext(\"Mean initial equity offered (%)\", side = 1, line = 2.4, cex = 0.9)\nsegments(13.20, 0.15, 13.20, 0.55, col = \"#0072B2\", lwd = 4)\nsegments(14.02, 0.15, 14.02, 0.55, col = \"#D55E00\", lwd = 4)\narrows(13.20, 0.38, 14.02, 0.38, length = 0.08, code = 3, col = \"#17324D\")\ntext(13.20, 0.72, expression(beta[0] == 13.20), col = \"#0072B2\")\ntext(14.02, 0.72, expression(beta[0] + beta[1] == 14.02), col = \"#D55E00\")\ntext(13.61, 0.25, expression(beta[1] == 0.82), col = \"#17324D\", cex = 0.9)\npar(old_par)\n```\n\n::: {.cell-output-display}\n![The two-level dummy model places the two group means as two ticks on the outcome axis: the intercept is the reference-group mean and the dummy coefficient is the distance between the ticks.](i05-categories-joint-tests_files/figure-html/fig-i05-two-ticks-1.png){#fig-i05-two-ticks width=672}\n:::\n:::\n\n\n\n\n### More than two categories\n\nWith $G$ categories and an intercept, use $G-1$ dummies. Including all $G$\ndummies plus an intercept creates exact linear dependence, because the\ndummies sum to 1 in every row --- the model from Lecture 4 whose coefficients\nare not identified. This is the **dummy-variable trap**.\n\nR creates the dummies automatically when a predictor is a factor. Set the\nreference category deliberately and verify it --- this is exactly what your\nwarm-up built:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknown_gender$gender <- relevel(factor(known_gender$pitcher_gender_group),\n                               ref = \"all_men\")\nknown_gender$ask_1k <- known_gender$ask_amount_usd / 1000\nlevels(known_gender$gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"all_men\"   \"all_women\" \"mixed\"    \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrasts(known_gender$gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          all_women mixed\nall_men           0     0\nall_women         1     0\nmixed             0     1\n```\n\n\n:::\n:::\n\n\n\n\nEach row of the contrasts table is a category; each column is one dummy. The\nreference category `all_men` is the all-zero row: it lives in the intercept.\n\n::: {.callout-note collapse=\"true\"}\n## Check: four industries and an intercept --- how many dummies?\n\nThree. One industry is the reference group carried by the intercept; the\nthree dummy coefficients each compare one remaining industry with it. Four\ndummies plus an intercept would fall into the trap.\n:::\n\n### Percent versus percentage points\n\nOne habit must be in place before any coefficient is read. The outcome\n`equity_offered_pct` is measured in percent, so its regression coefficients\nare in **percentage points** --- and the sentence \"the all-women coefficient\nis 1.28%\" is ambiguous. It could mean:\n\n- a **relative** change: offers 1.28% *of* the all-men level higher (13.0%\n  would become about 13.2%); or\n- an **absolute** change of 1.28 **percentage points**: 13.0% becomes\n  14.28%.\n\nThese differ by a factor of about eight here. A coefficient on a\npercent-scaled outcome is always the absolute kind. The precise sentence\nreplacing the ambiguous one is: \"At the same season and requested amount,\nall-women presenting teams are fitted to offer 1.28 **equity percentage\npoints** more initially than all-men presenting teams.\" Every full-credit\ndummy interpretation in this course uses *percentage points* for this\noutcome.\n\n### The adjusted comparison\n\nNow the model of the driving question: both category dummies, with season and\nrequested amount (in thousands of dollars) held fixed.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngender_model <- lm(\n  equity_offered_pct ~ season + ask_1k + gender,\n  data = known_gender\n)\nsummary(gender_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = equity_offered_pct ~ season + ask_1k + gender, data = known_gender)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-16.118  -4.778  -1.100   3.220  82.590 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     20.8388333  0.5064929  41.143  < 2e-16 ***\nseason          -0.8238940  0.0477959 -17.238  < 2e-16 ***\nask_1k          -0.0026613  0.0005822  -4.571 5.28e-06 ***\ngenderall_women  1.2835231  0.4810241   2.668  0.00771 ** \ngendermixed      0.1209343  0.5411539   0.223  0.82320    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.612 on 1429 degrees of freedom\nMultiple R-squared:  0.1913,\tAdjusted R-squared:  0.189 \nF-statistic: 84.49 on 4 and 1429 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nBoth dummy coefficients, each with the full sentence --- categories named,\nunit, held-fixed set, sample boundary:\n\n- **All-women versus all-men.** Among pitches with a recorded source\n  classification, all-women presenting teams are fitted to offer about\n  **1.28 equity percentage points more** initially than all-men presenting\n  teams at the same season and requested amount (p $\\approx$ 0.008).\n- **Mixed versus all-men.** Among the same pitches, mixed teams are fitted\n  to differ from all-men teams by about **0.12 percentage points** at the\n  same season and requested amount (p $\\approx$ 0.823) --- an estimate not\n  statistically distinguishable from zero.\n\nNote the adjusted all-women gap (1.28 points) is larger than the raw gap\nfrom the worked example (0.82 points): adjusting for season and ask moved\nthe comparison, which is precisely why the held-fixed set belongs in the\nsentence. These are two reference-group comparisons, not a claim that gender\ncauses the offers.\n\nChanging the reference group changes coefficient labels, not fitted values or\noverall fit --- verify rather than trust:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknown_gender$gender_women_ref <- relevel(known_gender$gender,\n                                         ref = \"all_women\")\ncoef(lm(equity_offered_pct ~ season + ask_1k + gender_women_ref,\n        data = known_gender))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            (Intercept)                  season                  ask_1k \n           22.122356419            -0.823893957            -0.002661283 \ngender_women_refall_men   gender_women_refmixed \n           -1.283523102            -1.162588850 \n```\n\n\n:::\n:::\n\n\n\n\nThe same three group means are now described from the all-women vantage\npoint: the all-men coefficient is $-1.28$, the mirror image of before, and\nthe fitted values are identical.\n\n### Are the category terms worth having at all?\n\nBlock 1 read the coefficients one at a time. The driving question also asks\nsomething no single t-test answers: do the two category terms **jointly** add\ninformation beyond season and ask?\n\nThe logic needs two **nested** models --- the reduced model is the complete\nmodel with the tested coefficients forced to zero, fitted on the same rows:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the drawing code (optional, not exam material)\"}\nold_par <- par(no.readonly = TRUE)\npar(mar = c(0.3, 0.3, 0.3, 0.3))\nplot(NA, xlim = c(0, 10), ylim = c(0, 5), axes = FALSE,\n     xlab = \"\", ylab = \"\", xaxs = \"i\", yaxs = \"i\")\nrect(0.4, 1.1, 4.6, 3.9, col = \"#DCEAF3\", border = \"#17324D\", lwd = 2)\nrect(5.4, 1.1, 9.6, 3.9, col = \"#FDE5C1\", border = \"#17324D\", lwd = 2)\ntext(2.5, 3.35, \"Reduced model\", font = 2, col = \"#17324D\")\ntext(2.5, 2.55, \"season + ask_1k\", cex = 0.95)\ntext(2.5, 1.85, expression(beta[aw] == 0 ~ \",\" ~ beta[mx] == 0),\n     cex = 0.95, col = \"#5B6976\")\ntext(7.5, 3.35, \"Complete model\", font = 2, col = \"#17324D\")\ntext(7.5, 2.55, \"season + ask_1k\", cex = 0.95)\ntext(7.5, 1.85, \"+ two category dummies\", cex = 0.95)\narrows(4.7, 2.5, 5.3, 2.5, length = 0.1, lwd = 2, col = \"#17324D\")\ntext(5.0, 3.0, \"free the\\ntwo coefficients\", cex = 0.8, col = \"#5B6976\")\npar(old_par)\n```\n\n::: {.cell-output-display}\n![The nested pair behind the partial F-test: the reduced model is the complete model with the two category coefficients set to zero, on the same analysis rows.](i05-categories-joint-tests_files/figure-html/fig-i05-nested-1.png){#fig-i05-nested width=672}\n:::\n:::\n\n\n\n\nThe hypotheses:\n\n$$\nH_0:\\beta_{all\\_women}=\\beta_{mixed}=0\n\\quad\\text{against at least one non-zero.}\n$$\n\n::: {#exm-i05-partial-f}\n## Worked example: the partial F statistic by hand\n\nFit both models and ask R for the anova table:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreduced_gender <- lm(equity_offered_pct ~ season + ask_1k,\n                     data = known_gender)\nanova(reduced_gender, gender_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: equity_offered_pct ~ season + ask_1k\nModel 2: equity_offered_pct ~ season + ask_1k + gender\n  Res.Df   RSS Df Sum of Sq      F Pr(>F)  \n1   1431 83228                             \n2   1429 82792  2    436.25 3.7649 0.0234 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nPlug the table's numbers into the formula once by hand. Adding the two\ncategory terms reduces the residual sum of squares by $436.25$ using $2$\ndegrees of freedom; the complete model leaves $82{,}792$ on $1{,}429$\ndegrees of freedom:\n\n$$\nF=\\frac{436.25/2}{82{,}792/1{,}429}\n=\\frac{218.13}{57.94}\n\\approx 3.76.\n$$\n\nRead the ratio: the numerator is explained variation *per tested\ncoefficient*; the denominator is unexplained variation *per residual degree\nof freedom*. The category terms buy about 3.8 times as much explanation per\ncoefficient as noise alone would --- with p $\\approx$ 0.023, more than chance\ncomfortably explains.\n:::\n\nAt 5%, the two source-category terms are **jointly useful** in this\nspecification. Hold that next to the individual results: joint p-value\n$0.023$, yet the mixed dummy's own p-value is $0.823$ *in the very same\noutput*. Joint usefulness is not individual significance --- the F-test asks\nwhether the pair of terms together improves the model, not whether each\nsurvives on its own. (The overall F in `summary(gender_model)`, about 84.5\nwith a tiny p-value, answers a third, cruder question: whether *all four*\npredictors jointly beat an intercept-only model.)\n\n### Visualise the adjusted comparison\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nknown_gender <- subset(sharks, pitcher_gender_group != \"unknown\")\nknown_gender$gender <- relevel(factor(known_gender$pitcher_gender_group),\n                               ref = \"all_men\")\nknown_gender$ask_1k <- known_gender$ask_amount_usd / 1000\ngender_model <- lm(\n  equity_offered_pct ~ season + ask_1k + gender,\n  data = known_gender\n)\nnewdat <- data.frame(\n  season = mean(known_gender$season),\n  ask_1k = mean(known_gender$ask_1k),\n  gender = factor(c(\"all_men\", \"all_women\", \"mixed\"),\n                  levels = levels(known_gender$gender))\n)\npred <- predict(gender_model, newdata = newdat, interval = \"confidence\")\nadj_df <- data.frame(\n  team = factor(c(\"All-men\", \"All-women\", \"Mixed\"),\n                levels = c(\"All-men\", \"All-women\", \"Mixed\")),\n  fit = pred[, \"fit\"],\n  lwr = pred[, \"lwr\"],\n  upr = pred[, \"upr\"]\n)\n\nggplot(adj_df, aes(x = team, y = fit)) +\n  geom_pointrange(aes(ymin = lwr, ymax = upr),\n                  colour = \"#009E73\", linewidth = 0.7, fatten = 2.6) +\n  labs(x = \"Source classification of pitching team\",\n       y = \"Fitted initial equity offered (%)\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![Fitted initial equity by source classification at the average season and requested amount, with 95% confidence intervals. The intervals express model-based uncertainty, not uncertainty about how the categories were recorded.](i05-categories-joint-tests_files/figure-html/fig-i05-adjusted-1.png){#fig-i05-adjusted width=672}\n:::\n:::\n\n\n\n\nRead @fig-i05-adjusted with the standing five-step sequence:\n\n1. **Axes:** source categories across, fitted initial equity (in percent) up.\n2. **Units:** each point is a fitted mean at the *same* average season and\n   requested amount --- an adjusted comparison, not raw group means.\n3. **Marks:** points are fitted values (about 12.9, 14.1, and 13.0); vertical\n   lines are 95% confidence intervals, wider for the smaller categories.\n4. **Pattern:** the all-women point sits about 1.28 points above the all-men\n   point; the mixed interval overlaps both.\n5. **Limits:** the intervals express **model-based** sampling uncertainty.\n   They say nothing about the **recording** uncertainty in the broad source\n   categories themselves, and nothing causal.\n\n### Why `unknown` is excluded, not a fourth group\n\nSeven records carry the classification `unknown`. That label records the\n*absence of information*, not a kind of team: treating it as a substantive\nfourth category would estimate a \"mean equity of teams the source failed to\nclassify,\" a quantity with no business meaning. Excluding the records keeps\nevery coefficient interpretable; the price, stated openly, is that the\nanalysed sample is the classified records only.\n\n::: {.caveat-box}\n<span class=\"label\">What these category coefficients can and cannot say</span>\n\nThe categories are broad source codings of the on-screen presenting team ---\nnot shares, identities, or full founding teams --- so the coefficients\ncompare codings, not people. The analysed sample is the 1,434 classified\nrecords of broadcast pitches; selection into the show and into\nclassification travels with every estimate. The two dummy coefficients are\ntwo reference-group contrasts at fixed season and ask, and they change\nlabels when the reference changes. None of this supports an essentialist or\ncausal reading: the model reports that offers *differ* by coded composition\nin these data, not that composition *makes* anyone offer differently.\n:::\n\n### Answering the driving question\n\nAt the same season and requested amount, all-women presenting teams are\nfitted to offer about 1.28 equity percentage points more than all-men teams\n(p $\\approx$ 0.008); mixed teams are indistinguishable from all-men teams.\nThe two category terms are jointly useful (partial F $\\approx$ 3.76,\np $\\approx$ 0.023), so they earn their place in the model --- as an adjusted\nassociation within these recorded pitches, nothing more.\n\n**Next:** We can now compare categories at fixed values of the other\npredictors --- but so far every group shares one slope, and every trend is a\nstraight line. Both restrictions are modelling choices, not facts. Lecture 6\nrelaxes them: interactions let the season trend differ by team composition,\nand polynomial terms let the trend bend --- each with the discipline for\nreading the result honestly.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 70 minutes.</span>\n\n### Retrieval (10 minutes)\n\n1. Why are only $G-1$ dummies used with an intercept?\n2. What does a dummy coefficient compare?\n3. What changes when the reference group changes?\n4. What does a partial F-test evaluate?\n5. Why can a joint F-test reject when one individual t-test does not?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. All $G$ dummies sum to 1, the intercept column: exact collinearity, so\n   the coefficients would not be identified.\n2. A category with the named reference category, holding the other included\n   predictors fixed.\n3. Coefficient labels and values change to describe the same fits from a new\n   vantage point; fitted values and overall fit do not change.\n4. Whether a specified group of coefficients is jointly zero, comparing\n   nested models on the same rows.\n5. The F-test evaluates the terms together; individual tests ask narrower\n   questions, each with its own uncertainty, and can miss what the pair\n   achieves jointly.\n:::\n\n### Releveling and verification practice (15 minutes)\n\n1. Relevel `gender` so `mixed` is the reference group and interpret both\n   dummy coefficients. Save the relevelled model as `relevelled_model`.\n2. Verify that fitted values are unchanged after releveling by comparing\n   with `gender_model`.\n3. State the hypotheses for the partial F-test of both gender dummies.\n4. Explain why the seven `unknown` records were excluded rather than treated\n   as evidence of a substantive fourth group.\n5. Explain why \"the all-women coefficient is 1.28%\" is ambiguous, then\n   rewrite it precisely.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. Use:\n\n   ```r\n   mixed_reference <- relevel(known_gender$gender, ref = \"mixed\")\n   relevelled_model <- lm(\n     equity_offered_pct ~ season + ask_1k + mixed_reference,\n     data = known_gender\n   )\n   coef(relevelled_model)\n   ```\n\n   At fixed season and request, the all-men coefficient is about $-0.121$\n   percentage points and the all-women coefficient about $1.163$ percentage\n   points, each relative to mixed teams.\n2. `all.equal(fitted(gender_model), fitted(relevelled_model))` returns\n   `TRUE` up to numerical tolerance.\n3. $H_0:\\beta_{all\\_women}=\\beta_{mixed}=0$ against at least one non-zero\n   coefficient, with all-men as the current reference.\n4. `unknown` records lack a known classification; absence of recorded\n   information is not a meaningful team-composition category.\n5. It confuses percent with percentage points and omits the comparison and\n   conditioning. A precise version: \"At the same season and requested\n   amount, all-women presenting teams are fitted to offer 1.28 equity\n   percentage points more initially than all-men presenting teams.\"\n:::\n\n### From worked to faded: a partial F with new numbers (10 minutes)\n\nTest the two category dummies in a *smaller* complete model that contains\nonly `season`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreduced_season <- lm(equity_offered_pct ~ season, data = known_gender)\nfull_season    <- lm(equity_offered_pct ~ season + gender,\n                     data = known_gender)\nanova(reduced_season, full_season)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: equity_offered_pct ~ season\nModel 2: equity_offered_pct ~ season + gender\n  Res.Df   RSS Df Sum of Sq      F   Pr(>F)   \n1   1432 84646                                \n2   1430 84003  2    643.43 5.4766 0.004272 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n*Step 1 (given).* Adding the two dummies reduces the residual sum of squares\nby $643.43$ using $2$ degrees of freedom; the complete model leaves\n$84{,}003$ on $1{,}430$ degrees of freedom.\n\n*Step 2 (you).* Plug these into the F formula from the worked example.\n\n*Step 3 (you).* Compare with the table's F and p-value and state the\nconclusion at 5% in one sentence.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$F=(643.43/2)/(84{,}003/1{,}430)=321.7/58.7\\approx 5.48$, matching the\ntable, with p $\\approx$ 0.004. At 5%, the two category terms are jointly\nuseful even in the model that adjusts only for season.\n:::\n\n### The 120-word interpretation (10 minutes)\n\nWrite a 120-word interpretation of the full `gender_model` that includes the\nsource measurement boundary and the causal limit.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nA complete answer reports: the outcome and sample (initial equity offered,\n1,434 broadcast pitches with a recorded source classification); both\nestimates with units and conditioning (all-women teams fitted 1.28\npercentage points above all-men teams, mixed teams 0.12 points above, at the\nsame season and requested amount); uncertainty (p $\\approx$ 0.008 and 0.823;\njointly useful, partial F p $\\approx$ 0.023); the measurement boundary\n(broad source coding of the on-screen team, not shares or identities); and\nthe scope (adjusted associations among selected, recorded pitches --- not\ncausal, not essentialist).\n:::\n\n### Spaced review: one item from Lecture 4 (5 minutes)\n\nUsing the Lecture 4 three-predictor model, compute the combined fitted\ndifference for a pitch three seasons later requesting $200,000 more, at the\nsame description length.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$3(-0.836)+200(-0.0029)\\approx-3.09$ percentage points: contributions add\nbecause the model is additive, and $200,000 is 200 units of `ask_1k`.\n:::\n\n### Worked exam interpretation (5 minutes)\n\n**Question.** In the mock-exam Q4 style: a model of equity on season,\n`ask_1k`, and industry (four categories, reference `Food and Beverage`)\nreports `industryTechnology 1.9 (p = 0.04)`. A student writes: \"Technology\npitches offer 1.9% more equity, so entering tech makes founders more\ngenerous.\" Correct the sentence.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nThree repairs. Units: the estimate is 1.9 equity *percentage points*, not a\nrelative 1.9%. Comparison and conditioning: technology pitches are fitted\n1.9 points above *Food and Beverage* pitches at the same season and\nrequested amount, among the recorded pitches. Scope: nothing here is causal\n--- \"entering tech makes founders more generous\" reads a reference-group\ncontrast as an effect of industry choice.\n:::\n\n### From the reading ladder (10 minutes)\n\nNext rung of the [reading ladder](../resources/reading-ladder.qmd): open\n[Brooks et al. (2014)](https://doi.org/10.1073/pnas.1321202111) --- an\nopen-access study of entrepreneurial pitch success. Find where the analysis\ncompares pitches across a **category** (the presenter's gender). Identify\nthe categorical predictor and what serves as the reference comparison, and\nrestate the paper's headline gap in one careful sentence that respects\ntoday's two rules: percentage points are not percent, and an adjusted gap\nbetween categories is not a causal claim about any attribute. Then note one\nway their setting differs from our Shark Tank teaching file.\n\n::: {.callout-note collapse=\"true\"}\n## Check your approach\n\nA good sentence names both categories explicitly, states the outcome and\nits unit, and attributes the gap to the sample and design (\"in these\npitch competitions, pitches presented by ... were funded ... percentage\npoints more often than ...\") without sliding into \"because investors\nprefer...\". Differences from our file worth noting: their data include\nexperiments with manipulated recordings, whereas ours are selected,\nedited television records with a broad source category for the presenting\nteam.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA3 venture --- or any business you know well. Name one\ncategorical feature of your customers or products (segment, channel, region,\nplan tier), and write two sentences: which category would you set as the\nreference group and why, and what would a \"jointly useful\" F-test verdict on\nthe whole set of categories change about how you describe your market? There\nis no wrong answer; the point is choosing a reference deliberately.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"My channels are the campus stand, the app, and the website; I would set the campus stand as reference because it is the original channel every decision gets compared against. A jointly useful F-verdict would justify describing my market by channel at all --- individually mixed p-values on single dummies would not settle that.\"\n:::\n\nYou can discuss this task --- and any other task in this chapter --- with\n**Tilly**, the course AI assistant on Canvas: ask it to check whether your\ntwo sentences confuse percent with percentage points, or to quiz you on the\ndummy-variable trap with your own categories.\n::::\n\nContinue to Lecture 6: Interactions and curvature.\n\nFormula sheet: Lecture 5 formulas.\n\nFor a more formal treatment, see James et al., *An Introduction to\nStatistical Learning*, 2nd ed., Sections 3.2.2 and 3.3.1, and\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapters 20--21.\n\n:::\n",
    "supporting": [
      "i05-categories-joint-tests_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}