{
  "hash": "2a8bb8e57be11a585ebcb10ab0fc3edf",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 8: Sampling distributions and the central limit theorem {#b08}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 8, you can</span>\n\n- distinguish a population distribution, a sampling distribution, and a\n  realised estimate\n- derive the mean and variance of a sample mean using the rules for\n  rescaling and for sums\n- calculate and interpret a standard error\n- use the square-root rule to relate sample size to precision, and find the\n  sample size for a target margin of error\n- state the central limit theorem for this course's conditions and apply it\n  to means and proportions\n- explain what the law of large numbers and the CLT each claim, and what\n  neither of them repairs.\n:::\n\n::: {.must-know}\n<span class=\"label\">Must know</span>\n\n**Be able to do yourself:**\n\n- calculate the standard error of a mean and of a proportion\n- use the square-root rule: four times the data halves the standard error\n- find the sample size needed for a target margin of error\n- check the success-failure condition\n- calculate a probability for a sample mean with the CLT and supplied $Z$ values\n- tell a standard deviation from a standard error.\n\n**Enough to recognise:**\n\n- the derivation of $\\operatorname{Var}(\\bar X)=\\sigma^2/n$\n- the formal statements of the law of large numbers and the CLT\n- the binomial distribution $\\text{Bin}(n,p)$ for a number of successes, with\n  mean $np$ and variance $np(1-p)$.\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">Any number computed from a sample would have come out differently with a different sample. Before acting on an estimate, a careful analyst asks how much such numbers vary from sample to sample, and what reduces that variation.</p>\n\nA random sample of 100 pitches from the Shark Tank file had a mean equity\noffered of 12.76%. How wrong could that number be, and why can we trust an\naverage even though the equity offered in single pitches is strongly skewed?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 25 minutes.</span>\n\n**Minimum path:** the video preparation and the prediction. **Full path:** everything in this section.\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation (10 minutes)</span><br>\nWatch <a href=\"https://www.youtube.com/watch?v=IrKUM3nNXJE\">The Central Limit\nTheorem</a>. Focus on which distribution becomes approximately normal as the\nsample size grows. All links are also listed in the\n<a href=\"../resources/video-guide.html\">External Video Guide</a>.\n</div>\n\n**Reactivate (10 minutes).** Classify each object as a *population\ndistribution*, a *sampling distribution*, or a *realised estimate*:\n\n1. the distribution of equity offered across individual pitches\n2. the distribution of $\\bar X$ across all possible samples of 40 pitches\n3. the single mean calculated from one observed sample.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\nThe first is a population distribution, the second is a sampling\ndistribution, and the third is a realised estimate, the number observed in\none sample. Keep the three apart. Lecture 7 named the sampling distribution.\nThis lecture describes it.\n:::\n\n**Predict (5 minutes).** Answer the one-click Wooclap question posted on\nCanvas before you come to class: to cut the typical error of a sample mean\n**in half**, do you need $2\\times$, $4\\times$, or $10\\times$ the\nobservations? Commit to an answer. You find the answer in the lecture\nmaterial.\n\nIf square roots, sums, degrees of freedom, or standardisation are not secure,\nreview [Mathematics Refresher: powers, roots, and\nstandardisation](../resources/math-refresher.html).\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## Lecture material\n\nThis section describes the sampling distribution of the sample mean: where\nit is centred, how wide it is, and what shape it has. It then applies the\nsame results to proportions.\n\n### Start with a founder's question\n\nYou asked 100 customers and calculated an average. How far can that average\nbe from the truth, and how many customers would it take to halve the\ndistance? Lecture 7 showed that averages differ from sample to sample. This\nlecture measures by how much. Start from the five dots of Lecture 7. Five\nrandom samples of 100 pitches gave five different sample means, while the\npopulation mean stayed fixed. Where would the mean of a sixth sample land?\nThe answer lies in the pattern behind those dots.\n\n### The pattern behind the five dots\n\nImagine not five samples but every possible random sample of the same size,\neach with its own sample mean. The distribution of those possible values of\n$\\bar X$ is the sampling distribution of the mean, which Lecture 7 named. It\ndescribes the uncertainty of an estimator, not the variation among single\npitches. Three objects must be kept apart:\n\n- The **population distribution** describes how the equity offered varies\n  across the 1,441 pitches.\n- The **sampling distribution** describes how $\\bar X$ would vary across\n  repeated samples.\n- A **realised estimate**, such as 12.76, is one draw from that sampling\n  distribution.\n\nThis lecture uses three parameters of the Shark Tank file: the mean and the\nSD of the equity offered (`equity_offered_pct`), and the proportion of\npitches that ended with a deal (`deal_on_show`). The 1,441 records are the\nwhole population, so the SD divides by $N$ and not by $n-1$:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nmu_equity <- mean(sharks$equity_offered_pct)\nsigma_equity <- sqrt(mean((sharks$equity_offered_pct - mu_equity)^2))\np_deal <- mean(sharks$deal_on_show)\nc(mu_equity = mu_equity, sigma_equity = sigma_equity, p_deal = p_deal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   mu_equity sigma_equity       p_deal \n  13.2076128    8.4414247    0.6120749 \n```\n\n\n:::\n:::\n\n\n\n\nSo $\\mu = 13.21$%, $\\sigma = 8.44$ percentage points, and $p = 0.612$. These\nare fixed numbers. What varies is any number computed from a random sample\nof the 1,441 records.\n\n### Back to the lab\n\nIn Lecture 7 you worked with the\n[sampling-distribution lab](b07-samples-estimators.qmd#sampling-lab): the\nhistogram of sample means sat near 13.2, narrowed as $n$ grew, and turned\nbell-shaped although the population is strongly right-skewed. That pile of\nsample means is the sampling distribution of the mean. The rest of this\nlecture explains what you saw there: where the pile sits, how wide it is,\nand why it becomes bell-shaped.\n\n### The mean and variance of a sample mean\n\nLet $X_1,\\ldots,X_n$ be a random sample of independent and identically\ndistributed (iid) variables, as in Lecture 7, with population mean $\\mu$ and\nvariance $\\sigma^2$. Then\n\n$$\nE[\\bar X]=\\mu,\n\\qquad\n\\operatorname{Var}(\\bar X)=\\frac{\\sigma^2}{n},\n\\qquad\n\\operatorname{SD}(\\bar X)=\\frac{\\sigma}{\\sqrt n}.\n$$\n\nThe first equality says that $\\bar X$ is unbiased for $\\mu$ (Lecture 7): the\npile of sample means is centred on the parameter, as in the lab. The third\nquantity has its own name.\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**Standard error (SE).** The standard deviation of an estimator across\nrepeated random samples. For the sample mean,\n$\\operatorname{SE}(\\bar X)=\\sigma/\\sqrt n$.\n:::\n\nAn SD describes the variation among observations. An SE describes the\nvariation of an estimator.\n\nThe three formulas above are not new facts. They follow from the rules for\nrescaling a variable\nin [Lecture 3](b03-discrete-distributions.qmd#b03-shift-rescale) and from the\nrules for sums of variables in\n[Lecture 5](b05-joint-covariance-correlation.qmd#b05-sums):\n\n- $E[X+Y]=E[X]+E[Y]$ and $E[aX]=aE[X]$, so\n  $E[\\bar X]=\\frac{1}{n}\\sum_i E[X_i]=\\frac{1}{n}\\,n\\mu=\\mu$.\n- $\\operatorname{Var}(aX)=a^2\\operatorname{Var}(X)$ and, for\n  **independent** variables,\n  $\\operatorname{Var}(X+Y)=\\operatorname{Var}(X)+\\operatorname{Var}(Y)$, so\n\n$$\n\\operatorname{Var}(\\bar X)\n=\\operatorname{Var}\\!\\left(\\frac{X_1+\\cdots+X_n}{n}\\right)\n=\\frac{1}{n^2}\\sum_{i=1}^{n}\\operatorname{Var}(X_i)\n=\\frac{n\\sigma^2}{n^2}\n=\\frac{\\sigma^2}{n}.\n$$\n\nIndependent positive and negative deviations partly cancel in an average.\nThat is why the right-hand histogram in the lab is so much narrower than the\npopulation histogram.\n\nThe variance $\\sigma^2/n$ shrinks to zero as $n$ grows, so $\\bar X$ gets\nclose to $\\mu$. Estimators with this property are called **consistent**.\n\nThe formulas for $E[\\bar X]$ and $\\operatorname{SD}(\\bar X)$ give the centre\nand the spread of the sampling distribution, not its shape. In one case the\nshape is known exactly. If the population\nitself is normal, the sample mean is exactly normal for every $n$:\n$\\bar X\\sim N(\\mu,\\sigma^2/n)$. The reason is that a sum of independent\nnormal variables is again normal\n([Lecture 6](b06-continuous-normal.qmd#b06-normal-sums)). The central limit\ntheorem below deals with populations that are not normal.\n\nIn practice $\\sigma$ is usually unknown and is estimated by the sample SD\n$S$. This gives the estimated standard error\n$\\widehat{\\operatorname{SE}}(\\bar X)=S/\\sqrt n$. The hat marks an estimate:\n$\\widehat{\\operatorname{SE}}$ is a standard error calculated from the\nsample, just as $\\hat p$ is a proportion calculated from the sample.\nReplacing a parameter by an estimate adds a little extra uncertainty.\nLecture 9 shows how to allow for it.\n\n::: {#exm-b08-se}\n## Worked example: E, Var, and SE for σ = 12, n = 36\n\nA population has mean $\\mu$ and SD $\\sigma=12$. A random sample of $n=36$\nobservations is drawn. Find the mean, variance, and SE of $\\bar X$, naming\nthe rule used at each step.\n\n- **Mean.** By the rules for expectations ($E[X+Y]=E[X]+E[Y]$,\n  $E[aX]=aE[X]$), $E[\\bar X]=\\mu$: whatever $\\mu$ is, the sample mean is\n  unbiased for it.\n- **Variance.** By $\\operatorname{Var}(aX)=a^2\\operatorname{Var}(X)$ and the\n  sum rule for independent variables,\n  $\\operatorname{Var}(\\bar X)=\\sigma^2/n=12^2/36=144/36=4$.\n- **SE.** Take the square root:\n  $\\operatorname{SD}(\\bar X)=\\sqrt 4=2$, which is $\\sigma/\\sqrt n=12/6=2$.\n\nThe typical distance between a sample mean and $\\mu$ is about 2 units. That\nis one sixth of the typical distance of a single observation from $\\mu$.\nAll three rules are on the formula sheet.\n:::\n\n### The square-root rule\n\nPrecision grows with $\\sqrt n$, not with $n$. This answers the prediction\nquestion from before class: to cut the SE in half you need four times the\nobservations, because\n\n$$\n\\frac{\\sigma}{\\sqrt{4n}}=\\frac{1}{2}\\cdot\\frac{\\sigma}{\\sqrt n}.\n$$\n\nDoubling the sample size does not halve the SE. It only divides the SE by\n$\\sqrt 2\\approx 1.41$. More precision becomes more and more expensive, which\nis worth knowing before you budget for data collection.\n\n::: {.callout-caution collapse=\"true\"}\n## Try it: how large must n become to cut an SE from 4 to 1?\n\nTry this with your neighbour first. Complete the missing steps\nbefore opening the answer.\n\n*Step 1 (given).* The SE must fall by a factor of $4/1 = 4$.\n\n*Step 2 (you).* The SE is proportional to $1/\\sqrt n$. By what factor must\n$n$ change to divide the SE by 4?\n\n*Step 3 (you).* If the original sample had $n=50$, how many observations\ndoes the new design need?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nDividing the SE by 4 requires multiplying $n$ by $4^2=16$: the square-root\nrule in reverse. From $n=50$ the design needs $16\\times 50=800$\nobservations. Four times the precision costs sixteen times the data.\n:::\n:::\n\n### The central limit theorem\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/the-central-limit-theorem/\">19.2 The Central Limit Theorem</a>.</p>\n\nThe lab showed one more pattern that the rules for the mean and the variance\ndo not explain. The pile of sample means became bell-shaped, although the\npopulation is strongly skewed. The central limit theorem describes this\npattern.\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**Central limit theorem (CLT).** For a large random sample of iid\nobservations with mean $\\mu$ and variance $\\sigma^2$, the sample mean is\napproximately normal, whatever the shape of the population:\n$\\bar X\\ \\dot\\sim\\ N\\!\\left(\\mu,\\frac{\\sigma^2}{n}\\right)$.\n:::\n\nThe dot above $\\sim$ marks an approximation, which improves as $n$ grows. The\nsame statement can be written with the standardised sample mean\n\n$$\nZ=\\frac{\\bar X-\\mu}{\\sigma/\\sqrt n},\n$$\n\nwhich is approximately standard normal for large $n$. The normal model of\nLecture 6 returns here. It is not a model for the data, where it failed for\nthe equity offered. It is a model for the sample mean.\n\nWith the CLT you can calculate a probability for a sample mean. Take the\nworked example above (@exm-b08-se), with $\\sigma=12$ and $n=36$, so that\nthe SE is 2. Suppose that $\\mu=50$. By the CLT, $\\bar X$ is approximately\n$N(50,2^2)$. The probability of a sample mean above 53 is\n\n$$\nP(\\bar X>53)\\approx P\\!\\left(Z>\\frac{53-50}{2}\\right)=P(Z>1.5)\n=1-0.9332=0.0668,\n$$\n\nwith the supplied value $P(Z\\le1.5)=0.9332$. A sample mean above 53 occurs\nin about 7% of random samples.\n\nThere is no universal rule that $n=30$ is always enough. Thirty is a common\nstarting point for roughly symmetric data. Strongly skewed data, such as\nrevenues or deal amounts, need more. Extreme outliers and dependence between\nobservations can also require much more data.\n\n@fig-b08-clt shows a simulation: 5,000 sample means of $n=5$ draws and 5,000\nsample means of $n=40$ draws from the equity offered (`equity_offered_pct`).\nThe simulation draws with replacement, so its draws are exactly independent.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\n\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nmu_equity <- mean(sharks$equity_offered_pct)\nsigma_equity <- sqrt(mean((sharks$equity_offered_pct - mu_equity)^2))\nset.seed(208)\nB <- 5000\nmeans_5 <- replicate(B, mean(sample(sharks$equity_offered_pct, 5,\n                                    replace = TRUE)))\nmeans_40 <- replicate(B, mean(sample(sharks$equity_offered_pct, 40,\n                                     replace = TRUE)))\n\npanel_levels <- c(\"n = 5\", \"n = 40\")\nsim_means <- data.frame(\n  sample_mean = c(means_5, means_40),\n  panel = factor(rep(panel_levels, each = B), levels = panel_levels)\n)\n\nall_means <- c(means_5, means_40)\nshared_limits <- c(floor(min(all_means)), ceiling(max(all_means)))\nshared_breaks <- seq(shared_limits[1], shared_limits[2], length.out = 36)\n\nnormal_grid <- seq(shared_limits[1], shared_limits[2], length.out = 400)\nnormal_curves <- rbind(\n  data.frame(x = normal_grid, panel = panel_levels[1],\n             density = dnorm(normal_grid, mu_equity,\n                             sigma_equity / sqrt(5))),\n  data.frame(x = normal_grid, panel = panel_levels[2],\n             density = dnorm(normal_grid, mu_equity,\n                             sigma_equity / sqrt(40)))\n)\nnormal_curves$panel <- factor(normal_curves$panel, levels = panel_levels)\n\nggplot(sim_means, aes(sample_mean)) +\n  geom_histogram(aes(y = after_stat(density)), breaks = shared_breaks,\n                 fill = \"#009E73\", alpha = 0.85, colour = \"white\") +\n  geom_line(data = normal_curves, aes(x, density),\n            colour = \"#D55E00\", linewidth = 0.9) +\n  facet_wrap(~ panel, scales = \"fixed\") +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +\n  labs(x = \"Sample mean equity offered (%)\", y = \"Density\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\"),\n    strip.text = element_text(colour = \"#17324D\", face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![Simulated sampling distributions of the mean equity offered for n = 5 (left) and n = 40 (right), each based on 5,000 samples, with the corresponding normal approximations (orange curves). Both panels use the same axes.](b08-sampling-distributions_files/figure-html/fig-b08-clt-1.png){#fig-b08-clt width=672}\n:::\n:::\n\n\n\n\nRead @fig-b08-clt with the five-step sequence of Lecture 1. (1) *Unit and\nvariables:* each bar counts simulated sample means, not pitches. The\nhorizontal axis is the sample mean of the equity offered, in percent. (2)\n*Scales:* both panels use the same range and the same density scale, so\nwidths can be compared directly. (3) *One element:* the orange curve in each\npanel is the normal approximation for that sample size. (4) *Pattern:* the\npile for $n=40$ is far narrower and much closer to its normal curve than the\npile for $n=5$, which still leans right like the population. (5) *Limits:*\nthe figure shows random samples from this file. It says nothing about samples\nthat were not drawn by chance.\n\n### How many customers must I ask? {#b08-sample-size}\n\nThe square-root rule compares two sample sizes. A founder often asks a more\ndirect question: how large must the sample be to reach a given precision?\n\nThe CLT gives the answer. The central 95% of a normal distribution lies\nwithin 1.96 standard deviations of its mean, because $z_{0.975}=1.96$\n(Lecture 6). So in about 95% of\nrandom samples, $\\bar X$ lies within $1.96\\times\\sigma/\\sqrt n$ of $\\mu$. This\ndistance is called the margin of error at the 95% level. Lecture 9 uses it to\nbuild confidence intervals. If the margin of error may be at most $m$, solve\nfor $n$:\n\n$$\n1.96\\times\\frac{\\sigma}{\\sqrt n}\\le m\n\\qquad\\text{gives}\\qquad\nn\\ge\\left(\\frac{1.96\\times\\sigma}{m}\\right)^2.\n$$\n\n::: {#exm-b08-sample-size}\n## Worked example: a sample size for a margin of 2 euros\n\nAn invented example. You want to know the average order value of your\ncustomers to within 2 euros, at the 95% level. How many customers must you\nsurvey?\n\n- **Planning value.** The formula needs $\\sigma$, which you do not know\n  before the survey. A small pilot survey gave an SD of about 12 euros, so\n  use $\\sigma=12$ as a planning value. The target margin of 2 euros is one\n  sixth of that SD.\n- **Sample size.** $n\\ge(1.96\\times 12/2)^2=11.76^2\\approx 138.3$.\n- **Round up.** Survey $n=139$ customers. Always round up: with 138\n  customers the margin would be slightly above 2 euros.\n\nHalving the margin to 1 euro needs $(1.96\\times 12/1)^2=23.52^2\\approx 553.2$,\nso 554 customers. Half the margin costs about four times the sample, as the\nsquare-root rule says.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma_plan <- 12\nn_needed <- c(margin_2_euros = (1.96 * sigma_plan / 2)^2,\n              margin_1_euro  = (1.96 * sigma_plan / 1)^2)\nn_needed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmargin_2_euros  margin_1_euro \n      138.2976       553.1904 \n```\n\n\n:::\n\n```{.r .cell-code}\nceiling(n_needed)   # ceiling() rounds up to the next whole number\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmargin_2_euros  margin_1_euro \n           139            554 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Sample proportions are sample means\n\nFor a Bernoulli variable $X$ with $P(X=1)=p$ (Lecture 3),\n\n$$\nE[X]=p,\n\\qquad\n\\operatorname{Var}(X)=p(1-p).\n$$\n\nA sample proportion is the sample mean of a 0/1 variable (Lecture 7), so\nevery result above applies: $\\widehat P=\\bar X$ satisfies\n\n$$\nE[\\widehat P]=p,\n\\qquad\n\\operatorname{SE}(\\widehat P)=\\sqrt{\\frac{p(1-p)}{n}}.\n$$\n\nThis formula needs the parameter $p$, which is usually unknown. Replacing $p$\nby the estimate $\\hat p$ gives the estimated standard error\n\n$$\n\\widehat{\\operatorname{SE}}(\\widehat P)=\\sqrt{\\frac{\\hat p(1-\\hat p)}{n}}.\n$$\n\nUse the version with $p$ when the population proportion is given or assumed.\nUse the estimated version when you only have the sample, as in Tutorial 3.\n\nBy the CLT, the sampling distribution of $\\widehat P$ is approximately normal\nfor a large sample. How large is large enough for a proportion? The next\nsection answers this with the distribution of a count.\n\n### Counting successes: the binomial distribution {#b08-binomial}\n\nTake $n$ independent 0/1 trials, each with the same success probability $p$.\nThe number of successes is the sum $Y=X_1+\\cdots+X_n$. Its distribution is\ncalled the **binomial distribution**, written $Y\\sim\\text{Bin}(n,p)$. The sum\nrules of [Lecture 5](b05-joint-covariance-correlation.qmd#b05-sums) give\n\n$$\nE[Y]=np,\n\\qquad\n\\operatorname{Var}(Y)=np(1-p).\n$$\n\nThe sample proportion is this count divided by the number of trials:\n$\\widehat P=Y/n$.\n\nAn invented example: 200 people visit your web shop, and each of them buys\nwith probability 0.05, independently of the others. The number of buyers is\n$Y\\sim\\text{Bin}(200,\\,0.05)$. You expect $np=200\\times 0.05=10$ buyers, with\na standard deviation of $\\sqrt{200\\times 0.05\\times 0.95}=\\sqrt{9.5}\\approx 3.1$\nbuyers.\n\nA count is a sum, so the CLT applies to it: for large $n$ the binomial\ndistribution is close to a normal distribution. @fig-b08-binomial shows when\n$n$ is large enough. With 80 visitors you expect only $np=4$ buyers. The\ndistribution is skewed, with a longer tail to the right. The normal curve\nputs about 2% of its area below zero, where no count can lie. The fit is\nworse than in the right panel. With 400 visitors you expect $np=20$ buyers,\nand the normal curve fits well.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\n\np_buy <- 0.05\nn_small <- 80\nn_large <- 400\npanel_levels <- c(\"n = 80, np = 4: rule violated\",\n                  \"n = 400, np = 20: rule satisfied\")\n\npmf <- rbind(\n  data.frame(y = 0:12, panel = panel_levels[1],\n             prob = dbinom(0:12, size = n_small, prob = p_buy)),\n  data.frame(y = 5:37, panel = panel_levels[2],\n             prob = dbinom(5:37, size = n_large, prob = p_buy))\n)\npmf$panel <- factor(pmf$panel, levels = panel_levels)\n\ngrid_small <- seq(-7, 12, length.out = 300)\ngrid_large <- seq(5, 37, length.out = 300)\nnormal_curves <- rbind(\n  data.frame(y = grid_small, panel = panel_levels[1],\n             density = dnorm(grid_small, n_small * p_buy,\n                             sqrt(n_small * p_buy * (1 - p_buy)))),\n  data.frame(y = grid_large, panel = panel_levels[2],\n             density = dnorm(grid_large, n_large * p_buy,\n                             sqrt(n_large * p_buy * (1 - p_buy))))\n)\nnormal_curves$panel <- factor(normal_curves$panel, levels = panel_levels)\nbelow_zero <- normal_curves[normal_curves$panel == panel_levels[1] &\n                              normal_curves$y <= 0, ]\n\nnotes <- data.frame(\n  y = c(-7, 26, 26),\n  prob = c(0.055, 0.084, 0.068),\n  label = c(\"normal curve\\nreaches\\nbelow 0\", \"normal curve\",\n            \"binomial\\nprobabilities\"),\n  colour = c(\"#D55E00\", \"#D55E00\", \"#009E73\"),\n  panel = factor(panel_levels[c(1, 2, 2)], levels = panel_levels)\n)\n\nggplot(pmf, aes(y, prob)) +\n  geom_area(data = below_zero, aes(y, density),\n            fill = \"#D55E00\", alpha = 0.25) +\n  geom_segment(aes(xend = y, yend = 0), colour = \"#009E73\", linewidth = 0.8) +\n  geom_point(colour = \"#009E73\", size = 1.8) +\n  geom_line(data = normal_curves, aes(y, density),\n            colour = \"#D55E00\", linewidth = 0.9) +\n  geom_text(data = notes, aes(label = label), colour = notes$colour,\n            size = 3.2, hjust = 0, lineheight = 0.95) +\n  facet_wrap(~ panel, scales = \"free\") +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.08))) +\n  labs(x = \"Number of buyers\", y = \"Probability\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\"),\n    strip.text = element_text(colour = \"#17324D\", face = \"bold\", size = 10)\n  )\n```\n\n::: {.cell-output-display}\n![The binomial distribution of the number of buyers when each visitor buys with probability 0.05 (green), with the normal curve of the same mean and variance (orange). With 80 visitors (left) the distribution is skewed and the normal curve reaches below zero. With 400 visitors (right) the normal curve fits well. The two panels have different axes.](b08-sampling-distributions_files/figure-html/fig-b08-binomial-1.png){#fig-b08-binomial width=672}\n:::\n:::\n\n\n\n\nThis course therefore uses the normal approximation for a count or a\nproportion only if $np\\ge10$ and $n(1-p)\\ge10$. This rule is called the\n**success-failure condition**: the expected numbers of successes and of\nfailures must both be at least 10. When $p$ is unknown, check the rule with\nthe counts in the sample: at least 10 successes and at least 10 failures. In\na test, use the null value $p_0$ (Lecture 10). Some textbooks use 5 in place\nof 10. Ten is the safer choice. You do not need to calculate binomial\nprobabilities in this course.\n\n::: {#exm-b08-proportion}\n## Worked example: SE of the deal proportion at n = 100\n\nSuppose we draw a random sample of $n=100$ pitches from the frame, where the\ndeal proportion is $p=0.612$. How far is the sample deal proportion\ntypically from 0.612?\n\n- **SE.**\n  $\\operatorname{SE}(\\widehat P)=\\sqrt{0.612\\,(1-0.612)/100}\n  =\\sqrt{0.2375/100}\\approx 0.0487$, about 4.9 percentage points.\n- **Success-failure check.** $np=100(0.612)=61.2\\ge 10$ and\n  $n(1-p)=100(0.388)=38.8\\ge 10$, so the normal approximation is reasonable.\n\nIn R, using `p_deal` as constructed above:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_deal <- mean(sharks$deal_on_show)\nc(SE_deal_proportion_n_100 = sqrt(p_deal * (1 - p_deal) / 100),\n  successes = 100 * p_deal, failures = 100 * (1 - p_deal))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSE_deal_proportion_n_100                successes                 failures \n              0.04872773              61.20749480              38.79250520 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### The law of large numbers and the CLT answer different questions\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/the-weak-law-of-large-numbers/\">18.4 The Weak Law of Large Numbers</a>.</p>\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**Law of large numbers (LLN).** As the sample size $n$ grows, the sample\nmean $\\bar X$ of a random sample gets close to the population mean $\\mu$.\n:::\n\nThis is the consistency of $\\bar X$ noted above. The LLN and the CLT answer\ndifferent questions:\n\n- The LLN says where the pile of sample means goes: towards $\\mu$.\n- The CLT says what the pile looks like: its approximate shape and width.\n\nThe LLN is about a value. The CLT is about a distribution. Both assume that\nthe sampling is random. Neither repairs a sample that was selected badly in\nthe first place.\n\n::: {.callout-note collapse=\"true\"}\n## Check: match each statement to LLN, CLT, or neither\n\n1. \"With enough random draws, the sample mean equity will be very close to\n   13.21.\"\n2. \"For $n=100$ random draws, the sample mean equity is approximately\n   $N(13.21, 0.844^2)$.\"\n3. \"With enough respondents, our LinkedIn poll will represent Dutch\n   founders.\"\n\nStatement 1 is the LLN, statement 2 is the CLT, and statement 3 is\n**neither**. No theorem turns a self-selected sample into a representative\none (see the box below).\n:::\n\n::: {.caveat-box}\n<span class=\"label\">What a bigger sample can and cannot fix</span>\n\n- More data shrink the random error, at the square-root rate.\n- More data do nothing for selection bias. A million televised pitches still\n  describe televised pitches.\n- The standard error measures precision inside the list you sampled from. It\n  is silent about who is on the list.\n\n**What you can do with it:** first fix who you ask, then decide how many.\nStop collecting when more data would no longer change your decision.\n:::\n\n### Answering the driving question\n\nA random sample of 100 pitches from the Shark Tank file had a mean equity\noffered of 12.76%, while the mean of all 1,441 records is 13.21%. How wrong\ncould 12.76 have been? Its standard error:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma_equity <- sqrt(mean((sharks$equity_offered_pct -\n                             mean(sharks$equity_offered_pct))^2))\nc(SE_mean_n_25 = sigma_equity / sqrt(25),\n  SE_mean_n_100 = sigma_equity / sqrt(100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n SE_mean_n_25 SE_mean_n_100 \n    1.6882849     0.8441425 \n```\n\n\n:::\n:::\n\n\n\n\nAt $n=100$ the SE is about 0.84 percentage points, which is about 6% of the\npopulation mean. The mean of a random sample typically lands within about\n0.84 points of 13.21, and rarely more than about two SEs away. The sample\nwith 12.76 missed by 0.45 points, about half an SE. At $n=25$ the SE would be\ntwice as large, by the square-root rule.\n\nWhy can we trust the average although the equity offered in single pitches\nis strongly skewed? Deviations cancel in an average (the variance rule), and\nthe CLT gives the mean a predictable, nearly normal distribution.\n\nOne detail: our samples are drawn without replacement from 1,441 records.\nThat makes the exact standard error slightly smaller than the formula says,\n0.81 instead of 0.84. The 10% rule says that the difference can be ignored.\nThe optional box in\n[Lecture 7](b07-samples-estimators.qmd#b07-parameters) gives the exact\nformula.\n\n::: {.founder-box}\n<span class=\"label\">A founder's decision (invented example)</span>\n\nYou ask customers to rate your boxes from 1 to 10. Ratings have a standard deviation of about 2. With 25 customers the standard error of the mean is 2/5 = 0.4. With 100 customers it is 0.2. Is the larger survey worth four times the effort? Your rule is to change the menu only if the mean rating is below 7. The first 25 customers give a mean of 8.4, which is 3.5 standard errors above 7. The decision: stop surveying and keep the menu. More data would not change what you do.\n:::\n\n**Next:** We can now say how much a sample mean typically varies: by about\none standard error. A report needs a sentence such as \"the population mean\nplausibly lies between $a$ and $b$\". That takes one more step, because in a\nreal sample $\\sigma$ is unknown and must be estimated too, which adds\nuncertainty. Lecture 9 introduces the t distribution, which allows for this\nextra uncertainty, and builds the confidence interval from it.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 80 minutes.</span>\n\n**Minimum path (about 35 minutes):** read the lecture material, answer the recall questions, then work for 10 minutes on the tasks that follow. **Full path:** all tasks below.\n\n### Read the lecture material (15 minutes)\n\nRead the Lecture material section above from start to end. The lecture\ncovered the core of it. The text has every step, every example, and all the\ncode, including parts that were not shown in class. Note what is still\nunclear and bring it to the next tutorial, or ask Tilly.\n\n### Recall questions (10 minutes)\n\n1. What varies in a sampling distribution?\n2. Why is $E[\\bar X]=\\mu$ called unbiasedness?\n3. What is the difference between an SD and an SE?\n4. To cut an SE in half, by what factor must the sample size grow, and why?\n5. What does the CLT say becomes approximately normal?\n6. Why does a larger sample not remove selection bias?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. The statistic varies across possible repeated samples. The parameter and\n   the population stay fixed.\n2. Its long-run average across repeated samples equals the population\n   parameter.\n3. An SD describes variation among observations. An SE describes variation\n   of an estimator across samples.\n4. By a factor of 4: the SE is proportional to $1/\\sqrt n$, so halving it\n   requires $2^2=4$ times the observations.\n5. The sample mean. For a large sample its sampling distribution is\n   approximately normal. The single observations do not become normal.\n6. Sample size shrinks random error only. It does not change how units\n   entered the sampling frame or the sample.\n:::\n\n### Finish a half-worked example (5 minutes)\n\nRe-read the worked SE calculation (@exm-b08-se). Then complete the same\ncalculation for a proportion: a planned survey expects $p=0.30$ and\n$n=100$.\n\n*Step 1 (given).* The SE formula for a proportion is\n$\\sqrt{p(1-p)/n}$.\n\n*Step 2 (you).* Calculate the SE.\n\n*Step 3 (you).* Check the success-failure condition.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$\\operatorname{SE}(\\widehat P)=\\sqrt{0.30(0.70)/100}\\approx 0.0458$, about\n4.6 percentage points. The expected counts are $np=30$ successes and\n$n(1-p)=70$ failures, both at least 10, so the normal approximation is\nacceptable.\n:::\n\n### Practice (15 minutes)\n\n1. If $\\sigma=15$ and $n=25$, find $E[\\bar X]$,\n   $\\operatorname{Var}(\\bar X)$, and $\\operatorname{SE}(\\bar X)$, naming\n   the rule used at each step.\n2. How large must $n$ become to reduce an SE from 6 to 1.5?\n3. For a sample proportion with $p$ assumed to be 0.50 and $n=64$,\n   calculate the SE and check the success-failure condition.\n4. Explain why the normal approximation is more convincing in the\n   right-hand panel of @fig-b08-clt.\n5. State one threat to the CLT-based approximation that a large $n$ alone\n   does not solve.\n6. An invented example. A founder wants to know the average delivery time of\n   her orders to within 1 minute, at the 95% level. A pilot gave an SD of 5\n   minutes. How many deliveries must she time? How does the answer change\n   for a margin of half a minute?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. $E[\\bar X]=\\mu$ (rules for expectations),\n   $\\operatorname{Var}(\\bar X)=\\sigma^2/n=225/25=9$ (variance of a rescaled\n   sum of independent variables), $\\operatorname{SE}(\\bar X)=\\sqrt 9=3$.\n2. The SE must fall by a factor of 4, so the sample size must grow by\n   $4^2=16$ times.\n3. $\\sqrt{0.50(0.50)/64}=0.0625$. Expected counts are 32 and 32, both at\n   least 10.\n4. Averaging 40 observations cancels more of the skewness and shrinks the\n   sampling variation more than averaging 5 observations. The histogram\n   follows its normal curve much more closely.\n5. Dependence between observations. A non-representative sample is a\n   different problem: the approximation still works, but the mean then\n   estimates the wrong quantity. (Extreme outliers slow the approximation too.)\n6. $n\\ge(1.96\\times 5/1)^2=9.8^2=96.04$, so she must time 97 deliveries. For\n   half a minute, $n\\ge(1.96\\times 5/0.5)^2=19.6^2=384.16$, so 385\n   deliveries. Half the margin costs about four times the sample.\n:::\n\n### Widget homework (10 minutes)\n\nOpen the\n[sampling-distribution lab](b07-samples-estimators.qmd#sampling-lab) in\nLecture 7 again and run these three settings. For each, redraw several times\nand write **one sentence** on what the histogram of sample means shows:\n\n1. $n = 2$\n2. $n = 25$\n3. $n = 100$.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\n1. At $n=2$ the sample means scatter widely and their histogram is still\n   right-skewed, like the population.\n2. At $n=25$ the histogram of means is clearly narrower and roughly\n   symmetric, centred near 13.2.\n3. At $n=100$ the means form a tight bell around the population mean, with\n   a typical deviation of less than one percentage point. This is the SE of\n   about 0.84 percentage points.\n:::\n\n### Review: one question each from Lectures 7 and 6 (10 minutes)\n\n1. *(Lecture 7.)* The sample variance divides by $n-1$, not $n$. In one or\n   two sentences, why?\n2. *(Lecture 6.)* Daily revenue is modelled as $X\\sim N(10, 2^2)$ (in\n   thousands of euros). Find $P(X>13)$. Supplied value:\n   $P(Z\\le 1.5)=0.9332$.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. The deviations are measured from the sample mean, which was itself\n   estimated from the data. Once it is fixed, only $n-1$ deviations can\n   vary freely, and dividing by $n-1$ removes the resulting downward bias.\n2. Standardise: $z=(13-10)/2=1.5$, so\n   $P(X>13)=P(Z>1.5)=1-0.9332\\approx 0.067$.\n:::\n\n### Worked exam interpretation (5 minutes)\n\n**Question.** The mean equity offered (`equity_offered_pct`) in the Shark\nTank file is $\\mu=13.21$% with $\\sigma=8.44$ percentage points. A random\nsample of $n=100$ pitches is drawn. Using the CLT, find the probability that\nthe sample mean exceeds 14.5%. Supplied value: $P(Z\\le 1.53)=0.937$.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nBy the CLT, $\\bar X\\ \\dot\\sim\\ N(13.21, 0.844^2)$ since\n$\\operatorname{SE}=8.44/\\sqrt{100}=0.844$. Standardise:\n$z=(14.5-13.21)/0.844\\approx 1.53$, so\n$P(\\bar X>14.5)\\approx P(Z>1.53)=1-0.937=0.063$. That is about a 6% chance.\nNote that the question is about the mean, not about a single pitch. For a\nsingle pitch the normal model was rejected in Lecture 6.\n:::\n\n### Check the AI (5 minutes)\n\nYou asked an AI assistant: \"My ratings have a standard deviation of 12 and I asked 36 customers. How precise is the mean, and how do I halve the error?\" It answered:\n\n> \"The standard error is 12/36 = 0.33. To halve it you need twice as many customers, 72.\"\n\nFind what is wrong and write the corrected answer. This is the **Verify**\nstep of Attempt → Ask → Verify → Explain, and the exam asks for it.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nBoth steps are wrong. The standard error divides by the square root of the sample size: 12/6 = 2. And to halve it you need four times the data, 144 customers, because the standard error falls with the square root of the sample size.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA venture, or any business you know well. Name one number\nyou would estimate from a sample (customer satisfaction, conversion rate,\naverage basket size) and write two sentences. First say how you would draw\nthe sample and roughly what standard error you would accept. Then say\nwhether collecting four times the data would be worth halving that standard\nerror for the decision you face.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"I would estimate the conversion rate of tasting-stand visitors from a random 100 of them, and a standard error of about 5 percentage points is fine for deciding on a second stand. Collecting four times the data would halve that to about 2.5 points, which is not worth the extra tasting days for this decision.\"\n:::\n\nYou can discuss this task, and any other task in this chapter, with\n**Tilly**, the course AI assistant: ask it to help you sketch the\nsample-size trade-off for your own numbers.\n::::\n\n[Continue to Lecture 9: The t distribution and confidence intervals](b09-t-confidence-intervals.qmd).\n\n[Formula sheet: Lecture 8 formulas](formula-sheet.qmd#formula-l8).\n\nFor a more formal explanation, consult\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapters 13 and 14.\n\n:::\n",
    "supporting": [
      "b08-sampling-distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}