{
  "hash": "d0bcad9ed8d8b4fa53e2d166bf80a29f",
  "result": {
    "engine": "knitr",
    "markdown": "# Tutorial 2: Conditioning and relationships {#b-ep02}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Tutorial 2, you can</span>\n\n- calculate and interpret conditional and joint probabilities;\n- apply independence of events, total probability, and Bayes' rule\n  (Lecture 4);\n- recover marginal distributions from a joint PMF (Lecture 5);\n- interpret covariance and correlation without making causal claims.\n:::\n\nTutorials are **exam preparation sessions**: every task below follows the\nformat of the final exam. The standing routine for each task is the same ---\nthe TA states the task, pairs work on it first for a few minutes with AI use\nallowed, and the solution is then discussed in plenary, starting from the\npair attempts.\n\n::: {.course-phase .phase-before}\n\n## Before class\n\nBring your after-class work from Lectures 4 and 5. Complete these statements\nwithout reopening the chapters:\n\n1. In $P(A\\mid B)$, the reference class is ...\n2. Variance averages ...\n3. Events $A$ and $B$ are independent when ...\n4. A joint PMF records ...\n5. Covariance averages ...\n\nUse the cumulative formula sheet through Lecture 5.\n\nReview [Mathematics Refresher: fractions, products, and\nsums](../resources/math-refresher.html) if needed.\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\n1. The reference class is $B$, the event after the vertical bar.\n2. Variance averages squared deviations from a variable's mean.\n3. $P(A\\cap B)=P(A)P(B)$.\n4. A joint PMF records the probability of every possible value pair.\n5. Covariance averages products of deviations from the two means.\n:::\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In class\n\nAttempt each task before opening its answer. Use the formula and reference\nclass, verify the value, interpret it in context, and qualify the claim.\n\nAll tasks use the Shark Tank teaching file and the two familiar events,\nbuilt exactly as in the lectures:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nD <- sharks$deal_on_show == 1   # on-air deal\nL <- sharks$season >= 9         # late season: Seasons 9-16\n```\n:::\n\n\n\n\n### Task 1 --- Conditional probability and Bayes\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n              Deal\nPeriod         No on-air deal On-air deal\n  Seasons 1-8             330         377\n  Seasons 9-16            229         505\n```\n\n\n:::\n:::\n\n\n\n\n1. Calculate and interpret $P(D\\mid L)$.\n2. Calculate and interpret $P(L\\mid D)$.\n3. Verify $P(D\\cap L)=P(D\\mid L)P(L)$.\n4. Use total probability across $\\{L^c,L\\}$ to recover $P(D)$.\n5. Show how Bayes' rule recovers $P(L\\mid D)$.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$P(D\\mid L)=505/734=0.688$: among late-season records, 68.8% reached an\non-air deal. $P(L\\mid D)=505/882=0.573$: among deal records, 57.3% came from\nlate seasons. The joint probability is\n$(505/734)(734/1441)=505/1441$.\n\n$$\nP(D)=\\frac{377}{707}\\frac{707}{1441}\n     +\\frac{505}{734}\\frac{734}{1441}\n     =\\frac{882}{1441}.\n$$\n\nBayes gives\n$$\nP(L\\mid D)=\\frac{P(D\\mid L)P(L)}{P(D)}\n=\\frac{(505/734)(734/1441)}{882/1441}\n=\\frac{505}{882}.\n$$\n:::\n\n### Task 2 --- Independence of events\n\nLecture 4 defined independence of events in two equivalent ways: through\nconditioning and through the product form. R reports:\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n          P_D   P_D_given_L     P_D_and_L P_D_times_P_L \n    0.6120749     0.6880109     0.3504511     0.3117717 \n```\n\n\n:::\n:::\n\n\n\n\n1. Use the conditional definition to assess empirical independence.\n2. Use the product definition to reach the same conclusion.\n3. Explain why \"not independent\" does not mean \"late season causes a deal.\"\n4. Explain why the early and late events are disjoint but not independent.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe deal probability is about 0.612 overall and 0.688 within late seasons, so\nconditioning changes it. Likewise, the observed joint probability is about\n0.350 rather than the independent product of about 0.312. Thus the empirical\nevents are not independent. This is association in selected observational\nrecords; a time-linked cause is not isolated. Early and late are disjoint\nbecause they cannot occur together. Observing one makes the other impossible,\nso positive-probability disjoint events are dependent.\n:::\n\n### Task 3 --- Joint PMF, covariance, and correlation\n\nLet $X$ be the 0/1 deal indicator and $Y$ the 0/1 late-period indicator,\nbuilt from the same events:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- as.integer(D)\ny <- as.integer(L)\n```\n:::\n\n\n\n\nR reports:\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n   Y\nX           0         1\n  0 0.2290076 0.1589174\n  1 0.2616239 0.3504511\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        E_X         E_Y       Var_X       Var_Y        E_XY  covariance \n 0.61207495  0.50936849  0.23743921  0.24991223  0.35045108  0.03867938 \ncorrelation \n 0.15878503 \n```\n\n\n:::\n:::\n\n\n\n\n1. Verify that the joint PMF sums to 1.\n2. Recover the marginal PMF of $X$ by summing rows.\n3. Verify $\\operatorname{Var}(X)=E[X^2]-E[X]^2$.\n4. Verify $\\operatorname{Cov}(X,Y)=E[XY]-E[X]E[Y]$.\n5. Interpret the sign of covariance.\n6. Explain what correlation changes and what it does not prove.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe four joint masses sum to 1. Summing across the two $Y$ columns gives\n$P(X=0)=559/1441$ and $P(X=1)=882/1441$. Because $X$ is binary,\n$E[X^2]=E[X]$, so $\\operatorname{Var}(X)=E[X]-E[X]^2$. Here\n$E[XY]=P(X=1,Y=1)=505/1441$; subtracting\n$(882/1441)(734/1441)$ gives a positive covariance. Positive covariance means\nthe two 1-coded values co-occur slightly more than under the product of their\nmarginal means. Correlation divides covariance by both SDs, making the result\nunitless. A zero correlation would not establish independence; correlation\ndoes not establish causality or practical importance.\n:::\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n### Timed individual practice --- 10 minutes\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  early_deal_rate    late_deal_rate cor_season_equity   cor_equity_deal \n        0.5332390         0.6880109        -0.4157650        -0.1128703 \n```\n\n\n:::\n:::\n\n\n\n\nWrite no more than 120 words interpreting all four values. Include\ndenominators, direction and rough strength, measurement, and the causal\nboundary.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nAmong Seasons 1--8, 53.3% of records reached an on-air deal; among Seasons\n9--16, 68.8% did so. The 15.5-percentage-point difference is descriptive and\ndoes not identify a causal effect of season. Season and initially offered\nequity have a moderate negative linear association ($r\\approx-0.42$); offered\nequity and the deal indicator have a weak negative linear association\n($r\\approx-0.11$). Offered equity was not randomly assigned, and the outcome\nis an on-air agreement rather than completed investment.\n:::\n\n### Check your understanding\n\nComplete from memory:\n\n1. The conditioning event supplies ...\n2. Independence of events means ...\n3. Covariance averages ...\n4. Correlation standardises ...\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. The conditioning event supplies the denominator or reference class.\n2. Events $A$ and $B$ are independent when\n   $P(A\\cap B)=P(A)P(B)$.\n3. Covariance averages products of deviations from the two means.\n4. Correlation standardises covariance by dividing by both standard\n   deviations.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA venture --- or any business you know well. Name two events\nthat both matter for it (for example \"customer returns\" and \"customer bought\non discount\"), and write two sentences: first state which conditional\nprobability you would most want to know and why the direction of conditioning\nmatters, then say whether you would expect the two events to be independent\nand what a dependence would --- and would not --- tell you.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"I most want $P(\\text{returns} \\mid \\text{bought on discount})$ --- not the reverse --- because I choose whether to run discounts, and this direction tells me about the customers a discount attracts. I expect dependence (discount buyers return less), but dependence alone would not show the discount causes it: bargain-driven customers may differ to begin with.\"\n:::\n\nYou can discuss this task --- and any other task in this tutorial --- with\n**Tilly**, the course AI assistant on Canvas.\n::::\n\nThe next theory chapter, Lecture 6, extends the CDF framework to continuous\nrandom variables and introduces PDFs, uniform distributions, and normal\ndistributions.\n\n:::\n",
    "supporting": [
      "t02-exam-prep_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}