{
  "hash": "6ce49382d27467b22eb9bcf49161447e",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 3: Discrete distributions, expectation, and variance {#b03}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 3, you can</span>\n\n- describe a discrete variable with its probability and cumulative distributions\n- calculate and interpret the expected value of a discrete variable\n- measure spread with variance and standard deviation, also after rescaling\n- keep model expectations and variances apart from sample means and variances\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">Anyone preparing a pitch wants to know what to expect: the typical outcome, and how far real outcomes usually differ from it. Every summary of business risk starts from two numbers: the centre and the spread.</p>\n\nIf your pitch ends in a deal, how many sharks will you work with, and how\nmuch does that number differ from deal to deal?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\nDo all the preparation below before class.\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation</span><br>\nWatch\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/probability-mass-functions/\">Probability Mass Functions</a> and\n<a href=\"https://www.youtube.com/watch?v=_yJsO5955ZE\">Expectation</a>.\nBe ready to explain what $p_X(x)$ measures and why an expected\nvalue does not have to be a possible realised value. All links are also listed in\nthe <a href=\"../resources/video-guide.html\">External Video Guide</a>.\nThe videos explain key ideas in another way and can use a different notation. The lecture material and its notation always come first.\n</div>\n\n[Shark Tank data]{.shark-tag} **Warm up.** Lecture 2 ended with random variables for the\nexperiment that selects one record uniformly at random. Define $X=1$ if the\nselected pitch reached an on-air deal and $X=0$ otherwise. Define $S$ as the\nseason number of the selected pitch.\n\n1. What are the possible values of $X$ and of $S$?\n2. Do these possible values tell us how likely each value is?\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\n1. $X$ can take the values 0 and 1. $S$ can take the values\n   $1,2,\\ldots,16$.\n2. No. The support lists the possible values. A probability distribution\n   must also give a probability to each value. This lecture adds that\n   step.\n:::\n\n[Shark Tank data]{.shark-tag} **Predict.** Answer this question before you come to class: can the expected season be a\nnumber that is not a whole season, yes or no? Choose one answer. You find the\nanswer in the lecture material.\n\nIf functions, support, or summation notation are unfamiliar, review\n[Mathematics Refresher: summation notation](../resources/math-refresher.html#summation-notation).\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## Lecture material\n\n### Start with a founder's question\n\n[Shark Tank data]{.shark-tag} Suppose your pitch ends in a deal. Will you work with one investor who gives\nyou full attention, or with a group of sharks who share the deal? The Shark\nTank file records the number of sharks in each deal in the variable\n`number_sharks_in_deal`. The code below counts the deals by this number:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\ndeals <- subset(sharks, deal_on_show == 1)\nshark_counts <- table(deals$number_sharks_in_deal)\nshark_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   2   3   4   5 \n648 203  22   3   6 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(shark_counts), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    1     2     3     4     5 \n0.735 0.230 0.025 0.003 0.007 \n```\n\n\n:::\n:::\n\n\n\n\nOf the 882 deals, 648 have one shark, 203 have two, 22 have three, 3 have\nfour, and 6 have five. As shares: 0.735, 0.230, 0.025, 0.003, and 0.007.\n\n#### Four questions, answered from the shares\n\n1. **How likely is a deal with exactly one shark?** Read it from the shares: 73.5%.\n2. **How likely is a deal with at most two sharks?** Add the first two\n   shares: 73.5% + 23.0% = 96.5%.\n3. **How many sharks should you expect?** Multiply each number by its share\n   and add the results:\n   $$1\\times0.735+2\\times0.230+3\\times0.025+4\\times0.003+5\\times0.007\\approx1.32.$$\n   No deal has 1.32 sharks. The section on expectation\n   explains how to read such a number.\n4. **How much do deals differ from that number?** Not much: most deals have\n   one shark and nearly all others have two. The section on variance gives\n   one number for this spread.\n\nEach of the four answers uses a tool that has a name. The list of shares is a probability mass\nfunction. The running total in question 2 is a cumulative distribution\nfunction. The weighted average in question 3 is an expected value. The spread\nin question 4 is measured by the variance and the standard deviation.\n\n### A PMF assigns probability to each possible value\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/probability-mass-functions/\">05.3 Probability Mass Functions</a>.</p>\n\n[Shark Tank data]{.shark-tag} A random variable tells us which numerical values we may observe. Its\ndistribution adds the missing information: how the probability is divided\nbetween those values.\n\nFor a discrete random variable $X$, the **probability mass function (PMF)**\nis\n\n$$p_X(x)=P(X=x).$$\n\nRead this notation in parts:\n\n| Symbol | Meaning |\n|---|---|\n| $X$ | the random variable |\n| $x$ | one possible numerical value |\n| $p_X$ | the PMF belonging to $X$ |\n| $p_X(x)$ | the probability that $X$ equals exactly $x$ |\n\nThe probability of one value is also called its probability mass, or mass\nfor short. A valid PMF must meet two rules:\n\n$$\np_X(x)\\ge 0\\quad\\text{for every }x,\n\\qquad\n\\sum_{x\\in\\mathcal X}p_X(x)=1,\n$$\n\nwhere $\\mathcal X$ is the support of $X$. The first rule prevents negative\nprobability. The second says that one of the possible values must occur.\n\n::: {#exm-b03-deal-pmf}\n## Worked example: the deal-indicator PMF, checked\n\nIn the uniform selection experiment from Lecture 2, the deal indicator\n$X$ has support $\\{0,1\\}$. The Shark Tank file has 882 deals among 1,441\nrecords, so 559 records have no deal. The PMF is\n\n$$\np_X(0)=\\frac{559}{1441}\\approx 0.388,\n\\qquad\np_X(1)=\\frac{882}{1441}\\approx 0.612.\n$$\n\nCheck both rules: each mass is non-negative, and\n\n$$\n\\frac{559}{1441}+\\frac{882}{1441}=\\frac{1441}{1441}=1.\n$$\n\nThis is a valid PMF.\n:::\n\nThe code below builds the same objects in R: the data, the deal proportion\n`p_hat`, and the PMF.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\np_hat <- mean(sharks$deal_on_show)   # 882/1441\n\ndeal_pmf <- prop.table(\n  table(factor(sharks$deal_on_show, levels = c(0, 1)))\n)\nnames(deal_pmf) <- c(\"0: no on-air deal\", \"1: on-air deal\")\ndeal_pmf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0: no on-air deal    1: on-air deal \n        0.3879251         0.6120749 \n```\n\n\n:::\n\n```{.r .cell-code}\nsum(deal_pmf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\n\n\nFor the season $S$ (`season` in the Shark Tank file), the PMF in the\nuniform selection experiment gives each season its share of the 1,441\nrecords:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseason_pmf <- prop.table(table(sharks$season))\nround(season_pmf, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     1      2      3      4      5      6      7      8      9     10     11 \n0.0444 0.0250 0.0416 0.0715 0.0805 0.0805 0.0805 0.0666 0.0666 0.0638 0.0666 \n    12     13     14     15     16 \n0.0694 0.0666 0.0604 0.0604 0.0555 \n```\n\n\n:::\n\n```{.r .cell-code}\nsum(season_pmf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nseason_pmf <- prop.table(table(sharks$season))\npmf_df <- data.frame(\n  season = as.numeric(names(season_pmf)),\n  probability = as.numeric(season_pmf)\n)\n\nggplot(pmf_df, aes(x = season, y = probability)) +\n  geom_segment(aes(xend = season, yend = 0),\n               linewidth = 1.1, colour = \"#009E73\") +\n  geom_point(size = 2.6, colour = \"#009E73\") +\n  scale_x_continuous(breaks = 1:16) +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +\n  labs(x = \"Season s\", y = expression(p[S](s))) +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![The PMF of season under uniform record selection: sixteen separated probability masses, one per possible value.](b03-discrete-distributions_files/figure-html/fig-b03-season-pmf-1.png){#fig-b03-season-pmf width=672}\n:::\n:::\n\n\n\n\nThe probability mass above season 5 in @fig-b03-season-pmf has height\n$$p_S(5)=P(S=5)=\\frac{116}{1441}\\approx0.080.$$\nThe graph shows the PMF as separate\nprobability masses, because $S$ can take only the listed discrete values.\nThe term probability density function (PDF) is used only for continuous\nrandom variables. Lecture 6 introduces it.\n\n### A CDF accumulates probability up to a threshold\n\n[Shark Tank data]{.shark-tag} The PMF asks about one exact value. The **cumulative distribution function\n(CDF)** asks how much probability lies at or below a chosen threshold (a\ncut-off value). Imagine moving from left to right across the PMF and keeping a\nrunning total.\n\nFor any random variable $X$,\n\n$$F_X(a)=P(X\\le a).$$\n\nHere $a$ is a threshold, not necessarily a value in the support. For a\ndiscrete random variable,\n\n$$F_X(a)=\\sum_{x\\le a}p_X(x).$$\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**Probability mass function (PMF)** and **cumulative distribution function\n(CDF).** The PMF, $p_X(x)=P(X=x)$, gives the probability that $X$ equals\nexactly the value $x$. The CDF, $F_X(a)=P(X\\le a)$, gives the probability\nthat $X$ is at or below the threshold $a$.\n:::\n\n::: {#exm-b03-cdf-hand}\n## Worked example: F(3) for season, by hand\n\n\"$S\\le 3$\" contains the first three seasons, so add the first three\nprobability masses of the PMF. The season counts are 64, 36, and 60:\n\n$$\nF_S(3)=p_S(1)+p_S(2)+p_S(3)\n=\\frac{64}{1441}+\\frac{36}{1441}+\\frac{60}{1441}\n=\\frac{160}{1441}\\approx0.111.\n$$\n\nAbout 11% of the probability lies at or below season 3.\n:::\n\nThe code below builds the full running total in R. Each CDF value is the\ncurrent PMF value plus all earlier PMF values:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns_values <- as.numeric(names(season_pmf))\np_values <- as.numeric(season_pmf)\nseason_distribution <- data.frame(\n  season = s_values,\n  pmf = round(p_values, 4),\n  cdf = round(cumsum(p_values), 4)\n)\nseason_distribution\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   season    pmf    cdf\n1       1 0.0444 0.0444\n2       2 0.0250 0.0694\n3       3 0.0416 0.1110\n4       4 0.0715 0.1825\n5       5 0.0805 0.2630\n6       6 0.0805 0.3435\n7       7 0.0805 0.4240\n8       8 0.0666 0.4906\n9       9 0.0666 0.5573\n10     10 0.0638 0.6211\n11     11 0.0666 0.6877\n12     12 0.0694 0.7571\n13     13 0.0666 0.8237\n14     14 0.0604 0.8841\n15     15 0.0604 0.9445\n16     16 0.0555 1.0000\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nseason_pmf <- prop.table(table(sharks$season))\ncdf_df <- data.frame(\n  threshold = as.numeric(names(season_pmf)),\n  cdf = cumsum(as.numeric(season_pmf))\n)\n# For the line only: a flat part at 0 before Season 1 and at 1 after Season 16\nstep_df <- rbind(\n  data.frame(threshold = 0, cdf = 0),\n  cdf_df,\n  data.frame(threshold = 17, cdf = 1)\n)\n\nggplot(cdf_df, aes(x = threshold, y = cdf)) +\n  geom_step(data = step_df, linewidth = 0.9, colour = \"#009E73\") +\n  geom_point(size = 1.9, colour = \"#17324D\") +\n  scale_x_continuous(breaks = 1:16) +\n  scale_y_continuous(limits = c(0, 1)) +\n  labs(x = \"Threshold a\", y = expression(F[S](a))) +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![The CDF of season: a step graph that never falls. It is 0 to the left of Season 1, jumps at each possible value by that value's probability mass, and stays at 1 from Season 16 on.](b03-discrete-distributions_files/figure-html/fig-b03-season-cdf-1.png){#fig-b03-season-cdf width=672}\n:::\n:::\n\n\n\n\nA CDF adds up probability as the threshold moves from left to right. It\ncan stay flat or rise, but it cannot fall. It equals 0 below the smallest\npossible value and reaches 1 once it includes all possible values.\nIn @fig-b03-season-cdf the line is flat at 0 to the left of Season 1 and\nflat at 1 to the right of Season 16.\n\nFor a discrete variable, the CDF is a step graph. It stays flat between\npossible values and jumps at each value that has positive probability. A\nlarger jump means that this value has more probability.\n\n::: {.callout-note collapse=\"true\"}\n## Check: read F(8) from the step graph\n\n$F_S(8)=P(S\\le 8)$ is the height of the step graph at threshold 8: the\nfirst eight seasons contain $64+36+60+103+116+116+116+96=707$ records, so\n$F_S(8)=707/1441\\approx0.491$. Just under half of the probability lies in\nSeasons 1--8. This agrees with Lecture 2, where the early-period event\n$L^c$ had probability $707/1441$.\n:::\n\nThe probability of an interval is a difference of two CDF values:\n\n$$P(a<X\\le b)=F_X(b)-F_X(a).$$\n\nFor example,\n$$P(3<S\\le 8)=F_S(8)-F_S(3)=\\frac{707-160}{1441}=\\frac{547}{1441}\\approx0.380.$$\nSo 38.0% of the probability lies in Seasons 4 to 8.\n\nFor the deal indicator:\n\n$$\nF_X(a)=\n\\begin{cases}\n0, & a<0,\\\\\n1-p, & 0\\le a<1,\\\\\n1, & a\\ge1,\n\\end{cases}\n$$\n\nwhere $p=P(X=1)$. So $p_X(1)=P(X=1)=p$, while $F_X(1)=P(X\\le1)=1$. The\nPMF measures the mass at exactly 1. The CDF includes all mass up to and\nincluding 1.\n\n### Expectation is the distribution's weighted centre\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/expectation/\">05.8 Expectation</a>.</p>\n\n[Shark Tank data]{.shark-tag} A distribution can contain many possible values and probabilities. The\n**expected value**, or expectation, summarises its centre in one number.\nValues with larger probabilities receive more weight:\n\n$$E[X]=\\sum_{x\\in\\mathcal X}x\\,p_X(x).$$\n\nThe notation $E[X]$ is read \"the expected value of $X$\". The expected value\nis also called the mean of $X$ and written $\\mu$ (the Greek letter mu) or\n$\\mu_X$. The calculation multiplies each possible value by its probability\nand adds the products. You can also see the result as the balance point of\nthe probability distribution: if the masses were weights on a ruler, the\nruler would balance at this point.\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**Expected value.** The probability-weighted average of the possible values\nof $X$, written $E[X]$, $\\mu$, or $\\mu_X$. If you repeat the experiment\nmany times, the average of the observed values comes close to $E[X]$.\n:::\n\nThis long-run meaning does not make the expected value a guarantee for a\nsingle observation. The weighted average in question 3 at the start of the\nlecture was this calculation: the expected number of sharks in a deal is about 1.32. No\nsingle deal has 1.32 sharks, but over many deals the average number of\nsharks per deal comes close to 1.32.\n\nBefore we use the Shark Tank data again, try the calculation once on a very\nsmall invented distribution.\n\n::: {#exm-b03-tiny-expectation}\n## Worked example: expectation of a tiny PMF\n\nLet $Y$ have support $\\{0,1,2\\}$ with masses\n\n$$p_Y(0)=0.2,\\qquad p_Y(1)=0.5,\\qquad p_Y(2)=0.3.$$\n\nThis is a valid PMF: all masses are non-negative and $0.2+0.5+0.3=1$. Write\nevery product:\n\n$$\nE[Y]\n=0\\times0.2 \\;+\\; 1\\times0.5 \\;+\\; 2\\times0.3\n=0 + 0.5 + 0.6\n=1.1.\n$$\n\nEach possible value contributes its value times its probability. The sum,\n1.1, is the balance point. Note that 1.1 is not in the support: $Y$\nnever equals 1.1.\n:::\n\nNow apply the same steps to the Shark Tank distributions. For the deal\nindicator,\n\n$$E[X]=0\\times(1-p)+1\\times p=p.$$\n\nThis result explains why the mean of a 0/1 variable equals its proportion\nof 1s. Here $E[X]=882/1441\\approx0.612$.\n\nFor the season, the sum has sixteen products instead of two:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns <- as.numeric(names(season_pmf))\np_s <- as.numeric(season_pmf)\n\nc(\n  E_X = 0 * (1 - p_hat) + 1 * p_hat,\n  E_S_from_pmf = sum(s * p_s),\n  observed_mean_season = mean(sharks$season)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 E_X         E_S_from_pmf observed_mean_season \n           0.6120749            8.7959750            8.7959750 \n```\n\n\n:::\n:::\n\n\n\n\nThe expected season is about 8.8, and there is no Season 8.8. This\nanswers the prediction question from before class: an expectation is a\nprobability-weighted average, so it need not be a possible value of the\nrandom variable.\n\n### Expectation after transforming a variable\n\n[Shark Tank data]{.shark-tag} Many quantities come from a random variable through a fixed rule. Examples\nfor the variable $Y$ of the worked example are the profit $10Y-3$ (10 euros\nper unit of $Y$ minus a fixed cost of 3 euros) and the square $Y^2$. Such a\nfunction $g(X)$ of a random variable $X$ is itself a random variable, with\nits own possible values and its own distribution.\n\nIf $g$ changes each possible value of $X$, the expected value of the\ntransformed variable is\n\n$$E[g(X)]=\\sum_{x\\in\\mathcal X}g(x)\\,p_X(x).$$\n\nThe probabilities do not change. Apply $g$ to each possible value, weight\nthe transformed values by the original PMF, and add.\n\n::: {.callout-caution collapse=\"true\"}\n## Try it: E[Y²] for the tiny PMF\n\nTry this first with the student next to you. Use the same distribution as\nin the worked example: $Y\\in\\{0,1,2\\}$ with masses $0.2,0.5,0.3$, and $g(y)=y^2$.\n\n*Step 1 (given).* Square each possible value: $0^2=0$, $1^2=1$, $2^2=4$.\n\n*Step 2 (you).* Multiply each squared value by its original probability\nand write the three products.\n\n*Step 3 (you).* Add them to get $E[Y^2]$. Is it equal to\n$\\left(E[Y]\\right)^2=1.1^2$?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$$\nE[Y^2]=0\\times0.2+1\\times0.5+4\\times0.3=0+0.5+1.2=1.7.\n$$\n\nIt is not $\\left(E[Y]\\right)^2=1.21$. Squaring and then averaging\ndiffers from averaging and then squaring. The gap between the two is\n$1.7-1.21=0.49$. The section on variance gives this gap a name.\n:::\n:::\n\nThe same rule for season in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(\n  E_S = sum(s * p_s),\n  E_S_squared = sum(s^2 * p_s)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        E_S E_S_squared \n   8.795975   95.505205 \n```\n\n\n:::\n:::\n\n\n\n\n### Variance and standard deviation\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/variance/\">06.2 Variance</a>.</p>\n\n[Shark Tank data]{.shark-tag} Expectation gives the centre of a distribution, but it does not describe\nhow close the values lie to that centre. Two distributions can have\nthe same expectation and very different spreads. Both distributions in\n@fig-b03-same-mean-spread have expectation 1. Which one is riskier, and\nwhy?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nspread_df <- data.frame(\n  x = rep(0:2, times = 2),\n  probability = c(0.10, 0.80, 0.10,    # Distribution A\n                  0.45, 0.10, 0.45),   # Distribution B\n  distribution = rep(c(\"Distribution A (variance = 0.20)\",\n                       \"Distribution B (variance = 0.90)\"), each = 3)\n)\n\nggplot(spread_df, aes(x = x, y = probability)) +\n  geom_vline(xintercept = 1, colour = \"#C98B2E\",\n             linetype = \"dashed\", linewidth = 0.8) +\n  geom_segment(aes(xend = x, yend = 0),\n               linewidth = 1.1, colour = \"#009E73\") +\n  geom_point(size = 2.6, colour = \"#009E73\") +\n  annotate(\"text\", x = 1.1, y = 0.87, label = \"mean = 1\",\n           hjust = 0, colour = \"#17324D\", size = 3.4) +\n  facet_wrap(~ distribution) +\n  scale_x_continuous(breaks = 0:2) +\n  scale_y_continuous(limits = c(0, 0.9),\n                     expand = expansion(mult = c(0, 0.05))) +\n  labs(x = \"Possible value of X\", y = \"Probability\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\"),\n    strip.text = element_text(colour = \"#17324D\", face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![Two distributions with the same expectation and very different spreads. The dashed line marks the common mean, 1.](b03-discrete-distributions_files/figure-html/fig-b03-same-mean-spread-1.png){#fig-b03-same-mean-spread width=672}\n:::\n:::\n\n\n\n\nThe horizontal axis lists the possible values and the vertical axis gives\ntheir probabilities. The centre is the same, but Distribution B has greater\nspread because values 0 and 2 receive much more probability. If these were\npayoffs, B would be the riskier choice. Variance is the number that measures\nthis difference.\n\nTo measure spread, start with the deviation $X-\\mu$, where $\\mu=E[X]$.\nIf we averaged the deviations directly, positive and negative deviations\nwould cancel each other. So the **variance** squares each deviation before it\ntakes the probability-weighted average:\n\n$$\n\\operatorname{Var}(X)\n=E[(X-\\mu)^2]\n=\\sum_x (x-\\mu)^2\\,p_X(x).\n$$\n\nThe variance is also written $\\sigma^2$, read \"sigma squared\" ($\\sigma$ is\nthe Greek letter sigma). Read the calculation as four steps:\n\n1. Find the centre, $\\mu=E[X]$.\n2. Measure each possible deviation, $x-\\mu$.\n3. Square the deviation, $(x-\\mu)^2$.\n4. Weight it by $p_X(x)$ and add across the support.\n\nSo large deviations contribute more than small deviations. Variance is zero\nonly when all probability lies at one single value.\n\nThe equivalent **computational form** is\n\n$$\\operatorname{Var}(X)=E[X^2]-\\left(E[X]\\right)^2.$$\n\nIt gives the same result, but the definition $E[(X-\\mu)^2]$ is usually\neasier to interpret.\n\nThe **standard deviation** is the square root of the variance. It is also\nwritten $\\sigma$:\n\n$$\\operatorname{SD}(X)=\\sqrt{\\operatorname{Var}(X)}.$$\n\nVariance has squared units. Standard deviation returns to the units of $X$.\nIf $X$ is measured in seasons, $\\operatorname{Var}(X)$ is in seasons\nsquared, a unit that nobody can imagine, while $\\operatorname{SD}(X)$ is\nback in seasons.\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**Variance and standard deviation.** The variance, $\\operatorname{Var}(X)$\nor $\\sigma^2$, is the probability-weighted average of the squared deviations\nof $X$ from its mean $\\mu$. The standard deviation, $\\operatorname{SD}(X)$ or\n$\\sigma$, is the square root of the variance and has the same units as $X$.\n:::\n\n::: {#exm-b03-tiny-variance}\n## Worked example: variance of the tiny PMF, both ways\n\nSame $Y$ as before: values $0,1,2$ with masses $0.2,0.5,0.3$, and\n$\\mu=E[Y]=1.1$.\n\n**By the definition**, in four steps:\n\n$$\n\\operatorname{Var}(Y)\n=(0-1.1)^2(0.2)+(1-1.1)^2(0.5)+(2-1.1)^2(0.3)\n$$\n$$\n=1.21\\times0.2+0.01\\times0.5+0.81\\times0.3\n=0.242+0.005+0.243\n=0.49.\n$$\n\n**By the computational form**, using $E[Y^2]=1.7$ from the Try it task:\n\n$$\n\\operatorname{Var}(Y)=E[Y^2]-\\left(E[Y]\\right)^2=1.7-1.21=0.49.\n$$\n\nBoth ways give 0.49, so $\\operatorname{SD}(Y)=\\sqrt{0.49}=0.7$, in the\nsame units as $Y$.\n:::\n\nA variable with only the values 0 and 1, such as the deal indicator, is so\ncommon that its distribution has a name.\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**Bernoulli distribution.** A random variable $X$ that takes only the values\n0 and 1, with $P(X=1)=p$ and $P(X=0)=1-p$, has a Bernoulli distribution,\nwritten $X\\sim\\text{Bernoulli}(p)$. Its expected value is $p$ and its\nvariance is $p(1-p)$.\n:::\n\nThe symbol $\\sim$ is read \"is distributed as\". We found the expected value $p$\nin the section on expectation. The variance follows from the\ncomputational form. Since $X^2=X$ when $X$ is 0 or 1, $E[X^2]=E[X]=p$, so\n\n$$\n\\operatorname{Var}(X)=p-p^2=p(1-p).\n$$\n\nThe deal indicator is a Bernoulli variable with $p=882/1441\\approx0.612$.\nIts variance is $0.612\\times0.388\\approx0.237$ and its standard deviation is\nabout 0.49.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_s <- sum(s * p_s)\nvar_s <- sum((s - mu_s)^2 * p_s)\n\nc(\n  Var_X = p_hat * (1 - p_hat),\n  SD_X = sqrt(p_hat * (1 - p_hat)),\n  Var_S = var_s,\n  SD_S = sqrt(var_s),\n  average_distance_S = sum(abs(s - mu_s) * p_s)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Var_X               SD_X              Var_S               SD_S \n         0.2374392          0.4872773         18.1360282          4.2586416 \naverage_distance_S \n         3.6568416 \n```\n\n\n:::\n:::\n\n\n\n\nThe season has a variance of about 18.1 seasons squared and a standard\ndeviation of about 4.3 seasons. The season of a randomly selected pitch\ntypically lies about four seasons away from the expected season 8.8. Four\nseasons are a quarter of the 16 seasons. The standard deviation is somewhat\nlarger than the plain average distance (about 3.7 seasons here), because\nsquaring gives large deviations more weight.\n\nThe opening question asked how much deals differ in their number of sharks.\nThe same two steps answer it:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- as.numeric(names(shark_counts))\np_k <- as.numeric(prop.table(shark_counts))\nmu_k <- sum(k * p_k)\nc(expected_sharks = mu_k,\n  variance = sum((k - mu_k)^2 * p_k),\n  sd = sqrt(sum((k - mu_k)^2 * p_k)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nexpected_sharks        variance              sd \n      1.3174603       0.3686067       0.6071299 \n```\n\n\n:::\n:::\n\n\n\n\nThe expected number of sharks is 1.32 and the standard deviation is about\n0.61 sharks, which is less than one shark. So the number of sharks differs\nlittle from deal to deal.\n\n### Shifting and rescaling a variable {#b03-shift-rescale}\n\nBusiness quantities are often built from other quantities: revenue is price\ntimes units, profit is revenue minus a fixed cost. For constants $a$ and $b$,\n\n$$\nE[aX+b]=aE[X]+b,\n\\qquad\n\\operatorname{Var}(aX+b)=a^2\\operatorname{Var}(X),\n$$\n$$\n\\operatorname{SD}(aX+b)=|a|\\operatorname{SD}(X).\n$$\n\nAdding a constant $b$ moves the centre and leaves the spread unchanged.\nMultiplying by $a$ multiplies the centre by $a$ and the standard deviation\nby $|a|$, the size of $a$ without its sign. So the variance is multiplied\nby $a^2$.\n\nAn example with the tiny PMF: $Y$ has $E[Y]=1.1$,\n$\\operatorname{Var}(Y)=0.49$, and $\\operatorname{SD}(Y)=0.7$. If each unit of\n$Y$ earns 10 euros and there is a fixed cost of 3 euros, the profit is\n$10Y-3$. Its expectation is $10\\times1.1-3=8$ euros. Its variance is\n$10^2\\times0.49=49$ euros squared, and its standard deviation is\n$10\\times0.7=7$ euros.\n\nStandardising in [Lecture 6](b06-continuous-normal.qmd) uses this rule. Subtract the mean $\\mu$ from $X$ and divide by the standard deviation\n$\\sigma$. The result $(X-\\mu)/\\sigma$ then has mean 0 and standard\ndeviation 1. Lecture 8 uses the same rules to find the spread of a sample\nmean.\n\n### Model expectation and the sample mean\n\n[Shark Tank data]{.shark-tag} For observed values $x_1,\\ldots,x_n$, the sample mean is\n\n$$\\bar{x}=\\frac{1}{n}\\sum_{i=1}^n x_i.$$\n\nNow give every observed row the same probability, $1/n$. This distribution\nis called the **empirical distribution** of the data. Its expectation is\n\n$$\\sum_{i=1}^n x_i\\,\\frac{1}{n}=\\bar{x}.$$\n\nThe two numbers are equal, but the two terms have different meanings. Expectation\ndescribes a probability distribution. The sample mean summarises observed\ndata.\n\nThe same difference exists for spread. The variance of the empirical\ndistribution weights each of the $n$ observations by $1/n$, so it divides\nby $n$. The usual **sample variance** divides by $n-1$:\n\n$$s^2=\\frac{1}{n-1}\\sum_{i=1}^n\\left(x_i-\\bar{x}\\right)^2.$$\n\nIts square root $s$ is the sample standard deviation. R's `var()` and `sd()`\ndivide by $n-1$. [Lecture 7](b07-samples-estimators.qmd) explains why we divide\nby $n-1$ when we estimate a population variance.\n\nAn invented example shows the calculation by hand. A founder counts the\norders on five days: 3, 5, 6, 8, and 8. The mean is $\\bar x=30/5=6$ orders.\nThe deviations from the mean are $-3$, $-1$, $0$, $2$, and $2$. Their\nsquares add up to $9+1+0+4+4=18$. Divide by $n-1=4$:\n$s^2=18/4=4.5$ orders squared, so $s=\\sqrt{4.5}\\approx2.12$ orders. A\ntypical day lies about two orders, or about a third of the mean, away from\nthe mean. Dividing by $n=5$ would give $3.6$ instead of $4.5$. R gives the\nsame numbers:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\norders <- c(3, 5, 6, 8, 8)\nc(mean = mean(orders), var = var(orders), sd = sd(orders),\n  var_divide_n = mean((orders - mean(orders))^2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        mean          var           sd var_divide_n \n     6.00000      4.50000      2.12132      3.60000 \n```\n\n\n:::\n:::\n\n\n\n\nThe code below computes both versions for the number of words in the written description (`description_words`) in the\nShark Tank file:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw <- sharks$description_words\nc(\n  mean_words = mean(w),\n  empirical_expectation = sum(w * rep(1 / length(w), length(w))),\n  empirical_variance_divide_n = mean((w - mean(w))^2),\n  sample_variance_divide_n_minus_1 = var(w),\n  sample_sd = sd(w)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      mean_words            empirical_expectation \n                        4.995142                         4.995142 \n     empirical_variance_divide_n sample_variance_divide_n_minus_1 \n                        3.646749                         3.649282 \n                       sample_sd \n                        1.910309 \n```\n\n\n:::\n:::\n\n\n\n\nBoth centre calculations give about 5.0 words for these 1,441 records. The\ntwo variances, 3.647 and 3.649, differ only in the third decimal because $n$\nis large. All these numbers summarise the same observations. To use one of\nthem as an estimate for a larger population, you also need to know how the\nsample was drawn. Lecture 7 covers this. There, the model quantities $\\mu$\nand $\\sigma^2$ of this lecture become the parameters of a population: fixed\nnumbers that describe the whole population. The data quantities $\\bar x$ and\n$s^2$ become statistics: numbers calculated from a sample. The first figure\nof Lecture 7 shows how the model quantities and the data quantities are\nconnected.\n\n::: {.caveat-box}\n<span class=\"label\">What an expected value can and cannot promise</span>\n\n- An expected value is not a promise for one case. No deal has 1.32 sharks,\n  and no pitch gets \"0.612 of a deal\".\n- Single outcomes can lie far from the expected value. The standard deviation\n  says how far, typically.\n- All numbers here describe the recorded pitches. For future pitches they are\n  only forecasts, and these forecasts depend on the assumptions of Lecture 2.\n\n**What you can do with it:** plan with the expected value when a decision\nrepeats many times, and look at the spread when one bad outcome would cause\nserious damage.\n:::\n\n### Answering the driving question\n\nIf your pitch ends in a deal, expect to work with one shark. 73.5% of deals\nhave exactly one shark and 96.5% have at most two. The expected number is\n1.32, with a standard deviation of about 0.61. The same two numbers, centre\nand spread, describe the other variables of this lecture. The deal indicator\nis a Bernoulli variable: a recorded pitch reaches an on-air deal with\nprobability 0.612, and the variance is about 0.24. The season has expected\nvalue $E[S]\\approx8.8$ and a standard deviation of about 4.3 seasons. Centre\nand spread together describe a distribution. One of them alone can give a\nwrong picture.\n\n::: {.founder-box}\n<span class=\"label\">A founder's decision (invented example)</span>\n\nYour lunch startup sells boxes with prepared meals. Tomorrow you sell 20 meal boxes with probability 0.2, 30 with probability 0.5, and 40 with probability 0.3. The expected value is 31 meal boxes and the standard deviation is 7. A meal box that you prepare but do not sell costs you 3 euros of ingredients. A customer you cannot serve costs you 5 euros of margin. Compare the expected cost of three plans: preparing 20 meal boxes costs 55 euros a day on average, preparing 30 costs 21 euros, and preparing 40 costs 27 euros. The decision: prepare 30. The expected value told you where to aim. The spread and the two costs told you how much a wrong guess costs.\n:::\n\n**Next:** We can now say what a typical pitch looks like and how much pitches\nvary around it. But those are answers about a pitch we know nothing about.\nIn practice we always know something: its season, its industry, or the\nrating of an AI tool that screens pitches. Lecture 4 asks how probabilities\nchange when new information arrives. It covers conditional probability and\nthe total-probability rule, which rebuilds an overall rate from group rates.\nIt also covers Bayes' rule, which reverses the direction of a question, and\nindependence, the case in which new information changes nothing.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\nAfter the lecture, work through all the practice below.\n\n### Read the lecture material\n\nRead the Lecture material section above from start to end. The lecture\ncovered the most important parts. The text has every step, every example, and all the\ncode, including parts that were not shown in class. Note what is still\nunclear and bring it to the next tutorial, or ask Tilly.\n\n### Recall questions\n\n1. What information does a PMF add to the support of a random variable?\n2. Which two rules must every PMF follow?\n3. What is the difference between $p_X(x)$ and $F_X(x)$?\n4. Why can an expectation be a value the random variable never takes?\n5. What does the variance average, and why do we square the deviations first?\n6. Why do variance and standard deviation have different units, and which\n   one is easier to interpret?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. The support lists possible values. The PMF gives a probability to each\n   value.\n2. Every probability mass is non-negative, and the masses sum to 1.\n3. $p_X(x)=P(X=x)$ is the mass at exactly $x$. $F_X(x)=P(X\\le x)$ is all\n   probability accumulated up to and including $x$.\n4. Expectation is a probability-weighted average and need not belong to the\n   support.\n5. Variance averages squared deviations from the distribution mean. The\n   probability-weighted raw deviations sum to zero. Squaring prevents\n   positive and negative deviations from cancelling each other.\n6. Variance is in squared units of $X$. The standard deviation is its\n   square root and returns to the units of $X$, which makes it the easier\n   summary to interpret.\n:::\n\n### Finish a half-worked example\n\nRe-read the two tiny-PMF worked examples (@exm-b03-tiny-expectation and\n@exm-b03-tiny-variance). Then do all the steps on a new invented\ndistribution. Let $W$ have support $\\{0,1,2\\}$ with masses $0.3$, $0.4$,\nand $0.3$.\n\n*Step 1 (given).* Validity: all masses are non-negative and\n$0.3+0.4+0.3=1$.\n\n*Step 2 (you).* Calculate $F_W(1)$.\n\n*Step 3 (you).* Calculate $E[W]$, writing each product.\n\n*Step 4 (you).* Calculate $E[W^2]$, then $\\operatorname{Var}(W)$ with the\ncomputational form, then $\\operatorname{SD}(W)$.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$F_W(1)=P(W\\le1)=0.3+0.4=0.7$.\n$E[W]=0(0.3)+1(0.4)+2(0.3)=1.0$.\n$E[W^2]=0(0.3)+1(0.4)+4(0.3)=1.6$, so\n$\\operatorname{Var}(W)=1.6-1.0^2=0.6$ and\n$\\operatorname{SD}(W)=\\sqrt{0.6}\\approx0.77$.\nCompare $W$ with the variable $Y$ of the worked examples. Both take the\nvalues 0, 1, and 2, but $W$ has the larger variance ($0.6>0.49$), because\nmore of its probability lies at the two ends, 0 and 2.\n:::\n\n### Practice\n\n[Shark Tank data]{.shark-tag} Tasks 1 to 5 use the Shark Tank distributions of the lecture material.\nTask 6 uses an invented example.\n\n1. For the deal indicator with $p=882/1441$, calculate $F_X(0.4)$.\n2. Use the season CDF table to calculate $P(3<S\\le6)$.\n3. A Bernoulli variable has $p=0.25$. Calculate its variance and standard\n   deviation.\n4. The standard deviation of season is about 4.3. Write one sentence that\n   interprets this number and names its units.\n5. Why is $\\operatorname{Var}(S)\\approx18.1$ harder to interpret than\n   $\\operatorname{SD}(S)\\approx4.3$?\n6. An invented example. A founder sells phone cases at a weekend market.\n   The number of cases sold on one day, $X$, has $E[X]=12$ and\n   $\\operatorname{SD}(X)=4$. Each case brings in 15 euros and the stall\n   costs 60 euros per day, so the profit of one day is $15X-60$ euros.\n   Calculate the expected value, the variance, and the standard deviation\n   of the profit.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. Because $0\\le0.4<1$, $F_X(0.4)=P(X=0)=559/1441\\approx0.388$.\n2. $P(3<S\\le6)=F_S(6)-F_S(3)=(495-160)/1441=335/1441\\approx0.232$.\n3. $\\operatorname{Var}=0.25\\times0.75=0.1875$.\n   $\\operatorname{SD}=\\sqrt{0.1875}\\approx0.43$.\n4. The season of a randomly selected pitch typically differs from the\n   expected season (about 8.8) by roughly 4.3 seasons.\n5. Variance is measured in seasons squared, a unit that is hard to\n   imagine. The standard deviation is back in seasons.\n6. Use the rules for $aX+b$ with $a=15$ and $b=-60$. The expected profit is\n   $15\\times12-60=120$ euros. $\\operatorname{Var}(X)=4^2=16$, so the\n   variance of the profit is $15^2\\times16=3600$ euros squared. The standard\n   deviation of the profit is $15\\times4=60$ euros, half of the expected\n   profit. The stall cost of 60 euros lowers the expected profit and leaves\n   the spread unchanged.\n:::\n\n### Review: one question from Lecture 2\n\n[Shark Tank data]{.shark-tag} Using the Lecture 2 counts table ($|D^c|=559$, $|L|=734$,\n$|D^c\\cap L|=229$, $n=1441$), calculate $P(D^c\\cup L)$ and interpret it in\none sentence.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$P(D^c\\cup L)=(559+734-229)/1441=1064/1441\\approx0.738$: about 74% of the\nrecorded pitches failed to reach an on-air deal, came from Seasons 9--16,\nor both. We subtract the overlap (229 late-season no-deal records) once, so\nthat no record counts twice.\n:::\n\n### Worked exam interpretation\n\n[Shark Tank data]{.shark-tag} **Question.** For the number of sharks in a deal, R reports, after\nrounding, `expected_sharks` 1.32 and `sd` 0.61. Interpret both numbers in\ncontext, with their units.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nThe 1.32 is the expected number of sharks in a deal: the average of the\nshark counts of the recorded deals, each count weighted by its share. No\ndeal has 1.32 sharks, because an expected value need not be a possible\nvalue. The 0.61 is the standard deviation, in sharks. The number of sharks\nin a deal typically differs from 1.32 by about 0.6 sharks, less than one\nshark, so the number of sharks differs little between deals. Both numbers describe the\nrecorded deals. They do not guarantee the number of sharks for a future\npitch.\n:::\n\n### Worked exam interpretation: from a PMF to the standard deviation\n\n**Exam-style question.** An invented example. A venture sells one product per customer,\nat one of three prices. Let $V$ be the price paid by a randomly selected customer, in\neuros, with PMF $p_V(10)=0.5$, $p_V(20)=0.3$, $p_V(40)=0.2$. (a) Verify\nthat this is a valid PMF. (b) Calculate $F_V(20)$. (c) Calculate $E[V]$\nand $E[V^2]$. (d) Calculate $\\operatorname{Var}(V)$ and\n$\\operatorname{SD}(V)$, stating the units of each.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\n&#40;a) All masses are non-negative and $0.5+0.3+0.2=1$.\n&#40;b) $F_V(20)=P(V\\le20)=0.5+0.3=0.8$.\n&#40;c) $E[V]=10(0.5)+20(0.3)+40(0.2)=5+6+8=19$ euros.\n$E[V^2]=100(0.5)+400(0.3)+1600(0.2)=50+120+320=490$.\n&#40;d) $\\operatorname{Var}(V)=490-19^2=490-361=129$ euros squared.\n$\\operatorname{SD}(V)=\\sqrt{129}\\approx11.4$ euros. The expected revenue\nper customer is 19 euros. The typical deviation from it is about 11 euros,\nmore than half of the expected value.\n:::\n\n### Check the AI\n\n[Shark Tank data]{.shark-tag} You asked an AI assistant: \"How many sharks will I work with if I get a deal?\" It answered:\n\n> \"The expected number of sharks is 1.32. The expected value is the most likely value, so in most deals you negotiate with 1.32 sharks.\"\n\nFind what is wrong and write the corrected answer. This is the **Verify**\nstep of Attempt → Ask → Verify → Explain.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nNo deal has 1.32 sharks. The expected value is a weighted average, not the most likely value. The most likely number is one shark: 73.5% of deals have exactly one. The 1.32 is still useful, for example to plan for many deals, but it describes the centre of the distribution, not a single deal.\n:::\n\n### Make it yours\n\n:::: {.utility-prompt}\n<span class=\"label\">Two sentences about your own venture</span>\n\nThink of your EiA venture, or any business you know well. Pick one\nuncertain quantity with a few possible values, for example the units\nsold next week, the price a customer picks, or the orders per day. Sentence\n1: describe its approximate PMF and give its expected value. Sentence 2: does\nthe centre or the spread matter more for a real decision you would make, and\nwhy? There is no wrong answer.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run venture that sells boxes of prepared meals on campus. \"Daily orders next week are roughly 20 with probability 0.2, 30 with probability 0.5, and 40 with probability 0.3, so the expected value is about 31. The spread matters more than the centre for me, because I prepare ingredients in advance: a day with 40 orders when I have prepared for only 20 costs me more than an average day earns.\"\n:::\n\nYou can discuss this task, and any other task in this chapter, with\nTilly for QM Basic, the course AI assistant: ask it to check whether your\nPMF is valid and to compute its standard deviation with you.\n::::\n\n### More practice\n\nFor extra exercises on this lecture, with worked solutions, ask Tilly for\nQM Basic, the course AI assistant. For example: \"Give me an extra exercise for\nLecture 3. Show the solution only after I send my answer.\"\n\n[Continue to Tutorial 1: Evidence and probability foundations](t01-exam-prep.qmd).\n\n[Formula sheet: Lecture 3 formulas](formula-sheet.qmd#formula-l3).\n\nFor a more formal explanation, consult\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapter 8.\n\n:::\n",
    "supporting": [
      "b03-discrete-distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}