{
  "hash": "b173cba67d9e529f6d8939ec5b73fced",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 4: Multiple regression and what controls do {#i04}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 4, you can</span>\n\n- state a multiple linear regression model;\n- interpret a coefficient while holding the other included predictors fixed;\n- explain, with a constructed example, why simple and multiple-regression\n  coefficients can differ;\n- fit and compare multiple-regression specifications in R;\n- scale a coefficient to a comparison a reader cares about;\n- distinguish statistical control from causal identification.\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">Two stories can produce the same pattern: perhaps equity offers genuinely fell over time, or perhaps later pitches simply ask for different amounts. Separating overlapping explanations is the core job of multiple regression --- and of most business analytics.</p>\n\nLater seasons show smaller equity offers. Is that a time story, or is it\nreally a money story in disguise, since later pitches also ask for different\namounts?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 30 minutes.</span>\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation (15 minutes)</span><br>\nWatch Stanford Statistical Learning\n<a href=\"https://www.youtube.com/watch?v=o9hoLdylWKo&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=11\">3.3\nMultiple Linear Regression</a>. Focus on the conditional interpretation of\none coefficient and the reason several predictors may be included together.\nAll links are also listed in the\n<a href=\"../resources/video-guide.html\">External Video Guide</a>.\n</div>\n\n**Reactivate (10 minutes).** In Lecture 3 you fitted the simple season model\nand tested its slope. Fit it again, then fit the two-predictor model that adds\nthe requested amount in thousands of dollars, and bring **both season\ncoefficients** to class:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nsharks$ask_1k <- sharks$ask_amount_usd / 1000\ncoef(lm(equity_offered_pct ~ season, data = sharks))\ncoef(lm(equity_offered_pct ~ season + ask_1k, data = sharks))\n```\n:::\n\n\n\n\n**Predict (5 minutes).** Answer the one-click Mentimeter question posted on\nCanvas before you come to class: once the requested amount is added, will the\nseason coefficient move **towards zero**, **away from zero**, or **barely\nmove**? Think about why the slope might change at all: if the requested\namount is associated with both season and offered equity, the simple slope\nmixes their relationships. Commit to an answer; the lecture resolves it.\n\nIf subscripts or multivariable equations feel rusty, review\n[Mathematics Refresher: subscripts and multivariable equations](../resources/math-refresher.html).\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In class\n\nThe session opens with the usual four-minute entry quiz on the prep videos,\nthen turns to the driving question. Your warm-up produced two season\ncoefficients --- about $-0.824$ without the requested amount and $-0.814$\nwith it. This lecture explains what the second number means, why the two can\ndiffer, and why here they barely do.\n\n### More than one predictor\n\n<p class=\"concept-video\"><strong>Stanford explanation (review):</strong>\n<a href=\"https://www.youtube.com/watch?v=o9hoLdylWKo\">3.3 Multiple Linear Regression</a>.</p>\n\nFor predictors $X_{i1},\\ldots,X_{ik}$, the model is\n\n$$\nY_i=\\beta_0+\\beta_1X_{i1}+\\cdots+\\beta_kX_{ik}+\\varepsilon_i,\n$$\n\nwith conditional mean\n\n$$\nE[Y_i\\mid X_{i1}=x_1,\\ldots,X_{ik}=x_k]\n=\\beta_0+\\beta_1x_1+\\cdots+\\beta_kx_k.\n$$\n\nThe coefficient $\\beta_j$ is the expected change in $Y$ for a one-unit\nincrease in $X_j$, **holding the other included predictors fixed**. That\nphrase must appear in every multiple-regression slope interpretation you\nwrite in this course.\n\nIt describes a **model-based comparison**. It does not require that two real\npitches exist that are identical on every feature; it compares fitted\nconditional means at fixed values of the included variables. The model does\nthe holding fixed --- the data need not contain twins.\n\n### Why coefficients change: a constructed demonstration\n\nBefore touching the Shark Tank data, watch the mechanism operate where we\ncontrol it completely, because we built the data ourselves. Imagine 200 small\nfirms. A single background variable --- firm **size** --- drives both\nadvertising spend and revenue. Advertising itself contributes nothing: the\nrevenue line below contains `size` but no `adspend` term.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nn <- 200\nsize    <- rnorm(n, mean = 10, sd = 2)          # Z: firm size (drives both)\nadspend <- 2 + 0.8 * size + rnorm(n, sd = 1)    # X: bigger firms spend more\nrevenue <- 5 + 1.5 * size + rnorm(n, sd = 1.5)  # Y: size drives revenue,\ndemo <- data.frame(revenue, adspend, size)      #    adspend does not\ncoef(lm(revenue ~ adspend, data = demo))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)     adspend \n   5.957361    1.391909 \n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(lm(revenue ~ adspend + size, data = demo))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)     adspend        size \n  5.0975426   0.1007622   1.3804961 \n```\n\n\n:::\n:::\n\n\n\n\nThe simple slope of `adspend` is about $1.39$: strongly positive, and highly\nsignificant if you check its t statistic. Yet we *know* advertising does\nnothing here. Once `size` enters the model, the `adspend` slope collapses to\nabout $0.10$ with a p-value around $0.39$ --- indistinguishable from the zero\nwe built in. The simple slope was entirely an **omitted-variable** artefact:\n`adspend` earned credit for the size differences it was correlated with.\n\n@fig-i04-ovb-scatter makes the mechanism visible. Larger firms (orange) sit\nhigh on *both* axes; smaller firms (blue) sit low on both. Sliding along the\noverall cloud from left to right, you move from small firms to large firms\n--- so the simple slope compares different kinds of firms. *Within* each\ncolour, the cloud is nearly flat: at a given size, spending more is not\nassociated with more revenue.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nset.seed(42)\nn <- 200\nsize    <- rnorm(n, mean = 10, sd = 2)          # Z: firm size (drives both)\nadspend <- 2 + 0.8 * size + rnorm(n, sd = 1)    # X: bigger firms spend more\nrevenue <- 5 + 1.5 * size + rnorm(n, sd = 1.5)  # Y: size drives revenue,\ndemo <- data.frame(revenue, adspend, size)      #    adspend does not\ndemo$group <- ifelse(demo$size > median(demo$size),\n                     \"Larger firms (size above median)\",\n                     \"Smaller firms (size below median)\")\nsimple_fit <- lm(revenue ~ adspend, data = demo)\n\nggplot(demo, aes(x = adspend, y = revenue,\n                 colour = group, shape = group)) +\n  geom_abline(intercept = coef(simple_fit)[1],\n              slope = coef(simple_fit)[2],\n              colour = \"#17324D\", linewidth = 1.1) +\n  geom_point(alpha = 0.75, size = 2) +\n  annotate(\"text\", x = max(demo$adspend) - 0.2,\n           y = coef(simple_fit)[1] + coef(simple_fit)[2] *\n             (max(demo$adspend) - 0.2) - 2.4,\n           label = \"simple regression line\",\n           hjust = 1, colour = \"#17324D\", size = 3.4) +\n  scale_colour_manual(values = c(\n    \"Larger firms (size above median)\" = \"#D55E00\",\n    \"Smaller firms (size below median)\" = \"#0072B2\"\n  )) +\n  scale_shape_manual(values = c(\n    \"Larger firms (size above median)\" = 17,\n    \"Smaller firms (size below median)\" = 16\n  )) +\n  labs(x = \"Advertising spend (constructed units)\",\n       y = \"Revenue (constructed units)\",\n       colour = NULL, shape = NULL) +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\"),\n    legend.position = \"top\"\n  )\n```\n\n::: {.cell-output-display}\n![Constructed data: revenue against advertising spend for 200 simulated firms, coloured by firm size. The overall upward drift comes entirely from size; within a colour group the relationship is nearly flat.](i04-multiple-regression_files/figure-html/fig-i04-ovb-scatter-1.png){#fig-i04-ovb-scatter width=672}\n:::\n:::\n\n\n\n\nA coefficient changes when an added predictor accounts for variation that the\nsimpler association had absorbed. That is the entire mechanism --- and it is\nwhy \"holding the other included predictors fixed\" is not decoration but the\nsubstance of the estimate.\n\n### The real-data contrast: the season slope barely moves\n\nNow the same comparison on the Shark Tank data. The running money unit from\nhere on is **thousands of dollars**: `ask_1k` is the requested amount divided\nby 1,000, so one unit is $1,000 and 100 units are $100,000 (Lecture 1 showed\nhow a coefficient rescales when the unit changes).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nsharks$ask_1k <- sharks$ask_amount_usd / 1000\nm_simple   <- lm(equity_offered_pct ~ season, data = sharks)\nm_adjusted <- lm(equity_offered_pct ~ season + ask_1k, data = sharks)\nc(\n  simple           = coef(m_simple)[\"season\"],\n  adjusted_for_ask = coef(m_adjusted)[\"season\"]\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          simple.season adjusted_for_ask.season \n             -0.8241241              -0.8143307 \n```\n\n\n:::\n:::\n\n\n\n\nThe season slope moves from about $-0.824$ to about $-0.814$: hardly at all.\nContrast this with the constructed example, where adjustment destroyed the\nsimple slope. Here, adjusting for the requested amount leaves the season\ntrend essentially intact, so within these data the time story is not a\ndisguised money story.\n\nRead the stability correctly. It is **informative**: the measured requested\namount does not account for the season trend. It is **not proof** that\nomitted-variable bias is absent: an unmeasured variable --- venture maturity,\nfounder experience, editorial selection --- could still play exactly the role\n`size` played in the constructed data. Stability with respect to the\nvariables you have says nothing about the variables you do not have.\n\n### A three-predictor Shark Tank model\n\nAdd a third predictor and fit the model this lecture works with. The outcome\nis initial equity offered, in percentage points. The predictors are:\n\n- `season` --- the season number, 1 to 16;\n- `ask_1k` --- requested amount in thousands of dollars;\n- `description_words` --- the number of words in the source's short\n  description of the business.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequity_model <- lm(\n  equity_offered_pct ~ season + ask_1k + description_words,\n  data = sharks\n)\nsummary(equity_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = equity_offered_pct ~ season + ask_1k + description_words, \n    data = sharks)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-15.295  -4.776  -1.283   3.288  82.106 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       22.0249310  0.8878522  24.807  < 2e-16 ***\nseason            -0.8361515  0.0509825 -16.401  < 2e-16 ***\nask_1k            -0.0028975  0.0005771  -5.021 5.79e-07 ***\ndescription_words -0.1283379  0.1137527  -1.128    0.259    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.619 on 1437 degrees of freedom\nMultiple R-squared:  0.1876,\tAdjusted R-squared:  0.1859 \nF-statistic: 110.6 on 3 and 1437 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThe fitted equation is approximately\n\n$$\n\\widehat{equity}\n=22.025-0.836\\,season-0.0029\\,ask_{1k}\n-0.128\\,description\\_words.\n$$\n\n#### The coefficient-interpretation protocol\n\nUse the same five checks every time you interpret a slope:\n\n1. **Estimate and direction:** state the fitted change and its sign.\n2. **Predictor step and unit:** say what a one-unit increase means.\n3. **Outcome unit:** state the unit in which the outcome changes.\n4. **Conditioning:** name the other included predictors being held fixed.\n5. **Scope:** identify the analysed records and say \"associated with\" unless\n   a research design justifies a causal claim.\n\nThe variables in this model use deliberately different units:\n\n| Term | A one-unit increase means | Coefficient unit |\n|---|---|---|\n| `season` | one later season | equity percentage points per season |\n| `ask_1k` | $1,000 more requested | equity percentage points per $1,000 |\n| `description_words` | one additional word | equity percentage points per word |\n\nApplying the protocol to each slope in turn, always among the 1,441 recorded\npitches:\n\n- **Season.** At the same requested amount and description length, one later\n  season is associated with about $0.836$ percentage points less initial\n  equity offered.\n- **Requested amount.** At the same season and description length, an\n  additional $1,000 requested is associated with about $0.0029$ percentage\n  points less initial equity offered. The number is tiny because the unit\n  step is tiny; per additional $100,000 the association is about $0.29$\n  percentage points, and its t statistic (about $-5.0$) does not depend on\n  the unit chosen.\n- **Description length.** At the same season and request, one additional\n  description word is associated with about $0.128$ percentage points less\n  initial equity offered. This estimate is **not statistically\n  distinguishable from zero** at 5% (p $\\approx$ 0.26). Report the point\n  estimate anyway: \"not significant\" is not the same as \"exactly zero\" ---\n  the data are simply consistent with a range of values that includes zero.\n\n::: {.callout-note collapse=\"true\"}\n## Check: the season slope was −0.814 with two predictors and −0.836 with three. Contradiction?\n\nNo. Each coefficient answers a different conditional question: $-0.814$ holds\nonly `ask_1k` fixed; $-0.836$ holds `ask_1k` *and* `description_words` fixed.\nAdding a predictor changes what is being held fixed, so the coefficient may\nshift. Here the shift is small --- the same stability, and the same limits to\nit, as before.\n:::\n\n### Scaling to comparisons readers care about\n\nNobody plans in single seasons of a TV show or single thousands of dollars.\nScale the coefficient to the step a reader cares about: **fitted change =\ncoefficient × number of unit steps**, holding the other included predictors\nfixed. This resolves the Mentimeter question posed before the break.\n\n::: {#exm-i04-scaling}\n## Worked example: five seasons, half a million dollars, ten words\n\nHolding the other included predictors fixed in `equity_model`:\n\n- **Five later seasons:** $5\\times(-0.836)=-4.18$ fitted equity percentage\n  points.\n- **$500,000 more requested:** $500{,}000/1{,}000 = 500$ units of `ask_1k`,\n  so $500\\times(-0.0029)=-1.45$ fitted percentage points.\n- **Ten additional description words:** $10\\times(-0.128)=-1.28$ fitted\n  percentage points --- with the reminder that this coefficient is not\n  significantly different from zero, so the scaled version is not either.\n\nRescaling a predictor changes the numerical coefficient and its SE by the\nsame factor, but not the fitted values, t statistic, or substantive\nrelationship. A \"per dollar\" coefficient of $-0.0000029$ would be correct and\nunreadable; per $1,000 is readable on the data's scale; per $100,000 is often\nthe best unit for a sentence.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Try it: three seasons later and $200,000 more\n\nIn class this is the pair task. Two pitches are identical in description\nlength; one is three seasons later and requests $200,000 more. Complete the\nsteps before opening the answer.\n\n*Step 1 (given).* Three seasons contribute $3\\times(-0.836)$ fitted\npercentage points.\n\n*Step 2 (you).* Convert $200,000 into `ask_1k` units and multiply by the\n`ask_1k` coefficient.\n\n*Step 3 (you).* Add the two contributions --- the model is additive --- and\nstate the combined fitted difference in one protocol-complete sentence.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$200{,}000/1{,}000=200$ units, so the request contributes\n$200\\times(-0.0029)\\approx-0.58$. Combined:\n$3(-0.836)+200(-0.0029)\\approx-2.51-0.58=-3.09$ percentage points. Sentence:\namong the recorded pitches, a pitch three seasons later that requests\n$200,000 more is fitted to offer about 3.1 percentage points less initial\nequity, holding description length fixed --- an association, not an effect.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb <- coef(equity_model)\n3 * b[\"season\"] + 200 * b[\"ask_1k\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   season \n-3.087963 \n```\n\n\n:::\n:::\n\n\n\n:::\n:::\n\n### What controls can and cannot do\n\nIncluding a control **can**:\n\n- make a comparison more like-for-like on measured dimensions;\n- reduce residual variation, tightening intervals;\n- reveal that a simple association was partly compositional;\n- increase uncertainty when predictors overlap strongly.\n\nIncluding a control **cannot**:\n\n- adjust for unmeasured factors;\n- fix reverse causality;\n- repair selection into the sample;\n- remove measurement error.\n\nA \"control variable\" is just an included predictor. Nothing about the word\n*control* grants it a causal role; only a research design can do that.\n\n::: {.callout-note collapse=\"true\"}\n## Check: which of these four problems does adding `ask_1k` address?\n\n(a) later pitches request different amounts; (b) founder experience is not\nrecorded; (c) equity offers may influence how much is asked; (d) only pitches\nthat reached broadcast are in the file.\n\nOnly (a). It is a measured compositional difference, and holding `ask_1k`\nfixed removes it from the season comparison. Problems (b), (c), and (d) are\nunmeasured confounding, reverse causality, and sample selection --- none of\nthem touched by adding a measured control.\n:::\n\n### Assumptions extend to the full predictor set\n\nFor multiple regression, the Lecture 2 assumption list applies to the whole\nset of included predictors:\n\n1. the conditional mean is linear in the included terms;\n2. $E[\\varepsilon_i\\mid X_{i1},\\ldots,X_{ik}]=0$ --- zero conditional mean at\n   every combination of predictor values;\n3. observations are independent under the design;\n4. no predictor is an exact linear combination of the others;\n5. classical SEs require constant conditional error variance;\n6. exact small-sample t/F inference uses conditional normality.\n\nHigh correlation among predictors --- **collinearity** --- does not bias OLS\nby itself, but it makes individual coefficients unstable and imprecise: the\ndata contain little information to separate overlapping predictors. Exact\nlinear dependence is worse: the coefficients are then **not identified** at\nall, and R drops a term. Instability is a precision problem; exact dependence\nis a no-answer-exists problem.\n\n### A coefficient plot keeps units visible\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nsharks$ask_1k <- sharks$ask_amount_usd / 1000\nequity_model <- lm(\n  equity_offered_pct ~ season + ask_1k + description_words,\n  data = sharks\n)\nci <- confint(equity_model)[-1, , drop = FALSE]\nterm_labels <- c(\"Season\", \"Amount requested ($1,000s)\",\n                 \"Description length (words)\")\ncoef_df <- data.frame(\n  term = factor(term_labels, levels = term_labels),\n  estimate = coef(equity_model)[-1],\n  lower = ci[, 1],\n  upper = ci[, 2]\n)\n\nggplot(coef_df, aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 0, colour = \"#C98B2E\",\n             linetype = \"dashed\", linewidth = 0.8) +\n  geom_pointrange(aes(xmin = lower, xmax = upper),\n                  colour = \"#009E73\", linewidth = 0.7, fatten = 2.6) +\n  annotate(\"text\", x = -0.02, y = 3.35, label = \"no change = 0\",\n           hjust = 1, colour = \"#17324D\", size = 3.4) +\n  labs(x = \"Estimated change in equity offered (percentage points)\",\n       y = NULL) +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.y = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![Coefficient estimates from the three-predictor model with 95% confidence intervals. Each row uses a different predictor unit, so magnitudes are not comparable across rows without the units table.](i04-multiple-regression_files/figure-html/fig-i04-coefplot-1.png){#fig-i04-coefplot width=672}\n:::\n:::\n\n\n\n\nRead @fig-i04-coefplot with the standing five-step sequence:\n\n1. **Axes:** rows are predictors; the horizontal axis is the estimated change\n   in initial equity offered, in percentage points.\n2. **Units:** each row's estimate is *per one unit of that predictor* ---\n   per season, per $1,000, per word. The rows are not on a common scale.\n3. **Marks:** a dot is the coefficient estimate; its horizontal line is the\n   95% confidence interval; the dashed line marks zero.\n4. **Pattern:** season and requested amount sit clearly left of zero; the\n   description-words interval crosses zero. The `ask_1k` row hugs the zero\n   line only because its unit step ($1,000) is tiny --- its t statistic is\n   about $-5$. Visual size on this plot is a unit artefact, not evidence\n   strength.\n5. **Limits:** intervals reflect model-based sampling uncertainty among these\n   recorded pitches; they say nothing about causation or unmeasured\n   variables.\n\n::: {.caveat-box}\n<span class=\"label\">What an adjusted coefficient can and cannot say</span>\n\nEvery slope in `equity_model` is a model-based comparison among the 1,441\nrecorded pitches: fitted conditional means at fixed values of the *included*\npredictors. \"Holding the other included predictors fixed\" never extends to\nvariables outside the model --- maturity, revenue, founder experience, and\neditorial selection are all unheld. The stability of the season slope across\nspecifications is informative about the measured controls only; it proves no\nabsence of omitted-variable bias. Initial equity offered is an on-air opening\nposition, not a completed investment, and none of these associations is a\ncausal effect of time, money, or word count.\n:::\n\n### Answering the driving question\n\nAt the same requested amount (and description length), the season trend\npersists: about $-0.836$ equity percentage points per season, versus $-0.824$\nunadjusted. The money story does not absorb the time story here --- later\npitches offer less equity even compared at the same ask. And neither story is\ncausal: an unmeasured driver could still lie behind both, exactly as firm\nsize did in the constructed example.\n\n**Next:** We can now hold other predictors fixed --- as long as they are\nnumerical. But many of the most interesting business comparisons are\ncategorical: channels, segments, team compositions. Lecture 5 shows how\ncategories enter a regression correctly --- dummy variables and a reference\ngroup chosen deliberately --- and how to judge a whole set of category terms\nat once with the partial F-test, because individually insignificant dummies\ncan still be jointly worth having.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 75 minutes.</span>\n\n### Retrieval (10 minutes)\n\n1. What phrase must appear in a multiple-regression slope interpretation?\n2. Why can a coefficient change after another predictor is added?\n3. What is the zero conditional mean assumption?\n4. Why do controls not automatically identify causality?\n5. What problem can strongly overlapping predictors create?\n6. What five elements belong in a slope interpretation?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. \"Holding the other included predictors fixed.\"\n2. The simpler slope may absorb relationships involving omitted correlated\n   predictors; the added predictor takes back its share.\n3. The error has mean zero at every combination of included predictor values.\n4. Unmeasured confounding, selection, reverse causality, and measurement\n   error can all remain after adjustment.\n5. Unstable, imprecise individual coefficient estimates; exact overlap makes\n   the model unidentified.\n6. Estimate and direction, predictor step and unit, outcome unit, held-fixed\n   predictors, and the sample/causal scope.\n:::\n\n### Practice (30 minutes)\n\nItems 1--5 are unassisted checks of the core skills. **Items 6--9 form the\nfaded-to-unassisted ladder**: item 6 repeats a calculation worked in class,\nitems 7--8 change the numbers, and item 9 is the combined contrast you met\nhalf-finished in the pair task --- now do it start to finish.\n\n1. Interpret all three slopes from `equity_model` with units and\n   conditioning.\n2. Calculate 95% confidence intervals with `confint(equity_model)`.\n3. Test each coefficient against zero and distinguish three individual tests\n   from one joint model test.\n4. Remove `description_words`. Compare the season and request coefficients\n   with the full model's.\n5. Name one plausible omitted variable and explain which model assumption it\n   could threaten.\n6. Interpret a five-season difference using the fitted season coefficient.\n7. Interpret a $500,000 difference in requested amount.\n8. Interpret a ten-word difference in description length and use its 95%\n   interval to assess $H_0:\\beta=0$.\n9. Compare two otherwise identical fitted pitches when one is three seasons\n   later and requests $200,000 more. Calculate the combined fitted\n   difference.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. Holding the other two predictors fixed, among the recorded pitches: one\n   later season is associated with about 0.836 percentage points less\n   initial equity; an additional $1,000 requested with about 0.0029\n   percentage points less (0.29 per $100,000); one additional description\n   word with about 0.128 percentage points less.\n2. The season interval is approximately $(-0.936, -0.736)$, the `ask_1k`\n   interval $(-0.0040, -0.0018)$, and the description interval\n   $(-0.351, 0.095)$.\n3. Individual t-tests evaluate one $\\beta_j=0$ at a time; the overall F-test\n   (F $\\approx$ 110.6 on 3 and 1437 df) evaluates all slope coefficients\n   jointly.\n4. Without `description_words`, the season coefficient is about $-0.814$ and\n   the `ask_1k` coefficient about $-0.0029$. They change only slightly here;\n   that empirical stability does not prove absence of omitted-variable bias.\n5. Examples include venture maturity, revenue, founder experience, or editing\n   decisions; if related to both an included predictor and offered equity,\n   the omitted variable violates zero conditional mean.\n6. Holding request and description length fixed, a pitch five seasons later\n   is fitted to offer about $5(-0.836)=-4.18$ equity percentage points less.\n7. $500,000 equals 500 `ask_1k` units. Holding season and description length\n   fixed, the fitted difference is $500\\times(-0.0029)\\approx-1.45$\n   percentage points.\n8. Ten words correspond to about $-1.28$ fitted percentage points, holding\n   season and request fixed. Multiplying the interval by 10 gives\n   approximately $(-3.51, 0.95)$; because zero remains plausible, the\n   two-sided 5% test does not reject a zero coefficient.\n9. The fitted difference is $3(-0.836)+200(-0.0029)\\approx-3.09$ percentage\n   points, holding description length fixed. Coefficient contributions add\n   because the model is additive.\n:::\n\n### Cumulative mini-task (10 minutes)\n\nWrite **one paragraph** connecting the Lecture 2 diagnostics to\n`equity_model`: which residual checks would you run on this three-predictor\nfit, what would each look for, and what would you do about a highly\ninfluential pitch if you found one?\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nA residuals-versus-fitted plot checks that the conditional mean is roughly\nlinear in the included terms and that spread is roughly constant; curvature\nwould question assumption 1, a funnel shape would question the classical SEs.\nStandardised residuals (`rstandard`) flag pitches the model fits unusually\nbadly, and Cook's distance flags pitches that individually move the\ncoefficients. A flagged pitch --- say, an extreme requested amount --- gets\ninvestigated, not deleted: check the recorded values, refit with and without\nit, and report both fits if they disagree. Silent deletion is never an\noption.\n:::\n\n### Spaced review: one item from Lecture 3 (5 minutes)\n\nFor the simple model `equity_offered_pct ~ season`, the slope's t statistic\nis about $-17.34$. What is the overall F statistic of this one-predictor\nmodel, and why?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$F = t^2 \\approx 300.7$. With a single slope, the overall F-test and the\ntwo-sided t-test of that slope test the same hypothesis, and F is exactly the\nsquare of t. With several predictors that equivalence disappears --- which is\nwhy Lecture 5 needs a genuine joint test.\n:::\n\n### Worked exam interpretation (5 minutes)\n\n**Question.** A summary table reports, for the three-predictor model,\n`season  -0.836  (SE 0.051)` and `description_words  -0.128  (SE 0.114)`. A\nstudent writes: \"Season matters and word count does not, so descriptions have\nno effect on equity.\" Give two corrections in the mock-exam Q4 style.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nFirst, \"no effect\" misreads non-significance: the interval\n$(-0.351, 0.095)$ contains zero *and* values near $-0.35$, so the data are\nconsistent with no association and with a modest negative one --- not\nsignificant is not zero. Second, \"effect\" claims causation; both estimates\nare associations among recorded pitches, holding the other included\npredictors fixed, with no design that identifies a causal effect.\n:::\n\n### From the reading ladder (10 minutes)\n\nNext rung of the [reading ladder](../resources/reading-ladder.qmd): open\n[Zhao, Seibert & Hills (2005)](https://doi.org/10.1037/0021-9010.90.6.1265)\nvia the university library and find the table predicting **entrepreneurial\nintentions**. Identify the outcome, the predictors of substantive interest,\nand the variables included as controls. Pick one coefficient and write the\nfull protocol sentence --- including \"holding the other included predictors\nfixed\" and the sample scope. Then name one variable *not* in the model that\ncould drive both the predictor and the outcome, exactly like the\nconstructed demonstration from today's lecture.\n\n::: {.callout-note collapse=\"true\"}\n## Check your approach\n\nAny defensible answer names the model-based nature of the comparison (no\nclaim that identical students exist), keeps the units or scale of the\npredictor visible, and proposes an omitted variable with a plausible path to\nboth sides --- family business background, access to capital, and general\nself-confidence are all fair candidates. If your sentence could be read as\ncausal advice (\"increase X to raise intentions\"), tighten it.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA3 venture --- or any business you know well. Name one\noutcome you care about and two of its drivers that are correlated with each\nother (say, price and quality tier, or marketing spend and firm age), and\nwrite two sentences: which comparison would a regression of the outcome on\nonly one driver mix together, and what would \"holding the other fixed\" let\nyou see? There is no wrong answer; the point is spotting the confound in a\nbusiness you actually know.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"Outcome: weekly orders; drivers: price and quality tier, which move together because premium boxes cost more. Orders-on-price alone would mix cheaper with lower-tier; holding tier fixed shows what a price cut does within a tier --- the number I actually control.\"\n:::\n\nYou can discuss this task --- and any other task in this chapter --- with\n**Tilly**, the course AI assistant on Canvas: ask it to propose an omitted\nvariable for your venture's regression and challenge you to say whether a\nmeasured control could fix it.\n::::\n\nContinue to Lecture 5: Categories as predictors and joint tests.\n\nFormula sheet: Lecture 4 formulas.\n\nFor a more formal treatment, see James et al., *An Introduction to\nStatistical Learning*, 2nd ed., Sections 3.2 and 3.3.3, and\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapter 20.\n\n:::\n",
    "supporting": [
      "i04-multiple-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}