{
  "hash": "e43a213d446658e84a505e403a5f5fd2",
  "result": {
    "engine": "knitr",
    "markdown": "# Tutorial 3: Normal models, sampling, and confidence intervals {#b-ep03}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Tutorial 3, you can</span>\n\n- calculate a probability as an area under a uniform density\n- use a normal model in both directions: from a value to a probability, and\n  from a probability to a value\n- identify a valid population and sampling frame\n- distinguish parameters, estimators, and estimates\n- calculate the standard deviation of a sample mean or a sample proportion\n  when $\\sigma$ or $p$ is given, and the standard error when $s$ or\n  $\\hat p$ is used\n- calculate and interpret quartiles and the IQR of an observed sample\n- calculate a probability for a sample mean, in the exact normal case and\n  with the CLT, without confusing observations and statistics\n- construct a confidence interval for a mean and for a proportion in five\n  parts, and read it against a claimed value\n- calculate the sample size for a target margin of error\n- qualify conclusions when the sampling design is limited.\n:::\n\nTutorials are **exam preparation sessions**. Every task below follows the\nformat of the final exam. You first try each task in pairs. You may use AI for this, with\nthe four steps Attempt, Ask, Verify, Explain. Then the class discusses the\nsolution together.\n\nThis tutorial covers Lectures 6--9: densities and the normal model, samples\nand estimators, the sampling distribution of a mean and of a proportion, and\nconfidence intervals. Hypothesis tests follow in Lecture 10 and in\nTutorial 4.\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 15 minutes.</span>\n\nBring your after-class work from Lectures 6--9. If you find the algebra\ndifficult, review [Mathematics Refresher: sums, fractions, and\nroots](../resources/math-refresher.html).\n\nUse the formula sheet with all formulas up to and including Lecture 9.\n\nComplete from memory:\n\n1. Standardising an observation $x$ from $N(\\mu,\\sigma^2)$ means\n   calculating ...\n2. A parameter describes ...\n3. An estimator is ...\n4. The standard deviation of the sample mean $\\bar X$ is ... The standard\n   error of the sample mean is ...\n5. The CLT describes ...\n6. A written answer for a confidence interval has five parts, in this\n   order: ...\n7. The confidence interval for a mean with $s$ has the formula ... It may\n   be used when ...\n8. The confidence interval for a proportion has the formula ... It may be\n   used when ...\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\n1. $z=(x-\\mu)/\\sigma$: the number of population SDs between $x$ and the\n   mean.\n2. A parameter describes a population.\n3. An estimator is a rule that estimates a parameter from a sample. Its\n   value is random, because the sample is random.\n4. The standard deviation of the sample mean is\n   $\\operatorname{SD}(\\bar X)=\\sigma/\\sqrt n$. The standard error is\n   $\\operatorname{SE}(\\bar X)=S/\\sqrt n$, with the value $s/\\sqrt n$. It is\n   the estimated standard deviation of $\\bar X$, used when $\\sigma$ is\n   unknown.\n5. The distribution of the sample mean across random samples. It is\n   approximately normal for a large random sample, also when the population\n   is not normal.\n6. Formula, with the reason why it may be used. Given values. Calculations:\n   the standard error, then the margin of error. Interval, with the unit.\n   Conclusion in the words of the question.\n7. $\\bar X\\pm t_{1-\\alpha/2,\\,n-1}\\,S/\\sqrt n$. The population is normal, or\n   $n$ is large.\n8. $\\widehat P\\pm z_{1-\\alpha/2}\\sqrt{\\widehat P(1-\\widehat P)/n}$. The\n   condition is $n\\hat p\\ge10$ and $n(1-\\hat p)\\ge10$.\n:::\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In the tutorial\n\nAttempt each task before you open its answer. A complete written answer\nnames the quantity and shows the calculation. It reports the value with its\nunit and interprets this value in context. It also states one important\nlimit of the model or the data.\n\nEvery task shows a time in minutes for your attempt and the discussion.\nTasks 1 to 9 take about 83 minutes together. Tasks 10 to 12 are extra\npractice for home.\n\nIn the exam, an interval for a mean always uses $s$ and a t value. If a t\nvalue or a z value is not on the formula sheet, the task gives it as a\nsupplied value.\n\n### Task 1: A normal model in both directions (10 minutes)\n\nAn invented example. A founder runs an escape room. The time that a team\nneeds to solve the room, $Y$, is modelled as $Y\\sim N(45,5^2)$, in minutes.\nThe standard deviation is 5 minutes.\n\nSupplied values: $P(Z\\le0.8)=0.7881$, $P(Z\\le1.2)=0.8849$, and the 0.95\nquantile $z_{0.95}=1.645$.\n\n1. Calculate the probability that a team needs at most 49 minutes.\n2. Calculate the probability that a team needs between 39 and 49 minutes.\n3. The founder wants a time limit that 5% of the teams exceed. Calculate\n   this limit.\n4. Say in one sentence what the supplied quantile 1.645 means for a\n   standard normal variable $Z$.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n1. Standardise: $z=(49-45)/5=0.8$. So\n   $P(Y\\le49)=P(Z\\le0.8)=0.7881$. About 79% of the teams need at most 49\n   minutes.\n2. The two z values are $(39-45)/5=-1.2$ and $0.8$. The supplied values\n   contain only positive z values, so use the symmetry rule and then the\n   complement rule: $P(Z\\le-1.2)=P(Z>1.2)=1-0.8849=0.1151$. Then\n\n   $$\n   P(39\\le Y\\le49)=P(Z\\le0.8)-P(Z\\le-1.2)=0.7881-0.1151=0.6730.\n   $$\n\n   About 67% of the teams need between 39 and 49 minutes.\n3. If 5% of the teams exceed the limit, 95% are at or below it. The limit\n   is the 0.95 quantile of $Y$:\n   $y=\\mu+z\\sigma=45+1.645\\times5=53.23$ minutes. A limit of about 53\n   minutes fits.\n4. 95% of the values of $Z$ are at or below 1.645, and 5% are above it.\n\nParts 1 and 2 go from a value to a probability. Part 3 goes from a\nprobability to a value. One limit: the normal curve is a model. The answers\nare only as good as the fit of this model to the recorded times.\n\nVerification in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(p_at_most_49 = pnorm(49, mean = 45, sd = 5),\n  p_39_to_49 = pnorm(49, mean = 45, sd = 5) - pnorm(39, mean = 45, sd = 5),\n  by_hand = 0.7881 - (1 - 0.8849),\n  limit = qnorm(0.95, mean = 45, sd = 5),\n  limit_by_hand = 45 + 1.645 * 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n p_at_most_49    p_39_to_49       by_hand         limit limit_by_hand \n    0.7881446     0.6730749     0.6730000    53.2242681    53.2250000 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Task 2: Population, frame, and claim (5 minutes)\n\nA student randomly selects 100 rows from the Shark Tank file and estimates\nthe mean equity offered (`equity_offered_pct`).\n\n1. State the population about which this sample allows direct\n   conclusions.\n2. Explain why this sample does not represent all *Shark Tank* applicants.\n3. Explain why this sample does not represent all US entrepreneurs.\n4. State one change needed to target all US entrepreneurs.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe direct finite population is the 1,441 recorded pitches in completed\nSeasons 1--16. Applicants who did not appear on television are not in the\nfile, so the frame does not represent all applicants. The show also selects a specialised\ngroup of entrepreneurs, not a probability sample of US entrepreneurs.\nTo target all US entrepreneurs, you would need a suitable national\nsampling frame and a random selection from that frame.\n:::\n\n### Task 3: Reproduce the realised sample (8 minutes)\n\n[Shark Tank data]{.shark-tag} The code below draws the sample with seed 123, exactly as in Lecture 7.\nSo you get the same 100 rows when you run it:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nset.seed(123)\nsample_rows <- sample(seq_len(nrow(sharks)), size = 100, replace = FALSE)\npitch_sample <- sharks[sample_rows, ]\n\nc(\n  n = nrow(pitch_sample),\n  mean_equity = mean(pitch_sample$equity_offered_pct),\n  sd_equity = sd(pitch_sample$equity_offered_pct),\n  q1_equity = unname(quantile(pitch_sample$equity_offered_pct, 0.25)),\n  median_equity = median(pitch_sample$equity_offered_pct),\n  q3_equity = unname(quantile(pitch_sample$equity_offered_pct, 0.75)),\n  deal_proportion = mean(pitch_sample$deal_on_show)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              n     mean_equity       sd_equity       q1_equity   median_equity \n     100.000000       12.760000        7.707887        8.000000       10.000000 \n      q3_equity deal_proportion \n      17.750000        0.640000 \n```\n\n\n:::\n:::\n\n\n\n\nA note on the quartiles in this output. When a quartile falls between two\nordered values, R's `quantile()` reports a point between them. Here the\n75th ordered value is 17 and the 76th is 20, and R reports 17.75. The rule\nof Lecture 1 takes the 75th of the 100 ordered values, which is 17.\n\n1. Identify the parameter, estimator, and estimate for the mean equity\n   offered (`equity_offered_pct`).\n2. Identify the parameter, estimator, and estimate for the deal proportion\n   (`deal_on_show`).\n3. Calculate the interquartile range (IQR) of the equity offered in the\n   sample from the R output and interpret it. The IQR is defined in\n   [Lecture 1](b01-introduction-data-analysis.qmd#b01-quartiles).\n4. Explain why a different seed can produce different estimates and a\n   different IQR.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nFor the equity offered, the parameter is the population mean $\\mu$, the\nestimator is $\\bar X$, and the estimate is $\\bar x=12.76$%. For the deal\noutcome, the parameter is the population proportion $p$, the estimator is\n$\\widehat P$, and the estimate is $\\hat p=0.64$. The sample quartiles in the\nR output are $Q_1=8$ and $Q_3=17.75$, so\n$\\operatorname{IQR}=17.75-8=9.75$ percentage points: the middle half of the\ninitial equity offers in the sample lies between 8% and 17.75%. With the rule of\nLecture 1, $Q_3=17$ and the IQR is $17-8=9$ percentage points. Both answers\nare correct when you name the rule that you used. A different seed selects\na different random set of rows. So all sample statistics, including the\nIQR, can change.\n\nThe ordered values behind the two rules:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(pitch_sample$equity_offered_pct)[c(25, 26, 75, 76)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  8  8 17 20\n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Task 4: Standard errors and a larger sample (8 minutes)\n\n[Shark Tank data]{.shark-tag} Use the sample output of Task 3.\n\n1. Calculate the standard error of the sample mean of the equity offered,\n   $\\operatorname{SE}(\\bar X)$.\n2. Calculate the standard error of the sample proportion of deals,\n   $\\operatorname{SE}(\\widehat P)$ (Lecture 8).\n3. Check the success-failure condition for $\\widehat P$.\n4. Predict how each standard error changes if $n$ increases from 100 to 400\n   and the spread in the sample stays similar.\n5. In part 1, R calculates the sample SD with `sd()`. This function divides\n   by $n-1$. State the value of $n-1$ here, and explain in one sentence why\n   `sd()` divides by it.\n6. Explain why the results of parts 1 and 2 are standard errors and not the\n   standard deviations of $\\bar X$ and $\\widehat P$.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$$\n\\operatorname{SE}(\\bar X)=\\frac{s}{\\sqrt n}=\\frac{7.7079}{\\sqrt{100}}=0.7708.\n$$\n\n$$\n\\operatorname{SE}(\\widehat P)\n=\\sqrt{\\frac{\\hat p(1-\\hat p)}{n}}\n=\\sqrt{\\frac{0.64(0.36)}{100}}=0.0480.\n$$\n\nThe standard error of the mean is about 0.77 percentage points of equity.\nThe standard error of the proportion is about 4.8 percentage points of the\ndeal rate. The sample contains 64 successes (deals) and 36 failures (no\ndeal). Both counts are at least 10, so the success-failure condition holds.\nIf $n$ becomes four times as large, both standard errors are divided by\n$\\sqrt 4=2$. The divisor is $n-1=99$. The deviations are measured from the\nsample mean, so they must sum to zero. As a result, only 99 of them can\nvary freely. Dividing by 99 removes the downward bias that this causes\n(Lecture 7).\n\nThe standard deviations of the two estimators are $\\sigma/\\sqrt n$ and\n$\\sqrt{p(1-p)/n}$. They contain the population values $\\sigma$ and $p$,\nwhich a sample does not give. The standard errors use $s$ and $\\hat p$ from\nthe sample in their place. A standard error is an estimated standard\ndeviation of an estimator.\n\nVerification in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns_equity <- sd(pitch_sample$equity_offered_pct)\np_hat <- mean(pitch_sample$deal_on_show)\nc(se_mean = s_equity / sqrt(100),\n  se_proportion = sqrt(p_hat * (1 - p_hat) / 100),\n  deals = sum(pitch_sample$deal_on_show),\n  no_deals = 100 - sum(pitch_sample$deal_on_show),\n  se_mean_n400 = s_equity / sqrt(400),\n  se_proportion_n400 = sqrt(p_hat * (1 - p_hat) / 400))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           se_mean      se_proportion              deals           no_deals \n         0.7707887          0.0480000         64.0000000         36.0000000 \n      se_mean_n400 se_proportion_n400 \n         0.3853943          0.0240000 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Task 5: One pitch versus one mean (10 minutes)\n\n[Shark Tank data]{.shark-tag} Suppose the population mean of the equity offered is $\\mu=13.21$%, the\npopulation SD is $\\sigma=8.44$ percentage points. You draw independent\nrandom samples of $n=100$ pitches. Supplied values: $P(Z\\le 2.12)=0.983$ and\n$P(Z\\le 0.21)=0.583$.\n\n1. State the approximate sampling distribution of $\\bar X$, with the\n   standard deviation of the sample mean.\n2. Calculate $P(\\bar X>15)$.\n3. A classmate models a single pitch as $X\\sim N(13.21, 8.44^2)$ and\n   calculates $P(X>15)$. Compute that value too, and explain why the two\n   answers are so different.\n4. The equity offered is strongly right-skewed (Lecture 1). So which of the\n   two calculations uses a bad model? And why does the CLT still justify\n   the calculation in part 2?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe CLT gives approximately\n$\\bar X\\mathrel{\\dot\\sim}N(13.21,\\,8.44^2/100)$. The standard deviation of\nthe sample mean is $\\operatorname{SD}(\\bar X)=8.44/\\sqrt{100}=0.844$\npercentage points. Therefore\n\n$$\nP(\\bar X>15)\n=1-P\\!\\left(Z\\le\\frac{15-13.21}{0.844}\\right)\n=1-P(Z\\le2.12)\n\\approx0.017.\n$$\n\nFor a single pitch, $z=(15-13.21)/8.44\\approx0.21$, so\n$P(X>15)\\approx1-0.583\\approx0.42$. The mean of 100 pitches varies ten\ntimes less than one pitch ($\\sigma/\\sqrt{100}$), so 15 is an ordinary value\nfor one pitch but an extreme value for a mean of 100. A normal curve is\nsymmetric and the equity offered is strongly right-skewed. So the normal\nmodel for a single pitch in part 3 is a bad model. The CLT concerns the\nsample mean. The mean of 100 independent draws has a nearly normal\nsampling distribution, even when the population is skewed. This is why\nthe calculation in part 2 is justified.\n\nVerification in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd_mean <- 8.44 / sqrt(100)\nc(sd_of_mean = sd_mean,\n  z_mean = (15 - 13.21) / sd_mean,\n  p_mean_above_15 = 1 - pnorm(15, mean = 13.21, sd = sd_mean),\n  z_single = (15 - 13.21) / 8.44,\n  p_single_above_15 = 1 - pnorm(15, mean = 13.21, sd = 8.44))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       sd_of_mean            z_mean   p_mean_above_15          z_single \n       0.84400000        2.12085308        0.01696708        0.21208531 \np_single_above_15 \n       0.41602024 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Task 6: The exact normal case and the CLT (10 minutes)\n\nAn invented example. A founder makes scented candles. The burn time of one\ncandle, $X$, is modelled as $X\\sim N(40,6^2)$, in hours. A tester burns a\nrandom sample of $n=9$ candles and records the sample mean $\\bar X$.\nSupplied values for the whole task:\n\n```text\nP(Z <= 0.6) = 0.7257\nP(Z <= 1.8) = 0.9641\nP(Z <= 2.5) = 0.9938\n```\n\n1. State the distribution of $\\bar X$ for $n=9$, with its mean and its\n   standard deviation. Explain why you may use this distribution although\n   the sample is small.\n2. Calculate the probability that one candle burns less than 36.4 hours.\n3. Calculate the probability that the mean burn time of the 9 candles is\n   below 36.4 hours.\n4. Explain in one sentence why the answers to parts 2 and 3 differ.\n\nThe founder also looks at the orders in her web shop. The value of one\norder is strongly right-skewed: most orders are small and a few are very\nlarge. The mean is $\\mu=45$ euros and the standard deviation is\n$\\sigma=30$ euros.\n\n5. For a random sample of $n=100$ orders, calculate the probability that\n   the sample mean is above 52.50 euros. Name the result (the theorem)\n   that allows this calculation.\n6. Explain why you cannot do the same calculation for a random sample of 9\n   orders.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n1. The population is normal. Then the sample mean is exactly normal for\n   every sample size, also for a small one (Lecture 8):\n   $\\bar X\\sim N(40,\\,6^2/9)$. Its mean is 40 hours and its standard\n   deviation is $\\operatorname{SD}(\\bar X)=6/\\sqrt9=2$ hours.\n2. One candle: $z=(36.4-40)/6=-0.6$. With the symmetry rule and the\n   complement rule, $P(X<36.4)=P(Z\\le-0.6)=1-0.7257=0.2743$.\n3. The mean of 9 candles: $z=(36.4-40)/2=-1.8$. So\n   $P(\\bar X<36.4)=P(Z\\le-1.8)=1-0.9641=0.0359$.\n4. The mean of 9 candles varies three times less than one candle, so 36.4\n   hours is an ordinary value for one candle (about 27%) and an unusual\n   value for the mean of 9 candles (about 4%).\n5. The population is not normal, but $n=100$ is large. The CLT gives\n   approximately $\\bar X\\mathrel{\\dot\\sim}N(45,\\,30^2/100)$, with\n   $\\operatorname{SD}(\\bar X)=30/\\sqrt{100}=3$ euros. Then\n   $z=(52.50-45)/3=2.5$ and $P(\\bar X>52.50)\\approx1-0.9938=0.0062$.\n6. The order values are not normal, so the exact normal case does not hold.\n   A sample of 9 is too small for the CLT. No result of Lecture 8 gives the\n   distribution of $\\bar X$ in this case.\n\nVerification in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(sd_mean_9 = 6 / sqrt(9),\n  p_one_below_36.4 = pnorm(36.4, mean = 40, sd = 6),\n  p_mean_below_36.4 = pnorm(36.4, mean = 40, sd = 6 / sqrt(9)),\n  sd_mean_100 = 30 / sqrt(100),\n  p_mean_above_52.50 = 1 - pnorm(52.50, mean = 45, sd = 30 / sqrt(100)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         sd_mean_9   p_one_below_36.4  p_mean_below_36.4        sd_mean_100 \n       2.000000000        0.274253118        0.035930319        3.000000000 \np_mean_above_52.50 \n       0.006209665 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Task 7: A proportion through the CLT (7 minutes)\n\n[Shark Tank data]{.shark-tag} The deal proportion (`deal_on_show`) in the Shark Tank file is $p=0.612$. A\nrandom sample of $n=100$ pitches is planned, with sample deal proportion\n$\\widehat P$. Supplied value: $P(Z\\le -2.30)=0.011$.\n\n1. Calculate the standard deviation of the sample proportion,\n   $\\operatorname{SD}(\\widehat P)$, and check the success-failure\n   condition.\n2. State the approximate sampling distribution of $\\widehat P$.\n3. Approximate the probability that the sample shows a deal rate of at\n   most 50%, that is, $P(\\widehat P\\le0.50)$.\n4. Interpret the result in one sentence.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nHere $p$ is given, so the result is a standard deviation and not a standard\nerror: $\\operatorname{SD}(\\widehat P)=\\sqrt{0.612(0.388)/100}\\approx0.0487$.\nThe expected counts are $np=61.2$ and $n(1-p)=38.8$, both at least 10.\nSo $\\widehat P\\mathrel{\\dot\\sim}N(0.612,\\,0.0487^2)$. Standardise:\n\n$$\nz=\\frac{0.50-0.612}{0.0487}\\approx-2.30,\n\\qquad\nP(\\widehat P\\le0.50)\\approx P(Z\\le-2.30)\\approx0.011.\n$$\n\nIf the deal proportion in the file is 61.2%, only about 1% of random\nsamples of 100 pitches would show a deal rate at or below 50%. Such a sample would be\nsurprising. Lecture 10 builds the hypothesis test on this idea.\n\nVerification in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd_phat <- sqrt(0.612 * 0.388 / 100)\nc(sd_of_phat = sd_phat,\n  expected_deals = 100 * 0.612,\n  expected_no_deals = 100 * 0.388,\n  z = (0.50 - 0.612) / sd_phat,\n  p_at_most_050 = pnorm(0.50, mean = 0.612, sd = sd_phat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       sd_of_phat    expected_deals expected_no_deals                 z \n       0.04872946       61.20000000       38.80000000       -2.29840442 \n    p_at_most_050 \n       0.01076939 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Task 8: A confidence interval for a mean (15 minutes)\n\nAn invented example. A founder runs a bouldering gym. Her business plan\nassumes that a visit lasts 120 minutes on average. She draws a random sample\nof 16 visits from the 5,000 visits of last year in the check-in system. The\nsample has a mean of 136 minutes and a standard deviation of $s=28$\nminutes. The visit times are roughly normally distributed. Supplied values:\n$t_{0.95,\\,15}=1.753$, $t_{0.975,\\,15}=2.131$, and $t_{0.995,\\,15}=2.947$.\nThe formula sheet does not list $df=15$, so the task gives these values\nhere.\n\n1. Construct a 95% confidence interval for the mean visit time of last\n   year. Write the five parts of the exam procedure for a mean (Lecture 9).\n   In part 5, say what the interval tells you about the 120 minutes in the\n   business plan.\n2. Construct the 99% confidence interval. Only parts 2 to 5 change.\n3. Construct the 90% confidence interval. Again only parts 2 to 5 change.\n4. Compare the three conclusions about the 120 minutes, and explain how the\n   width of the interval changes with the confidence level.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe 95% interval in five parts:\n\n1. **Formula.** $\\bar X\\pm t_{1-\\alpha/2,\\,n-1}\\,S/\\sqrt n$. It may be used\n   because the visit times are roughly normal. The sample is small, so a\n   large $n$ is not the reason here.\n2. **Given values.** $\\bar x=136$ minutes, $s=28$ minutes, $n=16$,\n   $df=15$. The confidence level is 95%, so $\\alpha=0.05$ and the critical\n   value is $t_{0.975,\\,15}=2.131$.\n3. **Calculations.** The standard error is $s/\\sqrt n=28/\\sqrt{16}=7$\n   minutes. The margin of error is $2.131\\times7=14.92$ minutes.\n4. **Interval.** $(136-14.92,\\ 136+14.92)=(121.08,\\ 150.92)$ minutes.\n5. **Conclusion.** The value 120 minutes lies outside the interval. At the\n   5% level we can conclude that the mean visit time of last year differs\n   from 120 minutes. The whole interval lies above 120, so visits last\n   longer than the plan assumes. The lower end is 121.08 minutes, only\n   about 1% above 120. So the difference may be small.\n\nThe 99% interval, parts 2 to 5:\n\n2. **Given values.** As before, but the confidence level is 99%, so\n   $\\alpha=0.01$ and the critical value is $t_{0.995,\\,15}=2.947$.\n3. **Calculations.** The standard error stays 7 minutes. The margin of\n   error is $2.947\\times7=20.63$ minutes.\n4. **Interval.** $(136-20.63,\\ 136+20.63)=(115.37,\\ 156.63)$ minutes.\n5. **Conclusion.** The value 120 minutes lies inside the interval. At the\n   1% level we cannot conclude that the mean visit time differs from 120\n   minutes.\n\nThe 90% interval, parts 2 to 5:\n\n2. **Given values.** As before, but the confidence level is 90%, so\n   $\\alpha=0.10$ and the critical value is $t_{0.95,\\,15}=1.753$.\n3. **Calculations.** The standard error stays 7 minutes. The margin of\n   error is $1.753\\times7=12.27$ minutes.\n4. **Interval.** $(136-12.27,\\ 136+12.27)=(123.73,\\ 148.27)$ minutes.\n5. **Conclusion.** The value 120 minutes lies outside the interval. At the\n   10% level we can conclude that the mean visit time differs from 120\n   minutes, and the whole interval lies above 120.\n\nA higher confidence level needs a larger critical value, so the margin of\nerror grows from 12.27 minutes at 90% to 14.92 minutes at 95% and 20.63\nminutes at 99%. The 99% interval is about 1.7 times as wide as the 90%\ninterval. With the same sample, we can conclude that the mean differs from\n120 minutes at the 10% and the 5% level, but not at the stricter 1% level.\nFor this reason every conclusion names its level. One limit: the interval describes\nthe visits of last year, not the visits of next year.\n\nVerification in R, with the supplied t values:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nse_visit <- 28 / sqrt(16)\nc(se = se_visit,\n  margin_95 = 2.131 * se_visit,\n  lower_95 = 136 - 2.131 * se_visit, upper_95 = 136 + 2.131 * se_visit,\n  margin_99 = 2.947 * se_visit,\n  lower_99 = 136 - 2.947 * se_visit, upper_99 = 136 + 2.947 * se_visit,\n  margin_90 = 1.753 * se_visit,\n  lower_90 = 136 - 1.753 * se_visit, upper_90 = 136 + 1.753 * se_visit,\n  width_99_over_90 = 2.947 / 1.753)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              se        margin_95         lower_95         upper_95 \n        7.000000        14.917000       121.083000       150.917000 \n       margin_99         lower_99         upper_99        margin_90 \n       20.629000       115.371000       156.629000        12.271000 \n        lower_90         upper_90 width_99_over_90 \n      123.729000       148.271000         1.681118 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(t_95 = qt(0.95, df = 15), t_975 = qt(0.975, df = 15),\n  t_995 = qt(0.995, df = 15),\n  low_end_above_120_in_percent = 100 * (121.08 - 120) / 120)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        t_95                        t_975 \n                    1.753050                     2.131450 \n                       t_995 low_end_above_120_in_percent \n                    2.946713                     0.900000 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Task 9: A confidence interval for a proportion (10 minutes)\n\nAn invented example. A founder sells sneakers online. Her parcel service\nreports that customers return 15% of all sneaker orders. Last year her shop\nhad 6,000 orders. She draws a random sample of 400 of these orders.\nCustomers returned 40 of these 400 orders. Let\n$p$ be the proportion of returned orders among all 6,000 orders.\n\n1. Construct a 95% confidence interval for $p$. Write the five parts of the\n   exam procedure for a proportion (Lecture 9), with the check of the\n   condition. Check the 10% condition first. In part 5, say what the\n   interval tells you about the 15% reported by the parcel service.\n2. The founder says: \"My return rate is 10%, so I am 5 percentage points\n   below the 15%.\" Assess this sentence.\n3. State the formula of the standard deviation of $\\widehat P$ and explain\n   why you cannot calculate it here.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe sample contains 400 of the 6,000 orders, that is 6.7%. This is at most\n10%, so we may treat the sample as iid.\n\nThe interval of part 1 in five parts:\n\n1. **Formula.**\n   $\\widehat P\\pm z_{1-\\alpha/2}\\sqrt{\\widehat P(1-\\widehat P)/n}$. The\n   condition holds: $n\\hat p=40$ and $n(1-\\hat p)=360$ are both at least\n   10.\n2. **Given values.** 40 returned orders, $n=400$, $\\hat p=40/400=0.10$. The\n   confidence level is 95%, so $z_{0.975}=1.960$.\n3. **Calculations.** The standard error is\n   $\\sqrt{0.10\\times0.90/400}=\\sqrt{0.000225}=0.015$. The margin of error\n   is $1.960\\times0.015=0.0294$.\n4. **Interval.** $(0.10-0.0294,\\ 0.10+0.0294)=(0.071,\\ 0.129)$, that is,\n   from 7.1% to 12.9% of the orders.\n5. **Conclusion.** The value 0.15 lies outside the interval. At the 5%\n   level we can conclude that her proportion of returned orders differs\n   from 15%. The whole interval lies below 0.15.\n\nPart 2. The sentence treats the estimate as the exact rate. The 10% is the\nestimate from 400 orders. The plausible values run from 7.1% to 12.9%. So\nher return rate is between 2.1 and 7.9 percentage points below the 15%.\n\nPart 3. The standard deviation of the sample proportion is\n$\\operatorname{SD}(\\widehat P)=\\sqrt{p(1-p)/n}$. It contains the unknown\n$p$, which is the number that the interval tries to estimate. The standard error\nuses $\\hat p$ in its place.\n\nVerification in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_hat_returns <- 40 / 400\nse_returns <- sqrt(p_hat_returns * (1 - p_hat_returns) / 400)\nc(p_hat = p_hat_returns,\n  successes = 400 * p_hat_returns, failures = 400 * (1 - p_hat_returns),\n  se = se_returns, margin = 1.960 * se_returns,\n  lower = p_hat_returns - 1.960 * se_returns,\n  upper = p_hat_returns + 1.960 * se_returns,\n  sample_share_of_orders = 400 / 6000,\n  below_15_at_most = 0.15 - (p_hat_returns - 1.960 * se_returns),\n  below_15_at_least = 0.15 - (p_hat_returns + 1.960 * se_returns))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 p_hat              successes               failures \n            0.10000000            40.00000000           360.00000000 \n                    se                 margin                  lower \n            0.01500000             0.02940000             0.07060000 \n                 upper sample_share_of_orders       below_15_at_most \n            0.12940000             0.06666667             0.07940000 \n     below_15_at_least \n            0.02060000 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Task 10: A uniform model (8 minutes, extra practice for home)\n\nAn invented example. A founder runs a studio that prints T-shirts for\nstudent associations. The time to print one order, $X$, is equally likely\nto be anywhere between 20 and 60 minutes: $X\\sim U(20,60)$.\n\n1. A colleague sketches the density as a flat line at height 0.02 between\n   20 and 60 minutes, and zero elsewhere. Show that this is not a valid\n   density, and give the correct height.\n2. Calculate $P(30\\le X\\le45)$.\n3. Calculate $P(X>50)$.\n4. Calculate $P(10\\le X\\le30)$. Note that a part of this interval lies\n   outside the possible values of $X$.\n5. State $P(X=40)$. Then explain why the height of the density is not a\n   probability.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n1. A valid density is never negative and has a total area of 1. The sketch\n   is never negative, but its area is $(60-20)\\times0.02=0.8$, not 1. The\n   correct height is $1/(60-20)=0.025$ per minute. Then the area is\n   $40\\times0.025=1$.\n2. A probability is an area: width times height. So\n   $P(30\\le X\\le45)=(45-30)\\times0.025=0.375$.\n3. $P(X>50)=(60-50)\\times0.025=0.25$.\n4. The density is zero below 20 minutes, so only the part from 20 to 30\n   counts: $P(10\\le X\\le30)=(30-20)\\times0.025=0.25$. A calculation with\n   the full width of 20 minutes gives 0.5, which is wrong.\n5. $P(X=40)=0$. A single value has width zero, so the area above it is\n   zero. The height 0.025 is a probability per minute. It becomes a\n   probability only when you multiply it by a width in minutes.\n\nVerification in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(area_of_sketch = (60 - 20) * 0.02,\n  correct_height = 1 / (60 - 20),\n  p_30_to_45 = punif(45, min = 20, max = 60) - punif(30, min = 20, max = 60),\n  p_above_50 = 1 - punif(50, min = 20, max = 60),\n  p_10_to_30 = punif(30, min = 20, max = 60) - punif(10, min = 20, max = 60))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\narea_of_sketch correct_height     p_30_to_45     p_above_50     p_10_to_30 \n         0.800          0.025          0.375          0.250          0.250 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Task 11: A sample size for a target margin of error (6 minutes, extra practice for home)\n\nThe founder of the bouldering gym in Task 8 plans a new and larger sample.\nShe wants to estimate the mean visit time with a margin of error of at most\n5 minutes. She uses the sample SD of Task 8 as a planning value:\n$\\sigma=28$ minutes.\n\n1. Calculate the sample size that she needs at the 95% level\n   ($z_{0.975}=1.960$).\n2. Calculate the sample size for a margin of 2.5 minutes at the 95% level.\n   Compare it with part 1.\n3. Calculate the sample size for a margin of 5 minutes at the 99% level\n   ($z_{0.995}=2.576$).\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe formula of Lecture 9, with $m$ the margin of error, is\n\n$$\nn\\ge\\left(\\frac{z_{1-\\alpha/2}\\,\\sigma}{m}\\right)^2 .\n$$\n\n1. $n\\ge(1.960\\times28/5)^2=10.976^2\\approx120.5$, so she needs 121 visits.\n   Always round up: with 120 visits the margin would be slightly above 5\n   minutes.\n2. $n\\ge(1.960\\times28/2.5)^2=21.952^2\\approx481.9$, so 482 visits. Half\n   the margin needs about four times the sample.\n3. $n\\ge(2.576\\times28/5)^2=14.4256^2\\approx208.1$, so 209 visits. More\n   confidence with the same margin needs more observations: 209 in place\n   of 121.\n\nThe planning value is a guess. If the true $\\sigma$ is larger than 28\nminutes, the margin of the new sample will be larger than planned.\n\nVerification in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_needed <- c(margin_5_at_95 = (1.960 * 28 / 5)^2,\n              margin_2.5_at_95 = (1.960 * 28 / 2.5)^2,\n              margin_5_at_99 = (2.576 * 28 / 5)^2)\nn_needed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  margin_5_at_95 margin_2.5_at_95   margin_5_at_99 \n        120.4726         481.8903         208.0979 \n```\n\n\n:::\n\n```{.r .cell-code}\nceiling(n_needed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  margin_5_at_95 margin_2.5_at_95   margin_5_at_99 \n             121              482              209 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Task 12: A value for a sample mean (6 minutes, extra practice for home)\n\nAn invented example. A founder sells granola in bags of 250 grams. The\nfilling machine puts $X\\sim N(250,4^2)$ grams into one bag. Every hour she\nweighs a random sample of $n=16$ bags and calculates the sample mean\n$\\bar X$. She wants an alarm value $a$: she checks the machine when\n$\\bar X>a$. When the machine works as described, only 5% of the hourly\nsamples may give an alarm. Supplied value: the 0.95 quantile of $Z$ is\n$z_{0.95}=1.645$.\n\n1. State the distribution of $\\bar X$, with its standard deviation.\n2. Calculate the value $a$ with $P(\\bar X>a)=0.05$.\n3. Would the same rule make sense with single bags instead of the mean of\n   16 bags? Calculate the value for a single bag and compare.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n1. The population is normal, so the sample mean is exactly normal:\n   $\\bar X\\sim N(250,\\,4^2/16)$, with\n   $\\operatorname{SD}(\\bar X)=4/\\sqrt{16}=1$ gram.\n2. If 5% of the sample means lie above $a$, then 95% lie at or below it.\n   So $a$ is the 0.95 quantile of $\\bar X$:\n   $a=250+1.645\\times1=251.65$ grams.\n3. For a single bag the value is $250+1.645\\times4=256.58$ grams. Single\n   bags vary four times more than the mean of 16 bags. So the mean of 16\n   bags detects a change in the filling of the machine much earlier. Its\n   alarm value is only 1.65 grams above 250, about 0.7% of the bag weight.\n\nVerification in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(sd_mean = 4 / sqrt(16),\n  alarm_mean = qnorm(0.95, mean = 250, sd = 4 / sqrt(16)),\n  alarm_by_hand = 250 + 1.645 * 1,\n  alarm_single = 250 + 1.645 * 4,\n  shift_in_percent = 100 * 1.645 / 250)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         sd_mean       alarm_mean    alarm_by_hand     alarm_single \n          1.0000         251.6449         251.6450         256.5800 \nshift_in_percent \n          0.6580 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 30 minutes.</span>\n\n### Timed individual practice: 20 minutes\n\nDo this task alone and with a timer: no notes, no AI, only the formula\nsheet, as in the exam. An invented example. A random sample of 64 customers\nhas a mean monthly spending of €82 and a sample SD of €24. Of the 64\ncustomers, 40 renewed their subscription.\n\n1. Calculate the standard error of the mean spending.\n2. Calculate the standard error of the renewal proportion and check its\n   condition.\n3. State what would happen to both standard errors if the sample size were\n   $n=256$.\n4. Construct a 95% confidence interval for the mean monthly spending of all\n   customers, in the five parts of the exam procedure. The degrees of\n   freedom are 63. Use the closest value on the formula sheet:\n   $t_{0.975,\\,60}=2.000$. The business plan of the founder assumes a mean\n   spending of €90. Say in part 5 what the interval tells you about this\n   value.\n5. Write one sentence that explains the difference between sampling\n   uncertainty and selection bias.\n6. Treat $\\mu=82$ and $\\sigma=24$ as the population values. Use the CLT to\n   approximate the probability that a new sample of 64 customers shows a\n   mean above €85. Supplied value: $P(Z\\le 1)=0.841$.\n7. Use $\\sigma=24$ as a planning value. How many customers must a new\n   survey include to estimate the mean spending with a margin of error of\n   at most €3, at the 95% level\n   ($z_{0.975}=1.96$)?\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nThe standard error of the mean is $24/\\sqrt{64}=3$ euros. The renewal\nestimate is $\\hat p=40/64=0.625$, with standard error\n$\\sqrt{0.625(0.375)/64}\\approx0.0605$. The sample has 40 successes and 24\nfailures, so the success-failure condition holds. Increasing the sample\nsize from 64 to 256 would halve both standard errors if the spread\nstayed similar.\n\nThe interval for the mean spending in five parts:\n\n1. **Formula.** $\\bar X\\pm t_{1-\\alpha/2,\\,n-1}\\,S/\\sqrt n$. It may be used\n   because $n=64$ is large.\n2. **Given values.** $\\bar x=82$ euros, $s=24$ euros, $n=64$, $df=63$. The\n   confidence level is 95%, and the closest value on the formula sheet is\n   $t_{0.975,\\,60}=2.000$.\n3. **Calculations.** The standard error is $24/\\sqrt{64}=3$ euros. The\n   margin of error is $2.000\\times3=6$ euros.\n4. **Interval.** $(82-6,\\ 82+6)=(76,\\ 88)$ euros.\n5. **Conclusion.** The value 90 euros lies outside the interval. At the 5%\n   level we can conclude that the mean monthly spending differs from 90\n   euros. The whole interval lies below 90, so customers spend less than\n   the plan assumes: at least 2 euros less, about 2% of 90 euros.\n\nThe standard errors and the interval describe random variation from sample\nto sample, not bias created by an unrepresentative sampling frame. For the\nnew sample, the standard deviation of the sample mean is\n$\\operatorname{SD}(\\bar X)=24/\\sqrt{64}=3$ euros and\n$\\bar X\\mathrel{\\dot\\sim}N(82,3^2)$, so\n$z=(85-82)/3=1$ and $P(\\bar X>85)\\approx1-P(Z\\le1)\\approx0.16$. For a margin\nof €3, $n\\ge(1.96\\times24/3)^2=15.68^2\\approx245.9$, so the survey needs 246\ncustomers (Lecture 9).\n\nVerification in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_hat_renew <- 40 / 64\nc(se_mean = 24 / sqrt(64),\n  se_proportion = sqrt(p_hat_renew * (1 - p_hat_renew) / 64),\n  t_exact_df63 = qt(0.975, df = 63),\n  lower = 82 - 2.000 * 3, upper = 82 + 2.000 * 3,\n  below_90_in_percent = 100 * (90 - 88) / 90,\n  p_mean_above_85 = 1 - pnorm(85, mean = 82, sd = 3),\n  n_for_margin_3 = (1.96 * 24 / 3)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            se_mean       se_proportion        t_exact_df63               lower \n         3.00000000          0.06051536          1.99834054         76.00000000 \n              upper below_90_in_percent     p_mean_above_85      n_for_margin_3 \n        88.00000000          2.22222222          0.15865525        245.86240000 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Check your understanding (5 minutes)\n\nComplete from memory:\n\n1. A sampling distribution describes ...\n2. The standard deviation of a sample mean equals ... The standard error of\n   a sample mean equals ...\n3. The success-failure condition requires ...\n4. The CLT says ... becomes approximately normal.\n5. A larger sample does not fix ...\n6. A claimed value that lies outside a 95% confidence interval means ... A\n   claimed value that lies inside means ...\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. How a statistic would vary across repeated random samples.\n2. $\\sigma/\\sqrt n$. The standard error is the estimated version,\n   $s/\\sqrt n$.\n3. $np\\ge10$ and $n(1-p)\\ge10$. For a confidence interval the check uses\n   $\\hat p$.\n4. The sample mean. For a large sample its sampling distribution is\n   approximately normal. The single observations do not become normal.\n5. Selection bias, which comes from the way units entered the frame or the\n   sample.\n6. Outside: at the 5% level we can conclude that the parameter differs from\n   the claimed value. Inside: we cannot conclude that it differs, which is\n   not proof that the claimed value is true.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Two sentences about your own venture</span>\n\nThink of your EiA venture, or any business you know well. Pick one rate\nor average that you could estimate from about 100 observations, for\nexample a conversion rate, the average value of a purchase, or a renewal\nshare. Then write two sentences. First state the standard error that you\nwould roughly expect, and the 95% interval that follows from it. Then name one claimed value that your interval would\nrule out.\nLecture 10 turns this idea into a hypothesis test.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student venture that sells boxes of ready-made meals on campus. \"If 60 of 100 customers renew, the standard error of the renewal share is about 5 percentage points, so my 95% interval runs from roughly 50% to 70%. A claim that only 45% renew would lie outside this interval.\"\n:::\n\nYou can discuss this task, and any other task in this tutorial, with\n**Tilly**, the course AI assistant: ask it to check the standard error and\nthe interval for your own numbers.\n::::\n\n### More practice\n\nFor extra exercises on the lectures that this tutorial covers, with worked solutions, ask **Tilly**,\nthe course AI assistant. For example: \"Give me an extra exercise for\nTutorial 3. Show the solution only after I send my answer.\"\n\n[Continue to Lecture 10: Testing decisions, errors, power, and a first look at regression](b10-testing-errors-power.qmd).\n\n:::\n",
    "supporting": [
      "t03-exam-prep_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}