{
  "hash": "410ec627d6d119a61f3292a147b6e5f8",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 6: Interactions and curvature {#i06}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 6, you can</span>\n\n- read a picture of two lines as four numbers: two intercepts and two slopes\n- explain an interaction coefficient as a difference in slopes, with units\n- interpret the other coefficients in a model with an interaction, and use\n  centering to give them a useful meaning\n- report an interaction that is not significant without claiming too much in\n  either direction\n- apply the hierarchy principle and the `x * z` formula shorthand\n- fit a quadratic term, explain why the model is still a linear regression,\n  and compute a fitted change from both coefficients together\n- test added terms with a partial F-test, and explain why a curve must not be\n  used outside the range of the data.\n:::\n\n::: {.must-know}\n<span class=\"label\">Must know</span>\n\n**Be able to do yourself:**\n\n- write the two lines of an interaction model\n- interpret an interaction as a difference in slopes\n- say what centering changes and what it cannot change\n- calculate a fitted change in a quadratic model with $\\hat\\beta_1+\\hat\\beta_2(2x+1)$\n- explain why a curve must not be used beyond the range of the data.\n\n**Enough to recognise:**\n\n- the `I()` syntax, which is on the code sheet\n- the name hierarchy principle.\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">An average slope can hide the interesting part. A relationship may differ between groups, or it may bend as a predictor grows. Interactions and curves let a model show this.</p>\n\nThe equity offered (`equity_offered_pct`) in the Shark Tank file falls over\nthe seasons. Is this trend the same for every kind of presenting team, and\nis it a straight line at all?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 30 minutes.</span>\n\n**Minimum path:** the video and the R task. **Full path:** everything in this section.\n\nBring a charged laptop with RStudio and the course project open. The code of\nthe lecture is in this chapter, ready to copy, so you can run each step\nyourself during the lecture and get the same numbers and figures.\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation (15 minutes)</span><br>\nWatch Stanford Statistical Learning\n<a href=\"https://www.youtube.com/watch?v=dEBQmiXv9fk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=13\">3.5\nExtensions of the Linear Model</a> and\n<a href=\"https://www.youtube.com/watch?v=F-D3lZzYn50&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=48\">7.1\nPolynomials and Step Functions</a>. Focus on why an interaction changes a\nslope, and why a model with a squared term is still a linear regression. All\nlinks are also listed in the\n<a href=\"../resources/video-guide.html\">External Video Guide</a>.\n</div>\n\n**Derive the two lines (5 minutes).** In the model\n$Y=\\beta_0+\\beta_1X+\\beta_2D+\\beta_3XD+\\varepsilon$ with a dummy variable\n$D\\in\\{0,1\\}$, write the line for $D=0$ and the line for $D=1$.\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\nFor $D=0$: $E[Y\\mid X,D=0]=\\beta_0+\\beta_1X$. For $D=1$:\n$E[Y\\mid X,D=1]=(\\beta_0+\\beta_2)+(\\beta_1+\\beta_3)X$. Setting $D=1$ shifts\nthe intercept by $\\beta_2$ and the slope by $\\beta_3$.\n:::\n\n**Predict (2 minutes).** Answer the one-click Wooclap question posted on\nCanvas before you come to class: how many separate numbers do you need to\nfully describe a picture of **two straight lines with different slopes**?\nChoose one answer. You find the answer in the lecture material.\n\n**R warm-up (8 minutes).** Build the variables for the analysis. The code\nuses the same `known_gender` subset as Lecture 5. It adds a dummy `women`\nand a centred season `season_c`, which is the season minus the mean season.\nIt then fits one line of equity offered on season for each group and draws\nboth lines. Bring the plot:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nsharks$ask_1k <- sharks$ask_amount_usd / 1000\nknown_gender <- subset(sharks, pitcher_gender_group != \"unknown\")\nknown_gender$women <- as.integer(\n  known_gender$pitcher_gender_group %in% c(\"all_women\", \"mixed\")\n)\nknown_gender$season_c <- known_gender$season - mean(known_gender$season)\n\nplot(equity_offered_pct ~ season, data = known_gender,\n     pch = 16, col = \"grey80\")\nabline(lm(equity_offered_pct ~ season,\n          data = subset(known_gender, women == 0)),\n       col = \"#0072B2\", lwd = 3)\nabline(lm(equity_offered_pct ~ season,\n          data = subset(known_gender, women == 1)),\n       col = \"#D55E00\", lwd = 3)\n```\n:::\n\n\n\n\nIf you are not sure about products, powers, or centering, review\n[Mathematics Refresher: products, powers, and centering](../resources/math-refresher.html).\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## Lecture material\n\nThis section has two parts. The first part adds an interaction, which lets\na slope differ between two groups. The second part adds a squared term,\nwhich lets a slope change along the predictor itself.\n\n<p class=\"concept-video\"><strong>Stanford explanations (review):</strong>\n<a href=\"https://www.youtube.com/watch?v=dEBQmiXv9fk\">3.5 Extensions of the Linear Model</a> and\n<a href=\"https://www.youtube.com/watch?v=F-D3lZzYn50\">7.1 Polynomials and Step Functions</a>.</p>\n\n### Start with a founder's question\n\nDoes advertising work equally well in every week? Does a trend go on in a\nstraight line forever? Often the answer is \"it depends\". The two tools of\nthis lecture let you check this in the data. An interaction lets a slope\ndiffer between groups. A curve lets a slope change along the way.\n\n### The picture before the formula\n\nIn every model so far, all groups had the same slope. Lecture 5 let the\nheight of the line differ between groups. Now the slope may differ as well.\nStart with the picture in @fig-i06-two-lines:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the drawing code (optional, not exam material)\"}\nold_par <- par(no.readonly = TRUE)\npar(mar = c(4.2, 4.2, 1, 1), las = 1)\nplot(NA, xlim = c(0, 10), ylim = c(0, 10), bty = \"n\",\n     xlab = \"Predictor X\", ylab = \"Outcome Y\")\nabline(a = 2, b = 0.75, col = \"#009E73\", lwd = 3)\nabline(a = 4.5, b = 0.25, col = \"#D55E00\", lwd = 3, lty = 2)\ntext(8.4, 2 + 0.75 * 8.4 + 0.9, \"Group D = 0\", col = \"#009E73\")\ntext(8.4, 4.5 + 0.25 * 8.4 - 0.8, \"Group D = 1\", col = \"#D55E00\")\npar(old_par)\n```\n\n::: {.cell-output-display}\n![Two groups, two lines, different slopes (an invented picture). How many numbers do you need to describe this picture completely?](i06-interactions-curvature_files/figure-html/fig-i06-two-lines-1.png){#fig-i06-two-lines width=672}\n:::\n:::\n\n\n\n\nThis answers the Wooclap question from before class: four numbers, an\nintercept and a slope for each line. The interaction model writes the same\nfour numbers in a different way:\n\n$$\nE[Y\\mid X,D]\n=\\beta_0+\\beta_1X+\\beta_2D+\\beta_3XD.\n$$\n\nEach coefficient is one feature of the picture:\n\n- $\\beta_0$: where the $D=0$ line meets the vertical axis\n- $\\beta_1$: the slope of the $D=0$ line\n- $\\beta_2$: how much higher the $D=1$ line starts\n- $\\beta_3$: how much steeper the $D=1$ line is.\n\nThe same in a table with one row per group, as you derived it before class:\n\n| Group | Intercept | Slope |\n|---|---|---|\n| $D=0$ | $\\beta_0$ | $\\beta_1$ |\n| $D=1$ | $\\beta_0+\\beta_2$ | $\\beta_1+\\beta_3$ |\n\nWhen $\\beta_3=0$ the two lines are parallel, and the model is the dummy\nmodel of Lecture 5 with one common slope.\n\n### The interaction coefficient is a difference in slopes\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**Interaction.** A term that is the product of two predictors, for example\n$X\\times D$. It lets the slope of one predictor depend on the value of the\nother. Its coefficient is a difference in slopes.\n:::\n\nIn the additive model the slope of $X$ is the same at every value of the\nother predictor. With the product $XD$ in the model, a one-unit increase in\n$X$ changes the conditional mean by\n\n$$\n\\beta_1+\\beta_3D.\n$$\n\nSo $\\beta_3$ is the difference between the slope of the group with $D=1$ and\nthe slope of the reference group. It is not an effect on its own. Its unit\ncombines the two variables. If $X$ is measured in seasons and $D$ is a\ndummy, $\\beta_3$ is in outcome units per season: here, equity percentage\npoints per season, one group minus the reference group. The same algebra\nworks when the second variable is a number $Z$ and not a dummy. The slope of\n$X$ is then $\\beta_1+\\beta_3Z$, a slope that changes with $Z$.\n\n**Centering.** Centering a predictor means subtracting its mean. With $XD$\nin the model, $\\beta_2$ compares the two groups at $X=0$. For the Shark Tank\ndata this would be Season 0, which does not exist. Replacing season with\n\n$$\nseason\\_c = season - \\overline{season}\n$$\n\nmoves that comparison to the average season (about 8.8). Centering changes\none kind of thing and cannot change another:\n\n- It changes the meaning and the value of the intercept and of the group\n  coefficient. Both now refer to the average season.\n- It cannot change the fitted values, the residuals, $R^2$, or the\n  interaction coefficient. The lines are the same lines. Only the place\n  where we read the vertical gap between them has moved.\n\n::: {.callout-note collapse=\"true\"}\n## Check: which printed numbers change when season is centred?\n\nThe intercept and the `women` coefficient change. The interaction\ncoefficient, the `ask_1k` coefficient, all fitted values, and $R^2$ do not.\nYou check this in R in the after-class practice.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Try it: two lines from four coefficients\n\nTry this with your neighbour first. In an invented example, a venture models\nweekly orders with advertising spending in euros, a dummy for exam weeks,\nand their interaction:\nfitted orders = 100 + 0.10 × ads + 15 × exam + 0.12 × ads × exam.\n\n*Step 1 (given).* In ordinary weeks (exam = 0) the line is 100 + 0.10 × ads.\n\n*Step 2 (you).* Write the line for exam weeks.\n\n*Step 3 (you).* Compare the fitted orders at 200 euros of advertising in the\ntwo kinds of weeks, and say what the coefficient 0.12 means.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nExam weeks: (100 + 15) + (0.10 + 0.12) × ads = 115 + 0.22 × ads. At 200\neuros: 120 orders in an ordinary week and 159 in an exam week. The\ncoefficient 0.12 is the difference between the two slopes: each euro of\nadvertising goes with 0.12 more orders in an exam week than in an ordinary\nweek.\n:::\n:::\n\n### The Shark Tank interaction model\n\nNow take the first half of the driving question. In this lecture,\n`women = 1` means that the presenting team is classified as all-women or\nmixed, and `women = 0` means all-men. This split is broader than the three\ncategories of Lecture 5. It does not measure the share of women or the full\nteam behind the venture. The seven `unknown` records are left out as before.\nThe code first builds the variables, as in the R warm-up:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nsharks$ask_1k <- sharks$ask_amount_usd / 1000\nknown_gender <- subset(sharks, pitcher_gender_group != \"unknown\")\nknown_gender$women <- as.integer(\n  known_gender$pitcher_gender_group %in% c(\"all_women\", \"mixed\")\n)\nknown_gender$season_c <- known_gender$season - mean(known_gender$season)\n\ninteraction_model <- lm(\n  equity_offered_pct ~ season_c * women + ask_1k,\n  data = known_gender\n)\nsummary(interaction_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = equity_offered_pct ~ season_c * women + ask_1k, \n    data = known_gender)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-15.871  -4.742  -1.290   3.412  82.689 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    13.6247907  0.3354522  40.616  < 2e-16 ***\nseason_c       -0.7993817  0.0663226 -12.053  < 2e-16 ***\nwomen           0.8069665  0.4117061   1.960   0.0502 .  \nask_1k         -0.0026776  0.0005834  -4.590 4.83e-06 ***\nseason_c:women -0.0614594  0.0955667  -0.643   0.5203    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.62 on 1429 degrees of freedom\nMultiple R-squared:  0.1894,\tAdjusted R-squared:  0.1871 \nF-statistic: 83.47 on 4 and 1429 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nUse the table with one row per group to get the two season slopes, holding\nrequested amount fixed. For all-men teams (`women = 0`), the fitted season\nslope is about $-0.799$ percentage points per season. For teams with women\n(`women = 1`), it is\n\n$$\n-0.7994+(-0.0615)=-0.861\n\\text{ percentage points per season.}\n$$\n\nThe interaction estimate is $-0.061$ equity percentage points per season,\nwith a p-value of about 0.520. The difference is small: about 8% of the\nall-men slope. Read this result in both directions. The model gives no\nevidence that the season trend differs between the two groups. It also does\nnot prove that the two slopes are equal. The estimate is imprecise (standard\nerror about 0.096), so the data fit a somewhat steeper trend and also a\nsomewhat flatter trend for teams with women. No evidence of a difference is\nnot proof of no difference.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nsharks$ask_1k <- sharks$ask_amount_usd / 1000\nknown_gender <- subset(sharks, pitcher_gender_group != \"unknown\")\nknown_gender$women <- as.integer(\n  known_gender$pitcher_gender_group %in% c(\"all_women\", \"mixed\")\n)\nknown_gender$season_c <- known_gender$season - mean(known_gender$season)\ninteraction_model <- lm(\n  equity_offered_pct ~ season_c * women + ask_1k,\n  data = known_gender\n)\nseason_grid <- 1:16\nask_bar <- mean(known_gender$ask_1k)\nnewdat <- expand.grid(season = season_grid, women = c(0, 1))\nnewdat$season_c <- newdat$season - mean(known_gender$season)\nnewdat$ask_1k <- ask_bar\nnewdat$fit <- predict(interaction_model, newdata = newdat)\nnewdat$group <- ifelse(newdat$women == 1, \"Women represented\", \"All-men\")\nfit_men_13 <- newdat$fit[newdat$women == 0 & newdat$season == 13]\nfit_women_13 <- newdat$fit[newdat$women == 1 & newdat$season == 13]\n\nggplot(newdat, aes(x = season, y = fit,\n                   colour = group, linetype = group)) +\n  geom_line(linewidth = 1.1) +\n  geom_point(data = subset(newdat, season %in% c(1, 16)), size = 2.2) +\n  annotate(\"text\", x = 13, y = fit_women_13 + 1.1,\n           label = \"Women represented\",\n           colour = \"#D55E00\", size = 3.4) +\n  annotate(\"text\", x = 13, y = fit_men_13 - 1.1,\n           label = \"All-men\",\n           colour = \"#009E73\", size = 3.4) +\n  scale_colour_manual(values = c(\"All-men\" = \"#009E73\",\n                                 \"Women represented\" = \"#D55E00\"),\n                      guide = \"none\") +\n  scale_linetype_manual(values = c(\"All-men\" = \"solid\",\n                                   \"Women represented\" = \"dashed\"),\n                        guide = \"none\") +\n  scale_x_continuous(breaks = seq(1, 16, by = 3)) +\n  labs(x = \"Season\", y = \"Fitted initial equity offered (%)\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![Fitted equity offered by season for all-men teams and for teams with women, at the average requested amount. The two lines are almost parallel. The slope of a line is the fitted change per season for that group, and the vertical gap is the fitted difference between the groups in a given season.](i06-interactions-curvature_files/figure-html/fig-i06-interaction-1.png){#fig-i06-interaction width=672}\n:::\n:::\n\n\n\n\nAlways graph a model that contains an interaction. In @fig-i06-interaction\nthe two almost parallel lines are the result. Once $XD$ is in the model,\nneither $\\hat\\beta_1$ nor $\\hat\\beta_2$ alone describes all teams.\n\n### The hierarchy principle and the `*` shorthand\n\nThe **hierarchy principle** says: if a model contains $XD$, keep both $X$\nand $D$ in the model, even when one of them is not significant on its own.\nThe terms $X$ and $D$ define the two lines, and the interaction describes\nthe difference between these lines. Without one of them the two lines are\nrestricted for no reason, for example to the same intercept, and this\nrestriction distorts the interaction coefficient. The `*` shorthand in an R\nformula follows the principle for you:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(y ~ x * z, data = df)  # x * z expands to x + z + x:z\n```\n:::\n\n\n\n\nThe first part of this lecture let the slope differ by group. The second\npart lets the slope differ along $x$ itself. Both parts do the same thing:\nthey give least squares a new column that is built from the data (a product\nor a square), and they read several coefficients together.\n\n### Curvature: polynomials are still linear regression\n\nIs the season trend a straight line at all? To let it bend, add the square\nof the predictor.\n\n::: {.definition-box}\n<span class=\"label\">Definition</span>\n\n**Quadratic term.** The square of a predictor, $x^2$, added to a model that\nalso contains $x$. It lets the fitted line bend, so the slope changes with\n$x$. A model with powers of a predictor is called a polynomial.\n:::\n\nThe quadratic conditional mean\n\n$$\nE[Y\\mid X=x]=\\beta_0+\\beta_1x+\\beta_2x^2\n$$\n\nis curved in $x$, but it is linear in the unknown coefficients\n$\\beta_0,\\beta_1,\\beta_2$. That is all `lm()` requires. The square is one\nmore column of data.\n\nWhat changes is how to read the output. The slope is no longer one number.\nMoving from $x$ to $x+1$ changes the conditional mean by\n\n$$\n(\\beta_1(x+1)+\\beta_2(x+1)^2) - (\\beta_1x+\\beta_2x^2)\n=\\beta_1+\\beta_2(2x+1).\n$$\n\nThis change depends on where you start. The rule is: **never read $\\beta_1$\nalone while $x^2$ is in the model.** Calculate fitted changes or graph the\ncurve.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_season <- lm(equity_offered_pct ~ season + ask_1k, data = sharks)\npoly_season <- lm(equity_offered_pct ~ season + I(season^2) + ask_1k,\n                  data = sharks)\nsummary(poly_season)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate   Std. Error   t value      Pr(>|t|)\n(Intercept) 24.171680818 0.8205664983 29.457309 1.332051e-149\nseason      -1.713233277 0.2056686354 -8.330066  1.862369e-16\nI(season^2)  0.051034200 0.0113694269  4.488722  7.737227e-06\nask_1k      -0.002710806 0.0005740121 -4.722559  2.556506e-06\n```\n\n\n:::\n:::\n\n\n\n\n`I()` tells R to calculate the square. Without it, R would read `^` as\nformula syntax. The fitted coefficients are $\\hat\\beta_1 \\approx -1.713$ for\n`season` and $\\hat\\beta_2 \\approx 0.051$ for `I(season^2)`. Together they\ndescribe a steep decline in the early seasons that becomes flatter season by\nseason.\n\n::: {#exm-i06-quadratic-change}\n## Worked example: the fitted change from Season 5 to Season 6\n\nHolding requested amount fixed, the fitted change from season $x$ to season\n$x+1$ is $\\hat\\beta_1+\\hat\\beta_2(2x+1)$. From Season 5 to Season 6, $x = 5$:\n\n$$\n\\hat\\beta_1+\\hat\\beta_2(2\\times5+1)\n=-1.713+0.051\\times11\n=-1.713+0.561\n\\approx-1.15\n\\text{ percentage points.}\n$$\n\nReading $\\hat\\beta_1=-1.713$ alone would overstate the drop by about 0.56\npoints, which is about half of the fitted drop of 1.15 points. The number\n$-1.713$ is not a constant slope. It belongs to $x=0$, a season that does\nnot exist. Check the calculation in R with the stored coefficients:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb <- coef(poly_season)\nunname(b[\"season\"] + b[\"I(season^2)\"] * (2 * 5 + 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.151857\n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Is the curvature worth having? The partial F\n\nThe quadratic model and the linear model are nested, so the partial F-test\nof Lecture 5 applies to the one added term:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(linear_season, poly_season)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: equity_offered_pct ~ season + ask_1k\nModel 2: equity_offered_pct ~ season + I(season^2) + ask_1k\n  Res.Df   RSS Df Sum of Sq      F    Pr(>F)    \n1   1438 83493                                  \n2   1437 82338  1    1154.5 20.149 7.737e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nThe partial F-test for adding `I(season^2)` gives $F \\approx 20.1$ with a\np-value below 0.001. The data show a curve. The gain in fit is small:\nadjusted $R^2$ rises from about 0.186 to about 0.196, one percentage point\nmore of the variation in the equity offered. So also look at the shape of\nthe curve in @fig-i06-polynomial:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nsharks$ask_1k <- sharks$ask_amount_usd / 1000\npoly_season <- lm(equity_offered_pct ~ season + I(season^2) + ask_1k,\n                  data = sharks)\nseason_means <- aggregate(equity_offered_pct ~ season, data = sharks, mean)\ncurve_data <- data.frame(season = seq(1, 16, length.out = 200),\n                         ask_1k = mean(sharks$ask_1k))\ncurve_data$fit <- predict(poly_season, newdata = curve_data)\n\nggplot(season_means, aes(x = season, y = equity_offered_pct)) +\n  annotate(\"rect\", xmin = 16, xmax = 17.6, ymin = -Inf, ymax = Inf,\n           fill = \"grey75\", alpha = 0.25) +\n  geom_vline(xintercept = 16, colour = \"grey60\",\n             linetype = \"dashed\", linewidth = 0.8) +\n  geom_line(data = curve_data, aes(x = season, y = fit),\n            colour = \"#D55E00\", linewidth = 1.1) +\n  geom_point(size = 2.6, colour = \"#009E73\") +\n  annotate(\"text\", x = 16.8, y = max(season_means$equity_offered_pct),\n           label = \"no data beyond\\nseason 16\", colour = \"#5B6976\",\n           size = 3, lineheight = 0.95) +\n  scale_x_continuous(breaks = seq(1, 16, by = 3)) +\n  coord_cartesian(xlim = c(1, 17.6)) +\n  labs(x = \"Season\", y = \"Initial equity offered (%)\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![Season means of the equity offered (points) and the fitted quadratic curve at the average requested amount. The curve becomes flatter towards the last observed seasons. Beyond Season 16 (shaded) it would turn upward, but there are no data in that region.](i06-interactions-curvature_files/figure-html/fig-i06-polynomial-1.png){#fig-i06-polynomial width=672}\n:::\n:::\n\n\n\n\nThe points in @fig-i06-polynomial are the plain means of each season. The\ncurve holds the requested amount at its sample mean. To extrapolate means to\nuse a fitted model outside the range of the data. **Do not extrapolate the\nquadratic beyond Seasons 1--16.** The fitted curve reaches its lowest point\njust after Season 16 and would rise steeply afterwards. This rise comes from\nthe shape of a quadratic, not from any data, so it is not a forecast.\n\n::: {.caveat-box}\n<span class=\"label\">What flexible terms can and cannot repair</span>\n\n- Interactions and curves make the model more flexible. They repair nothing\n  about how the data came about.\n- Every added term costs precision. Add a term because a question asks for\n  it, not because it turns out significant.\n- A curve can be trusted only inside the range of the data.\n\n**What you can do with it:** ask whether a relationship could differ between\ngroups or bend, add that one term, graph the fitted lines, and report\ncombined results.\n:::\n\n### Answering the driving question\n\n**The same trend for every kind of team?** The estimated difference in\nslopes is $-0.061$ percentage points per season (p $\\approx$ 0.52). The data\nshow no difference between all-men teams and teams with women. They also do\nnot prove that the trends are equal, because the estimate is imprecise.\n\n**A straight line?** Not quite. The quadratic term is significant (partial\n$F \\approx 20.1$, p $<$ 0.001). The fitted decline becomes flatter: from\nabout $-1.56$ points per season between Seasons 1 and 2 to about $-0.64$\nbetween Seasons 10 and 11. The curve can be used only inside Seasons 1--16.\n\n::: {.founder-box}\n<span class=\"label\">A founder's decision (invented example)</span>\n\nYou suspect that advertising works better in exam weeks. The model with an interaction gives an advertising slope of 0.10 orders per euro in ordinary weeks and 0.10 + 0.12 = 0.22 in exam weeks. After a price increase, each order now brings 6 euros of margin. So 100 euros of advertising goes with 10 more orders and 60 euros of margin in an ordinary week, which is less than the advertising costs. In an exam week it goes with 22 more orders and 132 euros of margin. The decision: advertise in the exam weeks only. One check first: the interaction of 0.12 has its own interval. If that interval includes zero, the difference between the two kinds of weeks is not yet established, and you keep the budget split for one more term before you commit.\n:::\n\n**Next:** Tutorial 2 practises Lectures 4--6 in the format of the exam. It\nends with one full analysis, from a research question to a conclusion of 150\nwords. The exam asks for this kind of analysis, and so will your thesis.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 85 minutes.</span>\n\n**Minimum path (about 35 minutes):** read the lecture material, answer the recall questions, then work for 10 minutes on the tasks that follow. **Full path:** all tasks below.\n\n### Read the lecture material (15 minutes)\n\nRead the Lecture material section above from start to end. The lecture\ncovered the core of it. The text has every step, every example, and all the\ncode, including parts that were not shown in class. Note what is still\nunclear and bring it to the next tutorial, or ask Tilly.\n\n### Recall questions (10 minutes)\n\n1. What does an interaction coefficient measure, and what is its unit in the\n   model with season and the `women` dummy?\n2. Why centre a predictor before you use it in an interaction, and what can\n   centering never change?\n3. State the hierarchy principle.\n4. Why is a quadratic model still a linear regression model?\n5. Why should you graph a quadratic curve, and why should you not\n   extrapolate it?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. How the slope of one predictor differs with the other predictor. Here its\n   unit is equity percentage points per season, as a difference between the\n   two groups.\n2. So that the intercept and the group coefficient refer to a useful value,\n   such as the sample mean, and not to zero. Centering never changes the\n   fitted values, the residuals, $R^2$, or the interaction coefficient.\n3. Keep $X$ and $D$ in the model whenever their interaction $XD$ is in it,\n   and keep $x$ whenever $x^2$ is in it.\n4. It is linear in the unknown coefficients. The squared column is one more\n   predictor built from the data.\n5. No single coefficient is the slope, so only fitted values or the curve\n   show what the model says. Outside the observed range the curve can turn\n   sharply, and no data support that turn.\n:::\n\n### Centering verification (10 minutes)\n\nFit the interaction model with and without centering season. Check that the\nfitted values and the interaction coefficient are unchanged, and report\nwhich coefficients do change.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nsharks$ask_1k <- sharks$ask_amount_usd / 1000\nknown_gender <- subset(sharks, pitcher_gender_group != \"unknown\")\nknown_gender$women <- as.integer(\n  known_gender$pitcher_gender_group %in% c(\"all_women\", \"mixed\")\n)\nknown_gender$season_c <- known_gender$season - mean(known_gender$season)\n\nuncentered <- lm(equity_offered_pct ~ season * women + ask_1k,\n                 data = known_gender)\ncentered <- lm(equity_offered_pct ~ season_c * women + ask_1k,\n               data = known_gender)\nall.equal(fitted(uncentered), fitted(centered))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nc(uncentered = unname(coef(uncentered)[\"season:women\"]),\n  centered = unname(coef(centered)[\"season_c:women\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n uncentered    centered \n-0.06145941 -0.06145941 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(women_uncentered = unname(coef(uncentered)[\"women\"]),\n  women_centered = unname(coef(centered)[\"women\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwomen_uncentered   women_centered \n       1.3465150        0.8069665 \n```\n\n\n:::\n:::\n\n\n\n\nThe fitted values agree, and both interaction estimates are about $-0.061$.\nThe `women` coefficient changes from about $1.35$ (a comparison at Season 0,\nwhich does not exist) to about $0.81$ (a comparison at the average season,\nabout 8.8). The intercept changes as well. Centering moved the place where\nthe gap is read. It did not move the lines.\n:::\n\n### Finish a half-worked example: a quadratic change (15 minutes)\n\nRead the worked calculation for Season 5 to Season 6 again\n(@exm-i06-quadratic-change). Then calculate the fitted change from **Season\n10 to Season 11** in the same model.\n\n*Step 1 (given).* The formula is $\\hat\\beta_1+\\hat\\beta_2(2x+1)$ with $x=10$,\nso $\\hat\\beta_2$ is multiplied by $21$.\n\n*Step 2 (you).* Plug in $\\hat\\beta_1\\approx-1.713$ and $\\hat\\beta_2\\approx0.051$.\n\n*Step 3 (you).* Compare the result with the Season 5 to 6 change and state\nin one sentence what the comparison shows about the trend.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$-1.713+0.051\\times21\\approx-1.713+1.071\\approx-0.64$ percentage points\n(with the unrounded coefficients: $\\hat\\beta_1+21\\hat\\beta_2=-0.642$). The\ndrop per season has become smaller, from about $-1.15$ (Seasons 5--6) to\nabout $-0.64$ (Seasons 10--11). The decline becomes flatter in later\nseasons. This is what a positive $\\hat\\beta_2$ means.\n:::\n\nNow do the next tasks on your own, with new coefficients from an invented\nexample. A model of monthly revenue (€1,000s) on the age of a shop $x$\n(years) reports $\\widehat Y = 40 - 2.00x + 0.060x^2$.\n\n1. Calculate the fitted change from age 3 to age 4 and from age 8 to age 9.\n2. A colleague reports \"revenue falls €2,000 per year of age.\" Correct the\n   sentence.\n3. In $\\widehat Y=10+2X+3D-0.5XD$, write the lines of both groups and\n   interpret the interaction coefficient.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. Age 3 to 4: $-2.00+0.060(2\\times3+1)=-2.00+0.42=-1.58$, about\n   $-€1{,}580$. Age 8 to 9: $-2.00+0.060\\times17=-0.98$, about $-€980$.\n2. $-2.00$ is not the fitted change per year. With $x^2$ in the model the\n   change depends on age: about $-1.58$ from age 3 to 4 and about $-0.98$\n   from age 8 to 9. The decline becomes weaker as shops get older.\n3. For $D=0$: $\\widehat Y=10+2X$. For $D=1$: $\\widehat Y=13+1.5X$. The\n   interaction coefficient $-0.5$ says that the slope of the $D=1$ group is\n   0.5 outcome units per unit of $X$ smaller than the slope of the $D=0$\n   group.\n:::\n\n### Cumulative mini-task (15 minutes)\n\nIn Lecture 4 you wrote a paragraph that connects the diagnostics of Lecture\n2 to the three-predictor model of the equity offered. Add one argument to\nthat paragraph. Propose either an interaction or a quadratic term for that\nmodel. State the question about the business or the data that motivates the\nterm, and say how you would test whether the term belongs in the model.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nA good answer: \"The decline over the seasons need not be a straight line.\nThe show was new in the early seasons and pitches became more professional\nlater, so the trend may become flatter. I would add `I(season^2)`. I add the\nterm because of this question about the shape, not because I am searching\nfor a significant result. I would test it with a partial F-test against the\nnested linear model on the same observations (here $F\\approx20.1$,\np $<$ 0.001), check that adjusted $R^2$ rises, graph the fitted curve inside\nSeasons 1--16, and report fitted changes from season to season in place of\nthe `season` coefficient alone.\" An answer with an interaction is equally\ngood if it names the question and the nested test. An example is the\ninteraction of season with the `women` dummy, which asks whether the trend\ndiffers between the groups. Its test gives $F\\approx0.41$ and\np $\\approx$ 0.52, so the term is not kept.\n:::\n\n### Review: one partial-F question from Lecture 5 (5 minutes)\n\nAdding the two gender dummies to the season-and-ask model of equity reduced\nthe residual sum of squares by 436.25 using 2 degrees of freedom, and the\ncomplete model left 82,792 on 1,429 degrees of freedom. Compute the partial\nF statistic and state the 5% conclusion.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$F=(436.25/2)/(82{,}792/1{,}429)=218.1/57.9\\approx3.76$, with\np $\\approx$ 0.023. At 5%, the two category terms are jointly useful in that\nmodel, even though the t-test of the mixed dummy alone is far from\nsignificant. Joint tests and individual tests answer different questions.\n:::\n\n### Worked exam interpretation (5 minutes)\n\n**Question.** This question is in the style of Question 5 of the mock exam.\nThe numbers are invented. A model of the sales growth of ventures\n(percentage points) on marketing spending (€10,000s), a dummy for\nonline-only ventures, and their interaction reports `spending 1.20`,\n`online 2.00`, `spending:online -0.50`. A student writes: \"Spending raises\ngrowth by 1.2 percentage points per €10,000 for all ventures.\" Correct the\nsentence.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\nTwo corrections. First, with the interaction in the model, 1.20 is the\nfitted spending slope only for ventures that are not online-only\n(`online = 0`). For online-only ventures the slope is $1.20-0.50=0.70$\npercentage points per €10,000. There is no single slope for all ventures.\nSecond, \"raises\" claims causation. These are fitted associations among the\nsampled ventures, holding the other included terms fixed. The data do not\ncome from an experiment, so they do not show an effect of spending.\n:::\n\n### Check the AI (5 minutes)\n\nYou asked an AI assistant: \"The interaction has a coefficient of -0.061 and a p-value of 0.52. What do I conclude?\" It answered:\n\n> \"The p-value proves that the season trend is identical for both groups. And the season coefficient of -0.80 is the season trend for all teams.\"\n\nFind what is wrong and write the corrected answer. This is the **Verify**\nstep of Attempt → Ask → Verify → Explain, and the exam asks for it.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nTwo errors. A large p-value means the data do not show a difference. It does not prove that the trends are the same, because the estimate is imprecise. And with an interaction in the model, -0.80 is the trend for the group coded 0, the all-men teams. For teams with women it is -0.80 - 0.06 = -0.86.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA3 venture, or any business you know well. Name one\nrelationship in its data whose slope could depend on something else. For\nexample, the response to price may differ by customer segment, the result of\na campaign may differ by channel, or growth may become flatter as the\nbusiness gets larger. Then write two sentences. First, state the interaction\nor quadratic term you would add and the question behind it. Second, say what\na result that is not significant would tell you, and what it would not tell\nyou. There is no wrong answer.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run venture that sells meal-prep boxes on campus (an invented example). \"I would add an interaction of advertising spend with exam week, because my question is whether ads only work when students are on campus. An interaction that is not significant would mean no evidence that the slopes differ. It would not prove that exam weeks make no difference.\"\n:::\n\nYou can discuss this task, and any other task in this chapter, with\n**Tilly**, the course AI assistant. Ask it to read your two sentences and to\ncheck whether you treated \"no evidence of a difference\" as \"proof of no\ndifference\".\n::::\n\n[Continue to Tutorial 2: Multiple regression and extensions](t02-exam-prep.qmd).\n\n[Code sheet: Lecture 6 commands and formulas](code-sheet.qmd#lecture-6-interactions-and-polynomial-terms).\n\nFor a more formal treatment, see James et al., *An Introduction to\nStatistical Learning*, 2nd ed., Section 3.3.2 and Sections 3.6.4--3.6.6,\nand\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapter 21.\n\n:::\n",
    "supporting": [
      "i06-interactions-curvature_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}