{
  "hash": "90b5e4a35fd0c6d6aa3c5a687c3b62e6",
  "result": {
    "engine": "knitr",
    "markdown": "# Tutorial 1: Simple regression, diagnostics, and model usefulness {#i-ep01}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Tutorial 1, you can</span>\n\n- fit and interpret a simple regression in R, with units\n- calculate fitted values and residuals by hand\n- find problems with the assumptions from residual plots, standardised\n  residuals, and Cook's distance\n- interpret the coefficient table, $R^2$, and the F-test together\n- write a short interpretation of a model that is ready for the exam format.\n:::\n\nTutorials are **exam preparation sessions**. Every task below follows the\nformat of the final exam, which is taken in TestVision with R available.\nYou first try each task in pairs. You may use AI for this, following\nAttempt, Ask, Verify, Explain. Then the solution is discussed together.\n\nThe tasks follow the order of the course. Tasks 1 and 2 use Lecture 1, Task 3\nuses Lecture 2, and Tasks 4 and 5 use Lecture 3. Task 6 applies all steps to\na new question that matters to founders.\n\n::: {.course-phase .phase-before}\n\n## Before class\n\nComplete the after-class practice from Lectures 1 and 2. Lecture 3 is on the\nday before this tutorial: read its lecture material, and do its practice\nafter the tutorial. Keep the Lectures\n1--3 sections of the\n[QM Intermediate Code Sheet](#intermediate-code-sheet) open while working.\nIf the notation slows you down, review\n[Mathematics Refresher: lines, squares, and standardisation](../resources/math-refresher.html).\n\nWrite from memory:\n\n1. the simple linear regression model\n2. the fitted line\n3. the residual\n4. the formula for $R^2$\n5. the null hypothesis of the overall model F-test.\n\n::: {.callout-note collapse=\"true\"}\n## Check your preparation\n\n1. $Y_i=\\beta_0+\\beta_1X_i+\\varepsilon_i$.\n2. $\\widehat Y_i=\\hat\\beta_0+\\hat\\beta_1X_i$.\n3. $e_i=Y_i-\\widehat Y_i$.\n4. $R^2=1-\\text{SSE}/\\text{SST}=\\text{SSR}/\\text{SST}$.\n5. $H_0:\\beta_1=0$ in simple regression (all slopes zero in general).\n:::\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In the tutorial\n\nAttempt each task in R before opening the answer. A complete written answer\nnames the sample, shows the calculation, reports values with units,\ninterprets them in context, and states one important limit of the model or\nof the data.\n\nAll tasks use the Shark Tank teaching file and the valuations of Lectures 1\nto 3, in **millions of dollars**: the valuation agreed on air (`agreed_m`)\nand the valuation claimed by the founder (`claimed_m`). Build the data once,\nin the same way as in Lectures 1--3:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nvals <- subset(sharks, deal_on_show == 1 & deal_equity_pct > 0)\nvals$claimed_m <- vals$requested_valuation_usd / 1e6\nvals$agreed_m <- vals$deal_valuation_usd / 1e6\nnrow(vals)   # deals for a share of the company\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 874\n```\n\n\n:::\n:::\n\n\n\n\n### Task 1: Fit and interpret (Lecture 1)\n\nFit `agreed_m ~ claimed_m` among the deals for a share of the company.\nReport the sample, the fitted equation, the interpretation of the slope with\nunits, and the limit of the intercept.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nval_model <- lm(agreed_m ~ claimed_m, data = vals)\ncoef(val_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)   claimed_m \n-0.06798986  0.64874084 \n```\n\n\n:::\n:::\n\n\n\n\nAmong the 874 deals for a share of the company, the fitted equation is\n$\\widehat y = -0.068 + 0.649x$, with both valuations in \\$ millions. A\nclaimed valuation that is \\$1 million higher is associated with an agreed\nvaluation about \\$0.65 million higher. A claimed valuation of zero is outside\nthe observed range, so the intercept (about $-\\$68{,}000$) has no useful\nbusiness meaning of its own.\n:::\n\n### Task 2: Fitted value and residual (Lecture 1)\n\nA founder claimed a valuation of \\$5 million and the deal closed at a\nvaluation of \\$2.5 million.\n\n1. Calculate its fitted value.\n2. Calculate its residual.\n3. Interpret the sign of the residual.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nWith $x=5$ (in \\$ millions),\n$\\widehat y = -0.068 + 0.649 \\times 5 \\approx 3.18$, or about \\$3.18 million.\nThe observed $y = 2.5$, so $e = 2.5 - 3.18 = -0.68$, about $-\\$680{,}000$.\nThe negative sign means this deal closed below the model's fitted conditional\nmean for a claimed valuation of \\$5 million.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nval_model <- lm(agreed_m ~ claimed_m, data = vals)\nunname(2.5 - predict(val_model, newdata = data.frame(claimed_m = 5)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.6757143\n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Task 3: Diagnostics and influence (Lecture 2)\n\nProduce the residual-versus-fitted plot and the normal Q--Q plot for the\nTask 1 model.\n\n1. Name two problems with the assumptions that you can see in the plots.\n2. Count the standardised residuals beyond $\\pm 3$ and the observations\n   with a Cook's distance above $4/n$.\n3. State the three-step rule for handling a flagged observation.\n4. Name one assumption these plots cannot assess and what would assess it.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nval_model <- lm(agreed_m ~ claimed_m, data = vals)\nold_par <- par(no.readonly = TRUE)\npar(mfrow = c(1, 2), mar = c(4.5, 4.4, 1.3, 0.7), las = 1)\nplot(fitted(val_model), residuals(val_model),\n     pch = 16, col = grDevices::adjustcolor(\"#0072B2\", alpha.f = 0.35),\n     bty = \"n\", xlab = \"Fitted agreed valuation ($ millions)\",\n     ylab = \"Residual ($ millions)\")\nabline(h = 0, lty = 2, lwd = 2, col = \"#D55E00\")\nqqnorm(rstandard(val_model), pch = 16,\n       col = grDevices::adjustcolor(\"#009E73\", alpha.f = 0.40),\n       bty = \"n\", main = \"\", xlab = \"Normal theoretical quantile\",\n       ylab = \"Standardised residual\")\nqqline(rstandard(val_model), col = \"#D55E00\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](t01-exam-prep_files/figure-html/iep01-task3-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(old_par)\nc(big_rstandard = sum(abs(rstandard(val_model)) > 3),\n  cooks_flagged = sum(cooks.distance(val_model) > 4 / nrow(vals)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbig_rstandard cooks_flagged \n           25            64 \n```\n\n\n:::\n:::\n\n\n\n\nThe spread of the residuals widens with the fitted value. This fan\nchallenges constant conditional variance. The Q--Q plot leaves the line at\nboth ends, with several extreme residuals on both sides. This challenges\nnormality and points to possibly influential deals. Twenty-five standardised\nresiduals lie beyond $\\pm3$, and 64 observations have a Cook's distance above\n$4/n$. The rule for flagged observations: investigate, report, never\nsilently delete. The plots cannot assess independence or the absence of\nconfounding. Those need knowledge of how the data were collected, for\nexample whether the same sharks or founders appear in several rows.\n:::\n\n### Task 4: Coefficient inference (Lecture 3)\n\nUse `summary()` and `confint()` on the Task 1 model.\n\n1. Test $H_0:\\beta_1=0$ against the two-sided alternative.\n2. Report the 95% confidence interval for $\\beta_1$, and verify it by hand\n   from the estimate and the standard error.\n3. Would robust standard errors ([Lecture 3](i03-inference-fit-ftest.qmd#i03-robust)) fix both\n   problems from Task 3?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nval_model <- lm(agreed_m ~ claimed_m, data = vals)\nsummary(val_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error    t value      Pr(>|t|)\n(Intercept) -0.06798986 0.06847892 -0.9928582  3.210545e-01\nclaimed_m    0.64874084 0.01106883 58.6096854 1.099793e-304\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(val_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept) -0.2023926 0.06641292\nclaimed_m    0.6270162 0.67046551\n```\n\n\n:::\n:::\n\n\n\n\nThe slope is $0.649$ with standard error $0.0111$, so $t \\approx 58.6$ on\n$872$ degrees of freedom and the p-value is far below 0.001: reject a zero\nslope. By hand, with one more digit to avoid rounding error,\n$0.6487 \\pm 1.96 \\times 0.01107 = 0.6487 \\pm 0.0217 = (0.627,\\; 0.670)$. This\nmatches `confint()`, in \\$ million agreed per \\$ million claimed. Robust\nstandard errors address the unequal variance only. They do not help with\ninfluential observations, with the selection of pitches that ended in a\ndeal, or with a relationship that is not linear.\n:::\n\n### Task 5: R² and F (Lecture 3)\n\n1. Calculate SST, SSE, SSR, and $R^2$ manually.\n2. Verify them against `summary()`.\n3. Verify $F = t^2$.\n4. Write one concluding sentence that does not overclaim.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nval_model <- lm(agreed_m ~ claimed_m, data = vals)\ny <- vals$agreed_m\nyhat <- fitted(val_model)\nSST <- sum((y - mean(y))^2)\nSSE <- sum((y - yhat)^2)\nSSR <- sum((yhat - mean(y))^2)\nc(R2_manual = 1 - SSE / SST,\n  R2_summary = summary(val_model)$r.squared,\n  F_summary = unname(summary(val_model)$fstatistic[\"value\"]),\n  t_squared = summary(val_model)$coefficients[\"claimed_m\", \"t value\"]^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   R2_manual   R2_summary    F_summary    t_squared \n   0.7975434    0.7975434 3435.0952236 3435.0952236 \n```\n\n\n:::\n:::\n\n\n\n\nThe sums (in squared \\$ millions) satisfy $\\text{SST}=\\text{SSR}+\\text{SSE}$,\nand $R^2 \\approx 0.798$. The overall F statistic is about 3435, equal to the\nsquared slope t statistic, as it must be in simple regression. A sentence\nthat does not overclaim: among these deals, the claimed valuation explains\nabout 80% of the variation in the agreed valuations, but this is an\nassociation in a selected set of deals, shaped partly by a few influential\nones, and not the effect of changing a claim.\n:::\n\n### Task 6: A new question: how much more equity do the sharks take?\n\nLecture 1 showed that the sharks usually pay the amount asked and take a\nlarger share of the company. Model that directly. Use all 882 deals and\nregress the equity agreed in the deal on the equity the founder first\noffered, both in percent of the company:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_deals <- subset(sharks, deal_on_show == 1)\nequity_model <- lm(deal_equity_pct ~ equity_offered_pct, data = all_deals)\nnrow(all_deals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 882\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(equity_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Estimate Std. Error  t value     Pr(>|t|)\n(Intercept)        8.315024  0.7477311 11.12034 5.684681e-27\nequity_offered_pct 1.207341  0.0511365 23.61017 7.368475e-96\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(equity_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      2.5 %   97.5 %\n(Intercept)        6.847480 9.782569\nequity_offered_pct 1.106978 1.307705\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(equity_model)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3878006\n```\n\n\n:::\n:::\n\n\n\n\n1. Interpret the slope and the intercept with units.\n2. A founder offers 10% of the company. Which agreed share does the model\n   fit?\n3. Compare the $R^2$ with the valuation model. What does the difference tell\n   a founder?\n4. Advise the founder in two sentences.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe slope is about 1.21 percentage points of agreed equity per percentage\npoint offered, with a 95% interval of about 1.11 to 1.31. The intercept is\nabout 8.3 percentage points. A founder who offers 10% is fitted to give up\n$8.3 + 1.21\\times10\\approx20.4$% of the company, about twice the offer. $R^2$\nis about 0.39, against 0.80 for the valuations. The offered share says much\nless about the agreed share than the claimed valuation says about the agreed\nvaluation, so single deals scatter widely around the line. Advice: expect to\ngive up roughly twice the share you offer, and decide before the pitch how\nfar you are willing to go. These are deals that happened on a television\nshow. They describe what founders who closed a deal gave up, not what would\nhappen to you if you offered a different share.\n:::\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n### Timed individual practice: 20 minutes\n\nFit `equity_offered_pct ~ season` using all 1,441 records.\n\n1. Make and read the scatterplot with the fitted line.\n2. Report the fitted equation and units.\n3. Report the standard error of the slope, its t value, its p-value, and its\n   95% interval.\n4. Report $R^2$ and the overall F-test.\n5. Inspect the residual plots and write a conclusion of about 120 words.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nseason_model <- lm(equity_offered_pct ~ season, data = sharks)\nsummary(season_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error   t value      Pr(>|t|)\n(Intercept) 20.4565874 0.46442667  44.04697 4.922706e-269\nseason      -0.8241241 0.04752298 -17.34159  2.514546e-61\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(season_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept) 19.5455616 21.3676132\nseason      -0.9173458 -0.7309023\n```\n\n\n:::\n\n```{.r .cell-code}\nc(r_squared = summary(season_model)$r.squared,\n  F = unname(summary(season_model)$fstatistic[\"value\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  r_squared           F \n  0.1728605 300.7308055 \n```\n\n\n:::\n:::\n\n\n\n\nThe fitted equation is\n$\\widehat{equity}=20.457-0.824\\,season$: one later season is associated\nwith about 0.824 percentage points less initial equity offered on average.\nThe standard error is about 0.048, $t\\approx-17.3$, and the p-value is below\n0.001. The 95% interval $(-0.917,\\,-0.731)$ excludes zero.\n$R^2\\approx0.173$, so the season explains about 17.3% of the variation in\nthe equity offered, and the overall F-test ($F\\approx300.7=t^2$) reaches the\nsame conclusion as the slope test. The residual plot shows sixteen vertical\nstripes (the season takes whole numbers only) with broadly similar spread.\nThe Q--Q plot bends upwards at the right end because of some very high\noffers. This is a trend over time among recorded pitches, not a causal\neffect of a later season.\n:::\n\n### Check your understanding\n\nComplete from memory:\n\n1. A residual is ...\n2. The slope's standard error estimates ...\n3. A fan in the residual plot challenges ...\n4. $R^2$ is the proportion of ...\n5. In simple regression, the overall F statistic equals ...\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. The observed outcome minus the fitted value, $e_i=Y_i-\\widehat Y_i$.\n2. How much the estimated slope would vary from sample to sample, under the\n   model assumptions.\n3. Constant conditional variance (homoskedasticity), and with it the\n   usual standard errors.\n4. The variation of the outcome in the sample that the fitted values\n   explain, $\\text{SSR}/\\text{SST}$.\n5. The squared slope t statistic, $F=t^2$.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA3 venture, or any business you know well. Imagine the\none simple regression you would show an investor (revenue on customers,\norders on ad spend), and write two sentences. First name the number from\nthis tutorial you would put in the headline, slope, interval, or $R^2$, and\nsay why. Then name the limit from Task 3 or Task 5 that you would state\nopenly next to it. There is no wrong answer.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"Headline: the slope with its 95% interval. Each extra €100 of ads is associated with roughly 12 to 19 more orders. An investor asks what money buys, and the interval shows how uncertain the number is. Limit: the fan in my residual plot means that busy weeks vary more, so the interval rests on an assumption that my own residual plot puts in doubt.\"\n:::\n\nYou can discuss this task, and any other task in this tutorial, with\n**Tilly**, the course AI assistant: paste your two sentences and\nask it to play the sceptical investor.\n::::\n\n[Continue to Lecture 4: Multiple regression and what controls do](i04-multiple-regression.qmd).\n\n:::\n",
    "supporting": [
      "t01-exam-prep_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}