<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 1: Introduction to Data Analysis – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/b02-probability-foundations.html" rel="next">
<link href="../basic/overview.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ecf4e518a83458a2bb67b2a9bf74271b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b01-introduction-data-analysis.html"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution, confidence intervals, and the two-sided test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Inference and tests against zero</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals betray it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/reading-ladder.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reading research papers</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-class" id="toc-in-class" class="nav-link" data-scroll-target="#in-class">In class</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b01-introduction-data-analysis.html"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b01" class="quarto-section-identifier"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Lecture 1, you can</span></p>
<ul>
<li>organise a reproducible R analysis and verify AI-assisted work;</li>
<li>distinguish categorical, discrete, continuous, and identifier variables;</li>
<li>identify a sample, a target population, sampling variability, and selection bias;</li>
<li>inspect, validate, and qualify a real dataset;</li>
<li>describe one variable with frequency tables, bar charts, and histograms;</li>
<li>read a histogram by hand, including locating the median interval from cumulative bar counts.</li>
</ul>
</div>
<div class="driving-question">
<p><span class="label">Driving question</span></p>
<p class="dq-context">
Shark Tank turns a business decision — fund this venture or not — into recorded data: 1,441 pitches, each with an ask, an equity offer, and an outcome. Learning from records like these is how investors, founders, and analysts figure out what works.
</p>
<p>1,441 televised pitches are on our screen. What can this dataset tell us about entrepreneurship — and what can it never tell us?</p>
</div>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p><span class="time-budget">Total preparation time: about 30 minutes.</span></p>
<p><strong>Read (5 minutes).</strong> Read <em>How to use this book</em> at the start of this book and locate the sections called <strong>Before class</strong>, <strong>In class</strong>, and <strong>After class</strong> in this chapter.</p>
<p><strong>Set up (15 minutes).</strong> Open RStudio through an R project. Create a new script and save it before writing code. Then <a href="../data/shark_tank_teaching.csv" download="shark_tank_teaching.csv">download <code>shark_tank_teaching.csv</code></a> and place it in a folder called <code>data</code> inside your project. Keep the downloaded file unchanged. Run the following commands and bring the output to class:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(sharks)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(sharks)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  sharks[<span class="fu">c</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"pitch_id"</span>, <span class="st">"startup_name"</span>, <span class="st">"season"</span>, <span class="st">"industry"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"pitcher_gender_group"</span>, <span class="st">"deal_on_show"</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  )],</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="dv">3</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Predict (5 minutes).</strong> Write one sentence answering: <strong>what do you think one row in this dataset represents?</strong> Commit to an answer; the lecture resolves it. It is fine if your answer changes during class.</p>
<div class="r-refresher">
<p><span class="label">R reactivation</span><br> You used scripts, CSV files, data frames, summaries, and plots in <a href="https://walshc.github.io/ebi-prog/">Programming for E&amp;BI</a>. If the commands above feel unfamiliar, revisit its chapters on <a href="https://walshc.github.io/ebi-prog/r-scripts.html">R scripts</a>, <a href="https://walshc.github.io/ebi-prog/reading-csv-datasets.html">reading CSV files</a>, and <a href="https://walshc.github.io/ebi-prog/dataframes-summary-statistics.html">summarising data frames</a>.</p>
</div>
<p>If percentages, units, or graph axes are unfamiliar, review <a href="../resources/math-refresher.html">Mathematics Refresher: numbers, percentages, and graphs</a>.</p>
</section>
<section id="in-class" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-class">In class</h2>
<p>The session opens with the usual four-minute entry quiz — in this first week, on the preparation reading and setup — then turns to the driving question: what can 1,441 recorded pitches tell us about entrepreneurship, and what can they never tell us? The hook for the whole session is a graph the class builds itself: the anonymous class map from the Mentimeter risk activity below.</p>
<section id="how-the-course-works" class="level3">
<h3 class="anchored" data-anchor-id="how-the-course-works">How the course works</h3>
<p>Every lecture uses the same rhythm:</p>
<ol type="1">
<li><strong>Prepare before class.</strong> Encounter the question, notation, data, or short explanation before the lecture.</li>
<li><strong>Participate during class.</strong> Predict results, discuss choices, run code, and revise your reasoning with the teaching team.</li>
<li><strong>Practise after class.</strong> Retrieve ideas from memory, reproduce the analysis, and explain results without copying a model answer.</li>
<li><strong>Use the exam preparation sessions.</strong> Bring your attempts and questions; work in groups with classmates and teaching assistants.</li>
</ol>
<p>Complete the <strong>Before class</strong> section before each lecture; use <strong>After class</strong> to check that you can reproduce and explain the analysis independently.</p>
</section>
<section id="data-analysis-with-r-and-ai" class="level3">
<h3 class="anchored" data-anchor-id="data-analysis-with-r-and-ai">Data analysis with R and AI</h3>
<section id="reproducible-scripts" class="level4">
<h4 class="anchored" data-anchor-id="reproducible-scripts">Reproducible scripts</h4>
<p>A reproducible script recreates the analysis in a new R session, without depending on objects created earlier at the Console.</p>
<p>Use these habits from the start:</p>
<ul>
<li>open the project rather than changing the working directory with <code>setwd()</code>;</li>
<li>keep downloaded data unchanged;</li>
<li>use relative paths such as <code>data/shark_tank_teaching.csv</code>;</li>
<li>record importing, checking, transforming, plotting, and modelling in scripts;</li>
<li>give objects meaningful names;</li>
<li>keep code and written interpretation together; and</li>
<li>restart R and run the complete script before sharing the analysis.</li>
</ul>
</section>
<section id="the-analysis-cycle" class="level4">
<h4 class="anchored" data-anchor-id="the-analysis-cycle">The analysis cycle</h4>
<p>Data analysis is iterative:</p>
<ol type="1">
<li>Ask a focused question.</li>
<li>Define the unit and decide how each idea will be measured.</li>
<li>Obtain or create the data and document their provenance.</li>
<li>Inspect and validate before calculating.</li>
<li>Summarise and visualise patterns.</li>
<li>Interpret the result in context and state its limits.</li>
</ol>
</section>
<section id="use-ai-as-a-fallible-assistant" class="level4">
<h4 class="anchored" data-anchor-id="use-ai-as-a-fallible-assistant">Use AI as a fallible assistant</h4>
<p>AI systems generate plausible responses; they do not certify that a calculation, source, or interpretation is correct. Use:</p>
<p><strong>Attempt → Ask → Verify → Explain</strong></p>
<ol type="1">
<li><strong>Attempt</strong> the question and identify where you are stuck.</li>
<li><strong>Ask</strong> for a hint, diagnostic question, counterexample, or code review.</li>
<li><strong>Verify</strong> every claim against the data, R output, course notation, and reliable sources.</li>
<li><strong>Explain</strong> the result in your own words and ask for feedback on that explanation.</li>
</ol>
<p>Do not share confidential, personal, or assessment-restricted material. You remain responsible for every submitted claim.</p>
</section>
</section>
<section id="collecting-our-own-data" class="level3">
<h3 class="anchored" data-anchor-id="collecting-our-own-data">Collecting our own data</h3>
<p>The class creates its first dataset through an anonymous Mentimeter activity.</p>
<section id="a-choice-with-money-at-risk" class="level4">
<h4 class="anchored" data-anchor-id="a-choice-with-money-at-risk">A choice with money at risk</h4>
<p>Imagine receiving EUR 100 and making one choice:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Choice</th>
<th style="text-align: right;">Amount placed at risk</th>
<th>Possible final amounts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Keep it</td>
<td style="text-align: right;">EUR 0</td>
<td>EUR 100 for certain</td>
</tr>
<tr class="even">
<td>Split it</td>
<td style="text-align: right;">EUR 50</td>
<td>EUR 50 or EUR 150, each with 50% chance</td>
</tr>
<tr class="odd">
<td>Go all-in</td>
<td style="text-align: right;">EUR 100</td>
<td>EUR 0 or EUR 200, each with 50% chance</td>
</tr>
</tbody>
</table>
<p>All three choices have the same average monetary payoff across many repetitions: EUR 100. The options differ in how uncertain the one-time result is.</p>
<p>Next, answer:</p>
<blockquote class="blockquote">
<p>How do you see yourself in general? Use 0 for “not at all willing to take risks” and 10 for “very willing to take risks.”</p>
</blockquote>
<p>Finally, give your current belief:</p>
<blockquote class="blockquote">
<p>What is the probability that you will start or co-found a business at least once during the next ten years?</p>
</blockquote>
<p>Before the class map appears on screen, <strong>predict its shape</strong>: will students who place more money at risk also report a higher founder probability? The map places general risk willingness on the horizontal axis and the subjective founder probability on the vertical axis. One anonymous point represents one responding student.</p>
</section>
<section id="from-ideas-to-variables" class="level4">
<h4 class="anchored" data-anchor-id="from-ideas-to-variables">From ideas to variables</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>What is recorded</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>respondent_id</code></td>
<td>anonymous row label</td>
<td>identifier</td>
</tr>
<tr class="even">
<td><code>amount_at_risk</code></td>
<td>0, 50, or 100 euros</td>
<td>discrete quantitative</td>
</tr>
<tr class="odd">
<td><code>risk_willingness</code></td>
<td>one selected point from 0 to 10</td>
<td>ordered discrete rating</td>
</tr>
<tr class="even">
<td><code>founder_probability</code></td>
<td>belief from 0% to 100%</td>
<td>continuous concept recorded on a finite-precision slider</td>
</tr>
</tbody>
</table>
<p><strong>Risk attitude</strong> is a theoretical construct. The monetary choice and the 0–10 response are two imperfect measurements of it. They may disagree because risk taking depends on context, hypothetical choices differ from real stakes, and self-perceptions are imperfect. A single response is not a diagnosis of a permanent personality type.</p>
<p>The first two responses offer separate allowable points. Founder probability is conceptualised on the continuum from 0% to 100%, although the software stores a rounded value.</p>
</section>
</section>
<section id="sample-and-target-population" class="level3">
<h3 class="anchored" data-anchor-id="sample-and-target-population">Sample and target population</h3>
<p>The <strong>sample</strong> consists of students who are present and respond. Plausible target populations include:</p>
<ul>
<li>the responding students;</li>
<li>everyone attending this lecture;</li>
<li>all students enrolled in QM Basic;</li>
<li>all first-year business students in the Netherlands; or</li>
<li>all young adults in the Netherlands.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: which of the five candidate populations can our responses describe directly?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Only the first: the responding students. Everyone else — absent classmates, other QM Basic students, Dutch first-years, young adults — enters the picture only through assumptions, because attendance and participation were not random. The data describe the respondents; they do not automatically represent wider groups.</p>
</div>
</div>
</div>
</section>
<section id="sampling-variability-versus-selection-bias" class="level3">
<h3 class="anchored" data-anchor-id="sampling-variability-versus-selection-bias">Sampling variability versus selection bias</h3>
<p>Two uncertainties must not be confused:</p>
<ul>
<li><strong>Sampling variability:</strong> even a genuinely random sample can contain an unusual number of highly risk-tolerant students by chance. Larger random samples usually reduce this chance variation.</li>
<li><strong>Selection bias:</strong> a convenience sample can systematically exclude certain people. Collecting more responses from the same selected group does not necessarily repair that bias.</li>
</ul>
<div id="exm-b01-bias-contrast" class="theorem example">
<p><span class="theorem-title"><strong>Example 1.1 (Worked example: two scenarios, classified aloud)</strong></span> <em>Scenario 1.</em> A researcher draws 40 students <strong>at random</strong> from the full programme enrolment list. By chance, the sample contains an unusually large number of students who chose “go all-in.”</p>
<p><em>Scenario 2.</em> A survey about founding a business is shared <strong>in the group chat of the entrepreneurship club</strong>, and 400 members respond.</p>
<p>Scenario 1 is sampling variability: the selection mechanism was random, so the oddity is chance variation, and a larger random sample would usually tame it. Scenario 2 is selection bias: club members are systematically more interested in founding than the average student, and collecting 4,000 responses from the same chat would not repair the distortion — it would make a biased estimate more precise.</p>
</div>
<p>A probability sample of Dutch students would require a defined population, a suitable sampling frame, and random selection. Non-response and measurement error could still remain.</p>
</section>
<section id="meet-the-shark-tank-data" class="level3">
<h3 class="anchored" data-anchor-id="meet-the-shark-tank-data">Meet the Shark Tank data</h3>
<p>The first block used data the class created; this block turns to the data the whole course runs on.</p>
<section id="context-and-unit-of-observation" class="level4">
<h4 class="anchored" data-anchor-id="context-and-unit-of-observation">Context and unit of observation</h4>
<p><em>Shark Tank US</em> is a television programme in which entrepreneurs present a venture or product to a panel of investors known as sharks. Entrepreneurs may ask for money in exchange for an ownership share. The investors question them, negotiate, and may announce a deal during the episode.</p>
<p>The recorded outcome is an <strong>on-air agreement</strong>. It does not establish that an investment was completed or that the venture later succeeded.</p>
<p>The teaching file contains 1,441 televised pitches from completed Seasons 1–16 and 19 variables. The table below introduces the variables used most often in this course.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Meaning</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>pitch_id</code></td>
<td>row identifier</td>
<td>identifier</td>
</tr>
<tr class="even">
<td><code>startup_name</code></td>
<td>venture or product name</td>
<td>categorical label</td>
</tr>
<tr class="odd">
<td><code>deal_on_show</code></td>
<td>1 for an on-air agreement; 0 otherwise</td>
<td>binary categorical, stored as 0/1</td>
</tr>
<tr class="even">
<td><code>season</code></td>
<td>television season, 1–16</td>
<td>ordered discrete/time index</td>
</tr>
<tr class="odd">
<td><code>episode</code></td>
<td>episode number within season</td>
<td>discrete identifier within season</td>
</tr>
<tr class="even">
<td><code>industry</code></td>
<td>source industry category</td>
<td>categorical</td>
</tr>
<tr class="odd">
<td><code>description_words</code></td>
<td>words in the written dataset description</td>
<td>discrete quantitative count</td>
</tr>
<tr class="even">
<td><code>pitcher_gender_group</code></td>
<td><code>all_women</code>, <code>all_men</code>, <code>mixed</code>, or <code>unknown</code>, based on the source classification</td>
<td>categorical</td>
</tr>
<tr class="odd">
<td><code>women_represented</code></td>
<td>1 for <code>all_women</code> or <code>mixed</code>; 0 for <code>all_men</code>; missing for <code>unknown</code></td>
<td>binary categorical, stored as 0/1</td>
</tr>
<tr class="even">
<td><code>multiple_entrepreneurs</code></td>
<td>source indicator for more than one entrepreneur</td>
<td>binary categorical, with missing values</td>
</tr>
<tr class="odd">
<td><code>ask_amount_usd</code></td>
<td>amount requested</td>
<td>quantitative, USD</td>
</tr>
<tr class="even">
<td><code>equity_offered_pct</code></td>
<td>ownership percentage initially offered</td>
<td>quantitative, percentage points</td>
</tr>
<tr class="odd">
<td><code>requested_valuation_usd</code></td>
<td>valuation implied by the initial ask</td>
<td>quantitative, USD</td>
</tr>
<tr class="even">
<td><code>deal_amount_usd</code>, <code>deal_equity_pct</code>, <code>deal_valuation_usd</code></td>
<td>recorded deal terms</td>
<td>quantitative; structurally missing without a deal</td>
</tr>
</tbody>
</table>
<p>Gender describes the people presenting the pitch, not necessarily every founder or employee. <code>women_represented</code> is not the share of women: the source does not report the presenter counts needed to calculate that share for mixed teams. Names were not used to infer gender.</p>
<p>Note carefully what <code>description_words</code> measures: the length of the <strong>written description in the source dataset</strong>, not anything about the pitch itself. It counts words typed by whoever compiled the file, not words spoken in the tank. The file also does not measure the spoken pitch, completed investment, or later venture performance.</p>
</section>
<section id="inspect-and-validate" class="level4">
<h4 class="anchored" data-anchor-id="inspect-and-validate">Inspect and validate</h4>
<p>This is the live-coding part of the lecture: each output appears on screen, and you read it <strong>before</strong> the interpretation is given. Run the code yourself — everything on this page starts from the visible import below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(sharks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1441   19</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(sharks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "pitch_id"                "startup_name"           
 [3] "season"                  "episode"                
 [5] "industry"                "business_description"   
 [7] "description_words"       "pitcher_gender_group"   
 [9] "women_represented"       "multiple_entrepreneurs" 
[11] "pitcher_state"           "ask_amount_usd"         
[13] "equity_offered_pct"      "requested_valuation_usd"
[15] "deal_on_show"            "deal_amount_usd"        
[17] "deal_equity_pct"         "deal_valuation_usd"     
[19] "number_sharks_in_deal"  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sharks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1441 obs. of  19 variables:
 $ pitch_id               : int  1 2 3 4 5 6 7 8 9 10 ...
 $ startup_name           : chr  "AvaTheElephant" "MrTod'sPieFactory" "Wispots" "CollegeFoxesPackingBoxes" ...
 $ season                 : int  1 1 1 1 1 1 1 1 1 1 ...
 $ episode                : int  1 1 1 1 1 2 2 2 2 2 ...
 $ industry               : chr  "Health/Wellness" "Food and Beverage" "Business Services" "Lifestyle/Home" ...
 $ business_description   : chr  "Ava The Elephant - Baby and Child Care" "Mr. Tod's Pie Factory - Specialty Food" "Wispots - Consumer Services" "College Foxes Packing Boxes - Consumer Services" ...
 $ description_words      : int  8 7 4 7 4 6 4 3 7 6 ...
 $ pitcher_gender_group   : chr  "all_women" "all_men" "all_men" "all_men" ...
 $ women_represented      : int  1 0 0 0 0 1 0 0 0 1 ...
 $ multiple_entrepreneurs : int  0 0 0 0 0 0 0 0 0 0 ...
 $ pitcher_state          : chr  "GA" "NJ" "NC" "FL" ...
 $ ask_amount_usd         : num  50000 460000 1200000 250000 1000000 500000 250000 500000 200000 100000 ...
 $ equity_offered_pct     : num  15 10 10 25 15 15 10 10 20 20 ...
 $ requested_valuation_usd: num  333333 4600000 12000000 1000000 6666667 ...
 $ deal_on_show           : int  1 1 0 0 0 1 1 0 0 0 ...
 $ deal_amount_usd        : num  50000 460000 NA NA NA 500000 250000 NA NA NA ...
 $ deal_equity_pct        : num  55 50 NA NA NA 50 100 NA NA NA ...
 $ deal_valuation_usd     : num  90909 920000 NA NA NA ...
 $ number_sharks_in_deal  : int  1 2 NA NA NA 2 5 NA NA NA ...</code></pre>
</div>
</div>
<p>There are 1,441 rows and 19 columns. This resolves the prediction from your prep: <strong>one row represents one recorded televised pitch</strong> from Seasons 1–16 of <em>Shark Tank US</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(sharks))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               pitch_id            startup_name                  season 
                      0                       0                       0 
                episode                industry    business_description 
                      0                       0                       0 
      description_words    pitcher_gender_group       women_represented 
                      0                       0                       7 
 multiple_entrepreneurs           pitcher_state          ask_amount_usd 
                    427                       0                       0 
     equity_offered_pct requested_valuation_usd            deal_on_show 
                      0                       0                       0 
        deal_amount_usd         deal_equity_pct      deal_valuation_usd 
                    559                     559                     559 
  number_sharks_in_deal 
                    559 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">unique</span>(sharks<span class="sc">$</span>deal_on_show))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(sharks<span class="sc">$</span>season)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1 16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(sharks<span class="sc">$</span>episode)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1 29</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(sharks<span class="sc">$</span>description_words)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1 13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(sharks<span class="sc">$</span>pitcher_gender_group, <span class="at">useNA =</span> <span class="st">"ifany"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  all_men all_women     mixed   unknown 
      773       385       276         7 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anyDuplicated</span>(sharks<span class="sc">$</span>pitch_id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Pitch identifiers are unique, deal status contains only 0 and 1, and seasons run from 1 to 16. Written descriptions contain from 1 to 13 words. Missing deal terms are expected for pitches without a deal; seven records have an unknown source gender classification, and the source does not report <code>multiple_entrepreneurs</code> consistently. Missing does not mean zero. These checks establish internal plausibility, not that the source captured every pitch or measured every concept well.</p>
</section>
<section id="summarise-in-context" class="level4">
<h4 class="anchored" data-anchor-id="summarise-in-context">Summarise in context</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>deal_count <span class="ot">&lt;-</span> <span class="fu">sum</span>(sharks<span class="sc">$</span>deal_on_show)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>pitch_count <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sharks)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>deal_rate <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>deal_on_show)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">on_air_deals =</span> deal_count,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">recorded_pitches =</span> pitch_count,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">recorded_deal_rate =</span> deal_rate</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      on_air_deals   recorded_pitches recorded_deal_rate 
       882.0000000       1441.0000000          0.6120749 </code></pre>
</div>
</div>
<p>Because a 0/1 variable has mean equal to its proportion of 1s, <code>mean(deal_on_show)</code> is 61.2%. A defensible sentence is:</p>
<blockquote class="blockquote">
<p>In this dataset, 882 of 1,441 recorded pitches (61.2%) reached an on-air agreement.</p>
</blockquote>
<p>This sentence names the dataset and outcome. It does not claim that a randomly selected entrepreneur has the same chance of completed investment.</p>
</section>
</section>
<section id="describing-one-variable" class="level3">
<h3 class="anchored" data-anchor-id="describing-one-variable">Describing one variable</h3>
<p>Before comparing groups or fitting models, learn to describe <strong>one</strong> variable well. The right tool depends on the variable’s type.</p>
<section id="frequency-tables-and-bar-charts-for-discrete-categories" class="level4">
<h4 class="anchored" data-anchor-id="frequency-tables-and-bar-charts-for-discrete-categories">Frequency tables and bar charts for discrete categories</h4>
<p>An <strong>empirical distribution</strong> records how often values occur in a dataset. For a categorical or discrete variable, a <strong>frequency table</strong> gives counts and a <strong>relative-frequency table</strong> gives proportions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>season_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(sharks<span class="sc">$</span>season)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>season_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16 
 64  36  60 103 116 116 116  96  96  92  96 100  96  87  87  80 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(season_counts), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3     4     5     6     7     8     9    10    11    12    13 
0.044 0.025 0.042 0.071 0.080 0.080 0.080 0.067 0.067 0.064 0.067 0.069 0.067 
   14    15    16 
0.060 0.060 0.056 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>season_counts <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">table</span>(sharks<span class="sc">$</span>season))</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(season_counts) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"season"</span>, <span class="st">"pitches"</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>season_counts<span class="sc">$</span>season <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">as.character</span>(season_counts<span class="sc">$</span>season))</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(season_counts, <span class="fu">aes</span>(<span class="at">x =</span> season, <span class="at">y =</span> pitches)) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Season"</span>, <span class="at">y =</span> <span class="st">"Number of recorded pitches"</span>) <span class="sc">+</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b01-season-bar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b01-season-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b01-introduction-data-analysis_files/figure-html/fig-b01-season-bar-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b01-season-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: Number of recorded pitches per season. Later seasons contain more records, so an overall percentage gives those seasons more weight.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-b01-season-bar" class="quarto-xref">Figure&nbsp;<span>1.1</span></a> the horizontal axis lists the discrete season categories; each bar’s height on the vertical count scale is the number of recorded pitches in that season. The later seasons contain more records, so an overall percentage gives those seasons more weight.</p>
</section>
<section id="histograms-for-quantitative-variables" class="level4">
<h4 class="anchored" data-anchor-id="histograms-for-quantitative-variables">Histograms for quantitative variables</h4>
<p>For a quantitative variable, a <strong>histogram</strong> groups nearby values into intervals and counts how many observations fall in each.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>word_median <span class="ot">&lt;-</span> <span class="fu">median</span>(sharks<span class="sc">$</span>description_words)   <span class="co"># 5 words</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sharks, <span class="fu">aes</span>(<span class="at">x =</span> description_words)) <span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="fl">13.5</span>, <span class="at">by =</span> <span class="dv">1</span>),</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> word_median, <span class="at">colour =</span> <span class="st">"#C98B2E"</span>,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> word_median <span class="sc">+</span> <span class="fl">0.4</span>, <span class="at">y =</span> <span class="dv">300</span>,</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"median = 5 words"</span>, <span class="at">hjust =</span> <span class="dv">0</span>,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Words in the written dataset description"</span>,</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of recorded pitches"</span>) <span class="sc">+</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b01-word-hist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b01-word-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b01-introduction-data-analysis_files/figure-html/fig-b01-word-hist-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b01-word-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.2: Distribution of the number of words in the written dataset description. The dashed vertical line marks the median, 5 words.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-b01-word-hist" class="quarto-xref">Figure&nbsp;<span>1.2</span></a> the horizontal axis measures description length in words and the vertical axis counts pitches in each one-word interval. The distribution is mildly right-skewed: most descriptions contain 3–7 words, with a small number extending farther to the right. The median is 5 words. Remember what this variable measures: the source text about the pitch, not the pitch itself.</p>
<p>The histogram the rest of this section works with shows the equity initially offered:</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>equity_median <span class="ot">&lt;-</span> <span class="fu">median</span>(sharks<span class="sc">$</span>equity_offered_pct)   <span class="co"># 10%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sharks, <span class="fu">aes</span>(<span class="at">x =</span> equity_offered_pct)) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="at">by =</span> <span class="dv">5</span>),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> equity_median, <span class="at">colour =</span> <span class="st">"#C98B2E"</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> equity_median <span class="sc">+</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="dv">530</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"median = 10%"</span>, <span class="at">hjust =</span> <span class="dv">0</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Equity initially offered (%)"</span>,</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of recorded pitches"</span>) <span class="sc">+</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b01-equity-hist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b01-equity-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b01-introduction-data-analysis_files/figure-html/fig-b01-equity-hist-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b01-equity-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.3: Distribution of the equity initially offered across the 1,441 recorded pitches, in 5-point intervals. The dashed vertical line marks the median, 10%.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each bar counts pitches within an offered-equity interval. Most initial offers are below 20%, while a small number are much larger. Changing the interval width can reveal or conceal patterns, so a histogram is an analytical choice rather than decoration.</p>
</section>
</section>
<section id="reading-a-histogram-by-hand" class="level3">
<h3 class="anchored" data-anchor-id="reading-a-histogram-by-hand">Reading a histogram by hand</h3>
<p>The exam gives you a printed histogram and no computer, so this skill is practised by hand. Every graph in this course is read with the same <strong>five-step sequence</strong>:</p>
<ol type="1">
<li><strong>Unit and variables.</strong> What does one observation represent, and what is on each axis, in which units?</li>
<li><strong>Scales.</strong> Read the axis scales, including where they start and how wide each interval is.</li>
<li><strong>One element.</strong> Put one bar (or point) into a full sentence.</li>
<li><strong>Pattern.</strong> Describe the overall shape: where values concentrate, whether the distribution is symmetric or skewed, whether there are outliers.</li>
<li><strong>Limits.</strong> State one thing the graph cannot tell you.</li>
</ol>
<div id="exm-b01-histogram-read" class="theorem example">
<p><span class="theorem-title"><strong>Example 1.2 (Worked example: the five steps and the median interval)</strong></span> Apply the sequence to <a href="#fig-b01-equity-hist" class="quarto-xref">Figure&nbsp;<span>1.3</span></a>.</p>
<ol type="1">
<li>One observation is one recorded pitch; the horizontal axis is equity initially offered in percentage points, the vertical axis is the number of pitches.</li>
<li>The horizontal axis runs from 0 to 100 in intervals of width 5; the vertical axis counts pitches.</li>
<li>The tallest bar covers 5–10%: 560 pitches offered more than 5% and at most 10% equity.</li>
<li>The distribution is strongly right-skewed: most offers are at or below 20%, with a thin tail stretching towards 100%.</li>
<li>The histogram cannot say why offers cluster there, and it hides the exact values inside each interval.</li>
</ol>
<p><strong>Locating the median interval.</strong> With 1,441 ordered observations, the median is the 721st value. Add bar counts from the left until the running total reaches 721:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Interval (%)</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Cumulative count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0–5</td>
<td style="text-align: right;">293</td>
<td style="text-align: right;">293</td>
</tr>
<tr class="even">
<td style="text-align: right;">5–10</td>
<td style="text-align: right;">560</td>
<td style="text-align: right;">853</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10–15</td>
<td style="text-align: right;">194</td>
<td style="text-align: right;">1,047</td>
</tr>
<tr class="even">
<td style="text-align: right;">15–20</td>
<td style="text-align: right;">241</td>
<td style="text-align: right;">1,288</td>
</tr>
</tbody>
</table>
<p>After the first bar only 293 observations are covered — not yet 721. After the second bar the running total is <span class="math inline">\(293+560=853\ge721\)</span>, so the 721st observation lies in the <strong>5–10% interval</strong>: the median interval. (R confirms: the exact median is 10%, which this histogram counts in the 5–10 bar because each bar includes its right endpoint.) The same cumulative-count reading is tested in Mock Exam Question 1.</p>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it: locate the upper-quartile interval
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In class this is the pair task. The upper quartile is the value with three-quarters of the observations at or below it.</p>
<p><em>Step 1 (given).</em> Three-quarters of 1,441 observations is about 1,081, so you are looking for the interval containing the 1,081st ordered value.</p>
<p><em>Step 2 (you).</em> Extend the cumulative counts in the table above until the running total first reaches 1,081.</p>
<p><em>Step 3 (you).</em> Name the upper-quartile interval.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Through 10–15% the cumulative count is <span class="math inline">\(293+560+194=1{,}047\)</span>, still below 1,081. Adding the 15–20% bar gives <span class="math inline">\(1{,}047+241=1{,}288\ge1{,}081\)</span>, so the upper quartile lies in the <strong>15–20% interval</strong>. (R confirms: <code>quantile(sharks$equity_offered_pct, 0.75)</code> returns 20, on the upper edge of that bar.)</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="comparing-raw-observations-and-group-means" class="level3">
<h3 class="anchored" data-anchor-id="comparing-raw-observations-and-group-means">Comparing raw observations and group means</h3>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>sharks<span class="sc">$</span>deal_status <span class="ot">&lt;-</span> <span class="fu">factor</span>(sharks<span class="sc">$</span>deal_on_show, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No on-air deal"</span>, <span class="st">"On-air deal"</span>))</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>sharks<span class="sc">$</span>season_jittered <span class="ot">&lt;-</span> <span class="fu">jitter</span>(sharks<span class="sc">$</span>season, <span class="at">amount =</span> <span class="fl">0.16</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sharks, <span class="fu">aes</span>(<span class="at">x =</span> season_jittered, <span class="at">y =</span> equity_offered_pct,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">colour =</span> deal_status, <span class="at">shape =</span> deal_status)) <span class="sc">+</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.45</span>, <span class="at">size =</span> <span class="fl">1.6</span>) <span class="sc">+</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"No on-air deal"</span> <span class="ot">=</span> <span class="st">"#009E73"</span>,</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"On-air deal"</span> <span class="ot">=</span> <span class="st">"#D55E00"</span>)) <span class="sc">+</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"No on-air deal"</span> <span class="ot">=</span> <span class="dv">16</span>,</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"On-air deal"</span> <span class="ot">=</span> <span class="dv">17</span>)) <span class="sc">+</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">15</span>, <span class="at">by =</span> <span class="dv">2</span>), <span class="dv">16</span>)) <span class="sc">+</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Season"</span>, <span class="at">y =</span> <span class="st">"Equity initially offered (%)"</span>,</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">colour =</span> <span class="cn">NULL</span>, <span class="at">shape =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>),</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"top"</span></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b01-raw-points" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b01-raw-points-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b01-introduction-data-analysis_files/figure-html/fig-b01-raw-points-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b01-raw-points-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.4: Equity initially offered by season, one point per recorded pitch, jittered horizontally to reduce overlap. Colour and shape mark on-air deal status.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Season is a discrete ordered time index, so the points in <a href="#fig-b01-raw-points" class="quarto-xref">Figure&nbsp;<span>1.4</span></a> are moved slightly left or right only to reduce overlap. The vertical spread within every season warns us that a group mean will not describe every pitch.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>season_means <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> deal_on_show,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> sharks,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">FUN =</span> mean</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>season_means<span class="sc">$</span>deal_status <span class="ot">&lt;-</span> <span class="fu">factor</span>(season_means<span class="sc">$</span>deal_on_show,</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No on-air deal"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>                                              <span class="st">"On-air deal"</span>))</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(season_means, <span class="fu">aes</span>(<span class="at">x =</span> season, <span class="at">y =</span> equity_offered_pct,</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>                         <span class="at">colour =</span> deal_status, <span class="at">shape =</span> deal_status,</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>                         <span class="at">linetype =</span> deal_status)) <span class="sc">+</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.4</span>) <span class="sc">+</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"No on-air deal"</span> <span class="ot">=</span> <span class="st">"#009E73"</span>,</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"On-air deal"</span> <span class="ot">=</span> <span class="st">"#D55E00"</span>)) <span class="sc">+</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"No on-air deal"</span> <span class="ot">=</span> <span class="dv">16</span>,</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"On-air deal"</span> <span class="ot">=</span> <span class="dv">17</span>)) <span class="sc">+</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"No on-air deal"</span> <span class="ot">=</span> <span class="st">"solid"</span>,</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"On-air deal"</span> <span class="ot">=</span> <span class="st">"dashed"</span>)) <span class="sc">+</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>) <span class="sc">+</span></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>),</span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Season"</span>, <span class="at">y =</span> <span class="st">"Mean equity initially offered (%)"</span>,</span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">colour =</span> <span class="cn">NULL</span>, <span class="at">shape =</span> <span class="cn">NULL</span>, <span class="at">linetype =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>),</span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"top"</span></span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b01-season-means" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b01-season-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b01-introduction-data-analysis_files/figure-html/fig-b01-season-means-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b01-season-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.5: Mean equity initially offered per season, separately for pitches with and without an on-air deal.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Mean initially offered equity in <a href="#fig-b01-season-means" class="quarto-xref">Figure&nbsp;<span>1.5</span></a> is lower in later seasons for both deal groups. The graph describes selected televised pitches; it does not establish why the offers changed or what would happen if an entrepreneur changed only the offered equity.</p>
<p>A clear graph matches the variable types, labels its axes and groups, and makes the claim inspectable. Colour is reinforced here by point shape and line type, so the groups remain distinguishable without relying on colour alone.</p>
<div class="caveat-box">
<p><span class="label">What these records can and cannot say</span></p>
<p>The Shark Tank file describes <strong>1,441 recorded televised pitches</strong>, nothing more, for three structural reasons:</p>
<ul>
<li><strong>Selection into television.</strong> Producers choose which pitches are filmed and aired. The file is not a random sample of startups, entrepreneurs, or even Shark Tank applicants.</li>
<li><strong>On-air deal is not investment.</strong> <code>deal_on_show</code> records an on-air agreement. It does not establish that money changed hands or that the venture later succeeded.</li>
<li><strong>Measured is not the same as meant.</strong> <code>description_words</code> counts words in the source’s written description, not the spoken pitch; <code>women_represented</code> is a category, not a share; the file does not measure later performance at all.</li>
</ul>
<p>The same discipline applies to the class dataset: it describes the students who responded, and a bigger convenience sample would not make it describe Dutch students in general.</p>
</div>
</section>
<section id="answering-the-driving-question" class="level3">
<h3 class="anchored" data-anchor-id="answering-the-driving-question">Answering the driving question</h3>
<p>The dataset can tell us, precisely and reproducibly, what happened in these 1,441 recorded pitches: 882 of them (61.2%) reached an on-air agreement, most initial offers gave up at most 20% equity with a median in the 5–10% interval, and mean offers drifted downward across seasons. It can never tell us, by itself, what would happen to a new entrepreneur, whether an on-air agreement became a completed investment, or why any of these patterns arose — those questions need assumptions about selection, measurement, and causality that the file cannot supply.</p>
<p><strong>Next:</strong> We can now describe what happened in these 1,441 pitches: counts, shares, and shapes. But description alone cannot answer the chance questions an investor actually asks — how likely is a deal if I pick a pitch at random, how likely is a late-season pitch, how likely are both at once. Lecture 2 builds the tool for exactly such questions, a probability model: select one record at random so that every pitch is equally likely, define events such as “reached a deal” and “late season”, and compute how likely each is — with rules that say when chances may simply be added.</p>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p><span class="time-budget">Total practice time: about 75 minutes.</span></p>
<section id="reproduce-the-workflow-15-minutes" class="level3">
<h3 class="anchored" data-anchor-id="reproduce-the-workflow-15-minutes">Reproduce the workflow (15 minutes)</h3>
<p>Save the script. In RStudio, choose <strong>Session &gt; Restart R</strong> to clear objects from memory. Run the complete script from top to bottom. It should import the data, perform the checks, calculate the deal rate, and recreate at least one graph without relying on commands run earlier at the Console.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check the result
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A successful clean run reports 1,441 rows and 19 variables, a recorded on-air deal rate of 882/1,441 (61.2%), the stated ranges, and recreates the graph without an “object not found” error.</p>
</div>
</div>
</div>
</section>
<section id="retrieval-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="retrieval-10-minutes">Retrieval (10 minutes)</h3>
<p>Answer without reopening the chapter, then check your answers.</p>
<ol type="1">
<li>What does one row represent, and which population can it describe directly?</li>
<li>Why is <code>pitch_id</code> an identifier rather than a quantitative measurement?</li>
<li>What is the difference between sampling variability and selection bias?</li>
<li>What exactly does <code>description_words</code> measure?</li>
<li>How do you locate the median interval of a histogram by hand?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>One row is one recorded televised pitch; the file directly describes these 1,441 records from completed Seasons 1–16.</li>
<li><code>pitch_id</code> labels a record. Arithmetic differences between its values have no substantive meaning.</li>
<li>Sampling variability is chance variation across random samples; selection bias is systematic distortion from how units enter the sample.</li>
<li>The number of words in the written dataset description — the source text about the pitch, not the spoken pitch itself.</li>
<li>Find the position of the median (about <span class="math inline">\(n/2\)</span>), then add bar counts from the left; the first interval whose cumulative count reaches that position contains the median.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="explain-one-graph-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="explain-one-graph-10-minutes">Explain one graph (10 minutes)</h3>
<p>Write four sentences about either Shark Tank graph (<a href="#fig-b01-raw-points" class="quarto-xref">Figure&nbsp;<span>1.4</span></a> or <a href="#fig-b01-season-means" class="quarto-xref">Figure&nbsp;<span>1.5</span></a>):</p>
<ol type="1">
<li>name the variables and units;</li>
<li>describe the main visible pattern;</li>
<li>state one defensible interpretation; and</li>
<li>state one important limitation or next question.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Each point in the raw-data graph represents one recorded pitch, with season on the horizontal axis and initially offered equity on the vertical axis. Offers vary within every season and are generally lower in later seasons. This is evidence of an association between season and the recorded initial offer. It does not show why offers changed or identify the causal effect of changing an offer.</p>
</div>
</div>
</div>
</section>
<section id="from-worked-to-faded-finish-a-histogram-reading-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="from-worked-to-faded-finish-a-histogram-reading-10-minutes">From worked to faded: finish a histogram reading (10 minutes)</h3>
<p>Re-read the worked histogram reading (<a href="#exm-b01-histogram-read" class="quarto-xref">Example&nbsp;<span>1.2</span></a>). Now finish the same reading for the description-words histogram (<a href="#fig-b01-word-hist" class="quarto-xref">Figure&nbsp;<span>1.2</span></a>). The bar counts, from 1 word upward, are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Words</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
<th style="text-align: right;">5</th>
<th style="text-align: right;">6</th>
<th style="text-align: right;">7</th>
<th style="text-align: right;">8</th>
<th style="text-align: right;">9</th>
<th style="text-align: right;">10</th>
<th style="text-align: right;">11</th>
<th style="text-align: right;">12</th>
<th style="text-align: right;">13</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Count</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">113</td>
<td style="text-align: right;">217</td>
<td style="text-align: right;">285</td>
<td style="text-align: right;">292</td>
<td style="text-align: right;">241</td>
<td style="text-align: right;">146</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
<p><em>Step 1 (given).</em> One observation is one recorded pitch; the axes show description length in words and the pitch count. With 1,441 observations, the median is the 721st ordered value.</p>
<p><em>Step 2 (you).</em> Build the cumulative counts and locate the bar containing the 721st observation.</p>
<p><em>Step 3 (you).</em> Describe the shape and state one limit of the graph.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Cumulative counts: 4, 117, 334, 619, 911, … The running total first reaches 721 at the 5-word bar (<span class="math inline">\(619+292=911\ge721\)</span>), so the median is 5 words — matching <code>median(sharks$description_words)</code>. The distribution is mildly right-skewed, concentrated at 3–7 words with a thin right tail. The graph cannot say anything about the pitch itself: it describes the source’s written text.</p>
</div>
</div>
</div>
</section>
<section id="audit-an-ai-answer-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="audit-an-ai-answer-10-minutes">Audit an AI answer (10 minutes)</h3>
<p>An AI assistant writes:</p>
<blockquote class="blockquote">
<p>“The dataset contains 1,441 successful companies and proves that offering less equity makes investors fund startups.”</p>
</blockquote>
<p>Use <strong>Attempt → Ask → Verify → Explain</strong> to correct it. Your final response must use the observed count or percentage, name the measured outcome, and state why the causal claim is unsupported.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model correction after writing your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The file contains 1,441 recorded televised pitches, of which 882 reached an on-air agreement. It does not measure completed investment or later company success. <code>equity_offered_pct</code> records the initial ownership percentage offered, not a randomly assigned treatment, and the observational records do not establish that changing only this offer would cause an investor decision.</p>
</div>
</div>
</div>
</section>
<section id="worked-exam-interpretation-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="worked-exam-interpretation-5-minutes">Worked exam interpretation (5 minutes)</h3>
<p><strong>Question (mirrors Mock Exam Q1).</strong> A startup accelerator records, for each of 240 applications: <code>funding_requested_k</code> (euros, in thousands), <code>team_size</code>, <code>sector</code> (four categories), and <code>accepted</code> (0/1). Classify each variable. A histogram of <code>funding_requested_k</code> has equal-width intervals of EUR 20,000 with counts 58, 88, 54, 24, 10, 6. Which interval contains the median?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>funding_requested_k</code> is quantitative continuous; <code>team_size</code> is quantitative discrete; <code>sector</code> is categorical; <code>accepted</code> is categorical binary, even though it is coded 0/1. With 240 observations, the median lies between the 120th and 121st ordered values. Cumulative counts: 58 below EUR 20,000, then <span class="math inline">\(58+88=146\)</span> below EUR 40,000 — so observations 120 and 121, and hence the median, lie in the <strong>EUR 20,000–40,000 interval</strong>.</p>
</div>
</div>
</div>
</section>
<section id="from-the-reading-ladder-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="from-the-reading-ladder-10-minutes">From the reading ladder (10 minutes)</h3>
<p>This course trains you to read real research, one bounded piece at a time — the <a href="../resources/reading-ladder.html">reading ladder</a> explains the plan and the six-question protocol. First rung: open <a href="https://doi.org/10.1016/0749-5978(91)90020-T">Ajzen (1991), the Theory of Planned Behavior</a> via the university library and read only the <strong>title and abstract</strong>. List two theoretical constructs the theory uses (for example attitude toward the behaviour, subjective norm, perceived behavioural control, intention), and for each propose one concrete measurable variable you could actually record from a survey of E&amp;BI students — then classify each proposed variable as categorical, discrete quantitative, or continuous quantitative.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check an example answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The construct <em>entrepreneurial intention</em> could be measured as the answer to “do you plan to start a business within five years?” — a categorical (binary) variable; the construct <em>attitude toward entrepreneurship</em> could be measured as agreement with “running my own business appeals to me” on a 1–7 scale — a discrete quantitative measurement of a construct no single question fully captures. The gap between the construct and the variable is exactly the imperfect-measurement point from today’s lecture.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Utility: two sentences</span></p>
<p>Think of your EiA venture — or any business you know well. Write two sentences: first name one number you would genuinely want to know about it (a rate, a count, an amount), then state what data you would need to collect to measure that number and one way the collection could be biased. There is no wrong answer; the point is connecting today’s tools to something you care about.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run campus meal-prep box venture. “The number I most want is the share of first-order customers who order again within 30 days. I would need order records linked over time, and counting only app users would bias the share upward, because the most committed customers are the ones who install the app.”</p>
</div>
</div>
</div>
<p>You can discuss this task — and any other task in this chapter — with <strong>Tilly</strong>, the course AI assistant on Canvas: ask it to poke holes in your data-collection plan or to suggest a selection bias you have not thought of.</p>
</div>
<p>Continue to Lecture 2: Probability foundations and random variables.</p>
<p>Formula sheet: Lecture 1 formulas.</p>
<p>For a more formal explanation, consult <a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>, Chapters 1–5.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/overview.html" class="pagination-link" aria-label="QM Basic: Course overview">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">QM Basic: Course overview</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/b02-probability-foundations.html" class="pagination-link" aria-label="Lecture 2: Probability foundations and random variables">
        <span class="nav-page-text"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>