<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 2: Probability foundations and random variables – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/b03-discrete-distributions.html" rel="next">
<link href="../basic/b01-introduction-data-analysis.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ecf4e518a83458a2bb67b2a9bf74271b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b02-probability-foundations.html"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution, confidence intervals, and the two-sided test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Inference and tests against zero</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals betray it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/reading-ladder.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reading research papers</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-class" id="toc-in-class" class="nav-link" data-scroll-target="#in-class">In class</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b02-probability-foundations.html"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b02" class="quarto-section-identifier"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Lecture 2, you can</span></p>
<ul>
<li>define a random experiment, outcome, sample space, and event;</li>
<li>use complements, intersections, unions, and disjointness;</li>
<li>state the probability rules and compute probabilities from a counts table;</li>
<li>recognise a partition of the sample space;</li>
<li>distinguish empirical proportions from model probabilities and from forecasts;</li>
<li>define a random variable informally and state its support.</li>
</ul>
</div>
<div class="driving-question">
<p><span class="label">Driving question</span></p>
<p class="dq-context">
Investors think in chances: how likely is a deal, how likely is a pitch from the show’s later, bigger years, how likely are both at once. Before we can compute any such chance, we need a precise language for “how likely” — that language is today’s lecture.
</p>
<p>Pick one recorded pitch at random. What is the chance it reached a deal, came from a late season, or both — and what do those numbers mean beyond this file?</p>
</div>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p><span class="time-budget">Total preparation time: about 30 minutes.</span></p>
<div class="video-prep">
<p><span class="label">Video preparation (20 minutes)</span><br> Watch <a href="https://www.youtube.com/watch?v=iQ2edOqEQAs">Sample Space</a> and <a href="https://www.youtube.com/watch?v=pA83XtLeVig">Probability Axioms</a>, then watch <a href="https://www.youtube.com/watch?v=vfqPpai_9jI">Definition of Random Variables</a>. Be ready to define an outcome, sample space, event, and random variable. All links are also listed in the <a href="../resources/video-guide.html">External Video Guide</a>.</p>
</div>
<p><strong>Reactivate (5 minutes).</strong> In Lecture 1 you built frequency tables for the Shark Tank data. Rebuild the season frequency table — one line of R once the data are loaded:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(sharks<span class="sc">$</span>season)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Predict (5 minutes).</strong> Answer the one-click Mentimeter question posted on Canvas before you come to class: is <span class="math inline">\(P(\text{deal or late season})\)</span> <strong>larger</strong> or <strong>smaller</strong> than <span class="math inline">\(P(\text{deal}) + P(\text{late season})\)</span>? Commit to an answer; the lecture resolves it.</p>
<p>If set notation, complements, unions, or intersections are unfamiliar, review <a href="../resources/math-refresher.html">Mathematics Refresher: sets and events</a>.</p>
</section>
<section id="in-class" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-class">In class</h2>
<p>The session opens with the usual four-minute entry quiz on the prep videos, then turns to the driving question. The experiment behind the whole lecture: <strong>select one of the 1,441 recorded pitches uniformly at random.</strong></p>
<section id="a-probability-model-begins-with-possible-outcomes" class="level3">
<h3 class="anchored" data-anchor-id="a-probability-model-begins-with-possible-outcomes">A probability model begins with possible outcomes</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/sample-space/">01.2 Sample Space</a>.
</p>
<p>Probability starts by specifying exactly what may happen. A probability model needs a process, a list of complete possible results, and events that describe which results matter for the question.</p>
<p>A <strong>random experiment</strong> is a process whose outcome is not known in advance. The word <em>random</em> does not mean “unstructured.” It means the model does not specify in advance which possible outcome will occur.</p>
<ul>
<li>An <strong>outcome</strong>, written <span class="math inline">\(\omega\)</span>, is one complete possible result.</li>
<li>The <strong>sample space</strong>, written <span class="math inline">\(\Omega\)</span>, is the set of all possible outcomes.</li>
<li>An <strong>event</strong> is a specified subset of <span class="math inline">\(\Omega\)</span> to which the model assigns a probability. It occurs when the realised outcome belongs to that subset.</li>
</ul>
<p>The distinction is easiest to read from the whole-to-part structure:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Object</th>
<th>Question it answers</th>
<th>Shark Tank example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>experiment</td>
<td>What is done?</td>
<td>Select one of the 1,441 records uniformly</td>
</tr>
<tr class="even">
<td>outcome <span class="math inline">\(\omega\)</span></td>
<td>Which complete result occurred?</td>
<td>One complete selected pitch record</td>
</tr>
<tr class="odd">
<td>sample space <span class="math inline">\(\Omega\)</span></td>
<td>Which complete results were possible?</td>
<td>The set of all 1,441 records</td>
</tr>
<tr class="even">
<td>event <span class="math inline">\(A\)</span></td>
<td>Which outcomes count as “yes” for this question?</td>
<td>The subset of records with an on-air deal</td>
</tr>
</tbody>
</table>
<p>For a single roll of a fair six-sided die,</p>
<p><span class="math display">\[\Omega=\{1,2,3,4,5,6\}.\]</span></p>
<p>The event <span class="math inline">\(E=\{2,4,6\}\)</span> means “an even result.” The outcome <span class="math inline">\(\omega=4\)</span> belongs to <span class="math inline">\(E\)</span>, so <span class="math inline">\(E\)</span> occurs when 4 is rolled. The number 4 is an outcome; the singleton set <span class="math inline">\(\{4\}\)</span> is an event.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: is “the record with pitch_id 7” an outcome or an event?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The record itself is one complete possible result of the selection, so it is an <strong>outcome</strong>. The description “the selected pitch is the record with pitch_id 7” picks out the singleton set containing that record, and a set of outcomes is an <strong>event</strong>. The same distinction as 4 versus <span class="math inline">\(\{4\}\)</span> on the die.</p>
</div>
</div>
</div>
<section id="an-empirical-selection-experiment" class="level4">
<h4 class="anchored" data-anchor-id="an-empirical-selection-experiment">An empirical selection experiment</h4>
<p>Define the experiment as <strong>select one of the 1,441 recorded pitches uniformly at random</strong>. The sample space is the set of 1,441 pitch records. Define:</p>
<ul>
<li><span class="math inline">\(D\)</span>: the selected pitch reached an on-air deal;</li>
<li><span class="math inline">\(L\)</span>: the selected pitch appeared in a late season (Seasons 9–16).</li>
</ul>
<p>Making the selection uniform means every record has probability <span class="math inline">\(1/1441\)</span>. Consequently, event probabilities equal relative frequencies in this fixed dataset. This does not imply the same probabilities for future entrepreneurs — the caveat box below returns to this point.</p>
</section>
</section>
<section id="combining-events" class="level3">
<h3 class="anchored" data-anchor-id="combining-events">Combining events</h3>
<p>Events are sets of outcomes. Set notation therefore gives us a precise way to describe how events are combined.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Notation</th>
<th>Name</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(A^c\)</span></td>
<td>complement</td>
<td><span class="math inline">\(A\)</span> does not occur</td>
</tr>
<tr class="even">
<td><span class="math inline">\(A\cap B\)</span></td>
<td>intersection</td>
<td>both <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> occur</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(A\cup B\)</span></td>
<td>union</td>
<td><span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, or both occur</td>
</tr>
<tr class="even">
<td><span class="math inline">\(A\subseteq B\)</span></td>
<td>subset</td>
<td>every outcome in <span class="math inline">\(A\)</span> is also in <span class="math inline">\(B\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(A\cap B=\varnothing\)</span></td>
<td>disjoint</td>
<td><span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> cannot occur together</td>
</tr>
</tbody>
</table>
<p>To make the notation concrete, suppose one number is selected at random from</p>
<p><span class="math display">\[\Omega=\{1,2,\ldots,12\}.\]</span></p>
<p>Define <span class="math inline">\(A=\{1,2,3,5,6,9\}\)</span> and <span class="math inline">\(B=\{1,2,3,4\}\)</span>. Each panel of <a href="#fig-b02-events" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> shows the same sample space. A green circle means that the outcome belongs to the event named above the panel.</p>
<div class="cell">
<details class="code-fold">
<summary>See the drawing code (optional, not exam material)</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>old_par <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">no.readonly =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">0.6</span>, <span class="fl">0.35</span>, <span class="fl">2.8</span>, <span class="fl">0.35</span>),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">xaxs =</span> <span class="st">"i"</span>, <span class="at">yaxs =</span> <span class="st">"i"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>omega <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">9</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>event_sets <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">setdiff</span>(omega, A),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">intersect</span>(A, B),</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">union</span>(A, B)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>panel_titles <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Complement"</span>, <span class="st">"Intersection"</span>, <span class="st">"Union"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>panel_meanings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"not A"</span>, <span class="st">"A and B"</span>, <span class="st">"A or B (or both)"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>draw_outcome_set <span class="ot">&lt;-</span> <span class="cf">function</span>(selected, title, meaning) {</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(<span class="cn">NA</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">0.45</span>, <span class="fl">4.55</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fl">0.35</span>, <span class="fl">4.2</span>), <span class="at">axes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">asp =</span> <span class="dv">1</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">title</span>(<span class="at">main =</span> title, <span class="at">line =</span> <span class="fl">1.2</span>, <span class="at">cex.main =</span> <span class="fl">1.05</span>, <span class="at">col.main =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mtext</span>(meaning, <span class="at">side =</span> <span class="dv">3</span>, <span class="at">line =</span> <span class="fl">0.1</span>, <span class="at">cex =</span> <span class="fl">0.82</span>, <span class="at">col =</span> <span class="st">"#5B6976"</span>)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rect</span>(<span class="fl">0.62</span>, <span class="fl">0.55</span>, <span class="fl">4.38</span>, <span class="fl">3.55</span>, <span class="at">col =</span> <span class="st">"#F4F7F9"</span>,</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">border =</span> <span class="st">"#17324D"</span>, <span class="at">lwd =</span> <span class="fl">1.4</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">text</span>(<span class="fl">4.18</span>, <span class="fl">3.76</span>, <span class="fu">expression</span>(Omega), <span class="at">cex =</span> <span class="fl">0.85</span>, <span class="at">col =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">3</span>)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">each =</span> <span class="dv">4</span>)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>  is_selected <span class="ot">&lt;-</span> omega <span class="sc">%in%</span> selected</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">symbols</span>(x, y, <span class="at">circles =</span> <span class="fu">rep</span>(<span class="fl">0.25</span>, <span class="dv">12</span>), <span class="at">inches =</span> <span class="cn">FALSE</span>,</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>          <span class="at">bg =</span> <span class="fu">ifelse</span>(is_selected, <span class="st">"#009E73"</span>, <span class="st">"white"</span>),</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>          <span class="at">fg =</span> <span class="fu">ifelse</span>(is_selected, <span class="st">"#009E73"</span>, <span class="st">"#9AA7B2"</span>),</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>          <span class="at">lwd =</span> <span class="fl">1.4</span>, <span class="at">add =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">text</span>(x, y, <span class="at">labels =</span> omega,</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">ifelse</span>(is_selected, <span class="st">"white"</span>, <span class="st">"#17324D"</span>),</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>       <span class="at">font =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">0.82</span>)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(event_sets)) {</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">draw_outcome_set</span>(event_sets[[i]], panel_titles[i], panel_meanings[i])</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(old_par)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b02-events" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b02-events-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b02-probability-foundations_files/figure-html/fig-b02-events-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b02-events-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Complement, intersection, and union of two events in a 12-outcome sample space. Green outcomes belong to the event named above each panel.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Thus <span class="math inline">\(A^c=\{4,7,8,10,11,12\}\)</span>, <span class="math inline">\(A\cap B=\{1,2,3\}\)</span>, and <span class="math inline">\(A\cup B=\{1,2,3,4,5,6,9\}\)</span>. Notice that <strong>or</strong> includes outcomes that are in both events: <span class="math inline">\(1,2,3\)</span> belong to the union as well as the intersection.</p>
<p>The same grammar works for business events. In the selection experiment, let <span class="math inline">\(F\)</span> be “the selected pitch is from the Food and Beverage industry” and <span class="math inline">\(T\)</span> “from the Technology industry.” Each record lists exactly one industry, so <span class="math inline">\(F\)</span> and <span class="math inline">\(T\)</span> are disjoint: <span class="math inline">\(F\cap T=\varnothing\)</span>. The union <span class="math inline">\(F\cup T\)</span> is “a food or technology pitch,” and <span class="math inline">\(F^c\)</span> collects every pitch from any other industry. Nothing new is needed — only the sets have changed.</p>
<p>Disjoint does <strong>not</strong> mean independent. If two disjoint events both have positive probability, observing one makes the other impossible. Independence, introduced in Lecture 4, means that observing one event does not change the probability of the other.</p>
<section id="the-22-counts-table-for-deals-and-seasons" class="level4">
<h4 class="anchored" data-anchor-id="the-22-counts-table-for-deals-and-seasons">The 2×2 counts table for deals and seasons</h4>
<p>Everything this lecture computes comes from one table. The code constructs <span class="math inline">\(D\)</span> and <span class="math inline">\(L\)</span> exactly as defined above — run it yourself:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span>   <span class="co"># on-air deal</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span>         <span class="co"># late season: Seasons 9-16</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">deal =</span> D, <span class="at">late =</span> L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       late
deal    FALSE TRUE
  FALSE   330  229
  TRUE    377  505</code></pre>
</div>
</div>
<p>Written with row and column totals:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 31%">
<col style="width: 28%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Early (<span class="math inline">\(L^c\)</span>, S1–8)</th>
<th style="text-align: right;">Late (<span class="math inline">\(L\)</span>, S9–16)</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>No deal</strong> (<span class="math inline">\(D^c\)</span>)</td>
<td style="text-align: right;">330</td>
<td style="text-align: right;">229</td>
<td style="text-align: right;"><strong>559</strong></td>
</tr>
<tr class="even">
<td><strong>Deal</strong> (<span class="math inline">\(D\)</span>)</td>
<td style="text-align: right;">377</td>
<td style="text-align: right;">505</td>
<td style="text-align: right;"><strong>882</strong></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>707</strong></td>
<td style="text-align: right;"><strong>734</strong></td>
<td style="text-align: right;"><strong>1441</strong></td>
</tr>
</tbody>
</table>
<div id="exm-b02-events" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.1 (Worked example: three events in words and symbols)</strong></span> From the table, describe each event in words and give its count.</p>
<ul>
<li><span class="math inline">\(D^c\)</span>, “no on-air deal”: the top row, <span class="math inline">\(330 + 229 = 559\)</span> records.</li>
<li><span class="math inline">\(D\cap L\)</span>, “deal <strong>and</strong> late season”: the single bottom-right cell, 505 records.</li>
<li><span class="math inline">\(D\cup L\)</span>, “deal, late season, <strong>or both</strong>”: every record except the top-left cell, <span class="math inline">\(1441 - 330 = 1111\)</span> records — the deal row (882) plus the late column (734) minus the 505 records counted in both.</li>
</ul>
</div>
</section>
</section>
<section id="probability-rules" class="level3">
<h3 class="anchored" data-anchor-id="probability-rules">Probability rules</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/probability-axioms/">01.4 Probability Axioms</a>.
</p>
<p>A <strong>probability law</strong> assigns a number <span class="math inline">\(P(A)\)</span> to each event <span class="math inline">\(A\)</span>. It must satisfy three rules:</p>
<ol type="1">
<li><strong>Non-negativity:</strong> <span class="math inline">\(P(A)\ge 0\)</span> for every event <span class="math inline">\(A\)</span>.</li>
<li><strong>Normalisation:</strong> <span class="math inline">\(P(\Omega)=1\)</span>.</li>
<li><strong>Additivity:</strong> if <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are disjoint, then <span class="math display">\[P(A\cup B)=P(A)+P(B),\]</span> and the same holds for any finite collection of pairwise disjoint events.</li>
</ol>
<p>The first two rules set the probability scale: probability cannot be negative, and something in the sample space must occur. The third says that mutually exclusive routes can be added because no outcome is counted twice.</p>
<div class="optional-box">
<p><span class="label">Optional: countable additivity</span><br> In the formal theory the third rule is stated for infinite sequences of pairwise disjoint events, <span class="math inline">\(P\!\left(\bigcup_{i=1}^{\infty} A_i\right)
=\sum_{i=1}^{\infty} P(A_i)\)</span>, which matters for sample spaces with infinitely many outcomes. Every sample space in this course is finite, so the finite version above is all you need.</p>
</div>
<p>For a finite sample space with equally likely outcomes,</p>
<p><span class="math display">\[P(A)=\frac{|A|}{|\Omega|}.\]</span></p>
<p>That ratio is a special case, not a universal definition. It applies because equal likelihood has been built into the model — here, because the selection was made uniform.</p>
<section id="rules-derived-from-the-three-above" class="level4">
<h4 class="anchored" data-anchor-id="rules-derived-from-the-three-above">Rules derived from the three above</h4>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/simple-properties-of-probabilities/">01.5 Simple Properties of Probabilities</a>.
</p>
<p>Because <span class="math inline">\(A\)</span> and <span class="math inline">\(A^c\)</span> are disjoint and together form <span class="math inline">\(\Omega\)</span>,</p>
<p><span class="math display">\[P(A^c)=1-P(A).\]</span></p>
<p>When <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> may overlap,</p>
<p><span class="math display">\[P(A\cup B)=P(A)+P(B)-P(A\cap B).\]</span></p>
<p>The intersection is subtracted once because it was counted in both marginal probabilities.</p>
<div id="exm-b02-union" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.2 (Worked example: P(deal or late season), by hand)</strong></span> Every number comes from the counts table above — point to each one as you read.</p>
<p><span class="math display">\[
P(D\cup L)
=\frac{882}{1441}+\frac{734}{1441}-\frac{505}{1441}
=\frac{882+734-505}{1441}
=\frac{1111}{1441}\approx 0.771.
\]</span></p>
<p>The 882 is the deal row total, the 734 is the late column total, and the 505 is the deal-and-late cell that both totals contain — subtracted once so no record is counted twice.</p>
<p>This resolves the prediction from your prep: <span class="math inline">\(P(D\cup L)\)</span> is <strong>smaller</strong> than <span class="math inline">\(P(D)+P(L)\)</span> whenever the two events overlap, because the overlap <span class="math inline">\(P(D\cap L) &gt; 0\)</span> is subtracted.</p>
</div>
<p>Verification in R, with <span class="math inline">\(D\)</span> and <span class="math inline">\(L\)</span> built exactly as before:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_D            =</span> <span class="fu">mean</span>(D),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_L            =</span> <span class="fu">mean</span>(L),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_D_and_L      =</span> <span class="fu">mean</span>(D <span class="sc">&amp;</span> L),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_not_D        =</span> <span class="fu">mean</span>(<span class="sc">!</span>D),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_D_or_L_direct =</span> <span class="fu">mean</span>(D <span class="sc">|</span> L),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_D_or_L_rule   =</span> <span class="fu">mean</span>(D) <span class="sc">+</span> <span class="fu">mean</span>(L) <span class="sc">-</span> <span class="fu">mean</span>(D <span class="sc">&amp;</span> L)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            P_D             P_L       P_D_and_L         P_not_D P_D_or_L_direct 
      0.6120749       0.5093685       0.3504511       0.3879251       0.7709924 
  P_D_or_L_rule 
      0.7709924 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it: P(no deal and early season)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In class this is the pair task set just before the break. Complete the two missing steps before opening the answer.</p>
<p><em>Step 1 (given).</em> “No deal <strong>and</strong> early season” is the event <span class="math inline">\(D^c\cap L^c\)</span> — the top-left cell of the counts table.</p>
<p><em>Step 2 (you).</em> Read off the count for that cell.</p>
<p><em>Step 3 (you).</em> Divide by the number of records and interpret the result in one sentence.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(P(D^c\cap L^c) = 330/1441 \approx 0.229\)</span>: about 23% of the recorded pitches are early-season pitches that did not reach an on-air deal.</p>
<p>Verification in R (the construction of <code>D</code> and <code>L</code> is repeated so the block runs on its own):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="sc">!</span>D <span class="sc">&amp;</span> <span class="sc">!</span>L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2290076</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="partitions" class="level3">
<h3 class="anchored" data-anchor-id="partitions">Partitions</h3>
<p>A <strong>partition</strong> divides <span class="math inline">\(\Omega\)</span> into events that do not overlap and together include every possible outcome. Each outcome belongs to exactly one part. For example, Seasons 1–8 and Seasons 9–16 partition the recorded pitches into an early-period event <span class="math inline">\(L^c\)</span> and a late-period event <span class="math inline">\(L\)</span> (<a href="#fig-b02-partition" class="quarto-xref">Figure&nbsp;<span>2.2</span></a>).</p>
<div class="cell">
<details class="code-fold">
<summary>See the drawing code (optional, not exam material)</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>old_par <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">no.readonly =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="fl">0.3</span>, <span class="fl">0.3</span>, <span class="fl">0.3</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NA</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="at">axes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">xaxs =</span> <span class="st">"i"</span>, <span class="at">yaxs =</span> <span class="st">"i"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rect</span>(<span class="fl">0.4</span>, <span class="fl">0.4</span>, <span class="fl">9.6</span>, <span class="fl">4.6</span>, <span class="at">border =</span> <span class="st">"#17324D"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rect</span>(<span class="fl">0.4</span>, <span class="fl">0.4</span>, <span class="fl">4.9</span>, <span class="fl">4.6</span>, <span class="at">col =</span> <span class="st">"#DCEAF3"</span>, <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rect</span>(<span class="fl">4.9</span>, <span class="fl">0.4</span>, <span class="fl">9.6</span>, <span class="fl">4.6</span>, <span class="at">col =</span> <span class="st">"#FDE5C1"</span>, <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="fl">4.9</span>, <span class="fl">0.4</span>, <span class="fl">4.9</span>, <span class="fl">4.6</span>, <span class="at">col =</span> <span class="st">"#17324D"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rect</span>(<span class="fl">0.4</span>, <span class="fl">0.4</span>, <span class="fl">9.6</span>, <span class="fl">4.6</span>, <span class="at">border =</span> <span class="st">"#17324D"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">2.65</span>, <span class="fl">2.5</span>, <span class="fu">expression</span>(L<span class="sc">^</span>c), <span class="at">col =</span> <span class="st">"#0072B2"</span>, <span class="at">cex =</span> <span class="fl">1.25</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">7.25</span>, <span class="fl">2.5</span>, <span class="st">"L"</span>, <span class="at">col =</span> <span class="st">"#D55E00"</span>, <span class="at">cex =</span> <span class="fl">1.25</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">9.15</span>, <span class="fl">4.15</span>, <span class="fu">expression</span>(Omega), <span class="at">col =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(old_par)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b02-partition" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b02-partition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b02-probability-foundations_files/figure-html/fig-b02-partition-1.png" class="img-fluid figure-img" width="614">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b02-partition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: The early-period event and the late-period event partition the sample space: no overlap, nothing left out.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The two coloured regions do not overlap, and together they fill the whole rectangle. Lecture 4 uses this idea to combine conditional probabilities from separate groups.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: do the sixteen events “the pitch is from Season s” form a partition?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Yes. Every record has exactly one season, so the sixteen single-season events are pairwise disjoint and together cover all 1,441 records. <span class="math inline">\(D\)</span> and <span class="math inline">\(L\)</span>, by contrast, do <strong>not</strong> form a partition: they overlap (505 records) and leave records out (the 330 early no-deal records).</p>
</div>
</div>
</div>
</section>
<section id="from-complete-outcomes-to-numerical-measurements" class="level3">
<h3 class="anchored" data-anchor-id="from-complete-outcomes-to-numerical-measurements">From complete outcomes to numerical measurements</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/definition-of-random-variables/">05.2 Definition of Random Variables</a>.
</p>
<p>An outcome is a complete result, but an analysis usually focuses on one numerical feature of that result. A <strong>random variable</strong> is a numerical measurement whose value is determined by chance — through a fixed rule that turns the realised outcome into a number.</p>
<p>Three random variables on our selection experiment:</p>
<ul>
<li>the <strong>deal indicator</strong> <span class="math inline">\(X\)</span>: equal to 1 when the selected pitch reached an on-air deal and 0 otherwise;</li>
<li>the <strong>season</strong> <span class="math inline">\(S\)</span>: the season number of the selected pitch;</li>
<li>the <strong>word count</strong> <span class="math inline">\(W\)</span>: the number of words in its written description.</li>
</ul>
<p>The rule is fixed before an outcome is selected; the value is unknown until then. That is the only sense in which the variable is “random.” After selection, the number produced — written in lower case, <span class="math inline">\(x\)</span>, <span class="math inline">\(s\)</span>, or <span class="math inline">\(w\)</span> — is its <strong>realised value</strong>.</p>
<p>A random variable is <strong>discrete</strong> when its possible values can be listed. Its <strong>support</strong> is the set of values it can take with positive probability. The support of the deal indicator is <span class="math inline">\(\{0,1\}\)</span>; the support of season is <span class="math inline">\(\{1,2,\ldots,16\}\)</span>. Lecture 3 attaches a probability to every value in the support.</p>
<div class="optional-box">
<p><span class="label">Optional: the formal definition</span><br> Formally, a random variable is a function from the sample space to the real numbers, <span class="math inline">\(X:\Omega\rightarrow\mathbb{R}\)</span>. Read left to right: <span class="math inline">\(X\)</span> takes an outcome <span class="math inline">\(\omega\)</span> from <span class="math inline">\(\Omega\)</span> and returns the number <span class="math inline">\(X(\omega)\)</span>. For the deal indicator, <span class="math inline">\(X(\omega)=1\)</span> when <span class="math inline">\(\omega\in D\)</span> and <span class="math inline">\(X(\omega)=0\)</span> otherwise, so the event <span class="math inline">\(D\)</span> and the variable <span class="math inline">\(X\)</span> are linked by <span class="math inline">\(D=\{\omega : X(\omega)=1\}\)</span>. The bookkeeping table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Symbol</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\omega\)</span></td>
<td>one complete outcome, such as one selected pitch record</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X\)</span></td>
<td>the fixed measurement rule</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(X(\omega)\)</span></td>
<td>the number assigned by <span class="math inline">\(X\)</span> to outcome <span class="math inline">\(\omega\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(x\)</span></td>
<td>a possible or realised numerical value of <span class="math inline">\(X\)</span></td>
</tr>
</tbody>
</table>
</div>
<div class="caveat-box">
<p><span class="label">What these numbers can and cannot say</span></p>
<p><span class="math inline">\(P(D)=882/1441\approx 0.612\)</span> is exact for one question only: the chance of a deal when one record is selected uniformly from this fixed file. It is an <strong>empirical proportion</strong>. Calling it the probability that a <em>future</em> televised pitch reaches an on-air agreement adds four assumptions:</p>
<ul>
<li>the future case belongs to a defined target population;</li>
<li>selection into the show is comparable;</li>
<li>the process is stable over time;</li>
<li>“deal” retains the same definition.</li>
</ul>
<p>Calling it the probability of a completed <em>investment</em> would additionally change the outcome being predicted: completed investment is not recorded in these data. An on-air agreement is not money in the bank.</p>
</div>
</section>
<section id="answering-the-driving-question" class="level3">
<h3 class="anchored" data-anchor-id="answering-the-driving-question">Answering the driving question</h3>
<p>For one uniformly selected record: the chance it reached a deal is <span class="math inline">\(P(D)\approx 0.612\)</span>, the chance it came from a late season is <span class="math inline">\(P(L)\approx 0.509\)</span>, the chance of both is <span class="math inline">\(P(D\cap L)\approx 0.350\)</span>, and the chance of at least one is <span class="math inline">\(P(D\cup L)\approx 0.771\)</span>. Beyond this file, those numbers describe future pitches only under the four assumptions in the caveat box.</p>
<p><strong>Next:</strong> We can now attach a probability to a single event — deal or no deal, late or early. But most business quantities have many possible values: which season, how many words, how many units sold. Lecture 3 upgrades from single events to the whole <em>distribution</em> of a random variable: a probability for every possible value (the PMF), running totals (the CDF), and the two numbers that summarise it all — expected value and variance — so that “a typical pitch” finally gets a precise meaning.</p>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p><span class="time-budget">Total practice time: about 55 minutes.</span></p>
<section id="retrieval-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="retrieval-10-minutes">Retrieval (10 minutes)</h3>
<ol type="1">
<li>What is the difference between an outcome and an event?</li>
<li>What is the difference between a random variable and a realised value?</li>
<li>State the three probability rules.</li>
<li>Why is the equally-likely ratio a special case?</li>
<li>What extra assumptions turn an empirical proportion into a forecast?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>An outcome is one possible complete result; an event is a specified set of outcomes.</li>
<li>A random variable is a fixed measurement rule that turns outcomes into numbers; a realised value is the number produced for the observed outcome.</li>
<li>Probabilities are non-negative, <span class="math inline">\(P(\Omega)=1\)</span>, and probabilities add across disjoint events.</li>
<li>The ratio <span class="math inline">\(|A|/|\Omega|\)</span> requires a finite sample space whose outcomes are equally likely.</li>
<li>A forecast requires a defined target population and assumptions about selection, process stability, and a stable outcome definition.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="from-worked-to-faded-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="from-worked-to-faded-10-minutes">From worked to faded (10 minutes)</h3>
<p>Re-read the worked union calculation (<a href="#exm-b02-union" class="quarto-xref">Example&nbsp;<span>2.2</span></a>). Then complete the same calculation with new numbers: let <span class="math inline">\(E=L^c\)</span> be the early-period event (Seasons 1–8).</p>
<p><em>Step 1 (given).</em> From the counts table: <span class="math inline">\(|D| = 882\)</span>, <span class="math inline">\(|E| = 707\)</span>, <span class="math inline">\(|D\cap E| = 377\)</span>.</p>
<p><em>Step 2 (you).</em> Apply <span class="math inline">\(P(D\cup E)=P(D)+P(E)-P(D\cap E)\)</span>.</p>
<p><em>Step 3 (you).</em> Interpret the result in one sentence.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(P(D\cup E)=(882+707-377)/1441=1212/1441\approx 0.841\)</span>: about 84% of the recorded pitches reached an on-air deal, came from Seasons 1–8, or both.</p>
</div>
</div>
</div>
</section>
<section id="practice-15-minutes" class="level3">
<h3 class="anchored" data-anchor-id="practice-15-minutes">Practice (15 minutes)</h3>
<p>In the uniform selection experiment, use <span class="math inline">\(P(D)=882/1441\)</span>, <span class="math inline">\(P(L)=734/1441\)</span>, and <span class="math inline">\(P(D\cap L)=505/1441\)</span>.</p>
<ol type="1">
<li>Calculate and interpret <span class="math inline">\(P(D^c)\)</span>.</li>
<li>Calculate and interpret <span class="math inline">\(P(D\cup L)\)</span>.</li>
<li>Are <span class="math inline">\(D\)</span> and <span class="math inline">\(D^c\)</span> disjoint? Explain.</li>
<li>Define a random variable <span class="math inline">\(S\)</span> that records the season of the selected pitch. State its support.</li>
<li>Define a deal indicator <span class="math inline">\(X\)</span>. Explain how the event <span class="math inline">\(D\)</span> and the random variable <span class="math inline">\(X\)</span> are related but not the same object.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(P(D^c)=1-882/1441=559/1441\approx0.388\)</span>: 38.8% of the records did not reach an on-air agreement.</li>
<li><span class="math inline">\(P(D\cup L)=(882+734-505)/1441=1111/1441\approx0.771\)</span>: 77.1% of the records are from Seasons 9–16, reached an on-air deal, or satisfy both conditions.</li>
<li>They are disjoint because a record cannot simultaneously have and not have an on-air deal.</li>
<li><span class="math inline">\(S\)</span> records the season number of the selected pitch record. Its support is <span class="math inline">\(\{1,2,\ldots,16\}\)</span>.</li>
<li><span class="math inline">\(X\)</span> equals 1 when the selected pitch is in <span class="math inline">\(D\)</span> and 0 otherwise. <span class="math inline">\(D\)</span> is a set of outcomes; <span class="math inline">\(X\)</span> is a measurement rule that assigns a number to every outcome. They are related by <span class="math inline">\(D=\{X=1\}\)</span>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="spaced-review-one-item-from-lecture-1-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="spaced-review-one-item-from-lecture-1-5-minutes">Spaced review: one item from Lecture 1 (5 minutes)</h3>
<p>A student concludes: “Our class survey had 180 responses, so its average risk score describes Dutch first-year students well — with that many responses, chance variation is small.” Which problem does the size of the sample <em>not</em> fix?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Selection bias. A larger sample shrinks sampling variability, but the class is a convenience sample of one programme, not a random sample of Dutch first-year students. More responses from the same selected group do not make it more representative.</p>
</div>
</div>
</div>
</section>
<section id="worked-exam-interpretation-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="worked-exam-interpretation-10-minutes">Worked exam interpretation (10 minutes)</h3>
<p><strong>Question.</strong> R reports <code>mean(sharks$deal_on_show) = 0.612</code>. Is this an empirical proportion or a universal probability?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It is first an empirical proportion: 882 of the 1,441 recorded pitches reached an on-air agreement. It is also the event probability in a model that selects one of those 1,441 records uniformly. Applying it to a future entrepreneur requires additional population, selection, stability, and outcome assumptions.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Utility: two sentences</span></p>
<p>Think of your EiA venture — or any business you know well. Name one uncertain event that matters for it, and write two sentences: first define the event precisely (which outcomes count as “yes”?), then say what knowing its probability would change about a real decision. There is no wrong answer; the point is connecting today’s tools to something you care about.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run campus meal-prep box venture. “Let <span class="math inline">\(R\)</span> be the event that a first-time customer places a second order within 30 days — each order record either shows a repeat order in that window (yes) or does not. If <span class="math inline">\(P(R)\)</span> were known to be above 0.4, I would spend my small budget on loyalty rewards rather than new-customer ads.”</p>
</div>
</div>
</div>
<p>You can discuss this task — and any other task in this chapter — with <strong>Tilly</strong>, the course AI assistant on Canvas: ask it to challenge your event definition or to suggest what else you would need to know.</p>
</div>
<p>Continue to Lecture 3: Discrete distributions, expectation, and variance.</p>
<p>Formula sheet: Lecture 2 formulas.</p>
<p>For a more formal explanation, consult <a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>, Chapters 6–8 for probability models and random variables.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/b01-introduction-data-analysis.html" class="pagination-link" aria-label="Lecture 1: Introduction to Data Analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/b03-discrete-distributions.html" class="pagination-link" aria-label="Lecture 3: Discrete distributions, expectation, and variance">
        <span class="nav-page-text"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>