<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 4: Conditioning, Bayes’ rule, and independence – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/b05-joint-covariance-correlation.html" rel="next">
<link href="../basic/t01-exam-prep.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-130a4d33f88b74c424d8c0f2e9cca01a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b04-conditioning-bayes-independence.html"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 3: Normal models, sampling, and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and a first look at regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 4: Hypothesis tests, errors, and power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic Mock Exam</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate Mock Exam</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">QM Advanced</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Advanced: Course overview</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">External Video Guide</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#lecture-material" id="toc-lecture-material" class="nav-link" data-scroll-target="#lecture-material">Lecture material</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b04-conditioning-bayes-independence.html"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b04" class="quarto-section-identifier"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Lecture 4, you can</span></p>
<ul>
<li>calculate conditional probabilities and say which group each one refers to</li>
<li>rebuild an overall probability from the rates of separate groups</li>
<li>update a probability after new evidence with Bayes’ rule</li>
<li>check whether two events are independent and tell this apart from disjoint</li>
</ul>
</div>
<div class="driving-question">
<p><span class="label">Driving question</span></p>
<p class="dq-context">
An investor who learns that a pitch is from a late season updates their expectations. A bank that sees a fraud warning on a payment does the same. Updating chances after new information is a core probability skill in business. It is also easy to turn the question around by mistake.
</p>
<p>Late-season pitches reach deals more often. Two sentences about these pitches give the numbers 68.8% and 57.3%. What exactly does each sentence claim, and what does a positive flag from an AI tool that predicts deals really tell us?</p>
</div>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p>Do all the preparation below before class.</p>
<div class="video-prep">
<p><span class="label">Video preparation</span><br> Watch <a href="https://www.youtube.com/watch?v=MPRKc4UPoJk">Conditional Probabilities</a> and <a href="https://www.youtube.com/watch?v=kz2tvO_ZAKI">Bayes’ Rule</a>. Be ready to identify the reference class in a conditional probability and to explain why turning a condition around changes the denominator. All links are also listed in the <a href="../resources/video-guide.html">External Video Guide</a>. The videos explain key ideas in another way and can use a different notation. The lecture material and its notation always come first.</p>
</div>
<p><span class="shark-tag">Shark Tank data</span> <strong>Warm up.</strong> Lecture 2 built the counts table for deals and seasons from the Shark Tank file. Build it again. The events <span class="math inline">\(D\)</span> (on-air deal) and <span class="math inline">\(L\)</span> (late season) are defined as in Lecture 2:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span>   <span class="co"># on-air deal</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span>         <span class="co"># late season: Seasons 9-16</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">deal =</span> D, <span class="at">late =</span> L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then compare, in words only:</p>
<ul>
<li>“Among pitches in Seasons 9–16, what proportion reached an on-air deal?”</li>
<li>“Among pitches that reached an on-air deal, what proportion came from Seasons 9–16?”</li>
</ul>
<p>Both questions use the same cell of your table. Decide before class which part of the table each question looks at.</p>
<p><strong>Predict.</strong> Answer this question before you come to class. An AI classifier flags (marks) the pitches that are likely to get a deal. Of the pitches that it checks, only 10% reach a deal. The classifier flags 80% of the actual deals and also 20% of the non-deals. Of the flagged pitches, what share are deals: near 80%, near 50%, or near 30%? Choose one answer. You find the answer in the lecture material.</p>
<p>If fractions or event notation are unfamiliar, review <a href="../resources/math-refresher.html#sets-and-event-notation">Mathematics Refresher: sets and event notation</a> and <a href="../resources/math-refresher.html#fractions-and-rearranging-equations">fractions and rearranging equations</a>.</p>
</section>
<section id="lecture-material" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="lecture-material">Lecture material</h2>
<p>This section starts from one counts table. On that table it builds four tools: conditional probability, the law of total probability, Bayes’ rule, and independence of events.</p>
<section id="start-with-a-founders-question" class="level3">
<h3 class="anchored" data-anchor-id="start-with-a-founders-question">Start with a founder’s question</h3>
<p><span class="shark-tag">Shark Tank data</span> A founder hears that most deals on the show come from the later seasons. The founder concludes that a pitch in a later season is likely to end in a deal. Is that the same statement? Here are two sentences about the 1,441 pitches in the Shark Tank file:</p>
<ul>
<li><strong>Sentence A.</strong> “68.8% of late-season pitches reached an on-air deal.”</li>
<li><strong>Sentence B.</strong> “57.3% of the pitches that reached a deal came from the late seasons.”</li>
</ul>
<p>Both sentences use the same 505 records: the late-season pitches that reached a deal. But they answer different questions and give different numbers. This lecture shows what each sentence claims. It also answers a harder question of the same kind: when an AI classifier flags a pitch as a likely deal, how much should that flag change what you believe?</p>
</section>
<section id="one-table-five-probabilities" class="level3">
<h3 class="anchored" data-anchor-id="one-table-five-probabilities">One table, five probabilities</h3>
<p><span class="shark-tag">Shark Tank data</span> The starting point is the counts table from Lecture 2. The code builds the events <span class="math inline">\(D\)</span> (on-air deal, <code>deal_on_show</code>) and <span class="math inline">\(L\)</span> (late season, <code>season</code> 9 or higher) as before. Run it yourself:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span>   <span class="co"># on-air deal</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span>         <span class="co"># late season: Seasons 9-16</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">deal =</span> D, <span class="at">late =</span> L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       late
deal    FALSE TRUE
  FALSE   330  229
  TRUE    377  505</code></pre>
</div>
</div>
<p>Written with row and column totals:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 31%">
<col style="width: 28%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Early (<span class="math inline">\(L^c\)</span>, S1–8)</th>
<th style="text-align: right;">Late (<span class="math inline">\(L\)</span>, S9–16)</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>No deal</strong> (<span class="math inline">\(D^c\)</span>)</td>
<td style="text-align: right;">330</td>
<td style="text-align: right;">229</td>
<td style="text-align: right;"><strong>559</strong></td>
</tr>
<tr class="even">
<td><strong>Deal</strong> (<span class="math inline">\(D\)</span>)</td>
<td style="text-align: right;">377</td>
<td style="text-align: right;">505</td>
<td style="text-align: right;"><strong>882</strong></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>707</strong></td>
<td style="text-align: right;"><strong>734</strong></td>
<td style="text-align: right;"><strong>1441</strong></td>
</tr>
</tbody>
</table>
<p>Each of the five quantities below is a fraction of two counts. Before you read on, find in the table the count that goes on top and the count that goes underneath.</p>
<ol type="1">
<li><span class="math inline">\(P(D)\)</span>, the probability that a pitch reached a deal.</li>
<li><span class="math inline">\(P(L)\)</span>, the probability that a pitch is from the late seasons.</li>
<li><span class="math inline">\(P(D\cap L)\)</span>, the probability that a pitch is from the late seasons and reached a deal.</li>
<li>Among late-season pitches, the share that reached a deal.</li>
<li>Among pitches that reached a deal, the share that came from the late seasons.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your denominators
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(P(D)\)</span>: 882 deal records out of all 1,441 records.</li>
<li><span class="math inline">\(P(L)\)</span>: 734 late-season records out of all 1,441 records.</li>
<li><span class="math inline">\(P(D\cap L)\)</span>: 505 late-season deal records out of all 1,441 records.</li>
<li>Among late-season pitches, the share with a deal: 505 late-season deal records out of the 734 late-season records.</li>
<li>Among deal pitches, the share from the late seasons: 505 late-season deal records out of the 882 deal records.</li>
</ol>
<p>The first three all divide by 1,441, the number of all pitches. The last two divide by a part of the table. A share within a part of the table is called a conditional probability. The next section defines it.</p>
</div>
</div>
</div>
</section>
<section id="conditional-probability" class="level3">
<h3 class="anchored" data-anchor-id="conditional-probability">Conditional probability</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/conditional-probabilities/">02.2 Conditional Probabilities</a>.
</p>
<p><span class="shark-tag">Shark Tank data</span> Items 4 and 5 above ask the same kind of question: what is the probability of one event if you already know that another event happens? You answer both in two steps. First, keep only the pitches in one group. This group is called the <strong>reference class</strong>. Second, take the share of them in which the event happens. For item 4 the reference class is the 734 late-season pitches, and 505 of them reached a deal. Looking only at a reference class is called <strong>conditioning</strong> on it.</p>
<p>The symbol for this is a vertical bar, read as “given”. Item 4 is written <span class="math inline">\(P(D\mid L)\)</span>, “the probability of <span class="math inline">\(D\)</span> given <span class="math inline">\(L\)</span>”. Item 5 is written <span class="math inline">\(P(L\mid D)\)</span>. The event after the bar is always the reference class.</p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Conditional probability.</strong> The probability that event <span class="math inline">\(A\)</span> happens, given that event <span class="math inline">\(B\)</span> happens. For events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> with <span class="math inline">\(P(B)&gt;0\)</span>,</p>
<p><span class="math display">\[P(A\mid B)=\frac{P(A\cap B)}{P(B)}.\]</span></p>
<p>In words: keep only the outcomes in <span class="math inline">\(B\)</span>, then take the share of them that are also in <span class="math inline">\(A\)</span>.</p>
</div>
<p>The formula does the same two steps as the count. For item 4,</p>
<p><span class="math display">\[P(D\mid L)=\frac{P(D\cap L)}{P(L)}
=\frac{505/1441}{734/1441}=\frac{505}{734}.\]</span></p>
<p>The reference class gives the denominator. Dividing by <span class="math inline">\(P(B)\)</span> rescales the probabilities inside <span class="math inline">\(B\)</span> so that they add up to 1 again.</p>
<p>For a fixed event <span class="math inline">\(B\)</span>, conditional probabilities follow all three rules from Lecture 2. So every rule that Lecture 2 derived from them also holds inside the reference class. The condition is that the event after the bar stays the same in the whole calculation. Two examples follow. The first is the complement rule, <span class="math inline">\(P(A^c\mid B)=1-P(A\mid B)\)</span>. Among late-season pitches, the share without a deal is</p>
<p><span class="math display">\[P(D^c\mid L)=1-P(D\mid L)=1-\frac{505}{734}=\frac{229}{734}\approx 0.312.\]</span></p>
<p>The second is the addition rule. For two events <span class="math inline">\(A\)</span> and <span class="math inline">\(C\)</span> and the same reference class <span class="math inline">\(B\)</span>,</p>
<p><span class="math display">\[P(A\cup C\mid B)=P(A\mid B)+P(C\mid B)-P(A\cap C\mid B).\]</span></p>
<p>Some calculations mix different reference classes, for example <span class="math inline">\(P(A\mid B)\)</span> and <span class="math inline">\(P(A\mid B^c)\)</span>. For these you need the law of total probability, which a later section explains.</p>
<div id="exm-b04-conditional" class="theorem example">
<p><span class="theorem-title"><strong>Example 4.1 (Worked example: what each of the two sentences means)</strong></span> <span class="shark-tag">Shark Tank data</span> <strong>Sentence A asks about <span class="math inline">\(P(D\mid L)\)</span>.</strong> Conditioning on <span class="math inline">\(L\)</span> means that you hide everything except the Late column:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Early</th>
<th style="text-align: right;"><strong>Late (<span class="math inline">\(L\)</span>)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No deal</td>
<td style="text-align: right;">·</td>
<td style="text-align: right;"><strong>229</strong></td>
</tr>
<tr class="even">
<td>Deal</td>
<td style="text-align: right;">·</td>
<td style="text-align: right;"><strong>505</strong></td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">·</td>
<td style="text-align: right;"><strong>734</strong></td>
</tr>
</tbody>
</table>
<p>Within that one column, 505 of 734 records are deals:</p>
<p><span class="math display">\[P(D\mid L)=\frac{505}{734}\approx 0.688.\]</span></p>
<p><strong>Sentence B asks about <span class="math inline">\(P(L\mid D)\)</span>.</strong> Conditioning on <span class="math inline">\(D\)</span> means that you hide everything except the Deal row:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Early</th>
<th style="text-align: right;">Late</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No deal</td>
<td style="text-align: right;">·</td>
<td style="text-align: right;">·</td>
<td style="text-align: right;">·</td>
</tr>
<tr class="even">
<td><strong>Deal (<span class="math inline">\(D\)</span>)</strong></td>
<td style="text-align: right;"><strong>377</strong></td>
<td style="text-align: right;"><strong>505</strong></td>
<td style="text-align: right;"><strong>882</strong></td>
</tr>
</tbody>
</table>
<p>Within that one row, 505 of 882 records are late-season:</p>
<p><span class="math display">\[P(L\mid D)=\frac{505}{882}\approx 0.573.\]</span></p>
<p>The numerator is 505 in both calculations: the same cell of the table. The denominators differ, and so do the questions. Sentence A looks only at the 734 late-season pitches. Sentence B looks only at the 882 deal pitches.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: which sentence matches which number?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Sentence A (“of late-season pitches, … reached a deal”) conditions on the season, so it is <span class="math inline">\(P(D\mid L)=505/734\approx 68.8\%\)</span>. Sentence B (“of deal pitches, … came from late seasons”) conditions on the deal, so it is <span class="math inline">\(P(L\mid D)=505/882\approx 57.3\%\)</span>. A report that quotes “68.8% of deal pitches came from late seasons” has put the right number into the wrong sentence.</p>
</div>
</div>
</div>
<p>The same two numbers in R. <code>D[L]</code> keeps only the late-season pitches, and <code>L[D]</code> keeps only the deal pitches. This is the step that keeps only the reference class:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_deal_given_late =</span> <span class="fu">mean</span>(D[L]),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_late_given_deal =</span> <span class="fu">mean</span>(L[D])</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P_deal_given_late P_late_given_deal 
        0.6880109         0.5725624 </code></pre>
</div>
</div>
</section>
<section id="the-multiplication-rule" class="level3">
<h3 class="anchored" data-anchor-id="the-multiplication-rule">The multiplication rule</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/the-multiplication-rule/">02.6 The Multiplication Rule</a>.
</p>
<p><span class="shark-tag">Shark Tank data</span> The probability of an intersection, <span class="math inline">\(P(A\cap B)\)</span>, is also called a <strong>joint probability</strong>: both events happen together. Multiply both sides of the definition of conditional probability by <span class="math inline">\(P(B)\)</span>. The result is the <strong>multiplication rule</strong>. It builds a joint probability from a conditional one:</p>
<p><span class="math display">\[P(A\cap B)=P(A\mid B)\,P(B).\]</span></p>
<p>The same holds with the roles of <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> exchanged, because <span class="math inline">\(A\cap B\)</span> and <span class="math inline">\(B\cap A\)</span> are the same event:</p>
<p><span class="math display">\[P(A\cap B)=P(A\mid B)\,P(B)=P(B\mid A)\,P(A).\]</span></p>
<p>This line explains why the two sentences share a numerator and have different denominators. Both products equal <span class="math inline">\(505/1441\)</span>, but each one uses a different reference class.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it: verify the joint probability two ways
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="shark-tag">Shark Tank data</span> Try this first with the student next to you. Use the counts table of the section “One table, five probabilities” to check the equation above for <span class="math inline">\(D\)</span> (on-air deal) and <span class="math inline">\(L\)</span> (late season).</p>
<p><em>Step 1 (given).</em> The direct way: <span class="math inline">\(P(D\cap L)=505/1441\approx 0.350\)</span>.</p>
<p><em>Step 2 (given).</em> The first product: <span class="math inline">\(P(D\mid L)\,P(L)=\dfrac{505}{734}\cdot\dfrac{734}{1441}\)</span>. The 734 cancels. Cancel it and confirm that <span class="math inline">\(505/1441\)</span> is left.</p>
<p><em>Step 3 (you).</em> Write the second product, <span class="math inline">\(P(L\mid D)\,P(D)\)</span>, as two fractions from the table. Show that it also equals <span class="math inline">\(505/1441\)</span>.</p>
<p><em>Step 4 (you).</em> Confirm all three ways in R.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(P(L\mid D)\,P(D)=\dfrac{505}{882}\cdot\dfrac{882}{1441}=\dfrac{505}{1441}
\approx 0.350\)</span>. The 882 cancels, just as the 734 did.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">direct_joint            =</span> <span class="fu">mean</span>(D <span class="sc">&amp;</span> L),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">cond_on_late_times_base =</span> <span class="fu">mean</span>(D[L]) <span class="sc">*</span> <span class="fu">mean</span>(L),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">cond_on_deal_times_base =</span> <span class="fu">mean</span>(L[D]) <span class="sc">*</span> <span class="fu">mean</span>(D)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           direct_joint cond_on_late_times_base cond_on_deal_times_base 
              0.3504511               0.3504511               0.3504511 </code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-law-of-total-probability" class="level3">
<h3 class="anchored" data-anchor-id="the-law-of-total-probability">The law of total probability</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/total-probability-theorem/">02.7 Total Probability Theorem</a>.
</p>
<p><span class="shark-tag">Shark Tank data</span> Lecture 2 introduced a partition: events that do not overlap and together cover every outcome. The early seasons and the late seasons are a partition of the pitches. You can rebuild an overall probability from the parts of a partition in three steps. Take the conditional probability of <span class="math inline">\(A\)</span> within each part. Multiply it by the probability of that part, which gives a joint probability. Then add the joint probabilities.</p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Law of total probability.</strong> For a partition <span class="math inline">\(B_1,\ldots,B_k\)</span> with every <span class="math inline">\(P(B_i)&gt;0\)</span>,</p>
<p><span class="math display">\[P(A)=\sum_{i=1}^{k}P(A\mid B_i)\,P(B_i).\]</span></p>
<p>In words: the overall probability of <span class="math inline">\(A\)</span> is a weighted average of its probabilities within the groups. The weight of each group is the probability of that group.</p>
</div>
<p>With only two groups, <span class="math inline">\(B\)</span> and its complement <span class="math inline">\(B^c\)</span>, the sum has two terms:</p>
<p><span class="math display">\[P(A)=P(A\mid B)\,P(B)+P(A\mid B^c)\,P(B^c).\]</span></p>
<div id="exm-b04-total" class="theorem example">
<p><span class="theorem-title"><strong>Example 4.2 (Worked example: rebuilding P(D) from the deal rates of the two periods)</strong></span> <span class="shark-tag">Shark Tank data</span> The early and late events <span class="math inline">\(L^c\)</span> and <span class="math inline">\(L\)</span> form a partition, so</p>
<p><span class="math display">\[P(D)=P(D\mid L^c)\,P(L^c)+P(D\mid L)\,P(L)
=\frac{377}{707}\cdot\frac{707}{1441}
+\frac{505}{734}\cdot\frac{734}{1441}
=\frac{377+505}{1441}=\frac{882}{1441}\approx 0.612.\]</span></p>
<p>Two kinds of number appear here. <span class="math inline">\(377/707\approx 0.533\)</span> and <span class="math inline">\(505/734\approx 0.688\)</span> are the deal rates within each period. <span class="math inline">\(707/1441\approx 0.491\)</span> and <span class="math inline">\(734/1441\approx 0.509\)</span> are the weights: the share of all pitches that falls in each period. The overall deal probability is a weighted average of the two rates. So it must lie between 0.533 and 0.688, and it is a little closer to the rate of the larger group.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">direct       =</span> <span class="fu">mean</span>(D),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">from_periods =</span> <span class="fu">mean</span>(D[<span class="sc">!</span>L]) <span class="sc">*</span> <span class="fu">mean</span>(<span class="sc">!</span>L) <span class="sc">+</span> <span class="fu">mean</span>(D[L]) <span class="sc">*</span> <span class="fu">mean</span>(L)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      direct from_periods 
   0.6120749    0.6120749 </code></pre>
</div>
</div>
<p><a href="#fig-b04-partition-areas" class="quarto-xref">Figure&nbsp;<span>4.1</span></a> shows the same calculation as areas.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>p_early <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="sc">!</span>L)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>p_deal_early <span class="ot">&lt;-</span> <span class="fu">mean</span>(D[<span class="sc">!</span>L])</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>p_deal_late <span class="ot">&lt;-</span> <span class="fu">mean</span>(D[L])</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># light backgrounds: the two parts of the partition</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> <span class="dv">0</span>, <span class="at">xmax =</span> p_early, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> <span class="dv">1</span>,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> p_early, <span class="at">xmax =</span> <span class="dv">1</span>, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> <span class="dv">1</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="st">"#D55E00"</span>, <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># solid areas: deal rate within each part, times the part's width</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> <span class="dv">0</span>, <span class="at">xmax =</span> p_early, <span class="at">ymin =</span> <span class="dv">0</span>,</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">ymax =</span> p_deal_early, <span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> p_early, <span class="at">xmax =</span> <span class="dv">1</span>, <span class="at">ymin =</span> <span class="dv">0</span>,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>           <span class="at">ymax =</span> p_deal_late, <span class="at">fill =</span> <span class="st">"#D55E00"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> p_early, <span class="at">xend =</span> p_early, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">yend =</span> <span class="dv">1</span>,</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> <span class="dv">0</span>, <span class="at">xmax =</span> <span class="dv">1</span>, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> <span class="dv">1</span>,</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> p_early <span class="sc">/</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="fl">0.28</span>,</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"D ~ symbol('</span><span class="sc">\\</span><span class="st">307') ~ L^c"</span>, <span class="at">parse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">4.2</span>) <span class="sc">+</span></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> p_early <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> p_early) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="fl">0.36</span>,</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"D ~ symbol('</span><span class="sc">\\</span><span class="st">307') ~ L"</span>, <span class="at">parse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">4.2</span>) <span class="sc">+</span></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> p_early <span class="sc">/</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="fl">0.88</span>, <span class="at">label =</span> <span class="st">"L^c"</span>,</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>           <span class="at">parse =</span> <span class="cn">TRUE</span>, <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">4.4</span>) <span class="sc">+</span></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> p_early <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> p_early) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="fl">0.88</span>,</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"L"</span>, <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">4.4</span>) <span class="sc">+</span></span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.985</span>, <span class="at">y =</span> <span class="fl">0.955</span>, <span class="at">label =</span> <span class="st">"Omega"</span>,</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>           <span class="at">parse =</span> <span class="cn">TRUE</span>, <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.8</span>) <span class="sc">+</span></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b04-partition-areas" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b04-partition-areas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b04-conditioning-bayes-independence_files/figure-html/fig-b04-partition-areas-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b04-partition-areas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: Total probability as areas. The two columns are the early and late seasons, a partition of all pitches. The width of a column is the probability of that period (the weight). The height of the solid region is the deal rate within that period. The two solid areas do not overlap, and their sum is P(D).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="bayes-rule-count-first-formula-second" class="level3">
<h3 class="anchored" data-anchor-id="bayes-rule-count-first-formula-second">Bayes’ rule: count first, formula second</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/bayes-rule/">02.8 Bayes’ Rule</a>.
</p>
<p><span class="shark-tag">Shark Tank data</span> Return to the prediction question from before class. An AI classifier reads the transcripts of pitches (the written text of what was said) and flags (marks) the pitches that it considers likely to reach a deal. Three numbers describe an invented classifier of this kind:</p>
<ul>
<li>the <strong>base rate</strong>: 10% of the pitches that it checks reach a deal.</li>
<li>the <strong>sensitivity</strong>: among actual deals, 80% get flagged, <span class="math inline">\(P(\text{flag}\mid\text{deal})=0.80\)</span>.</li>
<li>the <strong>false-positive rate</strong>: among non-deals, 20% still get flagged, <span class="math inline">\(P(\text{flag}\mid\text{no deal})=0.20\)</span>.</li>
</ul>
<p>A pitch has just been flagged. How likely is a deal now: near 80%, 50%, or 30%? Count first, and use the formula afterwards.</p>
<div id="exm-b04-bayes-tree" class="theorem example">
<p><span class="theorem-title"><strong>Example 4.3 (Worked example: 1,000 imaginary pitches)</strong></span> Imagine 1,000 pitches and apply the three numbers to them one after the other, as in <a href="#fig-b04-bayes-tree" class="quarto-xref">Figure&nbsp;<span>4.2</span></a>.</p>
<ol type="1">
<li><strong>Split by the base rate.</strong> Of 1,000 pitches, 100 are deals and 900 are not.</li>
<li><strong>Flag the deals.</strong> Sensitivity 80%: of the 100 deals, 80 are flagged.</li>
<li><strong>Flag some non-deals too.</strong> False-positive rate 20%: of the 900 non-deals, 180 are flagged.</li>
<li><strong>Collect the flagged pitches.</strong> In total <span class="math inline">\(80+180=260\)</span> pitches have a flag, and only 80 of them are deals:</li>
</ol>
<p><span class="math display">\[P(\text{deal}\mid\text{flag})=\frac{80}{260}\approx 0.31.\]</span></p>
<p>The classifier finds 80% of deals, but fewer than a third of the flagged pitches are deals. The tree shows the reason. The 900 non-deals are a large group, so even a 20% false-positive rate produces 180 false flags. That is more than double the 80 true flags. A flag moves the deal probability from 10% to 31%. This is real evidence, but it is far from certainty.</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>See the drawing code (optional, not exam material)</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>old_par <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">no.readonly =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.2</span>, <span class="fl">0.2</span>, <span class="fl">0.2</span>))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NA</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="fl">9.7</span>), <span class="at">axes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">xaxs =</span> <span class="st">"i"</span>, <span class="at">yaxs =</span> <span class="st">"i"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>draw_node <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y, top, bottom, <span class="at">fill =</span> <span class="st">"white"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">border =</span> <span class="st">"#17324D"</span>, <span class="at">lwd =</span> <span class="fl">1.4</span>, <span class="at">w =</span> <span class="fl">1.05</span>, <span class="at">h =</span> <span class="fl">0.78</span>) {</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rect</span>(x <span class="sc">-</span> w, y <span class="sc">-</span> h, x <span class="sc">+</span> w, y <span class="sc">+</span> h, <span class="at">col =</span> fill, <span class="at">border =</span> border, <span class="at">lwd =</span> lwd)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">text</span>(x, y <span class="sc">+</span> <span class="fl">0.26</span>, top, <span class="at">font =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">1.0</span>, <span class="at">col =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">text</span>(x, y <span class="sc">-</span> <span class="fl">0.30</span>, bottom, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">col =</span> <span class="st">"#5B6976"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>draw_branch <span class="ot">&lt;-</span> <span class="cf">function</span>(x1, y1, x2, y2, label, <span class="at">above =</span> <span class="cn">TRUE</span>) {</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">segments</span>(x1, y1, x2, y2, <span class="at">col =</span> <span class="st">"#9AA7B2"</span>, <span class="at">lwd =</span> <span class="fl">1.6</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">text</span>((x1 <span class="sc">+</span> x2) <span class="sc">/</span> <span class="dv">2</span>, (y1 <span class="sc">+</span> y2) <span class="sc">/</span> <span class="dv">2</span> <span class="sc">+</span> <span class="cf">if</span> (above) <span class="fl">0.32</span> <span class="cf">else</span> <span class="sc">-</span><span class="fl">0.32</span>,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>       label, <span class="at">cex =</span> <span class="fl">0.76</span>, <span class="at">col =</span> <span class="st">"#5B6976"</span>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="co"># branches first, then boxes on top</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_branch</span>(<span class="fl">2.45</span>, <span class="fl">5.35</span>, <span class="fl">3.55</span>, <span class="fl">7.15</span>, <span class="st">"10% deal"</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_branch</span>(<span class="fl">2.45</span>, <span class="fl">4.65</span>, <span class="fl">3.55</span>, <span class="fl">2.85</span>, <span class="st">"90% no deal"</span>, <span class="at">above =</span> <span class="cn">FALSE</span>)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_branch</span>(<span class="fl">5.65</span>, <span class="fl">7.75</span>, <span class="fl">6.95</span>, <span class="fl">8.45</span>, <span class="st">"80% flagged"</span>)</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_branch</span>(<span class="fl">5.65</span>, <span class="fl">7.05</span>, <span class="fl">6.95</span>, <span class="fl">6.35</span>, <span class="st">"20% not"</span>, <span class="at">above =</span> <span class="cn">FALSE</span>)</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_branch</span>(<span class="fl">5.65</span>, <span class="fl">2.95</span>, <span class="fl">6.95</span>, <span class="fl">3.65</span>, <span class="st">"20% flagged"</span>)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_branch</span>(<span class="fl">5.65</span>, <span class="fl">2.25</span>, <span class="fl">6.95</span>, <span class="fl">1.55</span>, <span class="st">"80% not"</span>, <span class="at">above =</span> <span class="cn">FALSE</span>)</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_node</span>(<span class="fl">1.35</span>, <span class="fl">5.0</span>, <span class="st">"1,000"</span>, <span class="st">"pitches"</span>, <span class="at">w =</span> <span class="fl">1.15</span>)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_node</span>(<span class="fl">4.6</span>, <span class="fl">7.4</span>, <span class="st">"100"</span>, <span class="st">"deal"</span>)</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_node</span>(<span class="fl">4.6</span>, <span class="fl">2.6</span>, <span class="st">"900"</span>, <span class="st">"no deal"</span>)</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_node</span>(<span class="fl">8.0</span>, <span class="fl">8.6</span>, <span class="st">"80"</span>, <span class="st">"flagged"</span>, <span class="at">fill =</span> <span class="st">"#FDE5C1"</span>,</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>          <span class="at">border =</span> <span class="st">"#D55E00"</span>, <span class="at">lwd =</span> <span class="fl">2.2</span>)</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_node</span>(<span class="fl">8.0</span>, <span class="fl">6.2</span>, <span class="st">"20"</span>, <span class="st">"not flagged"</span>, <span class="at">fill =</span> <span class="st">"#F4F7F9"</span>,</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>          <span class="at">border =</span> <span class="st">"#9AA7B2"</span>)</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_node</span>(<span class="fl">8.0</span>, <span class="fl">3.8</span>, <span class="st">"180"</span>, <span class="st">"flagged"</span>, <span class="at">fill =</span> <span class="st">"#FDE5C1"</span>,</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>          <span class="at">border =</span> <span class="st">"#D55E00"</span>, <span class="at">lwd =</span> <span class="fl">2.2</span>)</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a><span class="fu">draw_node</span>(<span class="fl">8.0</span>, <span class="fl">1.4</span>, <span class="st">"720"</span>, <span class="st">"not flagged"</span>, <span class="at">fill =</span> <span class="st">"#F4F7F9"</span>,</span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>          <span class="at">border =</span> <span class="st">"#9AA7B2"</span>)</span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">9.55</span>, <span class="fl">6.2</span>, <span class="st">"260</span><span class="sc">\n</span><span class="st">flagged</span><span class="sc">\n</span><span class="st">in total"</span>, <span class="at">cex =</span> <span class="fl">0.82</span>, <span class="at">col =</span> <span class="st">"#D55E00"</span>)</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(old_par)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b04-bayes-tree" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b04-bayes-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b04-conditioning-bayes-independence_files/figure-html/fig-b04-bayes-tree-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b04-bayes-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: Tree of counts for 1,000 imaginary pitches. Orange boxes are the flagged pitches: 80 + 180 = 260 flags in total, of which only 80 are deals, so P(deal | flag) = 80/260, about 31%.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now the formula. The question turns a condition around. We describe the quality of the classifier with <span class="math inline">\(P(\text{flag}\mid\text{deal})\)</span>, but the person who makes the decision needs <span class="math inline">\(P(\text{deal}\mid\text{flag})\)</span>. The multiplication rule gives the numerator, and the law of total probability gives the denominator.</p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Bayes’ rule.</strong> A formula that turns a conditional probability around: from <span class="math inline">\(P(A\mid B)\)</span> to <span class="math inline">\(P(B\mid A)\)</span>. For events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> with positive probability,</p>
<p><span class="math display">\[P(B\mid A)=\frac{P(A\mid B)\,P(B)}{P(A)}.\]</span></p>
<p>When <span class="math inline">\(B_1,\ldots,B_k\)</span> form a partition, you can write out the denominator <span class="math inline">\(P(A)\)</span> with the law of total probability:</p>
<p><span class="math display">\[P(B_i\mid A)=\frac{P(A\mid B_i)\,P(B_i)}
{\sum_{j=1}^{k} P(A\mid B_j)\,P(B_j)}.\]</span></p>
</div>
<p>For the classifier, the partition is deal and no deal:</p>
<p><span class="math display">\[P(\text{deal}\mid\text{flag})
=\frac{0.80\times 0.10}{0.80\times 0.10+0.20\times 0.90}
=\frac{0.08}{0.08+0.18}=\frac{0.08}{0.26}\approx 0.308.\]</span></p>
<p>Every term is a branch of the tree, divided by 1,000:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Formula term</th>
<th style="text-align: right;">Value</th>
<th>Tree count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(P(\text{flag}\mid\text{deal})\,P(\text{deal})\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.08\)</span></td>
<td>the 80 flagged deals</td>
</tr>
<tr class="even">
<td><span class="math inline">\(P(\text{flag}\mid\text{no deal})\,P(\text{no deal})\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.18\)</span></td>
<td>the 180 flagged non-deals</td>
</tr>
<tr class="odd">
<td>the denominator (total probability of a flag)</td>
<td style="text-align: right;"><span class="math inline">\(0.26\)</span></td>
<td>all 260 flagged pitches</td>
</tr>
</tbody>
</table>
<p>The formula is a short way to write the tree. Drawing a tree and counting is a good way to solve a Bayes question. Use an imaginary total that is easy to calculate with, such as 1,000. The tree and the formula always give the same answer.</p>
<p>Bayes’ rule also works on the Shark Tank events. Starting from <span class="math inline">\(P(D\mid L)\)</span>, it gives <span class="math inline">\(P(L\mid D)\)</span>:</p>
<p><span class="math display">\[P(L\mid D)=\frac{P(D\mid L)\,P(L)}{P(D)}
=\frac{(505/734)(734/1441)}{882/1441}=\frac{505}{882}\approx 0.573.\]</span></p>
<p>The R check computes the same formula and compares it with the direct count from the table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>bayes_late_given_deal <span class="ot">&lt;-</span> <span class="fu">mean</span>(D[L]) <span class="sc">*</span> <span class="fu">mean</span>(L) <span class="sc">/</span> <span class="fu">mean</span>(D)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">from_bayes =</span> bayes_late_given_deal,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">from_table =</span> <span class="fu">mean</span>(L[D])</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>from_bayes from_table 
 0.5725624  0.5725624 </code></pre>
</div>
</div>
</section>
<section id="independence-of-events" class="level3">
<h3 class="anchored" data-anchor-id="independence-of-events">Independence of events</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/independence-of-two-events/">03.3 Independence of Two Events</a>.
</p>
<p><span class="shark-tag">Shark Tank data</span> Sometimes knowing that one event happened tells you nothing about another event. Lecture 2 mentioned this idea. Conditional probability makes it precise.</p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Independent events.</strong> Events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent when learning that <span class="math inline">\(B\)</span> happened does not change the probability of <span class="math inline">\(A\)</span>. For <span class="math inline">\(P(B)&gt;0\)</span>,</p>
<p><span class="math display">\[P(A\mid B)=P(A).\]</span></p>
<p>The same condition in <strong>product form</strong>:</p>
<p><span class="math display">\[P(A\cap B)=P(A)\,P(B).\]</span></p>
</div>
<p>The product form follows when you multiply both sides of the first equation by <span class="math inline">\(P(B)\)</span>. It treats <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> in the same way, and it also works when an event has probability zero. Events that are not independent are called dependent.</p>
<div id="exm-b04-independence" class="theorem example">
<p><span class="theorem-title"><strong>Example 4.4 (Worked example: are D and L independent?)</strong></span> Check both forms with the numbers from the counts table.</p>
<p>With conditioning: <span class="math inline">\(P(D\mid L)=505/734\approx 0.688\)</span>, while <span class="math inline">\(P(D)=882/1441\approx 0.612\)</span>. Learning that a pitch is late-season raises the deal probability, so <span class="math inline">\(D\)</span> and <span class="math inline">\(L\)</span> are not independent.</p>
<p>With the product form: <span class="math inline">\(P(D\cap L)=505/1441\approx 0.350\)</span>, while <span class="math display">\[P(D)\,P(L)=\frac{882}{1441}\cdot\frac{734}{1441}\approx 0.612\times0.509\approx 0.312.\]</span> The joint probability is larger than the product. This says the same thing: deals and late seasons occur together more often than they would under independence.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_D_given_L  =</span> <span class="fu">mean</span>(D[L]),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_D          =</span> <span class="fu">mean</span>(D),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_D_and_L    =</span> <span class="fu">mean</span>(D <span class="sc">&amp;</span> L),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_D_times_P_L =</span> <span class="fu">mean</span>(D) <span class="sc">*</span> <span class="fu">mean</span>(L)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  P_D_given_L           P_D     P_D_and_L P_D_times_P_L 
    0.6880109     0.6120749     0.3504511     0.3117717 </code></pre>
</div>
</div>
<p><strong>Disjoint is not independent.</strong> Take the early and late events <span class="math inline">\(L^c\)</span> and <span class="math inline">\(L\)</span>. They are disjoint: no pitch is in both periods, so <span class="math inline">\(P(L^c\cap L)=0\)</span>. But the product <span class="math inline">\(P(L^c)\,P(L)\approx 0.491\times 0.509\approx 0.25\)</span> is not zero, so the product check fails. Disjoint events with positive probability are always dependent. If you observe one of them, you know that the other did not happen. So one event tells you a lot about the other.</p>
</section>
<section id="second-application-deal-rates-by-team-composition" class="level3">
<h3 class="anchored" data-anchor-id="second-application-deal-rates-by-team-composition">Second application: deal rates by team composition</h3>
<p><span class="shark-tag">Shark Tank data</span> The variable <code>pitcher_gender_group</code> in the Shark Tank file puts each team that pitches into one of four groups: <code>all_men</code>, <code>all_women</code>, <code>mixed</code>, or <code>unknown</code>. The deal rate within a category is a conditional probability, <span class="math inline">\(P(D\mid \text{category})\)</span>, with the category as reference class. The code computes the three rates for the pitches with a known category:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>known_gender <span class="ot">&lt;-</span> sharks<span class="sc">$</span>pitcher_gender_group <span class="sc">!=</span> <span class="st">"unknown"</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>gender_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"all_men"</span>, <span class="st">"all_women"</span>, <span class="st">"mixed"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>gender_deal_rates <span class="ot">&lt;-</span> <span class="fu">tapply</span>(</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  sharks<span class="sc">$</span>deal_on_show[known_gender],</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(sharks<span class="sc">$</span>pitcher_gender_group[known_gender], <span class="at">levels =</span> gender_labels),</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  mean</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>gender_deal_rates</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  all_men all_women     mixed 
0.5808538 0.6363636 0.6630435 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>known_gender <span class="ot">&lt;-</span> sharks<span class="sc">$</span>pitcher_gender_group <span class="sc">!=</span> <span class="st">"unknown"</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>gender_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"all_men"</span>, <span class="st">"all_women"</span>, <span class="st">"mixed"</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>gender_deal_rates <span class="ot">&lt;-</span> <span class="fu">tapply</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  sharks<span class="sc">$</span>deal_on_show[known_gender],</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(sharks<span class="sc">$</span>pitcher_gender_group[known_gender], <span class="at">levels =</span> gender_labels),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  mean</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>gender_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(sharks<span class="sc">$</span>pitcher_gender_group[known_gender], <span class="at">levels =</span> gender_labels)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>rates_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">team =</span> <span class="fu">paste0</span>(<span class="fu">c</span>(<span class="st">"All-men"</span>, <span class="st">"All-women"</span>, <span class="st">"Mixed"</span>),</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>                <span class="st">"</span><span class="sc">\n</span><span class="st">(n = "</span>, <span class="fu">as.integer</span>(gender_counts), <span class="st">")"</span>),</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">deal_rate =</span> <span class="fu">as.numeric</span>(gender_deal_rates)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>rates_df<span class="sc">$</span>team <span class="ot">&lt;-</span> <span class="fu">factor</span>(rates_df<span class="sc">$</span>team, <span class="at">levels =</span> rates_df<span class="sc">$</span>team)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rates_df, <span class="fu">aes</span>(<span class="at">x =</span> team, <span class="at">y =</span> deal_rate)) <span class="sc">+</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>, <span class="at">colour =</span> <span class="st">"white"</span>,</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>           <span class="at">width =</span> <span class="fl">0.62</span>) <span class="sc">+</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> deal_rate, <span class="dv">1</span>), <span class="st">"%"</span>)),</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.6</span>, <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.6</span>) <span class="sc">+</span></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.75</span>),</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>                     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.75</span>, <span class="at">by =</span> <span class="fl">0.15</span>),</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">paste0</span>(<span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">75</span>, <span class="at">by =</span> <span class="dv">15</span>), <span class="st">"%"</span>),</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Source classification of pitching team"</span>,</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Pitches with an on-air deal"</span>) <span class="sc">+</span></span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b04-team-deal-rates" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b04-team-deal-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b04-conditioning-bayes-independence_files/figure-html/fig-b04-team-deal-rates-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b04-team-deal-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.3: Share of pitches with an on-air deal by team category (<code>pitcher_gender_group</code>), among the 1,434 Shark Tank pitches with a known category. Each bar is a percentage within its own category: P(deal | category). The three rates lie between 58% and 67%.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-b04-team-deal-rates" class="quarto-xref">Figure&nbsp;<span>4.3</span></a> shows three conditional proportions, each with its own denominator. The 63.6% bar means that 63.6% of the 385 pitches by all-women teams reached an on-air deal. The three bars use three different reference classes. They can still be compared, because each rate is a share within its own group.</p>
<div class="caveat-box">
<p><span class="label">What a conditional probability can and cannot say</span></p>
<ul>
<li>Turning a condition around changes the number. Neither number shows a cause. 68.8% of late-season pitches got a deal. That does not mean that late seasons cause deals.</li>
<li>The team comparison uses the broad groups of presenters that the data source defined. It also uses only pitches that the producers selected.</li>
<li>The classifier numbers are invented for the example.</li>
</ul>
<p><strong>What you can do with it:</strong> before you act on a signal, ask how often the outcome that you look for happens. With a low base rate, most signals are false alarms, so a cheap second check is worth its cost.</p>
</div>
</section>
<section id="answering-the-driving-question" class="level3">
<h3 class="anchored" data-anchor-id="answering-the-driving-question">Answering the driving question</h3>
<p>The two sentences make different claims about the same 505 records. “68.8% of late-season pitches reached a deal” is <span class="math inline">\(P(D\mid L)=505/734\)</span>, with the late seasons as reference class. “57.3% of deal pitches came from late seasons” is <span class="math inline">\(P(L\mid D)=505/882\)</span>, with the deals as reference class. Both are correct. The typical error is to use the number of one sentence in the other. A positive flag from the AI classifier tells us less than its 80% sensitivity suggests. With a 10% base rate and a 20% false-positive rate, only <span class="math inline">\(80/260\approx 31\%\)</span> of flagged pitches are deals. The flag raises the probability of a deal from 10% to 31%, and not more.</p>
<div class="founder-box">
<p><span class="label">A founder’s decision (invented example)</span></p>
<p>Your venture sells boxes of prepared meals by subscription, and you give away free trial boxes. One in ten trial customers becomes a subscriber. You notice a signal: 80% of later subscribers open your follow-up email, and 20% of the others open it too. Count with 1,000 trial customers. 100 become subscribers, and 80 of them open the email. Of the other 900, 180 open it. So 80 of 260 openers become subscribers, about 31%. A phone call costs you 2 euros of time, and a subscriber is worth 30 euros. A call to an opener is worth 0.31 × 30 = 9.30 euros on average, so you call the openers. Among the 740 who did not open, only 20 become subscribers, under 3%. A call to one of them is worth about 0.80 euros on average. The decision: call the openers and nobody else.</p>
</div>
<p><strong>Next:</strong> You can now update the probability of one event when another event is known. Lecture 5 looks at two random variables at the same time, for example the season of a pitch and the equity offered. It introduces two numbers that measure how two variables change together, the covariance and the correlation. It also shows what a correlation can and cannot tell you.</p>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p>After the lecture, work through all the practice below.</p>
<section id="read-the-lecture-material" class="level3">
<h3 class="anchored" data-anchor-id="read-the-lecture-material">Read the lecture material</h3>
<p>Read the Lecture material section above from start to end. The lecture covered the most important parts. The text has every step, every example, and all the code, including parts that were not shown in class. Note what is still unclear and bring it to the next tutorial, or ask Tilly.</p>
</section>
<section id="recall-questions" class="level3">
<h3 class="anchored" data-anchor-id="recall-questions">Recall questions</h3>
<ol type="1">
<li>What is the denominator of <span class="math inline">\(P(A\mid B)\)</span>?</li>
<li>Why is <span class="math inline">\(P(A\mid B)\)</span> generally different from <span class="math inline">\(P(B\mid A)\)</span>?</li>
<li>What makes a collection of events a partition?</li>
<li>What does the denominator in Bayes’ rule calculate?</li>
<li>State the two equivalent definitions of independence of events.</li>
<li>Can two disjoint events, each with positive probability, be independent?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(P(B)\)</span>, the probability of the conditioning event.</li>
<li>They condition on different reference classes, so they have different denominators.</li>
<li>No two parts overlap, and together they make up <span class="math inline">\(\Omega\)</span> (their union is <span class="math inline">\(\Omega\)</span>).</li>
<li>The total probability of the observed evidence, added across all parts of the partition.</li>
<li><span class="math inline">\(P(A\mid B)=P(A)\)</span> (learning <span class="math inline">\(B\)</span> does not change the probability of <span class="math inline">\(A\)</span>), and the product form <span class="math inline">\(P(A\cap B)=P(A)\,P(B)\)</span>.</li>
<li>No.&nbsp;Their intersection has probability 0 while the product of their probabilities is positive, so the product check fails. Observing one makes the other impossible.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="finish-a-half-worked-example-the-bayes-tree" class="level3">
<h3 class="anchored" data-anchor-id="finish-a-half-worked-example-the-bayes-tree">Finish a half-worked example: the Bayes tree</h3>
<p>Re-read the worked example with the tree of 1,000 pitches (<a href="#exm-b04-bayes-tree" class="quarto-xref">Example&nbsp;<span>4.3</span></a>). Then build the tree again for an AI classifier that flags pitches likely to get a deal, with new numbers. Of the checked pitches, 20% reach a deal (the base rate). The classifier flags 90% of the deals (the sensitivity) and 30% of the non-deals (the false-positive rate).</p>
<p><em>Step 1 (given).</em> Start with 1,000 imaginary pitches: 200 deals, 800 non-deals.</p>
<p><em>Step 2 (you).</em> Fill in the four boxes at the end of the tree: the flagged and the unflagged counts in each branch.</p>
<p><em>Step 3 (you).</em> Collect the flagged pitches and compute <span class="math inline">\(P(\text{deal}\mid\text{flag})\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Of the 200 deals, 90% are flagged: 180. Of the 800 non-deals, 30% are flagged: 240. Flagged total <span class="math inline">\(180+240=420\)</span>, of which 180 are deals: <span class="math inline">\(P(\text{deal}\mid\text{flag})=180/420\approx 0.429\)</span>. The formula agrees: <span class="math inline">\(\dfrac{0.90\times 0.20}{0.90\times 0.20+0.30\times 0.80}
=\dfrac{0.18}{0.42}\approx 0.429\)</span>.</p>
</div>
</div>
</div>
<p><strong>On your own.</strong> A more accurate classifier checks a group of pitches in which 5% reach a deal. Its sensitivity is 90% and its false-positive rate is 10%. What share of flagged pitches are deals? Use either the tree or the formula.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>With 1,000 pitches: 50 deals, of which 45 are flagged, and 950 non-deals, of which 95 are flagged. <span class="math inline">\(P(\text{deal}\mid\text{flag})=45/(45+95)=45/140\approx 0.321\)</span>. Even with 90% sensitivity and a low false-positive rate, the 5% base rate keeps the share of true flags below one third.</p>
</div>
</div>
</div>
</section>
<section id="practice" class="level3">
<h3 class="anchored" data-anchor-id="practice">Practice</h3>
<p><span class="shark-tag">Shark Tank data</span> Select one of the 1,441 recorded pitches at random. <span class="math inline">\(D\)</span> is the event of an on-air deal, and <span class="math inline">\(L\)</span> is the event of a late season (Seasons 9–16). Use the counts table of this lecture. Without a deal: 330 early-season and 229 late-season pitches (559 in total). With a deal: 377 early-season and 505 late-season pitches (882 in total). The early seasons have 707 pitches, the late seasons 734, and all seasons 1,441.</p>
<ol type="1">
<li>Use the early/late partition to verify <span class="math display">\[P(D)=P(D\mid L^c)\,P(L^c)+P(D\mid L)\,P(L).\]</span></li>
<li>Calculate and interpret <span class="math inline">\(P(L\mid D)\)</span>. Explain why it differs from <span class="math inline">\(P(D\mid L)\)</span>.</li>
<li>Decide by calculation whether <span class="math inline">\(D\)</span> and <span class="math inline">\(L\)</span> are independent, using the product form.</li>
<li>The events <span class="math inline">\(L^c\)</span> and <span class="math inline">\(L\)</span> are disjoint. Are they independent? Explain in one sentence.</li>
<li>Consider the 1,434 pitches with a known classification of the team. Of the 661 pitches with women represented (all-women or mixed), 428 reached an on-air deal. Of the 773 all-men pitches, 449 reached an on-air deal. Calculate both conditional deal proportions and interpret the difference.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\((377/707)(707/1441)+(505/734)(734/1441)=(377+505)/1441=882/1441
\approx 0.612\)</span>.</li>
<li><span class="math inline">\(P(L\mid D)=505/882\approx 0.573\)</span>: among deal records, 57.3% came from Seasons 9–16. It differs from <span class="math inline">\(P(D\mid L)=505/734\approx 0.688\)</span> because the conditioning event, and so the denominator, is different.</li>
<li><span class="math inline">\(P(D\cap L)=505/1441\approx 0.350\)</span>, while <span class="math inline">\(P(D)\,P(L)=(882/1441)(734/1441)\approx 0.312\)</span>. The two are not equal, so <span class="math inline">\(D\)</span> and <span class="math inline">\(L\)</span> are not independent.</li>
<li>No: <span class="math inline">\(P(L^c\cap L)=0\)</span> but <span class="math inline">\(P(L^c)\,P(L)\approx 0.25&gt;0\)</span>, so the product check fails. Disjoint events with positive probability are always dependent.</li>
<li><span class="math inline">\(428/661\approx 0.648\)</span> and <span class="math inline">\(449/773\approx 0.581\)</span>, a descriptive difference of about 6.7 percentage points. The data source defined the groups, and the producers chose the pitches for television. The difference does not show that the kind of team causes the deal.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="review-one-question-from-lecture-3" class="level3">
<h3 class="anchored" data-anchor-id="review-one-question-from-lecture-3">Review: one question from Lecture 3</h3>
<p>A variable <span class="math inline">\(Y\)</span> has PMF <span class="math inline">\(p_Y(0)=0.2\)</span>, <span class="math inline">\(p_Y(1)=0.5\)</span>, and <span class="math inline">\(p_Y(2)=0.3\)</span>. Calculate <span class="math inline">\(E[Y]\)</span> and say in one sentence what the number means. Can <span class="math inline">\(Y\)</span> ever equal it exactly?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(E[Y]=0(0.2)+1(0.5)+2(0.3)=1.1\)</span>. It is the probability-weighted average of the possible values, and the long-run average over many repetitions. It does not have to be a value that the variable can take: here <span class="math inline">\(Y\)</span> is never 1.1.</p>
</div>
</div>
</div>
</section>
<section id="worked-exam-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="worked-exam-interpretation">Worked exam interpretation</h3>
<p><span class="shark-tag">Shark Tank data</span> <strong>Question.</strong> Select one recorded Shark Tank pitch at random. <span class="math inline">\(D\)</span> is the event of an on-air deal, and <span class="math inline">\(L\)</span> is the event of a late season (Seasons 9–16). A student sees <span class="math inline">\(P(D\mid L)=0.688\)</span> and writes, “68.8% of deal pitches came from late seasons.” Explain what is wrong and give the correct interpretation.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The calculation conditions on <span class="math inline">\(L\)</span>, so the denominator is the 734 pitches in Seasons 9–16. The correct interpretation is that 68.8% of late-season records reached an on-air deal. The sentence the student wrote describes the reversed conditional probability, <span class="math inline">\(P(L\mid D)=505/882\approx 57.3\%\)</span>. Neither quantity measures completed investment or a causal season effect.</p>
</div>
</div>
</div>
</section>
<section id="check-the-ai" class="level3">
<h3 class="anchored" data-anchor-id="check-the-ai">Check the AI</h3>
<p><span class="shark-tag">Shark Tank data</span> You asked an AI assistant: “If a pitch got a deal, how likely is it that it came from a late season?” It answered:</p>
<blockquote class="blockquote">
<p>“68.8% of late-season pitches got a deal. So if a pitch got a deal, there is a 68.8% chance that it came from a late season.”</p>
</blockquote>
<p>Find what is wrong and write the corrected answer. This is the <strong>Verify</strong> step of Attempt → Ask → Verify → Explain.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The AI turned the condition around. 68.8% is the share of deals among late-season pitches, 505 of 734. The question asks for the share of late-season pitches among deals: 505 of 882, about 57.3%. Always ask which group is in the denominator.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours">Make it yours</h3>
<div class="utility-prompt">
<p><span class="label">Two sentences about your own venture</span></p>
<p>Think of your EiA venture, or any business you know well. Name one signal it receives about customers or partners, for example a positive review, a signed letter of intent, or a click on an ad. Sentence 1: which conditional probability does the signal make you want to know? Write it with the vertical bar and name the reference class. Sentence 2: which base rate would you need to know before you trust the signal? There is no wrong answer.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run venture that sells boxes of prepared meals on campus. “I want <span class="math inline">\(P(\text{becomes a paying customer} \mid \text{clicked the ad})\)</span>, where the reference class is the students who clicked the ad this month. Before I trust a high number of clicks, I would need the base rate of buyers among all students who saw the ad. With a very low base rate, most students who click still never buy, as the tree of 1,000 cases shows.”</p>
</div>
</div>
</div>
<p>You can discuss this task, and any other task in this chapter, with Tilly for QM Basic, the course AI assistant: ask it to build the tree of 1,000 cases for your signal with numbers you consider realistic.</p>
</div>
</section>
<section id="more-practice" class="level3">
<h3 class="anchored" data-anchor-id="more-practice">More practice</h3>
<p>For extra exercises on this lecture, with worked solutions, ask Tilly for QM Basic, the course AI assistant. For example: “Give me an extra exercise for Lecture 4. Show the solution only after I send my answer.”</p>
<p><a href="../basic/b05-joint-covariance-correlation.html">Continue to Lecture 5: Joint random variables, covariance, and correlation</a>.</p>
<p><a href="../basic/formula-sheet.html#formula-l4">Formula sheet: Lecture 4 formulas</a>.</p>
<p>For a more formal explanation, consult <a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>, Chapters 7–8.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/t01-exam-prep.html" class="pagination-link" aria-label="Tutorial 1: Evidence and probability foundations">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Tutorial 1: Evidence and probability foundations</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/b05-joint-covariance-correlation.html" class="pagination-link" aria-label="Lecture 5: Joint random variables, covariance, and correlation">
        <span class="nav-page-text"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>