<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 5: Joint random variables, covariance, and correlation – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/t02-exam-prep.html" rel="next">
<link href="../basic/b04-conditioning-bayes-independence.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ecf4e518a83458a2bb67b2a9bf74271b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b05-joint-covariance-correlation.html"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution, confidence intervals, and the two-sided test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Inference and tests against zero</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals betray it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/reading-ladder.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reading research papers</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-class" id="toc-in-class" class="nav-link" data-scroll-target="#in-class">In class</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b05-joint-covariance-correlation.html"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b05" class="quarto-section-identifier"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Lecture 5, you can</span></p>
<ul>
<li>define a pair of random variables on one sample space;</li>
<li>read a joint PMF and recover marginal and conditional distributions;</li>
<li>check independence of two random variables with the product rule in every cell of the joint table;</li>
<li>derive covariance from signed products of deviations and compute it two ways;</li>
<li>explain how correlation standardises covariance;</li>
<li>separate linear association from independence, causality, and importance.</li>
</ul>
</div>
<div class="driving-question">
<p><span class="label">Driving question</span></p>
<p class="dq-context">
Business questions are rarely about one variable alone: marketing and sales, price and demand, timing and success. The first analytical step is measuring whether two quantities move together at all, and how strongly.
</p>
<p>Deals and late seasons, equity offers and deals, seasons and equity offers. Which pairs move together, how strongly, and what does a correlation number license us to say?</p>
</div>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p><span class="time-budget">Total preparation time: about 30 minutes.</span></p>
<div class="video-prep">
<p><span class="label">Video preparation (20 minutes)</span><br> Watch <a href="https://www.youtube.com/watch?v=7nu97OYx4X4">Joint PMFs and the Expected Value Rule</a>, <a href="https://www.youtube.com/watch?v=K2Tlj27nkjs">Covariance</a>, and <a href="https://www.youtube.com/watch?v=HTs6Zhc2S1M">The Correlation Coefficient</a>. Be ready to state what a joint PMF records, what covariance averages, and how correlation standardises covariance. All links are also listed in the <a href="../resources/video-guide.html">External Video Guide</a>.</p>
</div>
<p><strong>Reactivate (5 minutes).</strong> From earlier lectures you know the deal indicator <span class="math inline">\(X\)</span> (1 for an on-air deal, 0 otherwise) and the late-period indicator <span class="math inline">\(Y\)</span> (1 for Seasons 9–16, 0 for Seasons 1–8). One selected pitch record now produces <em>two</em> numbers at once: the ordered pair <span class="math inline">\((X,Y)\)</span>. Write down all possible values of the pair.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Four ordered pairs: <span class="math inline">\((0,0)\)</span>, <span class="math inline">\((0,1)\)</span>, <span class="math inline">\((1,0)\)</span>, <span class="math inline">\((1,1)\)</span> — early no-deal, late no-deal, early deal, late deal. Order matters: <span class="math inline">\((1,0)\)</span> and <span class="math inline">\((0,1)\)</span> describe different pitches.</p>
</div>
</div>
</div>
<p><strong>Predict (5 minutes).</strong> Answer the one-click Mentimeter question posted on Canvas before you come to class: is the correlation between season and the equity percentage entrepreneurs initially offer <strong>positive</strong>, <strong>near zero</strong>, or <strong>negative</strong>? Commit to an answer; the lecture resolves it.</p>
<p>If ordered pairs, products, or standardisation are unfamiliar, review <a href="../resources/math-refresher.html">Mathematics Refresher: products, indices, and z-scores</a>.</p>
</section>
<section id="in-class" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-class">In class</h2>
<p>The session opens with the usual four-minute entry quiz on the prep videos, then turns to the driving question — three pairs of variables on one slide: deal and late period, equity offered and deal, season and equity offered. Every pair raises the same two questions: do the variables move together, and how strongly? Until now each random variable had its own distribution, studied alone. Two separate marginal distributions, however, cannot say how values are <em>paired</em>. For that we need the joint distribution.</p>
<section id="the-joint-probability-mass-function" class="level3">
<h3 class="anchored" data-anchor-id="the-joint-probability-mass-function">The joint probability mass function</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/joint-pmfs-and-the-expected-value-rule/">06.7 Joint PMFs and the Expected Value Rule</a>.
</p>
<p>For discrete random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> defined on the same experiment, the <strong>joint PMF</strong> records the probability of every possible pair of values:</p>
<p><span class="math display">\[p_{X,Y}(x,y)=P(X=x,\;Y=y).\]</span></p>
<p>Like any PMF it must be non-negative, and its entries must sum to 1 over every possible pair — each outcome lands in exactly one cell.</p>
<p>The live construction, with <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> built in full view:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show                <span class="co"># deal indicator: 1 = on-air deal</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span>)     <span class="co"># late-period indicator: 1 = S9-16</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>joint_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Deal =</span> X, <span class="at">Late_period =</span> Y)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>joint_pmf <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(joint_counts)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>joint_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Late_period
Deal   0   1
   0 330 229
   1 377 505</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(joint_pmf, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Late_period
Deal     0     1
   0 0.229 0.159
   1 0.262 0.350</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(joint_pmf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>As a table with the marginal sums written in:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(p_{X,Y}(x,y)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=0\)</span> (early)</th>
<th style="text-align: right;"><span class="math inline">\(Y=1\)</span> (late)</th>
<th style="text-align: right;">row sum: <span class="math inline">\(p_X(x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X=0\)</span> (no deal)</td>
<td style="text-align: right;">0.229</td>
<td style="text-align: right;">0.159</td>
<td style="text-align: right;"><strong>0.388</strong></td>
</tr>
<tr class="even">
<td><span class="math inline">\(X=1\)</span> (deal)</td>
<td style="text-align: right;">0.262</td>
<td style="text-align: right;">0.350</td>
<td style="text-align: right;"><strong>0.612</strong></td>
</tr>
<tr class="odd">
<td>column sum: <span class="math inline">\(p_Y(y)\)</span></td>
<td style="text-align: right;"><strong>0.491</strong></td>
<td style="text-align: right;"><strong>0.509</strong></td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: which entry is P(X = 1, Y = 1)?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The bottom-right cell of the joint table, 0.350: the probability that the selected pitch reached a deal <em>and</em> came from a late season, <span class="math inline">\(505/1441\approx 0.350\)</span>. It is one number for one pair of values — not a row, not a column.</p>
</div>
</div>
</div>
<section id="recovering-marginal-pmfs" class="level4">
<h4 class="anchored" data-anchor-id="recovering-marginal-pmfs">Recovering marginal PMFs</h4>
<p>Each single-variable distribution is recovered by summing the joint PMF over the values of the other variable:</p>
<p><span class="math display">\[p_X(x)=\sum_y p_{X,Y}(x,y),
\qquad
p_Y(y)=\sum_x p_{X,Y}(x,y).\]</span></p>
<p>Work it by hand on the table first — the arrows drawn in class point along a row and down a column: <span class="math inline">\(p_X(1)=0.262+0.350=0.612\)</span> (sum the <span class="math inline">\(X=1\)</span> row) and <span class="math inline">\(p_Y(1)=0.159+0.350=0.509\)</span> (sum the <span class="math inline">\(Y=1\)</span> column). These are exactly <span class="math inline">\(P(D)\)</span> and <span class="math inline">\(P(L)\)</span> from earlier lectures, now living in the margins of the joint table — which is why single-variable distributions are called <em>marginal</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>joint_pmf <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(<span class="at">Deal =</span> X, <span class="at">Late_period =</span> Y))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rowSums</span>(joint_pmf)   <span class="co"># marginal PMF of X</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        0         1 
0.3879251 0.6120749 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(joint_pmf)   <span class="co"># marginal PMF of Y</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        0         1 
0.4906315 0.5093685 </code></pre>
</div>
</div>
<p>The joint table determines the marginals, but not the other way round: many different joint tables share the same margins. What the joint table adds is the <em>pairing</em>.</p>
</section>
<section id="conditional-pmfs-are-rescaled-columns" class="level4">
<h4 class="anchored" data-anchor-id="conditional-pmfs-are-rescaled-columns">Conditional PMFs are rescaled columns</h4>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/conditional-pmfs/">07.2 Conditional PMFs</a>.
</p>
<p>Lecture 4’s conditioning idea transfers cell by cell. For <span class="math inline">\(p_Y(y)&gt;0\)</span>,</p>
<p><span class="math display">\[p_{X\mid Y}(x\mid y)=\frac{p_{X,Y}(x,y)}{p_Y(y)}.\]</span></p>
<div id="exm-b05-conditional" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.1 (Worked example: one conditional entry, by hand)</strong></span> What is <span class="math inline">\(p_{X\mid Y}(1\mid 1)\)</span> — the deal probability given a late-season pitch? Cover everything except the <span class="math inline">\(Y=1\)</span> column and rescale it by its own total:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(p_{X,Y}(x,y)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=0\)</span></th>
<th style="text-align: right;"><strong><span class="math inline">\(Y=1\)</span></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X=0\)</span></td>
<td style="text-align: right;">·</td>
<td style="text-align: right;"><strong>0.159</strong></td>
</tr>
<tr class="even">
<td><span class="math inline">\(X=1\)</span></td>
<td style="text-align: right;">·</td>
<td style="text-align: right;"><strong>0.350</strong></td>
</tr>
<tr class="odd">
<td>column sum</td>
<td style="text-align: right;">·</td>
<td style="text-align: right;"><strong>0.509</strong></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[p_{X\mid Y}(1\mid 1)=\frac{0.350}{0.509}
=\frac{505/1441}{734/1441}=\frac{505}{734}\approx 0.688.\]</span></p>
<p>This is precisely Lecture 4’s <span class="math inline">\(P(D\mid L)\)</span>: the 505-over-734 calculation, now read off a joint PMF. Dividing the whole column by 0.509 makes its entries sum to 1 — a rescaled column is a complete conditional distribution of <span class="math inline">\(X\)</span>.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>joint_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Deal =</span> X, <span class="at">Late_period =</span> Y)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(joint_counts, <span class="at">margin =</span> <span class="dv">2</span>), <span class="dv">3</span>)   <span class="co"># each column sums to 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Late_period
Deal     0     1
   0 0.467 0.312
   1 0.533 0.688</code></pre>
</div>
</div>
</section>
</section>
<section id="independence-of-random-variables" class="level3">
<h3 class="anchored" data-anchor-id="independence-of-random-variables">Independence of random variables</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/independence-of-random-variables/">07.4 Independence of Random Variables</a>.
</p>
<p>Lecture 4 defined independence for a <em>pair of events</em>: <span class="math inline">\(P(A\cap
B)=P(A)\,P(B)\)</span>. Random variables generate many events at once — one for every value they can take — so independence of random variables demands more. Discrete <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are <strong>independent</strong> when the product rule holds in <em>every</em> cell of the joint table:</p>
<p><span class="math display">\[p_{X,Y}(x,y)=p_X(x)\,p_Y(y)
\quad\text{for every pair } (x,y).\]</span></p>
<p>One mismatch anywhere proves dependence; establishing independence requires checking every cell.</p>
<div id="exm-b05-independence" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.2 (Worked example: the (1,1) cell check)</strong></span> If deal and late period were independent, the bottom-right cell would equal the product of its margins:</p>
<p><span class="math display">\[p_X(1)\,p_Y(1)=0.612\times 0.509\approx 0.312.\]</span></p>
<p>The actual entry is <span class="math inline">\(p_{X,Y}(1,1)=0.350\)</span>. The mismatch — 0.350 observed against 0.312 required — proves that <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are <strong>not independent</strong>: deals and late seasons are paired more often than independent variables would allow. This is the joint-PMF version of Lecture 4’s finding that <span class="math inline">\(P(D\mid L)\ne P(D)\)</span>.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>observed_joint_11 <span class="ot">&lt;-</span> <span class="fu">mean</span>(X <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> Y <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>independent_joint_11 <span class="ot">&lt;-</span> <span class="fu">mean</span>(X <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">mean</span>(Y <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">observed_joint_11 =</span> observed_joint_11,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">independent_joint_11 =</span> independent_joint_11)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   observed_joint_11 independent_joint_11 
           0.3504511            0.3117717 </code></pre>
</div>
</div>
<p>Had the <span class="math inline">\((1,1)\)</span> cell matched, the conclusion would still be open: one matching cell is not enough for independence, but one mismatching cell is enough for dependence.</p>
</section>
<section id="covariance-comes-from-expectation" class="level3">
<h3 class="anchored" data-anchor-id="covariance-comes-from-expectation">Covariance comes from expectation</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/covariance/">12.5 Covariance</a>.
</p>
<p>Independence versus dependence is a yes/no verdict. The next tool grades the dependence: in which <em>direction</em> do the variables move together, and how strongly? Lecture 3 measured spread as an expected squared deviation, <span class="math inline">\(\operatorname{Var}(X)=E[(X-\mu_X)^2]\)</span>. <strong>Covariance</strong> applies the same idea to a pair. With <span class="math inline">\(\mu_X=E[X]\)</span> and <span class="math inline">\(\mu_Y=E[Y]\)</span>,</p>
<p><span class="math display">\[\operatorname{Cov}(X,Y)=E[(X-\mu_X)(Y-\mu_Y)].\]</span></p>
<p>The object inside the expectation is a <em>signed product</em> of deviations, and the sign logic comes before any formula manipulation:</p>
<ul>
<li>both values above their means, or both below: the product is <strong>positive</strong>;</li>
<li>one above and one below: the product is <strong>negative</strong>.</li>
</ul>
<p>Covariance averages those signed products over the joint distribution. A positive covariance says above-average values of one variable tend to occur with above-average values of the other; a negative covariance says they tend to occur with below-average values.</p>
<div id="exm-b05-covariance" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.3 (Worked example: four signed products, one at a time)</strong></span> Take this small joint PMF (it returns in the practice sets):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\(Y=0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X=0\)</span></td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.20</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X=1\)</span></td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.40</td>
</tr>
</tbody>
</table>
<p>The marginals are <span class="math inline">\(p_X(1)=0.10+0.40=0.50\)</span> and <span class="math inline">\(p_Y(1)=0.20+0.40=0.60\)</span>, so <span class="math inline">\(\mu_X=E[X]=0.5\)</span> and <span class="math inline">\(\mu_Y=E[Y]=0.6\)</span>.</p>
<p>Write out the signed product of deviations for each cell, one by one:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Cell <span class="math inline">\((x,y)\)</span></th>
<th style="text-align: right;"><span class="math inline">\((x-0.5)(y-0.6)\)</span></th>
<th style="text-align: center;">Sign</th>
<th style="text-align: right;">Probability</th>
<th style="text-align: right;">Contribution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\((0,0)\)</span></td>
<td style="text-align: right;"><span class="math inline">\((-0.5)(-0.6)=+0.30\)</span></td>
<td style="text-align: center;">both below</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;"><span class="math inline">\(+0.090\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\((0,1)\)</span></td>
<td style="text-align: right;"><span class="math inline">\((-0.5)(+0.4)=-0.20\)</span></td>
<td style="text-align: center;">mixed</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;"><span class="math inline">\(-0.040\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\((1,0)\)</span></td>
<td style="text-align: right;"><span class="math inline">\((+0.5)(-0.6)=-0.30\)</span></td>
<td style="text-align: center;">mixed</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;"><span class="math inline">\(-0.030\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\((1,1)\)</span></td>
<td style="text-align: right;"><span class="math inline">\((+0.5)(+0.4)=+0.20\)</span></td>
<td style="text-align: center;">both above</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;"><span class="math inline">\(+0.080\)</span></td>
</tr>
</tbody>
</table>
<p>Average with the joint probabilities as weights:</p>
<p><span class="math display">\[\operatorname{Cov}(X,Y)=0.090-0.040-0.030+0.080=0.10.\]</span></p>
<p>The heavy cells are the two “agreeing” corners <span class="math inline">\((0,0)\)</span> and <span class="math inline">\((1,1)\)</span>, so the positive contributions dominate: this pair moves together.</p>
<p><strong>Verify with the computational form.</strong> Expanding the product gives the identity</p>
<p><span class="math display">\[\operatorname{Cov}(X,Y)=E[XY]-E[X]\,E[Y].\]</span></p>
<p>Here <span class="math inline">\(XY\)</span> is nonzero only in the <span class="math inline">\((1,1)\)</span> cell, so <span class="math inline">\(E[XY]=1\times 1\times
0.40=0.40\)</span>, and</p>
<p><span class="math display">\[\operatorname{Cov}(X,Y)=0.40-(0.5)(0.6)=0.40-0.30=0.10.\]</span></p>
<p>The same answer by both routes. The definition explains the sign; the computational form is quicker on an exam.</p>
</div>
<p>The same two routes on the Shark Tank pair, in visible code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>E_X <span class="ot">&lt;-</span> <span class="fu">mean</span>(X)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>E_Y <span class="ot">&lt;-</span> <span class="fu">mean</span>(Y)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>E_XY <span class="ot">&lt;-</span> <span class="fu">mean</span>(X <span class="sc">*</span> Y)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">E_X =</span> E_X,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">E_Y =</span> E_Y,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">E_XY =</span> E_XY,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">covariance_from_moments =</span> E_XY <span class="sc">-</span> E_X <span class="sc">*</span> E_Y,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">covariance_from_deviations =</span> <span class="fu">mean</span>((X <span class="sc">-</span> E_X) <span class="sc">*</span> (Y <span class="sc">-</span> E_Y))</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       E_X                        E_Y 
                0.61207495                 0.50936849 
                      E_XY    covariance_from_moments 
                0.35045108                 0.03867938 
covariance_from_deviations 
                0.03867938 </code></pre>
</div>
</div>
<p>Covariance has <strong>product units</strong>. If <span class="math inline">\(X\)</span> is measured in dollars and <span class="math inline">\(Y\)</span> in years, <span class="math inline">\(\operatorname{Cov}(X,Y)\)</span> is in dollar-years. Its sign is interpretable; its magnitude changes whenever either measurement unit changes, which makes raw covariances hard to compare.</p>
<section id="independence-implies-zero-covariance" class="level4">
<h4 class="anchored" data-anchor-id="independence-implies-zero-covariance">Independence implies zero covariance</h4>
<p>If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent, then <span class="math inline">\(E[XY]=E[X]\,E[Y]\)</span>, so <span class="math inline">\(\operatorname{Cov}(X,Y)=0\)</span>. The reverse is not generally true: zero covariance rules out linear co-movement, not every form of dependence.</p>
</section>
</section>
<section id="correlation-standardises-covariance" class="level3">
<h3 class="anchored" data-anchor-id="correlation-standardises-covariance">Correlation standardises covariance</h3>
<p class="concept-video">
<strong>MIT explanations (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/the-correlation-coefficient/">12.8 The Correlation Coefficient</a> and <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/interpreting-the-correlation-coefficient/">12.10 Interpreting the Correlation Coefficient</a>.
</p>
<p>The unit problem has a standard fix: divide by the two standard deviations. For variables whose standard deviations are not zero,</p>
<p><span class="math display">\[\rho_{XY}
=\frac{\operatorname{Cov}(X,Y)}
{\operatorname{SD}(X)\operatorname{SD}(Y)},
\qquad -1\le\rho_{XY}\le1.\]</span></p>
<p>Track the units: the numerator is in dollar-years, and the denominator is dollars times years — also dollar-years. They cancel, so <strong>correlation has no units</strong> and does not change when either variable is rescaled. Its sign gives the direction of linear association; its magnitude, between 0 and 1, gives the strength of linear association.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>cov_xy <span class="ot">&lt;-</span> <span class="fu">mean</span>((X <span class="sc">-</span> <span class="fu">mean</span>(X)) <span class="sc">*</span> (Y <span class="sc">-</span> <span class="fu">mean</span>(Y)))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>rho_xy <span class="ot">&lt;-</span> cov_xy <span class="sc">/</span> (<span class="fu">sqrt</span>(<span class="fu">mean</span>((X <span class="sc">-</span> <span class="fu">mean</span>(X))<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">*</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">sqrt</span>(<span class="fu">mean</span>((Y <span class="sc">-</span> <span class="fu">mean</span>(Y))<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">from_definition =</span> rho_xy,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">from_R =</span> <span class="fu">cor</span>(X, Y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>from_definition          from_R 
       0.158785        0.158785 </code></pre>
</div>
</div>
<p>The word <em>linear</em> carries real weight. <a href="#fig-b05-linear-curved" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> shows two patterns of the same size.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>x_association <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="at">length.out =</span> <span class="dv">61</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>y_linear <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">scale</span>(<span class="fl">0.8</span> <span class="sc">*</span> x_association <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                             <span class="fl">0.25</span> <span class="sc">*</span> <span class="fu">sin</span>(<span class="dv">7</span> <span class="sc">*</span> x_association)))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>y_curved <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">scale</span>(x_association<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>assoc_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">rep</span>(x_association, <span class="at">times =</span> <span class="dv">2</span>),</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>(y_linear, y_curved),</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">pattern =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Pattern A"</span>, <span class="st">"Pattern B"</span>), <span class="at">each =</span> <span class="dv">61</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>r_labels <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">pattern =</span> <span class="fu">c</span>(<span class="st">"Pattern A"</span>, <span class="st">"Pattern B"</span>),</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"r = "</span>, <span class="fu">sprintf</span>(<span class="st">"%.2f"</span>, <span class="fu">c</span>(</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cor</span>(x_association, y_linear),</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cor</span>(x_association, y_curved)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  ))),</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="sc">-</span><span class="dv">2</span>,</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">max</span>(assoc_df<span class="sc">$</span>y) <span class="sc">+</span> <span class="fl">0.45</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(assoc_df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.72</span>, <span class="at">size =</span> <span class="fl">1.8</span>) <span class="sc">+</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>              <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> r_labels, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">label =</span> label),</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> pattern) <span class="sc">+</span></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"X"</span>, <span class="at">y =</span> <span class="st">"Y (standardised units)"</span>) <span class="sc">+</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>),</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b05-linear-curved" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b05-linear-curved-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b05-joint-covariance-correlation_files/figure-html/fig-b05-linear-curved-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b05-linear-curved-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Correlation measures linear association only. Pattern A rises almost linearly and has r close to 1. Pattern B is strongly related but U-shaped: its fitted line is flat and its correlation is close to 0.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each point is one <span class="math inline">\((x,y)\)</span> pair; the orange line is the fitted linear summary. Pattern A follows an almost straight rising path, so its correlation is close to 1. Pattern B has a clear U-shaped relationship, but its fitted line is flat and its correlation is close to 0.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: which panel has correlation near zero — and why is that not “no relationship”?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Pattern B. Its correlation is near zero because rises on the right cancel falls on the left in the signed products — there is no <em>linear</em> trend. The relationship itself is strong: knowing <span class="math inline">\(x\)</span> pins down <span class="math inline">\(y\)</span> almost exactly. A near-zero correlation licenses only “no linear association,” never “no relationship.”</p>
</div>
</div>
</div>
<section id="sample-covariance-and-sample-correlation" class="level4">
<h4 class="anchored" data-anchor-id="sample-covariance-and-sample-correlation">Sample covariance and sample correlation</h4>
<p>For observed pairs <span class="math inline">\((x_i,y_i)\)</span>, the usual sample covariance is</p>
<p><span class="math display">\[s_{XY}=\frac{1}{n-1}\sum_{i=1}^{n}(x_i-\bar{x})(y_i-\bar{y}),\]</span></p>
<p>and the sample correlation is</p>
<p><span class="math display">\[r_{XY}=\frac{s_{XY}}{s_X s_Y}.\]</span></p>
<p>These are sample statistics, the two-variable analogues of <span class="math inline">\(s^2\)</span> and <span class="math inline">\(s\)</span> from Lecture 3. Under a model and sampling design, they may be used to estimate the population quantities <span class="math inline">\(\operatorname{Cov}(X,Y)\)</span> and <span class="math inline">\(\rho_{XY}\)</span>.</p>
<div class="optional-box">
<p><span class="label">Optional: point-biserial correlation</span><br> When one of the two variables is a 0/1 indicator — offered equity paired with the deal indicator, say — the ordinary Pearson correlation computed on the pair also goes by the name <em>point-biserial correlation</em>. It is not a new formula, only a special-case name you may meet in other courses; <code>cor()</code> computes it the same way.</p>
</div>
</section>
</section>
<section id="inspect-first-summarise-second" class="level3">
<h3 class="anchored" data-anchor-id="inspect-first-summarise-second">Inspect first, summarise second</h3>
<p>A correlation compresses a whole scatter of pairs into one number, so look at the scatter before trusting the number. For the season–equity pair (treating season as an equally spaced time index), <a href="#fig-b05-season-equity" class="quarto-xref">Figure&nbsp;<span>6.2</span></a> shows every pitch.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sharks, <span class="fu">aes</span>(<span class="at">x =</span> season, <span class="at">y =</span> equity_offered_pct)) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.14</span>, <span class="at">height =</span> <span class="dv">0</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">seed =</span> <span class="dv">2026</span>),</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.45</span>, <span class="at">size =</span> <span class="fl">1.6</span>) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">15</span>, <span class="at">by =</span> <span class="dv">2</span>), <span class="dv">16</span>)) <span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Season"</span>, <span class="at">y =</span> <span class="st">"Equity initially offered (%)"</span>) <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b05-season-equity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b05-season-equity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b05-joint-covariance-correlation_files/figure-html/fig-b05-season-equity-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b05-season-equity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Season and initially offered equity for all 1,441 pitches. Horizontal jitter only reveals overlapping points. The orange line is the fitted linear summary; its downward direction is the negative linear association that the correlation summarises.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each point represents one pitch: season is read horizontally and initially offered equity in percentage points vertically. The downward drift is visible but noisy — the large vertical spread shows why the line does not predict every pitch closely. Now the live correlations, resolving the prep prediction:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">season_with_equity_offered =</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cor</span>(sharks<span class="sc">$</span>season, sharks<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">equity_offered_with_deal =</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cor</span>(sharks<span class="sc">$</span>equity_offered_pct, sharks<span class="sc">$</span>deal_on_show)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>season_with_equity_offered   equity_offered_with_deal 
                -0.4157650                 -0.1128703 </code></pre>
</div>
</div>
<p>Season and initially offered equity have a moderate <strong>negative</strong> linear association, <span class="math inline">\(r\approx -0.42\)</span>: entrepreneurs in later seasons tend to offer smaller ownership stakes. If you predicted “negative” in the prep, the scatter and the number now back you up — and if not, the plot shows what the single number was hiding. Offered equity and the 0/1 deal indicator have a weak negative association, <span class="math inline">\(r\approx -0.11\)</span>.</p>
<div class="caveat-box">
<p><span class="label">What a correlation can and cannot say</span></p>
<p>The weak negative equity–deal correlation invites a tempting reading: “offer less equity and you are more likely to get a deal.” Three patterns coexist in this file: later seasons have higher deal proportions, later seasons have lower initial equity offers, and deal records have slightly lower offers on average. The marginal equity–deal association may therefore partly reflect differences <em>between seasons</em> rather than an effect of the offer itself — season is entangled with both variables. Offered equity was not randomly assigned, and the file records selected televised pitches, not a causal experiment. Separating the equity–deal association <em>within</em> a season from the season differences requires holding season fixed — exactly what multiple regression does in Intermediate Lecture 4. Until then: correlation alone does not establish causation, independence (only its absence), or practical importance.</p>
</div>
</section>
<section id="answering-the-driving-question" class="level3">
<h3 class="anchored" data-anchor-id="answering-the-driving-question">Answering the driving question</h3>
<p>Deal and late period move together: the joint entry 0.350 exceeds the independence benchmark 0.312, and their correlation is a mild positive <span class="math inline">\(r\approx 0.16\)</span>. Season and offered equity move oppositely, and moderately: <span class="math inline">\(r\approx -0.42\)</span>. Offered equity and deals barely move together at all, <span class="math inline">\(r\approx -0.11\)</span>, and the caveat box explains why even that number should not be read as advice. A correlation licenses a statement about the direction and strength of <em>linear</em> co-movement in these records — nothing about cause, and nothing about curved relationships.</p>
<p><strong>Next:</strong> Tutorial 2 turns Lectures 4 and 5 into exam practice: conditional probabilities read off tables, a Bayes tree with new numbers, and covariance and correlation computed and interpreted. Bring your attempted after-class tasks — especially the joint table and the signed-product routine, which the tutorial reuses directly. After the tutorial, Lecture 6 leaves whole numbers behind: quantities that can land anywhere in a range.</p>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p><span class="time-budget">Total practice time: about 70 minutes.</span></p>
<section id="retrieval-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="retrieval-10-minutes">Retrieval (10 minutes)</h3>
<ol type="1">
<li>What information does a joint PMF contain that two marginal PMFs do not?</li>
<li>How do you recover a marginal PMF from a joint PMF?</li>
<li>Why can covariance change when units change?</li>
<li>Why does independence imply zero covariance?</li>
<li>Why does zero correlation not imply independence?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>It records how values of the two variables occur together — the pairing, not just the two separate distributions.</li>
<li>Sum the joint PMF over every value of the other variable.</li>
<li>Covariance has product units, so rescaling either variable rescales the covariance.</li>
<li>Independence gives <span class="math inline">\(E[XY]=E[X]\,E[Y]\)</span>, hence zero covariance for the variables considered in this course.</li>
<li>Correlation measures linear association; dependent variables can have zero linear association (the U-shape in <a href="#fig-b05-linear-curved" class="quarto-xref">Figure&nbsp;<span>6.1</span></a>).</li>
</ol>
</div>
</div>
</div>
</section>
<section id="from-worked-to-faded-covariance-on-a-new-table-20-minutes" class="level3">
<h3 class="anchored" data-anchor-id="from-worked-to-faded-covariance-on-a-new-table-20-minutes">From worked to faded: covariance on a new table (20 minutes)</h3>
<p>Re-read the signed-products worked example (<a href="#exm-b05-covariance" class="quarto-xref">Example&nbsp;<span>6.3</span></a>). Then repeat the routine on a new joint PMF:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\(Y=0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X=0\)</span></td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.30</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X=1\)</span></td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.20</td>
</tr>
</tbody>
</table>
<p><em>Step 1 (given).</em> The marginals: <span class="math inline">\(p_X(1)=0.60\)</span>, <span class="math inline">\(p_Y(1)=0.50\)</span>, so <span class="math inline">\(\mu_X=0.6\)</span> and <span class="math inline">\(\mu_Y=0.5\)</span>.</p>
<p><em>Step 2 (you).</em> Write the four signed products <span class="math inline">\((x-0.6)(y-0.5)\)</span>, one per cell, with their signs.</p>
<p><em>Step 3 (you).</em> Weight each product by its cell probability and add.</p>
<p><em>Step 4 (you).</em> Verify with <span class="math inline">\(E[XY]-E[X]E[Y]\)</span> and interpret the sign.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Contributions: <span class="math inline">\((0,0)\)</span>: <span class="math inline">\((+0.30)(0.10)=+0.030\)</span>; <span class="math inline">\((0,1)\)</span>: <span class="math inline">\((-0.30)(0.30)=-0.090\)</span>; <span class="math inline">\((1,0)\)</span>: <span class="math inline">\((-0.20)(0.40)=-0.080\)</span>; <span class="math inline">\((1,1)\)</span>: <span class="math inline">\((+0.20)(0.20)=+0.040\)</span>. Sum: <span class="math inline">\(\operatorname{Cov}(X,Y)=0.030-0.090-0.080+0.040=-0.10\)</span>. Check: <span class="math inline">\(E[XY]=0.20\)</span> and <span class="math inline">\(E[X]E[Y]=0.6\times 0.5=0.30\)</span>, so <span class="math inline">\(0.20-0.30=-0.10\)</span>. The negative sign says the disagreeing corners are heavy: high <span class="math inline">\(X\)</span> tends to come with low <span class="math inline">\(Y\)</span>.</p>
</div>
</div>
</div>
<p><strong>Unassisted practice table.</strong> For the joint PMF</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\(Y=0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X=0\)</span></td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X=1\)</span></td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.35</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Find the marginal PMFs of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
<li>Are <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> independent?</li>
<li>Calculate <span class="math inline">\(\operatorname{Cov}(X,Y)\)</span> and interpret its sign.</li>
<li>Calculate <span class="math inline">\(P(X=1\mid Y=1)\)</span> and compare it with <span class="math inline">\(P(X=1)\)</span>.</li>
<li>Define <span class="math inline">\(Z=100X\)</span>. Calculate <span class="math inline">\(\operatorname{Cov}(Z,Y)\)</span> and state what happens to <span class="math inline">\(\operatorname{Corr}(Z,Y)\)</span>.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(P(X=0)=0.50\)</span>, <span class="math inline">\(P(X=1)=0.50\)</span>; <span class="math inline">\(P(Y=0)=0.40\)</span>, <span class="math inline">\(P(Y=1)=0.60\)</span>.</li>
<li>No.&nbsp;<span class="math inline">\(P(X=1,Y=1)=0.35\)</span>, whereas <span class="math inline">\(P(X=1)P(Y=1)=0.50\times 0.60=0.30\)</span>. One mismatching cell proves dependence.</li>
<li><span class="math inline">\(E[X]=0.50\)</span>, <span class="math inline">\(E[Y]=0.60\)</span>, <span class="math inline">\(E[XY]=0.35\)</span>, so <span class="math inline">\(\operatorname{Cov}(X,Y)=0.35-0.30=0.05\)</span>. Positive: the pair <span class="math inline">\((1,1)\)</span> occurs with greater probability than independence would give.</li>
<li><span class="math inline">\(P(X=1\mid Y=1)=0.35/0.60=7/12\approx 0.583\)</span>, larger than the marginal <span class="math inline">\(P(X=1)=0.50\)</span>: conditioning on <span class="math inline">\(Y=1\)</span> shifts the distribution of <span class="math inline">\(X\)</span> upward.</li>
<li><span class="math inline">\(\operatorname{Cov}(Z,Y)=100\operatorname{Cov}(X,Y)=5\)</span>. Multiplication by a positive constant rescales covariance but leaves correlation unchanged.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="spaced-review-two-items-from-earlier-lectures-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="spaced-review-two-items-from-earlier-lectures-10-minutes">Spaced review: two items from earlier lectures (10 minutes)</h3>
<p><strong>From Lecture 2.</strong> In the record-selection experiment, is “the selected pitch is the record with pitch_id 7” an outcome or an event? And what kind of object is the record itself?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The record itself is an <strong>outcome</strong> — one complete possible result. The description picks out the singleton set containing that record, and a set of outcomes is an <strong>event</strong>. Same distinction as 4 versus <span class="math inline">\(\{4\}\)</span> for a die.</p>
</div>
</div>
</div>
<p><strong>From Lecture 4.</strong> A classifier flags likely deals in a population with a 10% deal base rate; sensitivity is 70% and the false-positive rate is 20%. Using a 1,000-pitch tree, what share of flagged pitches are deals?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Of 100 deals, 70 are flagged; of 900 non-deals, 180 are flagged. So <span class="math inline">\(P(\text{deal}\mid\text{flag})=70/(70+180)=70/250=0.28\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="worked-exam-interpretation-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="worked-exam-interpretation-10-minutes">Worked exam interpretation (10 minutes)</h3>
<p>The dataset contains 1,441 televised pitches from Seasons 1–16. The variable <code>season</code> records the season number, and <code>equity_offered_pct</code> records the percentage of the business initially offered to the sharks.</p>
<p><strong>Question.</strong> R reports <code>cor(sharks$season, sharks$equity_offered_pct) = -0.416</code>. Interpret this result in context. State:</p>
<ol type="1">
<li>the direction and approximate strength of the linear association;</li>
<li>what the association means for pitches in earlier and later seasons;</li>
<li>whether the correlation has units; and</li>
<li>one conclusion that cannot be justified from this result.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Among the 1,441 records, season and initially offered equity have a moderate negative linear association: later-season pitches tend to offer a smaller ownership percentage initially, although this is not true of every individual pitch. The correlation is dimensionless: it has no units. It summarises only linear co-movement and does not show that the passage of time caused offers to change.</p>
</div>
</div>
</div>
</section>
<section id="exam-style-independence-and-covariance-sign-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="exam-style-independence-and-covariance-sign-5-minutes">Exam-style: independence and covariance sign (5 minutes)</h3>
<p>For the joint PMF</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\(Y=0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X=0\)</span></td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.42</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X=1\)</span></td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.28</td>
</tr>
</tbody>
</table>
<p>decide whether <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent, and state <span class="math inline">\(\operatorname{Cov}(X,Y)\)</span> without long calculation.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Marginals: <span class="math inline">\(P(X=1)=0.40\)</span>, <span class="math inline">\(P(Y=1)=0.70\)</span>. Check every cell: <span class="math inline">\(0.60\times 0.30=0.18\)</span>, <span class="math inline">\(0.60\times 0.70=0.42\)</span>, <span class="math inline">\(0.40\times 0.30=0.12\)</span>, <span class="math inline">\(0.40\times 0.70=0.28\)</span> — all four match, so <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are <strong>independent</strong>. Independence implies <span class="math inline">\(\operatorname{Cov}(X,Y)=0\)</span> (directly: <span class="math inline">\(E[XY]=0.28=E[X]E[Y]\)</span>). Note the contrast with the earlier tables: there one mismatch settled dependence; here independence needed all four cells.</p>
</div>
</div>
</div>
</section>
<section id="from-the-reading-ladder-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="from-the-reading-ladder-10-minutes">From the reading ladder (10 minutes)</h3>
<p>Next rung of the <a href="../resources/reading-ladder.html">reading ladder</a>: open <a href="https://doi.org/10.2307/3069429">Tierney &amp; Farmer (2002)</a> via the university library and find the table that reports means, standard deviations, and correlations among the study variables (in management journals this is usually the first numbered table). Pick any two variables: state their reported correlation, interpret its sign and rough strength in one sentence, and — as in today’s caveat — name one third variable that could produce that correlation without either variable driving the other. Note the sample size the table reports and why it matters for how seriously to take a small correlation.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your approach
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Whatever pair you chose, the sentence should have the form “employees higher in A tended also to be higher/lower in B in this sample (r = …)” — a statement about co-movement in one sample, not about causation and not about any individual. If your third-variable story was plausible (tenure, role, ability), you have applied the Lecture 5 box to a published table — which is precisely how you will read your thesis sources.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Utility: two sentences</span></p>
<p>Think of your EiA venture — or any business you know well. Name two quantities it could measure per customer, per week, or per order (marketing spend and sign-ups, price and basket size, delivery time and repeat purchases) and write two sentences: first predict the sign of their correlation and why; then name one third variable that could produce that correlation without either quantity driving the other. There is no wrong answer; the point is connecting today’s tools to something you care about.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run campus meal-prep box venture. “Weekly flyer spend and weekly sign-ups should correlate positively, since flyers reach students who have never heard of us. But exam weeks could produce that correlation on their own: I hand out more flyers in exam weeks, and students order more prepared food in exactly those weeks.”</p>
</div>
</div>
</div>
<p>You can discuss this task — and any other task in this chapter — with <strong>Tilly</strong>, the course AI assistant on Canvas: ask it to propose lurking third variables for your pair and pick the most plausible one.</p>
</div>
<p>Continue to Tutorial 2: Conditioning and relationships.</p>
<p>Formula sheet: Lecture 5 formulas.</p>
<p>For a more formal explanation, consult <a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>, Chapters 5 and 11.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/b04-conditioning-bayes-independence.html" class="pagination-link" aria-label="Lecture 4: Conditioning, Bayes' rule, and independence">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/t02-exam-prep.html" class="pagination-link" aria-label="Tutorial 2: Conditioning and relationships">
        <span class="nav-page-text"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>