<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 6: Continuous distributions and the normal model – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/b07-samples-estimators.html" rel="next">
<link href="../basic/t02-exam-prep.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1825cde5eff643560dd74da544ac5848.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b06-continuous-normal.html"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Inference and tests against zero</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#lecture-material" id="toc-lecture-material" class="nav-link" data-scroll-target="#lecture-material">Lecture material</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b06-continuous-normal.html"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b06" class="quarto-section-identifier"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Lecture 6, you can</span></p>
<ul>
<li>distinguish a continuous random variable from a discrete one</li>
<li>explain why <span class="math inline">\(P(X=x)=0\)</span> for a continuous random variable and interpret a probability density function as area rather than point probability</li>
<li>use a CDF to calculate interval probabilities</li>
<li>calculate uniform probabilities from interval lengths</li>
<li>standardise a normal value and compute normal probabilities by hand from supplied <span class="math inline">\(Z\)</span> values and with <code>pnorm()</code></li>
<li>convert a percentile back to a raw value with <span class="math inline">\(x=\mu+z\sigma\)</span> and verify with <code>qnorm()</code></li>
<li>find quantiles of model distributions (the uniform median, normal quartiles)</li>
<li>check a proposed normal model against a histogram of data and say when it fails.</li>
</ul>
</div>
<div class="must-know">
<p><span class="label">Must know</span></p>
<p><strong>Be able to do yourself:</strong></p>
<ul>
<li>calculate uniform probabilities from interval lengths</li>
<li>standardise a value and use the supplied <span class="math inline">\(Z\)</span> values, with the complement rule and the symmetry rule where needed</li>
<li>go back from a percentile to a value with <span class="math inline">\(x=\mu+z\sigma\)</span></li>
<li>say from a histogram whether a normal model fits.</li>
</ul>
<p><strong>Enough to recognise:</strong></p>
<ul>
<li>the density notation <span class="math inline">\(f_X(x)\)</span></li>
<li><code>pnorm()</code> and <code>qnorm()</code></li>
<li>the central 95% of the standard normal distribution, between <span class="math inline">\(-1.96\)</span> and <span class="math inline">\(1.96\)</span>.</li>
</ul>
</div>
<div class="driving-question">
<p><span class="label">Driving question</span></p>
<p class="dq-context">
Not everything comes in whole numbers: equity shares, waiting times, and revenues can take any value in a range. Insurers, lenders, and operations planners price risk on such quantities every day, and that needs a new kind of probability model.
</p>
<p>You plan to offer the sharks 30% of your company. How unusual is that, and can a model with two numbers answer the question without counting every pitch?</p>
</div>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p><span class="time-budget">Total preparation time: about 30 minutes.</span></p>
<p><strong>Minimum path:</strong> the video preparation and the prediction. <strong>Full path:</strong> everything in this section.</p>
<div class="video-prep">
<p><span class="label">Video preparation (20 minutes)</span><br> Watch <a href="https://www.youtube.com/watch?v=8QFpZ3FndBc">Probability Density Functions</a>, <a href="https://www.youtube.com/watch?v=jPB9zI8F7rE">Uniform and Piecewise Constant PDFs</a>, and <a href="https://www.youtube.com/watch?v=6UMv4vb4y7c">Normal Random Variables</a>. Focus on the difference between density height and probability, and on the roles of the two normal parameters. All links are also listed in the <a href="../resources/video-guide.html">External Video Guide</a>.</p>
</div>
<p><strong>Reactivate (5 minutes).</strong> A discrete random variable has separated possible values (Lecture 3 attached a PMF and a CDF to such variables). A continuous random variable can take every real value in an interval. Match each variable to the better description:</p>
<ol type="1">
<li>number of sharks in an on-air deal</li>
<li>equity offered, as an exact percentage of the company</li>
<li>season number</li>
<li>exact amount invested, before rounding to dollars.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Variables 1 and 3 are discrete. Variables 2 and 4 are continuous in a mathematical model, even if a measuring device or database records rounded values.</p>
</div>
</div>
</div>
<p><strong>Predict (5 minutes).</strong> Answer the one-click Wooclap question posted on Canvas before you come to class: for a <em>continuous</em> random variable <span class="math inline">\(X\)</span>, is <span class="math inline">\(P(X = \text{exactly } 10)\)</span> <strong>very small</strong> or <strong>exactly zero</strong>? Commit to an answer. You find the answer in the lecture material.</p>
<p>If fractions or rearranging an equation feel unfamiliar, review <a href="../resources/math-refresher.html#fractions-and-rearranging-equations">Mathematics Refresher: fractions and rearranging equations</a>. The same refresher has short parts on square roots and on inequalities.</p>
</section>
<section id="lecture-material" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="lecture-material">Lecture material</h2>
<p>This section builds probability models for quantities that can take any value in a range. It uses them to answer one question about the equity offered in the Shark Tank file.</p>
<section id="start-with-a-founders-question" class="level3">
<h3 class="anchored" data-anchor-id="start-with-a-founders-question">Start with a founder’s question</h3>
<p>You plan to offer the sharks 30% of your company. Is that unusual? The Shark Tank file records the equity offered in each pitch (<code>equity_offered_pct</code>). The code below reads the file and counts the pitches that offered 30% or more.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sharks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1441</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(sharks<span class="sc">$</span>equity_offered_pct <span class="sc">&gt;=</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 76</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct <span class="sc">&gt;=</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05274115</code></pre>
</div>
</div>
<p>In the file, 76 of the 1,441 pitches offered 30% or more, about 5%. Now suppose you did not have the file. You only knew two numbers about the offers: the mean and the standard deviation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean_equity =</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_equity   =</span> <span class="fu">sd</span>(sharks<span class="sc">$</span>equity_offered_pct))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mean_equity   sd_equity 
  13.207613    8.444355 </code></pre>
</div>
</div>
<p>The mean is 13.2% and the standard deviation is 8.4 percentage points. Could you still say how unusual 30% is? An AI assistant that gets this question will often answer with a model called the normal distribution, and it reports about 2%. That is less than half of the share in the data.</p>
<p>This lecture shows how such models work for quantities that can take any value in a range, how to calculate with them by hand, and how to check whether a model fits the data at hand. The check comes near the end, and it explains the gap between 2% and 5%.</p>
</section>
<section id="from-counting-values-to-measuring-intervals" class="level3">
<h3 class="anchored" data-anchor-id="from-counting-values-to-measuring-intervals">From counting values to measuring intervals</h3>
<p>Equity offered is a continuous quantity: an offer <span class="math inline">\(X\)</span> can be any percentage in a range, for example 29.87%. What is the probability that an offer is exactly 30%?</p>
<p>Take a window around 30. The offer lies between 29.5% and 30.5% with some probability <span class="math inline">\(q\)</span>. The window from 29.95% to 30.05% is ten times narrower. Over such a short range the probability is spread almost evenly, so this window holds about <span class="math inline">\(q/10\)</span>. Every further decimal divides the probability by about ten. The value “exactly 30%” lies inside every one of these windows, so its probability cannot be larger than any of theirs. Only zero is that small. For a continuous random variable,</p>
<p><span class="math display">\[P(X=x)=0 \quad\text{for every single value } x.\]</span></p>
<p>This answers the Wooclap question from the preparation: exactly zero, not very small. Probability has not disappeared. It belongs to intervals, not to single values.</p>
</section>
<section id="from-probability-mass-to-probability-density" class="level3">
<h3 class="anchored" data-anchor-id="from-probability-mass-to-probability-density">From probability mass to probability density</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/probability-density-functions/">08.2 Probability Density Functions</a>.
</p>
<p>For a discrete random variable, the PMF gives a probability to each single value. For a continuous variable that no longer works. Look at the two windows again. The probability fell from <span class="math inline">\(q\)</span> to about <span class="math inline">\(q/10\)</span>, and the width fell from 1 to 0.1 percentage points. Their ratio hardly changed:</p>
<p><span class="math display">\[\frac{q}{1}\approx\frac{q/10}{0.1}.\]</span></p>
<p>For narrow windows, the probability divided by the width is approximately constant. This ratio is the probability per unit of width near 30%. It is called the density at 30%, written <span class="math inline">\(f_X(30)\)</span>. The density takes the place of the PMF.</p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Probability density function (PDF).</strong> A curve <span class="math inline">\(f_X(x)\)</span> that is never negative and has a total area of 1 under it. The probability that <span class="math inline">\(X\)</span> lies between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> is the area under the curve between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>.</p>
</div>
<p>Three reading rules follow. The height of the curve is a rate, not a probability. The area over an interval is a probability. A rate can be high where the probability is packed into a narrow range, so a density can exceed 1, as long as the total area is 1. A metal rod gives the same picture: it has a weight per metre at each point, but no single point has weight.</p>
<p>The Shark Tank file records the equity offered in rounded percentages, so values repeat.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(sharks<span class="sc">$</span>equity_offered_pct <span class="sc">==</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 33</code></pre>
</div>
</div>
<p>In the file, 33 of the 1,441 pitches show exactly 30. That comes from rounding. The model is continuous.</p>
<p>You do not need calculus in this course. You read probability as an area, and you calculate it with a CDF, with R, or with supplied values.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Optional: the formal definition of a density
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A function <span class="math inline">\(f_X\)</span> is a density of the continuous random variable <span class="math inline">\(X\)</span> if it is never negative and has total area 1,</p>
<p><span class="math display">\[f_X(x)\ge 0 \ \text{ for every } x,
\qquad
\int_{-\infty}^{\infty} f_X(x)\,dx=1,\]</span></p>
<p>and if, for all values <span class="math inline">\(a\le b\)</span>,</p>
<p><span class="math display">\[P(a\le X\le b)=\int_a^b f_X(x)\,dx.\]</span></p>
<p>The integral is the area under the curve between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. For <span class="math inline">\(a=b\)</span> the area has zero width, which gives <span class="math inline">\(P(X=a)=0\)</span> again.</p>
<p>The normal distribution, which comes later in this lecture, has the density</p>
<p><span class="math display">\[f_X(x)=\frac{1}{\sigma\sqrt{2\pi}}\,
\exp\!\left(-\frac{(x-\mu)^2}{2\sigma^2}\right).\]</span></p>
<p>Nobody needs to memorise this formula. R evaluates it with <code>dnorm()</code>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: is a rectangle of width 0.5 and height 2 a valid density?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Yes. The curve is never negative and its total area is <span class="math inline">\(0.5 \times 2 = 1\)</span>, so it is a valid PDF. The height 2 is not a probability. No probability here exceeds 1, because every probability is an area inside that rectangle. The height 2 means that the probability is packed into a narrow range.</p>
</div>
</div>
</div>
<section id="the-cdf-works-for-every-random-variable" class="level4">
<h4 class="anchored" data-anchor-id="the-cdf-works-for-every-random-variable">The CDF works for every random variable</h4>
<p>The cumulative distribution function (CDF) is still</p>
<p><span class="math display">\[F_X(x)=P(X\le x),\]</span></p>
<p>exactly as in Lecture 3. In a picture, <span class="math inline">\(F_X(x)\)</span> is the area under the density to the left of <span class="math inline">\(x\)</span>. For a continuous random variable the CDF rises smoothly, without jumps, from 0 to 1. It never falls, because a move to the right can only add area. <a href="#fig-b06-uniform-cdf" class="quarto-xref">Figure&nbsp;<span>8.2</span></a> in the next section shows an example.</p>
<p>The probability of an interval is the difference of two CDF values:</p>
<p><span class="math display">\[P(a&lt;X\le b)=F_X(b)-F_X(a).\]</span></p>
<p>Because a single point has zero probability, changing <span class="math inline">\(&lt;\)</span> to <span class="math inline">\(\le\)</span> does not change a continuous probability: <span class="math inline">\(P(a&lt;X&lt;b)\)</span>, <span class="math inline">\(P(a\le X\le b)\)</span>, and the two mixed versions are all equal. This differs from a discrete variable, where a point may carry positive probability and the inequality type matters.</p>
</section>
</section>
<section id="the-uniform-distribution" class="level3">
<h3 class="anchored" data-anchor-id="the-uniform-distribution">The uniform distribution</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/uniform-piecewise-constant-pdfs">08.3 Uniform and Piecewise Constant PDFs</a>.
</p>
<p>The uniform distribution is the simplest continuous model. All possible values lie in an interval from <span class="math inline">\(a\)</span> to <span class="math inline">\(b\)</span>, and all parts of this interval with the same length are equally likely. We write <span class="math inline">\(X\sim U(a,b)\)</span>. The numbers <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are the parameters of the distribution. The interval <span class="math inline">\([a,b]\)</span> is the set of possible values, also called the support. The density is constant on the support,</p>
<p><span class="math display">\[f_X(x)=\frac{1}{b-a},\qquad a\le x\le b,\]</span></p>
<p>and zero outside it. The height is not a free choice. The whole rectangle must have area 1:</p>
<p><span class="math display">\[\text{width}\times\text{height}=(b-a)\times\frac{1}{b-a}=1.\]</span></p>
<p>Because the height is constant, the probability of an interval depends only on its length. For <span class="math inline">\(a\le c&lt;d\le b\)</span>,</p>
<p><span class="math display">\[P(c&lt;X&lt;d)=\frac{d-c}{b-a}.\]</span></p>
<p>The mean, the variance, and the standard deviation are stated here without derivation:</p>
<p><span class="math display">\[E[X]=\frac{a+b}{2},\qquad \operatorname{Var}(X)=\frac{(b-a)^2}{12},
\qquad \operatorname{SD}(X)=\frac{b-a}{\sqrt{12}}.\]</span></p>
<div id="exm-b06-uniform-session" class="theorem example">
<p><span class="theorem-title"><strong>Example 8.1 (Worked example: when does the pitch appear?)</strong></span> This is an invented example. A recording session lasts 90 minutes, and a pitch is equally likely to start at any moment of it. Model the start time as <span class="math inline">\(X\sim U(0,90)\)</span>, measured in minutes.</p>
<p><em>Step 1: the height.</em> The density is <span class="math inline">\(1/(90-0)=1/90\approx 0.011\)</span> per minute. The total area of 1 fixes this height.</p>
<p><em>Step 2: the event.</em> “The pitch starts during the 18-minute window from minute 30 to minute 48” is the event <span class="math inline">\(30&lt;X&lt;48\)</span>.</p>
<p><em>Step 3: the area.</em> The probability is the area of the shaded rectangle in <a href="#fig-b06-uniform-session" class="quarto-xref">Figure&nbsp;<span>8.1</span></a>:</p>
<p><span class="math display">\[P(30&lt;X&lt;48)=\frac{48-30}{90-0}=\frac{18}{90}=0.20.\]</span></p>
<p>For a uniform model, only the length of the window matters: any 18-minute window inside the session has probability 0.20.</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="dv">90</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>c_cut <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>d_cut <span class="ot">&lt;-</span> <span class="dv">48</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>density_height <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> (b <span class="sc">-</span> a)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>support_rect <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">c</span>(a, b), <span class="at">y =</span> density_height)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>window_rect  <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">c</span>(c_cut, d_cut), <span class="at">y =</span> density_height)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>density_line <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">9</span>, a, a, b, b, <span class="dv">99</span>),</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>                           <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, density_height, density_height, <span class="dv">0</span>, <span class="dv">0</span>))</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> support_rect, <span class="fu">aes</span>(x, y), <span class="at">fill =</span> <span class="st">"grey75"</span>, <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> window_rect, <span class="fu">aes</span>(x, y), <span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> density_line, <span class="fu">aes</span>(x, y), <span class="at">colour =</span> <span class="st">"#17324D"</span>,</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">66</span>, <span class="at">y =</span> <span class="fl">0.0127</span>,</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"density = 1/(b - a) = 1/90"</span>,</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> <span class="dv">39</span>, <span class="at">xend =</span> <span class="dv">39</span>, <span class="at">y =</span> <span class="fl">0.0042</span>, <span class="at">yend =</span> <span class="fl">0.0010</span>,</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>,</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>           <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.08</span>, <span class="st">"inches"</span>))) <span class="sc">+</span></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">39</span>, <span class="at">y =</span> <span class="fl">0.0052</span>,</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"area = P(30 &lt; X &lt; 48) = 0.20"</span>,</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(a, c_cut, d_cut, b),</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"a = 0"</span>, <span class="st">"c = 30"</span>, <span class="st">"d = 48"</span>, <span class="st">"b = 90"</span>),</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, density_height),</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1/90"</span>),</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.0145</span>),</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Minutes into the session"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b06-uniform-session" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b06-uniform-session-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b06-continuous-normal_files/figure-html/fig-b06-uniform-session-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b06-uniform-session-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: The uniform density for a pitch start time over a 90-minute session. The navy line is the density. The shaded green area is the probability of the 18-minute window, 18/90 = 0.20.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Read the horizontal axis as possible start times and the vertical axis as density, not probability. The navy density line is at 0 before minute 0, jumps to <span class="math inline">\(1/90\)</span> on the support, and drops back to 0 after minute 90. The green probability is an area: <span class="math inline">\(18\times(1/90)=0.20\)</span>. Compare this with the check above: here the height is far below 1, there it was 2. Both densities are valid, because only the area is a probability.</p>
<section id="the-cdf-of-the-session-model" class="level4">
<h4 class="anchored" data-anchor-id="the-cdf-of-the-session-model">The CDF of the session model</h4>
<p>For the session model, the area to the left of <span class="math inline">\(x\)</span> is a rectangle of width <span class="math inline">\(x\)</span> and height <span class="math inline">\(1/90\)</span>. So the CDF is <span class="math inline">\(F_X(x)=x/90\)</span> for <span class="math inline">\(0\le x\le 90\)</span>. It is 0 before minute 0 and 1 after minute 90. <a href="#fig-b06-uniform-cdf" class="quarto-xref">Figure&nbsp;<span>8.2</span></a> shows it. The probability of the window is the difference of two CDF values:</p>
<p><span class="math display">\[P(30&lt;X&lt;48)=F_X(48)-F_X(30)=\frac{48}{90}-\frac{30}{90}=0.20.\]</span></p>
<p>This is the same 0.20 as the green area in <a href="#fig-b06-uniform-session" class="quarto-xref">Figure&nbsp;<span>8.1</span></a>.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="dv">90</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>c_cut <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>d_cut <span class="ot">&lt;-</span> <span class="dv">48</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>F_c <span class="ot">&lt;-</span> (c_cut <span class="sc">-</span> a) <span class="sc">/</span> (b <span class="sc">-</span> a)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>F_d <span class="ot">&lt;-</span> (d_cut <span class="sc">-</span> a) <span class="sc">/</span> (b <span class="sc">-</span> a)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>cdf_line <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">9</span>, a, b, <span class="dv">99</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> <span class="fu">c</span>(c_cut, d_cut), <span class="at">xend =</span> <span class="fu">c</span>(c_cut, d_cut),</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> <span class="dv">0</span>, <span class="at">yend =</span> <span class="fu">c</span>(F_c, F_d),</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"#C98B2E"</span>, <span class="at">linewidth =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> <span class="sc">-</span><span class="dv">9</span>, <span class="at">xend =</span> <span class="fu">c</span>(c_cut, d_cut),</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> <span class="fu">c</span>(F_c, F_d), <span class="at">yend =</span> <span class="fu">c</span>(F_c, F_d),</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>           <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"#C98B2E"</span>, <span class="at">linewidth =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> cdf_line, <span class="fu">aes</span>(x, y), <span class="at">colour =</span> <span class="st">"#17324D"</span>,</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> <span class="dv">6</span>, <span class="at">xend =</span> <span class="dv">6</span>, <span class="at">y =</span> F_c, <span class="at">yend =</span> F_d,</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#009E73"</span>, <span class="at">linewidth =</span> <span class="fl">1.6</span>) <span class="sc">+</span></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">8</span>, <span class="at">y =</span> (F_c <span class="sc">+</span> F_d) <span class="sc">/</span> <span class="dv">2</span>,</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"difference = 0.20"</span>, <span class="at">colour =</span> <span class="st">"#17324D"</span>,</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>           <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">66</span>, <span class="at">y =</span> <span class="fl">0.58</span>, <span class="at">label =</span> <span class="st">"F(x) = x/90"</span>,</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(a, c_cut, d_cut, b), <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, F_c, F_d, <span class="dv">1</span>),</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"F(30) = 0.33"</span>, <span class="st">"F(48) = 0.53"</span>, <span class="st">"1"</span>),</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1.05</span>), <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Minutes into the session (x)"</span>,</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Cumulative probability F(x)"</span>) <span class="sc">+</span></span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b06-uniform-cdf" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b06-uniform-cdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b06-continuous-normal_files/figure-html/fig-b06-uniform-cdf-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b06-uniform-cdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: The CDF of the pitch start time in the 90-minute session model. The navy line rises from 0 to 1 and never falls. The gold dashed lines read off F(30) and F(48). Their difference, the green bar, is the probability of the 18-minute window, 0.20.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it: the final stretch of the session
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Try this with your neighbour first. Same model, <span class="math inline">\(X\sim U(0,90)\)</span>. What is the probability that the pitch starts in the final 27 minutes of the session?</p>
<p><em>Step 1 (given).</em> The event is <span class="math inline">\(63&lt;X&lt;90\)</span>, an interval of length <span class="math inline">\(90-63=27\)</span> minutes inside the support.</p>
<p><em>Step 2 (you).</em> Divide the interval length by the support length.</p>
<p><em>Step 3 (you).</em> Interpret the result in one sentence.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(P(63&lt;X&lt;90)=27/90=0.30\)</span>: under the uniform model there is a 30% chance the pitch starts in the final 27 minutes, larger than the 0.20 above only because the window is longer.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="the-normal-distribution" class="level3">
<h3 class="anchored" data-anchor-id="the-normal-distribution">The normal distribution</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/normal-random-variables/">08.8 Normal Random Variables</a>.
</p>
<p>Many quantities are the sum of many small influences: body height, measurement errors, the weight of a filled package. Such quantities often have a bell-shaped distribution, with most values near the middle and few values far away on either side. The normal distribution is the model for this shape. It is a model, not a law. Many business variables, such as revenues, are strongly skewed and do not follow it.</p>
<p>A normal model needs two numbers. The first is its mean <span class="math inline">\(\mu\)</span>. The second is its standard deviation <span class="math inline">\(\sigma\)</span>. Lecture 3 introduced both symbols.</p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Normal distribution.</strong> A continuous distribution with a symmetric, bell-shaped density. Its centre is the mean <span class="math inline">\(\mu\)</span>, and its spread is the standard deviation <span class="math inline">\(\sigma&gt;0\)</span>. We write <span class="math inline">\(X\sim N(\mu,\sigma^2)\)</span>.</p>
</div>
<p>Read the notation with care: the second number in the brackets is the variance <span class="math inline">\(\sigma^2\)</span>, not the standard deviation. For example, <span class="math inline">\(N(50,100)\)</span> has <span class="math inline">\(\sigma=\sqrt{100}=10\)</span>. In symbols,</p>
<p><span class="math display">\[E[X]=\mu,\qquad \operatorname{Var}(X)=\sigma^2,
\qquad \operatorname{SD}(X)=\sigma.\]</span></p>
<p>The two parameters do different jobs, as <a href="#fig-b06-normal-parameters" class="quarto-xref">Figure&nbsp;<span>8.3</span></a> shows. A change in <span class="math inline">\(\mu\)</span> shifts the whole curve to the left or to the right, and the shape stays the same. A change in <span class="math inline">\(\sigma\)</span> makes the curve wider or narrower. A wider curve is also lower, because the total area stays 1.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>x_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">8</span>, <span class="at">length.out =</span> <span class="dv">600</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>panel_shift <span class="ot">&lt;-</span> <span class="st">"Changing the mean shifts the curve"</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>panel_width <span class="ot">&lt;-</span> <span class="st">"Changing the SD widens the curve"</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>curves <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">panel =</span> panel_shift, <span class="at">curve =</span> <span class="st">"first"</span>, <span class="at">x =</span> x_grid,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">density =</span> <span class="fu">dnorm</span>(x_grid, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)),</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">panel =</span> panel_shift, <span class="at">curve =</span> <span class="st">"second"</span>, <span class="at">x =</span> x_grid,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">density =</span> <span class="fu">dnorm</span>(x_grid, <span class="at">mean =</span> <span class="dv">3</span>, <span class="at">sd =</span> <span class="dv">1</span>)),</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">panel =</span> panel_width, <span class="at">curve =</span> <span class="st">"first"</span>, <span class="at">x =</span> x_grid,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">density =</span> <span class="fu">dnorm</span>(x_grid, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)),</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">panel =</span> panel_width, <span class="at">curve =</span> <span class="st">"second"</span>, <span class="at">x =</span> x_grid,</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">density =</span> <span class="fu">dnorm</span>(x_grid, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">2</span>))</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>curves<span class="sc">$</span>panel <span class="ot">&lt;-</span> <span class="fu">factor</span>(curves<span class="sc">$</span>panel, <span class="at">levels =</span> <span class="fu">c</span>(panel_shift, panel_width))</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>curve_labels <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">panel =</span> <span class="fu">factor</span>(<span class="fu">c</span>(panel_shift, panel_shift, panel_width, panel_width),</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>                 <span class="at">levels =</span> <span class="fu">c</span>(panel_shift, panel_width)),</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">curve =</span> <span class="fu">c</span>(<span class="st">"first"</span>, <span class="st">"second"</span>, <span class="st">"first"</span>, <span class="st">"second"</span>),</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.2</span>, <span class="fl">4.2</span>, <span class="fl">1.1</span>, <span class="fl">3.3</span>),</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>(<span class="fl">0.36</span>, <span class="fl">0.36</span>, <span class="fl">0.36</span>, <span class="fl">0.12</span>),</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"mu == 0*','~sigma == 1"</span>, <span class="st">"mu == 3*','~sigma == 1"</span>,</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>            <span class="st">"mu == 0*','~sigma == 1"</span>, <span class="st">"mu == 0*','~sigma == 2"</span>),</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">hjust =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(curves, <span class="fu">aes</span>(x, density, <span class="at">colour =</span> curve)) <span class="sc">+</span></span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> curve_labels, <span class="fu">aes</span>(x, y, <span class="at">label =</span> label, <span class="at">hjust =</span> hjust),</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>            <span class="at">parse =</span> <span class="cn">TRUE</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>panel) <span class="sc">+</span></span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">first =</span> <span class="st">"#009E73"</span>, <span class="at">second =</span> <span class="st">"#D55E00"</span>),</span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a>                      <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">8</span>, <span class="at">by =</span> <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.43</span>),</span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.02</span>))) <span class="sc">+</span></span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Value of X"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb13-43"><a href="#cb13-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb13-44"><a href="#cb13-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb13-45"><a href="#cb13-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb13-46"><a href="#cb13-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>),</span>
<span id="cb13-47"><a href="#cb13-47" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">hjust =</span> <span class="dv">0</span>)</span>
<span id="cb13-48"><a href="#cb13-48" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b06-normal-parameters" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b06-normal-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b06-continuous-normal_files/figure-html/fig-b06-normal-parameters-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b06-normal-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3: The two parameters of the normal model. Left: a larger mean (orange, μ = 3 in place of 0) shifts the curve to the right and leaves its shape unchanged. Right: a larger standard deviation (orange, σ = 2 in place of 1) makes the curve wider and lower.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-b06-normal-shape" class="quarto-xref">Figure&nbsp;<span>8.4</span></a> shows where the probability of a normal model lies.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>normal_curve <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">z =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">3.6</span>, <span class="fl">3.6</span>, <span class="at">length.out =</span> <span class="dv">800</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>normal_curve<span class="sc">$</span>density <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(normal_curve<span class="sc">$</span>z)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(normal_curve, <span class="fu">aes</span>(z, density)) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> <span class="fu">subset</span>(normal_curve, z <span class="sc">&gt;=</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">&amp;</span> z <span class="sc">&lt;=</span> <span class="dv">1</span>),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"#5B6976"</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"#C98B2E"</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="fl">0.16</span>, <span class="at">label =</span> <span class="st">"about 68%"</span>,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.15</span>, <span class="at">y =</span> <span class="fl">0.425</span>, <span class="at">label =</span> <span class="st">"mean~mu"</span>, <span class="at">parse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">expression</span>(mu <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> sigma, mu <span class="sc">-</span> sigma, mu,</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>                                         mu <span class="sc">+</span> sigma, mu <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> sigma)) <span class="sc">+</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.43</span>),</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.02</span>))) <span class="sc">+</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Value of X"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b06-normal-shape" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b06-normal-shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b06-continuous-normal_files/figure-html/fig-b06-normal-shape-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b06-normal-shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.4: The normal density. The shaded central area between the two grey dashed lines runs from one standard deviation below the mean to one above and contains about 68% of the distribution. The gold dashed line marks the mean μ.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The horizontal axis locates possible values relative to <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>. The vertical axis is density, and probability is again area. In the normal model, about 68% of the distribution lies within one standard deviation of the mean and about 95% within 1.96 standard deviations. The value 1.96 is explained later in this lecture. These are facts about the mathematical model. The caveat box below explains why they are not automatic facts about every dataset.</p>
<section id="the-opening-question-as-an-area" class="level4">
<h4 class="anchored" data-anchor-id="the-opening-question-as-an-area">The opening question as an area</h4>
<p>Return to the offer of 30%. Take the normal model that has the mean and the standard deviation of the equity offered in the Shark Tank file, <span class="math inline">\(X\sim N(13.2,\,8.4^2)\)</span>. In this model, the probability of an offer of 30% or more is the area under the curve to the right of 30. <a href="#fig-b06-equity-normal-area" class="quarto-xref">Figure&nbsp;<span>8.5</span></a> shows that this area is small.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>mean_equity <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>sd_equity <span class="ot">&lt;-</span> <span class="fu">sd</span>(sharks<span class="sc">$</span>equity_offered_pct)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>model_curve <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">15</span>, <span class="dv">45</span>, <span class="at">length.out =</span> <span class="dv">601</span>))</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>model_curve<span class="sc">$</span>density <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(model_curve<span class="sc">$</span>x, <span class="at">mean =</span> mean_equity,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>                             <span class="at">sd =</span> sd_equity)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(model_curve, <span class="fu">aes</span>(x, density)) <span class="sc">+</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> <span class="fu">subset</span>(model_curve, x <span class="sc">&gt;=</span> <span class="dv">30</span>),</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">fill =</span> <span class="st">"#D55E00"</span>, <span class="at">alpha =</span> <span class="fl">0.55</span>) <span class="sc">+</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_equity, <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"#C98B2E"</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> mean_equity <span class="sc">+</span> <span class="fl">0.8</span>, <span class="at">y =</span> <span class="fl">0.0495</span>, <span class="at">label =</span> <span class="st">"mean 13.2%"</span>,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> <span class="dv">35</span>, <span class="at">xend =</span> <span class="fl">32.2</span>, <span class="at">y =</span> <span class="fl">0.012</span>, <span class="at">yend =</span> <span class="fl">0.003</span>,</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>,</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>           <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.08</span>, <span class="st">"inches"</span>))) <span class="sc">+</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">30.5</span>, <span class="at">y =</span> <span class="fl">0.0168</span>, <span class="at">label =</span> <span class="st">"area == P(X &gt;= 30)"</span>,</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>           <span class="at">parse =</span> <span class="cn">TRUE</span>, <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">30.5</span>, <span class="at">y =</span> <span class="fl">0.0138</span>, <span class="at">label =</span> <span class="st">"about 2% in this model"</span>,</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">40</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.052</span>),</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.02</span>))) <span class="sc">+</span></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Equity offered (%)"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b06-equity-normal-area" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b06-equity-normal-area-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b06-continuous-normal_files/figure-html/fig-b06-equity-normal-area-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b06-equity-normal-area-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.5: The normal model with the mean and the standard deviation of the equity offered (<code>equity_offered_pct</code>) in the Shark Tank file. The gold dashed line marks the mean. The orange area to the right of 30% is the probability that this model gives to an offer of 30% or more, about 2%.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The figure shows the answer of the model, not the answer of the data. The curve also gives some area to values below 0%, which no offer can have. The check of the model later in this lecture returns to both points. To turn the orange area into a number, you need one more tool: standardising.</p>
</section>
<section id="standardising-every-normal-question-becomes-a-z-question" class="level4">
<h4 class="anchored" data-anchor-id="standardising-every-normal-question-becomes-a-z-question">Standardising: every normal question becomes a Z question</h4>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>z-score.</strong> The z-score of a value <span class="math inline">\(x\)</span> is <span class="math inline">\(z=\dfrac{x-\mu}{\sigma}\)</span>. It says how many standard deviations <span class="math inline">\(x\)</span> lies above the mean (positive <span class="math inline">\(z\)</span>) or below the mean (negative <span class="math inline">\(z\)</span>). Calculating a z-score is called <strong>standardising</strong>.</p>
</div>
<p>If <span class="math inline">\(X\sim N(\mu,\sigma^2)\)</span>, then the standardised variable is again normal, with mean 0 and standard deviation 1:</p>
<p><span class="math display">\[Z=\frac{X-\mu}{\sigma}\sim N(0,1).\]</span></p>
<p>The distribution <span class="math inline">\(N(0,1)\)</span> is called the <strong>standard normal distribution</strong>. The mean 0 and the standard deviation 1 follow from the rules for shifting and rescaling in <a href="../basic/b03-discrete-distributions.html#b03-shift-rescale">Lecture 3</a>.</p>
<p>Standardising helps because one set of standard-normal values then serves every normal model. Whatever <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> are, the question “what is <span class="math inline">\(P(X\le x)\)</span>?” becomes the question “what is <span class="math inline">\(P(Z\le z)\)</span>?”, with <span class="math inline">\(z=(x-\mu)/\sigma\)</span>.</p>
<p>Two general rules turn one value <span class="math inline">\(P(Z\le z)\)</span> into further probabilities. Both hold for every <span class="math inline">\(z\)</span>.</p>
<ul>
<li>Complement rule. The total area under the curve is 1, so <span class="math inline">\(P(Z&gt;z)=1-P(Z\le z)\)</span>.</li>
<li>Symmetry rule. The curve is symmetric around 0, so <span class="math inline">\(P(Z\le -z)=P(Z&gt;z)\)</span>.</li>
</ul>
<div id="exm-b06-supplied-z" class="theorem example">
<p><span class="theorem-title"><strong>Example 8.2 (Worked example: normal probabilities from supplied Z values)</strong></span> This is an invented example. Processing time <span class="math inline">\(Y\)</span> (in minutes) is modelled as <span class="math inline">\(Y\sim N(50,100)\)</span>. The variance is 100, so <span class="math inline">\(\sigma=\sqrt{100}=10\)</span>. In the exam, the standard-normal values that you need are printed in the question, as here:</p>
<pre><code>P(Z &lt;=  1.5) = 0.9332
P(Z &lt;=  1.0) = 0.8413
P(Z &lt;= -1.0) = 0.1587</code></pre>
<p><strong>(a) <span class="math inline">\(P(Y\le 65)\)</span>.</strong> Standardise the boundary:</p>
<p><span class="math display">\[z=\frac{65-50}{10}=1.5,\]</span></p>
<p>so</p>
<p><span class="math display">\[P(Y\le 65)=P(Z\le 1.5)=0.9332.\]</span></p>
<p><strong>(b) <span class="math inline">\(P(40&lt;Y&lt;60)\)</span>.</strong> Standardise both boundaries:</p>
<p><span class="math display">\[z_{\text{low}}=\frac{40-50}{10}=-1.0,\qquad
z_{\text{high}}=\frac{60-50}{10}=1.0,\]</span></p>
<p>then take the difference of the two cumulative probabilities, exactly as with any CDF:</p>
<p><span class="math display">\[P(40&lt;Y&lt;60)=P(Z\le 1.0)-P(Z\le -1.0)=0.8413-0.1587=0.6826.\]</span></p>
<p>That is the 68% rule seen in <a href="#fig-b06-normal-shape" class="quarto-xref">Figure&nbsp;<span>8.4</span></a>: the interval runs from one standard deviation below the mean to one above.</p>
<p><strong>(c) <span class="math inline">\(P(Y&gt;60)\)</span> and <span class="math inline">\(P(Y\le 35)\)</span>.</strong> These two need the rules. The z-score of 60 is 1.0, and the complement rule gives</p>
<p><span class="math display">\[P(Y&gt;60)=P(Z&gt;1.0)=1-P(Z\le 1.0)=1-0.8413=0.1587.\]</span></p>
<p>The z-score of 35 is <span class="math inline">\((35-50)/10=-1.5\)</span>. No value for <span class="math inline">\(-1.5\)</span> is supplied, so use the symmetry rule first and then the complement rule:</p>
<p><span class="math display">\[P(Y\le 35)=P(Z\le -1.5)=P(Z&gt;1.5)=1-0.9332=0.0668.\]</span></p>
<p>The supplied values also show the symmetry rule at work: <span class="math inline">\(P(Z\le -1.0)=0.1587\)</span> is the same number as <span class="math inline">\(P(Z&gt;1.0)\)</span>.</p>
</div>
<p><code>pnorm()</code> is the normal CDF in R. Give it the boundary, the mean, and the standard deviation (not the variance). The four lines below repeat the four results of the worked example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">65</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9331928</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">60</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">40</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6826895</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">60</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1586553</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">35</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0668072</code></pre>
</div>
</div>
<p>The hand calculation and <code>pnorm()</code> agree. Small differences in the fourth decimal come from the rounding of the supplied values.</p>
</section>
<section id="the-answer-of-the-model-to-the-opening-question" class="level4">
<h4 class="anchored" data-anchor-id="the-answer-of-the-model-to-the-opening-question">The answer of the model to the opening question</h4>
<p>Now the orange area in <a href="#fig-b06-equity-normal-area" class="quarto-xref">Figure&nbsp;<span>8.5</span></a> can be calculated. The model is <span class="math inline">\(X\sim N(13.2,\,8.4^2)\)</span> and the boundary is 30:</p>
<p><span class="math display">\[z=\frac{30-13.2}{8.4}=2.0.\]</span></p>
<p>An offer of 30% lies two standard deviations above the mean. The supplied value is <span class="math inline">\(P(Z\le 2.0)=0.9772\)</span>, and the complement rule gives</p>
<p><span class="math display">\[P(X\ge 30)=P(Z\ge 2.0)=1-P(Z\le 2.0)=1-0.9772=0.0228.\]</span></p>
<p>For a continuous variable, <span class="math inline">\(\ge\)</span> and <span class="math inline">\(&gt;\)</span> give the same probability. R confirms the result:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9772499</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02275013</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="fl">13.2</span>, <span class="at">sd =</span> <span class="fl">8.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02275013</code></pre>
</div>
</div>
<p>The normal model says that about 2% of pitches offer 30% or more. The count in the file gave about 5%. The section on checking the model explains the difference.</p>
</section>
<section id="the-reverse-direction-from-a-probability-to-a-value" class="level4">
<h4 class="anchored" data-anchor-id="the-reverse-direction-from-a-probability-to-a-value">The reverse direction: from a probability to a value</h4>
<p><code>pnorm()</code> starts from a value and returns the probability at or below it. The reverse question starts from the probability: which value has 90% of the probability at or below it? Such a value is called a quantile.</p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Quantile and percentile.</strong> The 0.90 quantile of a distribution is the value with 90% of the probability at or below it. It is also called the 90th percentile. In the same way, the 0.25 quantile is the 25th percentile. For the standard normal we write <span class="math inline">\(z_{0.90}\)</span>, and R gives it with <code>qnorm(0.90)</code>.</p>
</div>
<p>For the standard normal, <span class="math inline">\(z_{0.90}=1.2816\)</span>: 90% of the area lies at or below 1.2816. For any other normal model, solve <span class="math inline">\(z=(x-\mu)/\sigma\)</span> for <span class="math inline">\(x\)</span>:</p>
<p><span class="math display">\[x=\mu+z\sigma,\]</span></p>
<p>where <span class="math inline">\(z\)</span> is the standard-normal quantile for the chosen proportion.</p>
<div id="exm-b06-reverse" class="theorem example">
<p><span class="theorem-title"><strong>Example 8.3 (Worked example: the 90th percentile of processing time)</strong></span> Take the invented processing-time model <span class="math inline">\(Y\sim N(50,100)\)</span> again. Which processing time is exceeded by only 10% of cases? This is the 90th percentile of <span class="math inline">\(Y\)</span>. The supplied standard-normal quantile is <span class="math inline">\(z_{0.90}=1.2816\)</span>.</p>
<p><em>Step 1.</em> The 90th percentile of <span class="math inline">\(Z\)</span> is 1.2816. The value you look for therefore lies 1.2816 standard deviations above the mean.</p>
<p><em>Step 2.</em> Translate back to the scale of <span class="math inline">\(Y\)</span>:</p>
<p><span class="math display">\[x=\mu+z\sigma=50+1.2816\times 10=62.8 \text{ minutes.}\]</span></p>
<p><em>Step 3.</em> Verify with <code>qnorm()</code>, the reverse of <code>pnorm()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.90</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 62.81552</code></pre>
</div>
</div>
<p>About 62.8 minutes: 90% of processing times fall at or below it, 10% above.</p>
</div>
</section>
<section id="the-central-95-of-the-standard-normal" class="level4">
<h4 class="anchored" data-anchor-id="the-central-95-of-the-standard-normal">The central 95% of the standard normal</h4>
<p>One pair of quantiles is used again and again in later lectures. Which two values enclose the central 95% of the standard normal? If 95% of the probability lies in the middle, 5% is left for the two tails. By symmetry, each tail holds 2.5%. The upper boundary therefore has 97.5% of the probability at or below it. It is the 0.975 quantile. The lower boundary is the 0.025 quantile.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.959964  1.959964</code></pre>
</div>
</div>
<p>So <span class="math inline">\(z_{0.025}=-1.96\)</span> and <span class="math inline">\(z_{0.975}=1.96\)</span>. In the standard normal, 95% of the probability lies between <span class="math inline">\(-1.96\)</span> and <span class="math inline">\(1.96\)</span>, with 2.5% in each tail, as <a href="#fig-b06-central-95" class="quarto-xref">Figure&nbsp;<span>8.6</span></a> shows.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>z_cut <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>z_curve <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">z =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">3.6</span>, <span class="fl">3.6</span>, <span class="at">length.out =</span> <span class="dv">800</span>))</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>z_curve<span class="sc">$</span>density <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(z_curve<span class="sc">$</span>z)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>centre <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">z =</span> <span class="fu">seq</span>(<span class="sc">-</span>z_cut, z_cut, <span class="at">length.out =</span> <span class="dv">400</span>))</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>centre<span class="sc">$</span>density <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(centre<span class="sc">$</span>z)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>left_tail <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">z =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">3.6</span>, <span class="sc">-</span>z_cut, <span class="at">length.out =</span> <span class="dv">200</span>))</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>left_tail<span class="sc">$</span>density <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(left_tail<span class="sc">$</span>z)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>right_tail <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">z =</span> <span class="fu">seq</span>(z_cut, <span class="fl">3.6</span>, <span class="at">length.out =</span> <span class="dv">200</span>))</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>right_tail<span class="sc">$</span>density <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(right_tail<span class="sc">$</span>z)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(z_curve, <span class="fu">aes</span>(z, density)) <span class="sc">+</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> centre, <span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> left_tail, <span class="at">fill =</span> <span class="st">"#D55E00"</span>, <span class="at">alpha =</span> <span class="fl">0.55</span>) <span class="sc">+</span></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> right_tail, <span class="at">fill =</span> <span class="st">"#D55E00"</span>, <span class="at">alpha =</span> <span class="fl">0.55</span>) <span class="sc">+</span></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="fl">0.16</span>, <span class="at">label =</span> <span class="st">"95% of the area"</span>,</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.9</span>, <span class="fl">2.9</span>), <span class="at">xend =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.3</span>, <span class="fl">2.3</span>),</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> <span class="fl">0.075</span>, <span class="at">yend =</span> <span class="fl">0.02</span>, <span class="at">colour =</span> <span class="st">"#17324D"</span>,</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>           <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.08</span>, <span class="st">"inches"</span>))) <span class="sc">+</span></span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.9</span>, <span class="fl">2.9</span>), <span class="at">y =</span> <span class="fl">0.09</span>, <span class="at">label =</span> <span class="st">"2.5%"</span>,</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span>z_cut, <span class="dv">0</span>, z_cut),</span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"-1.96"</span>, <span class="st">"0"</span>, <span class="st">"1.96"</span>)) <span class="sc">+</span></span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.43</span>),</span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.02</span>))) <span class="sc">+</span></span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Value of Z"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb35-34"><a href="#cb35-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb35-35"><a href="#cb35-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb35-36"><a href="#cb35-36" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b06-central-95" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b06-central-95-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b06-continuous-normal_files/figure-html/fig-b06-central-95-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b06-central-95-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.6: The standard normal density. The green area between -1.96 and 1.96 holds 95% of the probability. Each orange tail holds 2.5%.
</figcaption>
</figure>
</div>
</div>
</div>
<p>With <span class="math inline">\(x=\mu+z\sigma\)</span> the same holds for every normal model: 95% of the probability lies between <span class="math inline">\(\mu-1.96\sigma\)</span> and <span class="math inline">\(\mu+1.96\sigma\)</span>. Lectures 9 and 10 build on this. Lecture 10 uses the value 1.96 in confidence intervals for proportions. Lecture 9 uses slightly larger values from the t distribution in its place.</p>
</section>
<section id="b06-normal-sums" class="level4">
<h4 class="anchored" data-anchor-id="b06-normal-sums">Sums of normal variables</h4>
<p>A sum of independent normal variables is again normal. Its mean and its variance follow from the sum rules of <a href="../basic/b05-joint-covariance-correlation.html#b05-sums">Lecture 5</a>. Lecture 8 uses this fact for the sample mean.</p>
</section>
</section>
<section id="checking-the-normal-model-against-data" class="level3">
<h3 class="anchored" data-anchor-id="checking-the-normal-model-against-data">Checking the normal model against data</h3>
<p>The normal distribution is a model, not a label that every quantitative variable automatically deserves. Skewness, bounds, extreme outliers, or a few heavily repeated values can make it a poor description. The check is visual: draw the histogram of the data, overlay the normal curve with the same mean and standard deviation, and see whether the curve reproduces the bars. <a href="#fig-b06-equity-normal-check" class="quarto-xref">Figure&nbsp;<span>8.7</span></a> does this for the equity offered (<code>equity_offered_pct</code>) in the Shark Tank file, with the mean of 13.2% and the standard deviation of 8.4 percentage points from the start of this lecture.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>mean_equity <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>sd_equity <span class="ot">&lt;-</span> <span class="fu">sd</span>(sharks<span class="sc">$</span>equity_offered_pct)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sharks, <span class="fu">aes</span>(equity_offered_pct)) <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="at">by =</span> <span class="dv">5</span>),</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm,</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> mean_equity, <span class="at">sd =</span> sd_equity),</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">42</span>, <span class="at">y =</span> <span class="fl">0.062</span>, <span class="at">label =</span> <span class="st">"observed pitches"</span>,</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">42</span>, <span class="at">y =</span> <span class="fl">0.054</span>,</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"normal curve with the same mean and SD"</span>,</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Equity initially offered (%)"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b06-equity-normal-check" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b06-equity-normal-check-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b06-continuous-normal_files/figure-html/fig-b06-equity-normal-check-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b06-equity-normal-check-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.7: Initial equity offered across all 1,441 recorded pitches (green bars), with the normal density that has the same mean and standard deviation (orange curve). The curve misses the skew, the bounds, and the spikes at round percentages.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Read <a href="#fig-b06-equity-normal-check" class="quarto-xref">Figure&nbsp;<span>8.7</span></a> with the five-step sequence from Lecture 1. <em>Unit and variables:</em> one observation is one pitch. The horizontal axis is the equity offered, in percentage points. <em>Scales:</em> the vertical axis is density, so the areas of the bars, not their heights alone, represent proportions of pitches. <em>One element:</em> the green bars are the 1,441 observed offers. The orange curve is <span class="math inline">\(N(13.2,\,8.4^2)\)</span>, the normal model with the same mean and SD. <em>Pattern:</em> the bars pile up between 5% and 20% and stretch out a long right tail. The data are bounded between 0% and 100%, strongly right-skewed, and spiked at round values such as 10% and 20%. The symmetric curve misses all three features. <em>Limits:</em> the figure rejects the normal model for single equity offers. It says nothing yet about averages of offers. A model is a choice, and this check rejects the choice.</p>
<p>The opening question shows what happens without the check. The normal model gave <span class="math inline">\(P(X\ge 30)=0.0228\)</span>, about 2%. The data give 76 of 1,441, about 5%. The model misses the long right tail, and the offers of 30% or more lie in that tail.</p>
<p>The normal model stays useful all the same. From Lecture 8 onwards it describes the sampling distribution of an average, that is, how an average varies from sample to sample. Lectures 7 and 8 explain this idea. The normal model fits those distributions well, even when the underlying variable is as skewed as this one. That result is the central limit theorem. It is the main reason why the normal model is used so much in statistics.</p>
</section>
<section id="quantiles-of-a-model-distribution" class="level3">
<h3 class="anchored" data-anchor-id="quantiles-of-a-model-distribution">Quantiles of a model distribution</h3>
<p>Lecture 1 located quantiles of data: the median, the quartiles <span class="math inline">\(Q_1\)</span> and <span class="math inline">\(Q_3\)</span>, and the interquartile range of the equity offered (see <a href="../basic/b01-introduction-data-analysis.html#b01-quartiles">Lecture 1</a>). A model distribution has the same quantiles. The median is the 0.50 quantile, and the quartiles are the 0.25 and the 0.75 quantiles.</p>
<ul>
<li><strong>Uniform:</strong> by symmetry, the median of <span class="math inline">\(U(a,b)\)</span> is the midpoint <span class="math inline">\((a+b)/2\)</span>. For the session model <span class="math inline">\(U(0,90)\)</span>, the median start time is 45 minutes: half of the probability lies on each side.</li>
<li><strong>Normal:</strong> by symmetry, the median equals the mean <span class="math inline">\(\mu\)</span>. The quartiles lie <span class="math inline">\(0.6745\)</span> standard deviations on either side of the mean, <span class="math inline">\(\mu\pm 0.6745\sigma\)</span>. For the processing-time model <span class="math inline">\(Y\sim N(50,100)\)</span>:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.75</span>), <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 43.2551 56.7449</code></pre>
</div>
</div>
<p>The middle half of this model distribution runs from about 43.3 to 56.7 minutes. The width of this range is the interquartile range of the model.</p>
<div class="caveat-box">
<p><span class="label">What a normal label can and cannot say</span></p>
<ul>
<li>“Normally distributed” is a model, not a fact. It has to be checked against a histogram.</li>
<li>The 68% and 95% rules hold for the model. For skewed or bounded data they give wrong numbers, as with the 30% offers.</li>
<li>A curve with the right mean and standard deviation can still have the wrong shape.</li>
</ul>
<p><strong>What you can do with it:</strong> use the normal model for quick answers when the histogram looks roughly bell-shaped, and count in the data when it does not. From Lecture 8 on, the normal model describes averages, where it works well.</p>
</div>
</section>
<section id="answering-the-driving-question" class="level3">
<h3 class="anchored" data-anchor-id="answering-the-driving-question">Answering the driving question</h3>
<p>An offer of 30% or more is unusual: about 1 pitch in 20 makes one. In the Shark Tank file, 76 of the 1,441 pitches did, about 5%. The normal model with the same mean and standard deviation says about 2%, because it ignores the long right tail of the offers. So a model with two numbers can answer such a question without counting every pitch, but only when the model fits. The histogram check tells you whether it does.</p>
<p>The tools behind this answer are general. For a continuous variable, no single value has positive probability, <span class="math inline">\(P(X=x)=0\)</span>. Probabilities belong to intervals, and they are areas under a density. For a uniform model, only the length of the interval matters: the 18-minute window in the session model has probability <span class="math inline">\(18/90=0.20\)</span>. For a normal model, you standardise and use the supplied <span class="math inline">\(Z\)</span> values. In the processing-time model <span class="math inline">\(N(50,100)\)</span> this gave <span class="math inline">\(P(Y\le 65)=0.9332\)</span> and <span class="math inline">\(P(40&lt;Y&lt;60)=0.6826\)</span>, and <code>pnorm()</code> confirmed both. A density is a modelling choice, so check the model before you trust its areas.</p>
<div class="founder-box">
<p><span class="label">A founder’s decision (invented example)</span></p>
<p>Your delivery times look roughly normal, with a mean of 28 minutes and a standard deviation of 6 minutes. You want to promise a delivery time that 90% of orders meet. The 90th percentile is 28 + 1.2816 × 6 = 35.7 minutes. The decision: promise 36 minutes on the website. First check the histogram of your delivery times. If a few deliveries go very wrong, the normal model is too optimistic, and you promise the 90th percentile of the actual times instead.</p>
</div>
<p><strong>Next:</strong> So far the 1,441 pitches were treated as the whole world. In practice a firm rarely sees the whole world. It sees a sample: 100 audited transactions, 500 surveyed customers. Lecture 7 moves from one pitch to a sample of pitches. It covers populations, random sampling, and the difference between a parameter, an estimator, and an estimate.</p>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p><span class="time-budget">Total practice time: about 75 minutes.</span></p>
<p><strong>Minimum path (about 35 minutes):</strong> read the lecture material, answer the recall questions, then work for 10 minutes on the tasks that follow. <strong>Full path:</strong> all tasks below.</p>
<section id="read-the-lecture-material-15-minutes" class="level3">
<h3 class="anchored" data-anchor-id="read-the-lecture-material-15-minutes">Read the lecture material (15 minutes)</h3>
<p>Read the Lecture material section above from start to end. The lecture covered the core of it. The text has every step, every example, and all the code, including parts that were not shown in class. Note what is still unclear and bring it to the next tutorial, or ask Tilly.</p>
</section>
<section id="recall-questions-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="recall-questions-10-minutes">Recall questions (10 minutes)</h3>
<ol type="1">
<li>Why is <span class="math inline">\(P(X=x)=0\)</span> for a continuous random variable?</li>
<li>What quantity under a PDF represents probability?</li>
<li>How do you obtain <span class="math inline">\(P(a&lt;X\le b)\)</span> from a CDF?</li>
<li>What do <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> control in a normal model?</li>
<li>A density curve reaches a height of 2. Why is that not a contradiction?</li>
<li>What does a z-score of <span class="math inline">\(-1.5\)</span> mean?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Probability belongs to intervals. An individual point has zero width and therefore zero area.</li>
<li>Area under the density curve between the interval boundaries.</li>
<li><span class="math inline">\(F_X(b)-F_X(a)\)</span>.</li>
<li><span class="math inline">\(\mu\)</span> controls the centre and <span class="math inline">\(\sigma\)</span> the spread.</li>
<li>Density is probability per unit, not probability. A height above 1 is fine as long as the total area under the curve is 1.</li>
<li>The value lies 1.5 standard deviations below the mean.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="finish-a-half-worked-example-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="finish-a-half-worked-example-5-minutes">Finish a half-worked example (5 minutes)</h3>
<p>Re-read the session-timing calculation (<a href="#exm-b06-uniform-session" class="quarto-xref">Example&nbsp;<span>8.1</span></a>). Then complete the same calculation for a new model: a waiting time <span class="math inline">\(X\sim U(10,30)\)</span> minutes.</p>
<p><em>Step 1 (given).</em> The density height is <span class="math inline">\(1/(30-10)=0.05\)</span> on the support <span class="math inline">\([10,30]\)</span> and zero outside it.</p>
<p><em>Step 2 (you).</em> Find <span class="math inline">\(P(14&lt;X&lt;20)\)</span>.</p>
<p><em>Step 3 (you).</em> State <span class="math inline">\(E[X]\)</span> and interpret both numbers in one sentence.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(P(14&lt;X&lt;20)=(20-14)/(30-10)=6/20=0.30\)</span> and <span class="math inline">\(E[X]=(10+30)/2=20\)</span>: the wait averages 20 minutes, and under the uniform model there is a 30% chance it lands between 14 and 20 minutes.</p>
</div>
</div>
</div>
</section>
<section id="practice-15-minutes" class="level3">
<h3 class="anchored" data-anchor-id="practice-15-minutes">Practice (15 minutes)</h3>
<p>For items 3 and 4, use only these supplied values, then verify in R:</p>
<pre><code>P(Z &lt;=  1.5) = 0.9332
P(Z &lt;=  1.0) = 0.8413
P(Z &lt;= -1.0) = 0.1587
z(0.90)      = 1.2816</code></pre>
<ol type="1">
<li>For <span class="math inline">\(X\sim U(10,30)\)</span>: find <span class="math inline">\(\operatorname{SD}(X)\)</span> and <span class="math inline">\(P(X&gt;25)\)</span>.</li>
<li>A supplier delivers at a moment uniformly distributed between 09:00 and 13:00. Your goods lift is reserved for other tenants except during 12:00–13:00. What is the probability the delivery arrives while the lift is available, and what is the density height per minute?</li>
<li>Monthly demand for a product is modelled as <span class="math inline">\(Y\sim N(200,400)\)</span>. Calculate <span class="math inline">\(P(Y\le 230)\)</span>, <span class="math inline">\(P(180&lt;Y&lt;220)\)</span>, <span class="math inline">\(P(Y&gt;230)\)</span>, and <span class="math inline">\(P(Y\le 170)\)</span> by hand.</li>
<li>Weekly revenue is modelled as <span class="math inline">\(N(100,15^2)\)</span> (in hundreds of euros). Which revenue level is exceeded in only 10% of weeks? Compute by hand with <span class="math inline">\(x=\mu+z\sigma\)</span>, then verify with <code>qnorm()</code>.</li>
<li>Explain in two sentences why the normal curve in <a href="#fig-b06-equity-normal-check" class="quarto-xref">Figure&nbsp;<span>8.7</span></a> is not a convincing model for offered equity.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(\operatorname{SD}(X)=\sqrt{(30-10)^2/12}=20/\sqrt{12}\approx 5.77\)</span> minutes, and <span class="math inline">\(P(X&gt;25)=(30-25)/20=0.25\)</span>.</li>
<li>The window is 60 of the 240 possible minutes, so <span class="math inline">\(60/240=0.25\)</span>. The density height is <span class="math inline">\(1/240\approx 0.0042\)</span> per minute, and the probability is the area <span class="math inline">\(60\times(1/240)=0.25\)</span>, not the height.</li>
<li><span class="math inline">\(\sigma=\sqrt{400}=20\)</span>. For 230: <span class="math inline">\(z=(230-200)/20=1.5\)</span>, so <span class="math inline">\(P(Y\le 230)=0.9332\)</span>. For the interval: <span class="math inline">\(z_{\text{low}}=(180-200)/20=-1.0\)</span> and <span class="math inline">\(z_{\text{high}}=(220-200)/20=1.0\)</span>, so <span class="math inline">\(P(180&lt;Y&lt;220)=0.8413-0.1587=0.6826\)</span>. The complement rule gives <span class="math inline">\(P(Y&gt;230)=1-0.9332=0.0668\)</span>. For 170: <span class="math inline">\(z=(170-200)/20=-1.5\)</span>, and the symmetry rule gives <span class="math inline">\(P(Y\le 170)=P(Z\le -1.5)=P(Z&gt;1.5)=0.0668\)</span>.</li>
<li><span class="math inline">\(x=100+1.2816\times 15=119.2\)</span>, so about 119 hundred euros, that is about 11,900 euros. Only 10% of weeks exceed it.</li>
<li>The observed distribution is bounded between 0% and 100%, strongly right-skewed, and concentrated at a few round percentages. The symmetric normal curve reproduces none of those features.</li>
</ol>
<p>Verification in R for items 3 and 4:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">230</span>, <span class="at">mean =</span> <span class="dv">200</span>, <span class="at">sd =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9331928</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">220</span>, <span class="at">mean =</span> <span class="dv">200</span>, <span class="at">sd =</span> <span class="dv">20</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">180</span>, <span class="at">mean =</span> <span class="dv">200</span>, <span class="at">sd =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6826895</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">230</span>, <span class="at">mean =</span> <span class="dv">200</span>, <span class="at">sd =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0668072</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">170</span>, <span class="at">mean =</span> <span class="dv">200</span>, <span class="at">sd =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0668072</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.90</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 119.2233</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="review-one-question-from-lecture-3-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="review-one-question-from-lecture-3-5-minutes">Review: one question from Lecture 3 (5 minutes)</h3>
<p>The number of sharks who join an on-air deal, <span class="math inline">\(X\)</span>, has PMF <span class="math inline">\(p(1)=0.6\)</span>, <span class="math inline">\(p(2)=0.3\)</span>, <span class="math inline">\(p(3)=0.1\)</span>. Find <span class="math inline">\(F(2)=P(X\le 2)\)</span> and <span class="math inline">\(P(X&lt;2)\)</span>. Why do the two answers differ here, when for a continuous variable they would not?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(F(2)=0.6+0.3=0.9\)</span>, while <span class="math inline">\(P(X&lt;2)=P(X=1)=0.6\)</span>. They differ because the single point <span class="math inline">\(X=2\)</span> carries positive probability, <span class="math inline">\(p(2)=0.3\)</span>. For a continuous variable every single point has probability zero, so <span class="math inline">\(&lt;\)</span> and <span class="math inline">\(\le\)</span> give the same answer.</p>
</div>
</div>
</div>
</section>
<section id="changing-units-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="changing-units-5-minutes">Changing units (5 minutes)</h3>
<p>The session-timing variable <span class="math inline">\(X\sim U(0,90)\)</span> is recorded in minutes and then converted to seconds. Explain what changes about the PDF and what remains unchanged.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The support stretches from <span class="math inline">\([0,90]\)</span> minutes to <span class="math inline">\([0,5400]\)</span> seconds, and the density height drops from <span class="math inline">\(1/90\)</span> per minute to <span class="math inline">\(1/5400\)</span> per second: the numerical size of a density depends on the units. Probabilities of corresponding time intervals are unchanged, because they are areas: the 18-minute window becomes a 1,080-second window, and <span class="math inline">\(1080/5400=18/90=0.20\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="exam-style-item-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="exam-style-item-10-minutes">Exam-style item (10 minutes)</h3>
<p>This item follows the pattern of Mock Exam Question 3. Let <span class="math inline">\(X\sim U(20,60)\)</span> be a waiting time in minutes and, separately, <span class="math inline">\(Y\sim N(80,25)\)</span> a processing time in minutes. Supplied:</p>
<pre><code>P(Z &lt;=  1.5) = 0.9332
P(Z &lt;=  1.0) = 0.8413
P(Z &lt;= -1.0) = 0.1587</code></pre>
<ol type="1">
<li>State the PDF height of <span class="math inline">\(X\)</span>, including its value outside the support.</li>
<li>Calculate <span class="math inline">\(P(30&lt;X&lt;40)\)</span>, <span class="math inline">\(E[X]\)</span>, and <span class="math inline">\(\operatorname{Var}(X)\)</span>.</li>
<li>Standardise 87.5 minutes under the model for <span class="math inline">\(Y\)</span>, then calculate <span class="math inline">\(P(Y\le 87.5)\)</span>.</li>
<li>Calculate <span class="math inline">\(P(75&lt;Y&lt;85)\)</span>.</li>
<li>Explain why a PDF height is not itself a probability.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(f_X(x)=1/(60-20)=0.025\)</span> for <span class="math inline">\(20\le x\le 60\)</span>, and <span class="math inline">\(f_X(x)=0\)</span> outside that interval.</li>
<li><span class="math inline">\(P(30&lt;X&lt;40)=(40-30)/40=0.25\)</span>, <span class="math inline">\(E[X]=(20+60)/2=40\)</span>, and <span class="math inline">\(\operatorname{Var}(X)=(60-20)^2/12\approx 133.33\)</span> square minutes.</li>
<li>The variance is 25, so <span class="math inline">\(\sigma=5\)</span> and <span class="math inline">\(z=(87.5-80)/5=1.5\)</span>. Hence <span class="math inline">\(P(Y\le 87.5)=0.9332\)</span>.</li>
<li><span class="math inline">\(P(75&lt;Y&lt;85)=P(-1&lt;Z&lt;1)=0.8413-0.1587=0.6826\)</span>.</li>
<li>Probability is area over an interval: approximately density times a small interval width. A single point has zero width and hence zero probability. A density value only becomes a probability once multiplied by a width.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="check-the-ai-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="check-the-ai-5-minutes">Check the AI (5 minutes)</h3>
<p>You asked an AI assistant: “Equity offers have a mean of 13.2% and a standard deviation of 8.4%. How many pitches offer 30% or more?” It answered:</p>
<blockquote class="blockquote">
<p>“With the normal distribution, 30% is 2.0 standard deviations above the mean, so about 2.3% of pitches offer 30% or more.”</p>
</blockquote>
<p>Find what is wrong and write the corrected answer. This is the <strong>Verify</strong> step of Attempt → Ask → Verify → Explain, and the exam asks for it.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The calculation is correct for a normal model, but the model does not fit. Equity offers are strongly right-skewed and pile up at round numbers. In the data, 76 of 1,441 pitches offer 30% or more, about 5.3%, more than twice the answer of the AI. Check the histogram before you accept an answer that rests on a normal model.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Utility: two sentences</span></p>
<p>Think of your EiA venture, or any business you know well. Pick one continuous quantity that matters for it (a delivery time, weekly revenue, time on site) and write two sentences: first name the interval of values that would trigger a real decision, then say whether a uniform or a normal model seems defensible for that quantity, and which feature of its histogram you would check first. There is no wrong answer.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run campus meal-prep box venture. “Delivery time is my quantity: anything over 40 minutes triggers a refund, so <span class="math inline">\(P(T &gt; 40)\)</span> is the number that matters. A normal model is doubtful because times cannot be negative and a few deliveries go very wrong: right skew is the first thing I would check on the histogram.”</p>
</div>
</div>
</div>
<p>You can discuss this task, and any other task in this chapter, with <strong>Tilly</strong>, the course AI assistant: ask it to propose a distribution for your quantity and then challenge whether the normal model’s assumptions actually hold for it.</p>
</div>
<p><a href="../basic/b07-samples-estimators.html">Continue to Lecture 7: Samples, parameters, and estimators</a>.</p>
<p><a href="../basic/formula-sheet.html#formula-l6">Formula sheet: Lecture 6 formulas</a>.</p>
<p>For a more formal explanation, consult <a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>, Chapter 10.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/t02-exam-prep.html" class="pagination-link" aria-label="Tutorial 2: Conditioning and relationships">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/b07-samples-estimators.html" class="pagination-link" aria-label="Lecture 7: Samples, parameters, and estimators">
        <span class="nav-page-text"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>