<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 7: Samples, parameters, and estimators – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/b08-sampling-distributions.html" rel="next">
<link href="../basic/b06-continuous-normal.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ecf4e518a83458a2bb67b2a9bf74271b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b07-samples-estimators.html"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution, confidence intervals, and the two-sided test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Inference and tests against zero</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals betray it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/reading-ladder.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reading research papers</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-class" id="toc-in-class" class="nav-link" data-scroll-target="#in-class">In class</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b07-samples-estimators.html"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b07" class="quarto-section-identifier"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Lecture 7, you can</span></p>
<ul>
<li>distinguish a population, sampling frame, sample, and target population;</li>
<li>explain simple random sampling with and without replacement, and apply the 10% working rule;</li>
<li>distinguish parameters, estimators, and estimates, with the capital and lower-case notation discipline;</li>
<li>explain why a sample proportion is a sample mean;</li>
<li>explain the <span class="math inline">\(n-1\)</span> degrees of freedom in a sample variance;</li>
<li>describe how an estimate varies from sample to sample while the parameter sits still;</li>
<li>classify sampling methods and name the main threat of each.</li>
</ul>
</div>
<div class="driving-question">
<p><span class="label">Driving question</span></p>
<p class="dq-context">
Checking every record, customer, or transaction is usually too expensive, so firms audit a sample and act on what it shows. That only works if a small sample can be trusted to speak for the whole.
</p>
<p>We can only afford to inspect 100 of the 1,441 pitches. What can 100 randomly chosen records tell us about all of them — and what can they never tell us about entrepreneurs in general?</p>
</div>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p><span class="time-budget">Total preparation time: about 25 minutes.</span></p>
<div class="video-prep">
<p><span class="label">Video preparation (10 minutes)</span><br> Watch <a href="https://www.youtube.com/watch?v=nuXDb9B3y0M">The Sample Mean and Some Terminology</a>. Be ready to distinguish a population quantity from a statistic calculated after a sample is observed. The link is also listed in the <a href="../resources/video-guide.html">External Video Guide</a>.</p>
</div>
<p><strong>Reactivate (10 minutes).</strong> Suppose we want the mean initial equity offered across the 1,441 recorded pitches in completed Seasons 1–16, but can inspect only 100 randomly selected records. Identify:</p>
<ol type="1">
<li>the finite population;</li>
<li>the population variable;</li>
<li>the sample;</li>
<li>the parameter of interest;</li>
<li>a statistic that could estimate it.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The finite population is the 1,441 recorded pitches; the variable is initial equity offered; the sample is the 100 selected records; the parameter is the population mean equity offer; and the sample mean is a suitable estimator.</p>
</div>
</div>
</div>
<p><strong>Predict (5 minutes).</strong> Answer the one-click Mentimeter question posted on Canvas before you come to class: two students each draw their own random sample of 100 pitches from the file and each compute the mean equity offered. Will their two sample means be <strong>equal</strong>? Commit to an answer; the lecture resolves it.</p>
<p>If subscripts or summation notation are not secure, review <a href="../resources/math-refresher.html">Mathematics Refresher: indices and sums</a>.</p>
</section>
<section id="in-class" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-class">In class</h2>
<p>The session opens with the usual four-minute entry quiz on the prep videos, then turns to the driving question. Your prep prediction — do two random samples give equal means? — stays on screen, unresolved, until the sampling activity below settles it with evidence.</p>
<section id="define-the-population-before-calculating" class="level3">
<h3 class="anchored" data-anchor-id="define-the-population-before-calculating">Define the population before calculating</h3>
<p>A <strong>population</strong> is the complete set of units about which a question is asked. A <strong>sample</strong> is the subset observed for analysis. A <strong>sampling frame</strong> is the list or mechanism from which the sample is selected. The <strong>target population</strong> is the broader group to which we hope to generalise.</p>
<p>These sets need not coincide. The teaching file is a near-census of recorded US <em>Shark Tank</em> pitches from completed Seasons 1–16, but it is not a random sample of all entrepreneurs, all funding pitches, or even all applicants to the show. Randomly sampling rows from this file supports inference to the 1,441-record population. It does not remove the show’s selection process.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: classify two scenarios
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Scenario A.</strong> A food-delivery startup wants to know how satisfied “its customers” are. It emails a survey to the app users who opted in to marketing emails; 800 reply. Identify the target population, the frame, and the sample.</p>
<p><strong>Scenario B.</strong> A consultant uses our 100 sampled pitches to advise “US entrepreneurs seeking investors.” What is the frame, and what is the target population being claimed?</p>
<p><strong>Answers.</strong> In A, the target population is all customers; the frame is the opted-in email list (which already excludes many customers); the sample is the 800 who chose to reply — a voluntary-response subset of an incomplete frame. In B, the frame is the 1,441 recorded <em>Shark Tank</em> pitches; the claimed target population is all US entrepreneurs seeking investors. Random row sampling licenses conclusions about the frame, not about that far larger target group.</p>
</div>
</div>
</div>
</section>
<section id="simple-random-sampling" class="level3">
<h3 class="anchored" data-anchor-id="simple-random-sampling">Simple random sampling</h3>
<p>In a simple random sample of size <span class="math inline">\(n\)</span>, every set of <span class="math inline">\(n\)</span> population units has the same chance of selection.</p>
<ul>
<li><strong>With replacement:</strong> a selected unit is returned before the next draw. Draws are independent and each draw has the same distribution.</li>
<li><strong>Without replacement:</strong> a unit cannot be selected twice. Draws are dependent, although every draw has the same marginal distribution.</li>
</ul>
<p>When a without-replacement sample is a small fraction of a large population, the dependence is weak. This course uses the 10% condition as a practical working rule: if <span class="math inline">\(n\le 0.10N\)</span>, the usual independent-sample standard-error formulas are a good approximation.</p>
<p>The running sample for this lecture and the next is drawn with a visible seed, so every reader gets the same 100 rows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>sample_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>pitch_sample <span class="ot">&lt;-</span> sharks[sample_rows, ]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(pitch_sample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100</code></pre>
</div>
</div>
<p>Here <span class="math inline">\(100/1441\approx 0.069&lt;0.10\)</span>, so the working rule is satisfied.</p>
<p>How does this one realised sample compare to the population it came from?</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>sample_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>pitch_sample <span class="ot">&lt;-</span> sharks[sample_rows, ]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>breaks <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="at">by =</span> <span class="dv">5</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>pop_hist <span class="ot">&lt;-</span> <span class="fu">hist</span>(sharks<span class="sc">$</span>equity_offered_pct, <span class="at">breaks =</span> breaks, <span class="at">plot =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>samp_hist <span class="ot">&lt;-</span> <span class="fu">hist</span>(pitch_sample<span class="sc">$</span>equity_offered_pct, <span class="at">breaks =</span> breaks,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">plot =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>pop_density <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">mid =</span> pop_hist<span class="sc">$</span>mids, <span class="at">density =</span> pop_hist<span class="sc">$</span>density)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>samp_density <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">mid =</span> samp_hist<span class="sc">$</span>mids, <span class="at">density =</span> samp_hist<span class="sc">$</span>density)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">data =</span> pop_density, <span class="fu">aes</span>(mid, density), <span class="at">width =</span> <span class="dv">5</span>,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="st">"grey75"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> samp_density, <span class="fu">aes</span>(mid, density),</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">colour =</span> <span class="st">"#009E73"</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> samp_density, <span class="fu">aes</span>(mid, density),</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"#009E73"</span>, <span class="at">size =</span> <span class="fl">2.2</span>) <span class="sc">+</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">40</span>, <span class="at">y =</span> <span class="fl">0.070</span>, <span class="at">label =</span> <span class="st">"all 1,441 records"</span>,</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#5B6976"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">40</span>, <span class="at">y =</span> <span class="fl">0.062</span>, <span class="at">label =</span> <span class="st">"random sample of 100"</span>,</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#009E73"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Equity initially offered (%)"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b07-population-sample" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b07-population-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b07-samples-estimators_files/figure-html/fig-b07-population-sample-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b07-population-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Initial equity offered: all 1,441 records (grey bars) and the seed-123 random sample of 100 (green connected points). The sample resembles the population but does not reproduce it exactly.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The horizontal axis gives equity intervals in percentage points; the vertical axis is density, so the differently sized datasets can be compared by shape. The sample resembles the population but does not reproduce it exactly — and a <em>different</em> random sample would resemble it differently. That observation is worth turning into an experiment.</p>
</section>
<section id="the-live-sampling-activity-watching-an-estimator-vary" class="level3">
<h3 class="anchored" data-anchor-id="the-live-sampling-activity-watching-an-estimator-vary">The live sampling activity: watching an estimator vary</h3>
<p>In class this segment runs live. The whole class watches five different random samples being drawn, one after another, and tracks one number per sample: the mean equity offered. The target of the exercise is the population mean of the file,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mu_equity <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>mu_equity</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.20761</code></pre>
</div>
</div>
<p>about 13.21 percentage points — knowable here only because we happen to hold the full file. In a real study you would hold <em>only</em> the sample, which is exactly why the behaviour of the sample mean matters.</p>
<p>Five samples of 100, each from its own seed, each summarised by its mean. The code is fully reproducible — run it yourself and you will get the same five numbers:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>seeds <span class="ot">&lt;-</span> <span class="dv">101</span><span class="sc">:</span><span class="dv">105</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>sample_means <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(seeds))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(seeds)) {</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(seeds[i])</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  sample_means[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct[rows])</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(sample_means, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.03 12.77 13.75 12.07 13.58</code></pre>
</div>
</div>
<p>Five samples, five different means — from about 12.0 to about 13.8. <a href="#fig-b07-five-means" class="quarto-xref">Figure&nbsp;<span>9.2</span></a> puts them on one fixed axis, with the population mean drawn as a vertical line that never moves.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>mu_equity <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>seeds <span class="ot">&lt;-</span> <span class="dv">101</span><span class="sc">:</span><span class="dv">105</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>sample_means <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(seeds))</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(seeds)) {</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(seeds[i])</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  sample_means[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct[rows])</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>five_means <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">draw =</span> <span class="fu">seq_along</span>(seeds),</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>                         <span class="at">seed =</span> <span class="fu">paste</span>(<span class="st">"seed"</span>, seeds),</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>                         <span class="at">sample_mean =</span> sample_means)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(five_means, <span class="fu">aes</span>(sample_mean, draw)) <span class="sc">+</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu_equity, <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"#C98B2E"</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">"#009E73"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> mu_equity <span class="sc">+</span> <span class="fl">0.12</span>, <span class="at">y =</span> <span class="fu">length</span>(seeds) <span class="sc">+</span> <span class="fl">0.45</span>,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"mu == 13.21"</span>, <span class="at">parse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> five_means<span class="sc">$</span>draw, <span class="at">labels =</span> five_means<span class="sc">$</span>seed) <span class="sc">+</span></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">16</span>),</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fu">length</span>(seeds) <span class="sc">+</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sample mean equity offered (%)"</span>, <span class="at">y =</span> <span class="st">"Draw"</span>) <span class="sc">+</span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b07-five-means" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b07-five-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b07-samples-estimators_files/figure-html/fig-b07-five-means-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b07-five-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: Five random samples of 100, five sample means (green dots), one fixed population mean (gold dashed line at 13.21). The estimate varies from draw to draw; the parameter sits still.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Read the figure slowly, because Lecture 8 is built on it. Each green dot is one <em>estimate</em>: the realised mean of one realised sample. The gold dashed line is the <em>parameter</em>: one fixed, unmoving number. The dots scatter around the line — none hits it exactly, none is far from it, and no dot is “wrong.” The scatter is not a mistake in the procedure; it <em>is</em> the procedure. Random samples produce random estimates.</p>
<p>This resolves the prep prediction: two students drawing their own random samples will almost never get equal means. Any two of the five dots differ, and yours (in the after-class task below) will differ again.</p>
<p>In class the five-dot plot stays on screen through the break, with one question to chew on: if we drew a sixth sample, where would its mean land? You cannot say exactly — but by now you can say something about the <em>range</em> in which it would probably fall. Making that “something” precise is the entire subject of Lecture 8.</p>
</section>
<section id="parameters-estimators-and-estimates" class="level3">
<h3 class="anchored" data-anchor-id="parameters-estimators-and-estimates">Parameters, estimators, and estimates</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/the-sample-mean-and-some-terminology/">20.3 The Sample Mean and Some Terminology</a>.
</p>
<p>A <strong>parameter</strong> is a fixed numerical property of a population, usually unknown. An <strong>estimator</strong> is a rule based on random sample variables. Its value changes from sample to sample. An <strong>estimate</strong> is the number obtained from one realised sample.</p>
<p>For a random sample <span class="math inline">\(X_1,\ldots,X_n\)</span>:</p>
<p><span class="math display">\[\bar X=\frac{1}{n}\sum_{i=1}^{n}X_i\]</span></p>
<p>is an estimator of the population mean <span class="math inline">\(\mu\)</span>. After observing values <span class="math inline">\(x_1,\ldots,x_n\)</span>,</p>
<p><span class="math display">\[\bar x=\frac{1}{n}\sum_{i=1}^{n}x_i\]</span></p>
<p>is the realised estimate. Capital letters describe random quantities before sampling; lower-case letters describe observed values.</p>
<p>For a 0/1 variable, the sample proportion is a sample mean:</p>
<p><span class="math display">\[\widehat P=\frac{1}{n}\sum_{i=1}^{n}X_i.\]</span></p>
<p>Its realised value is written <span class="math inline">\(\hat p\)</span>.</p>
<p>The usual sample variance and standard deviation are</p>
<p><span class="math display">\[S^2=\frac{1}{n-1}\sum_{i=1}^{n}(X_i-\bar X)^2,
\qquad S=\sqrt{S^2}.\]</span></p>
<p>The denominator <span class="math inline">\(n-1\)</span> makes <span class="math inline">\(S^2\)</span> an unbiased estimator of population variance under independent random sampling.</p>
<p>The realised estimates for our seed-123 sample:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_mean_equity =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_sd_equity =</span> <span class="fu">sd</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_deal_proportion =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>deal_on_show)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    sample_mean_equity       sample_sd_equity sample_deal_proportion 
             12.760000               7.707887               0.640000 </code></pre>
</div>
</div>
<p>For this realised sample, <span class="math inline">\(\bar x=12.76\)</span> percentage points, <span class="math inline">\(s=7.71\)</span> percentage points, and <span class="math inline">\(\hat p=0.64\)</span>.</p>
<div id="exm-b07-three-objects" class="theorem example">
<p><span class="theorem-title"><strong>Example 9.1 (Worked example: three objects for the deal proportion)</strong></span> Identify the parameter, the estimator, and the estimate for the proportion of deals, using our realised sample.</p>
<ul>
<li><strong>Parameter:</strong> <span class="math inline">\(p\)</span>, the proportion of the 1,441 records with an on-air deal — one fixed number. Because the file is a near-census of its frame, we can even look it up: <span class="math inline">\(882/1441\approx 0.612\)</span>. In a real study it would be unknown.</li>
<li><strong>Estimator:</strong> <span class="math inline">\(\widehat P=\frac{1}{100}\sum_{i=1}^{100}X_i\)</span>, where <span class="math inline">\(X_i\)</span> is the deal indicator of the <span class="math inline">\(i\)</span>-th sampled record — a rule whose value is random because the sample is.</li>
<li><strong>Estimate:</strong> <span class="math inline">\(\hat p=0.64\)</span>, the number the rule produced for the seed-123 sample. A different seed would produce a different <span class="math inline">\(\hat p\)</span> while <span class="math inline">\(p\)</span> stayed exactly where it was.</li>
</ul>
</div>
</section>
<section id="why-the-sample-variance-has-n-1-degrees-of-freedom" class="level3">
<h3 class="anchored" data-anchor-id="why-the-sample-variance-has-n-1-degrees-of-freedom">Why the sample variance has <span class="math inline">\(n-1\)</span> degrees of freedom</h3>
<p>Once <span class="math inline">\(\bar X\)</span> has been calculated from the same sample, the deviations must satisfy</p>
<p><span class="math display">\[\sum_{i=1}^{n}(X_i-\bar X)=0.\]</span></p>
<p>If <span class="math inline">\(n-1\)</span> deviations are known, the final deviation is forced to make the sum zero. Only <span class="math inline">\(n-1\)</span> deviations can vary freely: the sample variance has <span class="math inline">\(n-1\)</span> <strong>degrees of freedom</strong>.</p>
<div id="exm-b07-df" class="theorem example">
<p><span class="theorem-title"><strong>Example 9.2 (Worked example: three deviations, two degrees of freedom)</strong></span> Suppose a sample has <span class="math inline">\(n=3\)</span> observations and the first two deviations from the sample mean are <span class="math inline">\(2\)</span> and <span class="math inline">\(-5\)</span>.</p>
<p><em>Step 1.</em> The deviations must sum to zero: <span class="math inline">\(2+(-5)+d_3=0\)</span>.</p>
<p><em>Step 2.</em> Solve: <span class="math inline">\(d_3=3\)</span>. The third deviation cannot be chosen freely — it is forced.</p>
<p><em>Step 3.</em> Count the freedom: three deviations, but only two carried any information once the sample mean was fixed. The sample variance for this sample has <span class="math inline">\(3-1=2\)</span> degrees of freedom.</p>
</div>
<p>Using the fitted sample mean makes squared deviations around <span class="math inline">\(\bar X\)</span> slightly too small on average as a measure of population spread. Dividing by <span class="math inline">\(n-1\)</span>, rather than <span class="math inline">\(n\)</span>, corrects that downward bias under the random-sample model. Degrees of freedom count remaining independent pieces of information; they are not a percentage or a probability.</p>
</section>
<section id="sampling-method-determines-the-evidence-boundary" class="level3">
<h3 class="anchored" data-anchor-id="sampling-method-determines-the-evidence-boundary">Sampling method determines the evidence boundary</h3>
<p>The number of rows does not identify the sampling design. Ask how units entered the data:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>How units enter</th>
<th>Main implication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simple random sample</td>
<td>selected by a known random mechanism</td>
<td>supports design-based generalisation to the frame</td>
</tr>
<tr class="even">
<td>Stratified random sample</td>
<td>randomly selected within defined groups</td>
<td>can guarantee representation of important groups</td>
</tr>
<tr class="odd">
<td>Convenience sample</td>
<td>selected because they are easy to reach</td>
<td>vulnerable to selection bias</td>
</tr>
<tr class="even">
<td>Voluntary-response sample</td>
<td>units choose whether to respond</td>
<td>people with stronger views may be over-represented</td>
</tr>
<tr class="odd">
<td>Census of a frame</td>
<td>every unit in the available frame is recorded</td>
<td>no sampling error for that frame, but coverage error can remain</td>
</tr>
</tbody>
</table>
<p>The Shark Tank teaching file is close to a census of its recorded-pitch frame. When we draw 100 rows for an inference exercise, the randomisation is created by our row-sampling procedure. It does not make the television programme’s selection of pitches random.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it: classify four recruitment stories
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In class this is the pair task. For each story, name the sampling method from the table and state its main threat.</p>
<p><em>Story 1 (given, as a model).</em> “A ministry lists all registered firms, groups them by province, and randomly selects firms within each province.” Method: stratified random sample. Main implication: representation of every province is guaranteed by design.</p>
<p><em>Story 2 (you).</em> “A startup posts a poll on its own Instagram account asking followers to rate a prototype; 412 followers respond.”</p>
<p><em>Story 3 (you).</em> “A student emails the survey to friends, family, and two student associations she belongs to.”</p>
<p><em>Story 4 (you).</em> “A researcher numbers all 8,214 firms in the Chamber of Commerce register and selects 300 using a random number generator.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Story 2: voluntary-response sample — followers already like the brand, and those with the strongest opinions are most likely to reply. Story 3: convenience sample — easy-to-reach contacts are systematically unlike the wider population, so selection bias is the main threat. Story 4: simple random sample from the register — it supports generalisation to the registered-firm frame, though firms missing from the register remain out of reach (coverage error).</p>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Random selection reduces systematic over-representation within the sampling frame. It does not guarantee that one realised sample is perfectly balanced: by chance, a sample can contain unusually many large equity offers or unusually many deals. Larger samples reduce this random instability — the five-dot plot would tighten if each dot summarised 1,000 draws instead of 100.</p>
<div class="caveat-box">
<p><span class="label">What random selection can and cannot repair</span></p>
<p>Random <strong>sampling</strong> supports generalisation from the sample to the frame it was drawn from: our 100 rows speak, with quantifiable uncertainty, for the 1,441 recorded pitches. Random <strong>assignment</strong> — allocating units to treatments by chance — supports causal comparison. They answer different design questions and neither substitutes for the other. And neither repairs the show’s selection: the frame itself was assembled by producers choosing telegenic pitches, so no amount of careful random row-sampling turns conclusions about this file into conclusions about entrepreneurs in general. Finally, “unbiased” is a promise about the procedure across many samples, not about your one realised estimate: <span class="math inline">\(\bar x = 12.76\)</span> is not <span class="math inline">\(\mu = 13.21\)</span>, and no single sample can tell you how far off it is.</p>
</div>
</section>
<section id="answering-the-driving-question" class="level3">
<h3 class="anchored" data-anchor-id="answering-the-driving-question">Answering the driving question</h3>
<p>One hundred randomly chosen records give estimates of the file’s parameters: the seed-123 sample estimates the mean equity offer at <span class="math inline">\(\bar x=12.76\)</span> against the true <span class="math inline">\(\mu=13.21\)</span>, and the deal proportion at <span class="math inline">\(\hat p=0.64\)</span> against <span class="math inline">\(p\approx 0.612\)</span>. Five repeated draws put the sample mean between about 12.0 and 13.8 while the parameter never moved — random samples inform us about the frame, with a random error whose size Lecture 8 will quantify. What they can never tell us: anything reliable about entrepreneurs in general, because the frame is a television programme’s curated selection, and our row-sampling randomness cannot undo that.</p>
<p><strong>Next:</strong> We now speak carefully about samples: the parameter sits still while the estimator varies from sample to sample — you watched five sample means land in five different places. Lecture 8 studies the pattern behind those dots: the sampling distribution of the mean, the standard error that measures its spread, and the central limit theorem, which explains why averages turn bell-shaped even when the underlying data are wildly skewed. That pattern is what will let us attach a margin of error to any estimate.</p>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p><span class="time-budget">Total practice time: about 50 minutes.</span></p>
<section id="retrieval-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="retrieval-10-minutes">Retrieval (10 minutes)</h3>
<ol type="1">
<li>What is the difference between a target population and a sampling frame?</li>
<li>Why are draws without replacement dependent?</li>
<li>What is the difference between an estimator and an estimate?</li>
<li>Why is a sample proportion a sample mean?</li>
<li>Why does the sample variance have <span class="math inline">\(n-1\)</span> degrees of freedom?</li>
<li>What does random sampling support that random assignment does not?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The target population is the group of substantive interest; the sampling frame is the set from which units can actually be selected.</li>
<li>Selecting one unit changes which units remain available.</li>
<li>An estimator is a random rule before data are observed; an estimate is its realised numerical value.</li>
<li>A 0/1 indicator sums to the number of successes, so its mean is the success proportion.</li>
<li>Estimating the sample mean imposes one constraint: all deviations from it must sum to zero. Only <span class="math inline">\(n-1\)</span> deviations can vary freely.</li>
<li>Random sampling supports generalisation to the sampling frame; random assignment supports causal comparison of treatments.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="practice-15-minutes" class="level3">
<h3 class="anchored" data-anchor-id="practice-15-minutes">Practice (15 minutes)</h3>
<ol type="1">
<li>For a population of <span class="math inline">\(N=20{,}000\)</span> customers and a simple random sample of <span class="math inline">\(n=500\)</span>, check the 10% condition.</li>
<li>Write the estimator and realised estimate for the population deal proportion.</li>
<li>Explain why <span class="math inline">\(\mu\)</span> is fixed while <span class="math inline">\(\bar X\)</span> is random.</li>
<li>Using <code>pitch_sample</code>, calculate the sample mean and sample SD of <code>description_words</code>.</li>
<li>Explain why this random sample cannot justify conclusions about all US entrepreneurs.</li>
<li>For a sample of five observations, state the degrees of freedom used to estimate variance and explain the number.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(500/20{,}000=0.025&lt;0.10\)</span>, so the condition is satisfied.</li>
<li>The estimator is <span class="math inline">\(\widehat P=n^{-1}\sum_iX_i\)</span>; the realised estimate is <span class="math inline">\(\hat p=n^{-1}\sum_ix_i\)</span> — here <span class="math inline">\(0.64\)</span>.</li>
<li>The population and its mean are treated as fixed; the selected observations, and therefore their mean, vary across possible samples.</li>
<li>Rebuild the sample and compute — about 4.82 words with an SD of about 1.76:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>sample_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>pitch_sample <span class="ot">&lt;-</span> sharks[sample_rows, ]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>description_words),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd   =</span> <span class="fu">sd</span>(pitch_sample<span class="sc">$</span>description_words))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   mean      sd 
4.82000 1.76028 </code></pre>
</div>
</div>
<ol start="5" type="1">
<li>The sample was selected from televised records, not from all US entrepreneurs; random row selection cannot repair that coverage gap.</li>
<li>The degrees of freedom are <span class="math inline">\(5-1=4\)</span>. Once the sample mean is estimated, four deviations may vary freely and the fifth is fixed by their zero sum.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="draw-your-own-sample-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="draw-your-own-sample-10-minutes">Draw your own sample (10 minutes)</h3>
<p>Add a dot of your own to the class version of <a href="#fig-b07-five-means" class="quarto-xref">Figure&nbsp;<span>9.2</span></a>. Use your student number as the seed, draw your own sample of 100, and compute your mean equity offer:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>my_seed <span class="ot">&lt;-</span> <span class="dv">2412345</span>   <span class="co"># replace with your own student number</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(my_seed)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct[rows])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Submit your mean to the shared class plot on Canvas (the Mentimeter link is posted under Lecture 7). Every student uses a different seed, so every student contributes a different dot.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: what will the class plot show?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Two hundred dots will not scatter arbitrarily: they will pile up around 13.2, thin out towards the edges, and form a recognisable shape. That shape — the sampling distribution of the mean — is exactly what Lecture 8 names, describes, and puts to work.</p>
</div>
</div>
</div>
</section>
<section id="spaced-review-one-item-from-lecture-6-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="spaced-review-one-item-from-lecture-6-5-minutes">Spaced review: one item from Lecture 6 (5 minutes)</h3>
<p>Processing time is modelled as <span class="math inline">\(Y\sim N(50,100)\)</span>, and <span class="math inline">\(P(Z\le 1.5)=0.9332\)</span> is supplied. Find <span class="math inline">\(P(Y&gt;65)\)</span> by hand.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\sigma=\sqrt{100}=10\)</span> and <span class="math inline">\(z=(65-50)/10=1.5\)</span>, so <span class="math inline">\(P(Y&gt;65)=1-P(Z\le 1.5)=1-0.9332=0.0668\)</span>: under this model, about 6.7% of processing times exceed 65 minutes.</p>
</div>
</div>
</div>
</section>
<section id="worked-exam-interpretation-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="worked-exam-interpretation-5-minutes">Worked exam interpretation (5 minutes)</h3>
<p><strong>Question.</strong> A retailer’s loyalty programme has 52,000 members. An analyst draws 400 members at random; their mean January spend is €87.40. A slide then claims: “the average member spends €87.40 per month.” Identify the parameter, the estimator, and the estimate, and give two distinct objections to the claim.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The parameter is the mean January spend across all 52,000 members (fixed, unknown). The estimator is the sample mean <span class="math inline">\(\bar X\)</span> of 400 randomly drawn members’ spends. The estimate is <span class="math inline">\(\bar x=87.40\)</span> euros. Objections: first, the estimate carries sampling error — another random 400 members would give a different mean, so €87.40 should be reported with its uncertainty (Lectures 8–9); second, the claim generalises a January figure to “per month,” which the data cannot support — the frame covers one month’s spending only.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Utility: two sentences</span></p>
<p>Think of your EiA venture — or any business you know well. Write two sentences: first name one group you would genuinely want to learn about (your target population) and the best list of its members you could actually get your hands on (your frame), then say where the gap between the two would bite if you sampled from that list. There is no wrong answer; the point is connecting today’s tools to something you care about.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run campus meal-prep box venture. “I want to learn about all students on campus who buy lunch at least twice a week, but the best list I can actually get is my own mailing list. Sampling from that list overrepresents existing fans, so any satisfaction estimate would be too rosy for the market I want to enter next.”</p>
</div>
</div>
</div>
<p>You can discuss this task — and any other task in this chapter — with <strong>Tilly</strong>, the course AI assistant on Canvas: ask it to hunt for coverage gaps in your frame and to suggest who your sample would silently leave out.</p>
</div>
<p>Continue to Lecture 8: Sampling distributions and the central limit theorem.</p>
<p>Formula sheet: Lecture 7 formulas.</p>
<p>For a more formal explanation, consult <a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>, Chapter 12.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/b06-continuous-normal.html" class="pagination-link" aria-label="Lecture 6: Continuous distributions and the normal model">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/b08-sampling-distributions.html" class="pagination-link" aria-label="Lecture 8: Sampling distributions and the central limit theorem">
        <span class="nav-page-text"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>