<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 8: Sampling distributions and the central limit theorem – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/t03-exam-prep.html" rel="next">
<link href="../basic/b07-samples-estimators.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ecf4e518a83458a2bb67b2a9bf74271b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b08-sampling-distributions.html"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution, confidence intervals, and the two-sided test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Inference and tests against zero</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals betray it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/reading-ladder.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reading research papers</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-class" id="toc-in-class" class="nav-link" data-scroll-target="#in-class">In class</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b08-sampling-distributions.html"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b08" class="quarto-section-identifier"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Lecture 8, you can</span></p>
<ul>
<li>distinguish a population distribution, a sampling distribution, and a realised estimate;</li>
<li>derive the mean and variance of a sample mean using the linearity rules;</li>
<li>calculate and interpret a standard error;</li>
<li>use the square-root rule to relate sample size to precision;</li>
<li>state the central limit theorem for this course’s conditions and apply it to means and proportions;</li>
<li>explain what the law of large numbers and the CLT each claim — and what neither of them repairs.</li>
</ul>
</div>
<div class="driving-question">
<p><span class="label">Driving question</span></p>
<p class="dq-context">
Any number computed from a sample would have come out differently with a different sample. Before acting on an estimate, a careful analyst asks how much such numbers wobble — and what tames the wobble.
</p>
<p>Our sample of 100 gave mean equity 12.76. How wrong could that number be, and why does averaging make it trustworthy even though single pitches are wildly skewed?</p>
</div>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p><span class="time-budget">Total preparation time: about 30 minutes.</span></p>
<div class="video-prep">
<p><span class="label">Video preparation (15 minutes)</span><br> Watch <a href="https://www.youtube.com/watch?v=Yh5bR7X3ch8">The Weak Law of Large Numbers</a> and <a href="https://www.youtube.com/watch?v=IrKUM3nNXJE">The Central Limit Theorem</a>. Focus on what converges as sample size grows and on which distribution becomes approximately normal. All links are also listed in the <a href="../resources/video-guide.html">External Video Guide</a>.</p>
</div>
<p><strong>Reactivate (10 minutes).</strong> Classify each object as a <em>population distribution</em>, a <em>sampling distribution</em>, or a <em>realised estimate</em>:</p>
<ol type="1">
<li>the distribution of equity offered across individual pitches;</li>
<li>the distribution of <span class="math inline">\(\bar X\)</span> across all possible samples of 40 pitches;</li>
<li>the single mean calculated from one observed sample.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The first is a population distribution, the second is a sampling distribution, and the third is a realised estimate. Keep the three apart all lecture: the middle one is the new object.</p>
</div>
</div>
</div>
<p><strong>Predict (5 minutes).</strong> Answer the one-click Mentimeter question posted on Canvas before you come to class: to cut the typical error of a sample mean <strong>in half</strong>, do you need <span class="math inline">\(2\times\)</span>, <span class="math inline">\(4\times\)</span>, or <span class="math inline">\(10\times\)</span> the observations? Commit to an answer; the lecture resolves it.</p>
<p>If square roots, sums, degrees of freedom, or standardisation are not secure, review <a href="../resources/math-refresher.html">Mathematics Refresher: powers, roots, and standardisation</a>.</p>
</section>
<section id="in-class" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-class">In class</h2>
<p>The session opens with the usual four-minute entry quiz on the prep videos, then turns to the driving question. Start from where Lecture 7 ended: <strong>the five dots.</strong> Five random samples of 100 pitches produced five different sample means, plotted on one axis, while the population mean sat still underneath them. During the break you guessed where a sixth mean would land. This lecture is about the <em>pattern</em> behind those dots — the hardest and most useful idea in the course.</p>
<section id="the-pattern-behind-the-five-dots" class="level3">
<h3 class="anchored" data-anchor-id="the-pattern-behind-the-five-dots">The pattern behind the five dots</h3>
<p>Imagine not five samples but <em>every possible</em> random sample of the same size, each producing its own sample mean. The distribution of those possible values of <span class="math inline">\(\bar X\)</span> is its <strong>sampling distribution</strong>. It describes uncertainty in an <em>estimator</em>, not variation among individual pitches:</p>
<ul>
<li>the <strong>population distribution</strong> describes how equity offers vary across the 1,441 pitches;</li>
<li>the <strong>sampling distribution</strong> describes how <span class="math inline">\(\bar X\)</span> would vary across repeated samples;</li>
<li>a <strong>realised estimate</strong>, such as 12.76, is one draw from that sampling distribution.</li>
</ul>
<p>The two population parameters this chapter keeps returning to are the frame mean and SD of equity offered, and the frame deal proportion. Construct them yourself — because the 1,441 records are the entire frame, the SD divides by <span class="math inline">\(N\)</span>, not <span class="math inline">\(n-1\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>mu_equity <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>sigma_equity <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((sharks<span class="sc">$</span>equity_offered_pct <span class="sc">-</span> mu_equity)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>p_deal <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>deal_on_show)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mu_equity =</span> mu_equity, <span class="at">sigma_equity =</span> sigma_equity, <span class="at">p_deal =</span> p_deal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   mu_equity sigma_equity       p_deal 
  13.2076128    8.4414247    0.6120749 </code></pre>
</div>
</div>
<p>So <span class="math inline">\(\mu = 13.21\)</span> percentage points, <span class="math inline">\(\sigma = 8.44\)</span> percentage points, and <span class="math inline">\(p = 0.612\)</span>. These are fixed numbers. What varies is any statistic computed from a random sample of the frame.</p>
</section>
<section id="explore-it-the-sampling-distribution-lab" class="level3">
<h3 class="anchored" data-anchor-id="explore-it-the-sampling-distribution-lab">Explore it: the sampling-distribution lab</h3>
<p>Before any formula, see the sampling distribution <em>form</em>. The lab below shows the strongly right-skewed population histogram of the 1,441 equity offers on the left. Use the <strong>slider</strong> to choose a sample size <span class="math inline">\(n\)</span> and press <strong>Redraw</strong> to draw many random samples of that size: each sample’s mean drops into the histogram forming on the right, next to the population.</p>
<iframe src="../assets/widgets/sampling-lab.html" width="100%" height="520" style="border:1px solid #C9D4DC; border-radius:6px;" title="Sampling distribution lab">
</iframe>
<p>Work through three settings and watch three things — centre, spread, shape:</p>
<ol type="1">
<li>Set <span class="math inline">\(n = 2\)</span> and redraw several times. The means scatter widely and the histogram of means is still skewed.</li>
<li>Set <span class="math inline">\(n = 25\)</span>. The histogram of means narrows and starts to look symmetric, centred near 13.2.</li>
<li>Slide up to <span class="math inline">\(n = 100\)</span>. The histogram of means is a tight, bell-shaped pile around the population mean, even though the population histogram beside it has not changed at all.</li>
</ol>
<p>Everything in the rest of this lecture is the mathematics of what you just manipulated: <em>where</em> the pile sits, <em>how wide</em> it is, and <em>why</em> it becomes bell-shaped.</p>
</section>
<section id="the-mean-and-variance-of-a-sample-mean" class="level3">
<h3 class="anchored" data-anchor-id="the-mean-and-variance-of-a-sample-mean">The mean and variance of a sample mean</h3>
<p>For independent, identically distributed variables <span class="math inline">\(X_1,\ldots,X_n\)</span> with population mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>,</p>
<p><span class="math display">\[
E[\bar X]=\mu,
\qquad
\operatorname{Var}(\bar X)=\frac{\sigma^2}{n},
\qquad
\operatorname{SD}(\bar X)=\frac{\sigma}{\sqrt n}.
\]</span></p>
<p>The first equality says that <span class="math inline">\(\bar X\)</span> is <strong>unbiased</strong> for <span class="math inline">\(\mu\)</span>: the pile of sample means is centred on the parameter, exactly as in the lab. The third quantity — the SD of the estimator across repeated samples — is called the <strong>standard error</strong> (SE). An SD describes variation among <em>observations</em>; an SE describes variation of an <em>estimator</em>.</p>
<p>These are not new facts. They follow from the linearity rules you already have on the formula sheet (the Lecture 8 block, and the Refresher’s linearity rules):</p>
<ul>
<li><span class="math inline">\(E[X+Y]=E[X]+E[Y]\)</span> and <span class="math inline">\(E[aX]=aE[X]\)</span>, so <span class="math inline">\(E[\bar X]=\frac{1}{n}\sum_i E[X_i]=\frac{1}{n}\,n\mu=\mu\)</span>;</li>
<li><span class="math inline">\(\operatorname{Var}(aX)=a^2\operatorname{Var}(X)\)</span> and, for <strong>independent</strong> variables, <span class="math inline">\(\operatorname{Var}(X+Y)=\operatorname{Var}(X)+\operatorname{Var}(Y)\)</span>, so</li>
</ul>
<p><span class="math display">\[
\operatorname{Var}(\bar X)
=\operatorname{Var}\!\left(\frac{X_1+\cdots+X_n}{n}\right)
=\frac{1}{n^2}\sum_{i=1}^{n}\operatorname{Var}(X_i)
=\frac{n\sigma^2}{n^2}
=\frac{\sigma^2}{n}.
\]</span></p>
<p>Independent positive and negative deviations partly cancel in an average. That cancellation is why the right-hand histogram in the lab is so much narrower than the population histogram.</p>
<p>In practice <span class="math inline">\(\sigma\)</span> is usually unknown and is estimated by the sample SD <span class="math inline">\(S\)</span>, giving the estimated standard error <span class="math inline">\(\operatorname{SE}(\bar X)=S/\sqrt n\)</span>. Substituting an estimate for a parameter adds a little extra uncertainty; Lecture 9 opens with the price of that substitution.</p>
<div id="exm-b08-se" class="theorem example">
<p><span class="theorem-title"><strong>Example 10.1 (Worked example: E, Var, and SE for σ = 12, n = 36)</strong></span> A population has mean <span class="math inline">\(\mu\)</span> and SD <span class="math inline">\(\sigma=12\)</span>. A random sample of <span class="math inline">\(n=36\)</span> observations is drawn. Find the mean, variance, and SE of <span class="math inline">\(\bar X\)</span>, naming the rule used at each step.</p>
<ul>
<li><strong>Mean.</strong> By linearity of expectation (<span class="math inline">\(E[X+Y]=E[X]+E[Y]\)</span>, <span class="math inline">\(E[aX]=aE[X]\)</span>), <span class="math inline">\(E[\bar X]=\mu\)</span> — whatever <span class="math inline">\(\mu\)</span> is, the sample mean is unbiased for it.</li>
<li><strong>Variance.</strong> By <span class="math inline">\(\operatorname{Var}(aX)=a^2\operatorname{Var}(X)\)</span> and additivity of variance under independence, <span class="math inline">\(\operatorname{Var}(\bar X)=\sigma^2/n=12^2/36=144/36=4\)</span>.</li>
<li><strong>SE.</strong> Take the square root: <span class="math inline">\(\operatorname{SD}(\bar X)=\sqrt 4=2\)</span>, i.e.&nbsp;<span class="math inline">\(\sigma/\sqrt n=12/6=2\)</span>.</li>
</ul>
<p>The typical distance between a sample mean and <span class="math inline">\(\mu\)</span> is about 2 units — one sixth of the typical distance of a <em>single</em> observation from <span class="math inline">\(\mu\)</span>. All three rules are on the formula sheet; the derivations are in the <a href="../resources/math-refresher.html">Mathematics Refresher</a>.</p>
</div>
</section>
<section id="the-square-root-rule" class="level3">
<h3 class="anchored" data-anchor-id="the-square-root-rule">The square-root rule</h3>
<p>Precision grows with <span class="math inline">\(\sqrt n\)</span>, not with <span class="math inline">\(n\)</span>. This resolves the prep prediction: to cut the SE <strong>in half</strong> you need <span class="math inline">\(\mathbf{4\times}\)</span> the observations, because</p>
<p><span class="math display">\[
\frac{\sigma}{\sqrt{4n}}=\frac{1}{2}\cdot\frac{\sigma}{\sqrt n}.
\]</span></p>
<p>Doubling the sample buys less than you might hope; each extra digit of precision gets more expensive. This is worth knowing before you budget for any data collection.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it: how large must n become to cut an SE from 4 to 1?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In class this is the pair task before the break. Complete the missing steps before opening the answer.</p>
<p><em>Step 1 (given).</em> The SE must fall by a factor of <span class="math inline">\(4/1 = 4\)</span>.</p>
<p><em>Step 2 (you).</em> The SE is proportional to <span class="math inline">\(1/\sqrt n\)</span>. By what factor must <span class="math inline">\(n\)</span> change to divide the SE by 4?</p>
<p><em>Step 3 (you).</em> If the original sample had <span class="math inline">\(n=50\)</span>, how many observations does the new design need?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Dividing the SE by 4 requires multiplying <span class="math inline">\(n\)</span> by <span class="math inline">\(4^2=16\)</span>: the square-root rule in reverse. From <span class="math inline">\(n=50\)</span> the design needs <span class="math inline">\(16\times 50=800\)</span> observations. Precision is bought at a quadratic price.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-central-limit-theorem" class="level3">
<h3 class="anchored" data-anchor-id="the-central-limit-theorem">The central limit theorem</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/the-central-limit-theorem/">19.2 The Central Limit Theorem</a>.
</p>
<p>The lab showed one more pattern that the mean-and-variance rules do not explain: the pile of sample means became <em>bell-shaped</em>, even though the population is strongly skewed. That is the <strong>central limit theorem</strong> (CLT). Under the independent-sampling conditions used in this course, the standardised sample mean</p>
<p><span class="math display">\[
Z=\frac{\bar X-\mu}{\sigma/\sqrt n}
\]</span></p>
<p>approaches a standard normal distribution as <span class="math inline">\(n\)</span> grows. Equivalently,</p>
<p><span class="math display">\[
\bar X\ \dot\sim\ N\!\left(\mu,\frac{\sigma^2}{n}\right)
\]</span></p>
<p>for a sufficiently large sample. The dot above <span class="math inline">\(\sim\)</span> signals an approximation. The normal model from Lecture 6 returns here — not as a model for the <em>data</em>, where it failed for equity offers, but as a model for the <em>sample mean</em>.</p>
<p>There is <strong>no universal rule that <span class="math inline">\(n=30\)</span> is always enough.</strong> Strong skewness, extreme outliers, or dependence between observations may require much more data. If the population itself is normal, the sample mean is exactly normal for every <span class="math inline">\(n\)</span>.</p>
<p><a href="#fig-b08-clt" class="quarto-xref">Figure&nbsp;<span>10.1</span></a> shows the simulation behind the claim: 5,000 sample means of <span class="math inline">\(n=5\)</span> draws and 5,000 sample means of <span class="math inline">\(n=40\)</span> draws from the equity variable.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>mu_equity <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>sigma_equity <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((sharks<span class="sc">$</span>equity_offered_pct <span class="sc">-</span> mu_equity)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">208</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">5000</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>means_5 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, <span class="fu">mean</span>(<span class="fu">sample</span>(sharks<span class="sc">$</span>equity_offered_pct, <span class="dv">5</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">replace =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>means_40 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, <span class="fu">mean</span>(<span class="fu">sample</span>(sharks<span class="sc">$</span>equity_offered_pct, <span class="dv">40</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">replace =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>panel_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"n = 5"</span>, <span class="st">"n = 40"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>sim_means <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_mean =</span> <span class="fu">c</span>(means_5, means_40),</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">panel =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(panel_levels, <span class="at">each =</span> B), <span class="at">levels =</span> panel_levels)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>all_means <span class="ot">&lt;-</span> <span class="fu">c</span>(means_5, means_40)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>shared_limits <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">floor</span>(<span class="fu">min</span>(all_means)), <span class="fu">ceiling</span>(<span class="fu">max</span>(all_means)))</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>shared_breaks <span class="ot">&lt;-</span> <span class="fu">seq</span>(shared_limits[<span class="dv">1</span>], shared_limits[<span class="dv">2</span>], <span class="at">length.out =</span> <span class="dv">36</span>)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>normal_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(shared_limits[<span class="dv">1</span>], shared_limits[<span class="dv">2</span>], <span class="at">length.out =</span> <span class="dv">400</span>)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>normal_curves <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">x =</span> normal_grid, <span class="at">panel =</span> panel_levels[<span class="dv">1</span>],</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>             <span class="at">density =</span> <span class="fu">dnorm</span>(normal_grid, mu_equity,</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>                             sigma_equity <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">5</span>))),</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">x =</span> normal_grid, <span class="at">panel =</span> panel_levels[<span class="dv">2</span>],</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>             <span class="at">density =</span> <span class="fu">dnorm</span>(normal_grid, mu_equity,</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>                             sigma_equity <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">40</span>)))</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>normal_curves<span class="sc">$</span>panel <span class="ot">&lt;-</span> <span class="fu">factor</span>(normal_curves<span class="sc">$</span>panel, <span class="at">levels =</span> panel_levels)</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sim_means, <span class="fu">aes</span>(sample_mean)) <span class="sc">+</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">breaks =</span> shared_breaks,</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> normal_curves, <span class="fu">aes</span>(x, density),</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>            <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> panel, <span class="at">scales =</span> <span class="st">"fixed"</span>) <span class="sc">+</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sample mean equity offered (%)"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>),</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b08-clt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b08-clt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b08-sampling-distributions_files/figure-html/fig-b08-clt-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b08-clt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.1: Simulated sampling distributions of the mean equity offered for n = 5 (left) and n = 40 (right), each based on 5,000 samples, with the corresponding normal approximations (orange curves). Both panels use the same axes.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Read <a href="#fig-b08-clt" class="quarto-xref">Figure&nbsp;<span>10.1</span></a> with the five-step sequence. (1) Each bar counts simulated sample means, not pitches. (2) The horizontal axis is the possible sample mean of equity offered, in percentage points — <strong>the same range in both panels</strong>, so widths can be compared directly. (3) The vertical axis is density, also on a shared scale. (4) The pattern: the <span class="math inline">\(n=40\)</span> pile is far narrower and visibly closer to its orange normal curve than the <span class="math inline">\(n=5\)</span> pile, which still leans right like the population. (5) Takeaway: averaging 40 independent draws from a wildly skewed population already produces a concentrated, nearly normal sampling distribution.</p>
</section>
<section id="sample-proportions-are-sample-means" class="level3">
<h3 class="anchored" data-anchor-id="sample-proportions-are-sample-means">Sample proportions are sample means</h3>
<p>For a Bernoulli variable <span class="math inline">\(X\)</span> with <span class="math inline">\(P(X=1)=p\)</span> (Lecture 3),</p>
<p><span class="math display">\[
E[X]=p,
\qquad
\operatorname{Var}(X)=p(1-p).
\]</span></p>
<p>A sample proportion is just the sample mean of an indicator, so every result above applies immediately: <span class="math inline">\(\widehat P=\bar X\)</span> satisfies</p>
<p><span class="math display">\[
E[\widehat P]=p,
\qquad
\operatorname{SE}(\widehat P)=\sqrt{\frac{p(1-p)}{n}}.
\]</span></p>
<p>Its sampling distribution is approximately normal when the expected numbers of successes and failures are both sufficiently large. This course uses <span class="math inline">\(np\ge10\)</span> <strong>and</strong> <span class="math inline">\(n(1-p)\ge10\)</span> as the working rule (the <em>success–failure condition</em>).</p>
<div id="exm-b08-proportion" class="theorem example">
<p><span class="theorem-title"><strong>Example 10.2 (Worked example: SE of the deal proportion at n = 100)</strong></span> Suppose we draw a random sample of <span class="math inline">\(n=100\)</span> pitches from the frame, where the deal proportion is <span class="math inline">\(p=0.612\)</span>. How far is the sample deal proportion typically from 0.612?</p>
<ul>
<li><strong>SE.</strong> <span class="math inline">\(\operatorname{SE}(\widehat P)=\sqrt{0.612\,(1-0.612)/100}
=\sqrt{0.2375/100}\approx 0.0487\)</span>, about 4.9 percentage points.</li>
<li><strong>Success–failure check.</strong> <span class="math inline">\(np=100(0.612)=61.2\ge 10\)</span> and <span class="math inline">\(n(1-p)=100(0.388)=38.8\ge 10\)</span>, so the normal approximation is reasonable.</li>
</ul>
<p>In R, using <code>p_deal</code> as constructed above:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>p_deal <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>deal_on_show)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">SE_deal_proportion_n_100 =</span> <span class="fu">sqrt</span>(p_deal <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_deal) <span class="sc">/</span> <span class="dv">100</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">successes =</span> <span class="dv">100</span> <span class="sc">*</span> p_deal, <span class="at">failures =</span> <span class="dv">100</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_deal))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SE_deal_proportion_n_100                successes                 failures 
              0.04872773              61.20749480              38.79250520 </code></pre>
</div>
</div>
</div>
</section>
<section id="the-law-of-large-numbers-and-the-clt-answer-different-questions" class="level3">
<h3 class="anchored" data-anchor-id="the-law-of-large-numbers-and-the-clt-answer-different-questions">The law of large numbers and the CLT answer different questions</h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/the-weak-law-of-large-numbers/">18.4 The Weak Law of Large Numbers</a>.
</p>
<ul>
<li>The <strong>law of large numbers</strong> (LLN) says <em>where the pile goes</em>: <span class="math inline">\(\bar X\)</span> becomes close to <span class="math inline">\(\mu\)</span> as <span class="math inline">\(n\)</span> grows.</li>
<li>The <strong>CLT</strong> says <em>what the pile looks like</em>: the approximate shape and scale of the sampling distribution after standardisation.</li>
</ul>
<p>One is about convergence of a value, the other about convergence of a distribution. Both assume the sampling is random; neither repairs a sample that was selected badly in the first place.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: match each statement to LLN, CLT, or neither
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>“With enough random draws, the sample mean equity will be very close to 13.21.”</li>
<li>“For <span class="math inline">\(n=100\)</span> random draws, the sample mean equity is approximately <span class="math inline">\(N(13.21, 0.844^2)\)</span>.”</li>
<li>“With enough respondents, our LinkedIn poll will represent Dutch founders.”</li>
</ol>
<p>Statement 1 is the LLN, statement 2 is the CLT, and statement 3 is <strong>neither</strong>: no theorem turns a self-selected sample into a representative one — see the caveat box.</p>
</div>
</div>
</div>
<div class="caveat-box">
<p><span class="label">What a bigger sample can and cannot fix</span></p>
<p>Everything in this lecture concerns <strong>random sampling error</strong>: the unavoidable wobble of a statistic across random samples. More observations shrink that wobble at the square-root rate. They do <strong>nothing</strong> for <strong>selection bias</strong>: if pitches enter the data because producers chose good television, a sample of a million such pitches still describes televised pitches, not entrepreneurs in general. An SE of 0.84 quantifies precision <em>within the recorded-pitch frame</em>; it is silent about who got into the frame, and an on-air deal is still not a completed investment.</p>
</div>
</section>
<section id="answering-the-driving-question" class="level3">
<h3 class="anchored" data-anchor-id="answering-the-driving-question">Answering the driving question</h3>
<p>Our sample of 100 gave mean equity 12.76, while the frame mean is 13.21. How wrong could 12.76 have been? Its standard error:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>sigma_equity <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((sharks<span class="sc">$</span>equity_offered_pct <span class="sc">-</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct))<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">SE_mean_n_25 =</span> sigma_equity <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">25</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">SE_mean_n_100 =</span> sigma_equity <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> SE_mean_n_25 SE_mean_n_100 
    1.6882849     0.8441425 </code></pre>
</div>
</div>
<p>At <span class="math inline">\(n=100\)</span> the SE is about <strong>0.84 percentage points</strong>: a random-sample mean typically lands within about 0.84 points of 13.21, and rarely more than about two SEs away. (At <span class="math inline">\(n=25\)</span> the SE would be twice as large — the square-root rule again.) Averaging is trustworthy despite the wild skew of single pitches because deviations cancel (the variance rule) and the CLT gives the mean a predictable, nearly normal distribution.</p>
<p><strong>Next:</strong> We can now say how much a sample mean typically wobbles: one standard error. Turning that into a sentence a report can carry — “the frame mean plausibly lies between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>” — needs one more ingredient, because in a real sample the population <span class="math inline">\(\sigma\)</span> is unknown and must be estimated too, adding uncertainty of its own. Lecture 9 introduces the t distribution that prices in this extra uncertainty, builds the confidence interval from it, and runs the course’s first formal test of a benchmark claim.</p>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p><span class="time-budget">Total practice time: about 55 minutes.</span></p>
<section id="retrieval-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="retrieval-10-minutes">Retrieval (10 minutes)</h3>
<ol type="1">
<li>What varies in a sampling distribution?</li>
<li>Why is <span class="math inline">\(E[\bar X]=\mu\)</span> called unbiasedness?</li>
<li>What is the difference between an SD and an SE?</li>
<li>To cut an SE in half, by what factor must the sample size grow, and why?</li>
<li>What does the CLT say becomes approximately normal?</li>
<li>Why does a larger sample not remove selection bias?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The statistic varies across possible repeated samples; the parameter and the population stay fixed.</li>
<li>Its long-run average across repeated samples equals the population parameter.</li>
<li>An SD describes variation among observations; an SE describes variation of an estimator across samples.</li>
<li>By a factor of 4: the SE is proportional to <span class="math inline">\(1/\sqrt n\)</span>, so halving it requires <span class="math inline">\(2^2=4\)</span> times the observations.</li>
<li>The standardised sample mean — and therefore, approximately, the sampling distribution of the mean. Not the original observations.</li>
<li>Sample size shrinks random error only. It does not change how units entered the sampling frame or the sample.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="from-worked-to-faded-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="from-worked-to-faded-5-minutes">From worked to faded (5 minutes)</h3>
<p>Re-read the worked SE calculation (<a href="#exm-b08-se" class="quarto-xref">Example&nbsp;<span>10.1</span></a>). Then complete the same calculation for a proportion: a planned survey expects <span class="math inline">\(p=0.30\)</span> and <span class="math inline">\(n=100\)</span>.</p>
<p><em>Step 1 (given).</em> The SE formula for a proportion is <span class="math inline">\(\sqrt{p(1-p)/n}\)</span>.</p>
<p><em>Step 2 (you).</em> Calculate the SE.</p>
<p><em>Step 3 (you).</em> Check the success–failure condition.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\operatorname{SE}(\widehat P)=\sqrt{0.30(0.70)/100}\approx 0.0458\)</span>, about 4.6 percentage points. The expected counts are <span class="math inline">\(np=30\)</span> successes and <span class="math inline">\(n(1-p)=70\)</span> failures, both at least 10, so the normal approximation is acceptable.</p>
</div>
</div>
</div>
</section>
<section id="practice-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="practice-10-minutes">Practice (10 minutes)</h3>
<ol type="1">
<li>If <span class="math inline">\(\sigma=15\)</span> and <span class="math inline">\(n=25\)</span>, find <span class="math inline">\(E[\bar X]\)</span>, <span class="math inline">\(\operatorname{Var}(\bar X)\)</span>, and <span class="math inline">\(\operatorname{SE}(\bar X)\)</span>, naming the rule used at each step.</li>
<li>How large must <span class="math inline">\(n\)</span> become to reduce an SE from 6 to 1.5?</li>
<li>For a sample proportion with <span class="math inline">\(\hat p\)</span> expected near 0.50 and <span class="math inline">\(n=64\)</span>, calculate the SE and check the success–failure condition.</li>
<li>Explain why the normal approximation is more convincing in the right-hand panel of <a href="#fig-b08-clt" class="quarto-xref">Figure&nbsp;<span>10.1</span></a>.</li>
<li>State one threat to the CLT-based approximation that a large <span class="math inline">\(n\)</span> alone does not solve.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(E[\bar X]=\mu\)</span> (linearity of expectation); <span class="math inline">\(\operatorname{Var}(\bar X)=\sigma^2/n=225/25=9\)</span> (variance of a scaled sum of independent variables); <span class="math inline">\(\operatorname{SE}(\bar X)=\sqrt 9=3\)</span>.</li>
<li>The SE must fall by a factor of 4, so the sample size must grow by <span class="math inline">\(4^2=16\)</span> times.</li>
<li><span class="math inline">\(\sqrt{0.50(0.50)/64}=0.0625\)</span>. Expected counts are 32 and 32, both at least 10.</li>
<li>Averaging 40 observations cancels more of the skewness and shrinks the sampling variation more than averaging 5 observations; the histogram hugs its normal curve far more closely.</li>
<li>Dependence between observations, or a non-representative sampling process. (Extreme outliers slow the approximation too.)</li>
</ol>
</div>
</div>
</div>
</section>
<section id="widget-homework-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="widget-homework-10-minutes">Widget homework (10 minutes)</h3>
<p>Open the sampling-distribution lab again and run these three settings. For each, redraw several times and write <strong>one sentence</strong> on what the histogram of sample means shows:</p>
<ol type="1">
<li><span class="math inline">\(n = 2\)</span>;</li>
<li><span class="math inline">\(n = 25\)</span>;</li>
<li><span class="math inline">\(n = 100\)</span>.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>At <span class="math inline">\(n=2\)</span> the sample means scatter widely and their histogram is still right-skewed, echoing the population shape.</li>
<li>At <span class="math inline">\(n=25\)</span> the histogram of means is clearly narrower and roughly symmetric, centred near 13.2.</li>
<li>At <span class="math inline">\(n=100\)</span> the means form a tight bell around the population mean, with a typical deviation of less than one percentage point — the SE of about 0.84 made visible.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="spaced-review-one-item-each-from-lectures-7-and-6-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="spaced-review-one-item-each-from-lectures-7-and-6-10-minutes">Spaced review: one item each from Lectures 7 and 6 (10 minutes)</h3>
<ol type="1">
<li><em>(Lecture 7.)</em> The sample variance divides by <span class="math inline">\(n-1\)</span>, not <span class="math inline">\(n\)</span>. In one or two sentences, why?</li>
<li><em>(Lecture 6.)</em> Daily revenue is modelled as <span class="math inline">\(X\sim N(10, 2^2)\)</span> (in thousands of euros). Find <span class="math inline">\(P(X&gt;13)\)</span>.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The deviations are measured from the sample mean, which was itself estimated from the data; once it is fixed, only <span class="math inline">\(n-1\)</span> deviations can vary freely, and dividing by <span class="math inline">\(n-1\)</span> removes the resulting downward bias.</li>
<li>Standardise: <span class="math inline">\(z=(13-10)/2=1.5\)</span>, so <span class="math inline">\(P(X&gt;13)=P(Z&gt;1.5)\approx 0.067\)</span>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="worked-exam-interpretation-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="worked-exam-interpretation-5-minutes">Worked exam interpretation (5 minutes)</h3>
<p><strong>Question.</strong> Mean equity offered in the recorded-pitch frame is <span class="math inline">\(\mu=13.21\)</span> with <span class="math inline">\(\sigma=8.44\)</span>. A random sample of <span class="math inline">\(n=100\)</span> pitches is drawn. Using the CLT, find the probability that the sample mean exceeds 14.5 percentage points.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>By the CLT, <span class="math inline">\(\bar X\ \dot\sim\ N(13.21, 0.844^2)\)</span> since <span class="math inline">\(\operatorname{SE}=8.44/\sqrt{100}=0.844\)</span>. Standardise: <span class="math inline">\(z=(14.5-13.21)/0.844\approx 1.53\)</span>, so <span class="math inline">\(P(\bar X&gt;14.5)\approx P(Z&gt;1.53)\approx 0.063\)</span>. About a 6% chance — and note the question is about the <em>mean</em>, not a single pitch: for one pitch the normal model was already rejected in Lecture 6.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Utility: two sentences</span></p>
<p>Think of your EiA venture — or any business you know well. Name one number you would estimate from a sample (customer satisfaction, conversion rate, average basket size) and write two sentences: first say how you would draw the sample and roughly what SE-driven wobble you would tolerate, then say whether collecting four times the data would be worth halving that wobble for the decision at hand.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run campus meal-prep box venture. “I would estimate the conversion rate of tasting-stand visitors from a random 100 of them, and a wobble of about <span class="math inline">\(\pm 5\)</span> percentage points is fine for deciding on a second stand. Collecting four times the data would halve that to about <span class="math inline">\(\pm 2.5\)</span> points, which is not worth four more tasting days for this decision.”</p>
</div>
</div>
</div>
<p>You can discuss this task — and any other task in this chapter — with <strong>Tilly</strong>, the course AI assistant on Canvas: ask it to help you sketch the sample-size trade-off for your own numbers.</p>
</div>
<p>Continue to Lecture 9: The t distribution, confidence intervals, and the two-sided test.</p>
<p>Formula sheet: Lecture 8 formulas.</p>
<p>For a more formal explanation, consult <a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>, Chapters 13 and 14.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/b07-samples-estimators.html" class="pagination-link" aria-label="Lecture 7: Samples, parameters, and estimators">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/t03-exam-prep.html" class="pagination-link" aria-label="Tutorial 3: Normal models, sampling, and standard errors">
        <span class="nav-page-text"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>