<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 9: The t distribution and confidence intervals – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/b10-testing-errors-power.html" rel="next">
<link href="../basic/t03-exam-prep.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1825cde5eff643560dd74da544ac5848.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b09-t-confidence-intervals.html"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Inference and tests against zero</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#lecture-material" id="toc-lecture-material" class="nav-link" data-scroll-target="#lecture-material">Lecture material</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b09-t-confidence-intervals.html"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b09" class="quarto-section-identifier"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Lecture 9, you can</span></p>
<ul>
<li>explain why estimating the population SD leads to a t distribution with <span class="math inline">\(n-1\)</span> degrees of freedom, and use its critical values</li>
<li>construct a t confidence interval for a population mean</li>
<li>express comparison with a benchmark as a parameter equal to zero</li>
<li>state a two-sided null and alternative hypothesis</li>
<li>calculate a t statistic and say what it measures</li>
<li>state correctly what “95% confidence” is a property of.</li>
</ul>
</div>
<div class="must-know">
<p><span class="label">Must know</span></p>
<p><strong>Be able to do yourself:</strong></p>
<ul>
<li>build a 95% interval by hand from the mean, the standard deviation, the sample size, and a supplied t value</li>
<li>write <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span> for a gap from a benchmark</li>
<li>calculate a t statistic and say what it measures</li>
<li>say what “95%” refers to.</li>
</ul>
<p><strong>Enough to recognise:</strong></p>
<ul>
<li>the t curves for different degrees of freedom</li>
<li><code>qt()</code>.</li>
</ul>
</div>
<div class="driving-question">
<p><span class="label">Driving question</span></p>
<p class="dq-context">
Suppose an advisor tells founders that pitches typically offer investors about 15 percent equity. Our data can check such a benchmark, if we take the variation between samples into account.
</p>
<p>Is the mean equity offered (<code>equity_offered_pct</code>) across all recorded Shark Tank pitches really different from 15 percent?</p>
</div>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p><span class="time-budget">Total preparation time: about 30 minutes.</span></p>
<p><strong>Minimum path:</strong> the video preparation and the prediction. <strong>Full path:</strong> everything in this section.</p>
<div class="video-prep">
<p><span class="label">Video preparation (20 minutes)</span><br> Watch <a href="https://www.youtube.com/watch?v=NInNhFm046w">Confidence Intervals</a>, <a href="https://www.youtube.com/watch?v=MzvRQFYUEFU">Confidence Intervals When the Variance Is Unknown</a>, and <a href="https://www.youtube.com/watch?v=ti9NFdjf3sM">Introduction to Hypothesis Testing</a>. Focus on repeated-sampling coverage, the t reference distribution, and the role of the null value. All links are also listed in the <a href="../resources/video-guide.html">External Video Guide</a>.</p>
</div>
<p><strong>Reactivate (5 minutes).</strong> Let <span class="math inline">\(X\)</span> be the equity offered in a pitch (<code>equity_offered_pct</code>, in percentage points) and define the <strong>equity gap</strong></p>
<p><span class="math display">\[
G = X - 15.
\]</span></p>
<p>Write two-sided hypotheses for the question: “Does the population mean of the equity offered differ from 15 percentage points?”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your preparation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(\delta=E[G]=\mu_X-15\)</span>. Then</p>
<p><span class="math display">\[
H_0:\delta=0
\qquad\text{versus}\qquad
H_1:\delta\ne0.
\]</span></p>
<p>This is equivalent to testing <span class="math inline">\(H_0:\mu_X=15\)</span> against <span class="math inline">\(H_1:\mu_X\ne15\)</span>. Writing the gap as <span class="math inline">\(\delta\)</span> turns the question into “is the difference zero?”. Regression coefficients are tested in the same way later.</p>
</div>
</div>
</div>
<p><strong>Predict (5 minutes).</strong> Answer the one-click Wooclap question posted on Canvas before you come to class: in a real sample, the unknown population SD <span class="math inline">\(\sigma\)</span> must be replaced by the sample SD <span class="math inline">\(S\)</span>. Should that substitution make a 95% interval <strong>wider</strong>, <strong>narrower</strong>, or leave it <strong>unchanged</strong>? Commit to an answer. You find the answer in the lecture material.</p>
<p>If intervals, standardisation, or degrees of freedom feel rusty, review <a href="../resources/math-refresher.html">Mathematics Refresher: intervals, standardisation, and degrees of freedom</a>.</p>
</section>
<section id="lecture-material" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="lecture-material">Lecture material</h2>
<p>Lecture 8 gave a sample mean and its standard error. This section turns those two numbers into a range of plausible values for the parameter, the confidence interval. It ends with the t statistic, which measures how far an estimate lies from a benchmark. Lecture 10 uses it to reach a decision.</p>
<p class="concept-video">
<strong>Video explanations (review):</strong> <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/confidence-intervals/">20.5 Confidence Intervals</a>, <a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/confidence-intervals-for-the-mean-when-the-variance-is-unknown/">20.7 Confidence Intervals with Unknown Variance</a>, and <a href="https://www.youtube.com/watch?v=ti9NFdjf3sM">Introduction to Hypothesis Testing</a>.
</p>
<section id="start-with-a-founders-question" class="level3">
<h3 class="anchored" data-anchor-id="start-with-a-founders-question">Start with a founder’s question</h3>
<p>Suppose an advisor tells you that founders on the show offer about 15% of their company. You have looked at 100 pitches, chosen by chance, and their average equity offered (<code>equity_offered_pct</code>) is 12.76%. Is the advisor wrong? Or is 12.76 simply what 100 pitches can give by chance when the true average is 15? R answers with one command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>sample_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>pitch_sample <span class="ot">&lt;-</span> sharks[sample_rows, ]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(pitch_sample<span class="sc">$</span>equity_offered_pct, <span class="at">mu =</span> <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  pitch_sample$equity_offered_pct
t = -2.9061, df = 99, p-value = 0.004515
alternative hypothesis: true mean is not equal to 15
95 percent confidence interval:
 11.23059 14.28941
sample estimates:
mean of x 
    12.76 </code></pre>
</div>
</div>
<p>R prints the mean of the sample, 12.76, a t value of <span class="math inline">\(-2.91\)</span> with 99 degrees of freedom, a p-value of 0.0045, and an interval from 11.23 to 14.29. An AI assistant would hand you the same output with a confident sentence about it. This lecture and the next give you what you need to read the output yourself and to check that sentence: where the interval comes from, why it uses a t value and 99 degrees of freedom, and what the p-value does and does not say. This lecture builds the interval and the t value. Lecture 10 adds the p-value.</p>
</section>
<section id="from-a-benchmark-to-a-zero-contrast" class="level3">
<h3 class="anchored" data-anchor-id="from-a-benchmark-to-a-zero-contrast">From a benchmark to a zero contrast</h3>
<p>The driving question compares a population mean to the benchmark 15. As in the preparation exercise, subtract the benchmark and study the <strong>gap</strong></p>
<p><span class="math display">\[
G = X - 15,
\qquad
\delta = E[G] = \mu_X - 15.
\]</span></p>
<p>“Is the mean equity offered different from 15?” becomes “is <span class="math inline">\(\delta\)</span> different from zero?” A difference of this kind is called a <strong>contrast</strong>. Every benchmark question can be rewritten as a question about a contrast being zero. Lecture 10 tests a gap between proportions and a regression slope in this way, and names the difference between two groups as a further case.</p>
</section>
<section id="the-price-of-estimating-σ-the-t-distribution" class="level3">
<h3 class="anchored" data-anchor-id="the-price-of-estimating-σ-the-t-distribution">The price of estimating σ: the t distribution</h3>
<p>Lecture 8 gave the standardised sample mean</p>
<p><span class="math display">\[
Z=\frac{\bar X-\mu}{\sigma/\sqrt n},
\]</span></p>
<p>which is approximately standard normal by the central limit theorem (CLT). But this <span class="math inline">\(Z\)</span> contains the population SD <span class="math inline">\(\sigma\)</span>, and in a real study nobody knows <span class="math inline">\(\sigma\)</span>. In practice we replace it by the sample SD <span class="math inline">\(S\)</span>. But <span class="math inline">\(S\)</span> is itself random. It changes from sample to sample, and in a small sample it can be far from <span class="math inline">\(\sigma\)</span>. A mean that is standardised with an estimated spread therefore varies more than <span class="math inline">\(Z\)</span>. For independent observations from a normal population,</p>
<p><span class="math display">\[
T=\frac{\bar X-\mu}{S/\sqrt n}
\sim t_{n-1}.
\]</span></p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>t distribution and degrees of freedom.</strong> The t distribution describes a sample mean that is standardised with the sample SD <span class="math inline">\(S\)</span> in place of <span class="math inline">\(\sigma\)</span>. It is symmetric around zero and has heavier tails than the standard normal. Its shape depends on one number, the <strong>degrees of freedom</strong> (<span class="math inline">\(df\)</span>). For one sample mean, <span class="math inline">\(df=n-1\)</span>.</p>
</div>
<p>Heavier tails mean that values far from zero are more likely than under the standard normal. The reason is that <span class="math inline">\(S\)</span> sometimes underestimates the true spread. The degrees of freedom say how much heavier the tails are:</p>
<ul>
<li>few degrees of freedom mean that <span class="math inline">\(S\)</span> is an imprecise estimate of <span class="math inline">\(\sigma\)</span>, so the tails are heavier</li>
<li>more degrees of freedom mean more information about spread</li>
<li>as the degrees of freedom increase, the t distribution approaches the standard normal <span class="math inline">\(N(0,1)\)</span>.</li>
</ul>
<p>For one sample mean, <span class="math inline">\(df=n-1\)</span>. This is the same <span class="math inline">\(n-1\)</span> as in Lecture 7. Once the sample mean is estimated, the <span class="math inline">\(n\)</span> deviations must sum to zero, so only <span class="math inline">\(n-1\)</span> of them vary freely when spread is estimated.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>t_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">800</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>curve_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"t, df = 4"</span>, <span class="st">"t, df = 10"</span>, <span class="st">"standard normal"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>reference_curves <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">x =</span> t_grid, <span class="at">density =</span> <span class="fu">dt</span>(t_grid, <span class="at">df =</span> <span class="dv">4</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">curve =</span> curve_levels[<span class="dv">1</span>]),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">x =</span> t_grid, <span class="at">density =</span> <span class="fu">dt</span>(t_grid, <span class="at">df =</span> <span class="dv">10</span>),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">curve =</span> curve_levels[<span class="dv">2</span>]),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">x =</span> t_grid, <span class="at">density =</span> <span class="fu">dnorm</span>(t_grid),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">curve =</span> curve_levels[<span class="dv">3</span>])</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>reference_curves<span class="sc">$</span>curve <span class="ot">&lt;-</span> <span class="fu">factor</span>(reference_curves<span class="sc">$</span>curve,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">levels =</span> curve_levels)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>curve_colours <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"t, df = 4"</span> <span class="ot">=</span> <span class="st">"#D55E00"</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"t, df = 10"</span> <span class="ot">=</span> <span class="st">"#0072B2"</span>,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"standard normal"</span> <span class="ot">=</span> <span class="st">"#009E73"</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(reference_curves, <span class="fu">aes</span>(x, density,</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>                             <span class="at">colour =</span> curve, <span class="at">linetype =</span> curve)) <span class="sc">+</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">2.3</span>, <span class="at">y =</span> <span class="fl">0.375</span>, <span class="at">label =</span> <span class="st">"t, df = 4"</span>,</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">2.3</span>, <span class="at">y =</span> <span class="fl">0.335</span>, <span class="at">label =</span> <span class="st">"t, df = 10"</span>,</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#0072B2"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">2.3</span>, <span class="at">y =</span> <span class="fl">0.295</span>, <span class="at">label =</span> <span class="st">"standard normal"</span>,</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#009E73"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> curve_colours, <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"solid"</span>, <span class="st">"dashed"</span>, <span class="st">"dotted"</span>),</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>                        <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.41</span>),</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.02</span>))) <span class="sc">+</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Standardised value"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b09-t-curves" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b09-t-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b09-t-confidence-intervals_files/figure-html/fig-b09-t-curves-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b09-t-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: The t distribution for 4 and 10 degrees of freedom against the standard normal. All three are symmetric around zero. The t curves put more probability in the tails, most visibly at low degrees of freedom.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The difference in <a href="#fig-b09-t-curves" class="quarto-xref">Figure&nbsp;<span>12.1</span></a> is most visible in the tails. The central 95% of the standard normal lies between <span class="math inline">\(-1.96\)</span> and <span class="math inline">\(1.96\)</span> (Lecture 6). A t curve must reach further out to enclose its central 95%. The point where the central 95% ends is the 0.975 quantile of the t distribution. It is written <span class="math inline">\(t_{0.975,\,df}\)</span> and computed in R with <code>qt(0.975, df)</code>. This number is called the 95% <strong>critical value</strong>, or the multiplier. For small <span class="math inline">\(df\)</span> it is clearly larger than 1.96.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: which is larger, <span class="math inline">\(t_{0.975,11}\)</span> or <span class="math inline">\(t_{0.975,99}\)</span>?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(t_{0.975,11}\approx 2.20\)</span> is larger than <span class="math inline">\(t_{0.975,99}\approx 1.98\)</span>. With only 11 degrees of freedom, <span class="math inline">\(S\)</span> is an imprecise estimate of <span class="math inline">\(\sigma\)</span>, so the t distribution has heavier tails and its 97.5% quantile sits further from zero. At <span class="math inline">\(df=99\)</span> the critical value is already close to the normal 1.96. With a large sample, the t and normal answers are almost the same. Verify in R: <code>qt(0.975, df = 11)</code> and <code>qt(0.975, df = 99)</code>.</p>
</div>
</div>
</div>
</section>
<section id="the-interval-recipe" class="level3">
<h3 class="anchored" data-anchor-id="the-interval-recipe">The interval recipe</h3>
<p>A sample can be used in three ways. A point estimate gives one number for the parameter, such as the sample mean 12.76. An interval estimate gives a range of plausible values. A test answers a yes-or-no question about one value of the parameter. Lectures 7 and 8 gave point estimates. This lecture builds the interval estimate and prepares the test.</p>
<p>A confidence interval combines the estimate with its uncertainty. The general form is</p>
<p><span class="math display">\[
\text{estimate}
\ \pm\
\text{critical value}\times\text{standard error}.
\]</span></p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Confidence interval.</strong> A range of plausible values for a parameter, calculated from the sample as estimate <span class="math inline">\(\pm\)</span> critical value <span class="math inline">\(\times\)</span> standard error. A 95% confidence interval is built by a method that captures the parameter in about 95% of random samples.</p>
</div>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Margin of error.</strong> The part after the <span class="math inline">\(\pm\)</span> sign: critical value <span class="math inline">\(\times\)</span> standard error. It is half the width of the confidence interval.</p>
</div>
<p>A confidence interval becomes:</p>
<ul>
<li>wider when the confidence level increases (a larger critical value)</li>
<li>wider when observations are more variable (a larger SE)</li>
<li>narrower when the sample size increases, all else equal.</li>
</ul>
<p>For an independent sample from a normal population with unknown SD, or approximately for large <span class="math inline">\(n\)</span>,</p>
<p><span class="math display">\[
\bar X\pm t_{1-\alpha/2,\,n-1}\frac{S}{\sqrt n}
\]</span></p>
<p>is a <span class="math inline">\(100(1-\alpha)\%\)</span> confidence interval for <span class="math inline">\(\mu\)</span>. Here <span class="math inline">\(\alpha\)</span> is one minus the confidence level. A 95% interval has <span class="math inline">\(\alpha=0.05\)</span>, and the multiplier <span class="math inline">\(t_{0.975,\,n-1}\)</span> leaves <span class="math inline">\(\alpha/2=0.025\)</span> in each tail. The words “approximately for large <span class="math inline">\(n\)</span>” refer to the CLT: for a large independent sample the interval is a reasonable approximation even when the population is not normal. The same recipe applied to the gap variable <span class="math inline">\(G\)</span> gives an interval for <span class="math inline">\(\delta\)</span>.</p>
<p>The margin of error is the precision of the estimate at the stated confidence level. A smaller margin means a more precise estimate.</p>
<p>This also answers the prediction question from the preparation. Replacing <span class="math inline">\(\sigma\)</span> with <span class="math inline">\(S\)</span> makes the interval wider on average, because the t multiplier is larger than 1.96. The extra width is the price of estimating one more quantity from the same data.</p>
<p>In the exam, the multiplier you need is printed in the question or on the formula sheet. For a value of the degrees of freedom that is not on the sheet, use the closest one listed.</p>
<div id="exm-b09-hand-interval" class="theorem example">
<p><span class="theorem-title"><strong>Example 12.1 (Worked example: a 95% interval by hand)</strong></span> This is an invented example. A random sample of <span class="math inline">\(n=64\)</span> ventures reports a mean customer satisfaction score of <span class="math inline">\(\bar x = 80\)</span> points, with sample SD <span class="math inline">\(s = 16\)</span> points. The industry benchmark is 75 points. Construct a 95% confidence interval for <span class="math inline">\(\delta=\mu-75\)</span>, step by step.</p>
<ul>
<li><strong>Estimate.</strong> The estimated gap is the sample mean minus the benchmark: <span class="math inline">\(\widehat\delta = 80 - 75 = 5\)</span>.</li>
<li><strong>Standard error.</strong> <span class="math inline">\(\widehat{\operatorname{SE}}=s/\sqrt n = 16/\sqrt{64}\)</span>. The square root of 64 is 8, so <span class="math inline">\(\widehat{\operatorname{SE}}=16/8=2\)</span>.</li>
<li><strong>Degrees of freedom and critical value.</strong> <span class="math inline">\(df=n-1=63\)</span>, and <span class="math inline">\(t_{0.975,63}\approx 2.00\)</span>. In R it is <code>qt(0.975, df = 63)</code>, about 1.998. The closest value on the formula sheet is the one for <span class="math inline">\(df=60\)</span>, which is 2.000.</li>
<li><strong>Margin of error.</strong> Critical value times SE: <span class="math inline">\(2.00\times 2 = 4\)</span>.</li>
<li><strong>Interval.</strong> Estimate plus and minus the margin: <span class="math inline">\(5 - 4 = 1\)</span> and <span class="math inline">\(5 + 4 = 9\)</span>, so the 95% interval for <span class="math inline">\(\delta\)</span> is <span class="math inline">\((1,\,9)\)</span>.</li>
</ul>
<p>Every plausible value of the gap is positive. The data are consistent with a population mean between 1 and 9 points above the benchmark. Adding 75 back to both endpoints gives the equivalent interval <span class="math inline">\((76,\,84)\)</span> for <span class="math inline">\(\mu\)</span> itself. The gap form and the mean form are the same statement.</p>
</div>
</section>
<section id="check-conditions-before-calculating" class="level3">
<h3 class="anchored" data-anchor-id="check-conditions-before-calculating">Check conditions before calculating</h3>
<p>The formula is valid only when conditions on the sampling design and on the shape of the data hold. R does not check them for you. Before any interval or test, go through this checklist:</p>
<ol type="1">
<li><strong>Random selection.</strong> Were the rows selected randomly from a defined frame? In the Shark Tank case below they were: the sample of 100 is drawn at random (seed 123) from the 1,441 recorded pitches.</li>
<li><strong>The 10% condition.</strong> Sampling without replacement creates weak dependence, but <span class="math inline">\(100/1441\approx 0.07 &lt; 0.10\)</span>, so the usual independent-sample SE is a reasonable approximation.</li>
<li><strong>Shape and sample size.</strong> The equity offered (<code>equity_offered_pct</code>) is right-skewed. With <span class="math inline">\(n=100\)</span> the t approximation for the sample mean is still reasonable. For a very small sample it would not be. Also check for data errors and for single observations that dominate the mean.</li>
</ol>
<p>These conditions support conclusions about the recorded-pitch frame. They do not make televised pitches representative of all entrepreneurs. The caveat box at the end of this section returns to this point.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it: is the average order above break-even?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Try this with your neighbour first. This is an invented example. A venture needs an average order of 20 euros to break even. A random sample of <span class="math inline">\(n=36\)</span> orders has a mean of 21.50 euros and a standard deviation of 6 euros. Supplied value: <span class="math inline">\(t_{0.975,\,35}=2.030\)</span>.</p>
<p><em>Step 1 (given).</em> The estimated standard error is <span class="math inline">\(\widehat{\operatorname{SE}}=6/\sqrt{36}=1\)</span> euro.</p>
<p><em>Step 2 (you).</em> Calculate the margin of error and the 95% interval.</p>
<p><em>Step 3 (you).</em> Is 20 euros a plausible value for the mean order? What would you tell the founder?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The margin is <span class="math inline">\(2.030\times1=2.03\)</span> euros, so the interval runs from 19.47 to 23.53 euros. The break-even value of 20 euros lies inside the interval. The sample mean is above break-even, but the data cannot rule out that the true mean is below it. Advice: collect more orders before any decision that depends on being above break-even. With four times as many orders the margin would be about half as wide.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-shark-tank-case-step-by-step" class="level3">
<h3 class="anchored" data-anchor-id="the-shark-tank-case-step-by-step">The Shark Tank case, step by step</h3>
<p>Now apply the recipe to the Shark Tank data. The code draws the same random sample of 100 pitches as in Lecture 7 and builds every object step by step:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>sample_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>pitch_sample <span class="ot">&lt;-</span> sharks[sample_rows, ]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>benchmark <span class="ot">&lt;-</span> <span class="dv">15</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>pitch_sample<span class="sc">$</span>equity_gap_pp <span class="ot">&lt;-</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  pitch_sample<span class="sc">$</span>equity_offered_pct <span class="sc">-</span> benchmark</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>gap_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>equity_gap_pp)   <span class="co"># estimated gap</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>gap_sd  <span class="ot">&lt;-</span> <span class="fu">sd</span>(pitch_sample<span class="sc">$</span>equity_gap_pp)     <span class="co"># sample SD of the gap</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>n       <span class="ot">&lt;-</span> <span class="fu">nrow</span>(pitch_sample)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>df      <span class="ot">&lt;-</span> n <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>gap_se  <span class="ot">&lt;-</span> gap_sd <span class="sc">/</span> <span class="fu">sqrt</span>(n)                   <span class="co"># standard error</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_mean_equity =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_mean_gap =</span> gap_bar,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_sd_gap =</span> gap_sd,</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">standard_error_gap =</span> gap_se,</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">degrees_of_freedom =</span> df</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sample_mean_equity    sample_mean_gap      sample_sd_gap standard_error_gap 
        12.7600000         -2.2400000          7.7078866          0.7707887 
degrees_of_freedom 
        99.0000000 </code></pre>
</div>
</div>
<p>The estimated population mean gap is <span class="math inline">\(-2.24\)</span> percentage points. The sample mean of the equity offered, 12.76, lies 2.24 points below the benchmark of 15 points. That is about one seventh of the benchmark. Subtracting the constant 15 changes the mean but not the spread, as the shift rule of <a href="../basic/b03-discrete-distributions.html#b03-shift-rescale">Lecture 3</a> says. So <code>gap_sd</code> equals the sample SD of the equity offered itself, 7.71 points. The standard error is <span class="math inline">\(7.71/\sqrt{100}=0.77\)</span> points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>critical_t <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> df)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>gap_ci <span class="ot">&lt;-</span> gap_bar <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> critical_t <span class="sc">*</span> gap_se</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>mean_ci <span class="ot">&lt;-</span> benchmark <span class="sc">+</span> gap_ci</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">critical_t =</span> critical_t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>critical_t 
  1.984217 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">gap_lower =</span> gap_ci[<span class="dv">1</span>], <span class="at">gap_upper =</span> gap_ci[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> gap_lower  gap_upper 
-3.7694119 -0.7105881 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean_lower =</span> mean_ci[<span class="dv">1</span>], <span class="at">mean_upper =</span> mean_ci[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mean_lower mean_upper 
  11.23059   14.28941 </code></pre>
</div>
</div>
<p>The critical value is <span class="math inline">\(t_{0.975,\,99}=1.984\)</span>, so the margin of error is <span class="math inline">\(1.984\times0.77=1.53\)</span> percentage points. The 95% interval for the mean gap is approximately <span class="math inline">\((-3.77,\,-0.71)\)</span> percentage points. Adding 15 to both endpoints gives the equivalent interval <span class="math inline">\((11.23,\,14.29)\)</span> for the mean equity offered. The recipe is the same as in the worked example. Only the numbers differ.</p>
</section>
<section id="interpret-95-confidence-correctly" class="level3">
<h3 class="anchored" data-anchor-id="interpret-95-confidence-correctly">Interpret 95% confidence correctly</h3>
<p>The parameter is fixed. Interval endpoints vary from sample to sample. “95%” describes the <strong>procedure</strong>: if the same valid recipe were repeated on many random samples, about 95% of the resulting intervals would contain the parameter.</p>
<p>The simulation in <a href="#fig-b09-coverage" class="quarto-xref">Figure&nbsp;<span>12.2</span></a> repeats the random sample and the interval calculation 100 times. The fixed target is the mean equity offered (<code>equity_offered_pct</code>) among all 1,441 recorded pitches, 13.21 points.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">209</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>B_coverage <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>n_coverage <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>target_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>equity_offered_pct)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>ci_lower <span class="ot">&lt;-</span> ci_upper <span class="ot">&lt;-</span> ci_centre <span class="ot">&lt;-</span> <span class="fu">numeric</span>(B_coverage)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_len</span>(B_coverage)) {</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  repeated_sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    sharks<span class="sc">$</span>equity_offered_pct,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> n_coverage,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">replace =</span> <span class="cn">FALSE</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  repeated_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(repeated_sample)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  repeated_se <span class="ot">&lt;-</span> <span class="fu">sd</span>(repeated_sample) <span class="sc">/</span> <span class="fu">sqrt</span>(n_coverage)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>  repeated_critical <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n_coverage <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  ci_centre[i] <span class="ot">&lt;-</span> repeated_mean</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  ci_lower[i] <span class="ot">&lt;-</span> repeated_mean <span class="sc">-</span> repeated_critical <span class="sc">*</span> repeated_se</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>  ci_upper[i] <span class="ot">&lt;-</span> repeated_mean <span class="sc">+</span> repeated_critical <span class="sc">*</span> repeated_se</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>intervals <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> ci_lower, <span class="at">centre =</span> ci_centre, <span class="at">upper =</span> ci_upper,</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">covers =</span> <span class="fu">ifelse</span>(ci_lower <span class="sc">&lt;=</span> target_mean <span class="sc">&amp;</span> ci_upper <span class="sc">&gt;=</span> target_mean,</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"contains the target mean"</span>, <span class="st">"misses the target mean"</span>)</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>intervals <span class="ot">&lt;-</span> intervals[<span class="fu">order</span>(intervals<span class="sc">$</span>centre), ]</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>intervals<span class="sc">$</span>position <span class="ot">&lt;-</span> <span class="fu">seq_len</span>(B_coverage)</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(intervals, <span class="fu">aes</span>(<span class="at">y =</span> position, <span class="at">colour =</span> covers)) <span class="sc">+</span></span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> lower, <span class="at">xend =</span> upper, <span class="at">yend =</span> position),</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>               <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> centre), <span class="at">size =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> target_mean, <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"#C98B2E"</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> target_mean, <span class="at">y =</span> B_coverage <span class="sc">+</span> <span class="fl">3.5</span>,</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"mu == 13.21"</span>, <span class="at">parse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"contains the target mean"</span> <span class="ot">=</span> <span class="st">"#009E73"</span>,</span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"misses the target mean"</span> <span class="ot">=</span> <span class="st">"#D55E00"</span>)) <span class="sc">+</span></span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">20</span>, <span class="dv">40</span>, <span class="dv">60</span>, <span class="dv">80</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mean equity offered (%)"</span>,</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Repeated sample (ordered by estimate)"</span>,</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>       <span class="at">colour =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>),</span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"top"</span></span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b09-coverage" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b09-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b09-t-confidence-intervals_files/figure-html/fig-b09-coverage-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b09-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.2: One hundred repetitions of the same procedure: draw 100 random pitches, compute a 95% t interval for the mean equity offered. Green intervals contain the fixed target mean (gold dashed line). Orange intervals miss it. In this run, 96 of 100 intervals cover the target.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each horizontal segment in <a href="#fig-b09-coverage" class="quarto-xref">Figure&nbsp;<span>12.2</span></a> is one 95% confidence interval. Its dot is that sample’s mean. The gold dashed vertical line is the fixed target mean, 13.21. In this run (seed 209), <strong>96 of 100</strong> intervals cross the line. A new run need not give exactly 95, but across many repetitions the proportion approaches 95% when the procedure’s conditions hold.</p>
<p>The following sentence may look natural, but it is wrong:</p>
<blockquote class="blockquote">
<p>“There is a 95% probability that the population mean is in my interval.”</p>
</blockquote>
<p>Before the sample is drawn, the endpoints of the interval are random, and the 95% applies to them. After the sample is drawn, the interval <span class="math inline">\((11.23, 14.29)\)</span> consists of two fixed numbers. It either contains the fixed parameter or it does not, and no probability is left. The correct sentence is:</p>
<blockquote class="blockquote">
<p>“This interval was produced by a procedure that captures the fixed population mean in about 95% of repeated valid samples.”</p>
</blockquote>
</section>
<section id="from-interval-to-test-the-hypotheses-and-the-t-statistic" class="level3">
<h3 class="anchored" data-anchor-id="from-interval-to-test-the-hypotheses-and-the-t-statistic">From interval to test: the hypotheses and the t statistic</h3>
<p>The interval shows every plausible value. A <strong>test</strong> answers one question about one value: is the gap zero? A test starts from two hypotheses:</p>
<p><span class="math display">\[
H_0:\delta=0
\qquad\text{versus}\qquad
H_1:\delta\ne0.
\]</span></p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Null hypothesis and alternative hypothesis.</strong> The null hypothesis <span class="math inline">\(H_0\)</span> states that the parameter equals the benchmark value, here <span class="math inline">\(\delta=0\)</span>. The alternative hypothesis <span class="math inline">\(H_1\)</span> states that it does not. A two-sided alternative, <span class="math inline">\(\delta\ne0\)</span>, allows a difference in either direction.</p>
</div>
<p>Here the null hypothesis says that the population mean of the equity offered does not differ from the benchmark. State both hypotheses from the research question before you look at the sample estimate. Alternatives that allow only one direction (one-sided alternatives) also exist. They are optional reading in Lecture 10 and are not examined.</p>
<p>The <strong>t statistic</strong> standardises the estimated gap with its SE. Its general form is the estimate minus the null value, divided by the standard error:</p>
<p><span class="math display">\[
T=
\frac{\widehat\delta-0}
{\widehat{\operatorname{SE}}(\widehat\delta)}
=
\frac{\bar G}{S_G/\sqrt n}.
\]</span></p>
<p>First by hand, with the numbers calculated above. The estimate is <span class="math inline">\(-2.24\)</span> and its SE is <span class="math inline">\(0.77\)</span>, so</p>
<p><span class="math display">\[
t=\frac{-2.24}{0.77}\approx -2.91.
\]</span></p>
<p>The sign gives the direction: the estimate is below the benchmark. The absolute value gives the distance from zero in standard-error units, here almost three SEs. Now the same calculation in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>t_value <span class="ot">&lt;-</span> gap_bar <span class="sc">/</span> gap_se</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimate =</span> gap_bar,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">standard_error =</span> gap_se,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">t_statistic =</span> t_value,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">degrees_of_freedom =</span> df</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          estimate     standard_error        t_statistic degrees_of_freedom 
        -2.2400000          0.7707887         -2.9061144         99.0000000 </code></pre>
</div>
</div>
<p>A t statistic of <span class="math inline">\(-2.91\)</span> says that the estimate lies almost three standard errors below zero. Lecture 10 measures how surprising such a value would be if the null hypothesis were true. That measure is called the p-value.</p>
<div class="caveat-box">
<p><span class="label">What an interval can and cannot tell you</span></p>
<ul>
<li>Precision is not importance. An interval that excludes 15 says the gap is measured well, not that 2.24 points matter for a decision.</li>
<li>An interval is not a claim about cause. Nothing here says why offers sit below 15 points.</li>
<li>A narrow interval repairs nothing about selection. It describes the recorded pitches, not founders in general.</li>
</ul>
<p><strong>What you can do with it:</strong> read both ends of the interval as possible truths, and ask whether your decision would be the same at each end.</p>
</div>
</section>
<section id="answering-the-driving-question" class="level3">
<h3 class="anchored" data-anchor-id="answering-the-driving-question">Answering the driving question</h3>
<p>For the recorded-pitch frame, the evidence points to yes. The random sample of 100 pitches gives an estimated gap of <span class="math inline">\(-2.24\)</span> percentage points with SE <span class="math inline">\(0.77\)</span>. The 95% interval for the mean equity offered is <span class="math inline">\((11.23, 14.29)\)</span>, which excludes 15. The t statistic of <span class="math inline">\(-2.91\)</span> puts the estimate almost three standard errors below the benchmark. Lecture 10 turns that distance into a p-value and a formal decision. Whether the gap matters commercially, and what caused it, are separate questions that no interval can answer.</p>
<div class="founder-box">
<p><span class="label">A founder’s decision (invented example)</span></p>
<p>From 25 orders, the average order value is 9.60 euros with a standard deviation of 2 euros. You need 9 euros per order to break even on a kitchen lease. The 95% interval is 9.60 ± 2.064 × 0.40, from 8.77 to 10.43 euros. The break-even value of 9 euros lies inside the interval. The decision: do not sign yet. With 100 orders the standard error falls to 0.20. If the mean stays at 9.60, the interval then runs from 9.20 to 10.00 and excludes 9. You collect orders for three more weeks and decide then.</p>
</div>
<p><strong>Next:</strong> We can now report an estimate with an interval, and we have measured how far the estimate lies from a benchmark in standard-error units. Lecture 10 turns that distance into a p-value and a decision. It names the two ways a decision can be wrong and shows what makes wrong decisions rarer. It ends with a first look at a regression table, which reports the same five items: estimate, SE, t, p-value, and interval.</p>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p><span class="time-budget">Total practice time: about 70 minutes.</span></p>
<p><strong>Minimum path (about 35 minutes):</strong> read the lecture material, answer the recall questions, then work for 10 minutes on the tasks that follow. <strong>Full path:</strong> all tasks below.</p>
<section id="read-the-lecture-material-15-minutes" class="level3">
<h3 class="anchored" data-anchor-id="read-the-lecture-material-15-minutes">Read the lecture material (15 minutes)</h3>
<p>Read the Lecture material section above from start to end. The lecture covered the core of it. The text has every step, every example, and all the code, including parts that were not shown in class. Note what is still unclear and bring it to the next tutorial, or ask Tilly.</p>
</section>
<section id="recall-questions-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="recall-questions-10-minutes">Recall questions (10 minutes)</h3>
<ol type="1">
<li>Why does replacing <span class="math inline">\(\sigma\)</span> with the sample SD <span class="math inline">\(S\)</span> require a t rather than a normal reference distribution?</li>
<li>Why does a one-sample t procedure use <span class="math inline">\(n-1\)</span> degrees of freedom?</li>
<li>What are the three pieces of a confidence interval?</li>
<li>What do <span class="math inline">\(H_0:\delta=0\)</span> and <span class="math inline">\(H_1:\delta\ne0\)</span> say?</li>
<li>What does a t statistic of <span class="math inline">\(-2.91\)</span> tell you?</li>
<li>What is “95%” a property of: the interval you computed or the procedure?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(S\)</span> is itself estimated and varies from sample to sample. The t distribution’s heavier tails represent that extra uncertainty.</li>
<li>Estimating the sample mean imposes one constraint (deviations sum to zero) before spread is estimated, leaving <span class="math inline">\(n-1\)</span> freely varying deviations.</li>
<li>Estimate, critical value, and standard error.</li>
<li>The null hypothesis states that the population gap <span class="math inline">\(\delta\)</span> is zero. The alternative allows a non-zero gap in either direction.</li>
<li>The estimate lies 2.91 standard errors below the null value of zero.</li>
<li>The procedure: about 95% of intervals built this way from repeated valid samples contain the fixed parameter.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="finish-a-half-worked-example-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="finish-a-half-worked-example-10-minutes">Finish a half-worked example (10 minutes)</h3>
<p>Re-read the hand-worked interval (<a href="#exm-b09-hand-interval" class="quarto-xref">Example&nbsp;<span>12.1</span></a>). Then complete the same calculation with new invented numbers: a random sample of <span class="math inline">\(n=25\)</span> customers, mean satisfaction <span class="math inline">\(\bar x = 42\)</span> points, sample SD <span class="math inline">\(s = 10\)</span> points, benchmark 40 points, so <span class="math inline">\(\delta=\mu-40\)</span>.</p>
<p><em>Step 1 (given).</em> The estimated gap is <span class="math inline">\(42-40=2\)</span>, and <span class="math inline">\(t_{0.975,24}=2.064\)</span>.</p>
<p><em>Step 2 (you).</em> Calculate the SE and the margin of error.</p>
<p><em>Step 3 (you).</em> Write the 95% interval for <span class="math inline">\(\delta\)</span> and say whether a gap of zero is among the plausible values.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\widehat{\operatorname{SE}}=10/\sqrt{25}=2\)</span>. The margin of error is <span class="math inline">\(2.064\times 2=4.13\)</span>. The interval is <span class="math inline">\(2\pm 4.13=(-2.13,\,6.13)\)</span>. Zero lies inside, so a zero gap is among the plausible values, and so are gaps up to about 6 points. The t statistic is <span class="math inline">\(2/2=1.00\)</span>. The estimate lies one standard error from zero.</p>
</div>
</div>
</div>
</section>
<section id="practice-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="practice-10-minutes">Practice (10 minutes)</h3>
<p>The numbers in tasks 1 to 3 are invented.</p>
<ol type="1">
<li>A random sample has <span class="math inline">\(n=49\)</span>, <span class="math inline">\(\bar x=110\)</span>, and <span class="math inline">\(s=14\)</span>. Define <span class="math inline">\(\delta=\mu-100\)</span>. Construct a 95% interval for <span class="math inline">\(\delta\)</span> (use <span class="math inline">\(t_{0.975,48}\approx 2.01\)</span>).</li>
<li>For the sample of task 1, state <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span> for a two-sided test of a zero gap. Calculate the t statistic and its degrees of freedom.</li>
<li>An estimate is 0.42 percentage points per €100,000, with SE 0.18 and <span class="math inline">\(df=120\)</span>. Calculate the t statistic and construct a 95% interval (use <span class="math inline">\(t_{0.975,120}\approx 1.98\)</span>).</li>
<li>Explain why an interval that excludes zero does not show that a gap is important in practice, or that it has a particular cause.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The estimated gap is <span class="math inline">\(110-100=10\)</span>, its SE is <span class="math inline">\(14/\sqrt{49}=2\)</span>, and the interval is <span class="math inline">\(10\pm 2.01(2)=(5.98,\,14.02)\)</span>.</li>
<li><span class="math inline">\(H_0:\delta=0\)</span> against <span class="math inline">\(H_1:\delta\ne0\)</span>. The t statistic is <span class="math inline">\(t=10/2=5.00\)</span> with <span class="math inline">\(df=48\)</span>, so the estimate lies five standard errors above zero. The interval from task 1 lies entirely above zero. Plausible gaps run from about 6 to 14 points.</li>
<li><span class="math inline">\(t=0.42/0.18\approx 2.33\)</span>. The 95% interval is <span class="math inline">\(0.42\pm1.98(0.18)=(0.064,\,0.776)\)</span> percentage points per €100,000, which excludes zero.</li>
<li>An interval that excludes zero says that the estimate is precise enough to tell the gap from zero. Whether the gap is important depends on its size and on the decision. A causal claim needs a suitable study design. A narrow interval gives neither.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="rewrite-the-wrong-sentence-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="rewrite-the-wrong-sentence-5-minutes">Rewrite the wrong sentence (5 minutes)</h3>
<p>Rewrite this claim correctly: “There is a 95% chance that the population mean is in my interval <span class="math inline">\((11.23, 14.29)\)</span>.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>“The interval <span class="math inline">\((11.23, 14.29)\)</span> was produced by a procedure that captures the fixed population mean in about 95% of repeated valid samples.” The parameter is fixed. It is the interval endpoints that vary across samples, as in <a href="#fig-b09-coverage" class="quarto-xref">Figure&nbsp;<span>12.2</span></a>.</p>
</div>
</div>
</div>
</section>
<section id="review-one-question-each-from-lectures-8-and-4-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="review-one-question-each-from-lectures-8-and-4-10-minutes">Review: one question each from Lectures 8 and 4 (10 minutes)</h3>
<ol type="1">
<li><em>(Lecture 8.)</em> A planned survey expects a sample SD around 24 with <span class="math inline">\(n=64\)</span>. Estimate the SE of the sample mean, and state what happens to it if <span class="math inline">\(n\)</span> grows to 256.</li>
<li><em>(Lecture 4.)</em> From the 2×2 counts table, <span class="math inline">\(P(D\mid L)=505/734\approx 0.688\)</span> while <span class="math inline">\(P(L\mid D)=505/882\approx 0.573\)</span>. Why are these two numbers different even though both involve the same 505 records?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(\widehat{\operatorname{SE}}=24/\sqrt{64}=3\)</span>. Four times the sample size halves the SE to 1.5. This is the square-root rule.</li>
<li>They condition on different events. The first divides the 505 joint records by the 734 late-season records. The second divides the same 505 by the 882 deal records. Changing the event after the bar changes the denominator.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="check-the-ai-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="check-the-ai-5-minutes">Check the AI (5 minutes)</h3>
<p>You asked an AI assistant: “What does the 95% interval from 11.23 to 14.29 for the mean equity offered mean?” It answered:</p>
<blockquote class="blockquote">
<p>“It means that 95% of all pitches offer between 11.23% and 14.29% of the company.”</p>
</blockquote>
<p>Find what is wrong and write the corrected answer. This is the <strong>Verify</strong> step of Attempt → Ask → Verify → Explain, and the exam asks for it.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The interval is about the mean, not about single pitches. In the Shark Tank file, the equity offered (<code>equity_offered_pct</code>) in single pitches ranges from 1% to 100%. The correct reading: the interval was produced by a procedure that captures the mean equity offered in all recorded pitches in about 95% of samples.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Utility: two sentences</span></p>
<p>Think of your EiA venture, or any business you know well. Pick one key metric with a published industry benchmark (conversion rate, average order value, churn), frame the comparison as a gap <span class="math inline">\(\delta = \mu - \text{benchmark}\)</span>, and write two sentences: first say what sample you could realistically collect and what a 95% interval for <span class="math inline">\(\delta\)</span> excluding zero would let you claim, then say what decision would change if the interval turned out to include zero.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run campus meal-prep box venture. “The sector churn benchmark is 25% per term. From my roughly 120 subscribers I can estimate <span class="math inline">\(\delta = \mu - 25\)</span>, and a 95% interval sitting entirely below zero would let me claim genuinely stickier customers in my pitch. If the interval included zero, I would stop pitching retention as my edge and lead with margin instead.”</p>
</div>
</div>
</div>
<p>You can discuss this task, and any other task in this chapter, with <strong>Tilly</strong>, the course AI assistant: ask it to check whether your gap is defined on a population you can actually sample.</p>
</div>
<p><a href="../basic/b10-testing-errors-power.html">Continue to Lecture 10: Testing decisions, errors, power, and the road to regression</a>.</p>
<p><a href="../basic/formula-sheet.html#formula-l9">Formula sheet: Lecture 9 formulas</a>.</p>
<p>For a more formal explanation, consult <a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>, Chapters 15 and 16.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/t03-exam-prep.html" class="pagination-link" aria-label="Tutorial 3: Normal models, sampling, and standard errors">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/b10-testing-errors-power.html" class="pagination-link" aria-label="Lecture 10: Testing decisions, errors, power, and the road to regression">
        <span class="nav-page-text"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>