<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 10: Testing decisions, errors, power, and the road to regression – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/t04-exam-prep.html" rel="next">
<link href="../basic/b09-t-confidence-intervals.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ecf4e518a83458a2bb67b2a9bf74271b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b10-testing-errors-power.html"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution, confidence intervals, and the two-sided test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Inference and tests against zero</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals betray it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/reading-ladder.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reading research papers</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-class" id="toc-in-class" class="nav-link" data-scroll-target="#in-class">In class</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/b10-testing-errors-power.html"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b10" class="quarto-section-identifier"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Lecture 10, you can</span></p>
<ul>
<li>rewrite benchmark and comparison questions as tests of a zero contrast;</li>
<li>complete and communicate a two-sided test using the seven-step workflow;</li>
<li>distinguish a p-value, a significance level, and a test decision;</li>
<li>describe Type I error, Type II error, and power in context;</li>
<li>explain when a one-sided alternative is legitimate and why this course’s exams are two-sided;</li>
<li>separate statistical significance from magnitude, practical importance, and causality;</li>
<li>interpret the zero-null test printed for a regression coefficient.</li>
</ul>
</div>
<div class="driving-question">
<p><span class="label">Driving question</span></p>
<p class="dq-context">
Launch the product or wait. Approve the loan or decline. Decisions made from data can err in two directions, and the two mistakes usually cost very different amounts.
</p>
<p>Every test can be wrong in two ways. Which wrong call is which, what makes wrong calls rarer, and how does all of this reappear in a regression table?</p>
</div>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p><span class="time-budget">Total preparation time: about 25 minutes.</span></p>
<div class="video-prep">
<p><span class="label">Video preparation (15 minutes)</span><br> Review <a href="https://www.youtube.com/watch?v=ti9NFdjf3sM">Introduction to Hypothesis Testing</a> and watch <a href="https://www.youtube.com/watch?v=JNOWWJeZBTc">Examples Identifying Type I and Type II Errors</a>. Focus on two-sided tests, decision errors, and why “do not reject” is not “accept.” All links are also listed in the <a href="../resources/video-guide.html">External Video Guide</a>.</p>
</div>
<p><strong>Reactivate (8 minutes).</strong> Suppose R reports the following coefficient row:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-0.290</td>
<td style="text-align: right;">0.058</td>
<td style="text-align: right;">-5.00</td>
<td style="text-align: right;">&lt; 0.001</td>
</tr>
</tbody>
</table>
<p>State the hypotheses being tested and give a careful one-sentence statistical conclusion.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your preparation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The default two-sided coefficient test is <span class="math inline">\(H_0:\beta=0\)</span> against <span class="math inline">\(H_1:\beta\ne0\)</span>. Because the p-value is below 0.05, reject <span class="math inline">\(H_0\)</span>: the data provide evidence that the population-model coefficient differs from zero. A full interpretation still needs the outcome, predictor, units, held-fixed variables, population, and causal limit.</p>
</div>
</div>
</div>
<p><strong>Predict (2 minutes).</strong> Answer the one-click Mentimeter question posted on Canvas before you come to class: a test at <span class="math inline">\(\alpha=0.05\)</span> returns <span class="math inline">\(p=0.20\)</span>. Has the study <strong>shown that the null is true</strong> — yes, no, or cannot tell? Commit to an answer; the lecture resolves it.</p>
<p>Review <a href="../resources/math-refresher.html">Mathematics Refresher: zero contrasts, inequalities, and standardisation</a> if needed.</p>
</section>
<section id="in-class" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-class">In class</h2>
<p>The session opens with the usual four-minute entry quiz on the prep videos, then turns to the driving question. Lecture 9 delivered one complete test. This final lecture makes testing a <em>routine</em>: one recipe, an honest account of the two ways any decision can be wrong, and the payoff — the same machinery reappearing, unchanged, in every regression table you will read from Intermediate onwards.</p>
<p class="concept-video">
<strong>Video explanations (review):</strong> <a href="https://www.youtube.com/watch?v=ti9NFdjf3sM">Introduction to Hypothesis Testing</a> and <a href="https://www.youtube.com/watch?v=JNOWWJeZBTc">Type I and Type II Errors</a>.
</p>
<section id="why-zero-is-the-universal-benchmark" class="level3">
<h3 class="anchored" data-anchor-id="why-zero-is-the-universal-benchmark">Why zero is the universal benchmark</h3>
<p>Many empirical questions ask whether a population contrast is absent:</p>
<ul>
<li>difference from a target: <span class="math inline">\(\delta=\mu-15\)</span>;</li>
<li>difference in probabilities: <span class="math inline">\(\delta_p=p-0.50\)</span>;</li>
<li>difference between two group means: <span class="math inline">\(\mu_1-\mu_0\)</span>;</li>
<li>a regression slope: <span class="math inline">\(\beta_j\)</span>.</li>
</ul>
<p>In every case, “no difference” or “no linear association” becomes</p>
<p><span class="math display">\[
H_0:\theta=0
\qquad\text{versus}\qquad
H_1:\theta\ne0.
\]</span></p>
<p>Testing a non-zero benchmark can always be rewritten as a test of a zero-valued contrast — Lecture 9’s gap device. This common structure is the bridge from Basic inference to regression inference: learn to test one zero, and you can test them all.</p>
</section>
<section id="the-seven-step-testing-workflow" class="level3">
<h3 class="anchored" data-anchor-id="the-seven-step-testing-workflow">The seven-step testing workflow</h3>
<p>Use the same sequence every time — on the exam, in your EiA venture, in any report you ever write:</p>
<ol type="1">
<li>Define the population parameter and its units.</li>
<li>State <span class="math inline">\(H_0\)</span> and the two-sided <span class="math inline">\(H_1\)</span> <strong>before</strong> inspecting the result.</li>
<li>Check the sampling and model conditions.</li>
<li>Calculate the estimate and its SE under the null model.</li>
<li>Standardise: <span class="math inline">\((\text{estimate}-0)/\text{SE}\)</span>.</li>
<li>Calculate the two-sided p-value and compare it with the pre-specified significance level <span class="math inline">\(\alpha\)</span>.</li>
<li>Report the estimate, uncertainty, decision, contextual meaning, and limits.</li>
</ol>
<p>The significance level <span class="math inline">\(\alpha\)</span> is a long-run decision threshold, commonly 0.05, fixed in advance. The p-value is calculated from the observed data under <span class="math inline">\(H_0\)</span>. They are not the same object: one is a rule, the other a result.</p>
<p>If <span class="math inline">\(p\le\alpha\)</span>, reject <span class="math inline">\(H_0\)</span>. If <span class="math inline">\(p&gt;\alpha\)</span>, <strong>do not reject</strong> <span class="math inline">\(H_0\)</span> — and do not say “accept <span class="math inline">\(H_0\)</span>.” This resolves the prep prediction: a study with <span class="math inline">\(p=0.20\)</span> has <em>not</em> shown the null is true; it may simply lack the precision to distinguish a meaningful non-zero parameter from zero. The power section below makes that precise.</p>
<div id="exm-b10-launch-test" class="theorem example">
<p><span class="theorem-title"><strong>Example 13.1 (Worked example: a proportion test by hand)</strong></span> An accelerator claims that half of its alumni launch a trading venture within a year. In a random sample of 400 former participants, 232 had launched. Let <span class="math inline">\(p\)</span> be the launch proportion in the alumni frame and define <span class="math inline">\(\delta_p=p-0.50\)</span>. Test <span class="math inline">\(H_0:\delta_p=0\)</span> against <span class="math inline">\(H_1:\delta_p\ne0\)</span> at 5%, voicing every arithmetic step.</p>
<ul>
<li><strong>Estimate.</strong> <span class="math inline">\(\hat p=232/400=0.58\)</span>, so the estimated gap is <span class="math inline">\(\widehat\delta_p=0.58-0.50=0.08\)</span>, eight percentage points.</li>
<li><strong>Conditions under the null.</strong> <span class="math inline">\(np_0=400(0.50)=200\)</span> and <span class="math inline">\(n(1-p_0)=200\)</span>, both far above 10 — the normal approximation is safe.</li>
<li><strong>Null SE.</strong> Under <span class="math inline">\(H_0\)</span> the true proportion is 0.50, so <span class="math inline">\(\operatorname{SE}_0=\sqrt{0.50(0.50)/400}=\sqrt{0.25/400}
=\sqrt{0.000625}=0.025\)</span>.</li>
<li><strong>Standardise.</strong> <span class="math inline">\(z=0.08/0.025=3.20\)</span>: the observed gap sits 3.2 null standard errors above zero.</li>
<li><strong>p-value and decision.</strong> The two-sided p-value is <span class="math inline">\(2\,P(Z\le-3.20)\approx 0.0014 &lt; 0.05\)</span>: reject <span class="math inline">\(H_0\)</span>. The sample provides strong evidence that the frame launch proportion differs from 50%; the positive estimate places it above.</li>
</ul>
<p>Note step 4’s subtlety: the SE was computed with <span class="math inline">\(p_0=0.50\)</span>, not with <span class="math inline">\(\hat p\)</span> — the test measures how surprising the sample is <em>in the null’s world</em>, so the null supplies the spread.</p>
</div>
</section>
<section id="the-shark-tank-deal-proportion-in-r" class="level3">
<h3 class="anchored" data-anchor-id="the-shark-tank-deal-proportion-in-r">The Shark Tank deal proportion, in R</h3>
<p>The same recipe on our reproducible sample of 100: is the frame’s deal proportion different from 50%? Every object is constructed on screen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>sample_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>pitch_sample <span class="ot">&lt;-</span> sharks[sample_rows, ]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(pitch_sample)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>phat <span class="ot">&lt;-</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>deal_on_show)   <span class="co"># sample deal proportion</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">&lt;-</span> <span class="fl">0.50</span>                                <span class="co"># null value</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>deal_gap <span class="ot">&lt;-</span> phat <span class="sc">-</span> p0                     <span class="co"># estimated gap</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">n =</span> n, <span class="at">phat =</span> phat, <span class="at">p0 =</span> p0, <span class="at">deal_gap =</span> deal_gap)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       n     phat       p0 deal_gap 
  100.00     0.64     0.50     0.14 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>null_se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(p0 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p0) <span class="sc">/</span> n)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>z_value <span class="ot">&lt;-</span> deal_gap <span class="sc">/</span> null_se</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>two_sided_p <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fu">abs</span>(z_value))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">null_standard_error =</span> null_se,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">z_statistic =</span> z_value,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">two_sided_p_value =</span> two_sided_p</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>null_standard_error         z_statistic   two_sided_p_value 
        0.050000000         2.800000000         0.005110261 </code></pre>
</div>
</div>
<p>The estimate is <span class="math inline">\(\widehat\delta_p=0.14\)</span>, fourteen percentage points. The null SE is <span class="math inline">\(\sqrt{0.50(0.50)/100}=0.05\)</span>, the statistic is <span class="math inline">\(z=2.80\)</span>, and the two-sided p-value is about 0.005. The success–failure condition holds under the null: <span class="math inline">\(np_0=50\)</span> and <span class="math inline">\(n(1-p_0)=50\)</span>. Reject the zero-gap null at 5%: the random sample provides evidence that the recorded-pitch-frame deal proportion differs from 50%, and the positive estimate places it above.</p>
</section>
<section id="interval-and-test-report-both" class="level3">
<h3 class="anchored" data-anchor-id="interval-and-test-report-both">Interval and test: report both</h3>
<p>Step 7 of the workflow says a decision alone is not a report. A large-sample 95% interval for the proportion uses the estimated SE:</p>
<p><span class="math display">\[
\hat p\pm1.96
\sqrt{\frac{\hat p(1-\hat p)}{n}}.
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>estimated_se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(phat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> phat) <span class="sc">/</span> n)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>proportion_ci <span class="ot">&lt;-</span> phat <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> <span class="fl">1.96</span> <span class="sc">*</span> estimated_se</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>gap_ci <span class="ot">&lt;-</span> proportion_ci <span class="sc">-</span> p0</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">proportion_lower =</span> proportion_ci[<span class="dv">1</span>],</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">proportion_upper =</span> proportion_ci[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>proportion_lower proportion_upper 
         0.54592          0.73408 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">gap_lower =</span> gap_ci[<span class="dv">1</span>], <span class="at">gap_upper =</span> gap_ci[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>gap_lower gap_upper 
  0.04592   0.23408 </code></pre>
</div>
</div>
<p>The proportion interval is approximately <span class="math inline">\((0.546,\,0.734)\)</span>; the equivalent gap interval is <span class="math inline">\((0.046,\,0.234)\)</span>, which excludes zero and agrees with the test decision here.</p>
<div class="optional-box">
<p><span class="label">Optional: estimated versus null standard errors</span><br> Look closely: the test divided by the <strong>null</strong> SE <span class="math inline">\(\sqrt{p_0(1-p_0)/n}=0.050\)</span>, while the interval used the <strong>estimated</strong> SE <span class="math inline">\(\sqrt{\hat p(1-\hat p)/n}=0.048\)</span>. The test asks how surprising the sample is if <span class="math inline">\(H_0\)</span> were true, so the null supplies the spread; the interval makes no null assumption, so the data supply it. Because these are not exactly the same procedure, interval and test decisions need not match perfectly when a result sits very near the boundary. Exact equivalence requires an interval obtained by inverting the same test — beyond this course. For the mean-gap t procedures of Lecture 9 the same SE is used in both, so there the match is exact.</p>
</div>
</section>
<section id="what-a-p-value-is-not" class="level3">
<h3 class="anchored" data-anchor-id="what-a-p-value-is-not">What a p-value is not</h3>
<p>The two-sided p-value is</p>
<p><span class="math display">\[
P\!\left(|\text{test statistic}|
\ge|\text{observed statistic}|\mid H_0\right)
\]</span></p>
<p>— and nothing else. Before the break you receive four sentences about the launch test of <a href="#exm-b10-launch-test" class="quarto-xref">Example&nbsp;<span>13.1</span></a> (<span class="math inline">\(z=3.20\)</span>, <span class="math inline">\(p\approx 0.0014\)</span>). Each one is wrong. In pairs, correct all four; the plenary compares repairs.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it: correct the four wrong p-value sentences
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><em>Sentence 1 (you).</em> “There is only a 0.14% probability that the launch proportion really is 50%.”</p>
<p><em>Sentence 2 (you).</em> “The result has a 0.14% probability of being due to chance.”</p>
<p><em>Sentence 3 (you).</em> “Such a tiny p-value shows that the launch proportion is far above 50%.”</p>
<p><em>Sentence 4 (you).</em> “The tiny p-value proves that the accelerator causes its alumni to launch ventures.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>A p-value is not <span class="math inline">\(P(H_0\mid\text{data})\)</span>. Correct: “If the launch proportion were exactly 50%, a sample gap at least this far from zero in either direction would occur in about 0.14% of random samples.”</li>
<li>The p-value is computed <em>assuming</em> chance alone (the null model) generated the gap; it is the probability of data this extreme under that assumption, not the probability that the assumption holds.</li>
<li>A p-value measures surprise, not size. The magnitude is the estimate: 8 percentage points, with an interval around it. A tiny p-value can accompany a tiny gap when <span class="math inline">\(n\)</span> is huge.</li>
<li>Significance says nothing about why. Alumni self-selected into the accelerator; without a design that isolates its effect, “causes” is unsupported. Correct: the frame’s launch proportion differs from 50%.</li>
</ol>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="type-i-error-type-ii-error-and-power" class="level3">
<h3 class="anchored" data-anchor-id="type-i-error-type-ii-error-and-power">Type I error, Type II error, and power</h3>
<p>A test is a decision rule, and any decision rule can be wrong in exactly two ways:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Reality</th>
<th>Reject <span class="math inline">\(H_0\)</span></th>
<th>Do not reject <span class="math inline">\(H_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_0\)</span> true</td>
<td>Type I error</td>
<td>Correct decision</td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_1\)</span> true</td>
<td>Correct decision</td>
<td>Type II error</td>
</tr>
</tbody>
</table>
<p>The significance level controls the first:</p>
<p><span class="math display">\[
P(\text{reject }H_0\mid H_0\text{ true})=\alpha.
\]</span></p>
<p><strong>Power</strong> is the ability to avoid the second:</p>
<p><span class="math display">\[
\text{power}=P(\text{reject }H_0\mid H_1\text{ true}).
\]</span></p>
<p>For the launch test, in context: a <strong>Type I error</strong> would be concluding that the alumni launch proportion differs from 50% when it is exactly 50% — crying wolf about a fictitious difference, embarrassing the analyst who advises repricing the programme. A <strong>Type II error</strong> would be failing to detect a launch proportion that genuinely differs from 50% — missing a real signal because the sample was too small or noisy.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>z_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">4.5</span>, <span class="fl">6.5</span>, <span class="at">length.out =</span> <span class="dv">1600</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>critical <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>panel_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Null is true"</span>, <span class="st">"An alternative value is true"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>test_curves <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">z =</span> z_grid, <span class="at">density =</span> <span class="fu">dnorm</span>(z_grid, <span class="at">mean =</span> <span class="dv">0</span>),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">panel =</span> panel_levels[<span class="dv">1</span>]),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">z =</span> z_grid, <span class="at">density =</span> <span class="fu">dnorm</span>(z_grid, <span class="at">mean =</span> <span class="fl">2.5</span>),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">panel =</span> panel_levels[<span class="dv">2</span>])</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>test_curves<span class="sc">$</span>panel <span class="ot">&lt;-</span> <span class="fu">factor</span>(test_curves<span class="sc">$</span>panel, <span class="at">levels =</span> panel_levels)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>rejection <span class="ot">&lt;-</span> <span class="fu">subset</span>(test_curves, z <span class="sc">&lt;=</span> <span class="sc">-</span>critical <span class="sc">|</span> z <span class="sc">&gt;=</span> critical)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>rejection<span class="sc">$</span>side <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(rejection<span class="sc">$</span>z <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="st">"left"</span>, <span class="st">"right"</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>panel_labels <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">z =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">3.6</span>),</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">density =</span> <span class="fu">c</span>(<span class="fl">0.13</span>, <span class="fl">0.14</span>),</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"do not reject"</span>, <span class="st">"power"</span>),</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">panel =</span> <span class="fu">factor</span>(panel_levels[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">levels =</span> panel_levels)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>alpha_labels <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">z =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span>),</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">density =</span> <span class="fu">c</span>(<span class="fl">0.028</span>, <span class="fl">0.028</span>),</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"alpha/2"</span>, <span class="st">"alpha/2"</span>),</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">panel =</span> <span class="fu">factor</span>(panel_levels[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)], <span class="at">levels =</span> panel_levels)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(test_curves, <span class="fu">aes</span>(z, density)) <span class="sc">+</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> rejection, <span class="fu">aes</span>(<span class="at">group =</span> side, <span class="at">fill =</span> panel),</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>            <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="sc">-</span>critical, critical), <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"#5B6976"</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">colour =</span> panel), <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> panel_labels, <span class="fu">aes</span>(<span class="at">label =</span> label),</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>            <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> alpha_labels, <span class="fu">aes</span>(<span class="at">label =</span> label), <span class="at">parse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>            <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.1</span>) <span class="sc">+</span></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> panel, <span class="at">scales =</span> <span class="st">"fixed"</span>) <span class="sc">+</span></span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Null is true"</span> <span class="ot">=</span> <span class="st">"#D55E00"</span>,</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"An alternative value is true"</span> <span class="ot">=</span> <span class="st">"#009E73"</span>),</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>                    <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Null is true"</span> <span class="ot">=</span> <span class="st">"#17324D"</span>,</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"An alternative value is true"</span> <span class="ot">=</span> <span class="st">"#0072B2"</span>),</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>                      <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">6</span>)) <span class="sc">+</span></span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"z statistic"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>),</span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b10-errors-power" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b10-errors-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b10-testing-errors-power_files/figure-html/fig-b10-errors-power-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b10-errors-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.1: Two-sided testing at α = 0.05. Left: when the null is true, the z statistic follows the dark curve and the orange rejection regions have total probability 0.05 — the Type I error rate. Right: when a positive alternative is true, the statistic follows the shifted blue curve; the green area is the power, and the unshaded middle is the Type II error probability. Both panels use the same axes.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In both panels of <a href="#fig-b10-errors-power" class="quarto-xref">Figure&nbsp;<span>13.1</span></a>, the horizontal axis is the possible z statistic, the vertical axis is density, and probability is area. The dashed vertical lines mark the same two-sided critical values, <span class="math inline">\(\pm 1.96\)</span>. In the left panel the null is true: the two orange rejection tails have total probability <span class="math inline">\(\alpha=0.05\)</span>, which is exactly the Type I error rate — the test is <em>built</em> to cry wolf 5% of the time. In the right panel a particular positive alternative is true, so the curve has shifted: the green area is the power, and whatever probability remains between the dashed lines is the Type II error rate.</p>
<p>Four levers raise power:</p>
<ul>
<li>a larger true distance from zero (an effect that is easier to see);</li>
<li>a larger sample (a smaller SE);</li>
<li>lower unexplained variation (also a smaller SE);</li>
<li>a larger <span class="math inline">\(\alpha\)</span> — but this lever is a trade-off, not a free gain: widening the rejection region catches more true effects <em>and</em> raises the Type I error rate in lockstep.</li>
</ul>
</section>
<section id="one-sided-alternatives" class="level3">
<h3 class="anchored" data-anchor-id="one-sided-alternatives">One-sided alternatives</h3>
<p>A two-sided test asks whether a parameter differs from zero in <strong>either</strong> direction. A one-sided test asks a directional question chosen before the sample is examined:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Research question</th>
<th>Alternative</th>
<th>Relevant tail(s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Does the gap differ from zero?</td>
<td><span class="math inline">\(H_1:\delta\ne0\)</span></td>
<td>both tails</td>
</tr>
<tr class="even">
<td>Is the gap below zero?</td>
<td><span class="math inline">\(H_1:\delta&lt;0\)</span></td>
<td>left tail</td>
</tr>
<tr class="odd">
<td>Is the gap above zero?</td>
<td><span class="math inline">\(H_1:\delta&gt;0\)</span></td>
<td>right tail</td>
</tr>
</tbody>
</table>
<p>In all three cases the test statistic is compared with its distribution under the zero boundary <span class="math inline">\(H_0:\delta=0\)</span>. What changes is which values count as evidence for the stated alternative — that is, where the rejection region sits.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>alpha_tail <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>tail_df <span class="ot">&lt;-</span> <span class="dv">99</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>tail_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">1400</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>critical_two <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fu">c</span>(alpha_tail <span class="sc">/</span> <span class="dv">2</span>, <span class="dv">1</span> <span class="sc">-</span> alpha_tail <span class="sc">/</span> <span class="dv">2</span>), <span class="at">df =</span> tail_df)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>critical_left <span class="ot">&lt;-</span> <span class="fu">qt</span>(alpha_tail, <span class="at">df =</span> tail_df)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>critical_right <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha_tail, <span class="at">df =</span> tail_df)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>panel_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Two-sided"</span>, <span class="st">"Left-sided"</span>, <span class="st">"Right-sided"</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>null_curve <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(panel_levels, <span class="cf">function</span>(p) {</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">x =</span> tail_grid, <span class="at">density =</span> <span class="fu">dt</span>(tail_grid, <span class="at">df =</span> tail_df),</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">panel =</span> p)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>null_curve<span class="sc">$</span>panel <span class="ot">&lt;-</span> <span class="fu">factor</span>(null_curve<span class="sc">$</span>panel, <span class="at">levels =</span> panel_levels)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>rejection <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(<span class="fu">subset</span>(null_curve, panel <span class="sc">==</span> <span class="st">"Two-sided"</span> <span class="sc">&amp;</span> x <span class="sc">&lt;=</span> critical_two[<span class="dv">1</span>]),</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">side =</span> <span class="st">"left"</span>),</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(<span class="fu">subset</span>(null_curve, panel <span class="sc">==</span> <span class="st">"Two-sided"</span> <span class="sc">&amp;</span> x <span class="sc">&gt;=</span> critical_two[<span class="dv">2</span>]),</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">side =</span> <span class="st">"right"</span>),</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(<span class="fu">subset</span>(null_curve, panel <span class="sc">==</span> <span class="st">"Left-sided"</span> <span class="sc">&amp;</span> x <span class="sc">&lt;=</span> critical_left),</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">side =</span> <span class="st">"left"</span>),</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(<span class="fu">subset</span>(null_curve, panel <span class="sc">==</span> <span class="st">"Right-sided"</span> <span class="sc">&amp;</span> x <span class="sc">&gt;=</span> critical_right),</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>        <span class="at">side =</span> <span class="st">"right"</span>)</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>critical_lines <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">c</span>(critical_two, critical_left, critical_right),</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">panel =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Two-sided"</span>, <span class="st">"Two-sided"</span>, <span class="st">"Left-sided"</span>, <span class="st">"Right-sided"</span>),</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>                 <span class="at">levels =</span> panel_levels)</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>panel_labels <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.8</span>, <span class="fl">2.8</span>, <span class="sc">-</span><span class="fl">2.8</span>, <span class="fl">2.8</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">density =</span> <span class="fu">c</span>(<span class="fl">0.035</span>, <span class="fl">0.035</span>, <span class="fl">0.035</span>, <span class="fl">0.035</span>, <span class="fl">0.42</span>, <span class="fl">0.42</span>, <span class="fl">0.42</span>),</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"2.5%"</span>, <span class="st">"2.5%"</span>, <span class="st">"5%"</span>, <span class="st">"5%"</span>,</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>            <span class="st">"H[1] : delta != 0"</span>, <span class="st">"H[1] : delta &lt; 0"</span>, <span class="st">"H[1] : delta &gt; 0"</span>),</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">parse_me =</span> <span class="fu">c</span>(<span class="cn">FALSE</span>, <span class="cn">FALSE</span>, <span class="cn">FALSE</span>, <span class="cn">FALSE</span>, <span class="cn">TRUE</span>, <span class="cn">TRUE</span>, <span class="cn">TRUE</span>),</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">panel =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Two-sided"</span>, <span class="st">"Two-sided"</span>, <span class="st">"Left-sided"</span>, <span class="st">"Right-sided"</span>,</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Two-sided"</span>, <span class="st">"Left-sided"</span>, <span class="st">"Right-sided"</span>),</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>                 <span class="at">levels =</span> panel_levels)</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(null_curve, <span class="fu">aes</span>(x, density)) <span class="sc">+</span></span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> rejection, <span class="fu">aes</span>(<span class="at">group =</span> side),</span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a>            <span class="at">fill =</span> <span class="st">"#D55E00"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>,</span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"grey75"</span>, <span class="at">linewidth =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> critical_lines, <span class="fu">aes</span>(<span class="at">xintercept =</span> x),</span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"#5B6976"</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> <span class="fu">subset</span>(panel_labels, <span class="sc">!</span>parse_me), <span class="fu">aes</span>(<span class="at">label =</span> label),</span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a>            <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">2.9</span>) <span class="sc">+</span></span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> <span class="fu">subset</span>(panel_labels, parse_me), <span class="fu">aes</span>(<span class="at">label =</span> label),</span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a>            <span class="at">parse =</span> <span class="cn">TRUE</span>, <span class="at">colour =</span> <span class="st">"#5B6976"</span>, <span class="at">size =</span> <span class="fl">3.1</span>) <span class="sc">+</span></span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> panel, <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">scales =</span> <span class="st">"fixed"</span>) <span class="sc">+</span></span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">3</span>)) <span class="sc">+</span></span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.2</span>, <span class="fl">0.4</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.44</span>),</span>
<span id="cb10-60"><a href="#cb10-60" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.02</span>))) <span class="sc">+</span></span>
<span id="cb10-61"><a href="#cb10-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"t statistic"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb10-62"><a href="#cb10-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb10-63"><a href="#cb10-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb10-64"><a href="#cb10-64" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb10-65"><a href="#cb10-65" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb10-66"><a href="#cb10-66" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb10-67"><a href="#cb10-67" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>),</span>
<span id="cb10-68"><a href="#cb10-68" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb10-69"><a href="#cb10-69" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-b10-one-sided" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b10-one-sided-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="b10-testing-errors-power_files/figure-html/fig-b10-one-sided-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b10-one-sided-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.2: Rejection regions at α = 0.05 for the two-sided and both one-sided alternatives, on the same null t distribution (df = 99). The two-sided test places 2.5% in each tail; a one-sided test moves the full 5% into the tail named by its alternative, so its critical value is closer to zero in that direction.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Compare <a href="#fig-b10-one-sided" class="quarto-xref">Figure&nbsp;<span>13.2</span></a> with the left panel of <a href="#fig-b10-errors-power" class="quarto-xref">Figure&nbsp;<span>13.1</span></a>: same logic, different placement of the 5%. Moving the full 5% into one tail pulls that critical value closer to zero, so a one-sided test is <em>more</em> able to detect an effect in its chosen direction — a power gain. The price: results in the opposite direction, however extreme, do not support the stated alternative at all.</p>
<p>That power gain is exactly why the direction must follow from the research question and be <strong>fixed before the data are inspected</strong>. Choosing the tail because the observed estimate happens to point that way — or simply to obtain a smaller p-value — silently doubles the true Type I error rate: you would take the 5% tail on whichever side the noise landed. For Lecture 9’s equity-gap statistic, <span class="math inline">\(t=-2.91\)</span> with <span class="math inline">\(df=99\)</span>:</p>
<ul>
<li>the two-sided p-value is about 0.0045;</li>
<li>a <strong>pre-specified</strong> left-sided alternative <span class="math inline">\(H_1:\delta&lt;0\)</span> gives about 0.0023;</li>
<li>a <strong>pre-specified</strong> right-sided alternative <span class="math inline">\(H_1:\delta&gt;0\)</span> gives about 0.9977.</li>
</ul>
<p>The negative estimate agrees with the left-sided alternative and points away from the right-sided one. Course convention, on the exam and in every chapter: <strong>tests are two-sided</strong>, because in business research a difference in either direction is usually relevant — and because the convention removes any temptation to pick the convenient tail.</p>
</section>
<section id="preview-the-test-attached-to-a-regression-slope" class="level3">
<h3 class="anchored" data-anchor-id="preview-the-test-attached-to-a-regression-slope">Preview: the test attached to a regression slope</h3>
<p>R applies the same zero-null logic to every regression coefficient. Consider the simple model of initial equity offered on season, fitted to all 1,441 records:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>preview_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season, <span class="at">data =</span> sharks)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(preview_model)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error   t value      Pr(&gt;|t|)
(Intercept) 20.4565874 0.46442667  44.04697 4.922706e-269
season      -0.8241241 0.04752298 -17.34159  2.514546e-61</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(preview_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %     97.5 %
(Intercept) 19.5455616 21.3676132
season      -0.9173458 -0.7309023</code></pre>
</div>
</div>
<p>Read the <code>season</code> row with the vocabulary you now own. The <strong>estimate</strong> is <span class="math inline">\(-0.824\)</span>: about 0.82 percentage points less equity offered per additional season. The <strong>SE</strong>, 0.048, is its sampling uncertainty in the same units. The <strong>t value</strong>, <span class="math inline">\(-17.3\)</span>, is estimate divided by SE — step 5 of the workflow. The <strong>p-value</strong> belongs to the printed two-sided test</p>
<p><span class="math display">\[
H_0:\beta_1=0
\qquad\text{versus}\qquad
H_1:\beta_1\ne0,
\]</span></p>
<p>and the 95% <strong>interval</strong> <span class="math inline">\((-0.92,\,-0.73)\)</span> excludes zero, agreeing with the rejection. Every column is a Lecture 9–10 object wearing a regression name. What the row does <em>not</em> say: this is an observational time association, not a causal effect of moving a pitch to a later season.</p>
<p>Intermediate begins from this familiar estimate–SE–t–p-value structure and adds careful coefficient interpretation, multiple predictors, and model diagnostics.</p>
<div class="caveat-box">
<p><span class="label">What a significant result does and does not establish</span></p>
<p>Three separations to carry out of this course. <strong>Significance is not magnitude:</strong> a tiny effect can be significant in a large sample, and a meaningful effect can be non-significant in a small or noisy one — the p-value measures surprise under the null, the estimate measures size. <strong>Significance is not causation:</strong> none of this lecture’s machinery knows whether the predictor was randomly assigned. <strong>And no test repairs the frame:</strong> selection into the recorded-pitch file, measurement of “deal” as an on-air agreement, and dependence between observations are untouched by any p-value. The standing reporting list, for every analysis from now on: the estimate in substantive units; a confidence interval; the p-value or decision; whether the magnitude matters for the business question; and the sampling, measurement, and causal limits.</p>
</div>
</section>
<section id="answering-the-driving-question" class="level3">
<h3 class="anchored" data-anchor-id="answering-the-driving-question">Answering the driving question</h3>
<p>The two wrong calls: rejecting a true null (Type I, rate set by <span class="math inline">\(\alpha\)</span>) and missing a true effect (Type II, rate cut by power). Wrong calls become rarer with more data, less noise, bigger true effects — and, for Type I only, a stricter <span class="math inline">\(\alpha\)</span>, at the price of more Type II. And the regression table? Each coefficient row <em>is</em> a Lecture 9 test: estimate, SE, t, two-sided p against zero, interval.</p>
<p>That closes the arc of QM Basic. Ten lectures ago a Shark Tank pitch was an anecdote. Now you can define events and variables on a frame, describe their distributions, condition without confusing directions, model sampling variation, and turn “our sample mean is 12.76” into a defensible, properly hedged claim about a population — with its uncertainty, its decision, and its limits stated. That is the difference between an opinion with a spreadsheet and evidence.</p>
<p><strong>Next:</strong> Tutorial 4 rehearses Lectures 9–10 in exam format, and the Mock Exam then integrates the whole course under exam conditions. The story itself continues next year: QM Intermediate picks up exactly where today’s regression preview left off, and the coefficient row you can already read becomes the central object of six lectures on linear regression.</p>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p><span class="time-budget">Total practice time: about 65 minutes.</span></p>
<section id="retrieval-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="retrieval-10-minutes">Retrieval (10 minutes)</h3>
<ol type="1">
<li>Why can most comparison hypotheses be written as a parameter equal to zero?</li>
<li>What is the difference between <span class="math inline">\(\alpha\)</span> and a p-value?</li>
<li>What is a Type I error?</li>
<li>What is a Type II error?</li>
<li>Name three factors that increase power.</li>
<li>Why is “do not reject” different from “accept”?</li>
<li>What does <span class="math inline">\(H_0:\beta_j=0\)</span> mean in a regression model?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Subtracting the benchmark or reference value creates a contrast; “no difference” corresponds to a zero contrast.</li>
<li><span class="math inline">\(\alpha\)</span> is a pre-specified long-run decision threshold; the p-value is calculated from the observed statistic under the null.</li>
<li>Rejecting <span class="math inline">\(H_0\)</span> when it is true.</li>
<li>Not rejecting <span class="math inline">\(H_0\)</span> when a specified alternative is true.</li>
<li>Any three of: larger sample size, larger true effect, lower noise, or larger <span class="math inline">\(\alpha\)</span> (the last at the cost of more Type I errors).</li>
<li>A non-significant result may simply be too imprecise to distinguish a meaningful parameter from zero.</li>
<li>Holding the other included predictors fixed, the population-model coefficient for predictor <span class="math inline">\(j\)</span> is zero.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="from-worked-to-faded-then-unassisted-20-minutes" class="level3">
<h3 class="anchored" data-anchor-id="from-worked-to-faded-then-unassisted-20-minutes">From worked to faded, then unassisted (20 minutes)</h3>
<p>Re-read the hand-worked launch test (<a href="#exm-b10-launch-test" class="quarto-xref">Example&nbsp;<span>13.1</span></a>). Then complete the same recipe with new numbers: in 200 independent trials there are 120 successes, and the benchmark is <span class="math inline">\(p_0=0.50\)</span>.</p>
<p><em>Step 1 (given).</em> <span class="math inline">\(\hat p=120/200=0.60\)</span>, so <span class="math inline">\(\widehat\delta_p=0.10\)</span>; the null counts are <span class="math inline">\(200(0.50)=100\)</span> successes and 100 failures, both above 10.</p>
<p><em>Step 2 (you).</em> Calculate the null SE and the z statistic.</p>
<p><em>Step 3 (you).</em> The two-sided p-value and the 5% decision, in context.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\operatorname{SE}_0=\sqrt{0.50(0.50)/200}\approx 0.0354\)</span>, so <span class="math inline">\(z=0.10/0.0354\approx 2.83\)</span> and the two-sided p-value is about 0.005. Reject the zero-gap null at 5%: the data provide evidence that the success proportion differs from 50%, with the positive estimate placing it above.</p>
</div>
</div>
</div>
<p>Now unassisted:</p>
<ol type="1">
<li>A sample of <span class="math inline">\(n=49\)</span> difference scores has <span class="math inline">\(\bar d=3\)</span> and <span class="math inline">\(s_d=14\)</span>. Test <span class="math inline">\(H_0:\delta=0\)</span> against <span class="math inline">\(H_1:\delta\ne0\)</span> at 5%.</li>
<li>Describe the Type I and Type II errors for the 120-of-200 test above, in context.</li>
<li>A multiple-regression coefficient is <span class="math inline">\(-0.290\)</span> percentage points per €100,000, with SE 0.058 and a large <span class="math inline">\(df\)</span>. Calculate its t statistic and approximate 95% interval, and interpret the row.</li>
<li>A coefficient estimate is economically negligible but has <span class="math inline">\(p&lt;0.001\)</span>. Explain how both facts can be true.</li>
<li>State two reasons the regression preview cannot support a causal conclusion.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The SE is <span class="math inline">\(14/\sqrt{49}=2\)</span>, so <span class="math inline">\(t=3/2=1.50\)</span> with <span class="math inline">\(df=48\)</span>; the two-sided p-value is about 0.14. Do not reject the zero mean-difference null at 5% — which is not evidence that the difference is zero.</li>
<li>Type I: concluding the population success proportion differs from 0.50 when it equals 0.50. Type II: failing to detect a genuine specified difference from 0.50.</li>
<li><span class="math inline">\(t=-0.290/0.058=-5.00\)</span>. With a large <span class="math inline">\(df\)</span>, the 95% interval is approximately <span class="math inline">\(-0.290\pm1.96(0.058)=(-0.404,\,-0.176)\)</span> percentage points per €100,000. Holding the model’s other predictors fixed, an additional €100,000 requested is associated with between about 0.18 and 0.40 percentage points less fitted equity; reject the zero-coefficient null.</li>
<li>A very large sample or low noise makes the SE tiny, so even a negligible coefficient sits many SEs from zero. Precision does not confer importance.</li>
<li>Season was not randomly assigned, and omitted factors, selection, reverse direction, or measurement error can all remain.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="one-sided-reasoning-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="one-sided-reasoning-10-minutes">One-sided reasoning (10 minutes)</h3>
<p>Lecture 9’s equity-gap test gave <span class="math inline">\(t=-2.91\)</span> with <span class="math inline">\(df=99\)</span>.</p>
<ol type="1">
<li>State all three p-values: two-sided, left-sided (<span class="math inline">\(H_1:\delta&lt;0\)</span>), and right-sided (<span class="math inline">\(H_1:\delta&gt;0\)</span>).</li>
<li>Which of the three alternatives would have been legitimate to pre-specify, and what determines that?</li>
<li>A classmate, seeing the negative estimate, switches to the left-sided alternative “because it fits the data.” What exactly is wrong?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Two-sided: about 0.0045. Left-sided: about 0.0023 (the single left tail beyond <span class="math inline">\(-2.91\)</span>). Right-sided: about 0.9977 (everything to the right of <span class="math inline">\(-2.91\)</span>).</li>
<li>Any of the three — <strong>provided</strong> it was fixed before inspecting the sample and follows from the research question. Legitimacy is about timing and motivation, not about which alternative is “correct.”</li>
<li>Choosing the tail after seeing the estimate means the 5% rejection mass would follow the data to whichever side the noise landed, so the true Type I error rate is doubled to about 10%. The smaller p-value is bought by an invalid procedure. Course convention: two-sided, always, on the exam.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="spaced-review-one-item-each-from-lectures-9-and-5-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="spaced-review-one-item-each-from-lectures-9-and-5-10-minutes">Spaced review: one item each from Lectures 9 and 5 (10 minutes)</h3>
<ol type="1">
<li><em>(Lecture 9.)</em> A 95% confidence interval for a mean gap is <span class="math inline">\((0.4,\,5.2)\)</span> units. State the 5% two-sided test decision without computing, and name one thing the interval reports that the decision does not.</li>
<li><em>(Lecture 5.)</em> In the full file, the correlation between season and initial equity offered is about <span class="math inline">\(-0.42\)</span>. Interpret this number in one sentence, and state one claim it cannot support.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The interval excludes zero, so the matched two-sided test rejects <span class="math inline">\(H_0:\delta=0\)</span> at 5%. The interval additionally shows direction, plausible magnitude (0.4 to 5.2 units), and precision.</li>
<li>Season and offered equity have a moderate negative linear association: later-season pitches tend to offer less equity. It cannot support a causal claim — nothing assigned pitches to seasons, and other factors changed over time.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="worked-exam-interpretation-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="worked-exam-interpretation-10-minutes">Worked exam interpretation (10 minutes)</h3>
<p><strong>Question (Mock Exam Q5 pattern).</strong> In a simple random sample of 400 former accelerator participants, 232 had launched a trading venture within one year; a two-sided test of <span class="math inline">\(H_0:p=0.50\)</span> is planned. The same study fits a regression of monthly revenue (thousands of euros) on weekly mentoring hours; one row of the output is:</p>
<pre class="text"><code>                 Estimate  Std. Error  t value  Pr(&gt;|t|)  95% CI
mentoring_hours     0.80       0.25       3.20     0.0016  [0.31, 1.29]</code></pre>
<p>Complete the proportion test at 5% (a large-sample 95% interval for <span class="math inline">\(p\)</span> is <span class="math inline">\((0.532,\,0.628)\)</span>), define a Type I error for it, name two power levers that hold <span class="math inline">\(\alpha\)</span> fixed, and interpret the regression row without causal language.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(np_0=n(1-p_0)=200\ge 10\)</span>. <span class="math inline">\(\hat p=232/400=0.58\)</span>, <span class="math inline">\(\operatorname{SE}_0=\sqrt{0.50(0.50)/400}=0.025\)</span>, and <span class="math inline">\(z=0.08/0.025=3.20\)</span> with two-sided p-value about 0.0014: reject <span class="math inline">\(H_0\)</span>; the frame launch proportion differs from 50%, plausibly between 53.2% and 62.8% — the interval excludes 0.50, agreeing with the test. A Type I error would be concluding the launch proportion differs from 50% when it equals 50%. With <span class="math inline">\(\alpha\)</span> fixed, power rises with a larger sample or lower outcome variability (or a larger true gap, though that is not chosen). The regression row: each additional weekly mentoring hour is associated with 0.80 thousand euros more fitted monthly revenue; <span class="math inline">\(t=0.80/0.25=3.20\)</span>, <span class="math inline">\(p=0.0016\)</span>, and the interval <span class="math inline">\((0.31,\,1.29)\)</span> excludes zero, so reject <span class="math inline">\(H_0:\beta=0\)</span>. Mentoring hours were not randomly assigned, so this is an association, not a causal effect.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Utility: two sentences</span></p>
<p>Think of your EiA venture — or any business you know well. Name one yes-or-no claim you will realistically have to defend with data (our conversion rate beats the sector’s 3%; our average order exceeds the break-even basket), and write two sentences: first state it as a two-sided zero-contrast test and say which of the two errors would be more costly for you and why, then name the one power lever you could actually pull before your next pitch.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run campus meal-prep box venture. “My claim: our conversion rate differs from the sector’s 3% — <span class="math inline">\(H_0\!: p = 0.03\)</span> against a two-sided alternative. A false alarm is the costlier error, because I would sign a bigger kitchen lease on an effect that is not real; the one power lever I can pull before the next pitch is sample size, by running the tasting stand two more weeks.”</p>
</div>
</div>
</div>
<p>You can discuss this task — and any other task in this chapter — with <strong>Tilly</strong>, the course AI assistant on Canvas: ask it to draft the seven-step workflow for your claim and challenge your choice of the more costly error.</p>
</div>
<p>Continue to Tutorial 4: Inference and tests against zero.</p>
<p>Formula sheet: Lecture 10 formulas.</p>
<p>For a more formal explanation, consult <a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>, Chapters 15 and 16.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/b09-t-confidence-intervals.html" class="pagination-link" aria-label="Lecture 9: The t distribution, confidence intervals, and the two-sided test">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lecture 9: The t distribution, confidence intervals, and the two-sided test</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/t04-exam-prep.html" class="pagination-link" aria-label="Tutorial 4: Inference and tests against zero">
        <span class="nav-page-text"><span class="chapter-title">Tutorial 4: Inference and tests against zero</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>