<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mock Exam: QM Basic – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../intermediate/overview.html" rel="next">
<link href="../basic/formula-sheet.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0373dafead96411fe286b8dec0b5ee25.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/mock-exam.html"><span class="chapter-title">Mock Exam: QM Basic</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and a first look at regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Hypothesis tests, errors, and power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#question-1-data-and-a-histogram-11-points" id="toc-question-1-data-and-a-histogram-11-points" class="nav-link active" data-scroll-target="#question-1-data-and-a-histogram-11-points">Question 1: Data and a histogram (11 points)</a></li>
  <li><a href="#question-2-probability-from-a-table-and-a-decision-about-checks-14-points" id="toc-question-2-probability-from-a-table-and-a-decision-about-checks-14-points" class="nav-link" data-scroll-target="#question-2-probability-from-a-table-and-a-decision-about-checks-14-points">Question 2: Probability from a table, and a decision about checks (14 points)</a></li>
  <li><a href="#question-3-expected-value-spread-and-two-variables-17-points" id="toc-question-3-expected-value-spread-and-two-variables-17-points" class="nav-link" data-scroll-target="#question-3-expected-value-spread-and-two-variables-17-points">Question 3: Expected value, spread, and two variables (17 points)</a></li>
  <li><a href="#question-4-a-normal-model-and-the-precision-of-a-sample-mean-13-points" id="toc-question-4-a-normal-model-and-the-precision-of-a-sample-mean-13-points" class="nav-link" data-scroll-target="#question-4-a-normal-model-and-the-precision-of-a-sample-mean-13-points">Question 4: A normal model and the precision of a sample mean (13 points)</a></li>
  <li><a href="#question-5-a-mean-test-in-five-steps-and-r-output-14-points" id="toc-question-5-a-mean-test-in-five-steps-and-r-output-14-points" class="nav-link" data-scroll-target="#question-5-a-mean-test-in-five-steps-and-r-output-14-points">Question 5: A mean test in five steps, and R output (14 points)</a></li>
  <li><a href="#question-6-an-interval-and-a-test-for-a-proportion-two-errors-and-power-22-points" id="toc-question-6-an-interval-and-a-test-for-a-proportion-two-errors-and-power-22-points" class="nav-link" data-scroll-target="#question-6-an-interval-and-a-test-for-a-proportion-two-errors-and-power-22-points">Question 6: An interval and a test for a proportion, two errors, and power (22 points)</a></li>
  <li><a href="#question-7-an-answer-of-an-ai-assistant-about-a-regression-row-9-points" id="toc-question-7-an-answer-of-an-ai-assistant-about-a-regression-row-9-points" class="nav-link" data-scroll-target="#question-7-an-answer-of-an-ai-assistant-about-a-regression-row-9-points">Question 7: An answer of an AI assistant about a regression row (9 points)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/mock-exam.html"><span class="chapter-title">Mock Exam: QM Basic</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="basic-mock-exam" class="quarto-section-identifier"><span class="chapter-title">Mock Exam: QM Basic</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This mock exam covers all ten lectures of the course. It contains 100 points. Your test score is</p>
<p><span class="math display">\[
\text{test score} = \frac{\text{points earned}}{10},
\]</span></p>
<p>on a scale from 1.00 to 10.00, with two decimals. A score below 1.00 counts as 1.00. The test score goes into Osiris, the student information system. Osiris then rounds the test score to a whole or half grade for your final course grade. A score from 5.50 to 5.74 becomes 6.0, and a score from 5.25 to 5.49 becomes 5.0. For example, 72 points give a test score of 7.20 and a final grade of 7.0. You pass with a final grade of 6.0 or higher, that is, with 55 points or more.</p>
<p>The mock exam has the same form as the real exam:</p>
<ul>
<li>You write the exam on paper. It is a closed-book exam: you may not use books or notes. When you practise, give yourself 180 minutes.</li>
<li>There are seven questions. Every question has several parts, and every part shows its points.</li>
<li>All parts are open questions. You write your calculation or your explanation. An answer without a calculation or a reason gets no points, unless the part asks only to state or to name something.</li>
<li>Some questions show output from R or an answer of an AI assistant. You interpret the output or you assess the answer. You do not write R code in this exam.</li>
<li>You may use a calculator of the Casio FX-82 series or of the Texas Instruments TI-30 series, but not the TI-30X Pro. Other calculators are not allowed.</li>
<li>The complete <a href="formula-sheet.html">QM Basic Formula Sheet</a> is attached to the exam.</li>
<li>There are no statistical tables. Every probability or critical value (z or t value) that you need is printed in the question or is on the formula sheet.</li>
<li>All tests are two-sided. Use a 5% significance level.</li>
<li>At the exam inspection, you can see your marked exam. Canvas announces the date of the inspection together with the grades.</li>
</ul>
<section id="question-1-data-and-a-histogram-11-points" class="level2">
<h2 class="anchored" data-anchor-id="question-1-data-and-a-histogram-11-points">Question 1: Data and a histogram (11 points)</h2>
<p>An invented example. An entrepreneurship centre runs an accelerator, a support programme for new ventures. This year the accelerator received 240 applications. The dataset of the centre has these variables:</p>
<ul>
<li><code>application_id</code>: a number that identifies the application</li>
<li><code>funding_requested_k</code>: funding requested, in thousands of euros</li>
<li><code>team_size</code>: number of people in the venture team</li>
<li><code>stage</code>: <code>idea</code>, <code>prototype</code>, or <code>first sales</code></li>
<li><code>accepted</code>: 1 if the application was accepted and 0 otherwise.</li>
</ul>
<p>The histogram shows the 240 values of <code>funding_requested_k</code> in intervals of 20 thousand euros. Each interval includes its upper limit: for example, a value of exactly 20 is in the first bar. The number above a bar is the number of applications in that interval.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Self-contained: constructs everything it plots.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>mock_breaks <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">120</span>, <span class="at">by =</span> <span class="dv">20</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>mock_counts <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">58</span>, <span class="dv">88</span>, <span class="dv">54</span>, <span class="dv">24</span>, <span class="dv">10</span>, <span class="dv">6</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>mock_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xmin =</span> mock_breaks[<span class="sc">-</span><span class="fu">length</span>(mock_breaks)],</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">xmax =</span> mock_breaks[<span class="sc">-</span><span class="dv">1</span>],</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">count =</span> mock_counts</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mock_df) <span class="sc">+</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rect</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> xmin, <span class="at">xmax =</span> xmax, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> count),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> (xmin <span class="sc">+</span> xmax) <span class="sc">/</span> <span class="dv">2</span>, <span class="at">y =</span> count, <span class="at">label =</span> count),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">4.2</span>) <span class="sc">+</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> mock_breaks) <span class="sc">+</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="at">by =</span> <span class="dv">20</span>),</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))) <span class="sc">+</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Funding requested (thousands of euros)"</span>,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of applications"</span>) <span class="sc">+</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-bmock-histogram" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bmock-histogram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mock-exam_files/figure-html/fig-bmock-histogram-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bmock-histogram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.1: Funding requested in the 240 accelerator applications. The number above each bar is the number of applications in that interval.
</figcaption>
</figure>
</div>
</div>
</div>
<ol type="1">
<li>State what one row of the dataset represents and which group the 240 rows describe. <strong>(1 point)</strong></li>
<li>State the type of each of these three variables: <code>application_id</code>, <code>stage</code>, <code>accepted</code>. Use the five terms of Lecture 1: categorical, ordinal, discrete, continuous, identifier. An example: <code>funding_requested_k</code> is a continuous variable. <strong>(3 points)</strong></li>
<li>(a) Calculate the cumulative count and the cumulative share of each of the six intervals. The cumulative share is the cumulative count divided by 240. Use your results to state the interval that contains (b) the median and (c) the upper quartile <span class="math inline">\(Q_3\)</span> of <code>funding_requested_k</code>. <strong>(3 points: 1 + 1 + 1)</strong></li>
<li>A colleague wants to describe <code>funding_requested_k</code> with a normal model. Decide whether a normal model fits, and give one reason that you can see in the histogram. <strong>(2 points)</strong></li>
<li>The director of the centre writes: “Most new ventures in the Netherlands need at most 40 thousand euros.” (a) Explain in one sentence why these data cannot support this claim. (b) Rewrite the sentence so that the data support it. Use a count or a percentage. <strong>(2 points: 1 + 1)</strong></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer and marking guide
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>One row is one application to the accelerator. Accept: one venture that applied. The rows describe the 240 applications that the centre received this year (1 point, only if both are correct). No point for “all new ventures” or “all start-ups”.</li>
<li><code>application_id</code> is an identifier. <code>stage</code> is ordinal, because its three groups have an order. <code>accepted</code> is categorical with two groups (binary), although it is stored as 0 and 1 (1 point each). Accept “binary” for <code>accepted</code>. No point for “categorical” for <code>stage</code>, and no point for “discrete” for <code>accepted</code> or for <code>application_id</code>.</li>
<li>(a) The cumulative counts are 58, 146, 200, 224, 234, and 240. The cumulative shares are 0.242, 0.608, 0.833, 0.933, 0.975, and 1.000 (1 point if the cumulative counts and the cumulative shares are correct for all six intervals, or at least for the first three intervals). Accept percentages. (b) With 240 values the median lies between the 120th and the 121st ordered value. The cumulative share first reaches 0.50 in the second interval (0.608, or 146 of 240), so the median is above 20 and at most 40 thousand euros (1 point). (c) The upper quartile is the 180th value, because <span class="math inline">\(0.75\times240=180\)</span>. The cumulative share first reaches 0.75 in the third interval (0.833, or 200 of 240), so <span class="math inline">\(Q_3\)</span> is above 40 and at most 60 thousand euros (1 point). An interval in (b) or (c) without a cumulative count or share gets no point.</li>
<li>A normal model does not fit (1 point). Reason: the histogram is skewed to the right. Most applications lie in the first two intervals, and the counts fall slowly from 54 to 6 on the right side. A normal curve is symmetric around its centre (1 point). Accept as a reason: the values cannot be below zero, and the first interval already holds 58 applications, so there is no left tail.</li>
<li>(a) The 240 ventures chose to apply to this accelerator. They are not a random sample of all new ventures in the Netherlands, so they can differ in a systematic way from the other new ventures (1 point). Accept: the data show the amount requested, which is not the amount needed. (b) “Of the 240 applications to this accelerator, 146 (about 61%) requested at most 40 thousand euros” (1 point). The rewritten sentence must name the 240 applications and use 146 or 61%.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(mock_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  58 146 200 224 234 240</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cumsum</span>(mock_counts) <span class="sc">/</span> <span class="dv">240</span>, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.242 0.608 0.833 0.933 0.975 1.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">median_position =</span> <span class="dv">240</span> <span class="sc">/</span> <span class="dv">2</span>, <span class="at">q3_position =</span> <span class="fl">0.75</span> <span class="sc">*</span> <span class="dv">240</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>median_position     q3_position 
            120             180 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="question-2-probability-from-a-table-and-a-decision-about-checks-14-points" class="level2">
<h2 class="anchored" data-anchor-id="question-2-probability-from-a-table-and-a-decision-about-checks-14-points">Question 2: Probability from a table, and a decision about checks (14 points)</h2>
<p>An invented example. An archive contains 500 televised business pitches. You select one record at random, so every record has the same chance to be selected. <span class="math inline">\(D\)</span> is the event that the pitch ended with a deal on air. <span class="math inline">\(W\)</span> is the event that at least one woman is among the presenters.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Presenters</th>
<th style="text-align: right;">Deal on air</th>
<th style="text-align: right;">No deal on air</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Women among the presenters</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">110</td>
<td style="text-align: right;">200</td>
</tr>
<tr class="even">
<td>No women among the presenters</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">180</td>
<td style="text-align: right;">300</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>210</strong></td>
<td style="text-align: right;"><strong>290</strong></td>
<td style="text-align: right;"><strong>500</strong></td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Calculate (a) <span class="math inline">\(P(D)\)</span> and (b) <span class="math inline">\(P(D\cap W)\)</span>. <strong>(2 points: 1 + 1)</strong></li>
<li>Calculate <span class="math inline">\(P(D\cup W)\)</span>. Show your calculation. <strong>(1 point)</strong></li>
<li>Calculate (a) <span class="math inline">\(P(D\mid W)\)</span> and (b) <span class="math inline">\(P(W\mid D)\)</span>. <strong>(2 points: 1 + 1)</strong></li>
<li>Decide whether <span class="math inline">\(D\)</span> and <span class="math inline">\(W\)</span> are independent. Show the comparison that you used. <strong>(2 points)</strong></li>
</ol>
<p>Parts 5 and 6 use a new invented example. A founder rents out e-scooters. Of all rentals, 5% end with damage to the scooter. A sensor in the scooter puts a flag on some rentals. The sensor flags 80% of the rentals with damage. It also flags 10% of the rentals without damage.</p>
<ol start="5" type="1">
<li>Use a tree of 1,000 rentals. (a) State the four counts at the ends of the four branches of the tree. (b) Calculate the probability that a flagged rental ended with damage. (c) Calculate the probability that a rental without a flag ended with damage. <strong>(4 points: 2 + 1 + 1)</strong></li>
<li>After a rental, the founder can check the scooter by hand. One check costs her 4 euros of working time. When the check finds damage, the customer pays 60 euros for the damage. For each group, the expected gain of one check is the probability of damage times 60 euros. A check is worth its cost when the expected gain is above 4 euros. Decide which rentals the founder should check: the flagged rentals, the rentals without a flag, both groups, or no rental. Show the expected gain for each group. If you could not solve part 5, use 0.25 as the probability of damage for flagged rentals and 0.02 for rentals without a flag. <strong>(3 points)</strong></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer and marking guide
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>(a) <span class="math inline">\(P(D)=210/500=0.42\)</span> (1 point). (b) <span class="math inline">\(P(D\cap W)=90/500=0.18\)</span> (1 point). Accept fractions.</li>
<li><span class="math inline">\(P(W)=200/500=0.40\)</span>. The addition rule gives <span class="math inline">\(P(D\cup W)=0.42+0.40-0.18=0.64\)</span> (1 point for the result with its calculation). Accept the count <span class="math inline">\((90+110+120)/500=320/500\)</span>. An answer of 0.82, which counts the 90 pitches twice, gets no point.</li>
<li>(a) <span class="math inline">\(P(D\mid W)=90/200=0.45\)</span> (1 point). (b) <span class="math inline">\(P(W\mid D)=90/210\approx0.429\)</span> (1 point). The first probability divides by the 200 pitches with women among the presenters. The second divides by the 210 pitches with a deal. If the two values are swapped, give 0 points.</li>
<li><span class="math inline">\(P(D)\,P(W)=0.42\times0.40=0.168\)</span> (1 point). This is not equal to <span class="math inline">\(P(D\cap W)=0.18\)</span>, so <span class="math inline">\(D\)</span> and <span class="math inline">\(W\)</span> are not independent (1 point). A comparison of <span class="math inline">\(P(D\mid W)=0.45\)</span> with <span class="math inline">\(P(D)=0.42\)</span> is also correct and gets full points. A conclusion without a number gets no point.</li>
<li>(a) Of 1,000 rentals, 50 end with damage and 950 do not. Of the 50 rentals with damage, 40 are flagged and 10 are not (1 point). Of the 950 others, 95 are flagged and 855 are not (1 point). (b) <span class="math inline">\(40+95=135\)</span> rentals are flagged, so <span class="math inline">\(P(\text{damage}\mid\text{flag})=40/135\approx0.296\)</span> (1 point). (c) <span class="math inline">\(10+855=865\)</span> rentals have no flag, so <span class="math inline">\(P(\text{damage}\mid\text{no flag})=10/865\approx0.012\)</span> (1 point). An answer with the Bayes formula instead of the tree gets the same points. The products 0.04, 0.01, 0.095, and 0.855 then count as the four counts.</li>
<li>Flagged rentals: <span class="math inline">\(0.2963\times60\approx17.78\)</span> euros, which is above the cost of 4 euros (1 point). Rentals without a flag: <span class="math inline">\((10/865)\times60\approx0.69\)</span> euros, below 4 euros (1 point). Accept 0.70 and 0.72 euros, which follow from 0.0116 and 0.012. Decision: check the flagged rentals only (1 point). With the printed values the results are 15 euros and 1.20 euros, and the decision is the same. An answer that subtracts the cost and compares with zero (13.78 and <span class="math inline">\(-3.31\)</span> euros, or 11 and <span class="math inline">\(-2.80\)</span> euros with the printed values) gets full points. With wrong values from part 5, give the points when the two products and the comparison with 4 euros are correct for these wrong values.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>pitch_counts <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">90</span>, <span class="dv">110</span>, <span class="dv">120</span>, <span class="dv">180</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>n_pitches <span class="ot">&lt;-</span> <span class="fu">sum</span>(pitch_counts)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">P_D =</span> <span class="fu">sum</span>(pitch_counts[, <span class="dv">1</span>]) <span class="sc">/</span> n_pitches,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_W =</span> <span class="fu">sum</span>(pitch_counts[<span class="dv">1</span>, ]) <span class="sc">/</span> n_pitches,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_D_and_W =</span> pitch_counts[<span class="dv">1</span>, <span class="dv">1</span>] <span class="sc">/</span> n_pitches,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_D_or_W =</span> (<span class="dv">210</span> <span class="sc">+</span> <span class="dv">200</span> <span class="sc">-</span> <span class="dv">90</span>) <span class="sc">/</span> n_pitches,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_D_given_W =</span> <span class="dv">90</span> <span class="sc">/</span> <span class="dv">200</span>, <span class="at">P_W_given_D =</span> <span class="dv">90</span> <span class="sc">/</span> <span class="dv">210</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">product =</span> (<span class="dv">210</span> <span class="sc">/</span> <span class="dv">500</span>) <span class="sc">*</span> (<span class="dv">200</span> <span class="sc">/</span> <span class="dv">500</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        P_D         P_W   P_D_and_W    P_D_or_W P_D_given_W P_W_given_D 
  0.4200000   0.4000000   0.1800000   0.6400000   0.4500000   0.4285714 
    product 
  0.1680000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>damaged <span class="ot">&lt;-</span> <span class="dv">1000</span> <span class="sc">*</span> <span class="fl">0.05</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>others <span class="ot">&lt;-</span> <span class="dv">1000</span> <span class="sc">-</span> damaged</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>tree <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">damage_flag =</span> damaged <span class="sc">*</span> <span class="fl">0.80</span>, <span class="at">damage_no_flag =</span> damaged <span class="sc">*</span> <span class="fl">0.20</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">other_flag =</span> others <span class="sc">*</span> <span class="fl">0.10</span>, <span class="at">other_no_flag =</span> others <span class="sc">*</span> <span class="fl">0.90</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>tree</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   damage_flag damage_no_flag     other_flag  other_no_flag 
            40             10             95            855 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>p_flag <span class="ot">&lt;-</span> <span class="fu">unname</span>(tree[<span class="st">"damage_flag"</span>] <span class="sc">/</span> (tree[<span class="st">"damage_flag"</span>] <span class="sc">+</span> tree[<span class="st">"other_flag"</span>]))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>p_no_flag <span class="ot">&lt;-</span> <span class="fu">unname</span>(tree[<span class="st">"damage_no_flag"</span>] <span class="sc">/</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                      (tree[<span class="st">"damage_no_flag"</span>] <span class="sc">+</span> tree[<span class="st">"other_no_flag"</span>]))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">p_flag =</span> p_flag, <span class="at">p_no_flag =</span> p_no_flag,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">gain_flag =</span> <span class="dv">60</span> <span class="sc">*</span> p_flag, <span class="at">gain_no_flag =</span> <span class="dv">60</span> <span class="sc">*</span> p_no_flag,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">net_flag =</span> <span class="dv">60</span> <span class="sc">*</span> p_flag <span class="sc">-</span> <span class="dv">4</span>, <span class="at">net_no_flag =</span> <span class="dv">60</span> <span class="sc">*</span> p_no_flag <span class="sc">-</span> <span class="dv">4</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">printed_flag =</span> <span class="dv">60</span> <span class="sc">*</span> <span class="fl">0.25</span>, <span class="at">printed_no_flag =</span> <span class="dv">60</span> <span class="sc">*</span> <span class="fl">0.02</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         p_flag       p_no_flag       gain_flag    gain_no_flag        net_flag 
     0.29629630      0.01156069     17.77777778      0.69364162     13.77777778 
    net_no_flag    printed_flag printed_no_flag 
    -3.30635838     15.00000000      1.20000000 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="question-3-expected-value-spread-and-two-variables-17-points" class="level2">
<h2 class="anchored" data-anchor-id="question-3-expected-value-spread-and-two-variables-17-points">Question 3: Expected value, spread, and two variables (17 points)</h2>
<p>An invented example. A founder repairs phones at a stand on campus. Let <span class="math inline">\(R\)</span> be the number of repairs on one morning. Its PMF is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(r\)</span></th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">4</th>
<th style="text-align: right;">7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p_R(r)\)</span></td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.2</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Calculate <span class="math inline">\(E[R]\)</span>. <strong>(2 points)</strong></li>
<li>Calculate (a) <span class="math inline">\(\operatorname{Var}(R)\)</span> and (b) <span class="math inline">\(\operatorname{SD}(R)\)</span>. <strong>(3 points: 2 + 1)</strong></li>
<li>One repair brings in 25 euros. The stand costs 40 euros per morning. The profit of a morning is <span class="math inline">\(W=25R-40\)</span> euros. Calculate (a) <span class="math inline">\(E[W]\)</span> and (b) <span class="math inline">\(\operatorname{SD}(W)\)</span>. If you could not solve parts 1 and 2, use <span class="math inline">\(E[R]=5\)</span> and <span class="math inline">\(\operatorname{SD}(R)=2\)</span>. <strong>(2 points: 1 + 1)</strong></li>
</ol>
<p>The founder also sells phone cases and screen protectors. For one customer, <span class="math inline">\(X=1\)</span> if the customer buys a case and <span class="math inline">\(X=0\)</span> otherwise. <span class="math inline">\(Y=1\)</span> if the customer buys a screen protector and <span class="math inline">\(Y=0\)</span> otherwise. The joint probabilities are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\(Y=0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X=0\)</span></td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.10</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X=1\)</span></td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.20</td>
</tr>
</tbody>
</table>
<ol start="4" type="1">
<li>Calculate the conditional mean <span class="math inline">\(E[Y\mid X=1]\)</span> and interpret it in one sentence. <strong>(1 point)</strong></li>
<li>Calculate <span class="math inline">\(\operatorname{Cov}(X,Y)\)</span> with <span class="math inline">\(E[XY]-E[X]\,E[Y]\)</span>. <strong>(2 points)</strong></li>
<li>The sum <span class="math inline">\(X+Y\)</span> is the number of these two products (case and screen protector) that one customer buys: 0, 1, or 2. Calculate (a) <span class="math inline">\(E[X+Y]\)</span> and (b) <span class="math inline">\(\operatorname{Var}(X+Y)\)</span>. Use <span class="math inline">\(\operatorname{Var}(X)=0.24\)</span> and <span class="math inline">\(\operatorname{Var}(Y)=0.21\)</span>. If you could not solve part 5, use <span class="math inline">\(\operatorname{Cov}(X,Y)=0.10\)</span>. <strong>(3 points: 1 + 2)</strong></li>
<li>(a) Calculate the correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. If you could not solve part 5, use <span class="math inline">\(\operatorname{Cov}(X,Y)=0.10\)</span>. (b) Interpret its direction and its strength in context. <strong>(2 points: 1 + 1)</strong></li>
<li>The founder says: “A case makes customers buy a screen protector. I will give cases away for free to sell more protectors.” Name one third variable that could cause the correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, and explain how it could do this. <strong>(2 points: 1 + 1)</strong></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer and marking guide
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(E[R]=2(0.3)+4(0.5)+7(0.2)\)</span> (1 point) <span class="math inline">\(=0.6+2.0+1.4=4\)</span> repairs (1 point).</li>
<li>(a) <span class="math inline">\(E[R^2]=4(0.3)+16(0.5)+49(0.2)=1.2+8+9.8=19\)</span> (1 point), so <span class="math inline">\(\operatorname{Var}(R)=19-4^2=3\)</span> (1 point). The definition <span class="math inline">\((2-4)^2(0.3)+(4-4)^2(0.5)+(7-4)^2(0.2)=1.2+0+1.8=3\)</span> gets the same points. (b) <span class="math inline">\(\operatorname{SD}(R)=\sqrt3\approx1.73\)</span> repairs (1 point).</li>
<li>(a) <span class="math inline">\(E[W]=25\times4-40=60\)</span> euros (1 point). (b) <span class="math inline">\(\operatorname{SD}(W)=25\times1.7321\approx43.30\)</span> euros (1 point). The cost of 40 euros does not change the spread. An answer that subtracts 40 from the standard deviation gets no point for (b). With the printed values the results are 85 euros and 50 euros.</li>
<li><span class="math inline">\(P(X=1)=0.20+0.20=0.40\)</span>, so <span class="math inline">\(E[Y\mid X=1]=0\times(0.20/0.40)+1\times(0.20/0.40)=0.50\)</span>. Half of the customers who buy a case also buy a screen protector (1 point, only for the value with its calculation and the sentence). Among all customers the share is <span class="math inline">\(P(Y=1)=0.30\)</span>.</li>
<li><span class="math inline">\(E[X]=0.40\)</span>, <span class="math inline">\(E[Y]=0.10+0.20=0.30\)</span>, and <span class="math inline">\(E[XY]=0.20\)</span>, because <span class="math inline">\(XY=1\)</span> only when both <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are 1. Filled in: <span class="math inline">\(\operatorname{Cov}(X,Y)=0.20-0.40\times0.30\)</span> (1 point) <span class="math inline">\(=0.08\)</span> (1 point).</li>
<li>(a) <span class="math inline">\(E[X+Y]=0.40+0.30=0.70\)</span> products (1 point). An answer that uses wrong means from part 5 correctly also gets the point. (b) <span class="math inline">\(\operatorname{Var}(X+Y)=0.24+0.21+2\times0.08\)</span> (1 point) <span class="math inline">\(=0.61\)</span> (1 point). With the printed covariance of 0.10 the result is 0.65, which also gets full points. An answer of 0.45, without the covariance term, gets no point for (b). An answer of 0.53, with the covariance added only once, gets 1 point for (b).</li>
<li>(a) <span class="math inline">\(\rho_{XY}=0.08/\sqrt{0.24\times0.21}=0.08/0.2245\approx0.36\)</span> (1 point for the result with its calculation). With the printed covariance of 0.10 the result is 0.45, which also gets the point. (b) The correlation is positive and moderate: customers who buy a case tend to buy a screen protector too (1 point, only if the answer names the direction, the strength, and the two products). Accept “weak to moderate”. With a wrong value from (a), give the point when the direction and the strength fit that value.</li>
<li>A third variable: the customer has a new phone (1 point). A customer with a new phone wants to protect it and buys both products. Then a free case for other customers does not sell more protectors (1 point). Accept any third variable that can reasonably make both purchases more likely, for example an expensive phone or a careful customer, with the explanation. A third variable without the explanation gets 1 point.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>r_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">7</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>r_probs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="fl">0.5</span>, <span class="fl">0.2</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>mean_r <span class="ot">&lt;-</span> <span class="fu">sum</span>(r_values <span class="sc">*</span> r_probs)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>var_r <span class="ot">&lt;-</span> <span class="fu">sum</span>(r_values<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> r_probs) <span class="sc">-</span> mean_r<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">sum_of_probs =</span> <span class="fu">sum</span>(r_probs), <span class="at">mean =</span> mean_r,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_of_squares =</span> <span class="fu">sum</span>(r_values<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> r_probs),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">var =</span> var_r, <span class="at">sd =</span> <span class="fu">sqrt</span>(var_r),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_profit =</span> <span class="dv">25</span> <span class="sc">*</span> mean_r <span class="sc">-</span> <span class="dv">40</span>, <span class="at">sd_profit =</span> <span class="dv">25</span> <span class="sc">*</span> <span class="fu">sqrt</span>(var_r))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sum_of_probs            mean mean_of_squares             var              sd 
       1.000000        4.000000       19.000000        3.000000        1.732051 
    mean_profit       sd_profit 
      60.000000       43.301270 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>joint <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.10</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"X=0"</span>, <span class="st">"X=1"</span>), <span class="fu">c</span>(<span class="st">"Y=0"</span>, <span class="st">"Y=1"</span>)))</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>p_x1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(joint[<span class="st">"X=1"</span>, ])</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>p_y1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(joint[, <span class="st">"Y=1"</span>])</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>cov_xy <span class="ot">&lt;-</span> joint[<span class="st">"X=1"</span>, <span class="st">"Y=1"</span>] <span class="sc">-</span> p_x1 <span class="sc">*</span> p_y1</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>var_x <span class="ot">&lt;-</span> p_x1 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_x1)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>var_y <span class="ot">&lt;-</span> p_y1 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_y1)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">sum =</span> <span class="fu">sum</span>(joint), <span class="at">E_X =</span> p_x1, <span class="at">E_Y =</span> p_y1,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">E_Y_given_X1 =</span> joint[<span class="st">"X=1"</span>, <span class="st">"Y=1"</span>] <span class="sc">/</span> p_x1,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">cov =</span> cov_xy, <span class="at">var_x =</span> var_x, <span class="at">var_y =</span> var_y,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_sum =</span> p_x1 <span class="sc">+</span> p_y1, <span class="at">var_sum =</span> var_x <span class="sc">+</span> var_y <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> cov_xy,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">var_sum_printed =</span> var_x <span class="sc">+</span> var_y <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fl">0.10</span>,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">correlation =</span> cov_xy <span class="sc">/</span> <span class="fu">sqrt</span>(var_x <span class="sc">*</span> var_y),</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">correlation_printed =</span> <span class="fl">0.10</span> <span class="sc">/</span> <span class="fu">sqrt</span>(var_x <span class="sc">*</span> var_y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                sum                 E_X                 E_Y        E_Y_given_X1 
          1.0000000           0.4000000           0.3000000           0.5000000 
                cov               var_x               var_y            mean_sum 
          0.0800000           0.2400000           0.2100000           0.7000000 
            var_sum     var_sum_printed         correlation correlation_printed 
          0.6100000           0.6500000           0.3563483           0.4454354 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="question-4-a-normal-model-and-the-precision-of-a-sample-mean-13-points" class="level2">
<h2 class="anchored" data-anchor-id="question-4-a-normal-model-and-the-precision-of-a-sample-mean-13-points">Question 4: A normal model and the precision of a sample mean (13 points)</h2>
<p>An invented example. A founder repairs laptops. A courier collects the repaired laptops. Two models describe the times in her business:</p>
<ul>
<li><span class="math inline">\(X\sim U(15,40)\)</span> is the number of minutes between the founder’s call and the arrival of the courier.</li>
<li><span class="math inline">\(Y\sim N(120,8^2)\)</span> is the number of minutes that one repair takes. The standard deviation is 8 minutes.</li>
</ul>
<p>These values of the standard normal distribution are given for the whole question:</p>
<p><span class="math display">\[
P(Z\le1.0)=0.8413,\qquad P(Z\le1.5)=0.9332,\qquad
P(Z\le2.0)=0.9772,\qquad z_{0.90}=1.2816.
\]</span></p>
<ol type="1">
<li>Calculate <span class="math inline">\(P(22&lt;X&lt;32)\)</span>. <strong>(1 point)</strong></li>
<li>Calculate <span class="math inline">\(P(Y\le132)\)</span>. <strong>(2 points)</strong></li>
<li>Calculate <span class="math inline">\(P(Y\le112)\)</span>. <strong>(2 points)</strong></li>
<li>The founder wants to promise her customers a maximum repair time. 90% of the repairs should take at most this time. Calculate this time. <strong>(2 points)</strong></li>
</ol>
<p>The founder also looks at her prices. Let <span class="math inline">\(V\)</span> be the price of one repair, with mean <span class="math inline">\(\mu=85\)</span> euros and standard deviation <span class="math inline">\(\sigma=20\)</span> euros. She plans to draw a random sample of <span class="math inline">\(n=100\)</span> repairs from her records of 3,000 repairs.</p>
<ol start="5" type="1">
<li>(a) Calculate the standard deviation of the sample mean. (b) Calculate the probability that the sample mean is above 89 euros. <strong>(3 points: 1 + 2)</strong></li>
<li>State how many repairs the sample must contain so that the standard deviation of the sample mean is half as large as in part 5. <strong>(1 point)</strong></li>
<li>Next year the prices change, and she will estimate the new mean price from a sample. She wants a margin of error of at most 5 euros at the 95% level. Use <span class="math inline">\(\sigma=20\)</span> euros as a planning value. Calculate the sample size that she needs. <strong>(2 points)</strong></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer and marking guide
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(P(22&lt;X&lt;32)=(32-22)/(40-15)=10/25=0.40\)</span> (1 point for the result with its calculation).</li>
<li><span class="math inline">\(z=(132-120)/8=1.5\)</span> (1 point), so <span class="math inline">\(P(Y\le132)=P(Z\le1.5)=0.9332\)</span> (1 point). Accept 0.933.</li>
<li><span class="math inline">\(z=(112-120)/8=-1.0\)</span> (1 point). The symmetry rule and the complement rule give <span class="math inline">\(P(Z\le-1.0)=P(Z&gt;1.0)=1-0.8413=0.1587\)</span> (1 point). Accept 0.159. An answer of 0.8413 gets 1 point, for the z value.</li>
<li><span class="math inline">\(x=\mu+z\sigma=120+1.2816\times8\)</span> (1 point) <span class="math inline">\(=130.25\)</span> minutes (1 point). She can promise about 130 minutes. Accept 130, 130.3, and 131 minutes when the calculation is shown.</li>
<li>(a) <span class="math inline">\(\operatorname{SD}(\bar V)=\sigma/\sqrt n=20/\sqrt{100}=2\)</span> euros (1 point). (b) By the CLT the sample mean is approximately normal with mean 85 and standard deviation 2, because <span class="math inline">\(n=100\)</span> is large. The draws can be treated as independent, because <span class="math inline">\(100\le0.10\times3{,}000=300\)</span>. <span class="math inline">\(z=(89-85)/2=2.0\)</span> (1 point), so <span class="math inline">\(P(\bar V&gt;89)\approx1-0.9772=0.0228\)</span> (1 point). Accept 0.023. An answer that divides by <span class="math inline">\(\sigma=20\)</span> instead of this standard deviation gets 0 points for (b). An answer that uses a wrong standard deviation from (a) in the correct way gets the point for the z value. It also gets the second point when the probability fits this z value, for example “almost 0” for a z value far above 2.0.</li>
<li>The sample must contain 400 repairs (1 point). The standard deviation of the sample mean falls with the square root of the sample size. To halve it, she needs four times as many repairs: <span class="math inline">\(20/\sqrt{400}=1\)</span> euro. An answer of 200 repairs gets no point.</li>
<li><span class="math inline">\(n\ge(1.96\times20/5)^2=7.84^2\)</span> (1 point) <span class="math inline">\(\approx61.47\)</span>, so she needs 62 repairs (1 point). Always round up. An answer of 61 gets 1 point.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">uniform =</span> (<span class="dv">32</span> <span class="sc">-</span> <span class="dv">22</span>) <span class="sc">/</span> (<span class="dv">40</span> <span class="sc">-</span> <span class="dv">15</span>),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_132 =</span> <span class="fu">pnorm</span>(<span class="dv">132</span>, <span class="at">mean =</span> <span class="dv">120</span>, <span class="at">sd =</span> <span class="dv">8</span>),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_112 =</span> <span class="fu">pnorm</span>(<span class="dv">112</span>, <span class="at">mean =</span> <span class="dv">120</span>, <span class="at">sd =</span> <span class="dv">8</span>),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">percentile_90 =</span> <span class="fu">qnorm</span>(<span class="fl">0.90</span>, <span class="at">mean =</span> <span class="dv">120</span>, <span class="at">sd =</span> <span class="dv">8</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">by_hand_90 =</span> <span class="dv">120</span> <span class="sc">+</span> <span class="fl">1.2816</span> <span class="sc">*</span> <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      uniform         p_132         p_112 percentile_90    by_hand_90 
    0.4000000     0.9331928     0.1586553   130.2524125   130.2528000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sd_mean <span class="ot">&lt;-</span> <span class="dv">20</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">100</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">sd_of_sample_mean =</span> sd_mean, <span class="at">z =</span> (<span class="dv">89</span> <span class="sc">-</span> <span class="dv">85</span>) <span class="sc">/</span> sd_mean,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_mean_above_89 =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">89</span>, <span class="at">mean =</span> <span class="dv">85</span>, <span class="at">sd =</span> sd_mean),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by_hand =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.9772</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_of_sample_mean_n_400 =</span> <span class="dv">20</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">400</span>),</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_needed =</span> (<span class="fl">1.96</span> <span class="sc">*</span> <span class="dv">20</span> <span class="sc">/</span> <span class="dv">5</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">n_rounded_up =</span> <span class="fu">ceiling</span>((<span class="fl">1.96</span> <span class="sc">*</span> <span class="dv">20</span> <span class="sc">/</span> <span class="dv">5</span>)<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      sd_of_sample_mean                       z         p_mean_above_89 
             2.00000000              2.00000000              0.02275013 
                by_hand sd_of_sample_mean_n_400                n_needed 
             0.02280000              1.00000000             61.46560000 
           n_rounded_up 
            62.00000000 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="question-5-a-mean-test-in-five-steps-and-r-output-14-points" class="level2">
<h2 class="anchored" data-anchor-id="question-5-a-mean-test-in-five-steps-and-r-output-14-points">Question 5: A mean test in five steps, and R output (14 points)</h2>
<p>An invented example. A founder runs an online shop. The shop covers its costs when the mean order value is 60 euros. Last year the shop had 2,400 orders. She drew a simple random sample of 121 of these orders, without replacement. The variable <code>order_value</code> is the value of an order in euros. The sample has a mean of 64.60 euros and a standard deviation of <span class="math inline">\(s=22.00\)</span> euros.</p>
<ol type="1">
<li>State (a) in words what the parameter <span class="math inline">\(\mu\)</span> stands for in this question and (b) the estimate of <span class="math inline">\(\mu\)</span> with its unit. <strong>(2 points: 1 + 1)</strong></li>
<li>Test at the 5% level whether the mean order value differs from 60 euros. Give all five steps of the testing procedure. The critical value is on the formula sheet. <strong>(7 points: 1 + 1 + 1 + 2 + 2)</strong></li>
</ol>
<p>This year she drew a new simple random sample of 100 of the 2,600 orders that the shop has had so far this year. Its standard deviation is 24.00 euros. She ran the same test in R on these orders. This is the output:</p>
<pre class="text"><code>    One Sample t-test

data:  order_value
t = 2.6667, df = 99, p-value = 0.008949
alternative hypothesis: true mean is not equal to 60
95 percent confidence interval:
 61.63788 71.16212
sample estimates:
mean of x 
     66.4 </code></pre>
<ol start="3" type="1">
<li>Interpret the p-value of 0.008949 in one or two sentences. <strong>(2 points)</strong></li>
<li>The output also shows a 95% confidence interval. Show with a calculation how R found the two ends of this interval. <strong>(1 point)</strong></li>
<li>The founder will rent a larger storage room only if the mean order value of this year is above 60 euros. Write your advice to her in two or three sentences. (a) Give a decision and support it with both ends of the interval. (b) Name one limit of these data, that is, one thing that they cannot tell her. <strong>(2 points: 1 + 1)</strong></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer and marking guide
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>(a) <span class="math inline">\(\mu\)</span> is the mean order value of all 2,400 orders of last year (1 point). No point for “the mean of the sample”. (b) The estimate is <span class="math inline">\(\bar x=64.60\)</span> euros (1 point).</p></li>
<li><p>The five steps:</p>
<ul>
<li>Step 1, hypotheses. <span class="math inline">\(H_0:\mu=60\)</span> against <span class="math inline">\(H_1:\mu\ne60\)</span>, with <span class="math inline">\(\alpha=0.05\)</span>, where <span class="math inline">\(\mu\)</span> is the mean order value of all 2,400 orders (part 1) (1 point, only if both hypotheses are correct and two-sided).</li>
<li>Step 2, test statistic. <span class="math inline">\(T=(\bar X-60)/(S/\sqrt n)\)</span>. If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(T\)</span> has the <span class="math inline">\(t_{120}\)</span> distribution. This may be used because <span class="math inline">\(n=121\)</span> is large. Also <span class="math inline">\(121\le0.10\times2{,}400=240\)</span>, so the draws can be treated as independent (1 point for the formula, its distribution, and the condition that <span class="math inline">\(n\)</span> is large).</li>
<li>Step 3, critical value and rejection region. <span class="math inline">\(t_{0.975,\,120}=1.980\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t_{obs}\le-1.980\)</span> or <span class="math inline">\(t_{obs}\ge1.980\)</span> (1 point).</li>
<li>Step 4, observed value. The standard error is <span class="math inline">\(s/\sqrt n=22/\sqrt{121}=2.00\)</span> euros (1 point). <span class="math inline">\(t_{obs}=(64.60-60)/2.00=2.30\)</span> (1 point).</li>
<li>Step 5, conclusion. <span class="math inline">\(2.30\ge1.980\)</span>, so the observed value lies in the rejection region: reject <span class="math inline">\(H_0\)</span> (1 point). At the 5% level we can conclude that the mean order value of all 2,400 orders differs from 60 euros. The positive sign shows that it is above 60 euros (1 point for the sentence in context). “Accept <span class="math inline">\(H_1\)</span>” without a sentence in context loses the last point.</li>
</ul>
<p>A decision that only quotes a p-value, without a critical value and a rejection region, gets no point for step 3 and no point for the decision in step 5. The sentence in context still gets its point.</p></li>
<li><p>If the mean of all 2,600 orders of this year were 60 euros (1 point), a sample mean at least as far from 60 euros as this one, in either direction, would occur in about 0.9% of random samples (1 point). A sentence such as “the probability that <span class="math inline">\(H_0\)</span> is true is 0.9%” gets 0 points for the whole part.</p></li>
<li><p>The standard error is <span class="math inline">\(24.00/\sqrt{100}=2.40\)</span> euros. With <span class="math inline">\(df=99\)</span> the closest listed value is <span class="math inline">\(t_{0.975,\,100}=1.984\)</span>, so <span class="math inline">\(66.40\pm1.984\times2.40=66.40\pm4.76\)</span>. The interval runs from 61.64 to 71.16 euros (1 point for the two ends with the calculation). Small differences from the R output come from the rounded critical value.</p></li>
<li><p>A model answer: “Rent the room, because both ends of the interval, 61.64 and 71.16 euros, are above 60 euros. At the lower end the mean is 1.64 euros above 60, about 3% of that value. The data describe the orders of this year so far and do not show that later orders will have the same values.” (a) 1 point for a decision that follows from the interval, supported with both ends, or with the low end, and the numbers. (b) 1 point for one limit of the data. Accepted limits: the data cover only the orders so far, the interval is about the mean and not about single orders, or the test says nothing about the reason for the order values.</p></li>
</ol>
<p>The R code below builds two invented samples with exactly the means and the standard deviations of the question. It runs the test of part 2 on the first sample. For the second sample, it prints the output of parts 3 to 5:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>z_values <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">121</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>z_values <span class="ot">&lt;-</span> (z_values <span class="sc">-</span> <span class="fu">mean</span>(z_values)) <span class="sc">/</span> <span class="fu">sd</span>(z_values)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>order_value <span class="ot">&lt;-</span> <span class="fl">64.6</span> <span class="sc">+</span> <span class="dv">22</span> <span class="sc">*</span> z_values</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">n =</span> <span class="fu">length</span>(order_value), <span class="at">mean =</span> <span class="fu">mean</span>(order_value), <span class="at">sd =</span> <span class="fu">sd</span>(order_value),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">standard_error =</span> <span class="fu">sd</span>(order_value) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(order_value)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             n           mean             sd standard_error 
         121.0           64.6           22.0            2.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(order_value, <span class="at">mu =</span> <span class="dv">60</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  order_value
t = 2.3, df = 120, p-value = 0.02318
alternative hypothesis: true mean is not equal to 60
95 percent confidence interval:
 60.64014 68.55986
sample estimates:
mean of x 
     64.6 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fl">64.6</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> <span class="fl">1.980</span> <span class="sc">*</span> <span class="dv">2</span>   <span class="co"># the interval by hand with the sheet value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 60.64 68.56</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>z_values <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>z_values <span class="ot">&lt;-</span> (z_values <span class="sc">-</span> <span class="fu">mean</span>(z_values)) <span class="sc">/</span> <span class="fu">sd</span>(z_values)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>order_value <span class="ot">&lt;-</span> <span class="fl">66.4</span> <span class="sc">+</span> <span class="dv">24</span> <span class="sc">*</span> z_values   <span class="co"># the new sample of this year</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">n =</span> <span class="fu">length</span>(order_value), <span class="at">mean =</span> <span class="fu">mean</span>(order_value), <span class="at">sd =</span> <span class="fu">sd</span>(order_value),</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">standard_error =</span> <span class="fu">sd</span>(order_value) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(order_value)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             n           mean             sd standard_error 
         100.0           66.4           24.0            2.4 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(order_value, <span class="at">mu =</span> <span class="dv">60</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  order_value
t = 2.6667, df = 99, p-value = 0.008949
alternative hypothesis: true mean is not equal to 60
95 percent confidence interval:
 61.63788 71.16212
sample estimates:
mean of x 
     66.4 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fl">66.4</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> <span class="fl">1.984</span> <span class="sc">*</span> <span class="fl">2.4</span>   <span class="co"># the interval by hand with the sheet value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 61.6384 71.1616</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="question-6-an-interval-and-a-test-for-a-proportion-two-errors-and-power-22-points" class="level2">
<h2 class="anchored" data-anchor-id="question-6-an-interval-and-a-test-for-a-proportion-two-errors-and-power-22-points">Question 6: An interval and a test for a proportion, two errors, and power (22 points)</h2>
<p>An invented example. A founder sells a coffee subscription. New customers start with a trial month. In her industry, 20% of trial customers switch to a paid subscription. She wants to know whether her own share differs from 20%. She drew 100 trial customers at random from the list of all her 1,500 trial customers of last year. Of these 100, 26 switched to a paid subscription. Let <span class="math inline">\(p\)</span> be the share of customers who switched to a paid subscription among all 1,500 trial customers of last year.</p>
<ol type="1">
<li>A friend suggests a faster way: print a QR code for a short survey on the next 100 coffee bags that she ships, and use the answers that come in. (a) Name this sampling method. (b) Explain why the founder’s random draw from the list of trial customers is the better choice for her question. Name one weakness of the survey and one strength of the random draw. <strong>(3 points: 1 + 2)</strong></li>
<li>Construct a 95% confidence interval for <span class="math inline">\(p\)</span>, and use it to answer the question whether her share differs from 20%. Write down the formula of the interval, the interval, and your conclusion with an explanation. Give the five parts. <strong>(7 points: 2 + 1 + 2 + 1 + 1)</strong></li>
<li>Test at the 5% level whether her share differs from 20%. Give all five steps of the testing procedure. The critical value is on the formula sheet. <strong>(7 points: 1 + 1 + 1 + 2 + 2)</strong></li>
<li>Describe (a) a Type I error and (b) a Type II error for the test of part 3, in the context of the founder. <strong>(2 points: 1 + 1)</strong></li>
<li>(a) State which of the two errors is possible after the decision of your test in part 3. (b) Name one change to the study that raises the power while the significance level stays at 5%. <strong>(2 points: 1 + 1)</strong></li>
<li>Your interval and your test use different values of <span class="math inline">\(p\)</span> to calculate the standard deviation in the denominator. Explain in one sentence why. <strong>(1 point)</strong></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer and marking guide
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>(a) A voluntary-response sample (1 point). Accept “convenience sample”. (b) Weakness of the survey: the customers who scan the code decide themselves to answer. They can differ from the other customers in a systematic way, for example because they like the coffee more. Also, the bags go to the current customers and not to all trial customers of last year (1 point for either of the two weaknesses). Strength of the random draw: every trial customer on the list has the same chance to be selected, so the result describes all 1,500 (1 point). No point for “the survey is too small” or “100 is not enough”.</p></li>
<li><p>The five parts:</p>
<ul>
<li>Part 1, formula. <span class="math inline">\(\widehat P\pm z_{0.975}\sqrt{\widehat
P(1-\widehat P)/n}\)</span> (1 point). It may be used because <span class="math inline">\(n\hat p=26\)</span> and <span class="math inline">\(n(1-\hat p)=74\)</span> are both at least 10 (1 point).</li>
<li>Part 2, given values. 26 of <span class="math inline">\(n=100\)</span>, so <span class="math inline">\(\hat p=0.26\)</span>. The confidence level is 95%, so <span class="math inline">\(z_{0.975}=1.96\)</span> (1 point).</li>
<li>Part 3, calculations. Standard error <span class="math inline">\(\sqrt{0.26\times0.74/100}=\sqrt{0.001924}\approx0.0439\)</span> (1 point). Margin of error <span class="math inline">\(1.96\times0.0439\approx0.086\)</span> (1 point).</li>
<li>Part 4, interval. <span class="math inline">\((0.26-0.086,\ 0.26+0.086)=(0.174,\ 0.346)\)</span> (1 point).</li>
<li>Part 5, conclusion. The value 0.20 lies inside the interval. At the 5% level she cannot conclude that her share differs from the 20% of the industry. This is not proof that her share is 20%: the interval also contains shares up to 34.6% (1 point for “0.20 is inside, so she cannot conclude a difference”). The words “her share is 20%” lose this point.</li>
</ul>
<p>An interval with <span class="math inline">\(\sqrt{0.20\times0.80/100}=0.04\)</span> instead of the standard error loses the first point of part 3. Give the later points when the calculation is correct with this value.</p></li>
<li><p>The five steps:</p>
<ul>
<li>Step 1, hypotheses. <span class="math inline">\(H_0:p=0.20\)</span> against <span class="math inline">\(H_1:p\ne0.20\)</span>, with <span class="math inline">\(\alpha=0.05\)</span>, where <span class="math inline">\(p\)</span> is the share of all 1,500 trial customers of last year who switched to a paid subscription (1 point, only if both hypotheses are correct and two-sided).</li>
<li>Step 2, test statistic. <span class="math inline">\(Z=(\widehat P-0.20)/\sqrt{0.20\times0.80/100}\)</span>. If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(Z\)</span> is approximately <span class="math inline">\(N(0,1)\)</span>, because <span class="math inline">\(np_0=20\)</span> and <span class="math inline">\(n(1-p_0)=80\)</span> are both at least 10 (1 point for the formula, its distribution, and the condition).</li>
<li>Step 3, critical value and rejection region. <span class="math inline">\(z_{0.975}=1.96\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(z_{obs}\le-1.96\)</span> or <span class="math inline">\(z_{obs}\ge1.96\)</span> (1 point).</li>
<li>Step 4, observed value. The standard deviation under <span class="math inline">\(H_0\)</span> is <span class="math inline">\(\operatorname{SD}_0(\widehat P)=\sqrt{0.20\times0.80/100}
=\sqrt{0.0016}=0.04\)</span> (1 point). <span class="math inline">\(z_{obs}=(0.26-0.20)/0.04=1.50\)</span> (1 point).</li>
<li>Step 5, conclusion. <span class="math inline">\(-1.96&lt;1.50&lt;1.96\)</span>, so the observed value does not lie in the rejection region: do not reject <span class="math inline">\(H_0\)</span> (1 point). At the 5% level she cannot conclude that her share differs from the 20% of the industry (1 point for the sentence in context). “Accept <span class="math inline">\(H_0\)</span>” or “her share is 20%” loses this point.</li>
</ul>
<p>The test and the interval of part 2 agree: 0.20 lies inside <span class="math inline">\((0.174,\ 0.346)\)</span>, and <span class="math inline">\(|1.50|&lt;1.96\)</span>. An answer that uses <span class="math inline">\(\sqrt{0.26\times0.74/100}\)</span> in step 4 loses the first point of step 4. Give the later points when the calculation is correct with this value.</p></li>
<li><p>(a) Type I error: the test concludes that her share differs from 20%, but in truth it is 20% (1 point). (b) Type II error: the test does not conclude that her share differs from 20%, but in truth it differs (1 point). A definition without her share and the 20% gets 1 point for the two errors together.</p></li>
<li><p>(a) The test of part 3 did not reject <span class="math inline">\(H_0\)</span>, so only a Type II error is possible (1 point). With a wrong decision in part 3, give the point when the error fits that decision. (b) A larger sample (1 point). Not accepted: “a larger true difference from 20%”, because she cannot choose it. Not accepted: “less variation in the data”, because the spread of a 0/1 variable depends only on <span class="math inline">\(p\)</span>. Not accepted: “a larger significance level”, because the question keeps it at 5%.</p></li>
<li><p>The test calculates as if <span class="math inline">\(H_0\)</span> were true, so it uses <span class="math inline">\(p_0=0.20\)</span>. The interval has no claimed value for <span class="math inline">\(p\)</span>, so it uses the estimate <span class="math inline">\(\hat p=0.26\)</span> (1 point).</p></li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>n_trial <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>p_hat <span class="ot">&lt;-</span> <span class="dv">26</span> <span class="sc">/</span> n_trial</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>standard_error <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">/</span> n_trial)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">successes =</span> n_trial <span class="sc">*</span> p_hat, <span class="at">failures =</span> n_trial <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat),</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_hat =</span> p_hat, <span class="at">standard_error =</span> standard_error,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">margin =</span> <span class="fl">1.96</span> <span class="sc">*</span> standard_error,</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> p_hat <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> standard_error,</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">upper =</span> p_hat <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> standard_error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     successes       failures          p_hat standard_error         margin 
   26.00000000    74.00000000     0.26000000     0.04386342     0.08597231 
         lower          upper 
    0.17402769     0.34597231 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>p_null <span class="ot">&lt;-</span> <span class="fl">0.20</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>sd_under_H0 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(p_null <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_null) <span class="sc">/</span> n_trial)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>z_obs <span class="ot">&lt;-</span> (p_hat <span class="sc">-</span> p_null) <span class="sc">/</span> sd_under_H0</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">sd_under_H0 =</span> sd_under_H0, <span class="at">z_obs =</span> z_obs,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">critical_value =</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fu">abs</span>(z_obs)))   <span class="co"># the test of part 3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sd_under_H0          z_obs critical_value        p_value 
     0.0400000      1.5000000      1.9599640      0.1336144 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="question-7-an-answer-of-an-ai-assistant-about-a-regression-row-9-points" class="level2">
<h2 class="anchored" data-anchor-id="question-7-an-answer-of-an-ai-assistant-about-a-regression-row-9-points">Question 7: An answer of an AI assistant about a regression row (9 points)</h2>
<p>An invented example. An accelerator programme has data on 1,200 former participants. A regression has the monthly revenue of the venture, in thousands of euros, as the outcome. The predictor is the number of mentoring hours per week. The row below is a shortened version of the R output. The last column shows the 95% confidence interval for the coefficient. This interval comes from a separate R command.</p>
<pre class="text"><code>                 Estimate  Std. Error  t value  Pr(&gt;|t|)  95% CI
mentoring_hours     0.75       0.30       2.50     0.0126  [0.16, 1.34]</code></pre>
<p>A founder gave this row to an AI assistant and asked: “What does this row tell me? Should I book more mentoring hours?” The AI answered:</p>
<blockquote class="blockquote">
<p>“The p-value of 0.0126 means that there is only a 1.26% probability that the true coefficient is zero. The p-value is below 0.05, so the link between mentoring and revenue is strong and important for your business. Mentoring causes higher revenue: if you book two more hours per week, your revenue will rise by 1,500 euros per month.”</p>
</blockquote>
<ol type="1">
<li>Interpret the estimate of 0.75 in one sentence. Name the group, the difference in mentoring hours that the estimate refers to, and the revenue with its unit. <strong>(2 points)</strong></li>
<li>Assess the first sentence of the AI answer. (a) Explain why this is not what a p-value means. (b) Write a correct interpretation of the p-value of 0.0126. <strong>(3 points: 1 + 2)</strong></li>
<li>Assess the second sentence of the AI answer. (a) Explain whether a small p-value shows that a link is strong and important. (b) State which numbers of the row describe the size of the link, and what these numbers say. <strong>(2 points: 1 + 1)</strong></li>
<li>Assess the third sentence of the AI answer. (a) Explain whether these data support the claim that mentoring causes higher revenue, and give one other explanation for the link. (b) Write a sentence about two more mentoring hours that the data do support. <strong>(2 points: 1 + 1)</strong></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer and marking guide
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Among the 1,200 former participants, a participant with one more mentoring hour per week had on average 0.75 thousand euros (750 euros) more monthly revenue. Give 1 point for the size with the difference in hours and the unit (750 euros of monthly revenue per mentoring hour per week). Give 1 point for the wording as a comparison of participants in this group. An answer with “causes” or “will raise” loses the second point.</li>
<li>(a) A p-value is calculated under the assumption that the true coefficient is zero. It is not the probability that this assumption is true (1 point). (b) “If the true coefficient were zero (1 point), an estimate at least 2.5 standard errors from zero, in either direction, would occur in about 1.3% of samples” (1 point).</li>
<li>(a) No.&nbsp;A small p-value shows that the estimate is clearly different from zero. It does not show that the link is strong or important (1 point). (b) The size is the estimate with its interval: 750 euros more monthly revenue per mentoring hour, with plausible values from 160 to 1,340 euros. Whether this is important depends on the revenue and the costs of the venture (1 point for the estimate or the interval, with the unit).</li>
<li>(a) No.&nbsp;The row shows an association. Nobody assigned the mentoring hours at random. The participants chose their hours themselves. One other explanation: ventures that do well may book more mentoring, or founders with more drive both book more mentoring and earn more revenue (1 point, only for “no” with one concrete other explanation). (b) “Participants with two more mentoring hours per week had on average 1,500 euros more monthly revenue. The row does not show what happens to your revenue when you book more hours” (1 point, the first sentence is enough).</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">t_value =</span> <span class="fl">0.75</span> <span class="sc">/</span> <span class="fl">0.30</span>,</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fl">2.50</span>, <span class="at">df =</span> <span class="dv">1200</span> <span class="sc">-</span> <span class="dv">2</span>),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> <span class="fl">0.75</span> <span class="sc">-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">1200</span> <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="fl">0.30</span>,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">upper =</span> <span class="fl">0.75</span> <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">1200</span> <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="fl">0.30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  t_value   p_value     lower     upper 
2.5000000 0.0125522 0.1614162 1.3385838 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p>The seven questions have 100 points together. When you practise, complete the exam before you open the model answers. Then use the marking guide to see where you lost points: in a calculation, in an interpretation, in a unit, in a condition, or in a decision.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/formula-sheet.html" class="pagination-link" aria-label="QM Basic Formula Sheet">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">QM Basic Formula Sheet</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../intermediate/overview.html" class="pagination-link" aria-label="QM Intermediate: Course overview">
        <span class="nav-page-text">QM Intermediate: Course overview</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>