<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial 1: Evidence and probability foundations – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/b04-conditioning-bayes-independence.html" rel="next">
<link href="../basic/b03-discrete-distributions.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0373dafead96411fe286b8dec0b5ee25.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/t01-exam-prep.html"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and a first look at regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Hypothesis tests, errors, and power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-the-tutorial" id="toc-in-the-tutorial" class="nav-link" data-scroll-target="#in-the-tutorial">In the tutorial</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/t01-exam-prep.html"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b-ep01" class="quarto-section-identifier"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Tutorial 1, you can</span></p>
<ul>
<li>classify variables, and tell sampling variability and selection bias apart</li>
<li>distinguish data, events, random variables, and distributions</li>
<li>apply probability rules to the Shark Tank record-selection experiment</li>
<li>calculate and interpret a Bernoulli PMF, CDF, and expectation</li>
<li>calculate a variance and standard deviation from a small PMF</li>
<li>calculate the expected value and standard deviation of a shifted and rescaled variable <span class="math inline">\(aX+b\)</span></li>
<li>calculate a mean, a standard deviation, the quartiles, and the interquartile range from a frequency table</li>
<li>describe a random experiment by its sample space, and write events in set notation</li>
<li>calculate probabilities from a CDF table and recover the PMF from the CDF</li>
<li>compare two options by their expected values and standard deviations</li>
<li>write a short interpretation of supplied R output</li>
<li>find and correct the errors in an AI answer</li>
<li>read a histogram by hand and find the interval that contains the median.</li>
</ul>
</div>
<p>Tutorials are exam preparation sessions. Every task below follows the format of the final exam. You first try each task in pairs. You may use AI for this, following Attempt, Ask, Verify, Explain. Then the class discusses the solution together.</p>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p><span class="time-budget">Total preparation time: about 15 minutes.</span></p>
<p>Bring your after-class work from Lectures 1 to 3. Without looking at the chapters again, complete these definitions:</p>
<ol type="1">
<li>An observational unit is …</li>
<li>An event is …</li>
<li>A random variable is …</li>
<li>A PMF is …</li>
<li>The variance of a random variable averages …</li>
<li>The lower quartile <span class="math inline">\(Q_1\)</span> and the upper quartile <span class="math inline">\(Q_3\)</span> are …</li>
</ol>
<p>Use the <a href="../basic/formula-sheet.html">formula sheet</a> up to and including Lecture 3.</p>
<p>Review <a href="../resources/math-refresher.html#sets-and-event-notation">Mathematics Refresher: sets and event notation</a> and <a href="../resources/math-refresher.html#summation-notation">summation notation</a> if the notation is difficult for you.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your preparation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>An observational unit is the unit that one row of the data describes.</li>
<li>An event is a specified subset of the sample space.</li>
<li>A random variable is a numerical measurement of the outcome: a fixed rule that turns each outcome into a number.</li>
<li>A PMF assigns probability <span class="math inline">\(P(X=x)\)</span> to each value in the support of a discrete random variable. Its masses are non-negative and sum to 1.</li>
<li>Variance averages squared deviations from the variable’s mean: <span class="math inline">\(\operatorname{Var}(X)=E\!\left[(X-E[X])^2\right]\)</span>.</li>
<li>At least one quarter of the observations are at or below <span class="math inline">\(Q_1\)</span>, and at least three quarters are at or above it. At least three quarters of the observations are at or below <span class="math inline">\(Q_3\)</span>, and at least one quarter are at or above it. The difference <span class="math inline">\(Q_3-Q_1\)</span> is the interquartile range.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="in-the-tutorial" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-the-tutorial">In the tutorial</h2>
<p>Attempt each task before opening its answer. A complete written answer names the quantity and shows the calculation. It reports the value and units and interprets the value in context. It also states one important limit of the model or of the measurement.</p>
<p>Tasks 1 to 8 and Task 11 belong to the tutorial. Together they take about 76 minutes. Tasks 9 and 10 are extra practice for home.</p>
<p>Tasks 1, 3, and 4 and the timed practice after class use the Shark Tank teaching file. Tasks 2 and 5 to 7 use invented examples. Load the file once:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="task-1-data-and-measurement-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-1-data-and-measurement-5-minutes">Task 1: Data and measurement (5 minutes)</h3>
<p><span class="shark-tag">Shark Tank data</span> R reports:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                    rows                  columns                    deals 
            1441.0000000               19.0000000              882.0000000 
         deal_proportion median_description_words 
               0.6120749                5.0000000 </code></pre>
</div>
</div>
<ol type="1">
<li>What is the observational unit?</li>
<li>Verify the deal proportion from 882 deals and 559 non-deals.</li>
<li>Explain why the mean of <code>deal_on_show</code> is a proportion.</li>
<li>Evaluate: “The data contain 1,441 successful companies.”</li>
<li>What exactly does <code>description_words</code> measure?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>One row is one recorded televised pitch. There are <span class="math inline">\(882+559=1441\)</span> records and <span class="math inline">\(882/1441\approx0.612\)</span>, so 61.2% reached an on-air deal. The mean of a 0/1 indicator equals the share coded 1 because its sum counts the 1s. “Successful companies” is incorrect: the outcome is a deal made on the show, not completed funding or later venture performance. Word count describes the written text in the source dataset, not the spoken pitch.</p>
</div>
</div>
</div>
</section>
<section id="task-2-variables-and-samples-6-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-2-variables-and-samples-6-minutes">Task 2: Variables and samples (6 minutes)</h3>
<p>An invented example. A coffee-bar start-up records, for each of 150 orders: <code>order_id</code>, <code>drink</code> (espresso, latte, or tea), <code>cup_size</code> (small, medium, or large), <code>items</code> (the number of items), and <code>amount_eur</code> (the amount paid, in euros).</p>
<ol type="1">
<li>Classify each variable as categorical, ordinal, discrete, continuous, or an identifier.</li>
<li>The founder asks 150 loyalty-card holders whether they would pay more for oat milk. Is the main problem sampling variability or selection bias? Explain in two sentences.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><code>order_id</code> is an identifier, <code>drink</code> is categorical, <code>cup_size</code> is ordinal, <code>items</code> is discrete, and <code>amount_eur</code> is continuous.</li>
<li>The main problem is selection bias. Loyalty-card holders are regular customers who like the bar, so they may be more willing to pay extra than other customers. Asking more card holders would not fix this, because the sample was not drawn at random from all customers.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="task-3-events-and-probability-rules-8-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-3-events-and-probability-rules-8-minutes">Task 3: Events and probability rules (8 minutes)</h3>
<p><span class="shark-tag">Shark Tank data</span> The experiment selects one of the 1,441 records at random, each with the same probability. The two events are defined exactly as in Lecture 2:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span>   <span class="co"># on-air deal</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span>         <span class="co"># late season: Seasons 9-16</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>R reports:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      P_D       P_L P_D_and_L 
0.6120749 0.5093685 0.3504511 </code></pre>
</div>
</div>
<ol type="1">
<li>Define <span class="math inline">\(\Omega\)</span>, and explain the difference between an outcome and the event <span class="math inline">\(D\)</span>.</li>
<li>Translate <span class="math inline">\(D^c\)</span>, <span class="math inline">\(D\cap L\)</span>, and <span class="math inline">\(D\cup L\)</span> into words.</li>
<li>Calculate <span class="math inline">\(P(D^c)\)</span>.</li>
<li>Calculate <span class="math inline">\(P(D\cup L)\)</span> using the addition rule.</li>
<li>Explain why these probabilities do not automatically apply to a future US entrepreneur.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The sample space is the set of 1,441 complete pitch records. One selected record is an outcome, while <span class="math inline">\(D\)</span> is the subset of 882 deal records. The complement is no on-air deal, the intersection is a late-season deal, and the union is late-season, deal, or both. <span class="math inline">\(P(D^c)=1-882/1441=559/1441\approx0.388\)</span>. The union is <span class="math inline">\(P(D)+P(L)-P(D\cap L)\approx0.771\)</span>. To use these probabilities for a future entrepreneur, you need a defined target population and a comparable selection, time period, and outcome.</p>
</div>
</div>
</div>
</section>
<section id="task-4-pmf-cdf-and-expectation-8-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-4-pmf-cdf-and-expectation-8-minutes">Task 4: PMF, CDF, and expectation (8 minutes)</h3>
<p><span class="shark-tag">Shark Tank data</span> Let <span class="math inline">\(X=1\)</span> for an on-air deal and <span class="math inline">\(X=0\)</span> otherwise. Use <span class="math inline">\(p=882/1441\)</span>.</p>
<ol type="1">
<li>Write the PMF and verify that its masses sum to 1.</li>
<li>Write the full piecewise CDF <span class="math inline">\(F_X(a)\)</span>.</li>
<li>Calculate <span class="math inline">\(E[X]\)</span> from the PMF.</li>
<li>Explain why <span class="math inline">\(E[X]\)</span> equals the observed proportion of 1s.</li>
<li>Explain the difference between the random variable <span class="math inline">\(X\)</span> and a realised value <span class="math inline">\(x=1\)</span>.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[
p_X(0)=1-p,\qquad p_X(1)=p,
\]</span></p>
<p>and the masses sum to <span class="math inline">\(1-p+p=1\)</span>.</p>
<p><span class="math display">\[
F_X(a)=
\begin{cases}
0,&amp;a&lt;0,\\
1-p,&amp;0\le a&lt;1,\\
1,&amp;a\ge1.
\end{cases}
\]</span></p>
<p>The expectation is <span class="math inline">\(E[X]=0(1-p)+1p=p\approx0.612\)</span>. Because the indicator contains 882 ones among 1,441 observations, its mean is also <span class="math inline">\(882/1441\)</span>. <span class="math inline">\(X\)</span> is the random variable: a numerical measurement of the outcome, a fixed rule that turns each outcome into a number (1 for a deal, 0 for no deal). <span class="math inline">\(x=1\)</span> is one realised value, the number obtained when the selected pitch has a deal.</p>
</div>
</div>
</div>
</section>
<section id="task-5-variance-from-a-small-pmf-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-5-variance-from-a-small-pmf-10-minutes">Task 5: Variance from a small PMF (10 minutes)</h3>
<p>An invented example. A venture studio models <span class="math inline">\(N\)</span>, the number of investors who make an offer to one of its startups, with the PMF</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(n\)</span></th>
<th style="text-align: right;">0</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p_N(n)\)</span></td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.2</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Calculate <span class="math inline">\(E[N]\)</span>.</li>
<li>Calculate <span class="math inline">\(\operatorname{Var}(N)\)</span> from the definition <span class="math inline">\(E\!\left[(N-E[N])^2\right]\)</span>.</li>
<li>Verify the result with the computational form <span class="math inline">\(E[N^2]-\left(E[N]\right)^2\)</span>.</li>
<li>Report the standard deviation with its unit, and state in one sentence what it measures here.</li>
<li>Each offer costs the studio 3 hours of meetings, and every startup needs 2 hours of preparation. The time spent on one startup is therefore <span class="math inline">\(T=3N+2\)</span> hours. Calculate <span class="math inline">\(E[T]\)</span> and <span class="math inline">\(\operatorname{SD}(T)\)</span>.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(E[N]=0(0.5)+1(0.3)+2(0.2)=0.7\)</span> offers.</p>
<p>Definition form: <span class="math display">\[
\operatorname{Var}(N)=(0-0.7)^2(0.5)+(1-0.7)^2(0.3)+(2-0.7)^2(0.2)
=0.245+0.027+0.338=0.61.
\]</span></p>
<p>Computational form: <span class="math inline">\(E[N^2]=0^2(0.5)+1^2(0.3)+2^2(0.2)=1.1\)</span>, so <span class="math inline">\(\operatorname{Var}(N)=1.1-0.7^2=1.1-0.49=0.61\)</span>. The two methods agree.</p>
<p>The standard deviation is <span class="math inline">\(\sqrt{0.61}\approx0.78\)</span> offers. It measures the typical distance of the realised number of offers from the mean of 0.7, in the original unit (offers), whereas the variance is in squared offers.</p>
<p>Time per startup: use the rules for <span class="math inline">\(aX+b\)</span> with <span class="math inline">\(a=3\)</span> and <span class="math inline">\(b=2\)</span>. <span class="math inline">\(E[T]=3E[N]+2=3\times0.7+2=4.1\)</span> hours. <span class="math inline">\(\operatorname{SD}(T)=|3|\operatorname{SD}(N)\approx3\times0.78=2.34\)</span> hours, more than half of the expected time. The 2 hours of preparation raise the expected time and leave the spread unchanged.</p>
</div>
</div>
</div>
</section>
<section id="task-6-check-the-ai-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-6-check-the-ai-5-minutes">Task 6: Check the AI (5 minutes)</h3>
<p>You asked an AI assistant about the number of offers <span class="math inline">\(N\)</span> in Task 5. It answered:</p>
<blockquote class="blockquote">
<p>“E[N] = 0.7, so most startups get 0.7 offers. The variance is 0.61, so the number of offers typically differs from 0.7 by 0.61 offers.”</p>
</blockquote>
<p>Check the answer sentence by sentence. Find what is wrong and write the corrected answer.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The first sentence is wrong. No startup gets 0.7 offers, because <span class="math inline">\(N\)</span> is a count with the values 0, 1, and 2. The expected value is a probability-weighted average, not the most likely value. The most likely number is 0 offers, with probability 0.5. The second sentence is also wrong. The variance 0.61 is in squared offers. The typical distance from 0.7 is the standard deviation, <span class="math inline">\(\sqrt{0.61}\approx0.78\)</span> offers. Corrected answer: on average a startup gets 0.7 offers, half of the startups get no offer, and the number of offers typically differs from 0.7 by about 0.78 offers.</p>
</div>
</div>
</div>
</section>
<section id="task-7-read-a-histogram-by-hand-7-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-7-read-a-histogram-by-hand-7-minutes">Task 7: Read a histogram by hand (7 minutes)</h3>
<p>An invented example. A venture records the delivery times of 120 orders. A histogram groups them into intervals of 10 minutes, and each bar includes its upper limit. The bar counts, from the first interval (0 to 10 minutes) to the fifth (above 40, up to 50 minutes), are 18, 46, 32, 16, and 8.</p>
<ol type="1">
<li>What does one observation represent, and what is on each axis?</li>
<li>Describe the tallest bar in one full sentence.</li>
<li>Which interval contains the median? Show the cumulative counts.</li>
<li>Describe the shape, and state one thing the histogram cannot tell you.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>One observation is one order. The horizontal axis is the delivery time in minutes and the vertical axis is the number of orders. The tallest bar: 46 orders took more than 10 and at most 20 minutes. With 120 orders the median lies between the 60th and the 61st ordered value. The cumulative counts are 18 and then 18 + 46 = 64, so both values lie in the second interval: the median delivery time is above 10 and at most 20 minutes. The distribution is right-skewed: most orders arrive within 30 minutes and a few take much longer. The histogram cannot say which orders were late or why, and it hides the exact times inside each interval.</p>
</div>
</div>
</div>
</section>
<section id="b-ep01-calculation" class="level3">
<h3 class="anchored" data-anchor-id="b-ep01-calculation">More calculation practice</h3>
<p>Tasks 8 to 11 practise the calculations of Lectures 1 to 3 by hand. Tasks 8 and 11 belong to the tutorial. Do Tasks 9 and 10 in the tutorial if time is left, and otherwise at home. All four tasks use invented examples. You need a simple calculator and the formula sheet.</p>
</section>
<section id="task-8-mean-spread-and-quartiles-from-a-frequency-table-12-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-8-mean-spread-and-quartiles-from-a-frequency-table-12-minutes">Task 8: Mean, spread, and quartiles from a frequency table (12 minutes)</h3>
<p>An invented example. A founder runs an escape room. Groups of 2 to 6 persons book the room for one hour. The table shows the group size of the 40 bookings of last week.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group size (persons)</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
<th style="text-align: right;">5</th>
<th style="text-align: right;">6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of bookings</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">6</td>
</tr>
</tbody>
</table>
<p>Give every booking the same weight, <span class="math inline">\(1/40\)</span>. This is the empirical distribution of Lecture 3, so the relative frequencies work like a PMF.</p>
<ol type="1">
<li>State what one observation is. Calculate the relative frequency of each group size and check that the five values sum to 1.</li>
<li>Calculate the mean group size.</li>
<li>Calculate the variance and the standard deviation of this empirical distribution. Use the variance formula of Lecture 3 with the relative frequencies as weights. This version divides by <span class="math inline">\(n\)</span>. State the unit. Then calculate the sample standard deviation <span class="math inline">\(s\)</span> of Lecture 3, which divides by <span class="math inline">\(n-1\)</span>.</li>
<li>Write down the cumulative counts and find the median.</li>
<li>Find the lower quartile <span class="math inline">\(Q_1\)</span> and the upper quartile <span class="math inline">\(Q_3\)</span> with cumulative counts, as for the median in Lecture 1. Add the counts from the left until the running total first reaches one quarter of the observations. The group size at which this happens is <span class="math inline">\(Q_1\)</span>. Do the same with three quarters for <span class="math inline">\(Q_3\)</span>. Then calculate the interquartile range and interpret it in one sentence.</li>
<li>Compare the mean with the median. What does the comparison say about the shape of the distribution?</li>
</ol>
<p>For these 40 values, R’s <code>quantile()</code> reports the same median and the same quartiles as the rules in parts 4 and 5.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>One observation is one booking. The relative frequencies are <span class="math inline">\(4/40=0.10\)</span>, <span class="math inline">\(12/40=0.30\)</span>, <span class="math inline">\(10/40=0.25\)</span>, <span class="math inline">\(8/40=0.20\)</span>, and <span class="math inline">\(6/40=0.15\)</span>. Their sum is 1.</li>
<li>The mean is <span class="math inline">\(2(0.10)+3(0.30)+4(0.25)+5(0.20)+6(0.15)=0.20+0.90+1.00+1.00+0.90=4.0\)</span> persons. The counts give the same result: <span class="math inline">\((2\times4+3\times12+4\times10+5\times8+6\times6)/40=160/40=4.0\)</span>.</li>
<li>The variance is <span class="math display">\[
(2-4)^2(0.10)+(3-4)^2(0.30)+(4-4)^2(0.25)+(5-4)^2(0.20)+(6-4)^2(0.15)
\]</span> <span class="math display">\[
=0.40+0.30+0+0.20+0.60=1.50.
\]</span> The standard deviation is <span class="math inline">\(\sqrt{1.50}\approx1.22\)</span> persons. A booking typically differs from the mean of 4 persons by about 1.2 persons, which is about 31% of the mean. This variance divides by <span class="math inline">\(n=40\)</span>. The sum of the squared deviations is <span class="math inline">\(40\times1.50=60\)</span>. The sample variance divides it by <span class="math inline">\(n-1=39\)</span>: <span class="math inline">\(s^2=60/39\approx1.54\)</span> and <span class="math inline">\(s\approx1.24\)</span> persons, the value of R’s <code>sd()</code>.</li>
<li>The cumulative counts are 4, 16, 26, 34, and 40. With 40 observations the median is the average of the 20th and the 21st ordered value. The ordered values 17 to 26 all have group size 4, so the median is 4 persons.</li>
<li>One quarter of 40 is 10. The running total first reaches 10 at group size 3, because <span class="math inline">\(16\ge10\)</span>, so <span class="math inline">\(Q_1=3\)</span>. Three quarters of 40 is 30. The running total first reaches 30 at group size 5, because <span class="math inline">\(34\ge30\)</span>, so <span class="math inline">\(Q_3=5\)</span>. The interquartile range is <span class="math inline">\(5-3=2\)</span> persons: the middle half of the bookings lies between 3 and 5 persons. Of the 40 bookings, 16 are at or below 3 persons. That is 40%, more than one quarter, which is why the definition of <span class="math inline">\(Q_1\)</span> says “at least one quarter”.</li>
<li>The mean and the median are both 4 persons, so the two agree. The distribution has no long tail on one side that pulls the mean away from the median.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>group_size <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">times =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">12</span>, <span class="dv">10</span>, <span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(group_size),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">var_divide_n =</span> <span class="fu">mean</span>((group_size <span class="sc">-</span> <span class="fu">mean</span>(group_size))<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sum_of_squares =</span> <span class="fu">sum</span>((group_size <span class="sc">-</span> <span class="fu">mean</span>(group_size))<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">var_divide_n_minus_1 =</span> <span class="fu">var</span>(group_size),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_divide_n_minus_1 =</span> <span class="fu">sd</span>(group_size))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mean         var_divide_n       sum_of_squares 
            4.000000             1.500000            60.000000 
var_divide_n_minus_1  sd_divide_n_minus_1 
            1.538462             1.240347 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(<span class="fu">table</span>(group_size))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 2  3  4  5  6 
 4 16 26 34 40 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(group_size, <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>25% 50% 75% 
  3   4   5 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-9-a-random-experiment-its-sample-space-and-events-10-minutes-extra-practice-for-home" class="level3">
<h3 class="anchored" data-anchor-id="task-9-a-random-experiment-its-sample-space-and-events-10-minutes-extra-practice-for-home">Task 9: A random experiment, its sample space, and events (10 minutes, extra practice for home)</h3>
<p>An invented example. A streetwear start-up sells one hoodie in five sizes: XS, S, M, L, and XL. The random experiment is this: the next order arrives and its size is recorded. The founders use the shares of last year’s orders as probabilities:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Size</th>
<th style="text-align: right;">XS</th>
<th style="text-align: right;">S</th>
<th style="text-align: right;">M</th>
<th style="text-align: right;">L</th>
<th style="text-align: right;">XL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Probability</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.10</td>
</tr>
</tbody>
</table>
<p>Two events matter for the founders. <span class="math inline">\(A\)</span> is the event that the order is for a size up to M, that is XS, S, or M. <span class="math inline">\(B\)</span> is the event that the order is for a standard size, that is S, M, or L. The start-up keeps the standard sizes in stock and makes XS and XL only after a customer orders them.</p>
<ol type="1">
<li>Write down the sample space <span class="math inline">\(\Omega\)</span>. Is L an outcome or an event? What is <span class="math inline">\(\{\text{L}\}\)</span>?</li>
<li>Check that the table is a valid probability model.</li>
<li>Write <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> in set notation, and calculate <span class="math inline">\(P(A)\)</span> and <span class="math inline">\(P(B)\)</span>.</li>
<li>Describe <span class="math inline">\(A^c\)</span> and <span class="math inline">\(B^c\)</span> in words and write them in set notation. Calculate their probabilities with the complement rule.</li>
<li>Write <span class="math inline">\(A\cap B\)</span> and <span class="math inline">\(A\cup B\)</span> in set notation and in words. Calculate <span class="math inline">\(P(A\cup B)\)</span> with the addition rule. Explain why <span class="math inline">\(P(A)+P(B)\)</span> cannot be the answer.</li>
<li>Which size is neither in <span class="math inline">\(A\)</span> nor in <span class="math inline">\(B\)</span>? Calculate its probability from part 5 with the complement rule, and check the result in the table.</li>
<li>State one assumption that the founders make when they use these probabilities for the next order.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(\Omega=\{\text{XS},\text{S},\text{M},\text{L},\text{XL}\}\)</span>. L is an outcome: one complete possible result of the experiment. <span class="math inline">\(\{\text{L}\}\)</span> is an event: the set that contains only this outcome.</li>
<li>Every probability is at least 0, and <span class="math inline">\(0.05+0.20+0.35+0.30+0.10=1\)</span>, so <span class="math inline">\(P(\Omega)=1\)</span>. The five sizes are disjoint, so their probabilities may be added.</li>
<li><span class="math inline">\(A=\{\text{XS},\text{S},\text{M}\}\)</span> and <span class="math inline">\(P(A)=0.05+0.20+0.35=0.60\)</span>. <span class="math inline">\(B=\{\text{S},\text{M},\text{L}\}\)</span> and <span class="math inline">\(P(B)=0.20+0.35+0.30=0.85\)</span>.</li>
<li><span class="math inline">\(A^c=\{\text{L},\text{XL}\}\)</span>: the order is for a size above M. <span class="math inline">\(P(A^c)=1-0.60=0.40\)</span>. <span class="math inline">\(B^c=\{\text{XS},\text{XL}\}\)</span>: the order is for a size that is made only after an order. <span class="math inline">\(P(B^c)=1-0.85=0.15\)</span>. The table gives the same values: <span class="math inline">\(0.30+0.10=0.40\)</span> and <span class="math inline">\(0.05+0.10=0.15\)</span>.</li>
<li><span class="math inline">\(A\cap B=\{\text{S},\text{M}\}\)</span>: the size is up to M and it is a standard size. Its probability is <span class="math inline">\(0.20+0.35=0.55\)</span>. <span class="math inline">\(A\cup B=\{\text{XS},\text{S},\text{M},\text{L}\}\)</span>: the size is up to M, or it is a standard size, or both. The addition rule gives <span class="math inline">\(P(A\cup B)=0.60+0.85-0.55=0.90\)</span>. The sum <span class="math inline">\(P(A)+P(B)=1.45\)</span> is above 1, so it cannot be a probability. It counts the sizes S and M twice.</li>
<li>Only XL. In symbols, <span class="math inline">\((A\cup B)^c=\{\text{XL}\}\)</span>, and the complement rule gives <span class="math inline">\(1-0.90=0.10\)</span>. The table shows the same value for XL.</li>
<li>The probabilities are shares of last year’s orders. They describe the next order only if customers choose sizes in the same way as last year. A new group of customers or a new design of the hoodie could change the shares.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>size_prob <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">XS =</span> <span class="fl">0.05</span>, <span class="at">S =</span> <span class="fl">0.20</span>, <span class="at">M =</span> <span class="fl">0.35</span>, <span class="at">L =</span> <span class="fl">0.30</span>, <span class="at">XL =</span> <span class="fl">0.10</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>size_A <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"XS"</span>, <span class="st">"S"</span>, <span class="st">"M"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>size_B <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"S"</span>, <span class="st">"M"</span>, <span class="st">"L"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>p_A <span class="ot">&lt;-</span> <span class="fu">sum</span>(size_prob[size_A])</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>p_B <span class="ot">&lt;-</span> <span class="fu">sum</span>(size_prob[size_B])</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>p_A_and_B <span class="ot">&lt;-</span> <span class="fu">sum</span>(size_prob[<span class="fu">intersect</span>(size_A, size_B)])</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">total =</span> <span class="fu">sum</span>(size_prob), <span class="at">P_A =</span> p_A, <span class="at">P_B =</span> p_B,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_not_A =</span> <span class="dv">1</span> <span class="sc">-</span> p_A, <span class="at">P_not_B =</span> <span class="dv">1</span> <span class="sc">-</span> p_B,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_A_and_B =</span> p_A_and_B,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_A_or_B =</span> p_A <span class="sc">+</span> p_B <span class="sc">-</span> p_A_and_B,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_neither =</span> <span class="dv">1</span> <span class="sc">-</span> (p_A <span class="sc">+</span> p_B <span class="sc">-</span> p_A_and_B))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    total       P_A       P_B   P_not_A   P_not_B P_A_and_B  P_A_or_B P_neither 
     1.00      0.60      0.85      0.40      0.15      0.55      0.90      0.10 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-10-from-a-cdf-to-probabilities-and-to-the-pmf-10-minutes-extra-practice-for-home" class="level3">
<h3 class="anchored" data-anchor-id="task-10-from-a-cdf-to-probabilities-and-to-the-pmf-10-minutes-extra-practice-for-home">Task 10: From a CDF to probabilities and to the PMF (10 minutes, extra practice for home)</h3>
<p>An invented example. A founder rents out four cargo bikes to students who move house. Let <span class="math inline">\(X\)</span> be the number of bikes that are rented out on a Saturday. Her model for <span class="math inline">\(X\)</span> is given as a CDF:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Threshold <span class="math inline">\(a\)</span></th>
<th style="text-align: right;"><span class="math inline">\(F_X(a)=P(X\le a)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(a&lt;0\)</span></td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(0\le a&lt;1\)</span></td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(1\le a&lt;2\)</span></td>
<td style="text-align: right;">0.20</td>
</tr>
<tr class="even">
<td><span class="math inline">\(2\le a&lt;3\)</span></td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(3\le a&lt;4\)</span></td>
<td style="text-align: right;">0.80</td>
</tr>
<tr class="even">
<td><span class="math inline">\(a\ge4\)</span></td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>State the possible values of <span class="math inline">\(X\)</span>. How does the table show them?</li>
<li>Read <span class="math inline">\(F_X(2)\)</span>, <span class="math inline">\(F_X(2.5)\)</span>, and <span class="math inline">\(F_X(6)\)</span> from the table. Say in words what <span class="math inline">\(F_X(2)\)</span> means.</li>
<li>Calculate <span class="math inline">\(P(X&gt;2)\)</span>, <span class="math inline">\(P(1&lt;X\le3)\)</span>, and <span class="math inline">\(P(1\le X\le3)\)</span>.</li>
<li>Recover the PMF of <span class="math inline">\(X\)</span> from the CDF, and check that it is a valid PMF.</li>
<li>Check your PMF in two ways. Calculate <span class="math inline">\(F_X(3)\)</span> again as a running total, and calculate <span class="math inline">\(P(1\le X\le3)\)</span> again by adding probability masses.</li>
<li>Interpret <span class="math inline">\(p_X(4)\)</span> in one sentence. State one thing that this number cannot tell the founder.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><span class="math inline">\(X\)</span> can take the values 0, 1, 2, 3, and 4. These are the thresholds at which the CDF jumps. Between two of these values the CDF stays flat, because no probability lies there.</p></li>
<li><p><span class="math inline">\(F_X(2)=0.50\)</span>: with probability 0.50, at most two bikes are rented out on a Saturday. <span class="math inline">\(F_X(2.5)=0.50\)</span> as well, because <span class="math inline">\(X\)</span> takes no value between 2 and 2.5. <span class="math inline">\(F_X(6)=1\)</span>, because <span class="math inline">\(X\)</span> is never above 4.</p></li>
<li><p><span class="math inline">\(P(X&gt;2)=1-F_X(2)=1-0.50=0.50\)</span>. <span class="math inline">\(P(1&lt;X\le3)=F_X(3)-F_X(1)=0.80-0.20=0.60\)</span>. The event <span class="math inline">\(1\le X\le3\)</span> includes the value 1. <span class="math inline">\(X\)</span> takes whole numbers only, so this event is the same as <span class="math inline">\(0&lt;X\le3\)</span>, and <span class="math inline">\(P(1\le X\le3)=F_X(3)-F_X(0)=0.80-0.05=0.75\)</span>.</p></li>
<li><p>Each probability mass is the size of the jump of the CDF at that value: <span class="math inline">\(p_X(0)=0.05\)</span>, <span class="math inline">\(p_X(1)=0.20-0.05=0.15\)</span>, <span class="math inline">\(p_X(2)=0.50-0.20=0.30\)</span>, <span class="math inline">\(p_X(3)=0.80-0.50=0.30\)</span>, and <span class="math inline">\(p_X(4)=1-0.80=0.20\)</span>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th style="text-align: right;">0</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p_X(x)\)</span></td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.20</td>
</tr>
</tbody>
</table>
<p>No mass is negative, and <span class="math inline">\(0.05+0.15+0.30+0.30+0.20=1\)</span>.</p></li>
<li><p><span class="math inline">\(F_X(3)=0.05+0.15+0.30+0.30=0.80\)</span>, as in the table. <span class="math inline">\(P(1\le X\le3)=0.15+0.30+0.30=0.75\)</span>, as in part 3.</p></li>
<li><p><span class="math inline">\(p_X(4)=0.20\)</span>: with probability 0.20, on about one Saturday in five, all four bikes are rented out. The number counts rented bikes. It cannot tell how many students asked for a bike on such a day, so it does not show how often a fifth bike would be rented.</p></li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>bike_cdf <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.20</span>, <span class="fl">0.50</span>, <span class="fl">0.80</span>, <span class="dv">1</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>bike_pmf <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">c</span>(<span class="dv">0</span>, bike_cdf))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(bike_pmf) <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">4</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>bike_pmf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   0    1    2    3    4 
0.05 0.15 0.30 0.30 0.20 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">total =</span> <span class="fu">sum</span>(bike_pmf),</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_more_than_2 =</span> <span class="dv">1</span> <span class="sc">-</span> bike_cdf[<span class="dv">3</span>],</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_above_1_to_3 =</span> bike_cdf[<span class="dv">4</span>] <span class="sc">-</span> bike_cdf[<span class="dv">2</span>],</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_1_to_3 =</span> <span class="fu">sum</span>(bike_pmf[<span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>)]),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">F_3 =</span> <span class="fu">sum</span>(bike_pmf[<span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>)]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         total  P_more_than_2 P_above_1_to_3       P_1_to_3            F_3 
          1.00           0.50           0.60           0.75           0.80 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-11-two-options-compared-by-expected-value-and-spread-15-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-11-two-options-compared-by-expected-value-and-spread-15-minutes">Task 11: Two options, compared by expected value and spread (15 minutes)</h3>
<p>An invented example. Two founders sell second-hand designer clothes online. For December they want to rent a pop-up store, and they can choose between two locations. Option A is a shop in a side street of the city centre. Option B is a booth at the Christmas market, where the rent is high and the number of visitors depends on the weather. <span class="math inline">\(X\)</span> is the profit of the month with option A and <span class="math inline">\(Y\)</span> is the profit of the month with option B, both in thousands of euros. A negative value is a loss. The founders use these two PMFs:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th style="text-align: right;">0</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p_X(x)\)</span></td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.10</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(y\)</span></th>
<th style="text-align: right;"><span class="math inline">\(-2\)</span></th>
<th style="text-align: right;">0</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">4</th>
<th style="text-align: right;">8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p_Y(y)\)</span></td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.10</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Check that both tables are valid PMFs.</li>
<li>Calculate <span class="math inline">\(E[X]\)</span> and <span class="math inline">\(E[Y]\)</span>.</li>
<li>Calculate <span class="math inline">\(\operatorname{Var}(X)\)</span> and <span class="math inline">\(\operatorname{Var}(Y)\)</span> from the definition <span class="math inline">\(E\!\left[(X-E[X])^2\right]\)</span>.</li>
<li>Verify both variances with the computational form <span class="math inline">\(E[X^2]-\left(E[X]\right)^2\)</span>.</li>
<li>Calculate both standard deviations and state them in euros. Compare each standard deviation with the expected profit of its option.</li>
<li>Calculate the probability of a loss for each option.</li>
<li>Decide which option you would choose. Give the numbers that support your choice.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>No mass is negative. The masses sum to 1 in both tables: <span class="math inline">\(0.05+0.25+0.45+0.15+0.10=1\)</span> and <span class="math inline">\(0.10+0.10+0.20+0.50+0.10=1\)</span>.</li>
<li><span class="math inline">\(E[X]=0(0.05)+1(0.25)+2(0.45)+3(0.15)+4(0.10)=0+0.25+0.90+0.45+0.40=2.0\)</span>, an expected profit of 2,000 euros. <span class="math inline">\(E[Y]=(-2)(0.10)+0(0.10)+2(0.20)+4(0.50)+8(0.10)=-0.20+0+0.40+2.00+0.80=3.0\)</span>, an expected profit of 3,000 euros.</li>
<li>Definition form: <span class="math display">\[
\operatorname{Var}(X)=(0-2)^2(0.05)+(1-2)^2(0.25)+(2-2)^2(0.45)+
(3-2)^2(0.15)+(4-2)^2(0.10)
\]</span> <span class="math display">\[
=0.20+0.25+0+0.15+0.40=1.00,
\]</span> <span class="math display">\[
\operatorname{Var}(Y)=(-2-3)^2(0.10)+(0-3)^2(0.10)+(2-3)^2(0.20)+
(4-3)^2(0.50)+(8-3)^2(0.10)
\]</span> <span class="math display">\[
=2.50+0.90+0.20+0.50+2.50=6.60.
\]</span></li>
<li>Computational form: <span class="math inline">\(E[X^2]=0(0.05)+1(0.25)+4(0.45)+9(0.15)+16(0.10)=0+0.25+1.80+1.35+1.60=5.00\)</span>, so <span class="math inline">\(\operatorname{Var}(X)=5.00-2^2=1.00\)</span>. <span class="math inline">\(E[Y^2]=4(0.10)+0(0.10)+4(0.20)+16(0.50)+64(0.10)=0.40+0+0.80+8.00+6.40=15.60\)</span>, so <span class="math inline">\(\operatorname{Var}(Y)=15.60-3^2=6.60\)</span>. Both forms agree.</li>
<li><span class="math inline">\(\operatorname{SD}(X)=\sqrt{1.00}=1.00\)</span> thousand euros, that is 1,000 euros. This is half of the expected profit of option A. <span class="math inline">\(\operatorname{SD}(Y)=\sqrt{6.60}\approx2.57\)</span> thousand euros, that is about 2,570 euros. This is about 86% of the expected profit of option B.</li>
<li>Option A has no negative value, so <span class="math inline">\(P(X&lt;0)=0\)</span>. For option B, <span class="math inline">\(P(Y&lt;0)=p_Y(-2)=0.10\)</span>.</li>
<li>Both choices can be correct if the numbers support the reason. Option B has the higher expected profit: 3,000 euros against 2,000 euros, which is 50% more. Option A has the smaller spread: its standard deviation of 1,000 euros is less than half of the 2,570 euros of option B. Option A never makes a loss, and option B loses 2,000 euros with probability 0.10. The founders rent the store for one December only, so they cannot count on an average over many repetitions. If a loss of 2,000 euros would put the venture in danger, they choose option A. If they can afford such a loss, option B is the better choice because of its higher expected profit.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>x_val <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">4</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>x_prob <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.25</span>, <span class="fl">0.45</span>, <span class="fl">0.15</span>, <span class="fl">0.10</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>y_val <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">8</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>y_prob <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.20</span>, <span class="fl">0.50</span>, <span class="fl">0.10</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>mean_x <span class="ot">&lt;-</span> <span class="fu">sum</span>(x_val <span class="sc">*</span> x_prob)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>mean_y <span class="ot">&lt;-</span> <span class="fu">sum</span>(y_val <span class="sc">*</span> y_prob)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">E_X =</span> mean_x, <span class="at">E_Y =</span> mean_y,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Var_X_definition =</span> <span class="fu">sum</span>((x_val <span class="sc">-</span> mean_x)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> x_prob),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Var_X_shortcut =</span> <span class="fu">sum</span>(x_val<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> x_prob) <span class="sc">-</span> mean_x<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Var_Y_definition =</span> <span class="fu">sum</span>((y_val <span class="sc">-</span> mean_y)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> y_prob),</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Var_Y_shortcut =</span> <span class="fu">sum</span>(y_val<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> y_prob) <span class="sc">-</span> mean_y<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">SD_X =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>((x_val <span class="sc">-</span> mean_x)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> x_prob)),</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">SD_Y =</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>((y_val <span class="sc">-</span> mean_y)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> y_prob)),</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_loss_X =</span> <span class="fu">sum</span>(x_prob[x_val <span class="sc">&lt;</span> <span class="dv">0</span>]),</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_loss_Y =</span> <span class="fu">sum</span>(y_prob[y_val <span class="sc">&lt;</span> <span class="dv">0</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             E_X              E_Y Var_X_definition   Var_X_shortcut 
        2.000000         3.000000         1.000000         1.000000 
Var_Y_definition   Var_Y_shortcut             SD_X             SD_Y 
        6.600000         6.600000         1.000000         2.569047 
        P_loss_X         P_loss_Y 
        0.000000         0.100000 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p><span class="time-budget">Total practice time: about 20 minutes.</span></p>
<section id="timed-individual-practice-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="timed-individual-practice-10-minutes">Timed individual practice: 10 minutes</h3>
<p><span class="shark-tag">Shark Tank data</span> The R output below describes the number of words in the written description (<code>description_words</code>) in the Shark Tank file:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     mean    median   minimum   maximum 
 4.995142  5.000000  1.000000 13.000000 </code></pre>
</div>
</div>
<p>Write no more than 100 words. Compare mean and median, calculate the range, and say what the variable does and does not measure. Then explain which value equals the expectation if every record gets probability <span class="math inline">\(1/1441\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The written descriptions have a mean length of about 5.0 words and a median of 5 words, so the two agree. Their range is <span class="math inline">\(13-1=12\)</span> words. The histogram in Lecture 1 shows a thin tail to the right (mildly right-skewed), although mean and median almost agree. If each record gets probability <span class="math inline">\(1/1441\)</span>, the expectation of this distribution is the mean, about 5.0 words. These values describe the written text in the dataset, not the length or quality of the spoken pitch.</p>
</div>
</div>
</div>
</section>
<section id="check-your-understanding-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="check-your-understanding-5-minutes">Check your understanding (5 minutes)</h3>
<p>Complete from memory:</p>
<ol type="1">
<li>An event is …</li>
<li>A PMF must …</li>
<li>A CDF at <span class="math inline">\(a\)</span> reports …</li>
<li>Expectation is …</li>
<li>Variance is … and its square root is …</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>An event is a specified subset of the sample space.</li>
<li>A PMF is non-negative and sums to 1 over the support.</li>
<li><span class="math inline">\(F_X(a)=P(X\le a)\)</span>.</li>
<li><span class="math inline">\(E[X]=\sum_x x\, p_X(x)\)</span>, the probability-weighted average of the possible values.</li>
<li>Variance is the probability-weighted average of squared deviations from the mean, <span class="math inline">\(\operatorname{Var}(X)=E[X^2]-\left(E[X]\right)^2\)</span>. Its square root is the standard deviation, in the variable’s original unit.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Two sentences about your own venture</span></p>
<p>Think of your EiA venture, or any business you know well. Pick one uncertain count that matters for it, for example customers who sign up in a week, offers received, or orders returned. Write two sentences. First, sketch a small PMF for the count: three or four values with rough probabilities. Then say what its expectation and standard deviation would tell you about a real decision.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run campus venture that sells boxes of prepared meals. “Weekly catering requests: 0 with probability 0.4, 1 with 0.4, 2 with 0.15, and 3 with 0.05, so I expect about 0.85 requests per week. The standard deviation tells me whether a weekend helper is justified. With a high spread, some weeks need a helper even though the average says no.”</p>
</div>
</div>
</div>
<p>You can discuss this task, and any other task in this tutorial, with <strong>Tilly</strong>, the course AI assistant.</p>
</div>
</section>
<section id="more-practice" class="level3">
<h3 class="anchored" data-anchor-id="more-practice">More practice</h3>
<p>For extra exercises on the lectures of this tutorial, with worked solutions, ask <strong>Tilly</strong>, the course AI assistant. For example: “Give me an extra exercise for Tutorial 1. Show the solution only after I send my answer.”</p>
<p><a href="../basic/b04-conditioning-bayes-independence.html">Continue to Lecture 4: Conditioning, Bayes’ rule, and independence</a>.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/b03-discrete-distributions.html" class="pagination-link" aria-label="Lecture 3: Discrete distributions, expectation, and variance">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/b04-conditioning-bayes-independence.html" class="pagination-link" aria-label="Lecture 4: Conditioning, Bayes' rule, and independence">
        <span class="nav-page-text"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>