<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial 2: Conditioning and relationships – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/b07-samples-estimators.html" rel="next">
<link href="../basic/b06-continuous-normal.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-130a4d33f88b74c424d8c0f2e9cca01a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/t02-exam-prep.html">Tutorial 2: Conditioning and relationships</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 3: Normal models, sampling, and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and a first look at regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 4: Hypothesis tests, errors, and power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic Mock Exam</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate Mock Exam</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">QM Advanced</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Advanced: Course overview</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">External Video Guide</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-the-tutorial" id="toc-in-the-tutorial" class="nav-link" data-scroll-target="#in-the-tutorial">In the tutorial</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/t02-exam-prep.html">Tutorial 2: Conditioning and relationships</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b-ep02" class="quarto-section-identifier">Tutorial 2: Conditioning and relationships</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Tutorial 2, you can</span></p>
<ul>
<li>calculate conditional probabilities and apply Bayes’ rule and independence</li>
<li>find covariance and correlation from a joint table and interpret them without causal claims</li>
<li>read a correlation table in a research paper and check an AI answer</li>
</ul>
</div>
<p>Tutorials are exam preparation sessions. Tutorial 2 takes place after Lecture 6, but it practises Lectures 4 and 5 only. The tasks below are exam-style questions. You first try each task in pairs. You may use AI for this, following Attempt, Ask, Verify, Explain. Then the class discusses the solution together.</p>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p>Bring your after-class work from Lectures 4 and 5. Complete these statements without looking at the chapters again:</p>
<ol type="1">
<li>In <span class="math inline">\(P(A\mid B)\)</span>, the reference class is …</li>
<li>Variance averages …</li>
<li>Events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent when …</li>
<li>A joint PMF records …</li>
<li>Covariance averages …</li>
<li>Random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent when …</li>
</ol>
<p>Use the <a href="../basic/formula-sheet.html">formula sheet</a> up to and including Lecture 5.</p>
<p>Review <a href="../resources/math-refresher.html#fractions-and-rearranging-equations">Mathematics Refresher: fractions and rearranging equations</a> and <a href="../resources/math-refresher.html#summation-notation">summation notation</a> if needed.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your preparation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The reference class is <span class="math inline">\(B\)</span>, the event after the vertical bar.</li>
<li>Variance averages squared deviations from a variable’s mean.</li>
<li><span class="math inline">\(P(A\cap B)=P(A)P(B)\)</span>.</li>
<li>A joint PMF records the probability of every possible pair of values.</li>
<li>Covariance averages products of deviations from the two means.</li>
<li><span class="math inline">\(p_{X,Y}(x,y)=p_X(x)\,p_Y(y)\)</span> in every cell of the joint table.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="in-the-tutorial" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-the-tutorial">In the tutorial</h2>
<p>Try each task before you open its answer. In every answer, name the formula and the reference class, check the value, interpret it in context, and say what the result does not show.</p>
<p>Tasks 1 and 3 to 8 belong to the tutorial. Tasks 2, 9, and 10 are extra practice for home.</p>
<p>Tasks 1 to 3 and Task 5 use the Shark Tank file and the two events from Lectures 4 and 5, defined in the same way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span>   <span class="co"># on-air deal</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> sharks<span class="sc">$</span>season <span class="sc">&gt;=</span> <span class="dv">9</span>         <span class="co"># late season: Seasons 9-16</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="task-1-conditional-probability-and-bayes" class="level3">
<h3 class="anchored" data-anchor-id="task-1-conditional-probability-and-bayes">Task 1: Conditional probability and Bayes</h3>
<p><span class="shark-tag">Shark Tank data</span> R reports the counts of the 1,441 pitches by deal and by period:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                Period
Deal             Seasons 1-8 Seasons 9-16
  No on-air deal         330          229
  On-air deal            377          505</code></pre>
</div>
</div>
<ol type="1">
<li>Calculate and interpret <span class="math inline">\(P(D\mid L)\)</span>.</li>
<li>Calculate and interpret <span class="math inline">\(P(L\mid D)\)</span>.</li>
<li>Verify <span class="math inline">\(P(D\cap L)=P(D\mid L)P(L)\)</span>.</li>
<li>Use the law of total probability with the partition <span class="math inline">\(L^c\)</span> and <span class="math inline">\(L\)</span> to recover <span class="math inline">\(P(D)\)</span>.</li>
<li>Show how Bayes’ rule gives <span class="math inline">\(P(L\mid D)\)</span> from <span class="math inline">\(P(D\mid L)\)</span>.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(P(D\mid L)=505/734\approx 0.688\)</span>: among late-season records, 68.8% reached an on-air deal. <span class="math inline">\(P(L\mid D)=505/882\approx 0.573\)</span>: among deal records, 57.3% came from late seasons. The joint probability is <span class="math inline">\(P(D\mid L)P(L)=(505/734)(734/1441)=505/1441\approx 0.350\)</span>.</p>
<p>The law of total probability gives</p>
<p><span class="math display">\[
P(D)=\frac{377}{707}\frac{707}{1441}
     +\frac{505}{734}\frac{734}{1441}
     =\frac{882}{1441}\approx 0.612.
\]</span></p>
<p>Bayes’ rule gives</p>
<p><span class="math display">\[
P(L\mid D)=\frac{P(D\mid L)P(L)}{P(D)}
=\frac{(505/734)(734/1441)}{882/1441}
=\frac{505}{882}\approx 0.573.
\]</span></p>
</div>
</div>
</div>
</section>
<section id="task-2-independence-of-events-extra-practice-for-home" class="level3">
<h3 class="anchored" data-anchor-id="task-2-independence-of-events-extra-practice-for-home">Task 2: Independence of events (extra practice for home)</h3>
<p><span class="shark-tag">Shark Tank data</span> Lecture 4 defined independence of events in two equivalent ways: through conditioning and through the product form. R reports:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          P_D   P_D_given_L     P_D_and_L P_D_times_P_L 
    0.6120749     0.6880109     0.3504511     0.3117717 </code></pre>
</div>
</div>
<ol type="1">
<li>Use the definition with conditioning to decide whether <span class="math inline">\(D\)</span> and <span class="math inline">\(L\)</span> are independent in these records.</li>
<li>Use the product form to reach the same conclusion.</li>
<li>Explain why “not independent” does not mean “late season causes a deal.”</li>
<li>Explain why the early and late events are disjoint but not independent.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The deal probability is about 0.612 overall and 0.688 within late seasons, so conditioning on <span class="math inline">\(L\)</span> changes it. In the same way, the observed joint probability is about 0.350, while the product <span class="math inline">\(P(D)P(L)\)</span> is about 0.312. So <span class="math inline">\(D\)</span> and <span class="math inline">\(L\)</span> are not independent in these records. This is an association in televised pitches that the producers selected. It does not show that the season causes deals, because other factors also changed over the seasons. Early and late are disjoint because they cannot occur together. Observing one makes the other impossible, so disjoint events with positive probability are dependent.</p>
</div>
</div>
</div>
</section>
<section id="task-3-joint-pmf-covariance-and-correlation" class="level3">
<h3 class="anchored" data-anchor-id="task-3-joint-pmf-covariance-and-correlation">Task 3: Joint PMF, covariance, and correlation</h3>
<p><span class="shark-tag">Shark Tank data</span> Let <span class="math inline">\(X\)</span> be the 0/1 deal indicator and <span class="math inline">\(Y\)</span> the 0/1 late-period indicator, defined from the same events:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(D)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>R reports:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Y
X           0         1
  0 0.2290076 0.1589174
  1 0.2616239 0.3504511</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        E_X         E_Y       Var_X       Var_Y        E_XY  covariance 
 0.61207495  0.50936849  0.23743921  0.24991223  0.35045108  0.03867938 
correlation 
 0.15878503 </code></pre>
</div>
</div>
<ol type="1">
<li>Verify that the joint PMF sums to 1.</li>
<li>Recover the marginal PMF of <span class="math inline">\(X\)</span> by summing rows.</li>
<li>Verify <span class="math inline">\(\operatorname{Var}(X)=E[X^2]-\left(E[X]\right)^2\)</span>.</li>
<li>Verify <span class="math inline">\(\operatorname{Cov}(X,Y)=E[XY]-E[X]E[Y]\)</span>.</li>
<li>Interpret the sign of the covariance.</li>
<li>Explain what the correlation adds to the covariance, and what it does not prove.</li>
<li>Calculate the conditional means <span class="math inline">\(E[X\mid Y=1]\)</span> and <span class="math inline">\(E[X\mid Y=0]\)</span> from the joint PMF, and say what they mean.</li>
<li>The sum <span class="math inline">\(X+Y\)</span> counts how many of the two events, deal and late season, happened for a pitch. Calculate <span class="math inline">\(E[X+Y]\)</span> and <span class="math inline">\(\operatorname{Var}(X+Y)\)</span> from the values in the output.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The four joint probabilities sum to 1: <span class="math inline">\(0.229+0.159+0.262+0.350=1\)</span>.</li>
<li>Summing each row across the two <span class="math inline">\(Y\)</span> columns gives <span class="math inline">\(P(X=0)=0.229+0.159=0.388\)</span> and <span class="math inline">\(P(X=1)=0.262+0.350=0.612\)</span>. As counts, these are <span class="math inline">\(559/1441\)</span> and <span class="math inline">\(882/1441\)</span>.</li>
<li>Because <span class="math inline">\(X\)</span> takes only the values 0 and 1, <span class="math inline">\(X^2=X\)</span> and <span class="math inline">\(E[X^2]=E[X]\)</span>. So <span class="math inline">\(\operatorname{Var}(X)=E[X]-\left(E[X]\right)^2=0.612-0.612^2\approx 0.237\)</span>, as in the output.</li>
<li><span class="math inline">\(E[XY]=P(X=1,Y=1)\approx 0.3505\)</span>, and <span class="math inline">\(E[X]E[Y]\approx 0.6121\times0.5094\approx 0.3118\)</span>. The difference is about 0.0387, as in the output.</li>
<li>The covariance is positive. The value 1 occurs for both variables together a little more often than it would under independence: deals and late seasons go together.</li>
<li>The correlation divides the covariance by both standard deviations. The result, about 0.16, has no units and lies between <span class="math inline">\(-1\)</span> and <span class="math inline">\(1\)</span>: a weak positive linear association. It does not show a cause, and it does not say how important the association is in practice. A correlation of zero would not always mean independence, as the U-shaped pattern in Lecture 5 shows.</li>
<li>Divide each column of the joint PMF by its sum. The column sums are <span class="math inline">\(P(Y=1)\approx 0.5094\)</span> and <span class="math inline">\(P(Y=0)\approx 0.4906\)</span>. Because <span class="math inline">\(X\)</span> is 0 or 1, only the <span class="math inline">\(X=1\)</span> entry counts: <span class="math inline">\(E[X\mid Y=1]\approx 0.3505/0.5094\approx 0.688\)</span> and <span class="math inline">\(E[X\mid Y=0]\approx 0.2616/0.4906\approx 0.533\)</span>. Among late-season pitches the average of the deal indicator is 0.688, so 68.8% reached a deal. Among early-season pitches it is 53.3%.</li>
<li><span class="math inline">\(E[X+Y]=E[X]+E[Y]=0.612+0.509=1.121\)</span>. <span class="math inline">\(\operatorname{Var}(X+Y)=\operatorname{Var}(X)+\operatorname{Var}(Y)
+2\operatorname{Cov}(X,Y)=0.237+0.250+2\times0.039\approx 0.565\)</span>. Without the covariance term the result would be 0.487. The sum varies more because deals and late seasons go together.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="task-4-read-a-correlation-table-from-a-paper" class="level3">
<h3 class="anchored" data-anchor-id="task-4-read-a-correlation-table-from-a-paper">Task 4: Read a correlation table from a paper</h3>
<p>Research papers in management usually start their results with one table of means, standard deviations (SD), and correlations. The table below is an invented example in the layout of such a table. It does not come from a real study. It describes a survey of 240 employees with four variables:</p>
<ul>
<li>creative self-efficacy: how much an employee believes in his or her own ability to be creative, rated from 1 to 7.</li>
<li>job tenure: the number of years in the current job.</li>
<li>supervisor support: how much support the employee gets from the supervisor, rated from 1 to 7.</li>
<li>creative performance: how creative the employee’s work is, rated from 1 to 7.</li>
</ul>
<p>The columns “Mean” and “SD” describe each variable alone. The columns 1, 2, and 3 contain correlations. Each number is the correlation between the variable in that row and the variable with that number. For example, the 0.31 in row 3 and column 1 is the correlation between supervisor support and creative self-efficacy.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Creative self-efficacy (1 to 7)</td>
<td style="text-align: right;">5.10</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>2. Job tenure (years)</td>
<td style="text-align: right;">6.40</td>
<td style="text-align: right;">4.20</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>3. Supervisor support (1 to 7)</td>
<td style="text-align: right;">4.80</td>
<td style="text-align: right;">1.10</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>4. Creative performance (1 to 7)</td>
<td style="text-align: right;">4.20</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.28</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Find the correlation between creative self-efficacy and creative performance, and interpret its sign and strength in one sentence.</li>
<li>Which pair of variables has the weakest linear association?</li>
<li>A manager concludes: “Raising supervisor support will raise creative performance.” Name one third variable, or one other reason, that could produce the correlation of 0.28 without support causing performance.</li>
<li>State one thing this table cannot tell you about an individual employee.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The correlation is 0.36, in row 4 and column 1: a moderate positive linear association. Employees with higher creative self-efficacy tended to be rated higher on creative performance in this sample.</li>
<li>The weakest association is between job tenure and supervisor support, with a correlation of 0.05.</li>
<li>Several other explanations fit the same number. Employees in creative roles may get more support and also perform more creatively. Or supervisors may give more support to employees who already perform well. A correlation table cannot separate these explanations.</li>
<li>The table describes how the variables move together across 240 employees. It says nothing certain about any single employee. Many employees with high self-efficacy have average performance ratings.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="task-5-check-the-ai" class="level3">
<h3 class="anchored" data-anchor-id="task-5-check-the-ai">Task 5: Check the AI</h3>
<p><span class="shark-tag">Shark Tank data</span> You asked an AI assistant about the deal indicator <span class="math inline">\(X\)</span> and the late-season indicator <span class="math inline">\(Y\)</span> of Task 3. It answered:</p>
<blockquote class="blockquote">
<p>“The covariance of deal and late season is only 0.039, so the two are almost independent. The correlation of 0.16 shows that a late season causes a deal for 16% of the pitches.”</p>
</blockquote>
<p>Check the answer sentence by sentence. Find what is wrong and write the corrected answer.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The first sentence is wrong. The size of a covariance depends on the units of the two variables, so a small number does not mean a weak association. Independence needs <span class="math inline">\(P(X=1,Y=1)=P(X=1)P(Y=1)\)</span>, and here 0.350 differs from 0.312, so <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are not independent. The second sentence is also wrong. A correlation is not a share of pitches, and it does not show a cause. Corrected answer: deals and late seasons go together, with a weak positive linear association (<span class="math inline">\(r\approx0.16\)</span>). The records do not show that the season causes deals.</p>
</div>
</div>
</div>
</section>
<section id="b-ep02-calculation" class="level3">
<h3 class="anchored" data-anchor-id="b-ep02-calculation">More calculation practice</h3>
<p>Tasks 6 to 10 practise the calculations of Lectures 4 and 5 by hand. Tasks 6, 7, and 8 belong to the tutorial. Tasks 9 and 10 are extra practice for home. All five tasks use invented examples. You need a simple calculator and the formula sheet.</p>
</section>
<section id="task-6-total-probability-and-bayes-rule-from-given-rates" class="level3">
<h3 class="anchored" data-anchor-id="task-6-total-probability-and-bayes-rule-from-given-rates">Task 6: Total probability and Bayes’ rule from given rates</h3>
<p>An invented example. A start-up prints spare parts for household appliances on two 3D printers. The old printer makes 60% of all parts and the new printer makes 40%. Of the parts from the old printer, 5% fail the quality check. Of the parts from the new printer, 10% fail, because the team is still learning how to set up the new printer. One part is selected at random. Let <span class="math inline">\(N\)</span> be the event that the part comes from the new printer, and <span class="math inline">\(F\)</span> the event that the part fails the check.</p>
<ol type="1">
<li>Write the four given numbers as probabilities, with the symbols <span class="math inline">\(N\)</span>, <span class="math inline">\(N^c\)</span>, and <span class="math inline">\(F\)</span>. Name the reference class of <span class="math inline">\(P(F\mid N)\)</span>.</li>
<li>Calculate <span class="math inline">\(P(F\cap N)\)</span> and <span class="math inline">\(P(F\cap N^c)\)</span> with the multiplication rule.</li>
<li>Calculate <span class="math inline">\(P(F)\)</span> with the law of total probability.</li>
<li>Draw the tree for 1,000 parts and state the four counts at its end. Use the counts to calculate <span class="math inline">\(P(N\mid F)\)</span>.</li>
<li>Calculate <span class="math inline">\(P(N\mid F)\)</span> again with the formula of Bayes’ rule.</li>
<li>Decide whether <span class="math inline">\(N\)</span> and <span class="math inline">\(F\)</span> are independent. Show the comparison that you use.</li>
<li>A colleague reads your result and says: “So 57% of the parts from the new printer fail.” Explain what is wrong, and write the correct sentence.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(P(N)=0.40\)</span>, <span class="math inline">\(P(N^c)=0.60\)</span>, <span class="math inline">\(P(F\mid N)=0.10\)</span>, and <span class="math inline">\(P(F\mid N^c)=0.05\)</span>. The reference class of <span class="math inline">\(P(F\mid N)\)</span> is the parts from the new printer.</li>
<li><span class="math inline">\(P(F\cap N)=P(F\mid N)\,P(N)=0.10\times0.40=0.04\)</span> and <span class="math inline">\(P(F\cap N^c)=P(F\mid N^c)\,P(N^c)=0.05\times0.60=0.03\)</span>.</li>
<li><span class="math inline">\(P(F)=0.04+0.03=0.07\)</span>: 7% of all parts fail. This overall rate lies between the two rates of 5% and 10%. It is closer to 5%, because the old printer makes more parts.</li>
<li>Of 1,000 parts, 400 come from the new printer and 600 from the old one. New printer: 40 fail and 360 pass. Old printer: 30 fail and 570 pass. In total <span class="math inline">\(40+30=70\)</span> parts fail, and 40 of them come from the new printer: <span class="math inline">\(P(N\mid F)=40/70\approx0.571\)</span>.</li>
<li>The formula gives the same value: <span class="math display">\[
P(N\mid F)=\frac{P(F\mid N)\,P(N)}
{P(F\mid N)\,P(N)+P(F\mid N^c)\,P(N^c)}
=\frac{0.04}{0.04+0.03}=\frac{0.04}{0.07}\approx0.571.
\]</span></li>
<li><span class="math inline">\(P(F\mid N)=0.10\)</span>, while <span class="math inline">\(P(F)=0.07\)</span>. Learning that a part comes from the new printer raises the probability that it fails, so <span class="math inline">\(N\)</span> and <span class="math inline">\(F\)</span> are not independent. The product form says the same: <span class="math inline">\(P(F)\,P(N)=0.07\times0.40=0.028\)</span>, which is not equal to <span class="math inline">\(P(F\cap N)=0.04\)</span>.</li>
<li>The colleague reversed the condition. The 57% is <span class="math inline">\(P(N\mid F)\)</span>: of the failed parts, 57% come from the new printer. The share of the new printer’s parts that fail is <span class="math inline">\(P(F\mid N)=10\%\)</span>. A correct sentence is: the new printer makes 40% of all parts and 57% of the failed parts.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>p_new <span class="ot">&lt;-</span> <span class="fl">0.40</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>fail_new <span class="ot">&lt;-</span> <span class="fl">0.10</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>fail_old <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>printer_tree <span class="ot">&lt;-</span> <span class="dv">1000</span> <span class="sc">*</span> <span class="fu">c</span>(<span class="at">new_fail =</span> p_new <span class="sc">*</span> fail_new,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">new_pass =</span> p_new <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> fail_new),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">old_fail =</span> (<span class="dv">1</span> <span class="sc">-</span> p_new) <span class="sc">*</span> fail_old,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">old_pass =</span> (<span class="dv">1</span> <span class="sc">-</span> p_new) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> fail_old))</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>printer_tree</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>new_fail new_pass old_fail old_pass 
      40      360       30      570 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>p_fail <span class="ot">&lt;-</span> fail_new <span class="sc">*</span> p_new <span class="sc">+</span> fail_old <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_new)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">P_F_and_N =</span> fail_new <span class="sc">*</span> p_new, <span class="at">P_F_and_not_N =</span> fail_old <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_new),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_F =</span> p_fail, <span class="at">P_N_given_F =</span> fail_new <span class="sc">*</span> p_new <span class="sc">/</span> p_fail,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_F_times_P_N =</span> p_fail <span class="sc">*</span> p_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    P_F_and_N P_F_and_not_N           P_F   P_N_given_F P_F_times_P_N 
    0.0400000     0.0300000     0.0700000     0.5714286     0.0280000 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-7-read-a-joint-pmf-with-three-values-per-variable" class="level3">
<h3 class="anchored" data-anchor-id="task-7-read-a-joint-pmf-with-three-values-per-variable">Task 7: Read a joint PMF with three values per variable</h3>
<p>An invented example. A founder sells houseplants online. One order is selected at random. <span class="math inline">\(X\)</span> is the number of plants in the order (1, 2, or 3) and <span class="math inline">\(Y\)</span> is the number of decorative pots in the order (0, 1, or 2). The joint PMF is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(p_{X,Y}(x,y)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X=1\)</span></td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X=2\)</span></td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(X=3\)</span></td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.10</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Check that the table is a valid joint PMF.</li>
<li>Find the marginal PMF of <span class="math inline">\(X\)</span> and the marginal PMF of <span class="math inline">\(Y\)</span>.</li>
<li>Calculate <span class="math inline">\(P(X\le2,\ Y=2)\)</span>, the probability that an order has at most two plants and two pots. Then calculate <span class="math inline">\(P(X\le2\text{ or }Y=2)\)</span> with the addition rule.</li>
<li>Find the conditional PMF of <span class="math inline">\(X\)</span> given <span class="math inline">\(Y=0\)</span>, and check that it sums to 1.</li>
<li>Calculate the conditional mean <span class="math inline">\(E[X\mid Y=0]\)</span> and the mean <span class="math inline">\(E[X]\)</span>. Interpret the difference in one sentence.</li>
<li>Check the product form of independence in the cell <span class="math inline">\((x,y)=(1,0)\)</span>. What do you conclude, and why is one cell enough here?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>All nine entries are at least 0. The three rows sum to 0.40, 0.30, and 0.30, so all entries together sum to 1.</li>
<li>Sum along each row for <span class="math inline">\(X\)</span>: <span class="math inline">\(p_X(1)=0.25+0.10+0.05=0.40\)</span>, <span class="math inline">\(p_X(2)=0.10+0.15+0.05=0.30\)</span>, and <span class="math inline">\(p_X(3)=0.05+0.15+0.10=0.30\)</span>. Sum down each column for <span class="math inline">\(Y\)</span>: <span class="math inline">\(p_Y(0)=0.25+0.10+0.05=0.40\)</span>, <span class="math inline">\(p_Y(1)=0.10+0.15+0.15=0.40\)</span>, and <span class="math inline">\(p_Y(2)=0.05+0.05+0.10=0.20\)</span>.</li>
<li>The event “at most two plants and two pots” covers the cells <span class="math inline">\((1,2)\)</span> and <span class="math inline">\((2,2)\)</span>, so <span class="math inline">\(P(X\le2,\ Y=2)=0.05+0.05=0.10\)</span>. With <span class="math inline">\(P(X\le2)=0.40+0.30=0.70\)</span> and <span class="math inline">\(P(Y=2)=0.20\)</span>, the addition rule gives <span class="math inline">\(P(X\le2\text{ or }Y=2)=0.70+0.20-0.10=0.80\)</span>. Check: only the cells <span class="math inline">\((3,0)\)</span> and <span class="math inline">\((3,1)\)</span> are outside this event, and <span class="math inline">\(1-0.05-0.15=0.80\)</span>.</li>
<li>Divide the <span class="math inline">\(Y=0\)</span> column by its sum, 0.40: <span class="math inline">\(p_{X\mid Y}(1\mid0)=0.25/0.40=0.625\)</span>, <span class="math inline">\(p_{X\mid Y}(2\mid0)=0.10/0.40=0.25\)</span>, and <span class="math inline">\(p_{X\mid Y}(3\mid0)=0.05/0.40=0.125\)</span>. The three values sum to 1.</li>
<li><span class="math inline">\(E[X\mid Y=0]=1(0.625)+2(0.25)+3(0.125)=0.625+0.50+0.375=1.5\)</span> plants. <span class="math inline">\(E[X]=1(0.40)+2(0.30)+3(0.30)=0.40+0.60+0.90=1.9\)</span> plants. Orders without a pot contain 1.5 plants on average. That is 0.4 plants fewer than the average of all orders, about 21% fewer.</li>
<li>The entry is <span class="math inline">\(p_{X,Y}(1,0)=0.25\)</span>. The product of its margins is <span class="math inline">\(p_X(1)\,p_Y(0)=0.40\times0.40=0.16\)</span>. The two numbers differ, so <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are not independent. Independence needs the product form in every cell, so one cell that does not match is enough to show dependence.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>plant_pot <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span>,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">0.10</span>, <span class="fl">0.15</span>, <span class="fl">0.05</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                      <span class="fl">0.05</span>, <span class="fl">0.15</span>, <span class="fl">0.10</span>), <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="at">plants =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">pots =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>))</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rowSums</span>(plant_pot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  1   2   3 
0.4 0.3 0.3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(plant_pot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0   1   2 
0.4 0.4 0.2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>cond_plants_no_pot <span class="ot">&lt;-</span> plant_pot[, <span class="st">"0"</span>] <span class="sc">/</span> <span class="fu">sum</span>(plant_pot[, <span class="st">"0"</span>])</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>cond_plants_no_pot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3 
0.625 0.250 0.125 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">total =</span> <span class="fu">sum</span>(plant_pot),</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_X_le2_and_Y2 =</span> <span class="fu">sum</span>(plant_pot[<span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>), <span class="st">"2"</span>]),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_X_le2_or_Y2 =</span> <span class="fu">sum</span>(plant_pot[<span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>), ]) <span class="sc">+</span> <span class="fu">sum</span>(plant_pot[, <span class="st">"2"</span>]) <span class="sc">-</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(plant_pot[<span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>), <span class="st">"2"</span>]),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">E_X_given_Y0 =</span> <span class="fu">sum</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span> <span class="sc">*</span> cond_plants_no_pot),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">E_X =</span> <span class="fu">sum</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span> <span class="sc">*</span> <span class="fu">rowSums</span>(plant_pot)),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">cell_1_0 =</span> plant_pot[<span class="st">"1"</span>, <span class="st">"0"</span>],</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">product_1_0 =</span> <span class="fu">sum</span>(plant_pot[<span class="st">"1"</span>, ]) <span class="sc">*</span> <span class="fu">sum</span>(plant_pot[, <span class="st">"0"</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         total P_X_le2_and_Y2  P_X_le2_or_Y2   E_X_given_Y0            E_X 
          1.00           0.10           0.80           1.50           1.90 
      cell_1_0    product_1_0 
          0.25           0.16 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-8-covariance-and-correlation-from-the-same-table" class="level3">
<h3 class="anchored" data-anchor-id="task-8-covariance-and-correlation-from-the-same-table">Task 8: Covariance and correlation from the same table</h3>
<p>Use the joint PMF of Task 7 for the number of plants <span class="math inline">\(X\)</span> and the number of pots <span class="math inline">\(Y\)</span>. Its marginal PMFs are <span class="math inline">\(p_X=0.40,\ 0.30,\ 0.30\)</span> for the values 1, 2, 3 and <span class="math inline">\(p_Y=0.40,\ 0.40,\ 0.20\)</span> for the values 0, 1, 2.</p>
<ol type="1">
<li>Calculate <span class="math inline">\(E[X]\)</span> and <span class="math inline">\(E[Y]\)</span>.</li>
<li>Calculate <span class="math inline">\(E[XY]\)</span> as a double sum: in every cell multiply <span class="math inline">\(x\)</span>, <span class="math inline">\(y\)</span>, and the probability of the cell, and add the nine products.</li>
<li>Calculate <span class="math inline">\(\operatorname{Cov}(X,Y)\)</span> with <span class="math inline">\(E[XY]-E[X]\,E[Y]\)</span> and interpret its sign.</li>
<li>Calculate <span class="math inline">\(\operatorname{Var}(X)\)</span> and <span class="math inline">\(\operatorname{Var}(Y)\)</span> with the computational form.</li>
<li>Calculate the correlation of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Interpret its direction and its strength.</li>
<li>The founder says: “An order with three plants always has a pot in it.” Use the joint PMF of Task 7 to show that this is wrong. Then say what the correlation of part 5 can and cannot tell you about one order.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(E[X]=1(0.40)+2(0.30)+3(0.30)=1.9\)</span> plants and <span class="math inline">\(E[Y]=0(0.40)+1(0.40)+2(0.20)=0.8\)</span> pots.</li>
<li>The three cells with <span class="math inline">\(y=0\)</span> give the product 0. The other six cells give <span class="math inline">\(1\times1\times0.10=0.10\)</span>, <span class="math inline">\(1\times2\times0.05=0.10\)</span>, <span class="math inline">\(2\times1\times0.15=0.30\)</span>, <span class="math inline">\(2\times2\times0.05=0.20\)</span>, <span class="math inline">\(3\times1\times0.15=0.45\)</span>, and <span class="math inline">\(3\times2\times0.10=0.60\)</span>. Their sum is <span class="math inline">\(E[XY]=0.10+0.10+0.30+0.20+0.45+0.60=1.75\)</span>.</li>
<li><span class="math inline">\(\operatorname{Cov}(X,Y)=1.75-1.9\times0.8=1.75-1.52=0.23\)</span>. The sign is positive: orders with more plants than average tend to have more pots than average.</li>
<li><span class="math inline">\(E[X^2]=1(0.40)+4(0.30)+9(0.30)=0.40+1.20+2.70=4.30\)</span>, so <span class="math inline">\(\operatorname{Var}(X)=4.30-1.9^2=4.30-3.61=0.69\)</span>. <span class="math inline">\(E[Y^2]=0(0.40)+1(0.40)+4(0.20)=1.20\)</span>, so <span class="math inline">\(\operatorname{Var}(Y)=1.20-0.8^2=1.20-0.64=0.56\)</span>.</li>
<li>The standard deviations are <span class="math inline">\(\operatorname{SD}(X)=\sqrt{0.69}\approx0.831\)</span> and <span class="math inline">\(\operatorname{SD}(Y)=\sqrt{0.56}\approx0.748\)</span>. The correlation is <span class="math display">\[
\rho_{XY}=\frac{0.23}{0.831\times0.748}=\frac{0.23}{0.6216}\approx0.37.
\]</span> It is a moderate positive linear association, and it has no units.</li>
<li>The cell <span class="math inline">\((3,0)\)</span> has probability 0.05. Among the orders with three plants this is <span class="math inline">\(0.05/0.30\approx0.17\)</span>, about one order in six, so an order with three plants does not always have a pot. A correlation of 0.37 describes a tendency across all orders. It cannot say what one order contains.</li>
</ol>
<p>Verification in R, with <code>plant_pot</code> from the check of Task 7:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>plants <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>pots <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">2</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>p_plants <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(plant_pot)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>p_pots <span class="ot">&lt;-</span> <span class="fu">colSums</span>(plant_pot)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>mean_plants <span class="ot">&lt;-</span> <span class="fu">sum</span>(plants <span class="sc">*</span> p_plants)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>mean_pots <span class="ot">&lt;-</span> <span class="fu">sum</span>(pots <span class="sc">*</span> p_pots)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>var_plants <span class="ot">&lt;-</span> <span class="fu">sum</span>(plants<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> p_plants) <span class="sc">-</span> mean_plants<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>var_pots <span class="ot">&lt;-</span> <span class="fu">sum</span>(pots<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> p_pots) <span class="sc">-</span> mean_pots<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>cov_plants_pots <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">outer</span>(plants, pots) <span class="sc">*</span> plant_pot) <span class="sc">-</span> mean_plants <span class="sc">*</span> mean_pots</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">E_X =</span> mean_plants, <span class="at">E_Y =</span> mean_pots,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">E_XY =</span> <span class="fu">sum</span>(<span class="fu">outer</span>(plants, pots) <span class="sc">*</span> plant_pot),</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">Cov =</span> cov_plants_pots, <span class="at">Var_X =</span> var_plants, <span class="at">Var_Y =</span> var_pots,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">SD_X =</span> <span class="fu">sqrt</span>(var_plants), <span class="at">SD_Y =</span> <span class="fu">sqrt</span>(var_pots),</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">correlation =</span> cov_plants_pots <span class="sc">/</span> <span class="fu">sqrt</span>(var_plants <span class="sc">*</span> var_pots),</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">no_pot_given_3_plants =</span> plant_pot[<span class="st">"3"</span>, <span class="st">"0"</span>] <span class="sc">/</span> p_plants[[<span class="st">"3"</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  E_X                   E_Y                  E_XY 
            1.9000000             0.8000000             1.7500000 
                  Cov                 Var_X                 Var_Y 
            0.2300000             0.6900000             0.5600000 
                 SD_X                  SD_Y           correlation 
            0.8306624             0.7483315             0.3700064 
no_pot_given_3_plants 
            0.1666667 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-9-two-independent-variables-extra-practice-for-home" class="level3">
<h3 class="anchored" data-anchor-id="task-9-two-independent-variables-extra-practice-for-home">Task 9: Two independent variables (extra practice for home)</h3>
<p>An invented example. A founder makes soap and sells it in gift sets through two shops: a concept store in Tilburg and a museum shop in Groningen. <span class="math inline">\(X\)</span> is the number of gift sets sold on a Saturday in Tilburg, and <span class="math inline">\(Y\)</span> is the number sold on the same Saturday in Groningen. The two shops have different customers, so the founder assumes that <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent. The marginal PMFs are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Value</th>
<th style="text-align: right;">0</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p_X(x)\)</span></td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.1</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p_Y(y)\)</span></td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.1</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Build the joint PMF of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Show the calculation for the cell <span class="math inline">\((x,y)=(1,1)\)</span>, and check that the nine entries sum to 1.</li>
<li>Calculate <span class="math inline">\(E[X]\)</span>, <span class="math inline">\(E[Y]\)</span>, and <span class="math inline">\(E[XY]\)</span>. Calculate <span class="math inline">\(E[XY]\)</span> as a double sum over the cells of your table.</li>
<li>Calculate <span class="math inline">\(\operatorname{Cov}(X,Y)\)</span>. Which statement of Lecture 5 gives this result without a calculation?</li>
<li>Calculate <span class="math inline">\(E[X+Y]\)</span> and <span class="math inline">\(\operatorname{Var}(X+Y)\)</span>. Use <span class="math inline">\(\operatorname{Var}(X)=0.41\)</span> and <span class="math inline">\(\operatorname{Var}(Y)=0.44\)</span>.</li>
<li>A friend suggests another joint table with the same two marginal PMFs. In the friend’s table, <span class="math inline">\(p_{X,Y}(2,2)=0.03\)</span>. Can <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> be independent in the friend’s table? Explain.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>For independent variables, every cell is the product of its two margins. For the cell <span class="math inline">\((1,1)\)</span>: <span class="math inline">\(p_X(1)\,p_Y(1)=0.5\times0.4=0.20\)</span>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(p_{X,Y}(x,y)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y=2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(p_X(x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X=0\)</span></td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.4</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X=1\)</span></td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(X=2\)</span></td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.1</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p_Y(y)\)</span></td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
<p>The three rows sum to 0.4, 0.5, and 0.1, so the nine entries sum to 1.</p></li>
<li><p><span class="math inline">\(E[X]=0(0.4)+1(0.5)+2(0.1)=0.7\)</span> and <span class="math inline">\(E[Y]=0(0.5)+1(0.4)+2(0.1)=0.6\)</span> gift sets. In the double sum, every cell with <span class="math inline">\(x=0\)</span> or <span class="math inline">\(y=0\)</span> gives the product 0. The other four cells give <span class="math inline">\(E[XY]=1\times1\times0.20+1\times2\times0.05+2\times1\times0.04+
2\times2\times0.01=0.20+0.10+0.08+0.04=0.42\)</span>.</p></li>
<li><p><span class="math inline">\(\operatorname{Cov}(X,Y)=0.42-0.7\times0.6=0.42-0.42=0\)</span>. Lecture 5 states that independence implies zero covariance, because <span class="math inline">\(E[XY]=E[X]\,E[Y]\)</span> for independent variables.</p></li>
<li><p><span class="math inline">\(E[X+Y]=0.7+0.6=1.3\)</span> gift sets. <span class="math inline">\(\operatorname{Var}(X+Y)=0.41+0.44+2\times0=0.85\)</span>. For independent variables the variances add.</p></li>
<li><p>No.&nbsp;Independence needs <span class="math inline">\(p_{X,Y}(2,2)=p_X(2)\,p_Y(2)=0.1\times0.1=0.01\)</span>. The friend’s entry of 0.03 is three times as large. One cell that does not match is enough, so <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are dependent in the friend’s table. The two marginal PMFs alone do not determine the joint PMF.</p></li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>p_tilburg <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.4</span>, <span class="fl">0.5</span>, <span class="fl">0.1</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>p_groningen <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.4</span>, <span class="fl">0.1</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>soap_joint <span class="ot">&lt;-</span> <span class="fu">outer</span>(p_tilburg, p_groningen)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(soap_joint) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">X =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">Y =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>soap_joint</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Y
X      0    1    2
  0 0.20 0.16 0.04
  1 0.25 0.20 0.05
  2 0.05 0.04 0.01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mean_tilburg <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span> <span class="sc">*</span> p_tilburg)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>mean_groningen <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span> <span class="sc">*</span> p_groningen)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>var_tilburg <span class="ot">&lt;-</span> <span class="fu">sum</span>((<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> p_tilburg) <span class="sc">-</span> mean_tilburg<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>var_groningen <span class="ot">&lt;-</span> <span class="fu">sum</span>((<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> p_groningen) <span class="sc">-</span> mean_groningen<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">total =</span> <span class="fu">sum</span>(soap_joint), <span class="at">E_X =</span> mean_tilburg, <span class="at">E_Y =</span> mean_groningen,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">E_XY =</span> <span class="fu">sum</span>(<span class="fu">outer</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>) <span class="sc">*</span> soap_joint),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">Cov =</span> <span class="fu">sum</span>(<span class="fu">outer</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">0</span><span class="sc">:</span><span class="dv">2</span>) <span class="sc">*</span> soap_joint) <span class="sc">-</span> mean_tilburg <span class="sc">*</span> mean_groningen,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">Var_X =</span> var_tilburg, <span class="at">Var_Y =</span> var_groningen,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">E_sum =</span> mean_tilburg <span class="sc">+</span> mean_groningen,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">Var_sum =</span> var_tilburg <span class="sc">+</span> var_groningen), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  total     E_X     E_Y    E_XY     Cov   Var_X   Var_Y   E_sum Var_sum 
   1.00    0.70    0.60    0.42    0.00    0.41    0.44    1.30    0.85 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-10-the-sum-of-two-variables-with-positive-and-negative-covariance-extra-practice-for-home" class="level3">
<h3 class="anchored" data-anchor-id="task-10-the-sum-of-two-variables-with-positive-and-negative-covariance-extra-practice-for-home">Task 10: The sum of two variables, with positive and negative covariance (extra practice for home)</h3>
<p>An invented example. A founder sells ice cream from a cart in the park. Her daily revenue from ice cream, <span class="math inline">\(X\)</span>, has a mean of 320 euros and a standard deviation of 50 euros. She wants to add a second product and compares two options. With each option, the daily revenue from the second product, <span class="math inline">\(Y\)</span>, has a mean of 180 euros and a standard deviation of 30 euros.</p>
<ul>
<li>Lemonade sells well on the hot days on which ice cream also sells well: <span class="math inline">\(\operatorname{Cov}(X,Y)=600\)</span>.</li>
<li>Hot chocolate sells well on the cool days on which ice cream sells badly: <span class="math inline">\(\operatorname{Cov}(X,Y)=-600\)</span>.</li>
</ul>
<ol type="1">
<li>Calculate <span class="math inline">\(\operatorname{Var}(X)\)</span> and <span class="math inline">\(\operatorname{Var}(Y)\)</span>.</li>
<li>Calculate the expected total revenue <span class="math inline">\(E[X+Y]\)</span> for each option.</li>
<li>Calculate the variance and the standard deviation of the total revenue with lemonade.</li>
<li>Calculate the variance and the standard deviation of the total revenue with hot chocolate.</li>
<li>Calculate the correlation of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> for each option.</li>
<li>Which option gives the more stable total revenue? Explain in one or two sentences why the two options have the same expected total and a different spread.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(\operatorname{Var}(X)=50^2=2{,}500\)</span> and <span class="math inline">\(\operatorname{Var}(Y)=30^2=900\)</span>.</li>
<li><span class="math inline">\(E[X+Y]=320+180=500\)</span> euros for both options. The rule for the expected value of a sum does not use the covariance.</li>
<li>Lemonade: <span class="math inline">\(\operatorname{Var}(X+Y)=2{,}500+900+2\times600=4{,}600\)</span>, so <span class="math inline">\(\operatorname{SD}(X+Y)=\sqrt{4{,}600}\approx67.82\)</span> euros.</li>
<li>Hot chocolate: <span class="math inline">\(\operatorname{Var}(X+Y)=2{,}500+900+2\times(-600)=2{,}200\)</span>, so <span class="math inline">\(\operatorname{SD}(X+Y)=\sqrt{2{,}200}\approx46.90\)</span> euros.</li>
<li>Lemonade: <span class="math inline">\(\rho_{XY}=600/(50\times30)=0.4\)</span>. Hot chocolate: <span class="math inline">\(\rho_{XY}=-600/(50\times30)=-0.4\)</span>. Both are moderate linear associations, one positive and one negative.</li>
<li>Hot chocolate gives the more stable total. Its standard deviation is about 31% smaller (47 against 68 euros), and the expected total is 500 euros in both cases. With a negative covariance, a weak day for one product tends to be a good day for the other, so the two revenues partly cancel each other out. With a positive covariance, good days and bad days come together, and the total varies more.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>var_icecream <span class="ot">&lt;-</span> <span class="dv">50</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>var_second <span class="ot">&lt;-</span> <span class="dv">30</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>var_lemonade <span class="ot">&lt;-</span> var_icecream <span class="sc">+</span> var_second <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="dv">600</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>var_chocolate <span class="ot">&lt;-</span> var_icecream <span class="sc">+</span> var_second <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="sc">-</span><span class="dv">600</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">var_icecream =</span> var_icecream, <span class="at">var_second =</span> var_second,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_total =</span> <span class="dv">320</span> <span class="sc">+</span> <span class="dv">180</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">var_lemonade =</span> var_lemonade, <span class="at">sd_lemonade =</span> <span class="fu">sqrt</span>(var_lemonade),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">var_chocolate =</span> var_chocolate, <span class="at">sd_chocolate =</span> <span class="fu">sqrt</span>(var_chocolate),</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">corr_lemonade =</span> <span class="dv">600</span> <span class="sc">/</span> (<span class="dv">50</span> <span class="sc">*</span> <span class="dv">30</span>), <span class="at">corr_chocolate =</span> <span class="sc">-</span><span class="dv">600</span> <span class="sc">/</span> (<span class="dv">50</span> <span class="sc">*</span> <span class="dv">30</span>),</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_reduction =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sqrt</span>(var_chocolate) <span class="sc">/</span> <span class="fu">sqrt</span>(var_lemonade))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  var_icecream     var_second     mean_total   var_lemonade    sd_lemonade 
  2500.0000000    900.0000000    500.0000000   4600.0000000     67.8232998 
 var_chocolate   sd_chocolate  corr_lemonade corr_chocolate   sd_reduction 
  2200.0000000     46.9041576      0.4000000     -0.4000000      0.3084359 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<section id="individual-practice" class="level3">
<h3 class="anchored" data-anchor-id="individual-practice">Individual practice</h3>
<p><span class="shark-tag">Shark Tank data</span> R reports four values from the Shark Tank file. The first two are the shares of pitches with an on-air deal in Seasons 1 to 8 and in Seasons 9 to 16. The third is the correlation between <code>season</code> and the equity offered (<code>equity_offered_pct</code>). The fourth is the correlation between the equity offered and the deal indicator (<code>deal_on_show</code>).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  early_deal_rate    late_deal_rate cor_season_equity   cor_equity_deal 
        0.5332390         0.6880109        -0.4157650        -0.1128703 </code></pre>
</div>
</div>
<p>Write at most 120 words that interpret all four values. For the two rates, name the reference class. For the two correlations, give the direction and the rough strength. Say how the outcome is measured and what you cannot conclude about cause.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Among the pitches in Seasons 1 to 8, 53.3% reached an on-air deal. Among the pitches in Seasons 9 to 16, 68.8% did. The difference of 15.5 percentage points describes these records. It does not show a causal effect of the season. Season and equity initially offered have a moderate negative linear association (<span class="math inline">\(r\approx-0.42\)</span>). Equity offered and the deal indicator have a weak negative linear association (<span class="math inline">\(r\approx-0.11\)</span>). The entrepreneurs chose their offers themselves, so pitches with low and high offers may differ in other ways too. The outcome is a deal on air, not a completed investment.</p>
</div>
</div>
</div>
</section>
<section id="check-your-understanding" class="level3">
<h3 class="anchored" data-anchor-id="check-your-understanding">Check your understanding</h3>
<p>Complete from memory:</p>
<ol type="1">
<li>The conditioning event gives …</li>
<li>Independence of events means …</li>
<li>Covariance averages …</li>
<li>Correlation standardises …</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The conditioning event gives the denominator or reference class.</li>
<li>Events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent when <span class="math inline">\(P(A\cap B)=P(A)P(B)\)</span>.</li>
<li>Covariance averages products of deviations from the two means.</li>
<li>Correlation standardises covariance by dividing by both standard deviations.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="make-it-yours" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours">Make it yours</h3>
<div class="utility-prompt">
<p><span class="label">Two sentences about your own venture</span></p>
<p>Think of your EiA venture, or any business you know well. Name two events that both matter for it, for example “customer returns” (comes back for a second order) and “customer bought on discount”. Write two sentences. First, state which conditional probability you would most want to know, and why the direction of conditioning matters. Then say whether you would expect the two events to be independent, and what a dependence would, and would not, tell you.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run campus venture that sells boxes of prepared meals. “I most want <span class="math inline">\(P(\text{returns} \mid \text{bought on discount})\)</span>, not the reverse, because I choose whether to run discounts, and this direction tells me about the customers a discount attracts. I expect dependence (discount buyers come back less often), but dependence alone would not show that the discount causes it: customers who look for low prices may be different from the start.”</p>
</div>
</div>
</div>
<p>You can discuss this task, and any other task in this tutorial, with Tilly for QM Basic, the course AI assistant.</p>
</div>
</section>
<section id="more-practice" class="level3">
<h3 class="anchored" data-anchor-id="more-practice">More practice</h3>
<p>For extra exercises on the lectures of this tutorial, with worked solutions, ask Tilly for QM Basic, the course AI assistant. For example: “Give me an extra exercise for Tutorial 2. Show the solution only after I send my answer.”</p>
<p><a href="../basic/b07-samples-estimators.html">Continue to Lecture 7: Samples, parameters, and estimators</a>.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/b06-continuous-normal.html" class="pagination-link" aria-label="Lecture 6: Continuous distributions and the normal model">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/b07-samples-estimators.html" class="pagination-link" aria-label="Lecture 7: Samples, parameters, and estimators">
        <span class="nav-page-text"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>