<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial 3: Normal models, sampling, and confidence intervals – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/b10-testing-errors-power.html" rel="next">
<link href="../basic/b09-t-confidence-intervals.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0373dafead96411fe286b8dec0b5ee25.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/t03-exam-prep.html"><span class="chapter-title">Tutorial 3: Normal models, sampling, and confidence intervals</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Tutorial 3: Normal models, sampling, and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and a first look at regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Hypothesis tests, errors, and power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-the-tutorial" id="toc-in-the-tutorial" class="nav-link" data-scroll-target="#in-the-tutorial">In the tutorial</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/t03-exam-prep.html"><span class="chapter-title">Tutorial 3: Normal models, sampling, and confidence intervals</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b-ep03" class="quarto-section-identifier"><span class="chapter-title">Tutorial 3: Normal models, sampling, and confidence intervals</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Tutorial 3, you can</span></p>
<ul>
<li>calculate probabilities and values from uniform and normal models</li>
<li>calculate standard errors and probabilities for sample means and proportions</li>
<li>construct confidence intervals and qualify conclusions when the sampling design is limited</li>
</ul>
</div>
<p>Tutorials are <strong>exam preparation sessions</strong>. The tasks below are exam-style questions. You first try each task in pairs. You may use AI for this, with the four steps Attempt, Ask, Verify, Explain. Then the class discusses the solution together.</p>
<p>This tutorial covers Lectures 6–9: densities and the normal model, samples and estimators, the sampling distribution of a mean and of a proportion, and confidence intervals. Hypothesis tests follow in Lecture 10 and in Tutorial 4.</p>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p>Bring your after-class work from Lectures 6–9. If you find the algebra difficult, review <a href="../resources/math-refresher.html">Mathematics Refresher: sums, fractions, and roots</a>.</p>
<p>Use the formula sheet with all formulas up to and including Lecture 9.</p>
<p>Complete from memory:</p>
<ol type="1">
<li>Standardising an observation <span class="math inline">\(x\)</span> from <span class="math inline">\(N(\mu,\sigma^2)\)</span> means calculating …</li>
<li>A parameter describes …</li>
<li>An estimator is …</li>
<li>The standard deviation of the sample mean <span class="math inline">\(\bar X\)</span> is … The standard error of the sample mean is …</li>
<li>The CLT describes …</li>
<li>A written answer for a confidence interval has five parts, in this order: …</li>
<li>The confidence interval for a mean with <span class="math inline">\(s\)</span> has the formula … It may be used when …</li>
<li>The confidence interval for a proportion has the formula … It may be used when …</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your preparation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(z=(x-\mu)/\sigma\)</span>: the number of population SDs between <span class="math inline">\(x\)</span> and the mean.</li>
<li>A parameter describes a population.</li>
<li>An estimator is a rule that estimates a parameter from a sample. Its value is random, because the sample is random.</li>
<li>The standard deviation of the sample mean is <span class="math inline">\(\operatorname{SD}(\bar X)=\sigma/\sqrt n\)</span>. The standard error is <span class="math inline">\(\operatorname{SE}(\bar X)=S/\sqrt n\)</span>, with the value <span class="math inline">\(s/\sqrt n\)</span>. It is the estimated standard deviation of <span class="math inline">\(\bar X\)</span>, used when <span class="math inline">\(\sigma\)</span> is unknown.</li>
<li>The distribution of the sample mean across random samples. It is approximately normal for a large random sample, also when the population is not normal.</li>
<li>Formula, with the reason why it may be used. Given values. Calculations: the standard error, then the margin of error. Interval, with the unit. Conclusion in the words of the question.</li>
<li><span class="math inline">\(\bar X\pm t_{1-\alpha/2,\,n-1}\,S/\sqrt n\)</span>. The population is normal, or <span class="math inline">\(n\)</span> is large.</li>
<li><span class="math inline">\(\widehat P\pm z_{1-\alpha/2}\sqrt{\widehat P(1-\widehat P)/n}\)</span>. The condition is <span class="math inline">\(n\hat p\ge10\)</span> and <span class="math inline">\(n(1-\hat p)\ge10\)</span>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="in-the-tutorial" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-the-tutorial">In the tutorial</h2>
<p>Attempt each task before you open its answer. A complete written answer names the quantity and shows the calculation. It reports the value with its unit and interprets this value in context. It also states one important limit of the model or the data.</p>
<p>Tasks 1 to 9 belong to the tutorial. Tasks 10 to 12 are extra practice for home.</p>
<p>In practice <span class="math inline">\(\sigma\)</span> is unknown, so an interval for a mean uses <span class="math inline">\(s\)</span> and a t value. In this book, the values you need are given in the task or on the formula sheet.</p>
<section id="task-1-a-normal-model-in-both-directions" class="level3">
<h3 class="anchored" data-anchor-id="task-1-a-normal-model-in-both-directions">Task 1: A normal model in both directions</h3>
<p>An invented example. A founder runs an escape room. The time that a team needs to solve the room, <span class="math inline">\(Y\)</span>, is modelled as <span class="math inline">\(Y\sim N(45,5^2)\)</span>, in minutes. The standard deviation is 5 minutes.</p>
<p>Supplied values: <span class="math inline">\(P(Z\le0.8)=0.7881\)</span>, <span class="math inline">\(P(Z\le1.2)=0.8849\)</span>, and the 0.95 quantile <span class="math inline">\(z_{0.95}=1.645\)</span>.</p>
<ol type="1">
<li>Calculate the probability that a team needs at most 49 minutes.</li>
<li>Calculate the probability that a team needs between 39 and 49 minutes.</li>
<li>The founder wants a time limit that 5% of the teams exceed. Calculate this limit.</li>
<li>Say in one sentence what the supplied quantile 1.645 means for a standard normal variable <span class="math inline">\(Z\)</span>.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Standardise: <span class="math inline">\(z=(49-45)/5=0.8\)</span>. So <span class="math inline">\(P(Y\le49)=P(Z\le0.8)=0.7881\)</span>. About 79% of the teams need at most 49 minutes.</p></li>
<li><p>The two z values are <span class="math inline">\((39-45)/5=-1.2\)</span> and <span class="math inline">\(0.8\)</span>. The supplied values contain only positive z values, so use the symmetry rule and then the complement rule: <span class="math inline">\(P(Z\le-1.2)=P(Z&gt;1.2)=1-0.8849=0.1151\)</span>. Then</p>
<p><span class="math display">\[
P(39\le Y\le49)=P(Z\le0.8)-P(Z\le-1.2)=0.7881-0.1151=0.6730.
\]</span></p>
<p>About 67% of the teams need between 39 and 49 minutes.</p></li>
<li><p>If 5% of the teams exceed the limit, 95% are at or below it. The limit is the 0.95 quantile of <span class="math inline">\(Y\)</span>: <span class="math inline">\(y=\mu+z\sigma=45+1.645\times5=53.23\)</span> minutes. A limit of about 53 minutes fits.</p></li>
<li><p>95% of the values of <span class="math inline">\(Z\)</span> are at or below 1.645, and 5% are above it.</p></li>
</ol>
<p>Parts 1 and 2 go from a value to a probability. Part 3 goes from a probability to a value. One limit: the normal curve is a model. The answers are only as good as the fit of this model to the recorded times.</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">p_at_most_49 =</span> <span class="fu">pnorm</span>(<span class="dv">49</span>, <span class="at">mean =</span> <span class="dv">45</span>, <span class="at">sd =</span> <span class="dv">5</span>),</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_39_to_49 =</span> <span class="fu">pnorm</span>(<span class="dv">49</span>, <span class="at">mean =</span> <span class="dv">45</span>, <span class="at">sd =</span> <span class="dv">5</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">39</span>, <span class="at">mean =</span> <span class="dv">45</span>, <span class="at">sd =</span> <span class="dv">5</span>),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">by_hand =</span> <span class="fl">0.7881</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.8849</span>),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">limit =</span> <span class="fu">qnorm</span>(<span class="fl">0.95</span>, <span class="at">mean =</span> <span class="dv">45</span>, <span class="at">sd =</span> <span class="dv">5</span>),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">limit_by_hand =</span> <span class="dv">45</span> <span class="sc">+</span> <span class="fl">1.645</span> <span class="sc">*</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> p_at_most_49    p_39_to_49       by_hand         limit limit_by_hand 
    0.7881446     0.6730749     0.6730000    53.2242681    53.2250000 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-2-population-frame-and-claim" class="level3">
<h3 class="anchored" data-anchor-id="task-2-population-frame-and-claim">Task 2: Population, frame, and claim</h3>
<p>A student randomly selects 100 rows from the Shark Tank file and estimates the mean equity offered (<code>equity_offered_pct</code>).</p>
<ol type="1">
<li>State the population about which this sample allows direct conclusions.</li>
<li>Explain why this sample does not represent all <em>Shark Tank</em> applicants.</li>
<li>Explain why this sample does not represent all US entrepreneurs.</li>
<li>State one change needed to target all US entrepreneurs.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The direct finite population is the 1,441 recorded pitches in completed Seasons 1–16. Applicants who did not appear on television are not in the file, so the frame does not represent all applicants. The show also selects a specialised group of entrepreneurs, not a probability sample of US entrepreneurs. To target all US entrepreneurs, you would need a suitable national sampling frame and a random selection from that frame.</p>
</div>
</div>
</div>
</section>
<section id="task-3-reproduce-the-realised-sample" class="level3">
<h3 class="anchored" data-anchor-id="task-3-reproduce-the-realised-sample">Task 3: Reproduce the realised sample</h3>
<p><span class="shark-tag">Shark Tank data</span> The code below draws the sample with seed 123, exactly as in Lecture 7. So you get the same 100 rows when you run it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>sample_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>pitch_sample <span class="ot">&lt;-</span> sharks[sample_rows, ]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">nrow</span>(pitch_sample),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_equity =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_equity =</span> <span class="fu">sd</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">q1_equity =</span> <span class="fu">unname</span>(<span class="fu">quantile</span>(pitch_sample<span class="sc">$</span>equity_offered_pct, <span class="fl">0.25</span>)),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">median_equity =</span> <span class="fu">median</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">q3_equity =</span> <span class="fu">unname</span>(<span class="fu">quantile</span>(pitch_sample<span class="sc">$</span>equity_offered_pct, <span class="fl">0.75</span>)),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">deal_proportion =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>deal_on_show)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              n     mean_equity       sd_equity       q1_equity   median_equity 
     100.000000       12.760000        7.707887        8.000000       10.000000 
      q3_equity deal_proportion 
      17.750000        0.640000 </code></pre>
</div>
</div>
<p>A note on the quartiles in this output. When a quartile falls between two ordered values, R’s <code>quantile()</code> reports a point between them. Here the 75th ordered value is 17 and the 76th is 20, and R reports 17.75. The rule of Lecture 1 takes the 75th of the 100 ordered values, which is 17.</p>
<ol type="1">
<li>Identify the parameter, estimator, and estimate for the mean equity offered (<code>equity_offered_pct</code>).</li>
<li>Identify the parameter, estimator, and estimate for the deal proportion (<code>deal_on_show</code>).</li>
<li>Calculate the interquartile range (IQR) of the equity offered in the sample from the R output and interpret it. The IQR is defined in <a href="../basic/b01-introduction-data-analysis.html#b01-quartiles">Lecture 1</a>.</li>
<li>Explain why a different seed can produce different estimates and a different IQR.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For the equity offered, the parameter is the population mean <span class="math inline">\(\mu\)</span>, the estimator is <span class="math inline">\(\bar X\)</span>, and the estimate is <span class="math inline">\(\bar x=12.76\)</span>%. For the deal outcome, the parameter is the population proportion <span class="math inline">\(p\)</span>, the estimator is <span class="math inline">\(\widehat P\)</span>, and the estimate is <span class="math inline">\(\hat p=0.64\)</span>. The sample quartiles in the R output are <span class="math inline">\(Q_1=8\)</span> and <span class="math inline">\(Q_3=17.75\)</span>, so <span class="math inline">\(\operatorname{IQR}=17.75-8=9.75\)</span> percentage points: the middle half of the initial equity offers in the sample lies between 8% and 17.75%. With the rule of Lecture 1, <span class="math inline">\(Q_3=17\)</span> and the IQR is <span class="math inline">\(17-8=9\)</span> percentage points. Both answers are correct when you name the rule that you used. A different seed selects a different random set of rows. So all sample statistics, including the IQR, can change.</p>
<p>The ordered values behind the two rules:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(pitch_sample<span class="sc">$</span>equity_offered_pct)[<span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">26</span>, <span class="dv">75</span>, <span class="dv">76</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  8  8 17 20</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-4-standard-errors-and-a-larger-sample" class="level3">
<h3 class="anchored" data-anchor-id="task-4-standard-errors-and-a-larger-sample">Task 4: Standard errors and a larger sample</h3>
<p><span class="shark-tag">Shark Tank data</span> Use the sample output of Task 3.</p>
<ol type="1">
<li>Calculate the standard error of the sample mean of the equity offered, <span class="math inline">\(\operatorname{SE}(\bar X)\)</span>.</li>
<li>Calculate the standard error of the sample proportion of deals, <span class="math inline">\(\operatorname{SE}(\widehat P)\)</span> (Lecture 8).</li>
<li>Check the success-failure condition for <span class="math inline">\(\widehat P\)</span>.</li>
<li>Predict how each standard error changes if <span class="math inline">\(n\)</span> increases from 100 to 400 and the spread in the sample stays similar.</li>
<li>In part 1, R calculates the sample SD with <code>sd()</code>. This function divides by <span class="math inline">\(n-1\)</span>. State the value of <span class="math inline">\(n-1\)</span> here, and explain in one sentence why <code>sd()</code> divides by it.</li>
<li>Explain why the results of parts 1 and 2 are standard errors and not the standard deviations of <span class="math inline">\(\bar X\)</span> and <span class="math inline">\(\widehat P\)</span>.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\operatorname{SE}(\bar X)=\frac{s}{\sqrt n}=\frac{7.7079}{\sqrt{100}}=0.7708.
\]</span></p>
<p><span class="math display">\[
\operatorname{SE}(\widehat P)
=\sqrt{\frac{\hat p(1-\hat p)}{n}}
=\sqrt{\frac{0.64(0.36)}{100}}=0.0480.
\]</span></p>
<p>The standard error of the mean is about 0.77 percentage points of equity. The standard error of the proportion is about 4.8 percentage points of the deal rate. The sample contains 64 successes (deals) and 36 failures (no deal). Both counts are at least 10, so the success-failure condition holds. If <span class="math inline">\(n\)</span> becomes four times as large, both standard errors are divided by <span class="math inline">\(\sqrt 4=2\)</span>. The divisor is <span class="math inline">\(n-1=99\)</span>. The deviations are measured from the sample mean, so they must sum to zero. As a result, only 99 of them can vary freely. Dividing by 99 removes the downward bias that this causes (Lecture 7).</p>
<p>The standard deviations of the two estimators are <span class="math inline">\(\sigma/\sqrt n\)</span> and <span class="math inline">\(\sqrt{p(1-p)/n}\)</span>. They contain the population values <span class="math inline">\(\sigma\)</span> and <span class="math inline">\(p\)</span>, which a sample does not give. The standard errors use <span class="math inline">\(s\)</span> and <span class="math inline">\(\hat p\)</span> from the sample in their place. A standard error is an estimated standard deviation of an estimator.</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>s_equity <span class="ot">&lt;-</span> <span class="fu">sd</span>(pitch_sample<span class="sc">$</span>equity_offered_pct)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>p_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>deal_on_show)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">se_mean =</span> s_equity <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">100</span>),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">se_proportion =</span> <span class="fu">sqrt</span>(p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">/</span> <span class="dv">100</span>),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">deals =</span> <span class="fu">sum</span>(pitch_sample<span class="sc">$</span>deal_on_show),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">no_deals =</span> <span class="dv">100</span> <span class="sc">-</span> <span class="fu">sum</span>(pitch_sample<span class="sc">$</span>deal_on_show),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">se_mean_n400 =</span> s_equity <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">400</span>),</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">se_proportion_n400 =</span> <span class="fu">sqrt</span>(p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">/</span> <span class="dv">400</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           se_mean      se_proportion              deals           no_deals 
         0.7707887          0.0480000         64.0000000         36.0000000 
      se_mean_n400 se_proportion_n400 
         0.3853943          0.0240000 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-5-one-pitch-versus-one-mean" class="level3">
<h3 class="anchored" data-anchor-id="task-5-one-pitch-versus-one-mean">Task 5: One pitch versus one mean</h3>
<p><span class="shark-tag">Shark Tank data</span> Suppose the population mean of the equity offered is <span class="math inline">\(\mu=13.21\)</span>%, the population SD is <span class="math inline">\(\sigma=8.44\)</span> percentage points. You draw independent random samples of <span class="math inline">\(n=100\)</span> pitches. Supplied values: <span class="math inline">\(P(Z\le 2.12)=0.983\)</span> and <span class="math inline">\(P(Z\le 0.21)=0.583\)</span>.</p>
<ol type="1">
<li>State the approximate sampling distribution of <span class="math inline">\(\bar X\)</span>, with the standard deviation of the sample mean.</li>
<li>Calculate <span class="math inline">\(P(\bar X&gt;15)\)</span>.</li>
<li>A classmate models a single pitch as <span class="math inline">\(X\sim N(13.21, 8.44^2)\)</span> and calculates <span class="math inline">\(P(X&gt;15)\)</span>. Compute that value too, and explain why the two answers are so different.</li>
<li>The equity offered is strongly right-skewed (Lecture 1). So which of the two calculations uses a bad model? And why does the CLT still justify the calculation in part 2?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The CLT gives approximately <span class="math inline">\(\bar X\mathrel{\dot\sim}N(13.21,\,8.44^2/100)\)</span>. The standard deviation of the sample mean is <span class="math inline">\(\operatorname{SD}(\bar X)=8.44/\sqrt{100}=0.844\)</span> percentage points. Therefore</p>
<p><span class="math display">\[
P(\bar X&gt;15)
=1-P\!\left(Z\le\frac{15-13.21}{0.844}\right)
=1-P(Z\le2.12)
\approx0.017.
\]</span></p>
<p>For a single pitch, <span class="math inline">\(z=(15-13.21)/8.44\approx0.21\)</span>, so <span class="math inline">\(P(X&gt;15)\approx1-0.583\approx0.42\)</span>. The mean of 100 pitches varies ten times less than one pitch (<span class="math inline">\(\sigma/\sqrt{100}\)</span>), so 15 is an ordinary value for one pitch but an extreme value for a mean of 100. A normal curve is symmetric and the equity offered is strongly right-skewed. So the normal model for a single pitch in part 3 is a bad model. The CLT concerns the sample mean. The mean of 100 independent draws has a nearly normal sampling distribution, even when the population is skewed. This is why the calculation in part 2 is justified.</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sd_mean <span class="ot">&lt;-</span> <span class="fl">8.44</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">100</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">sd_of_mean =</span> sd_mean,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">z_mean =</span> (<span class="dv">15</span> <span class="sc">-</span> <span class="fl">13.21</span>) <span class="sc">/</span> sd_mean,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_mean_above_15 =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">15</span>, <span class="at">mean =</span> <span class="fl">13.21</span>, <span class="at">sd =</span> sd_mean),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">z_single =</span> (<span class="dv">15</span> <span class="sc">-</span> <span class="fl">13.21</span>) <span class="sc">/</span> <span class="fl">8.44</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_single_above_15 =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">15</span>, <span class="at">mean =</span> <span class="fl">13.21</span>, <span class="at">sd =</span> <span class="fl">8.44</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       sd_of_mean            z_mean   p_mean_above_15          z_single 
       0.84400000        2.12085308        0.01696708        0.21208531 
p_single_above_15 
       0.41602024 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-6-the-exact-normal-case-and-the-clt" class="level3">
<h3 class="anchored" data-anchor-id="task-6-the-exact-normal-case-and-the-clt">Task 6: The exact normal case and the CLT</h3>
<p>An invented example. A founder makes scented candles. The burn time of one candle, <span class="math inline">\(X\)</span>, is modelled as <span class="math inline">\(X\sim N(40,6^2)\)</span>, in hours. A tester burns a random sample of <span class="math inline">\(n=9\)</span> candles and records the sample mean <span class="math inline">\(\bar X\)</span>. Supplied values for the whole task:</p>
<pre class="text"><code>P(Z &lt;= 0.6) = 0.7257
P(Z &lt;= 1.8) = 0.9641
P(Z &lt;= 2.5) = 0.9938</code></pre>
<ol type="1">
<li>State the distribution of <span class="math inline">\(\bar X\)</span> for <span class="math inline">\(n=9\)</span>, with its mean and its standard deviation. Explain why you may use this distribution although the sample is small.</li>
<li>Calculate the probability that one candle burns less than 36.4 hours.</li>
<li>Calculate the probability that the mean burn time of the 9 candles is below 36.4 hours.</li>
<li>Explain in one sentence why the answers to parts 2 and 3 differ.</li>
</ol>
<p>The founder also looks at the orders in her web shop. The value of one order is strongly right-skewed: most orders are small and a few are very large. The mean is <span class="math inline">\(\mu=45\)</span> euros and the standard deviation is <span class="math inline">\(\sigma=30\)</span> euros.</p>
<ol start="5" type="1">
<li>For a random sample of <span class="math inline">\(n=100\)</span> orders, calculate the probability that the sample mean is above 52.50 euros. Name the result (the theorem) that allows this calculation.</li>
<li>Explain why you cannot do the same calculation for a random sample of 9 orders.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The population is normal. Then the sample mean is exactly normal for every sample size, also for a small one (Lecture 8): <span class="math inline">\(\bar X\sim N(40,\,6^2/9)\)</span>. Its mean is 40 hours and its standard deviation is <span class="math inline">\(\operatorname{SD}(\bar X)=6/\sqrt9=2\)</span> hours.</li>
<li>One candle: <span class="math inline">\(z=(36.4-40)/6=-0.6\)</span>. With the symmetry rule and the complement rule, <span class="math inline">\(P(X&lt;36.4)=P(Z\le-0.6)=1-0.7257=0.2743\)</span>.</li>
<li>The mean of 9 candles: <span class="math inline">\(z=(36.4-40)/2=-1.8\)</span>. So <span class="math inline">\(P(\bar X&lt;36.4)=P(Z\le-1.8)=1-0.9641=0.0359\)</span>.</li>
<li>The mean of 9 candles varies three times less than one candle, so 36.4 hours is an ordinary value for one candle (about 27%) and an unusual value for the mean of 9 candles (about 4%).</li>
<li>The population is not normal, but <span class="math inline">\(n=100\)</span> is large. The CLT gives approximately <span class="math inline">\(\bar X\mathrel{\dot\sim}N(45,\,30^2/100)\)</span>, with <span class="math inline">\(\operatorname{SD}(\bar X)=30/\sqrt{100}=3\)</span> euros. Then <span class="math inline">\(z=(52.50-45)/3=2.5\)</span> and <span class="math inline">\(P(\bar X&gt;52.50)\approx1-0.9938=0.0062\)</span>.</li>
<li>The order values are not normal, so the exact normal case does not hold. A sample of 9 is too small for the CLT. No result of Lecture 8 gives the distribution of <span class="math inline">\(\bar X\)</span> in this case.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">sd_mean_9 =</span> <span class="dv">6</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">9</span>),</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_one_below_36.4 =</span> <span class="fu">pnorm</span>(<span class="fl">36.4</span>, <span class="at">mean =</span> <span class="dv">40</span>, <span class="at">sd =</span> <span class="dv">6</span>),</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_mean_below_36.4 =</span> <span class="fu">pnorm</span>(<span class="fl">36.4</span>, <span class="at">mean =</span> <span class="dv">40</span>, <span class="at">sd =</span> <span class="dv">6</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">9</span>)),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_mean_100 =</span> <span class="dv">30</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">100</span>),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_mean_above_52.50 =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fl">52.50</span>, <span class="at">mean =</span> <span class="dv">45</span>, <span class="at">sd =</span> <span class="dv">30</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">100</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         sd_mean_9   p_one_below_36.4  p_mean_below_36.4        sd_mean_100 
       2.000000000        0.274253118        0.035930319        3.000000000 
p_mean_above_52.50 
       0.006209665 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-7-a-proportion-through-the-clt" class="level3">
<h3 class="anchored" data-anchor-id="task-7-a-proportion-through-the-clt">Task 7: A proportion through the CLT</h3>
<p><span class="shark-tag">Shark Tank data</span> The deal proportion (<code>deal_on_show</code>) in the Shark Tank file is <span class="math inline">\(p=0.612\)</span>. A random sample of <span class="math inline">\(n=100\)</span> pitches is planned, with sample deal proportion <span class="math inline">\(\widehat P\)</span>. Supplied value: <span class="math inline">\(P(Z\le -2.30)=0.011\)</span>.</p>
<ol type="1">
<li>Calculate the standard deviation of the sample proportion, <span class="math inline">\(\operatorname{SD}(\widehat P)\)</span>, and check the success-failure condition.</li>
<li>State the approximate sampling distribution of <span class="math inline">\(\widehat P\)</span>.</li>
<li>Approximate the probability that the sample shows a deal rate of at most 50%, that is, <span class="math inline">\(P(\widehat P\le0.50)\)</span>.</li>
<li>Interpret the result in one sentence.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Here <span class="math inline">\(p\)</span> is given, so the result is a standard deviation and not a standard error: <span class="math inline">\(\operatorname{SD}(\widehat P)=\sqrt{0.612(0.388)/100}\approx0.0487\)</span>. The expected counts are <span class="math inline">\(np=61.2\)</span> and <span class="math inline">\(n(1-p)=38.8\)</span>, both at least 10. So <span class="math inline">\(\widehat P\mathrel{\dot\sim}N(0.612,\,0.0487^2)\)</span>. Standardise:</p>
<p><span class="math display">\[
z=\frac{0.50-0.612}{0.0487}\approx-2.30,
\qquad
P(\widehat P\le0.50)\approx P(Z\le-2.30)\approx0.011.
\]</span></p>
<p>If the deal proportion in the file is 61.2%, only about 1% of random samples of 100 pitches would show a deal rate at or below 50%. Such a sample would be surprising. Lecture 10 builds the hypothesis test on this idea.</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>sd_phat <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fl">0.612</span> <span class="sc">*</span> <span class="fl">0.388</span> <span class="sc">/</span> <span class="dv">100</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">sd_of_phat =</span> sd_phat,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">expected_deals =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fl">0.612</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">expected_no_deals =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fl">0.388</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">z =</span> (<span class="fl">0.50</span> <span class="sc">-</span> <span class="fl">0.612</span>) <span class="sc">/</span> sd_phat,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_at_most_050 =</span> <span class="fu">pnorm</span>(<span class="fl">0.50</span>, <span class="at">mean =</span> <span class="fl">0.612</span>, <span class="at">sd =</span> sd_phat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       sd_of_phat    expected_deals expected_no_deals                 z 
       0.04872946       61.20000000       38.80000000       -2.29840442 
    p_at_most_050 
       0.01076939 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-8-a-confidence-interval-for-a-mean" class="level3">
<h3 class="anchored" data-anchor-id="task-8-a-confidence-interval-for-a-mean">Task 8: A confidence interval for a mean</h3>
<p>An invented example. A founder runs a bouldering gym. Her business plan assumes that a visit lasts 120 minutes on average. She draws a random sample of 16 visits from the 5,000 visits of last year in the check-in system. The sample has a mean of 136 minutes and a standard deviation of <span class="math inline">\(s=28\)</span> minutes. The visit times are roughly normally distributed. Supplied values: <span class="math inline">\(t_{0.95,\,15}=1.753\)</span>, <span class="math inline">\(t_{0.975,\,15}=2.131\)</span>, and <span class="math inline">\(t_{0.995,\,15}=2.947\)</span>. The formula sheet does not list <span class="math inline">\(df=15\)</span>, so the task gives these values here.</p>
<ol type="1">
<li>Construct a 95% confidence interval for the mean visit time of last year. Write the five parts of the exam procedure for a mean (Lecture 9). In part 5, say what the interval tells you about the 120 minutes in the business plan.</li>
<li>Construct the 99% confidence interval. Only parts 2 to 5 change.</li>
<li>Construct the 90% confidence interval. Again only parts 2 to 5 change.</li>
<li>Compare the three conclusions about the 120 minutes, and explain how the width of the interval changes with the confidence level.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The 95% interval in five parts:</p>
<ol type="1">
<li><strong>Formula.</strong> <span class="math inline">\(\bar X\pm t_{1-\alpha/2,\,n-1}\,S/\sqrt n\)</span>. It may be used because the visit times are roughly normal. The sample is small, so a large <span class="math inline">\(n\)</span> is not the reason here.</li>
<li><strong>Given values.</strong> <span class="math inline">\(\bar x=136\)</span> minutes, <span class="math inline">\(s=28\)</span> minutes, <span class="math inline">\(n=16\)</span>, <span class="math inline">\(df=15\)</span>. The confidence level is 95%, so <span class="math inline">\(\alpha=0.05\)</span> and the critical value is <span class="math inline">\(t_{0.975,\,15}=2.131\)</span>.</li>
<li><strong>Calculations.</strong> The standard error is <span class="math inline">\(s/\sqrt n=28/\sqrt{16}=7\)</span> minutes. The margin of error is <span class="math inline">\(2.131\times7=14.92\)</span> minutes.</li>
<li><strong>Interval.</strong> <span class="math inline">\((136-14.92,\ 136+14.92)=(121.08,\ 150.92)\)</span> minutes.</li>
<li><strong>Conclusion.</strong> The value 120 minutes lies outside the interval. At the 5% level we can conclude that the mean visit time of last year differs from 120 minutes. The whole interval lies above 120, so visits last longer than the plan assumes. The lower end is 121.08 minutes, only about 1% above 120. So the difference may be small.</li>
</ol>
<p>The 99% interval, parts 2 to 5:</p>
<ol start="2" type="1">
<li><strong>Given values.</strong> As before, but the confidence level is 99%, so <span class="math inline">\(\alpha=0.01\)</span> and the critical value is <span class="math inline">\(t_{0.995,\,15}=2.947\)</span>.</li>
<li><strong>Calculations.</strong> The standard error stays 7 minutes. The margin of error is <span class="math inline">\(2.947\times7=20.63\)</span> minutes.</li>
<li><strong>Interval.</strong> <span class="math inline">\((136-20.63,\ 136+20.63)=(115.37,\ 156.63)\)</span> minutes.</li>
<li><strong>Conclusion.</strong> The value 120 minutes lies inside the interval. At the 1% level we cannot conclude that the mean visit time differs from 120 minutes.</li>
</ol>
<p>The 90% interval, parts 2 to 5:</p>
<ol start="2" type="1">
<li><strong>Given values.</strong> As before, but the confidence level is 90%, so <span class="math inline">\(\alpha=0.10\)</span> and the critical value is <span class="math inline">\(t_{0.95,\,15}=1.753\)</span>.</li>
<li><strong>Calculations.</strong> The standard error stays 7 minutes. The margin of error is <span class="math inline">\(1.753\times7=12.27\)</span> minutes.</li>
<li><strong>Interval.</strong> <span class="math inline">\((136-12.27,\ 136+12.27)=(123.73,\ 148.27)\)</span> minutes.</li>
<li><strong>Conclusion.</strong> The value 120 minutes lies outside the interval. At the 10% level we can conclude that the mean visit time differs from 120 minutes, and the whole interval lies above 120.</li>
</ol>
<p>A higher confidence level needs a larger critical value, so the margin of error grows from 12.27 minutes at 90% to 14.92 minutes at 95% and 20.63 minutes at 99%. The 99% interval is about 1.7 times as wide as the 90% interval. With the same sample, we can conclude that the mean differs from 120 minutes at the 10% and the 5% level, but not at the stricter 1% level. For this reason every conclusion names its level. One limit: the interval describes the visits of last year, not the visits of next year.</p>
<p>Verification in R, with the supplied t values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>se_visit <span class="ot">&lt;-</span> <span class="dv">28</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">16</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">se =</span> se_visit,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">margin_95 =</span> <span class="fl">2.131</span> <span class="sc">*</span> se_visit,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower_95 =</span> <span class="dv">136</span> <span class="sc">-</span> <span class="fl">2.131</span> <span class="sc">*</span> se_visit, <span class="at">upper_95 =</span> <span class="dv">136</span> <span class="sc">+</span> <span class="fl">2.131</span> <span class="sc">*</span> se_visit,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">margin_99 =</span> <span class="fl">2.947</span> <span class="sc">*</span> se_visit,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower_99 =</span> <span class="dv">136</span> <span class="sc">-</span> <span class="fl">2.947</span> <span class="sc">*</span> se_visit, <span class="at">upper_99 =</span> <span class="dv">136</span> <span class="sc">+</span> <span class="fl">2.947</span> <span class="sc">*</span> se_visit,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">margin_90 =</span> <span class="fl">1.753</span> <span class="sc">*</span> se_visit,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower_90 =</span> <span class="dv">136</span> <span class="sc">-</span> <span class="fl">1.753</span> <span class="sc">*</span> se_visit, <span class="at">upper_90 =</span> <span class="dv">136</span> <span class="sc">+</span> <span class="fl">1.753</span> <span class="sc">*</span> se_visit,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">width_99_over_90 =</span> <span class="fl">2.947</span> <span class="sc">/</span> <span class="fl">1.753</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              se        margin_95         lower_95         upper_95 
        7.000000        14.917000       121.083000       150.917000 
       margin_99         lower_99         upper_99        margin_90 
       20.629000       115.371000       156.629000        12.271000 
        lower_90         upper_90 width_99_over_90 
      123.729000       148.271000         1.681118 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">t_95 =</span> <span class="fu">qt</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="dv">15</span>), <span class="at">t_975 =</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">15</span>),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">t_995 =</span> <span class="fu">qt</span>(<span class="fl">0.995</span>, <span class="at">df =</span> <span class="dv">15</span>),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">low_end_above_120_in_percent =</span> <span class="dv">100</span> <span class="sc">*</span> (<span class="fl">121.08</span> <span class="sc">-</span> <span class="dv">120</span>) <span class="sc">/</span> <span class="dv">120</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        t_95                        t_975 
                    1.753050                     2.131450 
                       t_995 low_end_above_120_in_percent 
                    2.946713                     0.900000 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-9-a-confidence-interval-for-a-proportion" class="level3">
<h3 class="anchored" data-anchor-id="task-9-a-confidence-interval-for-a-proportion">Task 9: A confidence interval for a proportion</h3>
<p>An invented example. A founder sells sneakers online. Her parcel service reports that customers return 15% of all sneaker orders. Last year her shop had 6,000 orders. She draws a random sample of 400 of these orders. Customers returned 40 of these 400 orders. Let <span class="math inline">\(p\)</span> be the proportion of returned orders among all 6,000 orders.</p>
<ol type="1">
<li>Construct a 95% confidence interval for <span class="math inline">\(p\)</span>. Write the five parts of the exam procedure for a proportion (Lecture 9), with the check of the condition. Check the 10% condition first. In part 5, say what the interval tells you about the 15% reported by the parcel service.</li>
<li>The founder says: “My return rate is 10%, so I am 5 percentage points below the 15%.” Assess this sentence.</li>
<li>State the formula of the standard deviation of <span class="math inline">\(\widehat P\)</span> and explain why you cannot calculate it here.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The sample contains 400 of the 6,000 orders, that is 6.7%. This is at most 10%, so we may treat the sample as iid.</p>
<p>The interval of part 1 in five parts:</p>
<ol type="1">
<li><strong>Formula.</strong> <span class="math inline">\(\widehat P\pm z_{1-\alpha/2}\sqrt{\widehat P(1-\widehat P)/n}\)</span>. The condition holds: <span class="math inline">\(n\hat p=40\)</span> and <span class="math inline">\(n(1-\hat p)=360\)</span> are both at least
<ol start="10" type="1">
<li></li>
</ol></li>
<li><strong>Given values.</strong> 40 returned orders, <span class="math inline">\(n=400\)</span>, <span class="math inline">\(\hat p=40/400=0.10\)</span>. The confidence level is 95%, so <span class="math inline">\(z_{0.975}=1.960\)</span>.</li>
<li><strong>Calculations.</strong> The standard error is <span class="math inline">\(\sqrt{0.10\times0.90/400}=\sqrt{0.000225}=0.015\)</span>. The margin of error is <span class="math inline">\(1.960\times0.015=0.0294\)</span>.</li>
<li><strong>Interval.</strong> <span class="math inline">\((0.10-0.0294,\ 0.10+0.0294)=(0.071,\ 0.129)\)</span>, that is, from 7.1% to 12.9% of the orders.</li>
<li><strong>Conclusion.</strong> The value 0.15 lies outside the interval. At the 5% level we can conclude that her proportion of returned orders differs from 15%. The whole interval lies below 0.15.</li>
</ol>
<p>Part 2. The sentence treats the estimate as the exact rate. The 10% is the estimate from 400 orders. The plausible values run from 7.1% to 12.9%. So her return rate is between 2.1 and 7.9 percentage points below the 15%.</p>
<p>Part 3. The standard deviation of the sample proportion is <span class="math inline">\(\operatorname{SD}(\widehat P)=\sqrt{p(1-p)/n}\)</span>. It contains the unknown <span class="math inline">\(p\)</span>, which is the number that the interval tries to estimate. The standard error uses <span class="math inline">\(\hat p\)</span> in its place.</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>p_hat_returns <span class="ot">&lt;-</span> <span class="dv">40</span> <span class="sc">/</span> <span class="dv">400</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>se_returns <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(p_hat_returns <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat_returns) <span class="sc">/</span> <span class="dv">400</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">p_hat =</span> p_hat_returns,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">successes =</span> <span class="dv">400</span> <span class="sc">*</span> p_hat_returns, <span class="at">failures =</span> <span class="dv">400</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat_returns),</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">se =</span> se_returns, <span class="at">margin =</span> <span class="fl">1.960</span> <span class="sc">*</span> se_returns,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> p_hat_returns <span class="sc">-</span> <span class="fl">1.960</span> <span class="sc">*</span> se_returns,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">upper =</span> p_hat_returns <span class="sc">+</span> <span class="fl">1.960</span> <span class="sc">*</span> se_returns,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_share_of_orders =</span> <span class="dv">400</span> <span class="sc">/</span> <span class="dv">6000</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">below_15_at_most =</span> <span class="fl">0.15</span> <span class="sc">-</span> (p_hat_returns <span class="sc">-</span> <span class="fl">1.960</span> <span class="sc">*</span> se_returns),</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">below_15_at_least =</span> <span class="fl">0.15</span> <span class="sc">-</span> (p_hat_returns <span class="sc">+</span> <span class="fl">1.960</span> <span class="sc">*</span> se_returns))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 p_hat              successes               failures 
            0.10000000            40.00000000           360.00000000 
                    se                 margin                  lower 
            0.01500000             0.02940000             0.07060000 
                 upper sample_share_of_orders       below_15_at_most 
            0.12940000             0.06666667             0.07940000 
     below_15_at_least 
            0.02060000 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-10-a-uniform-model-extra-practice-for-home" class="level3">
<h3 class="anchored" data-anchor-id="task-10-a-uniform-model-extra-practice-for-home">Task 10: A uniform model (extra practice for home)</h3>
<p>An invented example. A founder runs a studio that prints T-shirts for student associations. The time to print one order, <span class="math inline">\(X\)</span>, is equally likely to be anywhere between 20 and 60 minutes: <span class="math inline">\(X\sim U(20,60)\)</span>.</p>
<ol type="1">
<li>A colleague sketches the density as a flat line at height 0.02 between 20 and 60 minutes, and zero elsewhere. Show that this is not a valid density, and give the correct height.</li>
<li>Calculate <span class="math inline">\(P(30\le X\le45)\)</span>.</li>
<li>Calculate <span class="math inline">\(P(X&gt;50)\)</span>.</li>
<li>Calculate <span class="math inline">\(P(10\le X\le30)\)</span>. Note that a part of this interval lies outside the possible values of <span class="math inline">\(X\)</span>.</li>
<li>State <span class="math inline">\(P(X=40)\)</span>. Then explain why the height of the density is not a probability.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>A valid density is never negative and has a total area of 1. The sketch is never negative, but its area is <span class="math inline">\((60-20)\times0.02=0.8\)</span>, not 1. The correct height is <span class="math inline">\(1/(60-20)=0.025\)</span> per minute. Then the area is <span class="math inline">\(40\times0.025=1\)</span>.</li>
<li>A probability is an area: width times height. So <span class="math inline">\(P(30\le X\le45)=(45-30)\times0.025=0.375\)</span>.</li>
<li><span class="math inline">\(P(X&gt;50)=(60-50)\times0.025=0.25\)</span>.</li>
<li>The density is zero below 20 minutes, so only the part from 20 to 30 counts: <span class="math inline">\(P(10\le X\le30)=(30-20)\times0.025=0.25\)</span>. A calculation with the full width of 20 minutes gives 0.5, which is wrong.</li>
<li><span class="math inline">\(P(X=40)=0\)</span>. A single value has width zero, so the area above it is zero. The height 0.025 is a probability per minute. It becomes a probability only when you multiply it by a width in minutes.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">area_of_sketch =</span> (<span class="dv">60</span> <span class="sc">-</span> <span class="dv">20</span>) <span class="sc">*</span> <span class="fl">0.02</span>,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">correct_height =</span> <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">60</span> <span class="sc">-</span> <span class="dv">20</span>),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_30_to_45 =</span> <span class="fu">punif</span>(<span class="dv">45</span>, <span class="at">min =</span> <span class="dv">20</span>, <span class="at">max =</span> <span class="dv">60</span>) <span class="sc">-</span> <span class="fu">punif</span>(<span class="dv">30</span>, <span class="at">min =</span> <span class="dv">20</span>, <span class="at">max =</span> <span class="dv">60</span>),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_above_50 =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">punif</span>(<span class="dv">50</span>, <span class="at">min =</span> <span class="dv">20</span>, <span class="at">max =</span> <span class="dv">60</span>),</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_10_to_30 =</span> <span class="fu">punif</span>(<span class="dv">30</span>, <span class="at">min =</span> <span class="dv">20</span>, <span class="at">max =</span> <span class="dv">60</span>) <span class="sc">-</span> <span class="fu">punif</span>(<span class="dv">10</span>, <span class="at">min =</span> <span class="dv">20</span>, <span class="at">max =</span> <span class="dv">60</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>area_of_sketch correct_height     p_30_to_45     p_above_50     p_10_to_30 
         0.800          0.025          0.375          0.250          0.250 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-11-a-sample-size-for-a-target-margin-of-error-extra-practice-for-home" class="level3">
<h3 class="anchored" data-anchor-id="task-11-a-sample-size-for-a-target-margin-of-error-extra-practice-for-home">Task 11: A sample size for a target margin of error (extra practice for home)</h3>
<p>The founder of the bouldering gym in Task 8 plans a new and larger sample. She wants to estimate the mean visit time with a margin of error of at most 5 minutes. She uses the sample SD of Task 8 as a planning value: <span class="math inline">\(\sigma=28\)</span> minutes.</p>
<ol type="1">
<li>Calculate the sample size that she needs at the 95% level (<span class="math inline">\(z_{0.975}=1.960\)</span>).</li>
<li>Calculate the sample size for a margin of 2.5 minutes at the 95% level. Compare it with part 1.</li>
<li>Calculate the sample size for a margin of 5 minutes at the 99% level (<span class="math inline">\(z_{0.995}=2.576\)</span>).</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The formula of Lecture 9, with <span class="math inline">\(m\)</span> the margin of error, is</p>
<p><span class="math display">\[
n\ge\left(\frac{z_{1-\alpha/2}\,\sigma}{m}\right)^2 .
\]</span></p>
<ol type="1">
<li><span class="math inline">\(n\ge(1.960\times28/5)^2=10.976^2\approx120.5\)</span>, so she needs 121 visits. Always round up: with 120 visits the margin would be slightly above 5 minutes.</li>
<li><span class="math inline">\(n\ge(1.960\times28/2.5)^2=21.952^2\approx481.9\)</span>, so 482 visits. Half the margin needs about four times the sample.</li>
<li><span class="math inline">\(n\ge(2.576\times28/5)^2=14.4256^2\approx208.1\)</span>, so 209 visits. More confidence with the same margin needs more observations: 209 in place of 121.</li>
</ol>
<p>The planning value is a guess. If the true <span class="math inline">\(\sigma\)</span> is larger than 28 minutes, the margin of the new sample will be larger than planned.</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>n_needed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">margin_5_at_95 =</span> (<span class="fl">1.960</span> <span class="sc">*</span> <span class="dv">28</span> <span class="sc">/</span> <span class="dv">5</span>)<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">margin_2.5_at_95 =</span> (<span class="fl">1.960</span> <span class="sc">*</span> <span class="dv">28</span> <span class="sc">/</span> <span class="fl">2.5</span>)<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">margin_5_at_99 =</span> (<span class="fl">2.576</span> <span class="sc">*</span> <span class="dv">28</span> <span class="sc">/</span> <span class="dv">5</span>)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>n_needed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  margin_5_at_95 margin_2.5_at_95   margin_5_at_99 
        120.4726         481.8903         208.0979 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(n_needed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  margin_5_at_95 margin_2.5_at_95   margin_5_at_99 
             121              482              209 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-12-a-value-for-a-sample-mean-extra-practice-for-home" class="level3">
<h3 class="anchored" data-anchor-id="task-12-a-value-for-a-sample-mean-extra-practice-for-home">Task 12: A value for a sample mean (extra practice for home)</h3>
<p>An invented example. A founder sells granola in bags of 250 grams. The filling machine puts <span class="math inline">\(X\sim N(250,4^2)\)</span> grams into one bag. Every hour she weighs a random sample of <span class="math inline">\(n=16\)</span> bags and calculates the sample mean <span class="math inline">\(\bar X\)</span>. She wants an alarm value <span class="math inline">\(a\)</span>: she checks the machine when <span class="math inline">\(\bar X&gt;a\)</span>. When the machine works as described, only 5% of the hourly samples may give an alarm. Supplied value: the 0.95 quantile of <span class="math inline">\(Z\)</span> is <span class="math inline">\(z_{0.95}=1.645\)</span>.</p>
<ol type="1">
<li>State the distribution of <span class="math inline">\(\bar X\)</span>, with its standard deviation.</li>
<li>Calculate the value <span class="math inline">\(a\)</span> with <span class="math inline">\(P(\bar X&gt;a)=0.05\)</span>.</li>
<li>Would the same rule make sense with single bags instead of the mean of 16 bags? Calculate the value for a single bag and compare.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The population is normal, so the sample mean is exactly normal: <span class="math inline">\(\bar X\sim N(250,\,4^2/16)\)</span>, with <span class="math inline">\(\operatorname{SD}(\bar X)=4/\sqrt{16}=1\)</span> gram.</li>
<li>If 5% of the sample means lie above <span class="math inline">\(a\)</span>, then 95% lie at or below it. So <span class="math inline">\(a\)</span> is the 0.95 quantile of <span class="math inline">\(\bar X\)</span>: <span class="math inline">\(a=250+1.645\times1=251.65\)</span> grams.</li>
<li>For a single bag the value is <span class="math inline">\(250+1.645\times4=256.58\)</span> grams. Single bags vary four times more than the mean of 16 bags. So the mean of 16 bags detects a change in the filling of the machine much earlier. Its alarm value is only 1.65 grams above 250, about 0.7% of the bag weight.</li>
</ol>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">sd_mean =</span> <span class="dv">4</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">16</span>),</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">alarm_mean =</span> <span class="fu">qnorm</span>(<span class="fl">0.95</span>, <span class="at">mean =</span> <span class="dv">250</span>, <span class="at">sd =</span> <span class="dv">4</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">16</span>)),</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">alarm_by_hand =</span> <span class="dv">250</span> <span class="sc">+</span> <span class="fl">1.645</span> <span class="sc">*</span> <span class="dv">1</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alarm_single =</span> <span class="dv">250</span> <span class="sc">+</span> <span class="fl">1.645</span> <span class="sc">*</span> <span class="dv">4</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">shift_in_percent =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fl">1.645</span> <span class="sc">/</span> <span class="dv">250</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         sd_mean       alarm_mean    alarm_by_hand     alarm_single 
          1.0000         251.6449         251.6450         256.5800 
shift_in_percent 
          0.6580 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<section id="individual-practice" class="level3">
<h3 class="anchored" data-anchor-id="individual-practice">Individual practice</h3>
<p>Do this task alone: no notes, no AI, only the formula sheet. An invented example. A random sample of 64 customers has a mean monthly spending of €82 and a sample SD of €24. Of the 64 customers, 40 renewed their subscription.</p>
<ol type="1">
<li>Calculate the standard error of the mean spending.</li>
<li>Calculate the standard error of the renewal proportion and check its condition.</li>
<li>State what would happen to both standard errors if the sample size were <span class="math inline">\(n=256\)</span>.</li>
<li>Construct a 95% confidence interval for the mean monthly spending of all customers, in the five parts of the exam procedure. The degrees of freedom are 63. Use the closest value on the formula sheet: <span class="math inline">\(t_{0.975,\,60}=2.000\)</span>. The business plan of the founder assumes a mean spending of €90. Say in part 5 what the interval tells you about this value.</li>
<li>Write one sentence that explains the difference between sampling uncertainty and selection bias.</li>
<li>Treat <span class="math inline">\(\mu=82\)</span> and <span class="math inline">\(\sigma=24\)</span> as the population values. Use the CLT to approximate the probability that a new sample of 64 customers shows a mean above €85. Supplied value: <span class="math inline">\(P(Z\le 1)=0.841\)</span>.</li>
<li>Use <span class="math inline">\(\sigma=24\)</span> as a planning value. How many customers must a new survey include to estimate the mean spending with a margin of error of at most €3, at the 95% level (<span class="math inline">\(z_{0.975}=1.96\)</span>)?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The standard error of the mean is <span class="math inline">\(24/\sqrt{64}=3\)</span> euros. The renewal estimate is <span class="math inline">\(\hat p=40/64=0.625\)</span>, with standard error <span class="math inline">\(\sqrt{0.625(0.375)/64}\approx0.0605\)</span>. The sample has 40 successes and 24 failures, so the success-failure condition holds. Increasing the sample size from 64 to 256 would halve both standard errors if the spread stayed similar.</p>
<p>The interval for the mean spending in five parts:</p>
<ol type="1">
<li><strong>Formula.</strong> <span class="math inline">\(\bar X\pm t_{1-\alpha/2,\,n-1}\,S/\sqrt n\)</span>. It may be used because <span class="math inline">\(n=64\)</span> is large.</li>
<li><strong>Given values.</strong> <span class="math inline">\(\bar x=82\)</span> euros, <span class="math inline">\(s=24\)</span> euros, <span class="math inline">\(n=64\)</span>, <span class="math inline">\(df=63\)</span>. The confidence level is 95%, and the closest value on the formula sheet is <span class="math inline">\(t_{0.975,\,60}=2.000\)</span>.</li>
<li><strong>Calculations.</strong> The standard error is <span class="math inline">\(24/\sqrt{64}=3\)</span> euros. The margin of error is <span class="math inline">\(2.000\times3=6\)</span> euros.</li>
<li><strong>Interval.</strong> <span class="math inline">\((82-6,\ 82+6)=(76,\ 88)\)</span> euros.</li>
<li><strong>Conclusion.</strong> The value 90 euros lies outside the interval. At the 5% level we can conclude that the mean monthly spending differs from 90 euros. The whole interval lies below 90, so customers spend less than the plan assumes: at least 2 euros less, about 2% of 90 euros.</li>
</ol>
<p>The standard errors and the interval describe random variation from sample to sample, not bias created by an unrepresentative sampling frame. For the new sample, the standard deviation of the sample mean is <span class="math inline">\(\operatorname{SD}(\bar X)=24/\sqrt{64}=3\)</span> euros and <span class="math inline">\(\bar X\mathrel{\dot\sim}N(82,3^2)\)</span>, so <span class="math inline">\(z=(85-82)/3=1\)</span> and <span class="math inline">\(P(\bar X&gt;85)\approx1-P(Z\le1)\approx0.16\)</span>. For a margin of €3, <span class="math inline">\(n\ge(1.96\times24/3)^2=15.68^2\approx245.9\)</span>, so the survey needs 246 customers (Lecture 9).</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>p_hat_renew <span class="ot">&lt;-</span> <span class="dv">40</span> <span class="sc">/</span> <span class="dv">64</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">se_mean =</span> <span class="dv">24</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">64</span>),</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">se_proportion =</span> <span class="fu">sqrt</span>(p_hat_renew <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat_renew) <span class="sc">/</span> <span class="dv">64</span>),</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">t_exact_df63 =</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">63</span>),</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> <span class="dv">82</span> <span class="sc">-</span> <span class="fl">2.000</span> <span class="sc">*</span> <span class="dv">3</span>, <span class="at">upper =</span> <span class="dv">82</span> <span class="sc">+</span> <span class="fl">2.000</span> <span class="sc">*</span> <span class="dv">3</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">below_90_in_percent =</span> <span class="dv">100</span> <span class="sc">*</span> (<span class="dv">90</span> <span class="sc">-</span> <span class="dv">88</span>) <span class="sc">/</span> <span class="dv">90</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_mean_above_85 =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">85</span>, <span class="at">mean =</span> <span class="dv">82</span>, <span class="at">sd =</span> <span class="dv">3</span>),</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_for_margin_3 =</span> (<span class="fl">1.96</span> <span class="sc">*</span> <span class="dv">24</span> <span class="sc">/</span> <span class="dv">3</span>)<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            se_mean       se_proportion        t_exact_df63               lower 
         3.00000000          0.06051536          1.99834054         76.00000000 
              upper below_90_in_percent     p_mean_above_85      n_for_margin_3 
        88.00000000          2.22222222          0.15865525        245.86240000 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="check-your-understanding" class="level3">
<h3 class="anchored" data-anchor-id="check-your-understanding">Check your understanding</h3>
<p>Complete from memory:</p>
<ol type="1">
<li>A sampling distribution describes …</li>
<li>The standard deviation of a sample mean equals … The standard error of a sample mean equals …</li>
<li>The success-failure condition requires …</li>
<li>The CLT says … becomes approximately normal.</li>
<li>A larger sample does not fix …</li>
<li>A claimed value that lies outside a 95% confidence interval means … A claimed value that lies inside means …</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>How a statistic would vary across repeated random samples.</li>
<li><span class="math inline">\(\sigma/\sqrt n\)</span>. The standard error is the estimated version, <span class="math inline">\(s/\sqrt n\)</span>.</li>
<li><span class="math inline">\(np\ge10\)</span> and <span class="math inline">\(n(1-p)\ge10\)</span>. For a confidence interval the check uses <span class="math inline">\(\hat p\)</span>.</li>
<li>The sample mean. For a large sample its sampling distribution is approximately normal. The single observations do not become normal.</li>
<li>Selection bias, which comes from the way units entered the frame or the sample.</li>
<li>Outside: at the 5% level we can conclude that the parameter differs from the claimed value. Inside: we cannot conclude that it differs, which is not proof that the claimed value is true.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="make-it-yours" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours">Make it yours</h3>
<div class="utility-prompt">
<p><span class="label">Two sentences about your own venture</span></p>
<p>Think of your EiA venture, or any business you know well. Pick one rate or average that you could estimate from about 100 observations, for example a conversion rate, the average value of a purchase, or a renewal share. Then write two sentences. First state the standard error that you would roughly expect, and the 95% interval that follows from it. Then name one claimed value that your interval would rule out. Lecture 10 turns this idea into a hypothesis test.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student venture that sells boxes of ready-made meals on campus. “If 60 of 100 customers renew, the standard error of the renewal share is about 5 percentage points, so my 95% interval runs from roughly 50% to 70%. A claim that only 45% renew would lie outside this interval.”</p>
</div>
</div>
</div>
<p>You can discuss this task, and any other task in this tutorial, with <strong>Tilly</strong>, the course AI assistant: ask it to check the standard error and the interval for your own numbers.</p>
</div>
</section>
<section id="more-practice" class="level3">
<h3 class="anchored" data-anchor-id="more-practice">More practice</h3>
<p>For extra exercises on the lectures that this tutorial covers, with worked solutions, ask <strong>Tilly</strong>, the course AI assistant. For example: “Give me an extra exercise for Tutorial 3. Show the solution only after I send my answer.”</p>
<p><a href="../basic/b10-testing-errors-power.html">Continue to Lecture 10: Testing decisions, errors, power, and a first look at regression</a>.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/b09-t-confidence-intervals.html" class="pagination-link" aria-label="Lecture 9: The t distribution and confidence intervals">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/b10-testing-errors-power.html" class="pagination-link" aria-label="Lecture 10: Testing decisions, errors, power, and a first look at regression">
        <span class="nav-page-text"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and a first look at regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>