<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial 4: Hypothesis tests, errors, and power – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../basic/formula-sheet.html" rel="next">
<link href="../basic/b10-testing-errors-power.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0373dafead96411fe286b8dec0b5ee25.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/t04-exam-prep.html"><span class="chapter-title">Tutorial 4: Hypothesis tests, errors, and power</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and a first look at regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Tutorial 4: Hypothesis tests, errors, and power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-the-tutorial" id="toc-in-the-tutorial" class="nav-link" data-scroll-target="#in-the-tutorial">In the tutorial</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../basic/overview.html">QM Basic: Course overview</a></li><li class="breadcrumb-item"><a href="../basic/t04-exam-prep.html"><span class="chapter-title">Tutorial 4: Hypothesis tests, errors, and power</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="b-ep04" class="quarto-section-identifier"><span class="chapter-title">Tutorial 4: Hypothesis tests, errors, and power</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Tutorial 4, you can</span></p>
<ul>
<li>carry out a two-sided test for a mean and for a proportion in five steps, with a critical value and a rejection region</li>
<li>write the conclusion in the words of the question, also when <span class="math inline">\(H_0\)</span> is not rejected</li>
<li>connect a test decision with the confidence interval and with the p-value</li>
<li>describe a Type I error and a Type II error in context, and say how the significance level and the sample size can change a decision</li>
<li>read a row of regression coefficients without claiming more than the row shows.</li>
</ul>
</div>
<p>Tutorials are <strong>exam preparation sessions</strong>. Every task below follows the format of the final exam. You first try each task in pairs. You may use AI for this, with the four steps Attempt, Ask, Verify, Explain. Then the class discusses the solution together.</p>
<p>This tutorial covers Lecture 10: the five steps of a test, the link between a test and a confidence interval, the p-value, the two errors, and power. The tutorial also uses the confidence intervals of Lecture 9 again. All tests in the exam are two-sided.</p>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p><span class="time-budget">Total preparation time: about 15 minutes.</span></p>
<p>Bring your after-class work from Lectures 9 and 10. If you need it, review <a href="../resources/math-refresher.html">Mathematics Refresher: intervals, degrees of freedom, and standardisation</a>.</p>
<p>Use the formula sheet with all formulas up to and including Lecture 10.</p>
<p>Write from memory:</p>
<ol type="1">
<li>the five steps of a test, in order</li>
<li>the test statistic for a mean when <span class="math inline">\(s\)</span> is used, and its distribution if <span class="math inline">\(H_0\)</span> is true</li>
<li>the test statistic for a proportion, and its distribution if <span class="math inline">\(H_0\)</span> is true</li>
<li>the rejection rule of a two-sided test at the significance level <span class="math inline">\(\alpha\)</span></li>
<li>the definition of a two-sided p-value, and how it gives the same decision as the critical value</li>
<li>the definitions of a Type I error and a Type II error.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your preparation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Hypotheses, with the significance level. Test statistic, with its distribution if <span class="math inline">\(H_0\)</span> is true and the condition. Critical value and rejection region. Observed value. Conclusion.</li>
<li><span class="math inline">\(T=(\bar X-\mu_0)/(S/\sqrt n)\)</span>. If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(T\)</span> has the <span class="math inline">\(t_{n-1}\)</span> distribution. The condition: the population is normal, or <span class="math inline">\(n\)</span> is large.</li>
<li><span class="math inline">\(Z=(\widehat P-p_0)/\sqrt{p_0(1-p_0)/n}\)</span>. If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(Z\)</span> is approximately <span class="math inline">\(N(0,1)\)</span>, provided <span class="math inline">\(np_0\ge10\)</span> and <span class="math inline">\(n(1-p_0)\ge10\)</span>. The denominator is the standard deviation of <span class="math inline">\(\widehat P\)</span> under <span class="math inline">\(H_0\)</span>.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|t_{obs}|\ge t_{1-\alpha/2,\,n-1}\)</span>, or if <span class="math inline">\(|z_{obs}|\ge z_{1-\alpha/2}\)</span> for a proportion. In words: the observed value is at or below minus the critical value, or at or above the critical value.</li>
<li>The probability of a test statistic at least as far from zero as the observed value, in either direction. You calculate this probability as if <span class="math inline">\(H_0\)</span> were true: <span class="math inline">\(2\,P(T\ge|t_{obs}|)\)</span>. The p-value is at most <span class="math inline">\(\alpha\)</span> exactly when the observed value lies in the rejection region.</li>
<li>A Type I error is rejecting <span class="math inline">\(H_0\)</span> when <span class="math inline">\(H_0\)</span> is true. Its probability is at most <span class="math inline">\(\alpha\)</span>. A Type II error is not rejecting <span class="math inline">\(H_0\)</span> when <span class="math inline">\(H_1\)</span> is true.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="in-the-tutorial" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-the-tutorial">In the tutorial</h2>
<p>Try every task before you open its answer. Every conclusion must name the parameter, the units, the population, and the direction of the difference. It must also name the limits of the evidence. Write every test in the five steps and every confidence interval in the five parts, numbered 1 to 5.</p>
<p>Every task shows a time in minutes for your attempt and the discussion. Tasks 1 to 4, 6, and 7 take about 76 minutes together. Task 5 is optional and is extra practice for home.</p>
<p>In the exam, a test for a mean always uses <span class="math inline">\(s\)</span> and a t value. If a t value is not on the formula sheet, the task gives it as a supplied value.</p>
<p>Tasks 1, 2, and 5 use the random sample of 100 pitches (seed 123) from Lecture 7. The code below draws it in the same way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>sample_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>pitch_sample <span class="ot">&lt;-</span> sharks[sample_rows, ]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">n =</span> <span class="fu">nrow</span>(pitch_sample),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_equity =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_equity =</span> <span class="fu">sd</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">deals =</span> <span class="fu">sum</span>(pitch_sample<span class="sc">$</span>deal_on_show))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          n mean_equity   sd_equity       deals 
 100.000000   12.760000    7.707887   64.000000 </code></pre>
</div>
</div>
<section id="task-1-a-test-for-a-mean-and-its-confidence-interval-20-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-1-a-test-for-a-mean-and-its-confidence-interval-20-minutes">Task 1: A test for a mean and its confidence interval (20 minutes)</h3>
<p><span class="shark-tag">Shark Tank data</span> An advisor says that pitches offer 14.5% equity on average. Let <span class="math inline">\(\mu\)</span> be the mean equity offered (<code>equity_offered_pct</code>) among all 1,441 recorded pitches. The sample of 100 pitches has the mean <span class="math inline">\(\bar x=12.76\)</span>% and the standard deviation <span class="math inline">\(s=7.71\)</span> percentage points. The degrees of freedom are 99. Use the closest values on the formula sheet: <span class="math inline">\(t_{0.975,\,100}=1.984\)</span> and <span class="math inline">\(t_{0.995,\,100}=2.626\)</span>.</p>
<ol type="1">
<li>Test <span class="math inline">\(H_0:\mu=14.5\)</span> against <span class="math inline">\(H_1:\mu\ne14.5\)</span> at the 5% level. Write the five steps.</li>
<li>Repeat steps 1, 3, and 5 of the test at the 1% level. State the decision and say whether it changes.</li>
<li>Construct the 95% confidence interval for <span class="math inline">\(\mu\)</span> in five parts.</li>
<li>Explain how the interval of part 3 shows the decision of part 1. Also explain what the interval tells you in addition to the decision.</li>
<li>R reports a two-sided p-value of 0.026 for this test. Show that the p-value gives the same decisions at the 5% level and at the 1% level.</li>
<li>The equity offered is strongly right-skewed. Explain why the test may still use a t critical value with 99 degrees of freedom.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Part 1, the test in five steps:</p>
<ol type="1">
<li><strong>Hypotheses.</strong> <span class="math inline">\(H_0:\mu=14.5\)</span> against <span class="math inline">\(H_1:\mu\ne14.5\)</span>. Here <span class="math inline">\(\mu\)</span> is the mean equity offered among all 1,441 recorded pitches, in percent. The significance level is <span class="math inline">\(\alpha=0.05\)</span>.</li>
<li><strong>Test statistic.</strong> <span class="math inline">\(T=(\bar X-14.5)/(S/\sqrt n)\)</span>. If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(T\)</span> has the t distribution with <span class="math inline">\(n-1=99\)</span> degrees of freedom. The population is not normal, but <span class="math inline">\(n=100\)</span> is large.</li>
<li><strong>Critical value and rejection region.</strong> The critical value is <span class="math inline">\(t_{0.975,\,99}\approx1.984\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t_{obs}\le-1.984\)</span> or <span class="math inline">\(t_{obs}\ge1.984\)</span>.</li>
<li><strong>Observed value.</strong> The standard error is <span class="math inline">\(s/\sqrt n=7.71/\sqrt{100}
=0.771\)</span>. Then <span class="math inline">\(t_{obs}=(12.76-14.5)/0.771=-1.74/0.771=-2.26\)</span>.</li>
<li><strong>Conclusion.</strong> The observed value <span class="math inline">\(-2.26\)</span> is below <span class="math inline">\(-1.984\)</span>, so it lies in the rejection region. Reject <span class="math inline">\(H_0\)</span>. At the 5% level we can conclude that the mean equity offered among the recorded pitches differs from 14.5%. The sign of <span class="math inline">\(t_{obs}\)</span> is negative, so the mean lies below 14.5%.</li>
</ol>
<p>Part 2, the test at the 1% level:</p>
<p>Step 1. <strong>Hypotheses.</strong> As before, with <span class="math inline">\(\alpha=0.01\)</span>.</p>
<p>Step 3. <strong>Critical value and rejection region.</strong> The critical value is <span class="math inline">\(t_{0.995,\,99}\approx2.626\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t_{obs}\le-2.626\)</span> or <span class="math inline">\(t_{obs}\ge2.626\)</span>.</p>
<p>Step 5. <strong>Conclusion.</strong> The observed value <span class="math inline">\(-2.26\)</span> lies between <span class="math inline">\(-2.626\)</span> and 2.626, so it does not lie in the rejection region. Do not reject <span class="math inline">\(H_0\)</span>. At the 1% level we cannot conclude that the mean equity offered differs from 14.5%.</p>
<p>The decision changes with <span class="math inline">\(\alpha\)</span>. The stricter 1% level needs stronger evidence, and the same sample does not give it.</p>
<p>Part 3, the interval in five parts:</p>
<ol type="1">
<li><strong>Formula.</strong> <span class="math inline">\(\bar X\pm t_{1-\alpha/2,\,n-1}\,S/\sqrt n\)</span>. It may be used because <span class="math inline">\(n=100\)</span> is large.</li>
<li><strong>Given values.</strong> <span class="math inline">\(\bar x=12.76\)</span>%, <span class="math inline">\(s=7.71\)</span> percentage points, <span class="math inline">\(n=100\)</span>, <span class="math inline">\(df=99\)</span>. The confidence level is 95%, so the critical value is <span class="math inline">\(t_{0.975,\,99}\approx1.984\)</span>.</li>
<li><strong>Calculations.</strong> The standard error is <span class="math inline">\(7.71/\sqrt{100}=0.771\)</span>. The margin of error is <span class="math inline">\(1.984\times0.771=1.53\)</span> percentage points.</li>
<li><strong>Interval.</strong> <span class="math inline">\((12.76-1.53,\ 12.76+1.53)=(11.23,\ 14.29)\)</span> percent.</li>
<li><strong>Conclusion.</strong> The value 14.5 lies outside the interval. At the 5% level we can conclude that the mean equity offered differs from 14.5%, and the whole interval lies below 14.5%.</li>
</ol>
<p>Part 4. The test and the interval use the same critical value and the same standard error. So the test rejects <span class="math inline">\(H_0:\mu=14.5\)</span> at the 5% level exactly when 14.5 lies outside the 95% interval. The interval also shows the size of the difference: the mean lies between 0.21 and 3.27 percentage points below the 14.5% of the advisor. The lower end, 0.21 points, is about 1.5% of 14.5, so the difference may be small.</p>
<p>Part 5. The p-value 0.026 is below 0.05, so we reject <span class="math inline">\(H_0\)</span> at the 5% level. The p-value is above 0.01, so we do not reject <span class="math inline">\(H_0\)</span> at the 1% level. The critical values give the same decisions. The p-value is at most <span class="math inline">\(\alpha\)</span> exactly when the observed value lies in the rejection region.</p>
<p>Part 6. The test uses a t value because <span class="math inline">\(\sigma\)</span> is unknown and <span class="math inline">\(s\)</span> is used in its place. The sample is large, so by the CLT the test statistic is approximately normal, although single offers are skewed. With 99 degrees of freedom the t distribution is almost the same as the standard normal: the critical value is 1.984 against 1.960. The rule is: with <span class="math inline">\(s\)</span>, always use the t distribution with <span class="math inline">\(n-1\)</span> degrees of freedom.</p>
<p>One limit: the conclusion is about the recorded pitches in the file, not about all entrepreneurs.</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> pitch_sample<span class="sc">$</span>equity_offered_pct</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sd</span>(x)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> s <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>t_obs <span class="ot">&lt;-</span> (x_bar <span class="sc">-</span> <span class="fl">14.5</span>) <span class="sc">/</span> se</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> x_bar <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> se</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean =</span> x_bar, <span class="at">sd =</span> s, <span class="at">se =</span> se, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>, <span class="at">t_obs =</span> t_obs,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">critical_5 =</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>), <span class="at">critical_1 =</span> <span class="fu">qt</span>(<span class="fl">0.995</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fu">abs</span>(t_obs), <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       mean          sd          se          df       t_obs  critical_5 
12.76000000  7.70788656  0.77078866 99.00000000 -2.25742814  1.98421695 
 critical_1     p_value 
 2.62640546  0.02617788 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">lower =</span> ci[<span class="dv">1</span>], <span class="at">upper =</span> ci[<span class="dv">2</span>],</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">below_14.5_at_least =</span> <span class="fl">14.5</span> <span class="sc">-</span> ci[<span class="dv">2</span>], <span class="at">below_14.5_at_most =</span> <span class="fl">14.5</span> <span class="sc">-</span> ci[<span class="dv">1</span>],</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">low_end_in_percent =</span> <span class="dv">100</span> <span class="sc">*</span> (<span class="fl">14.5</span> <span class="sc">-</span> ci[<span class="dv">2</span>]) <span class="sc">/</span> <span class="fl">14.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              lower               upper below_14.5_at_least  below_14.5_at_most 
         11.2305881          14.2894119           0.2105881           3.2694119 
 low_end_in_percent 
          1.4523316 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">se_by_hand =</span> <span class="fl">7.71</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">100</span>), <span class="at">t_by_hand =</span> (<span class="fl">12.76</span> <span class="sc">-</span> <span class="fl">14.5</span>) <span class="sc">/</span> <span class="fl">0.771</span>,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">margin_by_hand =</span> <span class="fl">1.984</span> <span class="sc">*</span> <span class="fl">0.771</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    se_by_hand      t_by_hand margin_by_hand 
      0.771000      -2.256809       1.529664 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, <span class="at">mu =</span> <span class="fl">14.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  x
t = -2.2574, df = 99, p-value = 0.02618
alternative hypothesis: true mean is not equal to 14.5
95 percent confidence interval:
 11.23059 14.28941
sample estimates:
mean of x 
    12.76 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-2-a-test-for-a-proportion-and-its-confidence-interval-15-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-2-a-test-for-a-proportion-and-its-confidence-interval-15-minutes">Task 2: A test for a proportion and its confidence interval (15 minutes)</h3>
<p><span class="shark-tag">Shark Tank data</span> A commentator claims that three quarters of all pitches end with a deal. Let <span class="math inline">\(p\)</span> be the proportion of pitches with a deal (<code>deal_on_show</code>) among all 1,441 recorded pitches. In the sample of 100 pitches, 64 ended with a deal.</p>
<ol type="1">
<li>Test <span class="math inline">\(H_0:p=0.75\)</span> against <span class="math inline">\(H_1:p\ne0.75\)</span> at the 5% level. Write the five steps, with the check of the condition.</li>
<li>Construct the 95% confidence interval for <span class="math inline">\(p\)</span> in five parts, with the check of the condition.</li>
<li>The test divides by 0.0433. The interval uses 0.048. Name these two quantities and explain why their values differ.</li>
<li>Does the interval lead to the same conclusion about 0.75 as the test? Is this always so for a proportion?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Part 1, the test in five steps:</p>
<ol type="1">
<li><strong>Hypotheses.</strong> <span class="math inline">\(H_0:p=0.75\)</span> against <span class="math inline">\(H_1:p\ne0.75\)</span>. Here <span class="math inline">\(p\)</span> is the proportion of pitches with a deal among all 1,441 recorded pitches. The significance level is <span class="math inline">\(\alpha=0.05\)</span>.</li>
<li><strong>Test statistic.</strong> <span class="math inline">\(Z=(\widehat P-p_0)/\sqrt{p_0(1-p_0)/n}\)</span>. If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(Z\)</span> is approximately <span class="math inline">\(N(0,1)\)</span>. The condition holds: <span class="math inline">\(np_0=100\times0.75=75\)</span> and <span class="math inline">\(n(1-p_0)=100\times0.25=25\)</span> are both at least 10.</li>
<li><strong>Critical value and rejection region.</strong> The critical value is <span class="math inline">\(z_{0.975}=1.960\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(z_{obs}\le-1.960\)</span> or <span class="math inline">\(z_{obs}\ge1.960\)</span>.</li>
<li><strong>Observed value.</strong> The denominator is the standard deviation of <span class="math inline">\(\widehat P\)</span> under <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\sqrt{0.75\times0.25/100}=0.0433\)</span>. The estimate is <span class="math inline">\(\hat p=64/100=0.64\)</span>. Then <span class="math inline">\(z_{obs}=(0.64-0.75)/0.0433=-2.54\)</span>.</li>
<li><strong>Conclusion.</strong> The observed value <span class="math inline">\(-2.54\)</span> is below <span class="math inline">\(-1.960\)</span>, so it lies in the rejection region. Reject <span class="math inline">\(H_0\)</span>. At the 5% level we can conclude that the proportion of deals among the recorded pitches differs from 75%. The sign of <span class="math inline">\(z_{obs}\)</span> is negative, so the proportion lies below 75%.</li>
</ol>
<p>Part 2, the interval in five parts:</p>
<ol type="1">
<li><strong>Formula.</strong> <span class="math inline">\(\widehat P\pm z_{1-\alpha/2}\sqrt{\widehat P(1-\widehat P)/n}\)</span>. The condition holds: <span class="math inline">\(n\hat p=64\)</span> and <span class="math inline">\(n(1-\hat p)=36\)</span> are both at least 10.</li>
<li><strong>Given values.</strong> 64 deals, <span class="math inline">\(n=100\)</span>, <span class="math inline">\(\hat p=0.64\)</span>. The confidence level is 95%, so <span class="math inline">\(z_{0.975}=1.960\)</span>.</li>
<li><strong>Calculations.</strong> The standard error is <span class="math inline">\(\sqrt{0.64\times0.36/100}=0.048\)</span>. The margin of error is <span class="math inline">\(1.960\times0.048=0.094\)</span>.</li>
<li><strong>Interval.</strong> <span class="math inline">\((0.64-0.094,\ 0.64+0.094)=(0.546,\ 0.734)\)</span>, that is, from 54.6% to 73.4% of the pitches.</li>
<li><strong>Conclusion.</strong> The value 0.75 lies outside the interval. At the 5% level we can conclude that the proportion of deals differs from 75%, and the whole interval lies below 75%.</li>
</ol>
<p>Part 3. The value 0.0433 is the standard deviation of <span class="math inline">\(\widehat P\)</span> under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(\sqrt{p_0(1-p_0)/n}\)</span>. The test asks how surprising the sample would be if <span class="math inline">\(H_0\)</span> were true. So the test takes <span class="math inline">\(p=p_0=0.75\)</span> as given and does not estimate anything. The value 0.048 is the standard error, <span class="math inline">\(\sqrt{\hat p(1-\hat p)/n}\)</span>. The interval has no claimed value of <span class="math inline">\(p\)</span>, so it uses the estimate <span class="math inline">\(\hat p=0.64\)</span>.</p>
<p>Part 4. Here the interval and the test agree: 0.75 lies outside the interval, and the test rejects <span class="math inline">\(H_0\)</span>. For a proportion this agreement is not certain, because the two denominators differ. When the observed value is very close to the critical value, the test and the interval can give different answers. Use the procedure that the question names.</p>
<p>R reports a p-value of about 0.011 for this test. This p-value is below 0.05, so it gives the same decision.</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(pitch_sample)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>p_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>deal_on_show)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">&lt;-</span> <span class="fl">0.75</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>sd_null <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(p0 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p0) <span class="sc">/</span> n)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>z_obs <span class="ot">&lt;-</span> (p_hat <span class="sc">-</span> p0) <span class="sc">/</span> sd_null</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>se_hat <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(p_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">/</span> n)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>ci_p <span class="ot">&lt;-</span> p_hat <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> <span class="fl">1.960</span> <span class="sc">*</span> se_hat</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">successes_H0 =</span> n <span class="sc">*</span> p0, <span class="at">failures_H0 =</span> n <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p0),</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_hat =</span> p_hat, <span class="at">sd_under_H0 =</span> sd_null, <span class="at">z_obs =</span> z_obs,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fu">abs</span>(z_obs)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>successes_H0  failures_H0        p_hat  sd_under_H0        z_obs      p_value 
 75.00000000  25.00000000   0.64000000   0.04330127  -2.54034118   0.01107444 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">standard_error =</span> se_hat, <span class="at">margin =</span> <span class="fl">1.960</span> <span class="sc">*</span> se_hat,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> ci_p[<span class="dv">1</span>], <span class="at">upper =</span> ci_p[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>standard_error         margin          lower          upper 
       0.04800        0.09408        0.54592        0.73408 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-3-read-a-regression-coefficient-row-8-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-3-read-a-regression-coefficient-row-8-minutes">Task 3: Read a regression coefficient row (8 minutes)</h3>
<p>Suppose that you regress the equity offered (in percentage points) on the amount requested. The regression output shows this row for the amount requested. The sample is large, so the critical value at the 5% level is about 1.96.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Predictor</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: right;">95% interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Amount requested, per $100,000</td>
<td style="text-align: right;">-0.290</td>
<td style="text-align: right;">0.058</td>
<td style="text-align: right;">-5.00</td>
<td style="text-align: right;">&lt;0.001</td>
<td style="text-align: right;">(-0.404, -0.176)</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>State the tested hypotheses.</li>
<li>Explain every number in the row, with its units.</li>
<li>Give the statistical conclusion at the 5% level.</li>
<li>State two claims that the row cannot justify.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Write <span class="math inline">\(\beta_1\)</span> for the population coefficient of the amount requested. The test is <span class="math inline">\(H_0:\beta_1=0\)</span> against <span class="math inline">\(H_1:\beta_1\ne0\)</span>. The estimate <span class="math inline">\(\hat\beta_1=-0.290\)</span> says that each extra $100,000 requested goes together with 0.290 percentage points less equity offered. The standard error, 0.058, measures the sampling uncertainty of the estimate in the same units. The observed value of the test statistic is <span class="math inline">\(t_{obs}=-0.290/0.058=-5.00\)</span>: the estimate lies five standard errors below zero. The interval says that plausible values of the coefficient run from <span class="math inline">\(-0.404\)</span> to <span class="math inline">\(-0.176\)</span> percentage points per $100,000.</p>
<p>The observed value <span class="math inline">\(-5.00\)</span> is far below <span class="math inline">\(-1.96\)</span>, so it lies in the rejection region. Reject <span class="math inline">\(H_0\)</span> at the 5% level: the coefficient differs from zero, and the negative sign shows that it lies below zero. The p-value below 0.001 and the 95% interval, which does not contain zero, show the same decision. The row alone does not show that asking for more money causes lower equity offers, and it does not show that the conditions of the model hold.</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">t_obs =</span> <span class="sc">-</span><span class="fl">0.290</span> <span class="sc">/</span> <span class="fl">0.058</span>,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> <span class="sc">-</span><span class="fl">0.290</span> <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="fl">0.058</span>, <span class="at">upper =</span> <span class="sc">-</span><span class="fl">0.290</span> <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="fl">0.058</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        t_obs         lower         upper       p_value 
-5.000000e+00 -4.036800e-01 -1.763200e-01  5.733031e-07 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-4-errors-power-and-what-changes-a-decision-15-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-4-errors-power-and-what-changes-a-decision-15-minutes">Task 4: Errors, power, and what changes a decision (15 minutes)</h3>
<p>Parts 1 to 5 are about the test of Task 3:</p>
<ol type="1">
<li>describe a Type I error</li>
<li>describe a Type II error</li>
<li>state how a larger sample affects the standard error and the power</li>
<li>explain why raising <span class="math inline">\(\alpha\)</span> has a cost as well as a benefit</li>
<li>state which of the two errors is possible after the decision in Task 3.</li>
</ol>
<p>Parts 6 to 9 use an invented example. A founder runs a barbershop and plans 40 minutes for one haircut. She draws a random sample of 36 haircuts from the booking system of last month. The sample has a mean of 44 minutes and a standard deviation of <span class="math inline">\(s=12\)</span> minutes. Haircut times are roughly normally distributed. She tests <span class="math inline">\(H_0:\mu=40\)</span> against <span class="math inline">\(H_1:\mu\ne40\)</span>, where <span class="math inline">\(\mu\)</span> is the mean time of all haircuts of last month. Supplied values: <span class="math inline">\(t_{0.95,\,35}=1.690\)</span> and <span class="math inline">\(t_{0.995,\,35}=2.724\)</span>.</p>
<ol start="6" type="1">
<li>Calculate the observed value <span class="math inline">\(t_{obs}\)</span>.</li>
<li>Decide at the 10% level and at the 1% level. State the critical value and the rejection region each time.</li>
<li>Suppose that the same mean and the same standard deviation come from a sample of 144 haircuts. Calculate <span class="math inline">\(t_{obs}\)</span> again, and decide at the 1% level. The degrees of freedom are 143. Use the closest value on the formula sheet: <span class="math inline">\(t_{0.995,\,120}=2.617\)</span>.</li>
<li>Explain how <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(n\)</span> changed the decision. State which error is possible after each of the three decisions.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Parts 1 to 5. A Type I error is concluding that the population coefficient of the amount requested differs from zero when it equals zero. A Type II error is not rejecting <span class="math inline">\(H_0\)</span> when the population coefficient is in fact not zero. A larger independent sample usually reduces the standard error and raises the power. Raising <span class="math inline">\(\alpha\)</span> also raises the power, but it raises the probability of a Type I error at the same time. A wider rejection region leads to more rejections, both when <span class="math inline">\(H_1\)</span> is true and when <span class="math inline">\(H_0\)</span> is true. In Task 3 we rejected the null hypothesis, so only a Type I error is possible. A Type II error is possible only after a decision not to reject.</p>
<p>Part 6. Step 4. The standard error is <span class="math inline">\(s/\sqrt n=12/\sqrt{36}=2\)</span> minutes. Then <span class="math inline">\(t_{obs}=(44-40)/2=2.00\)</span>.</p>
<p>Part 7. At the 10% level: Step 3. Each tail holds 5%, so the critical value is <span class="math inline">\(t_{0.95,\,35}=1.690\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t_{obs}\le-1.690\)</span> or <span class="math inline">\(t_{obs}\ge1.690\)</span>. Step 5. The observed value 2.00 lies in the rejection region. Reject <span class="math inline">\(H_0\)</span>: at the 10% level we can conclude that the mean haircut time differs from 40 minutes. The positive sign shows that the mean lies above 40 minutes. At the 1% level: Step 3. The critical value is <span class="math inline">\(t_{0.995,\,35}=2.724\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t_{obs}\le-2.724\)</span> or <span class="math inline">\(t_{obs}\ge2.724\)</span>. Step 5. The observed value 2.00 does not lie in this rejection region. Do not reject <span class="math inline">\(H_0\)</span>: at the 1% level we cannot conclude that the mean haircut time differs from 40 minutes.</p>
<p>Part 8. Step 3. The critical value is <span class="math inline">\(t_{0.995,\,120}=2.617\)</span>, the closest listed value for <span class="math inline">\(df=143\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t_{obs}\le-2.617\)</span> or <span class="math inline">\(t_{obs}\ge2.617\)</span>. Step 4. With 144 haircuts the standard error is <span class="math inline">\(12/\sqrt{144}=1\)</span> minute, so <span class="math inline">\(t_{obs}=(44-40)/1=4.00\)</span>. Step 5. The observed value 4.00 lies in the rejection region, so reject <span class="math inline">\(H_0\)</span>. At the 1% level we can conclude that the mean haircut time differs from 40 minutes. The positive sign shows that the mean lies above 40 minutes.</p>
<p>Part 9. A smaller <span class="math inline">\(\alpha\)</span> moves the critical value away from zero, from 1.690 to 2.724. With the same data, we then no longer reject <span class="math inline">\(H_0\)</span>. This protects against a Type I error, but it makes a Type II error more likely. A larger sample makes the standard error smaller, from 2 minutes to 1 minute. The same difference of 4 minutes, 10% of the planned 40 minutes, then gives a larger observed value, 4.00 instead of 2.00. This means higher power. After the two rejections only a Type I error is possible. After the decision not to reject, with 36 haircuts at the 1% level, only a Type II error is possible.</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">se_36 =</span> <span class="dv">12</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">36</span>), <span class="at">t_obs_36 =</span> (<span class="dv">44</span> <span class="sc">-</span> <span class="dv">40</span>) <span class="sc">/</span> (<span class="dv">12</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">36</span>)),</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">critical_10 =</span> <span class="fu">qt</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="dv">35</span>), <span class="at">critical_1 =</span> <span class="fu">qt</span>(<span class="fl">0.995</span>, <span class="at">df =</span> <span class="dv">35</span>),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">se_144 =</span> <span class="dv">12</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">144</span>), <span class="at">t_obs_144 =</span> (<span class="dv">44</span> <span class="sc">-</span> <span class="dv">40</span>) <span class="sc">/</span> (<span class="dv">12</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">144</span>)),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">critical_1_df143 =</span> <span class="fu">qt</span>(<span class="fl">0.995</span>, <span class="at">df =</span> <span class="dv">143</span>),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">difference_in_percent =</span> <span class="dv">100</span> <span class="sc">*</span> (<span class="dv">44</span> <span class="sc">-</span> <span class="dv">40</span>) <span class="sc">/</span> <span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                se_36              t_obs_36           critical_10 
             2.000000              2.000000              1.689572 
           critical_1                se_144             t_obs_144 
             2.723806              1.000000              4.000000 
     critical_1_df143 difference_in_percent 
             2.610647             10.000000 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-5-optional-one-sided-alternatives-and-the-exam-convention-8-minutes-extra-practice-for-home" class="level3">
<h3 class="anchored" data-anchor-id="task-5-optional-one-sided-alternatives-and-the-exam-convention-8-minutes-extra-practice-for-home">Task 5 (optional): One-sided alternatives and the exam convention (8 minutes, extra practice for home)</h3>
<p><span class="shark-tag">Shark Tank data</span> This task belongs to the optional box on one-sided alternatives in Lecture 10. It is not part of the exam.</p>
<p>Task 1 gave <span class="math inline">\(t_{obs}=-2.26\)</span> with <span class="math inline">\(df=99\)</span> and a two-sided p-value of about 0.026.</p>
<ol type="1">
<li>Give the p-values for the one-sided alternatives <span class="math inline">\(H_1:\mu&lt;14.5\)</span> and <span class="math inline">\(H_1:\mu&gt;14.5\)</span>. Assume that the researcher chose each alternative before looking at the data.</li>
<li>A student first sees that the sample mean is below 14.5. Then the student wants to report the left-sided p-value “because the direction is now known”. Explain the error.</li>
<li>State the convention of this course for tests and one reason for it.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Left-sided: <span class="math inline">\(P(T\le-2.26)\approx0.013\)</span>, half of the two-sided p-value. Right-sided: <span class="math inline">\(P(T\ge-2.26)\approx0.987\)</span>, one minus that half. Suppose a researcher chooses the tail after seeing the estimate. Then the 5% always lies on the side where the estimate happens to fall. The true Type I error rate is then about 10%, not 5%. A one-sided alternative must follow from the research question. The researcher must choose it before looking at the sample. The convention of this course: all tests are two-sided. In business questions a difference in either direction usually matters. Also, with this convention nobody can choose the tail after seeing the data.</p>
<p>Verification in R, with the objects of Task 1:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">left_sided =</span> <span class="fu">pt</span>(t_obs, <span class="at">df =</span> <span class="dv">99</span>), <span class="at">right_sided =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(t_obs, <span class="at">df =</span> <span class="dv">99</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> left_sided right_sided 
 0.01308894  0.98691106 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="task-6-repair-the-conclusion-6-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-6-repair-the-conclusion-6-minutes">Task 6: Repair the conclusion (6 minutes)</h3>
<p>The following conclusion about the row of Task 3 contains two errors. Find them and write a better conclusion.</p>
<blockquote class="blockquote">
<p>The coefficient is significant, so asking for more money causes founders to offer less equity, and there is less than a 0.1% chance that the null hypothesis is true.</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The p-value is not the probability that the null hypothesis is true, and a significant result does not show a cause. A better conclusion: “Each extra $100,000 requested goes together with about 0.29 percentage points less equity offered (95% interval from 0.18 to 0.40 points less). If the population coefficient were zero, an estimate this far from zero would occur in fewer than 0.1% of samples. Nobody assigned the requested amounts to the pitches at random, so this is an association, not a causal effect.”</p>
</div>
</div>
</div>
</section>
<section id="task-7-a-test-that-does-not-reject-12-minutes" class="level3">
<h3 class="anchored" data-anchor-id="task-7-a-test-that-does-not-reject-12-minutes">Task 7: A test that does not reject (12 minutes)</h3>
<p>An invented example. A supplier of snack vending machines states in its brochure that one machine sells 120 items per week on average. A founder is thinking about signing a contract with this supplier. She draws a random sample of 25 of the 800 machines of the supplier. Last week these 25 machines sold 114 items on average, with a standard deviation of <span class="math inline">\(s=20\)</span> items. Weekly sales per machine are roughly normally distributed. Supplied value: <span class="math inline">\(t_{0.975,\,24}=2.064\)</span>.</p>
<ol type="1">
<li>Test at the 5% level whether the mean weekly sales of all 800 machines differ from 120 items. Write the five steps.</li>
<li>The founder writes: “The test shows that the brochure is right. The mean is 120 items.” Assess this conclusion and write a better one.</li>
<li>Calculate the 95% confidence interval for the mean weekly sales. Parts 3 and 4 of the procedure are enough. Use the interval to support your answer to part 2.</li>
<li>State which error is possible after the decision of part 1, and describe it in the context of the founder.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The test in five steps:</p>
<ol type="1">
<li><strong>Hypotheses.</strong> <span class="math inline">\(H_0:\mu=120\)</span> against <span class="math inline">\(H_1:\mu\ne120\)</span>. Here <span class="math inline">\(\mu\)</span> is the mean number of items that one machine sold last week, among all 800 machines of the supplier. The significance level is <span class="math inline">\(\alpha=0.05\)</span>.</li>
<li><strong>Test statistic.</strong> <span class="math inline">\(T=(\bar X-120)/(S/\sqrt n)\)</span>. If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(T\)</span> has the t distribution with <span class="math inline">\(n-1=24\)</span> degrees of freedom. The sample is small, so the condition is that the population is roughly normal.</li>
<li><strong>Critical value and rejection region.</strong> The critical value is <span class="math inline">\(t_{0.975,\,24}=2.064\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t_{obs}\le-2.064\)</span> or <span class="math inline">\(t_{obs}\ge2.064\)</span>.</li>
<li><strong>Observed value.</strong> The standard error is <span class="math inline">\(s/\sqrt n=20/\sqrt{25}=4\)</span> items. Then <span class="math inline">\(t_{obs}=(114-120)/4=-1.50\)</span>.</li>
<li><strong>Conclusion.</strong> The observed value <span class="math inline">\(-1.50\)</span> lies between <span class="math inline">\(-2.064\)</span> and 2.064, so it does not lie in the rejection region. Do not reject <span class="math inline">\(H_0\)</span>. At the 5% level we cannot conclude that the mean weekly sales per machine differ from 120 items.</li>
</ol>
<p>The conclusion of the founder claims too much. “Do not reject <span class="math inline">\(H_0\)</span>” is not the same as “accept <span class="math inline">\(H_0\)</span>”. The sample gave too little evidence against 120 items. The sample did not show that the mean is 120 items. A better conclusion: “The sample of 25 machines gives no evidence at the 5% level that the mean weekly sales differ from the 120 items of the brochure. But the sample is also in line with clearly lower values.”</p>
<p>The interval supports this. The margin of error is <span class="math inline">\(2.064\times4=8.26\)</span> items, so the 95% interval is <span class="math inline">\((114-8.26,\ 114+8.26)=(105.74,\ 122.26)\)</span> items. It contains 120, and it also contains 106. A mean of 106 items would be 14 items below the brochure, about 12% less. With this sample, you cannot tell which of these two values is closer to the truth.</p>
<p>After a decision not to reject, only a Type II error is possible. Here it would mean: the mean weekly sales of the 800 machines differ from 120 items, but the test did not detect this difference. With 25 machines the standard error is 4 items. A larger sample has a smaller standard error and more power.</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>se_items <span class="ot">&lt;-</span> <span class="dv">20</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">25</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">se =</span> se_items, <span class="at">t_obs =</span> (<span class="dv">114</span> <span class="sc">-</span> <span class="dv">120</span>) <span class="sc">/</span> se_items,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">critical =</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">24</span>),</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">margin =</span> <span class="fl">2.064</span> <span class="sc">*</span> se_items,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> <span class="dv">114</span> <span class="sc">-</span> <span class="fl">2.064</span> <span class="sc">*</span> se_items, <span class="at">upper =</span> <span class="dv">114</span> <span class="sc">+</span> <span class="fl">2.064</span> <span class="sc">*</span> se_items,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">below_120_in_percent =</span> <span class="dv">100</span> <span class="sc">*</span> (<span class="dv">120</span> <span class="sc">-</span> <span class="dv">106</span>) <span class="sc">/</span> <span class="dv">120</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  se                t_obs             critical 
            4.000000            -1.500000             2.063899 
              margin                lower                upper 
            8.256000           105.744000           122.256000 
below_120_in_percent 
           11.666667 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p><span class="time-budget">Total practice time: about 50 minutes.</span></p>
<section id="timed-individual-practice-40-minutes" class="level3">
<h3 class="anchored" data-anchor-id="timed-individual-practice-40-minutes">Timed individual practice: 40 minutes</h3>
<p>Solve this task alone and with a timer, under exam conditions: no notes, no AI, only the formula sheet. An invented example. A random sample of 81 customers of a subscription service gives a mean spending of 42 euros and a sample SD of 9 euros. Of the 81 customers, 55 renew their subscription.</p>
<ol type="1">
<li>Let <span class="math inline">\(\mu\)</span> be the population mean spending. Test <span class="math inline">\(H_0:\mu=40\)</span> against <span class="math inline">\(H_1:\mu\ne40\)</span> at the 5% level, in five steps. Supplied value: <span class="math inline">\(t_{0.975,\,80}=1.990\)</span>.</li>
<li>Construct the 95% confidence interval for <span class="math inline">\(\mu\)</span> in five parts. Say in part 5 how the interval fits the decision of part 1.</li>
<li>Let <span class="math inline">\(p\)</span> be the population renewal proportion. Test <span class="math inline">\(H_0:p=0.60\)</span> against <span class="math inline">\(H_1:p\ne0.60\)</span> at the 5% level, in five steps. Then calculate the 95% confidence interval for <span class="math inline">\(p\)</span>. For the interval, parts 3 and 4 of the procedure are enough.</li>
<li>Supplied values: the two-sided p-value is 0.049 for the test of part 1 and 0.15 for the test of part 3. Show that the p-values give the same decisions as your critical values.</li>
<li>State the Type I error for each test. State which error is possible after each of your two decisions.</li>
<li>The sample mean lies 2 euros above 40 euros. Explain why the test result for the mean is still only just significant.</li>
<li>Write a report of six sentences about the mean spending. Write one sentence on each of these topics: the estimate, the uncertainty, the decision, the practical importance, the population, and causality.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Part 1, the test for the mean:</p>
<ol type="1">
<li><strong>Hypotheses.</strong> <span class="math inline">\(H_0:\mu=40\)</span> against <span class="math inline">\(H_1:\mu\ne40\)</span>, where <span class="math inline">\(\mu\)</span> is the mean spending of all customers, in euros. The significance level is <span class="math inline">\(\alpha=0.05\)</span>.</li>
<li><strong>Test statistic.</strong> <span class="math inline">\(T=(\bar X-40)/(S/\sqrt n)\)</span>. If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(T\)</span> has the t distribution with <span class="math inline">\(n-1=80\)</span> degrees of freedom. The sample of 81 customers is large.</li>
<li><strong>Critical value and rejection region.</strong> The critical value is <span class="math inline">\(t_{0.975,\,80}=1.990\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t_{obs}\le-1.990\)</span> or <span class="math inline">\(t_{obs}\ge1.990\)</span>.</li>
<li><strong>Observed value.</strong> The standard error is <span class="math inline">\(9/\sqrt{81}=1\)</span> euro. Then <span class="math inline">\(t_{obs}=(42-40)/1=2.00\)</span>.</li>
<li><strong>Conclusion.</strong> The observed value 2.00 is above 1.990, so it lies in the rejection region, but only just. Reject <span class="math inline">\(H_0\)</span>. At the 5% level we can conclude that the mean spending differs from 40 euros, and the positive sign places it above 40 euros.</li>
</ol>
<p>Part 2, the interval for the mean:</p>
<ol type="1">
<li><strong>Formula.</strong> <span class="math inline">\(\bar X\pm t_{1-\alpha/2,\,n-1}\,S/\sqrt n\)</span>. It may be used because <span class="math inline">\(n=81\)</span> is large.</li>
<li><strong>Given values.</strong> <span class="math inline">\(\bar x=42\)</span> euros, <span class="math inline">\(s=9\)</span> euros, <span class="math inline">\(n=81\)</span>, <span class="math inline">\(df=80\)</span>. The confidence level is 95%, so the critical value is <span class="math inline">\(t_{0.975,\,80}=1.990\)</span>.</li>
<li><strong>Calculations.</strong> The standard error is 1 euro. The margin of error is <span class="math inline">\(1.990\times1=1.99\)</span> euros.</li>
<li><strong>Interval.</strong> <span class="math inline">\((42-1.99,\ 42+1.99)=(40.01,\ 43.99)\)</span> euros.</li>
<li><strong>Conclusion.</strong> The value 40 euros lies just outside the interval. This fits the decision of part 1: at the 5% level the mean spending differs from 40 euros, and the interval lies above 40.</li>
</ol>
<p>Part 3, the test for the proportion:</p>
<ol type="1">
<li><strong>Hypotheses.</strong> <span class="math inline">\(H_0:p=0.60\)</span> against <span class="math inline">\(H_1:p\ne0.60\)</span>, where <span class="math inline">\(p\)</span> is the proportion of all customers who renew. The significance level is <span class="math inline">\(\alpha=0.05\)</span>.</li>
<li><strong>Test statistic.</strong> <span class="math inline">\(Z=(\widehat P-p_0)/\sqrt{p_0(1-p_0)/n}\)</span>. If <span class="math inline">\(H_0\)</span> is true, <span class="math inline">\(Z\)</span> is approximately <span class="math inline">\(N(0,1)\)</span>. The condition holds: <span class="math inline">\(81\times0.60=48.6\)</span> and <span class="math inline">\(81\times0.40=32.4\)</span> are both at least 10.</li>
<li><strong>Critical value and rejection region.</strong> The critical value is <span class="math inline">\(z_{0.975}=1.960\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(z_{obs}\le-1.960\)</span> or <span class="math inline">\(z_{obs}\ge1.960\)</span>.</li>
<li><strong>Observed value.</strong> The standard deviation of <span class="math inline">\(\widehat P\)</span> under <span class="math inline">\(H_0\)</span> is <span class="math inline">\(\sqrt{0.60\times0.40/81}=0.0544\)</span>. The estimate is <span class="math inline">\(\hat p=55/81=0.679\)</span>. Then <span class="math inline">\(z_{obs}=(0.679-0.60)/0.0544=1.45\)</span>.</li>
<li><strong>Conclusion.</strong> The observed value 1.45 lies between <span class="math inline">\(-1.960\)</span> and 1.960, so it does not lie in the rejection region. Do not reject <span class="math inline">\(H_0\)</span>. At the 5% level we cannot conclude that the renewal proportion differs from 60%.</li>
</ol>
<p>The interval for the proportion uses the standard error: <span class="math inline">\(\sqrt{0.679\times0.321/81}=0.0519\)</span>. The margin of error is <span class="math inline">\(1.960\times0.0519=0.102\)</span>, so the 95% interval is <span class="math inline">\((0.577,\ 0.781)\)</span>. It contains 0.60, in line with the decision of the test.</p>
<p>Part 4. The p-value 0.049 is below 0.05, so the test for the mean rejects <span class="math inline">\(H_0\)</span>. The p-value 0.15 is above 0.05, so the test for the proportion does not reject <span class="math inline">\(H_0\)</span>. These are the decisions of the critical values.</p>
<p>Part 5. A Type I error for the mean is to conclude that the mean spending differs from 40 euros when <span class="math inline">\(\mu=40\)</span>. A Type I error for the proportion is to conclude that the renewal proportion differs from 60% when <span class="math inline">\(p=0.60\)</span>. The test for the mean rejected <span class="math inline">\(H_0\)</span>, so only a Type I error is possible there. The test for the proportion did not reject <span class="math inline">\(H_0\)</span>, so only a Type II error is possible there.</p>
<p>Part 6. The standard error is 1 euro, so the sample mean lies exactly two standard errors above 40 euros. The critical value is 1.990. The decision depends on the difference divided by its standard error, not on the size of the difference alone.</p>
<p>Part 7. A model report: “The 81 sampled customers spend 42 euros on average, 2 euros above the benchmark of 40 euros. The 95% interval for the mean spending runs from 40.01 to 43.99 euros. The test rejects <span class="math inline">\(H_0:\mu=40\)</span> at the 5% level, but only just: the observed value is 2.00 against the critical value 1.990. A difference of 2 euros is 5% of the benchmark, so its importance depends on the margin per customer. The result holds for the population from which we drew the customers at random. It does not show what causes the higher spending.”</p>
<p>Verification in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>se_spending <span class="ot">&lt;-</span> <span class="dv">9</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">81</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">se =</span> se_spending, <span class="at">t_obs =</span> (<span class="dv">42</span> <span class="sc">-</span> <span class="dv">40</span>) <span class="sc">/</span> se_spending,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">critical =</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">80</span>), <span class="at">p_value =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="at">df =</span> <span class="dv">80</span>),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> <span class="dv">42</span> <span class="sc">-</span> <span class="fl">1.990</span> <span class="sc">*</span> se_spending, <span class="at">upper =</span> <span class="dv">42</span> <span class="sc">+</span> <span class="fl">1.990</span> <span class="sc">*</span> se_spending,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">difference_in_percent =</span> <span class="dv">100</span> <span class="sc">*</span> (<span class="dv">42</span> <span class="sc">-</span> <span class="dv">40</span>) <span class="sc">/</span> <span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   se                 t_obs              critical 
           1.00000000            2.00000000            1.99006342 
              p_value                 lower                 upper 
           0.04889385           40.01000000           43.99000000 
difference_in_percent 
           5.00000000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>p_hat_renew <span class="ot">&lt;-</span> <span class="dv">55</span> <span class="sc">/</span> <span class="dv">81</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>sd_null_renew <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fl">0.60</span> <span class="sc">*</span> <span class="fl">0.40</span> <span class="sc">/</span> <span class="dv">81</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>z_renew <span class="ot">&lt;-</span> (p_hat_renew <span class="sc">-</span> <span class="fl">0.60</span>) <span class="sc">/</span> sd_null_renew</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>se_renew <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(p_hat_renew <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat_renew) <span class="sc">/</span> <span class="dv">81</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">successes_H0 =</span> <span class="dv">81</span> <span class="sc">*</span> <span class="fl">0.60</span>, <span class="at">failures_H0 =</span> <span class="dv">81</span> <span class="sc">*</span> <span class="fl">0.40</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_hat =</span> p_hat_renew, <span class="at">sd_under_H0 =</span> sd_null_renew, <span class="at">z_obs =</span> z_renew,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fu">abs</span>(z_renew)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>successes_H0  failures_H0        p_hat  sd_under_H0        z_obs      p_value 
 48.60000000  32.40000000   0.67901235   0.05443311   1.45154948   0.14662692 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">standard_error =</span> se_renew, <span class="at">margin =</span> <span class="fl">1.960</span> <span class="sc">*</span> se_renew,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> p_hat_renew <span class="sc">-</span> <span class="fl">1.960</span> <span class="sc">*</span> se_renew,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">upper =</span> p_hat_renew <span class="sc">+</span> <span class="fl">1.960</span> <span class="sc">*</span> se_renew)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>standard_error         margin          lower          upper 
     0.0518729      0.1016709      0.5773415      0.7806832 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="check-your-understanding-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="check-your-understanding-5-minutes">Check your understanding (5 minutes)</h3>
<p>Complete from memory:</p>
<ol type="1">
<li>A 95% confidence interval is correctly described as …</li>
<li>Reject <span class="math inline">\(H_0:\mu=\mu_0\)</span> at the level <span class="math inline">\(\alpha\)</span> exactly when the confidence interval with level <span class="math inline">\(1-\alpha\)</span> …</li>
<li>A Type I error is … Power is …</li>
<li>“Do not reject <span class="math inline">\(H_0\)</span>” is different from “accept <span class="math inline">\(H_0\)</span>” because …</li>
<li>The test for a proportion divides by … The interval for a proportion uses …</li>
<li>A regression coefficient row tests …</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The result of a procedure that contains the fixed parameter in about 95% of random samples. It is never “a 95% chance that the parameter is inside”.</li>
<li>Does not contain <span class="math inline">\(\mu_0\)</span> (for a two-sided t test and a t interval from the same sample).</li>
<li>Rejecting <span class="math inline">\(H_0\)</span> when it is true. The probability of rejecting <span class="math inline">\(H_0\)</span> when <span class="math inline">\(H_1\)</span> is true.</li>
<li>A sample may fail to reject <span class="math inline">\(H_0\)</span> only because it is too small or too variable. A real difference from the value of <span class="math inline">\(H_0\)</span> can still exist.</li>
<li>The standard deviation of <span class="math inline">\(\widehat P\)</span> under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(\sqrt{p_0(1-p_0)/n}\)</span>. The standard error, <span class="math inline">\(\sqrt{\hat p(1-\hat p)/n}\)</span>.</li>
<li><span class="math inline">\(H_0:\beta_j=0\)</span> against <span class="math inline">\(H_1:\beta_j\ne0\)</span>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Two sentences about your own venture</span></p>
<p>Think of your EiA venture, or any business you know well. Take the one claim about it that you would most like to defend in front of an investor. Then write two sentences. First write the claim as <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span> about one parameter, with a realistic sample. State which error would cost you more: the false alarm (Type I) or the missed difference (Type II). Then say which interval would make you change a real business decision, and not just a slide in your pitch.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student venture that sells boxes of ready-made meals on campus. “I want to show that my average order value differs from the €9 break-even, so I test <span class="math inline">\(H_0:\mu=9\)</span> against <span class="math inline">\(H_1:\mu\ne9\)</span> on my next 150 orders. The missed difference would cost me more, because I would give up a business that can make a profit. An interval that lies entirely above €9 would make me buy a stock of packaging, not just update a slide.”</p>
</div>
</div>
</div>
<p>You can discuss this task, and any other task in this tutorial, with <strong>Tilly</strong>, the course AI assistant.</p>
</div>
</section>
<section id="more-practice" class="level3">
<h3 class="anchored" data-anchor-id="more-practice">More practice</h3>
<p>For extra exercises on the lectures that this tutorial covers, with worked solutions, ask <strong>Tilly</strong>, the course AI assistant. For example: “Give me an extra exercise for Tutorial 4. Show the solution only after I send my answer.”</p>
<p>You have now completed all lectures and tutorials of QM Basic. Next, use the formula sheet and attempt the <a href="../basic/mock-exam.html">QM Basic Mock Exam</a>. Continue to QM Intermediate when that course begins.</p>
<p><a href="../basic/formula-sheet.html">Continue to QM Basic Formula Sheet</a>.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../basic/b10-testing-errors-power.html" class="pagination-link" aria-label="Lecture 10: Testing decisions, errors, power, and a first look at regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and a first look at regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../basic/formula-sheet.html" class="pagination-link" aria-label="QM Basic Formula Sheet">
        <span class="nav-page-text"><span class="chapter-title">QM Basic Formula Sheet</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>