<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 1: Simple linear regression – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../intermediate/i02-assumptions-diagnostics.html" rel="next">
<link href="../intermediate/overview.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-130a4d33f88b74c424d8c0f2e9cca01a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../intermediate/overview.html">QM Intermediate: Course overview</a></li><li class="breadcrumb-item"><a href="../intermediate/i01-simple-linear-regression.html"><span class="chapter-title">Lecture 1: Simple linear regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 3: Normal models, sampling, and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and a first look at regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 4: Hypothesis tests, errors, and power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic Mock Exam</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate Mock Exam</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">QM Advanced</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Advanced: Course overview</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">External Video Guide</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#lecture-material" id="toc-lecture-material" class="nav-link" data-scroll-target="#lecture-material">Lecture material</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../intermediate/overview.html">QM Intermediate: Course overview</a></li><li class="breadcrumb-item"><a href="../intermediate/i01-simple-linear-regression.html"><span class="chapter-title">Lecture 1: Simple linear regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="i01" class="quarto-section-identifier"><span class="chapter-title">Lecture 1: Simple linear regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Lecture 1, you can</span></p>
<ul>
<li>explain what a simple regression model describes and what its parts mean</li>
<li>tell apart the error terms of the model and the residuals of a fit</li>
<li>explain how least squares chooses the best fitting line</li>
<li>fit a simple regression in R and interpret the slope and the intercept in the units of the data</li>
</ul>
</div>
<div class="driving-question">
<p><span class="label">Driving question</span></p>
<p class="dq-context">
A founder who asks for money in exchange for a share of the company puts a price on the whole company. This price is the claimed valuation: the amount asked divided by the share offered. Asking 100,000 dollars for 10 percent claims a valuation of 1 million dollars. The deal agreed on air has its own price, the agreed valuation: the amount paid divided by the share the sharks receive. A deal of 100,000 dollars for 20 percent agrees on a valuation of 0.5 million dollars. The slope of the regression line of the agreed valuation on the claimed valuation tells a founder how many dollars of agreed valuation go, on average, with one more dollar of claimed valuation.
</p>
<p>Among Shark Tank pitches that ended in a deal for a share of the company, how does the agreed valuation relate to the claimed valuation: how many dollars of agreed valuation go, on average, with one more dollar of claimed valuation?</p>
</div>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p>Do all the preparation below before class.</p>
<div class="video-prep">
<p><span class="label">Video preparation</span><br> Watch Stanford Statistical Learning <a href="https://www.youtube.com/watch?v=vCHtY6Me5FI&amp;list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&amp;index=9">3.1 Simple Linear Regression</a>. Focus on the population line, the fitted line, and least squares. The video writes RSS for the quantity this book calls SSE, the sum of squared residuals. All links are also listed in the <a href="../resources/video-guide.html">External Video Guide</a>. The videos explain key ideas in another way and can use a different notation. The lecture material and its notation always come first.</p>
</div>
<p><strong>Warm up: five quantities from QM Basic.</strong> QM Intermediate builds directly on five quantities from the end of QM Basic: estimate, standard error, t statistic (R calls it t value), p-value, confidence interval. The sections for Lectures 9 and 10 of the <a href="../basic/formula-sheet.html#formula-l9">QM Basic formula sheet</a> list their formulas. With the sheet open, answer the five items below.</p>
<ol type="1">
<li>A study reports an estimate of 12 with standard error 4. What is the t statistic for testing whether the underlying quantity is zero?</li>
<li>With a large sample, what critical value goes into a 95% confidence interval?</li>
<li>Compute that 95% interval for the estimate in item 1.</li>
<li>The p-value is 0.003. Complete: “If the true value were zero, …”</li>
<li>Which of the five quantities has the same units as the estimate itself?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your preparation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(t = 12/4 = 3\)</span>.</li>
<li>About 1.96. The critical value <span class="math inline">\(t_{0.975,\,df}\)</span> is close to <span class="math inline">\(z_{0.975}=1.96\)</span> when the degrees of freedom are large.</li>
<li><span class="math inline">\(12 \pm 1.96 \times 4 = (4.2,\; 19.8)\)</span>.</li>
<li>“… an estimate at least this far from zero would occur in about 0.3% of samples.”</li>
<li>The standard error and both interval endpoints. The t statistic and p-value are unit-free.</li>
</ol>
</div>
</div>
</div>
<p><strong>Define the variables.</strong> The data of this course are 1,441 pitches from the television show Shark Tank, where founders ask investors (the sharks) for money in exchange for a share of their company. This lecture uses the 874 pitches that ended in a deal for a share of the company. It measures all money in <strong>millions of dollars</strong>:</p>
<ul>
<li><span class="math inline">\(X_i\)</span>: the valuation the founder claimed, in $ millions. Asking $100,000 for 10% claims $1 million, so <span class="math inline">\(X_i = 1\)</span>.</li>
<li><span class="math inline">\(Y_i\)</span>: the valuation agreed on air (during the show), in $ millions. A deal of $100,000 for 20% values the company at $0.5 million, so <span class="math inline">\(Y_i = 0.5\)</span>.</li>
</ul>
<p><strong>Predict.</strong> Answer this question before you come to class: what are the sign and the unit of the slope in a regression of the agreed valuation on the claimed valuation, and is the slope above or below 1? Choose one answer before class. The lecture material gives the correct answer.</p>
<p><span class="shark-tag">Shark Tank data</span> <strong>R warm-up.</strong> Every Intermediate lecture has a short R warm-up: you run a few lines of R and bring the output to class. This week, load the data, keep the deals for a share of the company, and plot the agreed valuation against the claimed valuation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">subset</span>(sharks, deal_on_show <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> deal_equity_pct <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>claimed_m <span class="ot">&lt;-</span> vals<span class="sc">$</span>requested_valuation_usd <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>agreed_m <span class="ot">&lt;-</span> vals<span class="sc">$</span>deal_valuation_usd <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vals<span class="sc">$</span>claimed_m, vals<span class="sc">$</span>agreed_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Code along (bring your laptop).</strong> Bring a charged laptop with RStudio and the course project open. The code of the lecture is in this chapter, ready to copy, so you can run each step yourself during the lecture and get the same numbers and figures.</p>
<p>If you are not sure about lines, slopes, intercepts, or subscripts, review <a href="../resources/math-refresher.html#straight-lines-slopes-and-intercepts">Mathematics Refresher: straight lines, slopes, and intercepts</a> and <a href="../resources/math-refresher.html#subscripts-and-indices">subscripts and indices</a>.</p>
</section>
<section id="lecture-material" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="lecture-material">Lecture material</h2>
<p>This section fits the regression line to the valuations in the Shark Tank data. Many straight lines can be drawn through a cloud of points. The regression line is the one that fits best by the least-squares criterion: the sum of its squared vertical distances to the points (the residuals) is as small as possible. The section explains what this line describes, how it is calculated, and how to read its slope and its intercept.</p>
<p class="concept-video">
<strong>Stanford explanation (review):</strong> <a href="https://www.youtube.com/watch?v=vCHtY6Me5FI">3.1 Simple Linear Regression</a>.
</p>
<section id="start-with-a-founders-question" class="level3">
<h3 class="anchored" data-anchor-id="start-with-a-founders-question">Start with a founder’s question</h3>
<p>A founder who asks $100,000 for 10% of the company claims a valuation of $1 million (<code>claimed_m = 1</code>). If the sharks pay $100,000 for 20%, the agreed valuation is $0.5 million (<code>agreed_m = 0.5</code>). The question is how the agreed valuation relates to the claimed valuation across many deals. Your warm-up plot shows the answer as a cloud of points. The regression line summarises this cloud, and its slope gives one number: the difference in the average agreed valuation per $1 million more of claimed valuation.</p>
</section>
<section id="begin-with-the-data" class="level3">
<h3 class="anchored" data-anchor-id="begin-with-the-data">Begin with the data</h3>
<p><span class="shark-tag">Shark Tank data</span> The data are the Shark Tank teaching file. One row is one pitch on the television show: 1,441 pitches from Seasons 1 to 16. This lecture uses the 874 pitches that ended in a deal for a share of the company, and two variables. The valuation claimed by the founder (<code>requested_valuation_usd</code>) is the amount asked divided by the share offered. The valuation agreed on air (<code>deal_valuation_usd</code>) is the amount paid divided by the share the sharks receive. The <a href="../basic/b01-introduction-data-analysis.html#b01-variable-table">variable table in Basic Lecture 1</a> describes every variable of the file.</p>
<p>The code below is the warm-up code. It keeps the deals for a share of the company and creates both valuations in $ millions. Of the 882 deals, 8 gave the sharks no share of the company. These 8 deals have no valuation, so we leave them out. This leaves 874 deals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(sharks<span class="sc">$</span>deal_on_show <span class="sc">==</span> <span class="dv">1</span>)   <span class="co"># all pitches that ended in a deal</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 882</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">subset</span>(sharks, deal_on_show <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> deal_equity_pct <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>claimed_m <span class="ot">&lt;-</span> vals<span class="sc">$</span>requested_valuation_usd <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>agreed_m <span class="ot">&lt;-</span> vals<span class="sc">$</span>deal_valuation_usd <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(vals)                      <span class="co"># deals for a share of the company</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 874</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">subset</span>(sharks, deal_on_show <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> deal_equity_pct <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>claimed_m <span class="ot">&lt;-</span> vals<span class="sc">$</span>requested_valuation_usd <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>agreed_m <span class="ot">&lt;-</span> vals<span class="sc">$</span>deal_valuation_usd <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>val_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(agreed_m <span class="sc">~</span> claimed_m, <span class="at">data =</span> vals)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>display_vals <span class="ot">&lt;-</span> <span class="fu">subset</span>(vals, claimed_m <span class="sc">&lt;=</span> <span class="dv">10</span> <span class="sc">&amp;</span> agreed_m <span class="sc">&lt;=</span> <span class="dv">10</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(display_vals, <span class="fu">aes</span>(<span class="at">x =</span> claimed_m, <span class="at">y =</span> agreed_m)) <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.45</span>, <span class="at">size =</span> <span class="fl">1.6</span>, <span class="at">colour =</span> <span class="st">"#009E73"</span>) <span class="sc">+</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">coef</span>(val_model)[<span class="dv">1</span>],</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> <span class="fu">coef</span>(val_model)[<span class="dv">2</span>],</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">colour =</span> <span class="st">"#5B6976"</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">6.8</span>, <span class="at">y =</span> <span class="fl">7.5</span>, <span class="at">label =</span> <span class="st">"agreed = claimed"</span>,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">colour =</span> <span class="st">"#5B6976"</span>, <span class="at">size =</span> <span class="fl">3.2</span>) <span class="sc">+</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.3</span>, <span class="at">y =</span> <span class="fl">9.85</span>,</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"Fitted regression (estimated on all 874 deals)"</span>,</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">10.3</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">10.3</span>), <span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Valuation claimed by the founder ($ millions)"</span>,</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Valuation agreed on air ($ millions)"</span>) <span class="sc">+</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-i01-scatter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-i01-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="i01-simple-linear-regression_files/figure-html/fig-i01-scatter-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-i01-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: Valuation agreed on air against the valuation claimed by the founder, for the 874 deals for a share of the company. Both axes in $ millions. The display zooms in on valuations up to $10 million (819 of 874 deals). The orange line is the fitted regression line, calculated from all 874 deals. On the grey dashed line the agreed valuation equals the claimed one.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each point in <a href="#fig-i01-scatter" class="quarto-xref">Figure&nbsp;<span>11.1</span></a> is one deal. The claimed valuation is on the horizontal axis and the agreed valuation is on the vertical axis. Both axes use units of $1 million. The orange line is the regression line, the line that fits the points best by the least-squares criterion. It shows the average agreed valuation at each claimed valuation, not the result of every deal. The rest of this lecture explains this criterion and how to read the line.</p>
<p>The figure shows 819 of the 874 deals, so that the area with many points is easy to read. The figure leaves out the 55 deals with a valuation above $10 million on at least one axis. R still uses these deals to calculate the orange line. Always say when a graph is zoomed in, that is, when it shows only part of the data. Otherwise readers may think that the displayed range is the complete data.</p>
<p>The code below counts the deals inside the zoomed area. It also gives the percentage of deals in which the agreed valuation is below, equal to, or above the claimed valuation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(vals<span class="sc">$</span>claimed_m <span class="sc">&lt;=</span> <span class="dv">10</span> <span class="sc">&amp;</span> vals<span class="sc">$</span>agreed_m <span class="sc">&lt;=</span> <span class="dv">10</span>)   <span class="co"># deals shown in the figure</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 819</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">c</span>(<span class="at">below =</span> <span class="fu">mean</span>(vals<span class="sc">$</span>agreed_m <span class="sc">&lt;</span> vals<span class="sc">$</span>claimed_m),</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">equal =</span> <span class="fu">mean</span>(vals<span class="sc">$</span>agreed_m <span class="sc">==</span> vals<span class="sc">$</span>claimed_m),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">above =</span> <span class="fu">mean</span>(vals<span class="sc">$</span>agreed_m <span class="sc">&gt;</span> vals<span class="sc">$</span>claimed_m)), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>below equal above 
 81.5  12.8   5.7 </code></pre>
</div>
</div>
<p>Most points lie below the grey dashed line. In 81.5% of the deals the agreed valuation is lower than the valuation the founder claimed. In 12.8% it is the same, and in 5.7% it is higher. The sharks usually pay the amount that the founder asked for, but they take a larger share of the company for it. In this way the agreed valuation ends up lower than the claimed valuation.</p>
</section>
<section id="units-first-money-in-millions" class="level3">
<h3 class="anchored" data-anchor-id="units-first-money-in-millions">Units first: money in millions</h3>
<p>Every number in this lecture has the units of these two columns. So we fix the units before we fit any model. We divide the raw dollar valuations by 1,000,000: a claimed valuation of $2,000,000 becomes <code>claimed_m = 2</code>. This change in the units of measurement does not change the relationship between the two valuations. <a href="#exm-i01-units" class="quarto-xref">Example&nbsp;<span>11.2</span></a>, after the model is fitted, shows what happens to the coefficients when the units change.</p>
</section>
<section id="the-population-model-and-the-conditional-mean" class="level3">
<h3 class="anchored" data-anchor-id="the-population-model-and-the-conditional-mean">The population model and the conditional mean</h3>
<p>A regression has an <strong>outcome</strong> <span class="math inline">\(Y\)</span>, the variable we want to describe, and a <strong>predictor</strong> <span class="math inline">\(X\)</span>, the variable we describe it with. Here the outcome is the agreed valuation and the predictor is the claimed valuation. Other books, R help pages, and AI assistants use other names for the same things. The outcome is also called the dependent variable or the response. The predictor is also called the independent variable, the explanatory variable, or the regressor. This book always says outcome and predictor. The simple linear regression model is</p>
<p><span class="math display">\[
Y_i=\beta_0+\beta_1X_i+\varepsilon_i.
\]</span></p>
<ul>
<li><span class="math inline">\(Y_i\)</span> is the outcome for observation <span class="math inline">\(i\)</span> (here: deal <span class="math inline">\(i\)</span>).</li>
<li><span class="math inline">\(X_i\)</span> is the predictor for observation <span class="math inline">\(i\)</span>.</li>
<li><span class="math inline">\(\beta_0\)</span> is the population intercept.</li>
<li><span class="math inline">\(\beta_1\)</span> is the population slope.</li>
<li><span class="math inline">\(\varepsilon_i\)</span> is the error term: the part of <span class="math inline">\(Y_i\)</span> that <span class="math inline">\(\beta_0+\beta_1X_i\)</span> does not capture. Nobody observes it.</li>
</ul>
<p>The intercept and the slope are the two coefficients of the model.</p>
<p>The model is a statement about averages. The <strong>conditional mean</strong> <span class="math inline">\(E[Y\mid X=x]\)</span> is the average outcome among observations whose predictor equals <span class="math inline">\(x\)</span>. An example is the average agreed valuation among deals in which the founder claimed exactly $2 million. The model says that this average follows a line:</p>
<p><span class="math display">\[
E[Y\mid X=x]=\beta_0+\beta_1x.
\]</span></p>
<p>If you compare two values of the predictor that are one unit apart, the two averages differ by the slope:</p>
<p><span class="math display">\[
\beta_1
=E[Y\mid X=x+1]-E[Y\mid X=x].
\]</span></p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Slope</strong> <span class="math inline">\(\beta_1\)</span>. The difference in the average outcome <span class="math inline">\(Y\)</span> that is associated with a one-unit difference in the predictor <span class="math inline">\(X\)</span>. Its unit is units of <span class="math inline">\(Y\)</span> per unit of <span class="math inline">\(X\)</span>.</p>
<p><strong>Intercept</strong> <span class="math inline">\(\beta_0\)</span>. The average outcome <span class="math inline">\(Y\)</span> at <span class="math inline">\(X=0\)</span>. It has the units of <span class="math inline">\(Y\)</span>, and it has a useful meaning only if <span class="math inline">\(X=0\)</span> lies inside the range of the data.</p>
</div>
<p>Here the slope is the difference in the average agreed valuation between deals whose claimed valuations differ by $1 million. The words “associated with” matter. A regression line compares averages across groups of observed deals. It does not say what would happen if one founder changed their claimed valuation. The box “What this fitted line can and cannot say” later in this section explains this limit.</p>
<p>You can read the slope as an effect only under one condition: nothing outside the model affects both the claimed and the agreed valuation. Lecture 2 calls this condition zero conditional mean of the error, with no omitted confounder.</p>
</section>
<section id="error-terms-versus-residuals" class="level3">
<h3 class="anchored" data-anchor-id="error-terms-versus-residuals">Error terms versus residuals</h3>
<p>The population line <span class="math inline">\(\beta_0+\beta_1x\)</span> is part of the model. Nobody can observe it, because <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are unknown. In the words of <a href="../basic/b07-samples-estimators.html">Basic Lecture 7</a>, they are parameters. What we calculate from the data is the fitted line. Its coefficients <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> have a hat symbol on top. The hat marks an estimate: these are the values that we calculate from the data for the unknown <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. The rule that turns the data into these numbers is the estimator. Here it is least squares, explained in the next section. The fitted line is</p>
<p><span class="math display">\[
\widehat Y_i=\hat\beta_0+\hat\beta_1X_i.
\]</span></p>
<p>Because least squares chooses it, the fitted line is also called the least-squares line or the regression line. The three names mean the same line.</p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>Error term</strong> <span class="math inline">\(\varepsilon_i\)</span>. The distance of observation <span class="math inline">\(i\)</span> from the population line: <span class="math inline">\(\varepsilon_i=Y_i-(\beta_0+\beta_1X_i)\)</span>. It belongs to the model and is never observed.</p>
<p><strong>Fitted value</strong> <span class="math inline">\(\widehat Y_i\)</span>. The value on the fitted line at the predictor value of observation <span class="math inline">\(i\)</span>: <span class="math inline">\(\widehat Y_i=\hat\beta_0+\hat\beta_1X_i\)</span>.</p>
<p><strong>Residual</strong> <span class="math inline">\(e_i\)</span>. The observed outcome minus the fitted value: <span class="math inline">\(e_i=Y_i-\widehat Y_i\)</span>. It is the vertical distance from the point to the fitted line, positive above the line and negative below it. It is calculated from the data.</p>
</div>
<p>The error term <span class="math inline">\(\varepsilon_i\)</span> and the residual <span class="math inline">\(e_i\)</span> have the same role in the two equations, but they are different quantities, as <a href="#fig-i01-error-residual" class="quarto-xref">Figure&nbsp;<span>11.2</span></a> shows. This book uses “error term” only for <span class="math inline">\(\varepsilon_i\)</span> and “residual” only for <span class="math inline">\(e_i\)</span>.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">101</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>x_er <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">2.2</span>, <span class="fl">3.4</span>, <span class="fl">4.6</span>, <span class="fl">5.8</span>, <span class="fl">7.0</span>, <span class="fl">8.2</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>beta0_true <span class="ot">&lt;-</span> <span class="dv">1</span>; beta1_true <span class="ot">&lt;-</span> <span class="fl">0.8</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>y_er <span class="ot">&lt;-</span> beta0_true <span class="sc">+</span> beta1_true <span class="sc">*</span> x_er <span class="sc">+</span> <span class="fu">c</span>(<span class="fl">1.3</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="fl">0.9</span>, <span class="sc">-</span><span class="fl">0.8</span>, <span class="fl">1.6</span>, <span class="sc">-</span><span class="fl">1.2</span>, <span class="fl">0.4</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>fit_er <span class="ot">&lt;-</span> <span class="fu">lm</span>(y_er <span class="sc">~</span> x_er)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>panel_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Population line (unknown)"</span>, <span class="st">"Fitted line (computed)"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>er_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">panel =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(panel_names, <span class="at">each =</span> <span class="dv">7</span>), <span class="at">levels =</span> panel_names),</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">rep</span>(x_er, <span class="dv">2</span>),</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">rep</span>(y_er, <span class="dv">2</span>),</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">line_y =</span> <span class="fu">c</span>(beta0_true <span class="sc">+</span> beta1_true <span class="sc">*</span> x_er, <span class="fu">fitted</span>(fit_er))</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>line_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">panel =</span> <span class="fu">factor</span>(panel_names, <span class="at">levels =</span> panel_names),</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">intercept =</span> <span class="fu">c</span>(beta0_true, <span class="fu">coef</span>(fit_er)[<span class="dv">1</span>]),</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">slope =</span> <span class="fu">c</span>(beta1_true, <span class="fu">coef</span>(fit_er)[<span class="dv">2</span>])</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>label_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">panel =</span> <span class="fu">factor</span>(panel_names, <span class="at">levels =</span> panel_names),</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> x_er[<span class="dv">5</span>] <span class="sc">+</span> <span class="fl">0.45</span>,</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>((y_er[<span class="dv">5</span>] <span class="sc">+</span> beta0_true <span class="sc">+</span> beta1_true <span class="sc">*</span> x_er[<span class="dv">5</span>]) <span class="sc">/</span> <span class="dv">2</span>,</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>        (y_er[<span class="dv">5</span>] <span class="sc">+</span> <span class="fu">fitted</span>(fit_er)[<span class="dv">5</span>]) <span class="sc">/</span> <span class="dv">2</span>),</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">lab =</span> <span class="fu">c</span>(<span class="st">"epsilon[i]"</span>, <span class="st">"e[i]"</span>)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(er_df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">data =</span> line_df[<span class="dv">1</span>, ],</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">intercept =</span> intercept, <span class="at">slope =</span> slope),</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>              <span class="at">colour =</span> <span class="st">"#5B6976"</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">data =</span> line_df[<span class="dv">2</span>, ],</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">intercept =</span> intercept, <span class="at">slope =</span> slope),</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>              <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> x, <span class="at">yend =</span> line_y),</span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>               <span class="at">colour =</span> <span class="st">"#0072B2"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.6</span>, <span class="at">colour =</span> <span class="st">"#009E73"</span>) <span class="sc">+</span></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> label_df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">label =</span> lab),</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>            <span class="at">parse =</span> <span class="cn">TRUE</span>, <span class="at">colour =</span> <span class="st">"#0072B2"</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">9.4</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">9.4</span>)) <span class="sc">+</span></span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> panel) <span class="sc">+</span></span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Predictor X"</span>, <span class="at">y =</span> <span class="st">"Outcome Y"</span>) <span class="sc">+</span></span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>),</span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-i01-error-residual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-i01-error-residual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="i01-simple-linear-regression_files/figure-html/fig-i01-error-residual-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-i01-error-residual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.2: The same seven observations twice. Left: the unknown population line with the error terms ε (distances to the population line). Right: the fitted line with the residuals e (distances to the fitted line). Only the right panel can be calculated from data.
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><span class="math inline">\(\varepsilon_i = Y_i - (\beta_0+\beta_1X_i)\)</span> measures the distance to the <strong>population</strong> line. Because <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are unknown, <span class="math inline">\(\varepsilon_i\)</span> is never observed.</li>
<li><span class="math inline">\(e_i = Y_i - (\hat\beta_0+\hat\beta_1X_i)\)</span> measures the distance to the <strong>fitted</strong> line. It is computed from data, one number per observation.</li>
</ul>
<p>We never see the error terms. The residuals are what we can calculate in their place, so they are estimates of the error terms and not the error terms themselves. Lecture 2 uses residuals to check the model.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: which object is observable?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Only the residual <span class="math inline">\(e_i\)</span>. The observed data give <span class="math inline">\(Y_i\)</span> and <span class="math inline">\(X_i\)</span>. The fitted line gives <span class="math inline">\(\widehat Y_i\)</span>, so <span class="math inline">\(e_i = Y_i - \widehat Y_i\)</span> is a computable number. The error term <span class="math inline">\(\varepsilon_i\)</span> depends on the unknown population coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, so we can think about it but we can never calculate it.</p>
</div>
</div>
</div>
</section>
<section id="least-squares-why-vertical-why-squared" class="level3">
<h3 class="anchored" data-anchor-id="least-squares-why-vertical-why-squared">Least squares: why vertical, why squared</h3>
<p>Many lines can be drawn through a cloud of points. To choose one, we need a criterion: a number that says how far a line lies from the points. The residuals measure these distances. Each residual is measured vertically, in the units of the outcome: millions of dollars of agreed valuation, not distance on the page. We measure vertically because we use the line to describe <span class="math inline">\(Y\)</span> at a given <span class="math inline">\(X\)</span>. So the distance that counts is a distance in <span class="math inline">\(Y\)</span>.</p>
<p>Adding up the residuals is not a useful criterion, because positive and negative residuals cancel. Adding up their absolute values avoids this, but then there is no simple formula for the best line. Squared residuals are never negative, they count a large residual more heavily than a small one, and they lead to a direct formula for the best line. For these reasons squaring is the standard choice. But it is not the only possible choice.</p>
<div class="definition-box">
<p><span class="label">Definition</span></p>
<p><strong>SSE.</strong> The sum of the squared residuals of a line. The letters come from its usual name, “sum of squared errors”, although it adds up squared residuals.</p>
<p><span class="math display">\[
\operatorname{SSE}=\sum_{i=1}^{n}e_i^2
=\sum_{i=1}^{n}(Y_i-\hat\beta_0-\hat\beta_1X_i)^2.
\]</span></p>
<p><strong>Ordinary least squares (OLS).</strong> The rule that chooses the intercept <span class="math inline">\(\hat\beta_0\)</span> and the slope <span class="math inline">\(\hat\beta_1\)</span> so that SSE is as small as possible. The resulting line is called the least-squares line.</p>
</div>
<section id="try-it-yourself-make-sse-as-small-as-you-can" class="level4">
<h4 class="anchored" data-anchor-id="try-it-yourself-make-sse-as-small-as-you-can">Try it yourself: make SSE as small as you can</h4>
<p>Drag either square handle to move the line. The vertical dashed lines are the residuals. The SSE below the figure changes every time you move the line. Find the line with the smallest SSE that you can. Then click “Show least-squares fit” to see the line with the smallest possible SSE, and compare it with your best attempt.</p>
<style>
.ls-lab {
  background: #fff;
  border: 1px solid #d5dbe0;
  border-radius: 8px;
  margin: 1.2em 0 1.5em;
  padding: 1em;
}
.ls-lab-heading,
.ls-actions {
  align-items: center;
  display: flex;
  flex-wrap: wrap;
  gap: 0.8em 1.2em;
  justify-content: space-between;
}
.ls-lab svg {
  display: block;
  height: auto;
  margin: 0.5em auto;
  max-width: 700px;
  touch-action: none;
  width: 100%;
}
.ls-controls {
  display: grid;
  gap: 0.8em 1.4em;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  margin: 0.6em 0 1em;
}
.ls-controls label {
  color: #17324d;
  font-size: 0.9em;
  font-weight: 600;
}
.ls-controls input {
  display: block;
  margin-top: 0.3em;
  width: 100%;
}
.ls-actions button {
  background: #17324d;
  border: 1px solid #17324d;
  border-radius: 4px;
  color: #fff;
  cursor: pointer;
  font: inherit;
  padding: 0.45em 0.8em;
}
.ls-actions button + button {
  background: #fff;
  color: #17324d;
}
.ls-caption {
  color: #53606b;
  font-size: 0.9em;
  margin-bottom: 0;
}
.ls-axis { stroke: #65727e; stroke-width: 1.2; }
.ls-tick { fill: #53606b; font-size: 13px; }
.ls-label { fill: #263b4b; font-size: 15px; }
.ls-point { fill: #0072b2; stroke: #17324d; stroke-width: 1; }
.ls-fit-line { stroke: #d55e00; stroke-width: 3; }
.ls-residual { stroke: #755f93; stroke-width: 2; stroke-dasharray: 4 3; }
.ls-handle { fill: #f0e442; stroke: #17324d; stroke-width: 2; cursor: ns-resize; }
.ls-handle:focus { outline: 3px solid #56b4e9; outline-offset: 2px; }
@media (max-width: 767px) {
  .ls-controls {
    grid-template-columns: 1fr;
  }
}
</style>
<div id="least-squares-lab" class="ls-lab" role="group" aria-labelledby="ls-lab-title">
<div class="ls-lab-heading">
<p><strong id="ls-lab-title">Least-squares line lab</strong> <span id="ls-equation" aria-live="polite"></span></p>
</div>
<svg id="ls-svg" viewbox="0 0 700 390" role="img" aria-label="Scatterplot with a draggable line and vertical residual segments">
</svg>
<div class="ls-controls">
<p><label>Line height at x = 1 <input id="ls-left" type="range" min="0" max="10" step="0.05" value="3"> </label> <label>Line height at x = 9 <input id="ls-right" type="range" min="0" max="10" step="0.05" value="7"> </label></p>
</div>
<div class="ls-actions">
<button id="ls-best" type="button">
Show least-squares fit
</button>
<button id="ls-reset" type="button">
Try another line
</button>
<p><strong id="ls-sse" aria-live="polite"></strong></p>
</div>
<p class="ls-caption">
Squaring makes every contribution to SSE zero or positive. A residual that is twice as long adds four times as much to SSE.
</p>
</div>
<script>
(function () {
  const root = document.getElementById("least-squares-lab");
  if (!root || root.dataset.ready) return;
  root.dataset.ready = "true";
  const svg = root.querySelector("#ls-svg");
  const left = root.querySelector("#ls-left");
  const right = root.querySelector("#ls-right");
  const equation = root.querySelector("#ls-equation");
  const sseText = root.querySelector("#ls-sse");
  const points = [
    {x:1, y:1.8}, {x:2, y:1.4}, {x:3, y:3.2},
    {x:4, y:4.8}, {x:5, y:4.2}, {x:6, y:6.8},
    {x:7, y:6.4}, {x:8, y:8.6}, {x:9, y:8.2}
  ];
  const ns = "http://www.w3.org/2000/svg";
  const box = {left:58, right:680, top:18, bottom:336};
  const sx = x => box.left + x / 10 * (box.right - box.left);
  const sy = y => box.bottom - y / 10 * (box.bottom - box.top);
  const add = (name, attrs, parent=svg) => {
    const el = document.createElementNS(ns, name);
    Object.entries(attrs).forEach(([k,v]) => el.setAttribute(k, v));
    parent.appendChild(el); return el;
  };
  add("line", {x1:box.left, y1:box.bottom, x2:box.right, y2:box.bottom, class:"ls-axis"});
  add("line", {x1:box.left, y1:box.top, x2:box.left, y2:box.bottom, class:"ls-axis"});
  [0,2,4,6,8,10].forEach(v => {
    add("line", {x1:sx(v), y1:box.bottom, x2:sx(v), y2:box.bottom+6, class:"ls-axis"});
    const tx=add("text", {x:sx(v), y:box.bottom+25, class:"ls-tick"}); tx.textContent=v;
    add("line", {x1:box.left-6, y1:sy(v), x2:box.left, y2:sy(v), class:"ls-axis"});
    const ty=add("text", {x:box.left-12, y:sy(v)+4, class:"ls-tick", "text-anchor":"end"}); ty.textContent=v;
  });
  const xl=add("text", {x:(box.left+box.right)/2, y:382, class:"ls-label", "text-anchor":"middle"}); xl.textContent="Predictor x";
  const yl=add("text", {x:16, y:(box.top+box.bottom)/2, class:"ls-label", transform:`rotate(-90 16 ${(box.top+box.bottom)/2})`, "text-anchor":"middle"}); yl.textContent="Outcome y";
  const residualGroup=add("g", {class:"ls-residuals"});
  const line=add("line", {class:"ls-fit-line"});
  const handleLeft=add("rect", {width:16, height:16, rx:2, class:"ls-handle", "aria-hidden":"true"});
  const handleRight=add("rect", {width:16, height:16, rx:2, class:"ls-handle", "aria-hidden":"true"});
  points.forEach(p => add("circle", {cx:sx(p.x), cy:sy(p.y), r:5.5, class:"ls-point"}));
  const meanX=points.reduce((a,p)=>a+p.x,0)/points.length;
  const meanY=points.reduce((a,p)=>a+p.y,0)/points.length;
  const bestSlope=points.reduce((a,p)=>a+(p.x-meanX)*(p.y-meanY),0) /
                  points.reduce((a,p)=>a+(p.x-meanX)**2,0);
  const bestIntercept=meanY-bestSlope*meanX;
  const fitFromHeights = () => {
    const y1=Number(left.value), y9=Number(right.value);
    const slope=(y9-y1)/8, intercept=y1-slope;
    return {intercept, slope};
  };
  function draw() {
    const {intercept, slope}=fitFromHeights();
    residualGroup.replaceChildren();
    let sse=0;
    points.forEach(p => {
      const fitted=intercept+slope*p.x;
      sse+=(p.y-fitted)**2;
      add("line", {x1:sx(p.x), y1:sy(p.y), x2:sx(p.x), y2:sy(fitted), class:"ls-residual"}, residualGroup);
    });
    line.setAttribute("x1", sx(0)); line.setAttribute("y1", sy(intercept));
    line.setAttribute("x2", sx(10)); line.setAttribute("y2", sy(intercept+10*slope));
    [[handleLeft,1,Number(left.value)],[handleRight,9,Number(right.value)]].forEach(([h,x,y])=>{
      h.setAttribute("x",sx(x)-8); h.setAttribute("y",sy(y)-8);
    });
    equation.textContent=`ŷ = ${intercept.toFixed(2)} ${slope<0?"−":"+"} ${Math.abs(slope).toFixed(2)}x`;
    sseText.textContent=`SSE = ${sse.toFixed(2)}`;
  }
  function drag(handle, slider) {
    handle.addEventListener("pointerdown", event => {
      handle.setPointerCapture(event.pointerId);
      const move = e => {
        const rect=svg.getBoundingClientRect();
        const svgY=(e.clientY-rect.top)*390/rect.height;
        const y=Math.max(0,Math.min(10,(box.bottom-svgY)*10/(box.bottom-box.top)));
        slider.value=y.toFixed(2); draw();
      };
      handle.addEventListener("pointermove", move);
      handle.addEventListener("pointerup", () => handle.removeEventListener("pointermove", move), {once:true});
    });
  }
  drag(handleLeft,left); drag(handleRight,right);
  root.querySelector("#ls-best").addEventListener("click",()=>{
    left.value=(bestIntercept+bestSlope).toFixed(2);
    right.value=(bestIntercept+9*bestSlope).toFixed(2); draw();
  });
  root.querySelector("#ls-reset").addEventListener("click",()=>{
    left.value=3; right.value=7; draw();
  });
  draw();
})();
</script>
</section>
<section id="the-formulas-for-the-slope-and-the-intercept" class="level4">
<h4 class="anchored" data-anchor-id="the-formulas-for-the-slope-and-the-intercept">The formulas for the slope and the intercept</h4>
<p>You do not have to find the least-squares line by trying many lines. There is a direct formula for the slope and one for the intercept, so no search is needed.</p>
<p>In words, the slope compares two amounts: how much <span class="math inline">\(Y\)</span> moves together with <span class="math inline">\(X\)</span>, and how much <span class="math inline">\(X\)</span> moves at all. Two quantities from QM Basic measure them.</p>
<ul>
<li>The <strong>sample variance</strong> of <span class="math inline">\(X\)</span>, written <span class="math inline">\(s_X^2\)</span>, measures how far the values of <span class="math inline">\(X\)</span> spread around their mean <span class="math inline">\(\bar x\)</span>. Its square root <span class="math inline">\(s_X\)</span> is the standard deviation. <a href="../basic/b03-discrete-distributions.html">Basic Lecture 3</a> explains the variance and the standard deviation.</li>
<li>The <strong>sample covariance</strong> of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, written <span class="math inline">\(s_{XY}\)</span>, measures whether <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> move together. It is positive when high values of <span class="math inline">\(X\)</span> go with high values of <span class="math inline">\(Y\)</span>, and negative when high values of <span class="math inline">\(X\)</span> go with low values of <span class="math inline">\(Y\)</span>. <a href="../basic/b05-joint-covariance-correlation.html">Basic Lecture 5</a> explains the covariance and the correlation.</li>
</ul>
<p>The variance is an average of squared deviations from the mean. The covariance is an average of products of deviations. Both divide by <span class="math inline">\(n-1\)</span> in place of <span class="math inline">\(n\)</span>:</p>
<p><span class="math display">\[
s_X^2=\frac{1}{n-1}\sum_{i=1}^{n}(x_i-\bar x)^2,
\qquad
s_{XY}=\frac{1}{n-1}\sum_{i=1}^{n}(x_i-\bar x)(y_i-\bar y).
\]</span></p>
<p>The slope is the covariance of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> divided by the variance of <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[
\hat\beta_1=\frac{s_{XY}}{s_X^2}.
\]</span></p>
<p>The covariance has the units of <span class="math inline">\(X\)</span> times the units of <span class="math inline">\(Y\)</span>, and the variance has the squared units of <span class="math inline">\(X\)</span>. So their ratio has the units of a slope: units of <span class="math inline">\(Y\)</span> per unit of <span class="math inline">\(X\)</span>.</p>
<p>The same slope can be written with the correlation <span class="math inline">\(r_{XY}=s_{XY}/(s_X s_Y)\)</span>. The correlation is the covariance rescaled so that it has no units and lies between <span class="math inline">\(-1\)</span> and <span class="math inline">\(1\)</span>. Then</p>
<p><span class="math display">\[
\hat\beta_1=r_{XY}\,\frac{s_Y}{s_X}.
\]</span></p>
<p>In words: the slope is the correlation, rescaled into units of <span class="math inline">\(Y\)</span> per unit of <span class="math inline">\(X\)</span>. Two facts follow from this. The slope always has the sign of the correlation, because standard deviations are positive. And if <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are both standardised, so that each has standard deviation 1, the slope is equal to the correlation.</p>
<p>The intercept is chosen so that the line passes through the point of means <span class="math inline">\((\bar x,\bar y)\)</span>:</p>
<p><span class="math display">\[
\hat\beta_0=\bar y-\hat\beta_1\bar x.
\]</span></p>
<p>You can check this by putting <span class="math inline">\(x=\bar x\)</span> into the fitted line: <span class="math inline">\(\hat\beta_0+\hat\beta_1\bar x=\bar y\)</span>. At the average value of <span class="math inline">\(X\)</span>, the line gives the average value of <span class="math inline">\(Y\)</span>.</p>
<div id="exm-i01-toy" class="theorem example">
<p><span class="theorem-title"><strong>Example 1.1 (Worked example: least squares by hand on three points)</strong></span> Three observations: <span class="math inline">\((1,2)\)</span>, <span class="math inline">\((2,5)\)</span>, <span class="math inline">\((3,5)\)</span>. We write out every sum.</p>
<p><strong>Means.</strong> <span class="math inline">\(\bar x = (1+2+3)/3 = 2\)</span> and <span class="math inline">\(\bar y = (2+5+5)/3 = 4\)</span>.</p>
<p><strong>Deviations and their products.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(i\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x_i-\bar x\)</span></th>
<th style="text-align: right;"><span class="math inline">\(y_i-\bar y\)</span></th>
<th style="text-align: right;"><span class="math inline">\((x_i-\bar x)(y_i-\bar y)\)</span></th>
<th style="text-align: right;"><span class="math inline">\((x_i-\bar x)^2\)</span></th>
<th style="text-align: right;"><span class="math inline">\((y_i-\bar y)^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: right;"><span class="math inline">\(-1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-2\)</span></td>
<td style="text-align: right;"><span class="math inline">\(2\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(4\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
</tr>
<tr class="even">
<td><strong>Sum</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><span class="math inline">\(3\)</span></td>
<td style="text-align: right;"><span class="math inline">\(2\)</span></td>
<td style="text-align: right;"><span class="math inline">\(6\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Covariance and variance.</strong> Divide the sums by <span class="math inline">\(n-1=2\)</span>. The covariance is <span class="math inline">\(s_{XY} = 3/2 = 1.5\)</span> and the variance of <span class="math inline">\(X\)</span> is <span class="math inline">\(s_X^2 = 2/2 = 1\)</span>.</p>
<p><strong>Slope: the covariance divided by the variance of <span class="math inline">\(X\)</span>.</strong></p>
<p><span class="math display">\[
\hat\beta_1 = \frac{s_{XY}}{s_X^2} = \frac{1.5}{1} = 1.5.
\]</span></p>
<p><strong>The same slope from the correlation.</strong> The standard deviations are <span class="math inline">\(s_X=\sqrt{1}=1\)</span> and <span class="math inline">\(s_Y=\sqrt{6/2}\approx 1.732\)</span>, so the correlation is <span class="math inline">\(r_{XY}=1.5/(1\times 1.732)\approx 0.866\)</span>. Then</p>
<p><span class="math display">\[
\hat\beta_1 = r_{XY}\,\frac{s_Y}{s_X} = 0.866\times\frac{1.732}{1} = 1.5.
\]</span></p>
<p><strong>Intercept: the line passes through the point of means.</strong></p>
<p><span class="math display">\[
\hat\beta_0 = \bar y - \hat\beta_1\bar x = 4 - 1.5\times 2 = 1.
\]</span></p>
<p>The fitted line is <span class="math inline">\(\widehat y = 1 + 1.5x\)</span>. <a href="#fig-i01-toy" class="quarto-xref">Figure&nbsp;<span>11.3</span></a> shows that the line passes exactly through the point of means <span class="math inline">\((\bar x,\bar y)=(2,4)\)</span>. The residuals are <span class="math inline">\(-0.5\)</span>, <span class="math inline">\(+1\)</span>, and <span class="math inline">\(-0.5\)</span>. They sum to zero, as least-squares residuals always do when the model has an intercept.</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>x_toy <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>); y_toy <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">5</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>toy_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(y_toy <span class="sc">~</span> x_toy)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>toy_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> x_toy, <span class="at">y =</span> y_toy, <span class="at">fitted =</span> <span class="fu">fitted</span>(toy_fit))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(toy_df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">coef</span>(toy_fit)[<span class="dv">1</span>], <span class="at">slope =</span> <span class="fu">coef</span>(toy_fit)[<span class="dv">2</span>],</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> x, <span class="at">yend =</span> fitted),</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">colour =</span> <span class="st">"#0072B2"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">colour =</span> <span class="st">"#009E73"</span>) <span class="sc">+</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"point"</span>, <span class="at">x =</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="dv">4</span>, <span class="at">shape =</span> <span class="dv">5</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">stroke =</span> <span class="fl">1.1</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>) <span class="sc">+</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">2.34</span>, <span class="at">y =</span> <span class="fl">3.72</span>,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"'('*bar(x)*', '*bar(y)*')'"</span>, <span class="at">parse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#17324D"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">3.5</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">6</span>)) <span class="sc">+</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"x"</span>, <span class="at">y =</span> <span class="st">"y"</span>) <span class="sc">+</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-i01-toy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-i01-toy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="i01-simple-linear-regression_files/figure-html/fig-i01-toy-1.png" class="img-fluid figure-img" width="518">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-i01-toy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.3: The three-point toy dataset with its least-squares line. The open diamond marks the point of means (2, 4), which the fitted line passes through exactly.
</figcaption>
</figure>
</div>
</div>
</div>
<p>You can verify the hand calculation in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>x_toy <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>); y_toy <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">5</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">covariance =</span> <span class="fu">cov</span>(x_toy, y_toy), <span class="at">variance_x =</span> <span class="fu">var</span>(x_toy),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_y =</span> <span class="fu">sd</span>(y_toy), <span class="at">correlation =</span> <span class="fu">cor</span>(x_toy, y_toy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> covariance  variance_x        sd_y correlation 
  1.5000000   1.0000000   1.7320508   0.8660254 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(y_toy <span class="sc">~</span> x_toy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)       x_toy 
        1.0         1.5 </code></pre>
</div>
</div>
</section>
</section>
<section id="fit-and-read-the-shark-tank-model-in-r" class="level3">
<h3 class="anchored" data-anchor-id="fit-and-read-the-shark-tank-model-in-r">Fit and read the Shark Tank model in R</h3>
<p><span class="shark-tag">Shark Tank data</span> Now the Shark Tank data. The function <code>lm()</code> (for “linear model”) fits the least-squares line. Its first argument is a formula of the form <code>outcome ~ predictor</code>. The block below loads the data again, so you can run it on its own:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">subset</span>(sharks, deal_on_show <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> deal_equity_pct <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>claimed_m <span class="ot">&lt;-</span> vals<span class="sc">$</span>requested_valuation_usd <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>agreed_m <span class="ot">&lt;-</span> vals<span class="sc">$</span>deal_valuation_usd <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>val_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(agreed_m <span class="sc">~</span> claimed_m, <span class="at">data =</span> vals)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(val_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   claimed_m 
-0.06798986  0.64874084 </code></pre>
</div>
</div>
<p>The fitted equation is approximately</p>
<p><span class="math display">\[
\widehat{\text{agreed valuation}}
=-0.068+0.649\times\text{claimed valuation},
\]</span></p>
<p>with both valuations measured in $ millions.</p>
<p>R calculated these two numbers with the formulas of the previous section. You can check this with the covariance, the variance, the correlation, and the standard deviations of the two columns:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> vals<span class="sc">$</span>claimed_m</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> vals<span class="sc">$</span>agreed_m</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">correlation =</span> <span class="fu">cor</span>(x, y), <span class="at">sd_x =</span> <span class="fu">sd</span>(x), <span class="at">sd_y =</span> <span class="fu">sd</span>(y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>correlation        sd_x        sd_y 
  0.8930528   5.0880676   3.6961276 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">cov_over_var =</span> <span class="fu">cov</span>(x, y) <span class="sc">/</span> <span class="fu">var</span>(x),</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">cor_times_sd_ratio =</span> <span class="fu">cor</span>(x, y) <span class="sc">*</span> <span class="fu">sd</span>(y) <span class="sc">/</span> <span class="fu">sd</span>(x),</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">slope_from_lm =</span> <span class="fu">unname</span>(<span class="fu">coef</span>(val_model)[<span class="st">"claimed_m"</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      cov_over_var cor_times_sd_ratio      slope_from_lm 
         0.6487408          0.6487408          0.6487408 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean_y_minus_slope_times_mean_x =</span> <span class="fu">mean</span>(y) <span class="sc">-</span> <span class="fu">cov</span>(x, y) <span class="sc">/</span> <span class="fu">var</span>(x) <span class="sc">*</span> <span class="fu">mean</span>(x),</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">intercept_from_lm =</span> <span class="fu">unname</span>(<span class="fu">coef</span>(val_model)[<span class="st">"(Intercept)"</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mean_y_minus_slope_times_mean_x               intercept_from_lm 
                    -0.06798986                     -0.06798986 </code></pre>
</div>
</div>
<p>Both formulas give the slope 0.649 that <code>lm()</code> reports, and the intercept formula gives <span class="math inline">\(-0.068\)</span>. The second form of the slope also shows why it is below 1. The correlation of the two valuations is 0.893, and the agreed valuations spread less than the claimed ones: their standard deviation is $3.70 million against $5.09 million. So <span class="math inline">\(\hat\beta_1 = 0.893 \times 3.70/5.09 \approx 0.649\)</span>.</p>
<p>The table below shows the observed value, the fitted value, and the residual for the first six rows of the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">observed =</span> vals<span class="sc">$</span>agreed_m,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">fitted =</span> <span class="fu">fitted</span>(val_model),</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="fu">residuals</span>(val_model)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   observed       fitted    residual
1  0.090909  0.148256872 -0.05734787
2  0.920000  2.916218011 -1.99621801
6  1.000000  2.094479396 -1.09447940
7  0.250000  1.553862244 -1.30386224
11 0.035000 -0.003115774  0.03811577
12 0.500000  0.742936193 -0.24293619</code></pre>
</div>
</div>
<p>For every row, <code>observed = fitted + residual</code>. Check it on the first row. The founders asked $50,000 for 15%, a claimed valuation of $0.333 million. They agreed to $50,000 for 55%, an agreed valuation of $0.091 million. The fitted value is <span class="math inline">\(-0.068 + 0.649 \times 0.333 = 0.148\)</span>, and indeed <span class="math inline">\(0.091 = 0.148 + (-0.057)\)</span>.</p>
</section>
<section id="i01-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="i01-interpretation">Reading a slope and an intercept</h3>
<p>A coefficient is a number with units. The slope is in units of <span class="math inline">\(Y\)</span> per unit of <span class="math inline">\(X\)</span>, and the intercept is in units of <span class="math inline">\(Y\)</span>. So the same model can give different numbers in different units, and a number without its units says little. The box below gives a fixed way to read both coefficients.</p>
<div class="exam-procedure">
<p><span class="label">Method: interpreting a slope and an intercept</span></p>
<ol type="1">
<li>Units. Write down the unit of the outcome <span class="math inline">\(Y\)</span>, the unit of the predictor <span class="math inline">\(X\)</span>, and which data the model uses.</li>
<li>Slope. “Among [the data], a [predictor] that is one [unit of <span class="math inline">\(X\)</span>] higher is associated with a [outcome] that is on average [<span class="math inline">\(\hat\beta_1\)</span>] [units of <span class="math inline">\(Y\)</span>] higher.” For a negative slope, write “lower” and drop the minus sign.</li>
<li>Intercept. “At [predictor] equal to zero, the fitted [outcome] is [<span class="math inline">\(\hat\beta_0\)</span>] [units of <span class="math inline">\(Y\)</span>].” Use this sentence only if <span class="math inline">\(X=0\)</span> lies inside the range of the data. Otherwise say that the intercept has no useful meaning of its own.</li>
<li>Words. Say “is associated with” and “on average”. Do not use causal words such as “increases”, “leads to”, “the effect of”, or “if you raise”.</li>
</ol>
</div>
<p><strong>The slope, with units.</strong> In the Shark Tank model both valuations are in $ millions. Among the 874 deals for a share of the company, a claimed valuation that is $1 million higher is associated with an agreed valuation that is on average about $0.65 million higher. Both valuations have the same unit, so the slope also reads per dollar: each extra dollar of claimed valuation goes with about 65 cents more agreed valuation, on average. This answers the prediction question from before class. The sign is positive, the unit is millions of dollars agreed per million claimed, and the slope is clearly below 1. The slope does not mean that claiming more causes the sharks to pay more.</p>
<p><strong>The intercept, with units.</strong> At a claimed valuation of zero, the fitted agreed valuation is about <span class="math inline">\(-\$68{,}000\)</span>. A company claimed to be worth nothing is not in the data (the smallest claimed valuation is $40,000), and a negative valuation has no meaning. The line needs an intercept so that it is at the right height. But this intercept has no useful meaning of its own.</p>
<section id="thousands-and-millions-rescaling-a-variable" class="level4">
<h4 class="anchored" data-anchor-id="thousands-and-millions-rescaling-a-variable">Thousands and millions: rescaling a variable</h4>
<p>Money is often reported in thousands or millions. A change of unit multiplies every value of a variable by the same number <span class="math inline">\(c\)</span>. For example, going from dollars to $1,000s divides every value by 1,000, so <span class="math inline">\(c=1/1{,}000\)</span>. The fitted line itself does not change. Only the numbers that describe it change, by a simple rule:</p>
<ul>
<li>multiply only the outcome by <span class="math inline">\(c\)</span>: the intercept and the slope are both multiplied by <span class="math inline">\(c\)</span></li>
<li>multiply only the predictor by <span class="math inline">\(c\)</span>: the slope is divided by <span class="math inline">\(c\)</span>, and the intercept stays the same</li>
<li>multiply both by <span class="math inline">\(c\)</span>: the intercept is multiplied by <span class="math inline">\(c\)</span>, and the slope stays the same.</li>
</ul>
<p>An invented example shows the second case. A web shop regresses its weekly orders on its weekly advertising spending in euros and finds a slope of 0.15 orders per euro. With spending measured in 1,000s of euros, every value of the predictor is divided by 1,000, so the slope is multiplied by 1,000: 150 orders per 1,000 euros. Both numbers say the same thing. The <a href="../intermediate/code-sheet.html#lecture-1-simple-linear-regression">code sheet</a> lists the rule as a table.</p>
<div id="exm-i01-units" class="theorem example">
<p><span class="theorem-title"><strong>Example 1.2 (Worked example: the same coefficients in three unit systems)</strong></span> <span class="shark-tag">Shark Tank data</span> The fitted intercept is about <span class="math inline">\(-0.068\)</span> and the fitted slope is about <span class="math inline">\(0.649\)</span>, with both valuations in $ millions. Read the intercept in dollars first:</p>
<p><span class="math display">\[
-0.068 \text{ (in \$ millions)} = -0.068 \times \$1{,}000{,}000 = -\$68{,}000.
\]</span></p>
<p>Suppose a report measures both valuations in $1,000s. Every value of <span class="math inline">\(Y\)</span> and of <span class="math inline">\(X\)</span> is then 1,000 times as large. This is the third case of the rule. The intercept has the units of <span class="math inline">\(Y\)</span>, so it is multiplied by 1,000. The slope is a ratio, units of <span class="math inline">\(Y\)</span> per unit of <span class="math inline">\(X\)</span>. Both parts of the ratio change by the same factor, so the slope stays the same:</p>
<p><span class="math display">\[
\text{intercept: } -0.068 \times 1000 = -68 \text{ (in \$1,000s)},
\qquad
\text{slope: } 0.649 \text{ (unchanged)}.
\]</span></p>
<p>R confirms this result:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>claimed_k <span class="ot">&lt;-</span> vals<span class="sc">$</span>claimed_m <span class="sc">*</span> <span class="dv">1000</span>   <span class="co"># claimed valuation in $1,000s</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>agreed_k <span class="ot">&lt;-</span> vals<span class="sc">$</span>agreed_m <span class="sc">*</span> <span class="dv">1000</span>     <span class="co"># agreed valuation in $1,000s</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(agreed_k <span class="sc">~</span> claimed_k, <span class="at">data =</span> vals))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   claimed_k 
-67.9898584   0.6487408 </code></pre>
</div>
</div>
<p>The sentence for the slope now uses the new unit. Among the 874 deals, a claimed valuation that is $1,000 higher is associated with an agreed valuation that is on average about $649 higher. In raw dollars, the intercept is <span class="math inline">\(-68{,}000\)</span> dollars and the slope is again 0.649: dollars of agreed valuation per dollar of claimed valuation. When two sources disagree about a coefficient, check the units first.</p>
</div>
</section>
<section id="percent-and-percentage-points" class="level4">
<h4 class="anchored" data-anchor-id="percent-and-percentage-points">Percent and percentage points</h4>
<p>Some outcomes are percentages, such as the equity offered or a conversion rate (the percentage of visitors who buy). The slope is then in percentage points per unit of <span class="math inline">\(X\)</span>. A percentage point is the difference between two percentages. A conversion rate that falls from 3.0% to 2.6% falls by 0.4 percentage points. In percent of its old value, the same fall is about 13%. The two statements are different, so always say which one you mean.</p>
<p>An invented example. A web shop regresses its daily conversion rate (in %) on the loading time of its website (in seconds) and finds a slope of <span class="math inline">\(-0.4\)</span>. The sentence is: days with a loading time that is one second longer are associated with a conversion rate that is on average 0.4 percentage points lower. “0.4 percent lower” would be wrong. At a conversion rate of 3.0%, the difference of 0.4 percentage points is about 13% of the rate.</p>
</section>
<section id="a-predictor-that-is-0-or-1" class="level4">
<h4 class="anchored" data-anchor-id="a-predictor-that-is-0-or-1">A predictor that is 0 or 1</h4>
<p>A predictor can also record yes or no, coded 1 for yes and 0 for no. Such a predictor is called a dummy variable. Other names are indicator variable and binary variable. You know the idea from QM Basic: the deal indicator was 1 for a pitch with a deal and 0 for a pitch without one. The word “dummy” means that the variable stands in for a category, such as “deal” or “campaign week”, so that a category can enter a regression as a number. For a dummy, “one unit higher” means the step from 0 to 1. The intercept is then the average outcome in the group with <span class="math inline">\(X=0\)</span>. The slope is the difference in the average outcome between the group with <span class="math inline">\(X=1\)</span> and the group with <span class="math inline">\(X=0\)</span>: a difference in means.</p>
<p>An invented example. A web shop regresses its weekly orders on a dummy that is 1 in weeks with a discount campaign. The intercept is 200 and the slope is 35. Weeks without a campaign have on average 200 orders. Weeks with a campaign have on average 35 orders more, that is 235, or about 18% more. <a href="../intermediate/i05-categories-joint-tests.html">Lecture 5</a> treats such predictors in detail.</p>
</section>
</section>
<section id="prediction-inside-the-range-of-the-data" class="level3">
<h3 class="anchored" data-anchor-id="prediction-inside-the-range-of-the-data">Prediction inside the range of the data</h3>
<p><span class="shark-tag">Shark Tank data</span> The function <code>predict()</code> calculates the fitted value for a new value of the predictor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(val_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">claimed_m =</span> <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
1.229492 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(vals<span class="sc">$</span>claimed_m)   <span class="co"># smallest and largest claimed valuation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.04 50.00</code></pre>
</div>
</div>
<p>For a claimed valuation of $2 million (<code>claimed_m = 2</code>), the fitted agreed valuation is about 1.23, that is, $1.23 million. This value is the average that the model gives for such deals. It is not a guarantee for a new pitch. If such a deal was agreed on air at a valuation of $1 million, its residual would be</p>
<p><span class="math display">\[
e = 1.00 - 1.23 = -0.23,
\]</span></p>
<p>about $230,000 below the fitted value. Use predictions only inside the range of the data. The claimed valuations run from $40,000 to $50 million. Outside this range there are no deals to support the line. A prediction there depends only on the assumption that the line continues.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try it: a fitted value and a residual
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="shark-tag">Shark Tank data</span> Try this with your neighbour first. A founder claims a valuation of $8 million, and the deal closes at a valuation of $6 million.</p>
<p><em>Step 1 (given).</em> The fitted equation is <span class="math inline">\(\widehat{\text{agreed}}=-0.068+0.649\times\text{claimed}\)</span>, in $ millions.</p>
<p><em>Step 2 (you).</em> Calculate the fitted agreed valuation.</p>
<p><em>Step 3 (you).</em> Calculate the residual and say what its sign means.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Fitted: <span class="math inline">\(-0.068+0.649\times8=5.12\)</span>, about $5.12 million. Residual: <span class="math inline">\(6-5.12=0.88\)</span>, about $880,000. The sign is positive: this deal was agreed above the fitted value. R confirms the residual:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unname</span>(<span class="dv">6</span> <span class="sc">-</span> <span class="fu">predict</span>(val_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">claimed_m =</span> <span class="dv">8</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8780631</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="caveat-box">
<p><span class="label">What this fitted line can and cannot say</span></p>
<ul>
<li>The slope 0.649 describes how deals differed. Founders who claim more also differ in sales, stage, and industry.</li>
<li>Only pitches that reached a deal are in the data.</li>
<li>The model does not say what happens if you raise your own claim.</li>
</ul>
<p><strong>What you can do with it:</strong> expect each extra dollar you claim to go with only about two thirds of a dollar more in the agreed valuation, and prepare your negotiation for that.</p>
</div>
</section>
<section id="from-an-association-to-a-decision" class="level3">
<h3 class="anchored" data-anchor-id="from-an-association-to-a-decision">From an association to a decision</h3>
<p>The box above protects you from one mistake: reading a description as a promise. It does not make the slope useless. Founders and managers decide with imperfect evidence every day. Three questions help.</p>
<ol type="1">
<li><strong>How expensive is a wrong decision, and can I undo it?</strong> If the action is cheap and easy to undo, act on the association and watch what happens. If the action is expensive or hard to undo, ask for more evidence first.</li>
<li><strong>What else differs between the cases I compare?</strong> Founders who claim more also differ in sales, stage, and industry. Lecture 4 shows how to hold measured differences fixed.</li>
<li><strong>Can I test it myself?</strong> A founder can often change one feature on purpose for some customers and not for others. Chance decides which customers get the change. Lecture 5 shows how to read such a test.</li>
</ol>
</section>
<section id="answering-the-driving-question" class="level3">
<h3 class="anchored" data-anchor-id="answering-the-driving-question">Answering the driving question</h3>
<p>Among the 874 Shark Tank deals for a share of the company, the agreed valuation rises with the claimed valuation, but less than one for one. The slope of the regression line is 0.649. So one more dollar of claimed valuation goes with about 65 cents more agreed valuation, on average. In the units of the model: each extra $1 million of claimed valuation is associated with about $0.65 million more agreed valuation. For a founder, about two thirds of each extra claimed dollar shows up in the agreed valuation. The limits in the box “What this fitted line can and cannot say” still apply.</p>
<div class="founder-box">
<p><span class="label">A founder’s decision (invented example)</span></p>
<p>You regress weekly orders on weekly advertising spending in euros and get: fitted orders = 120 + 0.15 × spending. Each extra 100 euros of advertising goes with 15 more orders. You earn 4 euros per order, so 100 euros of advertising goes with 60 euros of extra margin. The decision: at this slope, advertising does not pay for itself, unless new customers come back and order again. The slope turned a feeling that ads help into a number that you can compare with the cost. But the slope only describes your past weeks. Before a large budget change, vary the spending on purpose for a few weeks and see whether the orders follow. Such small planned changes also help to separate the effect of the spending from timing effects, such as the season or the day of the week.</p>
</div>
<p><strong>Next:</strong> R fits a least-squares line to any data, even to data that a straight line describes badly. R gives no warning. Lecture 2 states the assumptions behind the fitted line and shows how to check them with residual plots.</p>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p>After the lecture, work through all the practice below.</p>
<section id="read-the-lecture-material" class="level3">
<h3 class="anchored" data-anchor-id="read-the-lecture-material">Read the lecture material</h3>
<p>Read the Lecture material section above from start to end. The lecture covered the main points. The text has every step, every example, and all the code, including parts that were not shown in class. Note what is still unclear and bring it to the next tutorial, or ask Tilly.</p>
</section>
<section id="recall-questions" class="level3">
<h3 class="anchored" data-anchor-id="recall-questions">Recall questions</h3>
<ol type="1">
<li>What is the difference between <span class="math inline">\(\varepsilon_i\)</span> and <span class="math inline">\(e_i\)</span>?</li>
<li>What does least squares minimise, and why are the residuals squared before they are added up?</li>
<li>Why must a slope interpretation include units?</li>
<li>Why can an intercept be calculated correctly and still have no useful meaning?</li>
<li>Why is the slope not automatically causal?</li>
<li>The outcome is a conversion rate in percent, and the slope is <span class="math inline">\(-0.4\)</span>. Is the outcome 0.4 percent or 0.4 percentage points lower per unit of the predictor?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(\varepsilon_i\)</span> is the error term of the population model: the distance to the unknown population line. It is never observed. <span class="math inline">\(e_i\)</span> is the residual: the distance to the fitted line, calculated from the data.</li>
<li>The sum of squared residuals, <span class="math inline">\(\operatorname{SSE}=\sum_i e_i^2\)</span>. In a plain sum the positive and the negative residuals would cancel. Squares are never negative, and they count a large residual more heavily than a small one.</li>
<li>The slope is a difference in outcome units per one unit of the predictor. Without units the number 0.649 could mean anything.</li>
<li>The value <span class="math inline">\(X=0\)</span> may lie outside the observed range, or it may make no sense for the variable.</li>
<li>The predictor was not randomly assigned, and other factors may affect both variables.</li>
<li>0.4 percentage points. The slope of a percentage outcome is a difference between two percentages. A fall of 0.4 percentage points from 3.0% is a fall of about 13% of the rate.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="finish-a-half-worked-example" class="level3">
<h3 class="anchored" data-anchor-id="finish-a-half-worked-example">Finish a half-worked example</h3>
<p><span class="shark-tag">Shark Tank data</span> Re-read the prediction calculation in the chapter (fitted value at <code>claimed_m = 2</code>). Then complete the same calculation for a new claim.</p>
<p><em>Step 1 (given).</em> A founder claims a valuation of $4 million, so <code>claimed_m = 4</code>. The fitted equation is <span class="math inline">\(\widehat{\text{agreed}} = -0.068 + 0.649 \times \text{claimed}\)</span>.</p>
<p><em>Step 2 (you).</em> Compute the fitted agreed valuation, in $ millions and in dollars.</p>
<p><em>Step 3 (you).</em> The deal was actually agreed on air at a valuation of $2 million. Compute the residual and interpret its sign in one sentence.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Fitted: <span class="math inline">\(-0.068 + 0.649 \times 4 = 2.53\)</span>, about $2.53 million. Residual: <span class="math inline">\(2 - 2.53 = -0.53\)</span>, about <span class="math inline">\(-\$530{,}000\)</span>. The negative sign means this deal was agreed below the model’s fitted conditional mean for a claimed valuation of $4 million.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">subset</span>(sharks, deal_on_show <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> deal_equity_pct <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>claimed_m <span class="ot">&lt;-</span> vals<span class="sc">$</span>requested_valuation_usd <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>agreed_m <span class="ot">&lt;-</span> vals<span class="sc">$</span>deal_valuation_usd <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>val_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(agreed_m <span class="sc">~</span> claimed_m, <span class="at">data =</span> vals)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">unname</span>(<span class="dv">2</span> <span class="sc">-</span> <span class="fu">predict</span>(val_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">claimed_m =</span> <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.5269735</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Then do five more tasks. These tasks have no given steps:</p>
<ol type="1">
<li>Use the fitted equation to predict the agreed valuation for claimed valuations of $1 million and $10 million.</li>
<li>Calculate the residual for a deal with a claimed valuation of $2 million and an agreed valuation of $1 million.</li>
<li>Explain why <code>lm(y ~ x, data = dat)</code> treats the variable left of <code>~</code> as the outcome.</li>
<li>A report keeps the agreed valuation in $ millions but measures the claimed valuation in $1,000s. Which intercept and which slope does it report? Use the rule of <a href="#exm-i01-units" class="quarto-xref">Example&nbsp;<span>11.2</span></a>.</li>
<li>Under which condition could the slope 0.649 be read as the effect of a higher claim? Name one factor outside the model that breaks this condition for the Shark Tank deals.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Substitute <code>claimed_m = 1</code> and <code>claimed_m = 10</code>. The fitted values are about 0.58 and 6.42 in $ millions.</li>
<li>The fitted valuation is about 1.23 in $ millions, so the residual is <span class="math inline">\(1-1.23\approx-0.23\)</span>, or about <span class="math inline">\(-\$230{,}000\)</span>.</li>
<li>R formulas use <code>outcome ~ predictors</code>: the left-hand side is what the model predicts. The right-hand side is what the model uses to predict it.</li>
<li>Only the predictor is rescaled, by the factor 1,000. The slope is divided by 1,000: <span class="math inline">\(0.649/1000 = 0.000649\)</span> million dollars of agreed valuation per $1,000 claimed, which is $649 per $1,000. The intercept stays at <span class="math inline">\(-0.068\)</span>, because the outcome keeps its units.</li>
<li>The condition: nothing outside the model affects both the claimed and the agreed valuation. Here it fails. A company with high sales can claim a higher valuation, and the sharks also agree to a higher valuation for it. The slope then mixes the effect of the claim with the effect of the sales.</li>
</ol>
<p>The R check for task 4:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">subset</span>(sharks, deal_on_show <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> deal_equity_pct <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>claimed_k <span class="ot">&lt;-</span> vals<span class="sc">$</span>requested_valuation_usd <span class="sc">/</span> <span class="fl">1e3</span>   <span class="co"># in $1,000s</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>vals<span class="sc">$</span>agreed_m <span class="ot">&lt;-</span> vals<span class="sc">$</span>deal_valuation_usd <span class="sc">/</span> <span class="fl">1e6</span>         <span class="co"># in $ millions</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(agreed_m <span class="sc">~</span> claimed_k, <span class="at">data =</span> vals))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)     claimed_k 
-0.0679898584  0.0006487408 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="practice-a-regression-of-your-own" class="level3">
<h3 class="anchored" data-anchor-id="practice-a-regression-of-your-own">Practice: a regression of your own</h3>
<p><span class="shark-tag">Shark Tank data</span> Fit <code>equity_offered_pct ~ season</code> on the full dataset (all 1,441 pitches) and interpret both coefficients with units. State the unit of every quantity you report.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season, <span class="at">data =</span> sharks))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      season 
 20.4565874  -0.8241241 </code></pre>
</div>
</div>
<p>The fitted intercept is about 20.46% and the slope about <span class="math inline">\(-0.824\)</span> percentage points per season. Among all 1,441 pitches, a season that is one later is associated with an initial equity offer that is on average 0.824 percentage points smaller. The outcome and the intercept are in percent. The predictor is in seasons. The slope is a difference between two percentages, so it is in percentage points per season. The intercept is the fitted value at Season 0, which is outside the data (Seasons 1 to 16), so it has no useful meaning of its own.</p>
</div>
</div>
</div>
</section>
<section id="review-one-question-from-qm-basic" class="level3">
<h3 class="anchored" data-anchor-id="review-one-question-from-qm-basic">Review: one question from QM Basic</h3>
<p>An invented example. A market survey of <span class="math inline">\(n = 400\)</span> customers gives an average willingness to pay of €24.60 with standard error €1.10. Write down the t statistic for testing a benchmark of €22 and the 95% confidence interval, and say in one sentence what the interval estimates.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(t_{obs}=(24.60-22)/1.10\approx2.36\)</span>. With <span class="math inline">\(df=399\)</span>, the closest listed value on the formula sheet is <span class="math inline">\(t_{0.975,\,120}=1.980\)</span>. The interval is <span class="math inline">\(24.60\pm1.980\times1.10=24.60\pm2.18=(22.42,\ 26.78)\)</span> euros. It is a range of plausible values for the population mean willingness to pay, if the 400 customers are a random sample.</p>
</div>
</div>
</div>
</section>
<section id="worked-exam-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="worked-exam-interpretation">Worked exam interpretation</h3>
<p><strong>Exam-style question.</strong> An invented example. A model of the monthly revenue of cafés (€1,000s) on their opening hours per week reports <span class="math inline">\(\widehat{\text{revenue}} = 4.20 + 0.85\,\text{hours}\)</span>. Interpret the slope with units, and calculate the fitted value and the residual for a café that is open 40 hours per week and has a monthly revenue of €35,000.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Among the sampled cafés, an opening time that is one hour per week longer is associated with a monthly revenue that is on average €850 higher. For 40 hours the fitted value is <span class="math inline">\(4.20+0.85\times40=38.2\)</span>, about €38,200. The residual is <span class="math inline">\(35-38.2=-3.2\)</span>, about <span class="math inline">\(-\)</span>€3,200: the observed revenue is below the fitted value.</p>
</div>
</div>
</div>
</section>
<section id="check-the-ai" class="level3">
<h3 class="anchored" data-anchor-id="check-the-ai">Check the AI</h3>
<p><span class="shark-tag">Shark Tank data</span> You asked an AI assistant: “The slope of my valuation regression is 0.649 and the intercept is -0.068. What do they mean for my pitch?” It answered:</p>
<blockquote class="blockquote">
<p>“If you raise your claimed valuation by 1 million dollars, the sharks will pay you 649,000 dollars more. And a company with a claimed valuation of zero gets -68,000 dollars.”</p>
</blockquote>
<p>Find what is wrong and write the corrected answer. This task is the <strong>Verify</strong> step of Attempt → Ask → Verify → Explain.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Three errors. The slope describes how deals differed. It does not say what happens if you change your own claim, because stronger companies both claim more and get more. The outcome is the agreed valuation of the company, not money paid to the founder. And a claimed valuation of zero is outside the data, so the intercept has no meaning of its own.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours">Make it yours</h3>
<div class="utility-prompt">
<p><span class="label">Two sentences about your own venture</span></p>
<p>Think of your EiA3 venture, or any business you know well. Name one numerical outcome and one numerical input that you think affects it. Then write two sentences. First, state the slope you would expect (sign and units). Second, say what decision would change if the fitted slope turned out to be near zero. There is no wrong answer.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student venture that sells boxes of prepared meals on campus. “Outcome: weekly orders. Input: euros spent on social-media advertising that week. I expect a positive slope of a few orders per extra €100. If the fitted slope came out near zero, I would move the whole budget to campus flyers.”</p>
</div>
</div>
</div>
<p>You can discuss this task, and any other task in this chapter, with Tilly for QM Intermediate, the course AI assistant: ask it what else, besides your input, could affect your outcome.</p>
</div>
</section>
<section id="more-practice" class="level3">
<h3 class="anchored" data-anchor-id="more-practice">More practice</h3>
<p>For extra exercises on this lecture, with worked solutions, ask Tilly for QM Intermediate, the course AI assistant. For example: “Give me an extra exercise for Intermediate Lecture 1. Show the solution only after I send my answer.”</p>
<p><a href="../intermediate/i02-assumptions-diagnostics.html">Continue to Lecture 2: What the model assumes and how residuals reveal it</a>.</p>
<p><a href="../intermediate/code-sheet.html#lecture-1-simple-linear-regression">Code sheet: Lecture 1 commands and formulas</a>.</p>
<p>For a more formal treatment, see James et al., <em>An Introduction to Statistical Learning</em>, 2nd ed., Sections 3.1 and 3.6.2, and <a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>, Chapter 19.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../intermediate/overview.html" class="pagination-link" aria-label="QM Intermediate: Course overview">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">QM Intermediate: Course overview</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../intermediate/i02-assumptions-diagnostics.html" class="pagination-link" aria-label="Lecture 2: What the model assumes and how residuals reveal it">
        <span class="nav-page-text"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>