<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lecture 6: Interactions and curvature – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../intermediate/t02-exam-prep.html" rel="next">
<link href="../intermediate/i05-categories-joint-tests.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ecf4e518a83458a2bb67b2a9bf74271b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../intermediate/overview.html">QM Intermediate: Course overview</a></li><li class="breadcrumb-item"><a href="../intermediate/i06-interactions-curvature.html"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution, confidence intervals, and the two-sided test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Inference and tests against zero</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals betray it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/reading-ladder.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reading research papers</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-class" id="toc-in-class" class="nav-link" data-scroll-target="#in-class">In class</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../intermediate/overview.html">QM Intermediate: Course overview</a></li><li class="breadcrumb-item"><a href="../intermediate/i06-interactions-curvature.html"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="i06" class="quarto-section-identifier"><span class="chapter-title">Lecture 6: Interactions and curvature</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Lecture 6, you can</span></p>
<ul>
<li>read a two-lines picture as four numbers: two intercepts and two slopes;</li>
<li>explain an interaction coefficient as a difference in slopes, with units;</li>
<li>interpret lower-order terms in a model containing an interaction, and use centering to make them meaningful;</li>
<li>report a non-significant interaction without overclaiming in either direction;</li>
<li>apply the hierarchy principle and the <code>x * z</code> formula shorthand;</li>
<li>fit a quadratic term, explain why it is still linear regression, and compute a fitted change without reading coefficients separately;</li>
<li>test added terms with a partial F-test and refuse to extrapolate a polynomial.</li>
</ul>
</div>
<div class="driving-question">
<p><span class="label">Driving question</span></p>
<p class="dq-context">
“On average” can hide the interesting part: an effect may differ across groups, or bend as scale grows. Interactions and curvature are how a model is allowed to say so.
</p>
<p>Is the downward season trend in equity offers the same for every team composition — and is the trend even a straight line?</p>
</div>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p><span class="time-budget">Total preparation time: about 30 minutes.</span></p>
<div class="video-prep">
<p><span class="label">Video preparation (15 minutes)</span><br> Watch Stanford Statistical Learning <a href="https://www.youtube.com/watch?v=dEBQmiXv9fk&amp;list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&amp;index=13">3.5 Extensions of the Linear Model</a> and <a href="https://www.youtube.com/watch?v=F-D3lZzYn50&amp;list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&amp;index=48">7.1 Polynomials and Step Functions</a>. Focus on why an interaction changes a slope and why a polynomial remains a linear regression model in its coefficients. All links are also listed in the <a href="../resources/video-guide.html">External Video Guide</a>.</p>
</div>
<p><strong>Derive the two lines (5 minutes).</strong> In the model <span class="math inline">\(Y=\beta_0+\beta_1X+\beta_2D+\beta_3XD+\varepsilon\)</span> with <span class="math inline">\(D\in\{0,1\}\)</span>, write the fitted line for <span class="math inline">\(D=0\)</span> and for <span class="math inline">\(D=1\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your preparation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For <span class="math inline">\(D=0\)</span>: <span class="math inline">\(E[Y\mid X,D=0]=\beta_0+\beta_1X\)</span>. For <span class="math inline">\(D=1\)</span>: <span class="math inline">\(E[Y\mid X,D=1]=(\beta_0+\beta_2)+(\beta_1+\beta_3)X\)</span>. Setting <span class="math inline">\(D=1\)</span> shifts the intercept by <span class="math inline">\(\beta_2\)</span> and the slope by <span class="math inline">\(\beta_3\)</span>.</p>
</div>
</div>
</div>
<p><strong>Predict (2 minutes).</strong> Answer the one-click Mentimeter question posted on Canvas before you come to class: how many separate numbers do you need to fully describe a picture of <strong>two straight lines with different slopes</strong>? Commit to an answer; the lecture resolves it.</p>
<p><strong>R warm-up (8 minutes).</strong> Build the analysis variables — the same <code>known_gender</code> subset as Lecture 5, plus a <code>women</code> indicator and a centred season — fit one equity-on-season line per group, and bring the plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sharks<span class="sc">$</span>ask_1k <span class="ot">&lt;-</span> sharks<span class="sc">$</span>ask_amount_usd <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>known_gender <span class="ot">&lt;-</span> <span class="fu">subset</span>(sharks, pitcher_gender_group <span class="sc">!=</span> <span class="st">"unknown"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>women <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  known_gender<span class="sc">$</span>pitcher_gender_group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"all_women"</span>, <span class="st">"mixed"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>season_c <span class="ot">&lt;-</span> known_gender<span class="sc">$</span>season <span class="sc">-</span> <span class="fu">mean</span>(known_gender<span class="sc">$</span>season)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(equity_offered_pct <span class="sc">~</span> season, <span class="at">data =</span> known_gender,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="st">"grey80"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> <span class="fu">subset</span>(known_gender, women <span class="sc">==</span> <span class="dv">0</span>)),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">"#0072B2"</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> <span class="fu">subset</span>(known_gender, women <span class="sc">==</span> <span class="dv">1</span>)),</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">"#D55E00"</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If products, powers, or centering are not secure, review <a href="../resources/math-refresher.html">Mathematics Refresher: products, powers, and centering</a>.</p>
</section>
<section id="in-class" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-class">In class</h2>
<p>The session opens with the usual four-minute entry quiz on the prep videos, then turns to the driving question — with the class’s own warm-up two-line plots on screen.</p>
<p class="concept-video">
<strong>Stanford explanations (review):</strong> <a href="https://www.youtube.com/watch?v=dEBQmiXv9fk">3.5 Extensions of the Linear Model</a> and <a href="https://www.youtube.com/watch?v=F-D3lZzYn50">7.1 Polynomials and Step Functions</a>.
</p>
<section id="the-picture-before-the-formula" class="level3">
<h3 class="anchored" data-anchor-id="the-picture-before-the-formula">The picture before the formula</h3>
<p>Every model so far forced all groups to share one slope. Lecture 5 let the <em>heights</em> differ by group; today the <strong>slopes</strong> get the same freedom. Start with the picture, not the algebra:</p>
<div class="cell">
<details class="code-fold">
<summary>See the drawing code (optional, not exam material)</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>old_par <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">no.readonly =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">4.2</span>, <span class="fl">4.2</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NA</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">bty =</span> <span class="st">"n"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Predictor X"</span>, <span class="at">ylab =</span> <span class="st">"Outcome Y"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> <span class="dv">2</span>, <span class="at">b =</span> <span class="fl">0.75</span>, <span class="at">col =</span> <span class="st">"#009E73"</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> <span class="fl">4.5</span>, <span class="at">b =</span> <span class="fl">0.25</span>, <span class="at">col =</span> <span class="st">"#D55E00"</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">8.4</span>, <span class="dv">2</span> <span class="sc">+</span> <span class="fl">0.75</span> <span class="sc">*</span> <span class="fl">8.4</span> <span class="sc">+</span> <span class="fl">0.9</span>, <span class="st">"Group D = 0"</span>, <span class="at">col =</span> <span class="st">"#009E73"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">8.4</span>, <span class="fl">4.5</span> <span class="sc">+</span> <span class="fl">0.25</span> <span class="sc">*</span> <span class="fl">8.4</span> <span class="sc">-</span> <span class="fl">0.8</span>, <span class="st">"Group D = 1"</span>, <span class="at">col =</span> <span class="st">"#D55E00"</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(old_par)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-i06-two-lines" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-i06-two-lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="i06-interactions-curvature_files/figure-html/fig-i06-two-lines-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-i06-two-lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;23.1: Two groups, two lines, different slopes. Before any formula: how many numbers does it take to describe this picture completely?
</figcaption>
</figure>
</div>
</div>
</div>
<p>This resolves the prediction from your prep: <strong>four numbers</strong> — an intercept and a slope for each line. The interaction model is nothing more than a reparameterisation of those four numbers:</p>
<p><span class="math display">\[
E[Y\mid X,D]
=\beta_0+\beta_1X+\beta_2D+\beta_3XD.
\]</span></p>
<p>Map each coefficient to a feature of the picture:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: where the <span class="math inline">\(D=0\)</span> line meets the vertical axis;</li>
<li><span class="math inline">\(\beta_1\)</span>: the slope of the <span class="math inline">\(D=0\)</span> line;</li>
<li><span class="math inline">\(\beta_2\)</span>: how much <em>higher</em> the <span class="math inline">\(D=1\)</span> line starts;</li>
<li><span class="math inline">\(\beta_3\)</span>: how much <em>steeper</em> the <span class="math inline">\(D=1\)</span> line runs.</li>
</ul>
<p>Or as the two-row table that your prep derivation produced:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th>Intercept</th>
<th>Slope</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(D=0\)</span></td>
<td><span class="math inline">\(\beta_0\)</span></td>
<td><span class="math inline">\(\beta_1\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(D=1\)</span></td>
<td><span class="math inline">\(\beta_0+\beta_2\)</span></td>
<td><span class="math inline">\(\beta_1+\beta_3\)</span></td>
</tr>
</tbody>
</table>
<p>Four coefficients, four picture features. When <span class="math inline">\(\beta_3=0\)</span> the lines are parallel and the model collapses to Lecture 5’s common-slope dummy model.</p>
</section>
<section id="the-interaction-coefficient-is-a-difference-in-slopes" class="level3">
<h3 class="anchored" data-anchor-id="the-interaction-coefficient-is-a-difference-in-slopes">The interaction coefficient is a difference in slopes</h3>
<p>In the additive model the slope of <span class="math inline">\(X\)</span> is the same at every value of the other predictor. Adding the product <span class="math inline">\(XD\)</span> lets it depend: the change in the conditional mean for a one-unit increase in <span class="math inline">\(X\)</span> is</p>
<p><span class="math display">\[
\beta_1+\beta_3D,
\]</span></p>
<p>so <span class="math inline">\(\beta_3\)</span> is a <strong>difference in slopes</strong>, not a standalone effect. Its units combine the variables. If <span class="math inline">\(X\)</span> is measured in seasons and <span class="math inline">\(D\)</span> is a group indicator, <span class="math inline">\(\beta_3\)</span> is measured in <em>outcome units per season, between the groups</em> — here, equity percentage points per season, group minus reference group. (The same algebra works when both variables are quantitative: the slope of <span class="math inline">\(X\)</span> becomes <span class="math inline">\(\beta_1+\beta_3Z\)</span>, a slope that slides with <span class="math inline">\(Z\)</span>.)</p>
<p><strong>Centering.</strong> Once <span class="math inline">\(XD\)</span> is in the model, <span class="math inline">\(\beta_2\)</span> compares the groups <em>at <span class="math inline">\(X=0\)</span></em> — for us, the unobserved Season 0. Replacing season with</p>
<p><span class="math display">\[
season\_c = season - \overline{season}
\]</span></p>
<p>moves that comparison to the average season (about 8.8). Centering changes exactly one kind of thing and cannot change another:</p>
<ul>
<li>it <strong>changes</strong> the meaning (and value) of lower-order terms — the intercept and the group coefficient now refer to the average season;</li>
<li>it <strong>cannot change</strong> the fitted values, the residuals, <span class="math inline">\(R^2\)</span>, or the interaction estimate itself. The lines are the same lines; only the place where we read off their vertical gap has moved.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check: which printed numbers change when season is centred?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The intercept and the <code>women</code> coefficient (lower-order terms) change; the interaction coefficient, the <code>ask_1k</code> coefficient, all fitted values, and <span class="math inline">\(R^2\)</span> do not. The after-class practice has you verify this in R.</p>
</div>
</div>
</div>
</section>
<section id="the-shark-tank-interaction-model" class="level3">
<h3 class="anchored" data-anchor-id="the-shark-tank-interaction-model">The Shark Tank interaction model</h3>
<p>Now the driving question’s first half. For this lecture, <code>women = 1</code> means the source classifies the presenting team as all-women or mixed; <code>women = 0</code> means all-men. It is a broader split than Lecture 5’s three-category factor, it does not measure a share of women or the full venture team, and the seven <code>unknown</code> records are excluded as before. The whole setup is visible — it is the warm-up code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>sharks<span class="sc">$</span>ask_1k <span class="ot">&lt;-</span> sharks<span class="sc">$</span>ask_amount_usd <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>known_gender <span class="ot">&lt;-</span> <span class="fu">subset</span>(sharks, pitcher_gender_group <span class="sc">!=</span> <span class="st">"unknown"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>women <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  known_gender<span class="sc">$</span>pitcher_gender_group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"all_women"</span>, <span class="st">"mixed"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>season_c <span class="ot">&lt;-</span> known_gender<span class="sc">$</span>season <span class="sc">-</span> <span class="fu">mean</span>(known_gender<span class="sc">$</span>season)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>interaction_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season_c <span class="sc">*</span> women <span class="sc">+</span> ask_1k,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> known_gender</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(interaction_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = equity_offered_pct ~ season_c * women + ask_1k, 
    data = known_gender)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.871  -4.742  -1.290   3.412  82.689 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    13.6247907  0.3354522  40.616  &lt; 2e-16 ***
season_c       -0.7993817  0.0663226 -12.053  &lt; 2e-16 ***
women           0.8069665  0.4117061   1.960   0.0502 .  
ask_1k         -0.0026776  0.0005834  -4.590 4.83e-06 ***
season_c:women -0.0614594  0.0955667  -0.643   0.5203    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.62 on 1429 degrees of freedom
Multiple R-squared:  0.1894,    Adjusted R-squared:  0.1871 
F-statistic: 83.47 on 4 and 1429 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Read the two group slopes off the two-row table, holding requested amount fixed. For all-men teams (<code>women = 0</code>), the fitted season slope is about <span class="math inline">\(-0.799\)</span> percentage points per season. For teams with women represented, it is</p>
<p><span class="math display">\[
-0.799+(-0.061)=-0.861
\text{ percentage points per season.}
\]</span></p>
<p>The interaction estimate is <span class="math inline">\(-0.061\)</span> equity percentage points per season (between groups), with p-value about 0.520. Read that carefully, in both directions: this model does <strong>not provide evidence that the season trend differs</strong> between these two broad source-defined groups. It also does <strong>not prove the slopes are identical</strong> — the estimate is imprecise (SE about 0.096), and the data are consistent with anything from a moderately steeper to a moderately flatter trend for teams with women represented. No evidence of different trends is not proof of equal trends.</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>sharks<span class="sc">$</span>ask_1k <span class="ot">&lt;-</span> sharks<span class="sc">$</span>ask_amount_usd <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>known_gender <span class="ot">&lt;-</span> <span class="fu">subset</span>(sharks, pitcher_gender_group <span class="sc">!=</span> <span class="st">"unknown"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>women <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  known_gender<span class="sc">$</span>pitcher_gender_group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"all_women"</span>, <span class="st">"mixed"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>season_c <span class="ot">&lt;-</span> known_gender<span class="sc">$</span>season <span class="sc">-</span> <span class="fu">mean</span>(known_gender<span class="sc">$</span>season)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>interaction_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season_c <span class="sc">*</span> women <span class="sc">+</span> ask_1k,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> known_gender</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>season_grid <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">16</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>ask_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(known_gender<span class="sc">$</span>ask_1k)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">season =</span> season_grid, <span class="at">women =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>newdat<span class="sc">$</span>season_c <span class="ot">&lt;-</span> newdat<span class="sc">$</span>season <span class="sc">-</span> <span class="fu">mean</span>(known_gender<span class="sc">$</span>season)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>newdat<span class="sc">$</span>ask_1k <span class="ot">&lt;-</span> ask_bar</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>newdat<span class="sc">$</span>fit <span class="ot">&lt;-</span> <span class="fu">predict</span>(interaction_model, <span class="at">newdata =</span> newdat)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>newdat<span class="sc">$</span>group <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(newdat<span class="sc">$</span>women <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Women represented"</span>, <span class="st">"All-men"</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>fit_men_13 <span class="ot">&lt;-</span> newdat<span class="sc">$</span>fit[newdat<span class="sc">$</span>women <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> newdat<span class="sc">$</span>season <span class="sc">==</span> <span class="dv">13</span>]</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>fit_women_13 <span class="ot">&lt;-</span> newdat<span class="sc">$</span>fit[newdat<span class="sc">$</span>women <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> newdat<span class="sc">$</span>season <span class="sc">==</span> <span class="dv">13</span>]</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(newdat, <span class="fu">aes</span>(<span class="at">x =</span> season, <span class="at">y =</span> fit,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>                   <span class="at">colour =</span> group, <span class="at">linetype =</span> group)) <span class="sc">+</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> <span class="fu">subset</span>(newdat, season <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">16</span>)), <span class="at">size =</span> <span class="fl">2.2</span>) <span class="sc">+</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">13</span>, <span class="at">y =</span> fit_women_13 <span class="sc">+</span> <span class="fl">1.1</span>,</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"Women represented"</span>,</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">13</span>, <span class="at">y =</span> fit_men_13 <span class="sc">-</span> <span class="fl">1.1</span>,</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"All-men"</span>,</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#009E73"</span>, <span class="at">size =</span> <span class="fl">3.4</span>) <span class="sc">+</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"All-men"</span> <span class="ot">=</span> <span class="st">"#009E73"</span>,</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"Women represented"</span> <span class="ot">=</span> <span class="st">"#D55E00"</span>),</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>                      <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"All-men"</span> <span class="ot">=</span> <span class="st">"solid"</span>,</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Women represented"</span> <span class="ot">=</span> <span class="st">"dashed"</span>),</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>                        <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">16</span>, <span class="at">by =</span> <span class="dv">3</span>)) <span class="sc">+</span></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Season"</span>, <span class="at">y =</span> <span class="st">"Fitted initial equity offered (%)"</span>) <span class="sc">+</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-i06-interaction" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-i06-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="i06-interactions-curvature_files/figure-html/fig-i06-interaction-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-i06-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;23.2: Fitted initial equity by season for the two source-defined groups, at the same average requested amount. Each line’s slope is that group’s fitted change per season; the vertical separation is the fitted group difference at a given season.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Graph the model whenever an interaction is present: in <a href="#fig-i06-interaction" class="quarto-xref">Figure&nbsp;<span>23.2</span></a> the two nearly-parallel lines <em>are</em> the finding, and neither <span class="math inline">\(\beta_1\)</span> nor <span class="math inline">\(\beta_2\)</span> alone is an overall effect once <span class="math inline">\(XD\)</span> is in the model.</p>
</section>
<section id="the-hierarchy-principle-and-the-shorthand" class="level3">
<h3 class="anchored" data-anchor-id="the-hierarchy-principle-and-the-shorthand">The hierarchy principle and the <code>*</code> shorthand</h3>
<p>If a model contains <span class="math inline">\(XD\)</span>, ordinarily retain both <span class="math inline">\(X\)</span> and <span class="math inline">\(D\)</span>, even when a lower-order term is not individually significant. The lower-order terms define the two lines whose <em>difference</em> the interaction describes; dropping one forces the lines through an arbitrary common feature and turns the interaction coefficient into something unintended. R’s formula shorthand respects the hierarchy automatically:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">*</span> z, <span class="at">data =</span> df)  <span class="co"># x * z expands to x + z + x:z</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Before the break, the parallel that organises the whole lecture: block 1 let the slope differ <strong>by group</strong>; block 2 lets the slope differ <strong>along <span class="math inline">\(x\)</span> itself</strong>. Both are the same move — feeding least squares a new constructed column (a product, a square) and reading the fitted combination.</p>
</section>
<section id="curvature-polynomials-are-still-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="curvature-polynomials-are-still-linear-regression">Curvature: polynomials are still linear regression</h3>
<p>Is the season trend even a straight line? A quadratic conditional mean</p>
<p><span class="math display">\[
E[Y\mid X=x]=\beta_0+\beta_1x+\beta_2x^2
\]</span></p>
<p>is curved in <span class="math inline">\(x\)</span> but <strong>linear in the unknown coefficients</strong> <span class="math inline">\(\beta_0,\beta_1,\beta_2\)</span> — and that is all <code>lm()</code> requires. The square is just another constructed predictor column.</p>
<p>What changes is how to read the output. The slope is no longer one number: moving from <span class="math inline">\(x\)</span> to <span class="math inline">\(x+1\)</span> changes the fitted mean by</p>
<p><span class="math display">\[
(\beta_1(x+1)+\beta_2(x+1)^2) - (\beta_1x+\beta_2x^2)
=\beta_1+\beta_2(2x+1),
\]</span></p>
<p>a change that depends on where you start. The standing rule: <strong>never read <span class="math inline">\(\beta_1\)</span> alone while <span class="math inline">\(x^2\)</span> is in the model.</strong> Compute fitted changes or graph the curve.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>linear_season <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_1k, <span class="at">data =</span> sharks)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>poly_season <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> <span class="fu">I</span>(season<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> ask_1k,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> sharks)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(poly_season)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate   Std. Error   t value      Pr(&gt;|t|)
(Intercept) 24.171680818 0.8205664983 29.457309 1.332051e-149
season      -1.713233277 0.2056686354 -8.330066  1.862369e-16
I(season^2)  0.051034200 0.0113694269  4.488722  7.737227e-06
ask_1k      -0.002710806 0.0005740121 -4.722559  2.556506e-06</code></pre>
</div>
</div>
<p>The <code>I()</code> wrapper tells R to square arithmetically rather than read <code>^</code> as formula syntax. The fitted coefficients are <span class="math inline">\(b_1 \approx -1.713\)</span> and <span class="math inline">\(b_2 \approx 0.051\)</span>: a steep early decline that flattens season by season.</p>
<div id="exm-i06-quadratic-change" class="theorem example">
<p><span class="theorem-title"><strong>Example 23.1 (Worked example: the fitted change from Season 5 to Season 6)</strong></span> Holding requested amount fixed, the fitted change from season <span class="math inline">\(x\)</span> to season <span class="math inline">\(x+1\)</span> is <span class="math inline">\(b_1+b_2(2x+1)\)</span>. From Season 5 to Season 6, <span class="math inline">\(x = 5\)</span>:</p>
<p><span class="math display">\[
b_1+b_2(2\times5+1)
=-1.713+0.051\times11
=-1.713+0.561
\approx-1.15
\text{ percentage points.}
\]</span></p>
<p>Reading <span class="math inline">\(b_1=-1.713\)</span> alone would overstate the drop by half a point — that number is the fitted change at the meaningless <span class="math inline">\(x=0\)</span>, not a constant slope. Verification in R, as a difference of two fitted values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">coef</span>(poly_season)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unname</span>(b[<span class="st">"season"</span>] <span class="sc">+</span> b[<span class="st">"I(season^2)"</span>] <span class="sc">*</span> (<span class="dv">2</span> <span class="sc">*</span> <span class="dv">5</span> <span class="sc">+</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.151857</code></pre>
</div>
</div>
</div>
</section>
<section id="is-the-curvature-worth-having-the-partial-f" class="level3">
<h3 class="anchored" data-anchor-id="is-the-curvature-worth-having-the-partial-f">Is the curvature worth having? The partial F</h3>
<p>The quadratic model and the linear model are nested — Lecture 5’s test applies directly to the one added term:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(linear_season, poly_season)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: equity_offered_pct ~ season + ask_1k
Model 2: equity_offered_pct ~ season + I(season^2) + ask_1k
  Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1438 83493                                  
2   1437 82338  1    1154.5 20.149 7.737e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The partial F-test for adding <code>I(season^2)</code> gives <span class="math inline">\(F \approx 20.1\)</span> with p-value below 0.001 in the classical model: the curvature is statistically detectable. Detectable is not dramatic — adjusted <span class="math inline">\(R^2\)</span> moves from about 0.186 to 0.196 — so also assess the substantive shape:</p>
<div class="cell">
<details class="code-fold">
<summary>See the R code for this figure</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>sharks<span class="sc">$</span>ask_1k <span class="ot">&lt;-</span> sharks<span class="sc">$</span>ask_amount_usd <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>poly_season <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> <span class="fu">I</span>(season<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> ask_1k,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> sharks)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>season_means <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(equity_offered_pct <span class="sc">~</span> season, <span class="at">data =</span> sharks, mean)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>curve_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">season =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">16</span>, <span class="at">length.out =</span> <span class="dv">200</span>),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">ask_1k =</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>ask_1k))</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>curve_data<span class="sc">$</span>fit <span class="ot">&lt;-</span> <span class="fu">predict</span>(poly_season, <span class="at">newdata =</span> curve_data)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(season_means, <span class="fu">aes</span>(<span class="at">x =</span> season, <span class="at">y =</span> equity_offered_pct)) <span class="sc">+</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> <span class="dv">16</span>, <span class="at">xmax =</span> <span class="fl">17.6</span>, <span class="at">ymin =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">ymax =</span> <span class="cn">Inf</span>,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="st">"grey75"</span>, <span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">16</span>, <span class="at">colour =</span> <span class="st">"grey60"</span>,</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> curve_data, <span class="fu">aes</span>(<span class="at">x =</span> season, <span class="at">y =</span> fit),</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">colour =</span> <span class="st">"#D55E00"</span>, <span class="at">linewidth =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.6</span>, <span class="at">colour =</span> <span class="st">"#009E73"</span>) <span class="sc">+</span></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">16.8</span>, <span class="at">y =</span> <span class="fu">max</span>(season_means<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"no data beyond</span><span class="sc">\n</span><span class="st">season 16"</span>, <span class="at">colour =</span> <span class="st">"#5B6976"</span>,</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>           <span class="at">size =</span> <span class="dv">3</span>, <span class="at">lineheight =</span> <span class="fl">0.95</span>) <span class="sc">+</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">16</span>, <span class="at">by =</span> <span class="dv">3</span>)) <span class="sc">+</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">17.6</span>)) <span class="sc">+</span></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Season"</span>, <span class="at">y =</span> <span class="st">"Initial equity offered (%)"</span>) <span class="sc">+</span></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#5B6976"</span>),</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">colour =</span> <span class="st">"#17324D"</span>)</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-i06-polynomial" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-i06-polynomial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="i06-interactions-curvature_files/figure-html/fig-i06-polynomial-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-i06-polynomial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;23.3: Raw season means of initial equity offered (points) and the fitted quadratic at the average requested amount (curve). The curve flattens towards the last observed seasons; beyond Season 16 (shaded) it would turn upward, a region with no data support.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The points in <a href="#fig-i06-polynomial" class="quarto-xref">Figure&nbsp;<span>23.3</span></a> are raw season means; the curve holds requested amount at its sample mean. <strong>Do not extrapolate the quadratic beyond Seasons 1–16.</strong> The fitted parabola bottoms out just past Season 16 and would climb steeply afterwards — an artefact of the functional form, not a forecast. Polynomials can turn sharply the moment they leave the data.</p>
<div class="caveat-box">
<p><span class="label">What flexible terms can and cannot repair</span></p>
<p>Interactions and polynomials make the conditional mean more flexible — and that is <em>all</em> they do. They repair nothing about the design: dependence across rows, selection into broadcast, measurement error, unequal error variance, and unmeasured confounding all pass through untouched. Nor is flexibility free: every added term spends precision and invites overfitting if terms are added because they are significant rather than because a substantive question asks for them. Choose terms from the question — “could this trend differ by group?”, “could this relationship bend?” — inspect the implied predictions, and report combined effects, never single coefficients ripped out of a product or a polynomial.</p>
</div>
</section>
<section id="answering-the-driving-question" class="level3">
<h3 class="anchored" data-anchor-id="answering-the-driving-question">Answering the driving question</h3>
<p>Two halves, two verdicts, both with limits. <strong>Same trend for every composition?</strong> The estimated slope difference is <span class="math inline">\(-0.061\)</span> percentage points per season (p <span class="math inline">\(\approx\)</span> 0.52): no detectable difference between the source-defined groups — and no proof of equality, since the estimate is imprecise. <strong>A straight line?</strong> Not quite: the quadratic term is detectable (partial <span class="math inline">\(F \approx 20.1\)</span>, p <span class="math inline">\(&lt;\)</span> 0.001), and the fitted decline flattens from about <span class="math inline">\(-1.56\)</span> points per season early on to about <span class="math inline">\(-0.64\)</span> around Season 10 — a mild, data-supported curvature valid only inside Seasons 1–16, in a model that remains observational throughout.</p>
<p><strong>Next:</strong> Tutorial 2 rehearses Lectures 4–6 in exam format and closes with the integrated modelling task: one full analysis from research question to a 150-word conclusion — outcome, predictors, an extension a real question motivates, and the caveat that headlines it. That is a rehearsal of exactly what the exam, and later your thesis, will ask of you.</p>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<p><span class="time-budget">Total practice time: about 65 minutes.</span></p>
<section id="retrieval-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="retrieval-10-minutes">Retrieval (10 minutes)</h3>
<ol type="1">
<li>What does an interaction coefficient measure, and what are its units in the season-by-group model?</li>
<li>Why centre a predictor before interacting it, and what can centering never change?</li>
<li>State the hierarchy principle.</li>
<li>Why is a quadratic model still a linear regression model?</li>
<li>Why should a polynomial be graphed, and never extrapolated casually?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>How one predictor’s slope differs with the other predictor — here, equity percentage points per season, as a difference between groups.</li>
<li>To make lower-order terms refer to a meaningful value such as the sample mean; it never changes fitted values, residuals, <span class="math inline">\(R^2\)</span>, or the interaction estimate.</li>
<li>Retain the component lower-order terms whenever their interaction or higher-order term is in the model.</li>
<li>It is linear in the unknown coefficients; the squared column is just another constructed predictor.</li>
<li>No single coefficient is the slope, so only fitted values or the curve show the model’s claim — and outside the observed range the curve can turn sharply with no data support.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="centering-verification-10-minutes" class="level3">
<h3 class="anchored" data-anchor-id="centering-verification-10-minutes">Centering verification (10 minutes)</h3>
<p>Fit the interaction model with and without centering season. Verify that the fitted values and the interaction coefficient are unchanged, and report which coefficients do change.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>sharks<span class="sc">$</span>ask_1k <span class="ot">&lt;-</span> sharks<span class="sc">$</span>ask_amount_usd <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>known_gender <span class="ot">&lt;-</span> <span class="fu">subset</span>(sharks, pitcher_gender_group <span class="sc">!=</span> <span class="st">"unknown"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>women <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  known_gender<span class="sc">$</span>pitcher_gender_group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"all_women"</span>, <span class="st">"mixed"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>season_c <span class="ot">&lt;-</span> known_gender<span class="sc">$</span>season <span class="sc">-</span> <span class="fu">mean</span>(known_gender<span class="sc">$</span>season)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>uncentered <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">*</span> women <span class="sc">+</span> ask_1k,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> known_gender)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>centered <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season_c <span class="sc">*</span> women <span class="sc">+</span> ask_1k,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> known_gender)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">fitted</span>(uncentered), <span class="fu">fitted</span>(centered))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">uncentered =</span> <span class="fu">unname</span>(<span class="fu">coef</span>(uncentered)[<span class="st">"season:women"</span>]),</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">centered =</span> <span class="fu">unname</span>(<span class="fu">coef</span>(centered)[<span class="st">"season_c:women"</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> uncentered    centered 
-0.06145941 -0.06145941 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">women_uncentered =</span> <span class="fu">unname</span>(<span class="fu">coef</span>(uncentered)[<span class="st">"women"</span>]),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">women_centered =</span> <span class="fu">unname</span>(<span class="fu">coef</span>(centered)[<span class="st">"women"</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>women_uncentered   women_centered 
       1.3465150        0.8069665 </code></pre>
</div>
</div>
<p>The fitted values agree and both interaction estimates are about <span class="math inline">\(-0.061\)</span>. The lower-order <code>women</code> coefficient changes from about <span class="math inline">\(1.35\)</span> (a comparison at the unobserved Season 0) to about <span class="math inline">\(0.81\)</span> (a comparison at the average season, about 8.8); the intercept changes correspondingly. Centering moved the reading point, not the lines.</p>
</div>
</div>
</div>
</section>
<section id="from-worked-to-faded-a-quadratic-change-15-minutes" class="level3">
<h3 class="anchored" data-anchor-id="from-worked-to-faded-a-quadratic-change-15-minutes">From worked to faded: a quadratic change (15 minutes)</h3>
<p>Re-read the worked Season 5 to 6 calculation (<a href="#exm-i06-quadratic-change" class="quarto-xref">Example&nbsp;<span>23.1</span></a>). Then compute the fitted change from <strong>Season 10 to Season 11</strong> in the same model.</p>
<p><em>Step 1 (given).</em> The recipe is <span class="math inline">\(b_1+b_2(2x+1)\)</span> with <span class="math inline">\(x=10\)</span>, so the multiplier on <span class="math inline">\(b_2\)</span> is <span class="math inline">\(21\)</span>.</p>
<p><em>Step 2 (you).</em> Plug in <span class="math inline">\(b_1\approx-1.713\)</span> and <span class="math inline">\(b_2\approx0.051\)</span>.</p>
<p><em>Step 3 (you).</em> Compare the result with the Season 5 to 6 change and state in one sentence what the comparison shows about the trend.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(-1.713+0.051\times21\approx-1.713+1.072\approx-0.64\)</span> percentage points (exactly: <span class="math inline">\(b_1+21b_2=-0.642\)</span>). The drop per season has shrunk from about <span class="math inline">\(-1.15\)</span> (Seasons 5–6) to about <span class="math inline">\(-0.64\)</span> (Seasons 10–11): the decline flattens in later seasons, which is precisely what a positive <span class="math inline">\(b_2\)</span> says.</p>
</div>
</div>
</div>
<p>Then unassisted, with new coefficients. A model of monthly revenue (€1,000s) on shop age <span class="math inline">\(x\)</span> (years) reports <span class="math inline">\(\widehat Y = 40 - 2.00x + 0.060x^2\)</span>.</p>
<ol type="1">
<li>Compute the fitted change from age 3 to age 4 and from age 8 to age 9.</li>
<li>A colleague reports “revenue falls €2,000 per year of age.” Correct the sentence.</li>
<li>In <span class="math inline">\(Y=10+2X+3D-0.5XD\)</span>, write both group lines and interpret the interaction coefficient.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Age 3 to 4: <span class="math inline">\(-2.00+0.060(2\times3+1)=-2.00+0.42=-1.58\)</span>, about <span class="math inline">\(-€1{,}580\)</span>. Age 8 to 9: <span class="math inline">\(-2.00+0.060\times17=-0.98\)</span>, about <span class="math inline">\(-€980\)</span>.</li>
<li><span class="math inline">\(-2.00\)</span> is the fitted change at age 0 only. With <span class="math inline">\(x^2\)</span> in the model the change depends on age: about <span class="math inline">\(-1.58\)</span> at age 3, about <span class="math inline">\(-0.98\)</span> at age 8 — the decline weakens as shops age.</li>
<li>For <span class="math inline">\(D=0\)</span>: <span class="math inline">\(\widehat Y=10+2X\)</span>. For <span class="math inline">\(D=1\)</span>: <span class="math inline">\(\widehat Y=13+1.5X\)</span>. The interaction <span class="math inline">\(-0.5\)</span> says the <span class="math inline">\(D=1\)</span> slope is 0.5 outcome units per unit of <span class="math inline">\(X\)</span> smaller than the <span class="math inline">\(D=0\)</span> slope.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="cumulative-mini-task-15-minutes" class="level3">
<h3 class="anchored" data-anchor-id="cumulative-mini-task-15-minutes">Cumulative mini-task (15 minutes)</h3>
<p>In Lecture 4 you wrote a paragraph connecting the Lecture 2 diagnostics to the three-predictor equity model. Extend that paragraph by one argument: propose <strong>either</strong> an interaction <strong>or</strong> a polynomial term for that model, state the substantive question that motivates it, and say how you would test whether the term earns its place.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A defensible extension: “The season decline need not be linear — early-seasons novelty and later-seasons professionalisation suggest a flattening trend, so I would add <code>I(season^2)</code>. The term is motivated by the shape question, not by hunting significance. I would test it with a partial F-test against the nested linear model on the same rows (here <span class="math inline">\(F\approx20.1\)</span>, p <span class="math inline">\(&lt;\)</span> 0.001), check that adjusted <span class="math inline">\(R^2\)</span> improves, graph the fitted curve inside Seasons 1–16, and report fitted season-to-season changes rather than the raw <code>season</code> coefficient.” An interaction argument (for example season by gender group, testing whether the trend differs; <span class="math inline">\(F\approx0.41\)</span>, p <span class="math inline">\(\approx\)</span> 0.52, so the term is not retained) is equally valid if it names the motivating question and the nested test.</p>
</div>
</div>
</div>
</section>
<section id="spaced-review-one-partial-f-item-from-lecture-5-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="spaced-review-one-partial-f-item-from-lecture-5-5-minutes">Spaced review: one partial-F item from Lecture 5 (5 minutes)</h3>
<p>Adding the two gender dummies to the season-and-ask model of equity reduced the residual sum of squares by 436.25 using 2 degrees of freedom, and the complete model left 82,792 on 1,429 degrees of freedom. Compute the partial F statistic and state the 5% conclusion.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(F=(436.25/2)/(82{,}792/1{,}429)=218.1/57.9\approx3.76\)</span>, with p <span class="math inline">\(\approx\)</span> 0.023. At 5%, the two category terms are jointly useful in that specification — even though the mixed dummy’s own t-test is far from significant, which is the standing lesson that joint and individual tests answer different questions.</p>
</div>
</div>
</div>
</section>
<section id="worked-exam-interpretation-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="worked-exam-interpretation-5-minutes">Worked exam interpretation (5 minutes)</h3>
<p><strong>Question</strong> (mock exam Question 5 pattern). A model of venture sales growth (percentage points) on marketing spending (€10,000s), an online-only indicator, and their interaction reports <code>spending 1.20</code>, <code>online 2.00</code>, <code>spending:online -0.50</code>. A student writes: “Spending raises growth by 1.2 percentage points per €10,000 for all ventures.” Correct the sentence.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Two repairs. First, with the interaction present, 1.20 is the fitted spending slope for <strong>offline</strong> ventures only (<code>online = 0</code>); for online-only ventures the slope is <span class="math inline">\(1.20-0.50=0.70\)</span> percentage points per €10,000 — there is no single all-venture slope. Second, “raises” claims causation; these are fitted associations among sampled ventures, holding the other included terms fixed, with no design that identifies an effect of spending.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Utility: two sentences</span></p>
<p>Think of your EiA3 venture — or any business you know well. Name one relationship in its data whose <em>slope</em> plausibly depends on something else (price sensitivity differing by segment, campaign effect differing by channel, growth flattening with scale), and write two sentences: first state the interaction or quadratic term you would add and the substantive question behind it, then say what a non-significant result would — and would not — tell you. There is no wrong answer; the point is letting the question, not the software, choose the term.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run campus meal-prep box venture. “I would add an ad-spend × exam-week interaction, because the substantive question is whether ads only work when students are actually on campus. A non-significant interaction would mean no evidence the slopes differ — not proof that exam weeks make no difference.”</p>
</div>
</div>
</div>
<p>You can discuss this task — and any other task in this chapter — with <strong>Tilly</strong>, the course AI assistant on Canvas: ask it to read your two sentences and check whether you treated “no evidence of a difference” as “proof of no difference.”</p>
</div>
<p>Continue to Tutorial 2: Multiple regression and extensions.</p>
<p>Formula sheet: Lecture 6 formulas.</p>
<p>For a more formal treatment, see James et al., <em>An Introduction to Statistical Learning</em>, 2nd ed., Section 3.3.2 and Sections 3.6.4–3.6.6, and <a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>, Chapter 21.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../intermediate/i05-categories-joint-tests.html" class="pagination-link" aria-label="Lecture 5: Categories as predictors and joint tests">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../intermediate/t02-exam-prep.html" class="pagination-link" aria-label="Tutorial 2: Multiple regression and extensions">
        <span class="nav-page-text"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>