<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mock Exam: QM Intermediate – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../advanced/overview.html" rel="next">
<link href="../intermediate/code-sheet.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0373dafead96411fe286b8dec0b5ee25.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../intermediate/overview.html">QM Intermediate: Course overview</a></li><li class="breadcrumb-item"><a href="../intermediate/mock-exam.html"><span class="chapter-title">Mock Exam: QM Intermediate</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to data analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and a first look at regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Hypothesis tests, errors, and power</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#how-this-mock-exam-works" id="toc-how-this-mock-exam-works" class="nav-link active" data-scroll-target="#how-this-mock-exam-works">How this mock exam works</a></li>
  <li><a href="#dataset-used-throughout" id="toc-dataset-used-throughout" class="nav-link" data-scroll-target="#dataset-used-throughout">Dataset used throughout</a></li>
  <li><a href="#question-1-simple-regression-13-points" id="toc-question-1-simple-regression-13-points" class="nav-link" data-scroll-target="#question-1-simple-regression-13-points">Question 1: Simple regression (13 points)</a></li>
  <li><a href="#question-2-assumptions-and-diagnostics-15-points" id="toc-question-2-assumptions-and-diagnostics-15-points" class="nav-link" data-scroll-target="#question-2-assumptions-and-diagnostics-15-points">Question 2: Assumptions and diagnostics (15 points)</a></li>
  <li><a href="#question-3-inference-and-fit-10-points" id="toc-question-3-inference-and-fit-10-points" class="nav-link" data-scroll-target="#question-3-inference-and-fit-10-points">Question 3: Inference and fit (10 points)</a></li>
  <li><a href="#question-4-multiple-regression-and-a-dummy-predictor-23-points" id="toc-question-4-multiple-regression-and-a-dummy-predictor-23-points" class="nav-link" data-scroll-target="#question-4-multiple-regression-and-a-dummy-predictor-23-points">Question 4: Multiple regression and a dummy predictor (23 points)</a></li>
  <li><a href="#question-5-interactions-and-curvature-19-points" id="toc-question-5-interactions-and-curvature-19-points" class="nav-link" data-scroll-target="#question-5-interactions-and-curvature-19-points">Question 5: Interactions and curvature (19 points)</a></li>
  <li><a href="#question-6-an-answer-of-an-ai-assistant-and-a-decision-20-points" id="toc-question-6-an-answer-of-an-ai-assistant-and-a-decision-20-points" class="nav-link" data-scroll-target="#question-6-an-answer-of-an-ai-assistant-and-a-decision-20-points">Question 6: An answer of an AI assistant, and a decision (20 points)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../intermediate/overview.html">QM Intermediate: Course overview</a></li><li class="breadcrumb-item"><a href="../intermediate/mock-exam.html"><span class="chapter-title">Mock Exam: QM Intermediate</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="intermediate-mock-exam" class="quarto-section-identifier"><span class="chapter-title">Mock Exam: QM Intermediate</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This mock exam covers all six lectures of the course. It has <strong>100 points</strong>, so your test score is</p>
<p><span class="math display">\[
\text{test score} = \frac{\text{points earned}}{10},
\]</span></p>
<p>on a scale from 1.00 to 10.00, with two decimals. A score below 1.00 counts as 1.00. The lecturer enters this test score in Osiris. Osiris then rounds it to a whole or half grade for your final course grade. A score from 5.50 to 5.74 becomes 6.0, and a score from 5.25 to 5.49 becomes 5.0. For example, 72 points give a test score of 7.20 and a final grade of 7.0. You pass with a final grade of 6.0 or higher, that is, with 55 points or more.</p>
<p>You take the Intermediate exam in TestVision. It lasts 120 minutes. You may use RStudio, Excel, the calculator in TestVision, a simple pocket calculator, and scrap paper. The practice exam in TestVision appears in your own TestVision account once the lecturer publishes it. You log in with your university account. There is no separate link. General information about TestVision for students is on the <a href="https://www.tilburguniversity.edu/students/studying/exams/e-assessment/testvision">university page about TestVision</a>.</p>
<p>You receive the <a href="../intermediate/code-sheet.html">QM Intermediate Code Sheet</a> at the exam. Keep it open while you work on this mock exam.</p>
<p>Use <strong>120 minutes</strong> as the practice time limit, as in the exam.</p>
<section id="how-this-mock-exam-works" class="level2">
<h2 class="anchored" data-anchor-id="how-this-mock-exam-works">How this mock exam works</h2>
<p>This mock exam gives an impression of what an exam in this course can look like. You download a data file, you run R yourself, and you type your answers.</p>
<p>All parts are open questions. You type a number with your calculation, or one to three sentences. An answer without a calculation or an explanation gets no points, unless the part asks only to report or to state something.</p>
<p>You do not have to simulate data, and you do not have to reproduce a simulation. The practice data are invented. The code that made them is in a collapsed box at the end of this page. It is there only so that anyone can check how we made the data. It is not part of the exam.</p>
<p>A part that starts with “In R:” needs code that you write and run yourself. Its answer is not printed in the question. For these parts, copy the R code that you used into your answer, and type the numbers that the part asks for. You can answer all other parts from your own results, from printed output, or with a short calculation. You may use R as a calculator everywhere.</p>
<p>Question 3 shows an R output of a colleague, and Question 4 shows a regression table in the layout of a research paper. You interpret them. Question 6 shows an answer of an AI assistant. You assess it.</p>
<p>All tests in this course are two-sided. Use a 5% significance level. Some parts that build on an “In R:” part print stand-in values. Use them if your code does not run.</p>
</section>
<section id="dataset-used-throughout" class="level2">
<h2 class="anchored" data-anchor-id="dataset-used-throughout">Dataset used throughout</h2>
<p>The practice data are invented. Treat them as a simple random sample of 320 young ventures from a business registry. One row is one venture. The data are observational: none of the predictors was assigned by chance.</p>
<ul>
<li><code>growth_pct</code>: growth of annual sales compared with the year before, in percent. A value of 12 means that sales were 12% higher than in the year before</li>
<li><code>marketing_10k</code>: annual marketing spending, in €10,000s. The values run from 0.25 (€2,500) to 7.99 (€79,900)</li>
<li><code>experience_years</code>: prior industry experience of the lead founder, in years, from 0 to 18</li>
<li><code>team_size</code>: number of current team members, from 1 to 10</li>
<li><code>digital</code>: <code>No</code> for a mainly physical offering and <code>Yes</code> for a mainly digital offering. <code>No</code> is the reference category</li>
<li><code>spend_c</code>: <code>marketing_10k - 4</code>, marketing spending centred at €40,000. This is close to the sample mean of about €40,400.</li>
</ul>
<p>The population is the set of ventures in this registry. The data do not measure later survival or market conditions.</p>
<p><a href="../data/qm-intermediate-mock-exam.csv">Download <code>qm-intermediate-mock-exam.csv</code></a>, save it in the folder <code>data</code> of your R project, and load it with the code below. If you save the file directly in your project folder, write <code>"qm-intermediate-mock-exam.csv"</code> as the file name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>ventures <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/qm-intermediate-mock-exam.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>ventures<span class="sc">$</span>digital <span class="ot">&lt;-</span> <span class="fu">factor</span>(ventures<span class="sc">$</span>digital, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="question-1-simple-regression-13-points" class="level2">
<h2 class="anchored" data-anchor-id="question-1-simple-regression-13-points">Question 1: Simple regression (13 points)</h2>
<p>A founder asks whether ventures that spend more on marketing grow faster. The outcome is <code>growth_pct</code> and the predictor is <code>marketing_10k</code>.</p>
<ol type="1">
<li><p>In R: load the data and check that the file has 320 rows. Report the mean and the largest value of <code>growth_pct</code>. <strong>(2 points)</strong></p></li>
<li><p>In R: fit the simple regression of <code>growth_pct</code> on <code>marketing_10k</code>. Report the intercept and the slope. <strong>(2 points)</strong></p>
<p>Stand-in values, if your code does not run: intercept 6.6 and slope 1.4. Use them in parts 3 and 4.</p></li>
<li><p>Interpret the slope in one sentence. <strong>(4 points)</strong></p></li>
<li><p>In R: use <code>predict()</code> to calculate the fitted growth of a venture that spends €50,000 on marketing. The actual sales growth of this venture is 11%. Calculate its residual. State what the sign of the residual means. <strong>(5 points)</strong></p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Code</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Part 1</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>ventures <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/qm-intermediate-mock-exam.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>ventures<span class="sc">$</span>digital <span class="ot">&lt;-</span> <span class="fu">factor</span>(ventures<span class="sc">$</span>digital, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(ventures)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 320</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(ventures<span class="sc">$</span>growth_pct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.17166</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(ventures<span class="sc">$</span>growth_pct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31.94</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Part 2</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>simple_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(growth_pct <span class="sc">~</span> marketing_10k, <span class="at">data =</span> ventures)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(simple_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) marketing_10k 
     6.598158      1.378342 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Part 4</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>fit_50k <span class="ot">&lt;-</span> <span class="fu">predict</span>(simple_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">marketing_10k =</span> <span class="dv">5</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>fit_50k</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
13.48987 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="dv">11</span> <span class="sc">-</span> fit_50k</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
-2.489868 </code></pre>
</div>
</div>
<p><strong>Answers</strong></p>
<ol type="1">
<li>The file has 320 rows. The mean sales growth is 12.172%. The largest sales growth is 31.94%.</li>
<li>Intercept 6.598 and slope 1.378. The fitted line is <span class="math inline">\(\widehat{growth\_pct}=6.598+1.378\,marketing\_10k\)</span>.</li>
<li>Among the 320 sampled ventures, a venture that spends €10,000 more on marketing has on average 1.38 percentage points higher fitted sales growth.</li>
<li>€50,000 is <code>marketing_10k = 5</code>. The fitted growth is 13.49%. The residual is <span class="math inline">\(11-13.49=-2.49\)</span> percentage points. The sign is negative: this venture grew less than the fitted growth for ventures with the same marketing spending.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="question-2-assumptions-and-diagnostics-15-points" class="level2">
<h2 class="anchored" data-anchor-id="question-2-assumptions-and-diagnostics-15-points">Question 2: Assumptions and diagnostics (15 points)</h2>
<p>Check the model of Question 1, <code>growth_pct ~ marketing_10k</code>. Parts 1 and 4 ask for two plots.</p>
<ol type="1">
<li>In R: make the residual-versus-fitted plot of the model. Describe in one sentence the pattern that you see. State the assumption that this pattern challenges. <strong>(5 points)</strong></li>
<li>In R: count the ventures with a standardised residual beyond <span class="math inline">\(\pm3\)</span>. Then count the ventures with a Cook’s distance above <span class="math inline">\(4/n\)</span>. Report both counts. <strong>(2 points)</strong></li>
<li>A colleague wants to delete all ventures that part 2 flags, “to get a cleaner model”. Respond to her plan in two or three sentences. State the rule of Lecture 2 for flagged observations, and say what you would do with these ventures. <strong>(4 points)</strong></li>
<li>In R: make the normal Q–Q plot of the standardised residuals. Describe in one sentence how the points lie relative to the line. Then explain in one sentence whether a departure from normality is a serious problem for this model with 320 ventures. <strong>(4 points)</strong></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Code</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Part 1</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(simple_model), <span class="fu">residuals</span>(simple_model),</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Fitted value"</span>, <span class="at">ylab =</span> <span class="st">"Residual"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mock-exam_files/figure-html/imock-q2-resid-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Part 2</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(<span class="fu">rstandard</span>(simple_model)) <span class="sc">&gt;</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">cooks.distance</span>(simple_model) <span class="sc">&gt;</span> <span class="dv">4</span> <span class="sc">/</span> <span class="fu">nobs</span>(simple_model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Part 4</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">rstandard</span>(simple_model))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">rstandard</span>(simple_model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mock-exam_files/figure-html/imock-q2-qq-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Answers</strong></p>
<ol type="1">
<li>The vertical spread of the residuals grows from left to right, that is, with the fitted growth. The points form a fan shape. This is heteroskedasticity, so it challenges the assumption of homoskedasticity (constant variance of the errors).</li>
<li>One venture has a standardised residual beyond <span class="math inline">\(\pm3\)</span>. 19 ventures have a Cook’s distance above <span class="math inline">\(4/n=4/320=0.0125\)</span>.</li>
<li>The rule is: investigate, report, never silently delete. Investigate means to look at the flagged ventures in the data and to ask whether a value is an error or whether the venture is of a different kind. Report means to fit the model with and without these ventures, to show both results, and to say which one you use and why.</li>
<li>The points follow the line in the middle. At the upper end they lie above the line, and near the lower end slightly below it. This is not a serious problem here. Normal errors matter in small samples. With 320 ventures the tests and intervals still hold approximately.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="question-3-inference-and-fit-10-points" class="level2">
<h2 class="anchored" data-anchor-id="question-3-inference-and-fit-10-points">Question 3: Inference and fit (10 points)</h2>
<p>A colleague drew 200 of the 320 ventures at random and fitted the model below to these 200 ventures. You do not know which ventures she drew, so you cannot run this model yourself. Answer from her output. The formulas are on the code sheet.</p>
<pre class="text"><code>Call:
lm(formula = growth_pct ~ marketing_10k + experience_years + 
    digital, data = ventures_200)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.2970  -2.7338  -0.0992   2.6132  12.3786 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       2.73159    0.78897   3.462 0.000658 ***
marketing_10k     1.35473    0.12868  10.528  &lt; 2e-16 ***
experience_years  0.28585    0.05277   5.417 1.77e-07 ***
digitalYes        3.17544    0.58246   5.452 1.49e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.049 on 196 degrees of freedom
Multiple R-squared:  0.4803,    Adjusted R-squared:  0.4723 
F-statistic: 60.38 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>For this model, SSE = 3212.85 and SST = 6181.93. The critical value for a 95% confidence interval and a 5% test with 196 degrees of freedom is <span class="math inline">\(t_{0.975,\,196}=1.972\)</span>. In R, <code>qt(0.975, 196)</code> gives it.</p>
<ol type="1">
<li>(a) Show with a calculation how the Multiple R-squared follows from SSE and SST. (b) State in one sentence what this number says about the model for these 200 ventures. <strong>(4 points)</strong></li>
<li>(a) Calculate the 95% confidence interval for the coefficient of <code>marketing_10k</code>. Write the five parts of the <a href="../intermediate/i03-inference-fit-ftest.html#i03-exam-procedure">exam procedure of Lecture 3</a>. (b) State whether the 5% test rejects a coefficient of zero, and explain how the interval shows this. <strong>(6 points)</strong></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answers</strong></p>
<ol type="1">
<li>(a) <span class="math inline">\(R^2=1-\text{SSE}/\text{SST}=1-3212.85/6181.93=0.48\)</span>. (b) Among these 200 ventures, the model explains about 48% of the variation in sales growth.</li>
<li>(a) The five parts of the interval:
<ol type="1">
<li><strong>Formula.</strong> <span class="math inline">\(\hat\beta_j\pm t_{0.975,\,df}\,\operatorname{SE}(\hat\beta_j)\)</span>, with <span class="math inline">\(df=n-k-1=200-3-1=196\)</span>.</li>
<li><strong>Given values.</strong> <span class="math inline">\(\hat\beta_j=1.35473\)</span>, <span class="math inline">\(\operatorname{SE}(\hat\beta_j)=0.12868\)</span>, and <span class="math inline">\(t_{0.975,\,196}=1.972\)</span>.</li>
<li><strong>Calculations.</strong> The margin of error is <span class="math inline">\(1.972\times0.12868=0.254\)</span>.</li>
<li><strong>Interval.</strong> <span class="math inline">\((1.355-0.254,\ 1.355+0.254)=(1.10,\ 1.61)\)</span> percentage points per €10,000.</li>
<li><strong>Conclusion.</strong> See (b).</li>
</ol>
(b) Zero lies outside the interval. The interval contains the values of the coefficient that the two-sided 5% test does not reject, so the test rejects a coefficient of zero. At the 5% level we can conclude the following for all ventures in the registry: at the same experience and offering type, more marketing spending goes with higher sales growth.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="question-4-multiple-regression-and-a-dummy-predictor-23-points" class="level2">
<h2 class="anchored" data-anchor-id="question-4-multiple-regression-and-a-dummy-predictor-23-points">Question 4: Multiple regression and a dummy predictor (23 points)</h2>
<p>The table below has the layout of a regression table in a research paper. It shows three models of sales growth (<code>growth_pct</code>), fitted to all 320 ventures of the practice data. You do not need to run these models for parts 1 to 3.</p>
<div class="reg-table">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">(1)</th>
<th style="text-align: right;">(2)</th>
<th style="text-align: right;">(3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Marketing spending (€10,000s)</td>
<td style="text-align: right;">1.340***</td>
<td style="text-align: right;">1.338***</td>
<td style="text-align: right;">1.341***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(0.106)</td>
<td style="text-align: right;">(0.100)</td>
<td style="text-align: right;">(0.100)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Digital offering (1 = yes)</td>
<td style="text-align: right;">2.969***</td>
<td style="text-align: right;">3.016***</td>
<td style="text-align: right;">3.084***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(0.488)</td>
<td style="text-align: right;">(0.462)</td>
<td style="text-align: right;">(0.463)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Founder experience (years)</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.255***</td>
<td style="text-align: right;">0.258***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">(0.042)</td>
<td style="text-align: right;">(0.041)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Team size (members)</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.168</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">(0.103)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">5.418***</td>
<td style="text-align: right;">3.206***</td>
<td style="text-align: right;">2.449**</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(0.528)</td>
<td style="text-align: right;">(0.617)</td>
<td style="text-align: right;">(0.771)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Observations</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">320</td>
<td style="text-align: right;">320</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(R^2\)</span></td>
<td style="text-align: right;">0.395</td>
<td style="text-align: right;">0.459</td>
<td style="text-align: right;">0.464</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adjusted <span class="math inline">\(R^2\)</span></td>
<td style="text-align: right;">0.391</td>
<td style="text-align: right;">0.454</td>
<td style="text-align: right;">0.457</td>
</tr>
</tbody>
</table>
</div>
<p>Outcome: sales growth (%). Ordinary least squares. Standard errors in parentheses. All three columns use the same 320 ventures. The reference category of the dummy is ventures with a mainly physical offering. * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001.</p>
<p>The critical value for a 95% confidence interval and a 5% test is <span class="math inline">\(t_{0.975,\,df}=1.967\)</span> in all three columns. For column (3), with <span class="math inline">\(df=320-4-1=315\)</span>, R gives it with <code>qt(0.975, 315)</code>.</p>
<ol type="1">
<li><p>Team size has no star in column (3). Calculate its t statistic. Then state what the missing star means and what it does not mean. <strong>(4 points)</strong></p></li>
<li><p>Venture B spends €30,000 more on marketing than venture A. Its lead founder has 4 more years of experience. B has a digital offering and A a physical one. Both have the same team size. Calculate the fitted growth of B minus the fitted growth of A with column (3). <strong>(5 points)</strong></p></li>
<li><p>Founder experience has three stars in column (2). Still, adding it moves the marketing coefficient only from 1.340 to 1.338. Explain in one or two sentences what this says about experience and marketing spending in this sample. Then state one problem that the stable coefficient does not exclude. <strong>(5 points)</strong></p></li>
<li><p>In R: test whether founder experience and team size together improve the model of column (1). Fit the models of columns (1) and (3) and compare them with <code>anova()</code>. Report the F statistic. Then show how F follows from the two residual sums of squares in your output. <strong>(4 points)</strong></p>
<p>Stand-in values, if your code does not run: the residual sum of squares is about 5950 on 317 degrees of freedom for column (1). It is about 5270 on 315 degrees of freedom for column (3). Calculate F from them. For part 5, use a p-value below 0.001.</p></li>
<li><p>State the null hypothesis of the test in part 4 and your conclusion at the 5% level. Then explain in one sentence how this conclusion and the missing star of team size can both be true. <strong>(5 points)</strong></p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Code</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Part 4</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>col_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(growth_pct <span class="sc">~</span> marketing_10k <span class="sc">+</span> digital, <span class="at">data =</span> ventures)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>col_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  growth_pct <span class="sc">~</span> marketing_10k <span class="sc">+</span> digital <span class="sc">+</span> experience_years <span class="sc">+</span> team_size,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> ventures</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(col_1, col_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: growth_pct ~ marketing_10k + digital
Model 2: growth_pct ~ marketing_10k + digital + experience_years + team_size
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1    317 5949.3                                  
2    315 5272.6  2    676.77 20.216 5.491e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Answers</strong></p>
<ol type="1">
<li><span class="math inline">\(t=0.168/0.103=1.63\)</span>. The test in five steps:
<ol type="1">
<li><strong>Hypotheses.</strong> <span class="math inline">\(H_0:\beta_{team}=0\)</span> versus <span class="math inline">\(H_1:\beta_{team}\ne0\)</span>, where <span class="math inline">\(\beta_{team}\)</span> is the coefficient of team size in the model of column (3) for all ventures of the registry. The significance level is <span class="math inline">\(\alpha=0.05\)</span>.</li>
<li><strong>Test statistic.</strong> <span class="math inline">\(T=\hat\beta_{team}/\operatorname{SE}(\hat\beta_{team})\)</span>, which has the <span class="math inline">\(t_{315}\)</span> distribution if <span class="math inline">\(H_0\)</span> is true.</li>
<li><strong>Critical value and rejection region.</strong> <span class="math inline">\(t_{0.975,\,315}=1.967\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t\le-1.967\)</span> or <span class="math inline">\(t\ge1.967\)</span>.</li>
<li><strong>Observed value.</strong> The numbers in parentheses are standard errors, so <span class="math inline">\(t=0.168/0.103=1.63\)</span>.</li>
<li><strong>Conclusion.</strong> 1.63 lies between <span class="math inline">\(-1.967\)</span> and 1.967, so do not reject <span class="math inline">\(H_0\)</span>. The p-value is above 0.05, and so there is no star. At the 5% level we cannot conclude that team size goes with growth at fixed marketing spending, offering type, and experience.</li>
</ol>
What the missing star does not mean: it does not show that the coefficient is zero. The 95% interval, <span class="math inline">\(0.168\pm1.967\times0.103\)</span>, runs from <span class="math inline">\(-0.035\)</span> to 0.371 percentage points per team member. It contains zero and also clearly positive values.</li>
<li>Marketing: €30,000 is 3 steps, so <span class="math inline">\(3\times1.341=4.023\)</span>. Experience: <span class="math inline">\(4\times0.258=1.032\)</span>. Digital offering: 3.084. Sum: <span class="math inline">\(4.023+1.032+3.084=8.14\)</span> percentage points.</li>
<li>A coefficient changes when the added predictor is related to the outcome and also to the predictor of interest. Experience is related to growth, but in this sample it is almost unrelated to marketing spending. So holding it fixed changes the marketing comparison very little. The stable coefficient does not exclude a variable that is not in the data and that is related to both marketing spending and growth, for example the quality of the product.</li>
<li><span class="math inline">\(F=20.216\)</span>. From the output, with the partial F statistic, <span class="math inline">\(q=2\)</span>, and <span class="math inline">\(df=315\)</span>: <span class="math inline">\(F=\dfrac{(5949.3-5272.6)/2}{5272.6/315}=\dfrac{338.35}{16.74}=20.21\)</span>.</li>
<li><span class="math inline">\(H_0\)</span>: the coefficients of founder experience and team size are both zero. The p-value in the <code>anova()</code> output is 5.491e-09, that is 0.000000005, far below 0.05. So reject <span class="math inline">\(H_0\)</span>. At the 5% level we can conclude that the two predictors together improve the model of column (1). The F-test asks about the two terms together, and the t-test asks about team size alone. The joint result comes from experience. A set of terms can be jointly significant while one of its terms is not significant.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="question-5-interactions-and-curvature-19-points" class="level2">
<h2 class="anchored" data-anchor-id="question-5-interactions-and-curvature-19-points">Question 5: Interactions and curvature (19 points)</h2>
<p>Parts 1 to 3 ask whether marketing spending goes with more growth for digital ventures than for physical ventures. Parts 4 to 6 use a model in which the relation between marketing spending and growth can be curved.</p>
<ol type="1">
<li><p>In R: fit a model of <code>growth_pct</code> with <code>spend_c</code>, <code>digital</code>, the interaction of the two, and <code>experience_years</code>. Report the coefficients of <code>spend_c</code>, <code>digitalYes</code>, and the interaction. <strong>(3 points)</strong></p>
<p>Stand-in values, if your code does not run: 1.0 for <code>spend_c</code>, 3.0 for <code>digitalYes</code>, and 0.7 for the interaction. Use them in parts 2 and 3.</p></li>
<li><p>State the marketing slope for physical ventures. Calculate the marketing slope for digital ventures. <strong>(3 points)</strong></p></li>
<li><p>Interpret the interaction coefficient in one sentence. <strong>(4 points)</strong></p></li>
<li><p>In R: run the model below, which has no interaction and adds the square of marketing spending. Report the coefficients of <code>marketing_10k</code> and <code>I(marketing_10k^2)</code>. <strong>(2 points)</strong></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>curve_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  growth_pct <span class="sc">~</span> marketing_10k <span class="sc">+</span> <span class="fu">I</span>(marketing_10k<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> digital <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    experience_years,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> ventures</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Stand-in values, if your code does not run: 2.2 for <code>marketing_10k</code> and <span class="math inline">\(-0.10\)</span> for <code>I(marketing_10k^2)</code>. Use them in part 5.</p></li>
<li><p>Use the model of part 4. Calculate the fitted change in growth when marketing spending rises from €20,000 to €30,000, and when it rises from €60,000 to €70,000. Offering type and experience stay fixed. Then state in one sentence what the two results show together. <strong>(4 points)</strong></p></li>
<li><p>A founder plans to spend €150,000 on marketing. She wants to use the model of part 4 to calculate her fitted growth. Explain in one or two sentences why she should not do this. <strong>(3 points)</strong></p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Code</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Part 1</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>interaction_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  growth_pct <span class="sc">~</span> spend_c <span class="sc">*</span> digital <span class="sc">+</span> experience_years,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> ventures</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(interaction_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       (Intercept)            spend_c         digitalYes   experience_years 
         8.6155744          1.0437427          2.9667215          0.2454432 
spend_c:digitalYes 
         0.6599745 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Part 4</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>curve_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  growth_pct <span class="sc">~</span> marketing_10k <span class="sc">+</span> <span class="fu">I</span>(marketing_10k<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> digital <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    experience_years,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> ventures</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(curve_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       (Intercept)      marketing_10k I(marketing_10k^2)         digitalYes 
         2.0676173          2.1793589         -0.1045546          3.0101736 
  experience_years 
         0.2543531 </code></pre>
</div>
</div>
<p><strong>Answers</strong></p>
<ol type="1">
<li><code>spend_c</code> 1.044, <code>digitalYes</code> 2.967, interaction <code>spend_c:digitalYes</code> 0.660.</li>
<li>Physical ventures (<code>digital = No</code>): 1.044 percentage points per €10,000. Digital ventures: <span class="math inline">\(1.044+0.660=1.704\)</span> percentage points per €10,000.</li>
<li>Among the 320 sampled ventures and at the same founder experience, each additional €10,000 of marketing spending goes with 0.66 percentage points more sales growth for digital ventures than for physical ventures.</li>
<li><code>marketing_10k</code> 2.179 and <code>I(marketing_10k^2)</code> <span class="math inline">\(-0.105\)</span>.</li>
<li>The fitted change from <span class="math inline">\(x\)</span> to <span class="math inline">\(x+1\)</span> is <span class="math inline">\(\hat\beta_1+\hat\beta_2(2x+1)\)</span>. From €20,000 to €30,000, <span class="math inline">\(x=2\)</span>: <span class="math inline">\(2.1794-0.1046\times5=1.66\)</span> percentage points. From €60,000 to €70,000, <span class="math inline">\(x=6\)</span>: <span class="math inline">\(2.1794-0.1046\times13=0.82\)</span> percentage points. Together: the same extra €10,000 goes with about half as much extra growth at the higher level of spending. The fitted curve becomes flatter.</li>
<li>€150,000 is far outside the range of the data. The largest spending in the sample is €79,900. No venture in the data supports the curve there. A quadratic curve does not stop curving. This one turns downward at about €104,000 of spending, and no data show such a turn.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="question-6-an-answer-of-an-ai-assistant-and-a-decision-20-points" class="level2">
<h2 class="anchored" data-anchor-id="question-6-an-answer-of-an-ai-assistant-and-a-decision-20-points">Question 6: An answer of an AI assistant, and a decision (20 points)</h2>
<p>Sara runs a young venture with a mainly digital offering. She gave column (3) of the table in Question 4 to an AI assistant. Here is column (3) again:</p>
<pre class="text"><code>Outcome: sales growth (%), 320 ventures     Estimate  Std. Error
Marketing spending (€10,000s)                  1.341       0.100
Digital offering (1 = yes)                     3.084       0.463
Founder experience (years)                     0.258       0.041
Team size (members)                            0.168       0.103
Intercept                                      2.449       0.771</code></pre>
<p>She asked: “What does this mean for my marketing budget?” The AI answered:</p>
<blockquote class="blockquote">
<p>“Good news. Your model controls for experience, team size, and offering type. So the marketing coefficient is a causal effect: if you spend €20,000 more on marketing, your sales growth will rise by 2.68 percentage points. Your venture is digital, and digital ventures grow 3.084% faster than the average venture. And the p-value of marketing is below 0.001, which proves that the assumptions of the model hold.”</p>
</blockquote>
<ol type="1">
<li>Assess the claim that the marketing coefficient is a causal effect. (a) Explain whether the control variables in the model justify this claim. (b) Write a sentence about €20,000 more marketing spending that the table does support. <strong>(5 points)</strong></li>
<li>Assess the sentence about digital ventures. Explain two errors in it, and write a correct sentence about the coefficient 3.084. <strong>(4 points)</strong></li>
<li>Assess the last sentence. (a) Explain whether a small p-value can show that the assumptions of the model hold. (b) State what the small p-value of marketing does show. <strong>(4 points)</strong></li>
</ol>
<p>Sara’s venture had sales of €1,000,000 last year. So 1 percentage point of sales growth is €10,000 of extra sales. Of each euro of sales, 50 cents are left as margin after the direct costs. Sara is considering spending €10,000 more on marketing next year.</p>
<ol start="4" type="1">
<li>The 95% confidence interval of the marketing coefficient in column (3) runs from 1.14 to 1.54 percentage points per €10,000. Show with a calculation that €10,000 more marketing spending goes with extra sales between €11,400 and €15,400, and with an extra margin between €5,700 and €7,700. <strong>(2 points)</strong></li>
<li>(a) Decide whether Sara should spend the extra €10,000 on the basis of these numbers, and give your reason in one sentence. (b) Explain one reason why her true gain could differ from these numbers. <strong>(5 points)</strong></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answers</strong></p>
<ol type="1">
<li><p>(a) No.&nbsp;A control variable holds fixed only what is measured and in the model. Variables that are not in the data can influence both marketing spending and growth, for example the quality of the product. (b) “At the same experience, team size, and offering type, ventures that spend €20,000 more on marketing have on average 2.68 percentage points higher fitted sales growth.”</p></li>
<li><p>The outcome is in percent, so the difference is 3.084 percentage points, not 3.084%: “3.084% faster” would be a relative change. The comparison is with the reference category, ventures with a mainly physical offering, and not with the average venture. A correct sentence: “Ventures with a mainly digital offering have on average 3.084 percentage points higher fitted sales growth than ventures with a mainly physical offering that have the same marketing spending, experience, and team size.”</p></li>
<li><p>(a) No.&nbsp;A p-value is calculated under the assumptions of the model, so it cannot prove them. (b) The small p-value is evidence against a marketing coefficient of zero, if the assumptions hold.</p></li>
<li><p>Extra sales: <span class="math inline">\(1.14\times\text{€}10{,}000=\text{€}11{,}400\)</span> at the lower end and <span class="math inline">\(1.54\times\text{€}10{,}000=\text{€}15{,}400\)</span> at the upper end. Extra margin at 50 cents per euro: <span class="math inline">\(0.5\times\text{€}11{,}400=\text{€}5{,}700\)</span> and <span class="math inline">\(0.5\times\text{€}15{,}400=\text{€}7{,}700\)</span>.</p></li>
<li><p>(a) Decision: do not spend the extra €10,000 on this evidence. Reason: even at the upper end of the interval, the extra margin of €7,700 is below the €10,000 that the marketing costs.</p>
<p>(b) The coefficient is an association among 320 ventures in observational data. It is not the effect of a change in her own budget, which can be smaller or larger.</p></li>
</ol>
</div>
</div>
</div>
<p>The questions of this mock exam have 100 points together. Do the mock exam in R before you open the answers. Use the model answers to check your numbers, and also your units, reference categories, statements about what is held fixed, and the limits of causal claims.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Optional: how the practice data were made (not part of the exam)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You do not need this box for any question. The practice data were made with the code below. The fixed seed makes sure that the code always gives the same 320 rows as the file that you download. Answer every question for the registry data as the text describes them, not for this code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">734</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>n_mock <span class="ot">&lt;-</span> <span class="dv">320</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>marketing_10k <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(n_mock, <span class="fl">0.25</span>, <span class="dv">8</span>), <span class="dv">2</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>experience_years <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">18</span>, n_mock, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>team_size <span class="ot">&lt;-</span> <span class="fu">sample</span>(</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, n_mock, <span class="at">replace =</span> <span class="cn">TRUE</span>,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">16</span>, <span class="dv">20</span>, <span class="dv">20</span>, <span class="dv">14</span>, <span class="dv">9</span>, <span class="dv">6</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>digital <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(<span class="fu">runif</span>(n_mock) <span class="sc">&lt;</span> <span class="fl">0.45</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>spend_c <span class="ot">&lt;-</span> marketing_10k <span class="sc">-</span> <span class="dv">4</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>growth_mean <span class="ot">&lt;-</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>  <span class="dv">8</span> <span class="sc">+</span> <span class="fl">1.10</span> <span class="sc">*</span> spend_c <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> (digital <span class="sc">==</span> <span class="st">"Yes"</span>) <span class="sc">-</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  <span class="fl">0.10</span> <span class="sc">*</span> spend_c<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="fl">0.30</span> <span class="sc">*</span> experience_years <span class="sc">+</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  <span class="fl">0.70</span> <span class="sc">*</span> spend_c <span class="sc">*</span> (digital <span class="sc">==</span> <span class="st">"Yes"</span>) <span class="sc">+</span> <span class="fl">0.20</span> <span class="sc">*</span> team_size</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>growth_pct <span class="ot">&lt;-</span> <span class="fu">round</span>(</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>  growth_mean <span class="sc">+</span> <span class="fu">rnorm</span>(n_mock, <span class="dv">0</span>, <span class="fl">2.5</span> <span class="sc">+</span> <span class="fl">0.40</span> <span class="sc">*</span> marketing_10k),</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2</span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>ventures <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>  growth_pct, marketing_10k, experience_years, team_size, digital, spend_c</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../intermediate/code-sheet.html" class="pagination-link" aria-label="QM Intermediate Code Sheet">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">QM Intermediate Code Sheet</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../advanced/overview.html" class="pagination-link" aria-label="QM Advanced: Course overview">
        <span class="nav-page-text">QM Advanced: Course overview</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>