<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial 2: Multiple regression and extensions – Quantitative Methods to Understand E&amp;BI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../intermediate/code-sheet.html" rel="next">
<link href="../intermediate/i06-interactions-curvature.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1825cde5eff643560dd74da544ac5848.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../intermediate/overview.html">QM Intermediate: Course overview</a></li><li class="breadcrumb-item"><a href="../intermediate/t02-exam-prep.html"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Quantitative Methods to Understand E&amp;BI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../basic/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Basic: Course overview</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b01-introduction-data-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Introduction to Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b02-probability-foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: Probability foundations and random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b03-discrete-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Discrete distributions, expectation, and variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Evidence and probability foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b04-conditioning-bayes-independence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Conditioning, Bayes’ rule, and independence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b05-joint-covariance-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Joint random variables, covariance, and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t02-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 2: Conditioning and relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b06-continuous-normal.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Continuous distributions and the normal model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b07-samples-estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 7: Samples, parameters, and estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b08-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 8: Sampling distributions and the central limit theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t03-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 3: Normal models, sampling, and standard errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b09-t-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 9: The t distribution and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/b10-testing-errors-power.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 10: Testing decisions, errors, power, and the road to regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/t04-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 4: Inference and tests against zero</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/formula-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Basic Formula Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../basic/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Basic</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../intermediate/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">QM Intermediate: Course overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i01-simple-linear-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 1: Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i02-assumptions-diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 2: What the model assumes and how residuals reveal it</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i03-inference-fit-ftest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 3: Coefficient inference, fit, and the F-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t01-exam-prep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial 1: Simple regression, diagnostics, and model usefulness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i04-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 4: Multiple regression and what controls do</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i05-categories-joint-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 5: Categories as predictors and joint tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/i06-interactions-curvature.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lecture 6: Interactions and curvature</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/t02-exam-prep.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/code-sheet.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">QM Intermediate Code Sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intermediate/mock-exam.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mock Exam: QM Intermediate</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">QM Advanced: Course overview</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Supplementary resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/how-to-succeed.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to succeed in this course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/math-refresher.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mathematics Refresher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/video-guide.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">External Video Guide</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#before-class" id="toc-before-class" class="nav-link active" data-scroll-target="#before-class">Before class</a></li>
  <li><a href="#in-the-tutorial" id="toc-in-the-tutorial" class="nav-link" data-scroll-target="#in-the-tutorial">In the tutorial</a></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../intermediate/overview.html">QM Intermediate: Course overview</a></li><li class="breadcrumb-item"><a href="../intermediate/t02-exam-prep.html"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="i-ep02" class="quarto-section-identifier"><span class="chapter-title">Tutorial 2: Multiple regression and extensions</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="outcomes">
<p><span class="label">By the end of Tutorial 2, you can</span></p>
<ul>
<li>fit and interpret a multiple regression in R</li>
<li>test single coefficients and groups of coefficients against zero</li>
<li>interpret dummy, interaction, and quadratic terms correctly</li>
<li>compare nested models with a partial F-test</li>
<li>read a regression table as printed in a research paper</li>
<li>write a complete analysis that is ready for the exam format and states its limits.</li>
</ul>
</div>
<p>Tutorials are <strong>exam preparation sessions</strong>. Every task below follows the format of the final exam. You first try each task in pairs. You may use AI for this, following Attempt, Ask, Verify, Explain. Then the solution is discussed together.</p>
<p>The tasks follow the order of the course. Task 1 uses Lecture 4, Task 2 uses Lecture 5, and Tasks 3 and 4 use Lecture 6. A regression table then puts the models of Tasks 2 to 4 side by side. Task 5 applies Lectures 3 to 5 to a table in the style of a published paper.</p>
<section id="before-class" class="level2 course-phase phase-before">
<h2 class="anchored" data-anchor-id="before-class">Before class</h2>
<p>Complete the after-class practice from Lectures 4 and 5. Lecture 6 is on the day before this tutorial: read its lecture material, and do its practice after the tutorial. Use the complete <a href="code-sheet.html">QM Intermediate Code Sheet</a> while working, and review <a href="../resources/math-refresher.html">Mathematics Refresher: multivariable equations, indicators, products, and powers</a> if needed.</p>
<p>Complete from memory:</p>
<ol type="1">
<li>A multiple-regression slope is interpreted while …</li>
<li>A dummy coefficient compares …</li>
<li>An interaction coefficient is a difference in …</li>
<li>A partial F-test compares …</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your preparation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Holding the other included predictors fixed.</li>
<li>A category with the named reference category.</li>
<li>Slopes.</li>
<li>A reduced nested model with a complete model on the same observations.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="in-the-tutorial" class="level2 course-phase phase-in-class">
<h2 class="anchored" data-anchor-id="in-the-tutorial">In the tutorial</h2>
<p>Try each task in R before you open the answer. Tasks 1 to 4 use the Shark Tank file, and money is measured in thousands of dollars (<code>ask_1k</code>). First build the data for the analysis. The code is the same as in Lectures 4–6:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sharks <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/shark_tank_teaching.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sharks<span class="sc">$</span>ask_1k <span class="ot">&lt;-</span> sharks<span class="sc">$</span>ask_amount_usd <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>known_gender <span class="ot">&lt;-</span> <span class="fu">subset</span>(sharks, pitcher_gender_group <span class="sc">!=</span> <span class="st">"unknown"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">relevel</span>(<span class="fu">factor</span>(known_gender<span class="sc">$</span>pitcher_gender_group),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                               <span class="at">ref =</span> <span class="st">"all_men"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>ask_1k <span class="ot">&lt;-</span> known_gender<span class="sc">$</span>ask_amount_usd <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>women <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  known_gender<span class="sc">$</span>pitcher_gender_group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"all_women"</span>, <span class="st">"mixed"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>known_gender<span class="sc">$</span>season_c <span class="ot">&lt;-</span> known_gender<span class="sc">$</span>season <span class="sc">-</span> <span class="fu">mean</span>(known_gender<span class="sc">$</span>season)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="task-1-multiple-regression-coefficients-lecture-4" class="level3">
<h3 class="anchored" data-anchor-id="task-1-multiple-regression-coefficients-lecture-4">Task 1: Multiple-regression coefficients (Lecture 4)</h3>
<p>Fit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_1k <span class="sc">+</span> description_words,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> sharks</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = equity_offered_pct ~ season + ask_1k + description_words, 
    data = sharks)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.295  -4.776  -1.283   3.288  82.106 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       22.0249310  0.8878522  24.807  &lt; 2e-16 ***
season            -0.8361515  0.0509825 -16.401  &lt; 2e-16 ***
ask_1k            -0.0028975  0.0005771  -5.021 5.79e-07 ***
description_words -0.1283379  0.1137527  -1.128    0.259    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.619 on 1437 degrees of freedom
Multiple R-squared:  0.1876,    Adjusted R-squared:  0.1859 
F-statistic: 110.6 on 3 and 1437 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol type="1">
<li>Interpret all three slopes with units and with the predictors that are held fixed.</li>
<li>Find out which 95% confidence interval of a coefficient includes zero.</li>
<li>Interpret adjusted <span class="math inline">\(R^2\)</span> and the overall F-test.</li>
<li>Give two reasons why the coefficients cannot be read as causal effects.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>At fixed values of the other included predictors, among the 1,441 recorded pitches: one later season is associated with about 0.836 percentage points less equity offered, an extra $1,000 requested with about 0.0029 percentage points less (about 0.29 points per $100,000), and one additional description word with about 0.128 percentage points less. <code>confint(m1)</code> shows that the interval for the description words, about <span class="math inline">\((-0.351, 0.095)\)</span>, includes zero. Adjusted <span class="math inline">\(R^2\approx0.186\)</span>: the model accounts for about 19% of the variation in the equity offered. The overall F-test (<span class="math inline">\(F\approx110.6\)</span> on 3 and 1437 df) rejects the null hypothesis that all three slopes are zero. Possible reasons against a causal reading: only selected pitches reach the show, the quality of the venture is not measured, the equity offered may influence the amount requested, and the variables may be measured with error.</p>
</div>
</div>
</div>
</section>
<section id="task-2-dummy-variables-and-a-partial-f-test-lecture-5" class="level3">
<h3 class="anchored" data-anchor-id="task-2-dummy-variables-and-a-partial-f-test-lecture-5">Task 2: Dummy variables and a partial F-test (Lecture 5)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_1k,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> known_gender)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>complete <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_1k <span class="sc">+</span> gender,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> known_gender)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(complete)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = equity_offered_pct ~ season + ask_1k + gender, data = known_gender)

Residuals:
    Min      1Q  Median      3Q     Max 
-16.118  -4.778  -1.100   3.220  82.590 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     20.8388333  0.5064929  41.143  &lt; 2e-16 ***
season          -0.8238940  0.0477959 -17.238  &lt; 2e-16 ***
ask_1k          -0.0026613  0.0005822  -4.571 5.28e-06 ***
genderall_women  1.2835231  0.4810241   2.668  0.00771 ** 
gendermixed      0.1209343  0.5411539   0.223  0.82320    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.612 on 1429 degrees of freedom
Multiple R-squared:  0.1913,    Adjusted R-squared:  0.189 
F-statistic: 84.49 on 4 and 1429 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(reduced, complete)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: equity_offered_pct ~ season + ask_1k
Model 2: equity_offered_pct ~ season + ask_1k + gender
  Res.Df   RSS Df Sum of Sq      F Pr(&gt;F)  
1   1431 83228                             
2   1429 82792  2    436.25 3.7649 0.0234 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ol type="1">
<li>Name the reference category.</li>
<li>Interpret both dummy coefficients.</li>
<li>State the hypotheses of the partial F-test and decide.</li>
<li>Explain why the partial F-test and the individual t-tests answer different questions.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The reference category is all-men. At the same season and requested amount, all-women presenting teams are fitted to offer about 1.28 equity percentage points more than all-men teams, and mixed teams about 0.12 points more. The unit is percentage points, not percent. The null hypothesis of the partial F-test is that both dummy coefficients are zero. <span class="math inline">\(F\approx3.76\)</span> and p <span class="math inline">\(\approx\)</span> 0.023, so reject at 5%. The two terms are jointly useful, even though the t-test of the mixed dummy alone (p <span class="math inline">\(\approx\)</span> 0.82) is far from significant. The F-test asks whether the two terms together improve the model. Each t-test asks about one comparison with the reference group. The categories are broad and the data do not come from an experiment, so the result does not show a causal effect of gender.</p>
</div>
</div>
</div>
</section>
<section id="task-3-interaction-lecture-6" class="level3">
<h3 class="anchored" data-anchor-id="task-3-interaction-lecture-6">Task 3: Interaction (Lecture 6)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>m_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season_c <span class="sc">*</span> women <span class="sc">+</span> ask_1k,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> known_gender</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_interaction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = equity_offered_pct ~ season_c * women + ask_1k, 
    data = known_gender)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.871  -4.742  -1.290   3.412  82.689 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    13.6247907  0.3354522  40.616  &lt; 2e-16 ***
season_c       -0.7993817  0.0663226 -12.053  &lt; 2e-16 ***
women           0.8069665  0.4117061   1.960   0.0502 .  
ask_1k         -0.0026776  0.0005834  -4.590 4.83e-06 ***
season_c:women -0.0614594  0.0955667  -0.643   0.5203    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.62 on 1429 degrees of freedom
Multiple R-squared:  0.1894,    Adjusted R-squared:  0.1871 
F-statistic: 83.47 on 4 and 1429 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol type="1">
<li>Write the fitted line for <code>women = 0</code> and for <code>women = 1</code> at a fixed requested amount.</li>
<li>Calculate both season slopes.</li>
<li>Interpret the interaction estimate and its p-value without claiming too much in either direction.</li>
<li>Explain what centering does.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>At a fixed requested amount, the fitted line for all-men teams is <span class="math inline">\(13.625-0.799\,season\_c\)</span> plus the term for the requested amount. For teams with women the intercept is <span class="math inline">\(13.625+0.807=14.432\)</span> and the slope is <span class="math inline">\(-0.7994-0.0615=-0.861\)</span>. So the season slope is about <span class="math inline">\(-0.799\)</span> percentage points per season for all-men teams and about <span class="math inline">\(-0.861\)</span> for teams with women. The estimated difference in slopes is <span class="math inline">\(-0.061\)</span> percentage points per season with p <span class="math inline">\(\approx\)</span> 0.520. The model gives no evidence that the season trends differ between the two groups. It also does not prove that the trends are equal, because the estimate is imprecise. Centering makes the <code>women</code> coefficient compare the groups at the average season (about 8.8) and not at Season 0, which does not exist. It changes neither the fitted values nor the interaction estimate.</p>
</div>
</div>
</div>
</section>
<section id="task-4-polynomial-term-lecture-6" class="level3">
<h3 class="anchored" data-anchor-id="task-4-polynomial-term-lecture-6">Task 4: Polynomial term (Lecture 6)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>m_linear <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_1k, <span class="at">data =</span> sharks)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>m_quadratic <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> <span class="fu">I</span>(season<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> ask_1k,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> sharks</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_quadratic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = equity_offered_pct ~ season + I(season^2) + ask_1k, 
    data = sharks)

Residuals:
    Min      1Q  Median      3Q     Max 
-16.154  -4.549  -1.011   3.390  82.000 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 24.171681   0.820566  29.457  &lt; 2e-16 ***
season      -1.713233   0.205669  -8.330  &lt; 2e-16 ***
I(season^2)  0.051034   0.011369   4.489 7.74e-06 ***
ask_1k      -0.002711   0.000574  -4.723 2.56e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.57 on 1437 degrees of freedom
Multiple R-squared:  0.1981,    Adjusted R-squared:  0.1965 
F-statistic: 118.3 on 3 and 1437 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m_linear, m_quadratic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: equity_offered_pct ~ season + ask_1k
Model 2: equity_offered_pct ~ season + I(season^2) + ask_1k
  Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1438 83493                                  
2   1437 82338  1    1154.5 20.149 7.737e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ol type="1">
<li>Why must <code>I(season^2)</code> be used in the R formula?</li>
<li>Decide with the partial F-test whether the quadratic term improves the model.</li>
<li>Calculate the fitted change from Season 10 to Season 11.</li>
<li>State why the curve should not be extrapolated beyond Season 16.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>I()</code> tells R to calculate the square. Without it, R would read <code>^</code> as formula syntax. The partial F-test gives <span class="math inline">\(F\approx20.1\)</span> with p <span class="math inline">\(&lt;\)</span> 0.001, so the quadratic term improves the model. With <span class="math inline">\(\hat\beta_1\approx-1.713\)</span> and <span class="math inline">\(\hat\beta_2\approx0.051\)</span>, the change from Season 10 to 11 is <span class="math inline">\(\hat\beta_1+\hat\beta_2(2\times10+1)=\hat\beta_1+21\hat\beta_2\approx-0.64\)</span> percentage points. Never read <span class="math inline">\(\hat\beta_1\)</span> alone while the squared term is in the model. Beyond Season 16 the fitted curve turns upward, and no data support that turn. A quadratic curve can change direction sharply outside the observed range.</p>
</div>
</div>
</div>
</section>
<section id="iep02-spec-table" class="level3">
<h3 class="anchored" data-anchor-id="iep02-spec-table">The models of Tasks 2 to 4 in one table</h3>
<p>Lecture 4 showed how research papers put several models side by side in one regression table. The table below does this for the models of Tasks 2 to 4. All columns of such a table must use the same observations. Tasks 2 and 3 use the 1,434 pitches with a known team classification (<code>known_gender</code>). Task 4 uses all 1,441 pitches. So first fit the quadratic model again on the 1,434 pitches. The code then prints the two outputs that are not shown above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>m_quadratic_known <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> <span class="fu">I</span>(season<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> ask_1k,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> known_gender</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reduced)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = equity_offered_pct ~ season + ask_1k, data = known_gender)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.169  -4.814  -1.136   3.277  82.219 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 21.1849717  0.4838230  43.787  &lt; 2e-16 ***
season      -0.8152726  0.0472948 -17.238  &lt; 2e-16 ***
ask_1k      -0.0028517  0.0005776  -4.937 8.87e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.626 on 1431 degrees of freedom
Multiple R-squared:  0.187, Adjusted R-squared:  0.1859 
F-statistic: 164.6 on 2 and 1431 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_quadratic_known)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = equity_offered_pct ~ season + I(season^2) + ask_1k, 
    data = known_gender)

Residuals:
    Min      1Q  Median      3Q     Max 
-16.160  -4.540  -1.010   3.401  82.003 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 24.1677366  0.8217246  29.411  &lt; 2e-16 ***
season      -1.7128060  0.2059832  -8.315  &lt; 2e-16 ***
I(season^2)  0.0509421  0.0113830   4.475 8.24e-06 ***
ask_1k      -0.0026921  0.0005749  -4.682 3.10e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.576 on 1430 degrees of freedom
Multiple R-squared:  0.1982,    Adjusted R-squared:  0.1966 
F-statistic: 117.9 on 3 and 1430 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Column (1) is the reduced model of Task 2 (<code>reduced</code>), column (2) the complete model of Task 2 (<code>complete</code>), column (3) the interaction model of Task 3 (<code>m_interaction</code>), and column (4) the quadratic model (<code>m_quadratic_known</code>).</p>
<div class="reg-table">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">(1)</th>
<th style="text-align: right;">(2)</th>
<th style="text-align: right;">(3)</th>
<th style="text-align: right;">(4)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Season</td>
<td style="text-align: right;">−0.815***</td>
<td style="text-align: right;">−0.824***</td>
<td style="text-align: right;">−0.799***</td>
<td style="text-align: right;">−1.713***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(0.047)</td>
<td style="text-align: right;">(0.048)</td>
<td style="text-align: right;">(0.066)</td>
<td style="text-align: right;">(0.206)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Season squared</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.051***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">(0.011)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amount requested ($1,000s)</td>
<td style="text-align: right;">−0.0029***</td>
<td style="text-align: right;">−0.0027***</td>
<td style="text-align: right;">−0.0027***</td>
<td style="text-align: right;">−0.0027***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(0.0006)</td>
<td style="text-align: right;">(0.0006)</td>
<td style="text-align: right;">(0.0006)</td>
<td style="text-align: right;">(0.0006)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">All-women team</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1.284**</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">(0.481)</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mixed team</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.121</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">(0.541)</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Team with women (all-women or mixed)</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.807</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">(0.412)</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Season × team with women</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">−0.061</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">(0.096)</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">21.185***</td>
<td style="text-align: right;">20.839***</td>
<td style="text-align: right;">13.625***</td>
<td style="text-align: right;">24.168***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(0.484)</td>
<td style="text-align: right;">(0.506)</td>
<td style="text-align: right;">(0.335)</td>
<td style="text-align: right;">(0.822)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Observations</td>
<td style="text-align: right;">1,434</td>
<td style="text-align: right;">1,434</td>
<td style="text-align: right;">1,434</td>
<td style="text-align: right;">1,434</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(R^2\)</span></td>
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">0.191</td>
<td style="text-align: right;">0.189</td>
<td style="text-align: right;">0.198</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adjusted <span class="math inline">\(R^2\)</span></td>
<td style="text-align: right;">0.186</td>
<td style="text-align: right;">0.189</td>
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">0.197</td>
</tr>
</tbody>
</table>
</div>
<p>Outcome: equity offered (%). Ordinary least squares. Standard errors in parentheses. All four columns use the same 1,434 pitches with a known team classification. The reference group is all-men teams. In column (3) season is centred at its mean (about 8.8), so the intercept and the coefficient of “Team with women” refer to the average season. * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001.</p>
<p>Read along the Season row. The coefficient is close to <span class="math inline">\(-0.8\)</span> in columns (1) to (3). In column (4) it is <span class="math inline">\(-1.713\)</span>, because with the squared term in the model the season coefficient alone is not the trend. Read down a column to see one model. Columns (2), (3), and (4) each add terms to column (1), so each can be compared with column (1) by a partial F-test. The bottom rows show that the four models fit almost equally well: adjusted <span class="math inline">\(R^2\)</span> lies between 0.186 and 0.197, a difference of about one percentage point of the variation in the equity offered. Use this layout for regression results in your thesis.</p>
</section>
<section id="task-5-read-a-regression-table-from-a-paper" class="level3">
<h3 class="anchored" data-anchor-id="task-5-read-a-regression-table-from-a-paper">Task 5: Read a regression table from a paper</h3>
<p>The table below is invented for this tutorial. It has the layout of a table in a management journal, the same layout as the table above. The outcome is entrepreneurial intention on a scale from 1 to 7, measured in a survey of 265 students. Self-efficacy is a score from 1 to 7 for how confident a student is that he or she can start a business. The intercept is left out, as some journals do.</p>
<div class="reg-table">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">(1)</th>
<th style="text-align: right;">(2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age (years)</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(0.02)</td>
<td style="text-align: right;">(0.02)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Female (1 = yes)</td>
<td style="text-align: right;">−0.21*</td>
<td style="text-align: right;">−0.15</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">(0.10)</td>
<td style="text-align: right;">(0.10)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prior entrepreneurial experience (1 = yes)</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.42**</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">(0.13)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Entrepreneurial self-efficacy (1–7)</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.38***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">(0.07)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Observations</td>
<td style="text-align: right;">265</td>
<td style="text-align: right;">265</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(R^2\)</span></td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adjusted <span class="math inline">\(R^2\)</span></td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.18</td>
</tr>
</tbody>
</table>
</div>
<p>Outcome: entrepreneurial intention (scale from 1 to 7). Ordinary least squares. Standard errors in parentheses. * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001.</p>
<ol type="1">
<li>What do the numbers in parentheses and the stars mean? Check the stars of the self-efficacy coefficient with its t statistic.</li>
<li>Interpret the self-efficacy coefficient in column (2) in one complete sentence.</li>
<li>The coefficient of Female changes from <span class="math inline">\(-0.21\)</span> with a star in column (1) to <span class="math inline">\(-0.15\)</span> without a star in column (2). Explain what happened with the ideas of Lecture 4, and say what the missing star does and does not mean.</li>
<li><span class="math inline">\(R^2\)</span> rises from 0.03 to 0.19. What does that say, and which test would judge whether the two added predictors are jointly useful?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>The numbers in parentheses are standard errors. The stars show the p-value of the two-sided t-test of each coefficient against zero. For self-efficacy, <span class="math inline">\(t=0.38/0.07\approx5.4\)</span>. This is far beyond the multiplier <span class="math inline">\(t_{0.975,\,260}\approx1.97\)</span>, and p is below 0.001, so three stars are correct.</li>
<li>Among the 265 surveyed students, a self-efficacy score that is one point higher is associated with an entrepreneurial intention that is 0.38 points higher, holding age, gender, and prior experience fixed.</li>
<li>Model (2) holds two more variables fixed than model (1). The Female coefficient now compares women and men with the same experience and self-efficacy. Part of the raw gap of 0.21 points went together with differences in those two variables. The missing star says that the confidence interval around <span class="math inline">\(-0.15\)</span> includes zero. It does not show that the gap is zero.</li>
<li>The two added predictors account for a further 16 percentage points of the variation in intentions in this sample. A partial F-test of the two nested models, <code>anova(reduced, complete)</code>, would judge whether they are jointly useful.</li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="after-class" class="level2 course-phase phase-after">
<h2 class="anchored" data-anchor-id="after-class">After class</h2>
<section id="timed-integrated-task-30-minutes" class="level3">
<h3 class="anchored" data-anchor-id="timed-integrated-task-30-minutes">Timed integrated task: 30 minutes</h3>
<p>Build one model of the equity offered (<code>equity_offered_pct</code>) in the Shark Tank file. Use season, the requested amount in $1,000s, the three known categories of presenting teams, and one extension that you can justify: an interaction or a quadratic term.</p>
<p>Your answer must include:</p>
<ol type="1">
<li>a precise research question</li>
<li>the code that prepares the data, so that someone else can repeat it</li>
<li>one graph of the data before you fit the model</li>
<li>the R formula and the model summary. If you compare several models, show them in one regression table in the layout of this tutorial</li>
<li>interpretations of the coefficients with units and reference groups</li>
<li>a t-test of one coefficient and an overall or partial F-test</li>
<li><span class="math inline">\(R^2\)</span>, adjusted <span class="math inline">\(R^2\)</span>, and residual diagnostics</li>
<li>one graph of fitted values from the model</li>
<li>a conclusion of 150 words that keeps apart the association, its uncertainty, and the reasons why it is not causal.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check a model structure
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A good solution could fit</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season <span class="sc">*</span> gender <span class="sc">+</span> ask_1k,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> known_gender</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>or a model with a quadratic term for season and the group dummies. Keep <code>season</code> and <code>gender</code> in the model next to their interaction (the hierarchy principle), and name the reference group. Interpret slopes that combine several coefficients, or differences between fitted values. Compare the model with a nested reduced model with <code>anova(reduced, complete)</code>. Inspect the residuals, including <code>rstandard()</code> and Cook’s distance, and plot fitted values inside Seasons 1–16. The conclusion must say that the team categories are broad, that only broadcast pitches are in the file, and that the results therefore do not show a causal effect of gender or season.</p>
</div>
</div>
</div>
</section>
<section id="make-it-yours-5-minutes" class="level3">
<h3 class="anchored" data-anchor-id="make-it-yours-5-minutes">Make it yours (5 minutes)</h3>
<div class="utility-prompt">
<p><span class="label">Utility: two sentences</span></p>
<p>Think of your EiA3 venture, or any business you know well. Describe in two sentences the full analysis that you would run on its data. First, name the outcome, two predictors, and one extension (a set of dummies, an interaction, or a quadratic term) that a real question motivates. Second, say which limit you would put first in your conclusion: selection, measurement, or omitted variables. There is no wrong answer.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
See an example, then write your own
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take a student-run venture that sells meal-prep boxes on campus (an invented example). “Outcome: weekly orders. Predictors: advertising spend and price, plus a dummy for exam weeks and its interaction with advertising spend, because I believe ads work mainly when students are on campus. The first limit is omitted variables: the weather drives both how many flyers I hand out and how many people are on campus, and nothing in my data measures it.”</p>
</div>
</div>
</div>
<p>You can discuss this task, and any other task in this tutorial, with <strong>Tilly</strong>, the course AI assistant. Ask it to review your two sentences before you spend a weekend on the data.</p>
</div>
<p>QM Intermediate is complete. Review the <a href="code-sheet.html">QM Intermediate Code Sheet</a>, attempt the <a href="mock-exam.html">QM Intermediate Mock Exam</a>, then return to the <a href="../resources/r-refresher.html">R Refresher</a>, <a href="../resources/math-refresher.html">Mathematics Refresher</a>, or the <a href="../resources/video-guide.html">External Video Guide</a> whenever you need a targeted review.</p>
</section>
</section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/valentinamel\.github\.io\/textbook-qm-ebi\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../intermediate/i06-interactions-curvature.html" class="pagination-link" aria-label="Lecture 6: Interactions and curvature">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Lecture 6: Interactions and curvature</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../intermediate/code-sheet.html" class="pagination-link" aria-label="QM Intermediate Code Sheet">
        <span class="nav-page-text"><span class="chapter-title">QM Intermediate Code Sheet</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>