{
  "hash": "b0b32257df7fc484d5864ef20df6e959",
  "result": {
    "engine": "knitr",
    "markdown": "# Lecture 6: Continuous distributions and the normal model {#b06}\n\n\n\n\n\n\n\n\n\n::: {.outcomes}\n<span class=\"label\">By the end of Lecture 6, you can</span>\n\n- distinguish a continuous random variable from a discrete one;\n- explain why $P(X=x)=0$ for a continuous random variable and interpret a\n  probability density function as area rather than point probability;\n- use a CDF to calculate interval probabilities;\n- calculate uniform probabilities from interval lengths;\n- standardise a normal value and compute normal probabilities by hand from\n  supplied $Z$ values and with `pnorm()`;\n- convert a percentile back to a raw value with $x=\\mu+z\\sigma$ and verify\n  with `qnorm()`;\n- find quantiles of model distributions (the uniform median, normal\n  quartiles);\n- check a proposed normal model against a histogram of data and say when it\n  fails.\n:::\n\n::: {.driving-question}\n<span class=\"label\">Driving question</span>\n\n<p class=\"dq-context\">Not everything comes in whole numbers: negotiation time, invested amounts, and revenues can land anywhere in a range. Insurers, lenders, and operations planners price risk on exactly such quantities every day --- and that needs a new kind of probability model.</p>\n\nNegotiation time and invested amounts can take any value in a range. How do\nwe assign probabilities when no single value has any?\n:::\n\n::: {.course-phase .phase-before}\n\n## Before class\n\n<span class=\"time-budget\">Total preparation time: about 30 minutes.</span>\n\n<div class=\"video-prep\">\n<span class=\"label\">Video preparation (20 minutes)</span><br>\nWatch <a href=\"https://www.youtube.com/watch?v=8QFpZ3FndBc\">Probability\nDensity Functions</a>,\n<a href=\"https://www.youtube.com/watch?v=JoQDJMZA7F8\">Uniform Random\nVariables</a>, and\n<a href=\"https://www.youtube.com/watch?v=6UMv4vb4y7c\">Normal Random\nVariables</a>. Focus on the difference between density height and\nprobability, and on the roles of the two normal parameters. All links are\nalso listed in the\n<a href=\"../resources/video-guide.html\">External Video Guide</a>.\n</div>\n\n**Reactivate (5 minutes).** A discrete random variable has separated\npossible values (Lecture 3 attached a PMF and a CDF to such variables). A\ncontinuous random variable can take every real value in an interval. Match\neach variable to the better description:\n\n1. number of sharks in an on-air deal;\n2. exact time spent negotiating a pitch;\n3. season number;\n4. exact amount invested, before rounding to dollars.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\nVariables 1 and 3 are discrete. Variables 2 and 4 are continuous in a\nmathematical model, even if a measuring device or database records rounded\nvalues.\n:::\n\n**Predict (5 minutes).** Answer the one-click Mentimeter question posted on\nCanvas before you come to class: for a *continuous* random variable $X$, is\n$P(X = \\text{exactly } 10)$ **very small** or **exactly zero**? Commit to an\nanswer; the lecture resolves it.\n\nIf powers, square roots, inequalities, or z-score algebra feel unfamiliar,\nreview\n[Mathematics Refresher: powers, functions, and intervals](../resources/math-refresher.html).\n\n:::\n\n::: {.course-phase .phase-in-class}\n\n## In class\n\nThe session opens with the usual four-minute entry quiz on the prep videos,\nthen turns to the driving question.\n\nStart with the prediction from your prep. For a continuous random variable,\n\n$$P(X=x)=0 \\quad\\text{for every single value } x.$$\n\nNot very small --- exactly zero. An interval contains infinitely many values;\nif each single value carried even the tiniest positive probability, the total\nwould exceed 1. Yet the negotiation certainly takes *some* amount of time, so\nprobability has not disappeared. It has moved: probability now belongs to\n**intervals**, not points. That forces a new object to replace the PMF, and\nbuilding that object is the first job of this lecture.\n\n### From probability mass to probability density\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/probability-density-functions/\">08.2 Probability Density Functions</a>.</p>\n\nFor a discrete random variable, the PMF assigns probability to individual\nvalues. For a continuous random variable $X$, a **probability density\nfunction** (PDF), written $f_X(x)$, is a non-negative curve whose total area\nis 1. The probability that $X$ lies between $a$ and $b$ is the **area** under\nthe curve between those values.\n\nYou do not need calculus in this course. You need to interpret probability\nas area and use a CDF, R, or supplied values to calculate it.\n\nThe crucial reading rule: **density is height, probability is area.**\nDensity is probability *per unit* of $x$ --- roughly, the probability of a\ntiny interval divided by its width. Because a width can be small, the height\ncan be large. A density can exceed 1 as long as the total area under the\ncurve is 1.\n\n::: {.callout-note collapse=\"true\"}\n## Check: is a rectangle of width 0.5 and height 2 a valid density?\n\nYes. The curve is non-negative and its total area is\n$0.5 \\times 2 = 1$, so it is a legitimate PDF (a uniform density on an\ninterval of length 0.5). The height 2 is not a probability --- no\nprobability statement here exceeds 1, because every probability is an area\ninside that rectangle. Height 2 simply means the probability is packed into\na narrow range.\n:::\n\n#### The CDF works for every random variable\n\nThe cumulative distribution function is still\n\n$$F_X(x)=P(X\\le x),$$\n\nexactly as in Lecture 3. For a continuous random variable,\n\n$$P(a<X\\le b)=F_X(b)-F_X(a).$$\n\nBecause a single point has zero probability, changing $<$ to $\\le$ does not\nchange a continuous probability: $P(a<X<b)$, $P(a\\le X\\le b)$, and the two\nmixed versions are all equal. This differs from a discrete variable, where a\npoint may carry positive probability and the inequality type matters.\n\n### The uniform distribution\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/uniform-random-variables/\">05.5 Uniform Random Variables</a>.</p>\n\nIf every equal-length subinterval of $[a,b]$ is equally likely, then\n$X\\sim U(a,b)$. Its density is constant:\n\n$$f_X(x)=\\frac{1}{b-a},\\qquad a\\le x\\le b,$$\n\nand zero outside the **support** $[a,b]$. The height is not a choice --- it\nis *forced* by the requirement that the whole rectangle have area 1:\n\n$$\\text{width}\\times\\text{height}=(b-a)\\times\\frac{1}{b-a}=1.$$\n\nBecause the height is constant, interval probability depends only on\ninterval length. For $a\\le c<d\\le b$,\n\n$$P(c<X<d)=\\frac{d-c}{b-a}.$$\n\nThe mean and variance are stated here without derivation:\n\n$$E[X]=\\frac{a+b}{2},\\qquad \\operatorname{Var}(X)=\\frac{(b-a)^2}{12}.$$\n\n::: {#exm-b06-uniform-session}\n## Worked example: when does the pitch appear?\n\nA recording session lasts 90 minutes, and an anonymised pitch is equally\nlikely to start at any moment of it. Model the start time as\n$X\\sim U(0,90)$, measured in minutes.\n\n*Step 1: the height.* The density is $1/(90-0)=1/90\\approx 0.011$ per\nminute --- forced by total area 1, not chosen.\n\n*Step 2: the event.* \"The pitch starts during the 18-minute window from\nminute 30 to minute 48\" is the event $30<X<48$.\n\n*Step 3: the area.* The probability is the area of the shaded rectangle in\n@fig-b06-uniform-session:\n\n$$P(30<X<48)=\\frac{48-30}{90-0}=\\frac{18}{90}=0.20.$$\n\nFor a uniform model, only the *length* of the window matters --- any\n18-minute window inside the session has probability 0.20.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\n\na <- 0\nb <- 90\nc_cut <- 30\nd_cut <- 48\ndensity_height <- 1 / (b - a)\n\nsupport_rect <- data.frame(x = c(a, b), y = density_height)\nwindow_rect  <- data.frame(x = c(c_cut, d_cut), y = density_height)\ndensity_line <- data.frame(x = c(-9, a, a, b, b, 99),\n                           y = c(0, 0, density_height, density_height, 0, 0))\n\nggplot() +\n  geom_area(data = support_rect, aes(x, y), fill = \"grey75\", alpha = 0.25) +\n  geom_area(data = window_rect, aes(x, y), fill = \"#009E73\", alpha = 0.25) +\n  geom_line(data = density_line, aes(x, y), colour = \"#17324D\",\n            linewidth = 1.2) +\n  annotate(\"text\", x = 66, y = 0.0127,\n           label = \"density = 1/(b - a) = 1/90\",\n           colour = \"#17324D\", size = 3.4) +\n  annotate(\"segment\", x = 39, xend = 39, y = 0.0042, yend = 0.0010,\n           colour = \"#17324D\",\n           arrow = arrow(length = unit(0.08, \"inches\"))) +\n  annotate(\"text\", x = 39, y = 0.0052,\n           label = \"area = P(30 < X < 48) = 0.20\",\n           colour = \"#17324D\", size = 3.4) +\n  scale_x_continuous(breaks = c(a, c_cut, d_cut, b),\n                     labels = c(\"a = 0\", \"c = 30\", \"d = 48\", \"b = 90\"),\n                     expand = c(0, 0)) +\n  scale_y_continuous(breaks = c(0, density_height),\n                     labels = c(\"0\", \"1/90\"),\n                     limits = c(0, 0.0145),\n                     expand = c(0, 0)) +\n  labs(x = \"Minutes into the session\", y = \"Density\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![The uniform density for a pitch start time over a 90-minute session. The navy line is the density; the shaded green area is the probability of the 18-minute window, 18/90 = 0.20.](b06-continuous-normal_files/figure-html/fig-b06-uniform-session-1.png){#fig-b06-uniform-session width=672}\n:::\n:::\n\n\n\n\nRead the horizontal axis as possible start times and the vertical axis as\ndensity, not probability. The navy density line is at 0 before minute 0,\njumps to $1/90$ on the support, and drops back to 0 after minute 90. The\ngreen probability is an **area**: $18\\times(1/90)=0.20$. Note the contrast\nwith the check above --- here the height is far below 1, there it was 2;\nboth are legitimate, because only the area is a probability.\n\n::: {.callout-caution collapse=\"true\"}\n## Try it: the final stretch of the session\n\nIn class this is the pair task. Same model, $X\\sim U(0,90)$. What is the\nprobability that the pitch starts in the final 27 minutes of the session?\n\n*Step 1 (given).* The event is $63<X<90$, an interval of length\n$90-63=27$ minutes inside the support.\n\n*Step 2 (you).* Divide the interval length by the support length.\n\n*Step 3 (you).* Interpret the result in one sentence.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$P(63<X<90)=27/90=0.30$: under the uniform model there is a 30% chance the\npitch starts in the final 27 minutes --- larger than the 0.20 above only\nbecause the window is longer.\n:::\n:::\n\n### The normal distribution\n\n<p class=\"concept-video\"><strong>MIT explanation (review):</strong>\n<a href=\"https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/normal-random-variables/\">08.8 Normal Random Variables</a>.</p>\n\nA normal random variable is written\n\n$$X\\sim N(\\mu,\\sigma^2).$$\n\nRead the notation carefully: the second parameter is the **variance**\n$\\sigma^2$, not the standard deviation. The density is symmetric and\nbell-shaped. The parameter $\\mu$ locates its centre; $\\sigma>0$ controls its\nspread:\n\n$$E[X]=\\mu,\\qquad \\operatorname{Var}(X)=\\sigma^2.$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\n\nnormal_curve <- data.frame(z = seq(-3.6, 3.6, length.out = 800))\nnormal_curve$density <- dnorm(normal_curve$z)\n\nggplot(normal_curve, aes(z, density)) +\n  geom_area(data = subset(normal_curve, z >= -1 & z <= 1),\n            fill = \"#009E73\", alpha = 0.25) +\n  geom_vline(xintercept = c(-1, 1), linetype = \"dashed\",\n             colour = \"#5B6976\", linewidth = 0.5) +\n  geom_vline(xintercept = 0, linetype = \"dashed\",\n             colour = \"#C98B2E\", linewidth = 0.7) +\n  geom_line(colour = \"#17324D\", linewidth = 1.2) +\n  annotate(\"text\", x = 0, y = 0.16, label = \"about 68%\",\n           colour = \"#17324D\", size = 3.4) +\n  annotate(\"text\", x = 0.15, y = 0.425, label = \"mean~mu\", parse = TRUE,\n           colour = \"#17324D\", size = 3.4, hjust = 0) +\n  scale_x_continuous(breaks = c(-2, -1, 0, 1, 2),\n                     labels = expression(mu - 2 * sigma, mu - sigma, mu,\n                                         mu + sigma, mu + 2 * sigma)) +\n  scale_y_continuous(limits = c(0, 0.43),\n                     expand = expansion(mult = c(0, 0.02))) +\n  labs(x = \"Value of X\", y = \"Density\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![The normal density. The shaded central area between the two grey dashed lines runs from one standard deviation below the mean to one above and contains about 68% of the distribution; the gold dashed line marks the mean μ.](b06-continuous-normal_files/figure-html/fig-b06-normal-shape-1.png){#fig-b06-normal-shape width=672}\n:::\n:::\n\n\n\n\nThe horizontal axis locates possible values relative to $\\mu$ and $\\sigma$;\nthe vertical axis is density, and probability is again area. In the normal\n**model**, about 68% of the distribution lies within one standard deviation\nof the mean and about 95% within 1.96 standard deviations. These are facts\nabout the mathematical model --- the caveat box below explains why they are\nnot automatic facts about every dataset.\n\n#### Standardising: every normal question becomes a Z question\n\nIf $X\\sim N(\\mu,\\sigma^2)$, then\n\n$$Z=\\frac{X-\\mu}{\\sigma}\\sim N(0,1).$$\n\nA z-score reports how many standard deviations a value lies above or below\nthe mean. Standardising matters because the closed-book exam supplies a\nhandful of standard-normal probabilities on the page --- your job is to\ntranslate the business question into a $Z$ question that those supplied\nvalues can answer. The hand calculation is the primary route; R only\nverifies it.\n\n::: {#exm-b06-supplied-z}\n## Worked example: normal probabilities from supplied Z values\n\nProcessing time $Y$ (in minutes) is modelled as $Y\\sim N(50,100)$. The\nvariance is 100, so $\\sigma=\\sqrt{100}=10$. The following standard-normal\nprobabilities are supplied, exactly as on the exam paper:\n\n```\nP(Z <=  1.5) = 0.9332\nP(Z <=  1.0) = 0.8413\nP(Z <= -1.0) = 0.1587\n```\n\n**(a) $P(Y\\le 65)$.** Standardise the boundary:\n\n$$z=\\frac{65-50}{10}=1.5,$$\n\nso\n\n$$P(Y\\le 65)=P(Z\\le 1.5)=0.9332.$$\n\n**(b) $P(40<Y<60)$.** Standardise both boundaries:\n\n$$z_{\\text{low}}=\\frac{40-50}{10}=-1.0,\\qquad\nz_{\\text{high}}=\\frac{60-50}{10}=1.0,$$\n\nthen take the difference of the two cumulative probabilities, exactly as\nwith any CDF:\n\n$$P(40<Y<60)=P(Z\\le 1.0)-P(Z\\le -1.0)=0.8413-0.1587=0.6826.$$\n\nThat is the 68% rule seen in @fig-b06-normal-shape: the interval runs from\none standard deviation below the mean to one above.\n:::\n\nIn class the same two numbers are then produced live in R. `pnorm()` is the\nnormal CDF; give it the boundary, the mean, and the **standard deviation**\n(not the variance):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(65, mean = 50, sd = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9331928\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(60, mean = 50, sd = 10) - pnorm(40, mean = 50, sd = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6826895\n```\n\n\n:::\n:::\n\n\n\n\nThe hand path and `pnorm()` agree. On the exam you will have the supplied\nvalues, not R, so practise the hand path first and use R to check.\n\n#### The reverse direction: from percentile to raw value\n\n`pnorm()` turns a value into a cumulative probability. The reverse question\n--- which *value* has a given proportion below it --- is answered by\ninverting the standardisation:\n\n$$x=\\mu+z\\sigma,$$\n\nwhere $z$ is the standard-normal quantile for the chosen proportion.\n\n::: {#exm-b06-reverse}\n## Worked example: the 90th percentile of processing time\n\nFor $Y\\sim N(50,100)$, which processing time is exceeded by only 10% of\ncases? The supplied standard-normal quantile is $z_{0.90}=1.2816$.\n\n*Step 1.* The 90th percentile of $Z$ is 1.2816: it lies 1.2816 standard\ndeviations above the mean.\n\n*Step 2.* Translate back to the scale of $Y$:\n\n$$x=\\mu+z\\sigma=50+1.2816\\times 10=62.8 \\text{ minutes.}$$\n\n*Step 3.* Verify with `qnorm()`, the inverse of `pnorm()`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.90, mean = 50, sd = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62.81552\n```\n\n\n:::\n:::\n\n\n\n\nAbout 62.8 minutes --- 90% of processing times fall at or below it, 10%\nabove.\n:::\n\nThe same function confirms the 1.96 in the 95% rule: the central 95% of the\nstandard normal runs between\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.959964  1.959964\n```\n\n\n:::\n:::\n\n\n\n\nLectures 8 and 9 use exactly these two numbers to build confidence\nintervals.\n\n### Checking the normal model against data\n\nThe normal distribution is a model, not a label that every quantitative\nvariable automatically deserves. Skewness, bounds, extreme outliers, or a\nfew heavily repeated values can make it a poor description. The check is\nvisual: draw the histogram of the data, overlay the normal curve with the\nsame mean and standard deviation, and see whether the curve reproduces the\nbars.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nc(mean_equity = mean(sharks$equity_offered_pct),\n  sd_equity   = sd(sharks$equity_offered_pct))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean_equity   sd_equity \n  13.207613    8.444355 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\n\nsharks <- read.csv(\"data/shark_tank_teaching.csv\", stringsAsFactors = FALSE)\nmean_equity <- mean(sharks$equity_offered_pct)\nsd_equity <- sd(sharks$equity_offered_pct)\n\nggplot(sharks, aes(equity_offered_pct)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 breaks = seq(0, 100, by = 5),\n                 fill = \"#009E73\", alpha = 0.85, colour = \"white\") +\n  stat_function(fun = dnorm,\n                args = list(mean = mean_equity, sd = sd_equity),\n                colour = \"#D55E00\", linewidth = 0.9) +\n  annotate(\"text\", x = 42, y = 0.062, label = \"observed pitches\",\n           colour = \"#17324D\", size = 3.4, hjust = 0) +\n  annotate(\"text\", x = 42, y = 0.054,\n           label = \"normal curve with the same mean and SD\",\n           colour = \"#D55E00\", size = 3.4, hjust = 0) +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +\n  labs(x = \"Equity initially offered (%)\", y = \"Density\") +\n  theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n```\n\n::: {.cell-output-display}\n![Initial equity offered across all 1,441 recorded pitches (green bars), with the normal density that has the same mean and standard deviation (orange curve). The curve misses the skew, the bounds, and the spikes at round percentages.](b06-continuous-normal_files/figure-html/fig-b06-equity-normal-check-1.png){#fig-b06-equity-normal-check width=672}\n:::\n:::\n\n\n\n\nRead @fig-b06-equity-normal-check with the five-step sequence from\nLecture 1. *Axes:* initial equity in percentage points against density, so\nbar **areas**, not heights alone, represent proportions of pitches.\n*Elements:* green bars are the 1,441 observed offers; the orange curve is\n$N(13.2,\\,8.4^2)$, the normal model with the matching mean and SD.\n*Pattern:* the bars pile up between 5% and 20% and stretch out a long right\ntail. *Deviations:* the data are bounded between 0% and 100%, strongly\nright-skewed, and spiked at round values such as 10% and 20%; the symmetric\ncurve puts visible probability below 0% and misses the spikes entirely.\n*Meaning:* the normal model **fails** for individual equity offers. A model\nis a choice, and this check rejects the choice.\n\nThat failure is not the end of the normal distribution's usefulness ---\nalmost the opposite. From Lecture 8 onwards the normal model returns to\ndescribe **sampling distributions** of averages, and it will fit those well\n*even though* the underlying variable is as skewed as this one. That result\nis the central limit theorem, and it is the reason the normal model earns\nits central place in statistics.\n\n### Quantiles of a model distribution\n\nA **quantile** of a distribution is the boundary value below which a chosen\nproportion of the probability lies. You already computed quantiles of\n*data* in Lectures 1 and 2 (quartiles, the median, the IQR of the equity\noffers). The same idea applies to a *model* distribution, and the reverse\ncalculation above is exactly this: a quantile question.\n\n- **Uniform:** by symmetry, the median of $U(a,b)$ is the midpoint\n  $(a+b)/2$. For the session-timing model $U(0,90)$, the median start time\n  is 45 minutes --- half the probability lies on each side.\n- **Normal:** quartiles sit $0.6745$ standard deviations either side of the\n  mean, $\\mu\\pm 0.6745\\sigma$. For $Y\\sim N(50,100)$:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(c(0.25, 0.75), mean = 50, sd = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 43.2551 56.7449\n```\n\n\n:::\n:::\n\n\n\n\nSo the middle half of the model distribution runs from about 43.3 to 56.7\nminutes. Nothing more is needed here: quantiles of data were covered\nearlier in the course, and quantiles of models are one `qnorm()` or one\nmidpoint away.\n\n::: {.caveat-box}\n<span class=\"label\">What a normal label can and cannot say</span>\n\n\"$X$ is normally distributed\" is a **model claim**, not a fact about every\nvariable --- it must be checked, the way @fig-b06-equity-normal-check\nchecked it and found it false for equity offers. The 68% and 95% rules are\nexact statements about the mathematical normal model; quoting them for a\nvariable that is skewed, bounded, or spiked (most business variables are at\nleast one of these) produces confident-sounding numbers that are simply\nwrong. Model probabilities such as $P(Y\\le 65)=0.9332$ are conclusions\n*inside* the model $N(50,100)$; they say nothing about reality unless the\nmodel describes the data. And a fitted curve that matches the mean and SD\nof the data can still miss the shape entirely --- matching two summaries is\nnot a fit. The legitimate uses ahead: the normal as a checked model for\nsome variables, and --- from Lecture 8 --- as the reliable model for\nsampling distributions of averages, where mathematics rather than wishful\nthinking puts it there.\n:::\n\n### Answering the driving question\n\nNo single negotiation time or invested amount has positive probability ---\n$P(X=x)=0$ --- so probabilities are assigned to **intervals** as areas\nunder a density. For the uniform session model, the 18-minute window gets\n$18/90=0.20$ because only length matters. For the normal processing-time\nmodel $N(50,100)$, supplied $Z$ values give $P(Y\\le 65)=0.9332$ and\n$P(40<Y<60)=0.6826$ by hand, and `pnorm()` confirms both. The catch: a\ndensity is a modelling choice, and the equity histogram shows the normal\nchoice failing for real offers --- so check the model before trusting its\nareas.\n\n**Next:** We can now model quantities that live on a continuum and read\nprobabilities as areas. Everything so far, though, treats the 1,441 records as\nthe whole world --- and real analysis rarely has the whole world. Firms see\nsamples: 100 audited transactions, 500 surveyed customers. Lecture 7 makes the\nmove from one pitch to a *sample* of pitches: populations, frames, and random\nsampling, plus the discipline of parameters, estimators, and estimates on\nwhich all of inference stands.\n\n:::\n\n::: {.course-phase .phase-after}\n\n## After class\n\n<span class=\"time-budget\">Total practice time: about 55 minutes.</span>\n\n### Retrieval (10 minutes)\n\n1. Why is $P(X=x)=0$ for a continuous random variable?\n2. What quantity under a PDF represents probability?\n3. How do you obtain $P(a<X\\le b)$ from a CDF?\n4. What do $\\mu$ and $\\sigma$ control in a normal model?\n5. A density curve reaches a height of 2. Why is that not a contradiction?\n6. What does a z-score of $-1.5$ mean?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. Probability belongs to intervals; an individual point has zero width and\n   therefore zero area.\n2. Area under the density curve between the interval boundaries.\n3. $F_X(b)-F_X(a)$.\n4. $\\mu$ controls the centre and $\\sigma$ the spread.\n5. Density is probability per unit, not probability. A height above 1 is\n   fine as long as the total area under the curve is 1.\n6. The value lies 1.5 standard deviations below the mean.\n:::\n\n### From worked to faded (5 minutes)\n\nRe-read the session-timing calculation (@exm-b06-uniform-session). Then\ncomplete the same calculation for a new model: a waiting time\n$X\\sim U(10,30)$ minutes.\n\n*Step 1 (given).* The density height is $1/(30-10)=0.05$ on the support\n$[10,30]$ and zero outside it.\n\n*Step 2 (you).* Find $P(14<X<20)$.\n\n*Step 3 (you).* State $E[X]$ and interpret both numbers in one sentence.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$P(14<X<20)=(20-14)/(30-10)=6/20=0.30$ and $E[X]=(10+30)/2=20$: the wait\naverages 20 minutes, and under the uniform model there is a 30% chance it\nlands between 14 and 20 minutes.\n:::\n\n### Practice (15 minutes)\n\nFor items 3 and 4, use only these supplied values, then verify in R:\n\n```\nP(Z <=  1.5) = 0.9332\nP(Z <=  1.0) = 0.8413\nP(Z <= -1.0) = 0.1587\nz(0.90)      = 1.2816\n```\n\n1. For $X\\sim U(10,30)$: find $\\operatorname{SD}(X)$ and $P(X>25)$.\n2. A supplier delivers at a moment uniformly distributed between 09:00 and\n   13:00. Your goods lift is reserved for other tenants except during\n   12:00--13:00. What is the probability the delivery arrives while the\n   lift is available, and what is the density height per minute?\n3. Monthly demand for a product is modelled as $Y\\sim N(200,400)$.\n   Calculate $P(Y\\le 230)$ and $P(180<Y<220)$ by hand.\n4. Weekly revenue is modelled as $N(100,15^2)$ (in hundreds of euros).\n   Which revenue level is exceeded in only 10% of weeks? Compute by hand\n   with $x=\\mu+z\\sigma$, then verify with `qnorm()`.\n5. Explain in two sentences why the normal curve in\n   @fig-b06-equity-normal-check is not a convincing model for offered\n   equity.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answers\n\n1. $\\operatorname{SD}(X)=\\sqrt{(30-10)^2/12}=20/\\sqrt{12}\\approx 5.77$\n   minutes, and $P(X>25)=(30-25)/20=0.25$.\n2. The window is 60 of the 240 possible minutes, so $60/240=0.25$. The\n   density height is $1/240\\approx 0.0042$ per minute --- and the\n   probability is the area $60\\times(1/240)=0.25$, not the height.\n3. $\\sigma=\\sqrt{400}=20$. For 230: $z=(230-200)/20=1.5$, so\n   $P(Y\\le 230)=0.9332$. For the interval:\n   $z_{\\text{low}}=(180-200)/20=-1.0$ and\n   $z_{\\text{high}}=(220-200)/20=1.0$, so\n   $P(180<Y<220)=0.8413-0.1587=0.6826$.\n4. $x=100+1.2816\\times 15=119.2$, so about 119 hundred euros; only 10% of\n   weeks exceed it.\n5. The observed distribution is bounded between 0% and 100%, strongly\n   right-skewed, and concentrated at a few round percentages; the symmetric\n   normal curve reproduces none of those features.\n\nVerification in R for items 3 and 4:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(230, mean = 200, sd = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9331928\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(220, mean = 200, sd = 20) - pnorm(180, mean = 200, sd = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6826895\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.90, mean = 100, sd = 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 119.2233\n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Spaced review: one item from Lecture 3 (5 minutes)\n\nThe number of sharks who join an on-air deal, $X$, has PMF $p(1)=0.6$,\n$p(2)=0.3$, $p(3)=0.1$. Find $F(2)=P(X\\le 2)$ and $P(X<2)$. Why do the two\nanswers differ here, when for a continuous variable they would not?\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\n$F(2)=0.6+0.3=0.9$, while $P(X<2)=P(X=1)=0.6$. They differ because the\nsingle point $X=2$ carries positive probability, $p(2)=0.3$. For a\ncontinuous variable every single point has probability zero, so $<$ and\n$\\le$ give the same answer.\n:::\n\n### Changing units (5 minutes)\n\nThe session-timing variable $X\\sim U(0,90)$ is recorded in minutes and then\nconverted to seconds. Explain what changes about the PDF and what remains\nunchanged.\n\n::: {.callout-note collapse=\"true\"}\n## Check your answer\n\nThe support stretches from $[0,90]$ minutes to $[0,5400]$ seconds, and the\ndensity height drops from $1/90$ per minute to $1/5400$ per second --- the\nnumerical size of a density depends on the units. Probabilities of\ncorresponding time intervals are unchanged, because they are areas: the\n18-minute window becomes a 1,080-second window, and\n$1080/5400=18/90=0.20$.\n:::\n\n### Exam-style item (10 minutes)\n\nThis item follows the pattern of Mock Exam Question 3. Let\n$X\\sim U(20,60)$ be a waiting time in minutes and, separately,\n$Y\\sim N(80,25)$ a processing time in minutes. Supplied:\n\n```\nP(Z <=  1.5) = 0.9332\nP(Z <=  1.0) = 0.8413\nP(Z <= -1.0) = 0.1587\n```\n\n1. State the PDF height of $X$, including its value outside the support.\n2. Calculate $P(30<X<40)$, $E[X]$, and $\\operatorname{Var}(X)$.\n3. Standardise 87.5 minutes under the model for $Y$, then calculate\n   $P(Y\\le 87.5)$.\n4. Calculate $P(75<Y<85)$.\n5. Explain why a PDF height is not itself a probability.\n\n::: {.callout-note collapse=\"true\"}\n## Check a model answer\n\n1. $f_X(x)=1/(60-20)=0.025$ for $20\\le x\\le 60$, and $f_X(x)=0$ outside\n   that interval.\n2. $P(30<X<40)=(40-30)/40=0.25$, $E[X]=(20+60)/2=40$, and\n   $\\operatorname{Var}(X)=(60-20)^2/12\\approx 133.33$ square minutes.\n3. The variance is 25, so $\\sigma=5$ and $z=(87.5-80)/5=1.5$; hence\n   $P(Y\\le 87.5)=0.9332$.\n4. $P(75<Y<85)=P(-1<Z<1)=0.8413-0.1587=0.6826$.\n5. Probability is area over an interval --- approximately density times a\n   small interval width. A single point has zero width and hence zero\n   probability; a density value only becomes a probability once multiplied\n   by a width.\n:::\n\n### Make it yours (5 minutes)\n\n:::: {.utility-prompt}\n<span class=\"label\">Utility: two sentences</span>\n\nThink of your EiA venture --- or any business you know well. Pick one\ncontinuous quantity that matters for it (a delivery time, weekly revenue,\ntime on site) and write two sentences: first name the interval of values\nthat would trigger a real decision, then say whether a uniform or a normal\nmodel seems defensible for that quantity --- and which feature of its\nhistogram you would check first. There is no wrong answer; the point is\nconnecting today's tools to something you care about.\n\n::: {.callout-note collapse=\"true\"}\n## See an example, then write your own\n\nTake a student-run campus meal-prep box venture. \"Delivery time is my quantity: anything over 40 minutes triggers a refund, so $P(T > 40)$ is the number that matters. A normal model is doubtful because times cannot be negative and a few deliveries go very wrong --- right skew is the first thing I would check on the histogram.\"\n:::\n\nYou can discuss this task --- and any other task in this chapter --- with\n**Tilly**, the course AI assistant on Canvas: ask it to propose a\ndistribution for your quantity and then challenge whether the normal\nmodel's assumptions actually hold for it.\n::::\n\nContinue to Lecture 7: Samples, parameters, and estimators.\n\nFormula sheet: Lecture 6 formulas.\n\nFor a more formal explanation, consult\n[Nieuwenhuis, *Statistical Methods for Business and Economics*](https://tilburguniversity.on.worldcat.org/oclc/317545871),\nChapter 10.\n\n:::\n",
    "supporting": [
      "b06-continuous-normal_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}