{
  "hash": "177d162f91aad4ec311b2e99659e95a0",
  "result": {
    "engine": "knitr",
    "markdown": "# Mock Exam: QM Intermediate {#intermediate-mock-exam}\n\n\n\n\n\n\n\n\n\nThis mock exam represents the full six-lecture course. It contains **100\npoints**, so the exam grade is\n\n$$\n\\text{grade} = \\frac{\\text{points earned}}{10}.\n$$\n\nThe Intermediate exam is completed in TestVision with R available. Unless a\nquestion states otherwise, use a 5% significance level. Interpret every\ncoefficient in the units and sample defined below; do not use causal language\nunless the design supports it.\n\nUse the [QM Intermediate Code Sheet](#intermediate-code-sheet) to review the R\ncommands and corresponding formulas before attempting the exam.\n\n| Question | Topic | Points |\n|---|---|---:|\n| 1 | Simple regression and least squares | 20 |\n| 2 | Assumptions and diagnostics | 20 |\n| 3 | Model fit and the overall F-test | 20 |\n| 4 | Multiple regression and a dummy predictor | 20 |\n| 5 | Interactions, curvature, and a partial F-test | 20 |\n| **Total** |  | **100** |\n\n## Dataset used throughout\n\nThe downloadable simulated exam dataset represents a simple random sample of\n320 independent young ventures from a business registry. One row represents\none venture. Treat the stated sampling story as the study context. The design\nis observational: none of the predictors was randomly assigned.\n\n- `growth_pct`: change in annual sales, in percentage points;\n- `marketing_10k`: annual marketing spending, in €10,000s;\n- `experience_years`: lead founder's prior industry experience, in years;\n- `team_size`: number of current team members;\n- `digital`: `No` for a primarily physical offering and `Yes` for a primarily\n  digital offering. `No` is the reference category;\n- `spend_c = marketing_10k - 4`: marketing spending centred at €40,000.\n\nThe target population is the ventures covered by this registry and sampling\nframe. Later survival and market conditions are not measured.\n\nThe dataset is simulated with a fixed seed, so every printed result on this\npage can be reproduced exactly. The code below is the code that generated it\nand fits the four models used in the questions:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(734)\nn_mock <- 320\nmarketing_10k <- round(runif(n_mock, 0.25, 8), 2)\nexperience_years <- sample(0:18, n_mock, replace = TRUE)\nteam_size <- sample(\n  1:10, n_mock, replace = TRUE,\n  prob = c(8, 16, 20, 20, 14, 9, 6, 4, 2, 1)\n)\ndigital <- factor(\n  ifelse(runif(n_mock) < 0.45, \"Yes\", \"No\"),\n  levels = c(\"No\", \"Yes\")\n)\nspend_c <- marketing_10k - 4\ngrowth_mean <-\n  8 + 1.10 * spend_c + 3 * (digital == \"Yes\") -\n  0.10 * spend_c^2 + 0.30 * experience_years +\n  0.70 * spend_c * (digital == \"Yes\") + 0.20 * team_size\ngrowth_pct <- round(\n  growth_mean + rnorm(n_mock, 0, 2.5 + 0.40 * marketing_10k),\n  2\n)\nventures <- data.frame(\n  growth_pct, marketing_10k, experience_years, team_size, digital, spend_c\n)\n\nsimple_model <- lm(growth_pct ~ marketing_10k, data = ventures)\nmultiple_model <- lm(\n  growth_pct ~ marketing_10k + experience_years + team_size + digital,\n  data = ventures\n)\nadditive_model <- lm(\n  growth_pct ~ spend_c + digital + experience_years,\n  data = ventures\n)\nextended_model <- lm(\n  growth_pct ~ spend_c * digital + I(spend_c^2) + experience_years,\n  data = ventures\n)\n```\n:::\n\n\n\n\n\n\n[Download `qm-intermediate-mock-exam.csv`](../data/qm-intermediate-mock-exam.csv),\nsave it in your R project, and load it with:\n\n```r\nventures <- read.csv(\"qm-intermediate-mock-exam.csv\")\nventures$digital <- factor(ventures$digital, levels = c(\"No\", \"Yes\"))\n```\n\nThe printed results below allow you to continue if R is temporarily\nunavailable, but during timed practice you should reproduce them from the\ndownloaded file.\n\n## Question 1: Simple regression and least squares — 20 points\n\nThe first model is\n\n```r\nsimple_model <- lm(growth_pct ~ marketing_10k, data = ventures)\n```\n\nand R reports\n\n```text\nCoefficients:\n                Estimate  Std. Error  t value  Pr(>|t|)\n(Intercept)        6.60       0.52      12.72   <2e-16\nmarketing_10k      1.38       0.11      12.35   <2e-16\n\nResidual standard error: 4.57 on 318 degrees of freedom\nMultiple R-squared: 0.324\n```\n\n1. Write the fitted regression equation with units. **(3 points)**\n2. Interpret the slope and intercept in context. Comment on whether the\n   intercept is substantively useful. **(6 points)**\n3. Calculate the fitted growth for a venture spending €30,000 on marketing.\n   If its observed growth is 15 percentage points, calculate its residual and\n   interpret the sign. **(5 points)**\n4. Explain what least squares minimises and why residuals are squared rather\n   than simply summed. **(4 points)**\n5. State the observational unit and why the fitted slope is not automatically\n   causal. **(2 points)**\n\n::: {.callout-note collapse=\"true\"}\n## Model answer and marking guide\n\n1. $\\widehat{growth\\_pct}=6.60+1.38\\,marketing\\_10k$, where the outcome is\n   in percentage points and the predictor in €10,000s (3 points).\n2. For each additional €10,000 of marketing spending, fitted annual sales\n   growth is 1.38 percentage points higher among sampled ventures (3 points).\n   At zero marketing spending, fitted growth is 6.60 percentage points\n   (2 points). This intercept is useful only if zero lies in or near the\n   observed spending range and defines a meaningful venture (1 point).\n3. €30,000 gives `marketing_10k = 3`, so the fitted value is\n   $6.60+1.38(3)=10.74$ percentage points (3 points). The residual is\n   $15-10.74=4.26$ percentage points; positive means observed growth exceeds\n   the model's fitted value (2 points).\n4. OLS chooses coefficients that minimise\n   $\\sum_i(y_i-\\hat y_i)^2$ (2 points). Unsquared residuals can cancel\n   because positive and negative residuals sum to zero with an intercept;\n   squaring also penalises larger misses more strongly (2 points).\n5. The unit is one venture (1 point). Observational association can reflect\n   confounding, reverse direction, selection, or measurement error (1 point).\n:::\n\n## Question 2: Assumptions and diagnostics — 20 points\n\nR produced the following diagnostics for\n`lm(growth_pct ~ marketing_10k, data = ventures)`. In the left panel,\neach point has fitted growth on the horizontal axis and its residual on the\nvertical axis. In the right panel, observed standardised residuals are plotted\nagainst theoretical standard-normal quantiles; a normal pattern would follow\nthe straight reference line.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"See the R code for this figure\"}\nlibrary(ggplot2)\nlibrary(patchwork)\n# Rebuilds the same ventures dataset as the visible chunk above (same seed).\nset.seed(734)\nn_mock <- 320\nmarketing_10k <- round(runif(n_mock, 0.25, 8), 2)\nexperience_years <- sample(0:18, n_mock, replace = TRUE)\nteam_size <- sample(\n  1:10, n_mock, replace = TRUE,\n  prob = c(8, 16, 20, 20, 14, 9, 6, 4, 2, 1)\n)\ndigital <- factor(\n  ifelse(runif(n_mock) < 0.45, \"Yes\", \"No\"),\n  levels = c(\"No\", \"Yes\")\n)\nspend_c <- marketing_10k - 4\ngrowth_mean <-\n  8 + 1.10 * spend_c + 3 * (digital == \"Yes\") -\n  0.10 * spend_c^2 + 0.30 * experience_years +\n  0.70 * spend_c * (digital == \"Yes\") + 0.20 * team_size\ngrowth_pct <- round(\n  growth_mean + rnorm(n_mock, 0, 2.5 + 0.40 * marketing_10k),\n  2\n)\nventures <- data.frame(\n  growth_pct, marketing_10k, experience_years, team_size, digital, spend_c\n)\nsimple_model <- lm(growth_pct ~ marketing_10k, data = ventures)\n\nresid_df <- data.frame(\n  fitted = fitted(simple_model),\n  residual = residuals(simple_model)\n)\nqq_df <- data.frame(rs = rstandard(simple_model))\ntheme_mock <- theme_minimal(base_size = 13) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    plot.caption = element_text(colour = \"#5B6976\"),\n    axis.title = element_text(colour = \"#17324D\")\n  )\n\np_resid <- ggplot(resid_df, aes(x = fitted, y = residual)) +\n  geom_hline(yintercept = 0, colour = \"#C98B2E\",\n             linetype = \"dashed\", linewidth = 0.8) +\n  geom_point(alpha = 0.45, size = 1.6, colour = \"#009E73\") +\n  annotate(\"text\", x = max(resid_df$fitted), y = 0,\n           label = \"residual = 0\", hjust = 1, vjust = -0.7,\n           colour = \"#17324D\", size = 3) +\n  labs(x = \"Fitted growth (percentage points)\",\n       y = \"Residual (percentage points)\") +\n  theme_mock\n\np_qq <- ggplot(qq_df, aes(sample = rs)) +\n  geom_qq_line(colour = \"#D55E00\", linewidth = 0.9) +\n  geom_qq(colour = \"#009E73\", alpha = 0.45, size = 1.6) +\n  labs(x = \"Normal theoretical quantile\",\n       y = \"Observed standardised residual\") +\n  theme_mock\n\np_resid + p_qq\n```\n\n::: {.cell-output-display}\n![Residual-versus-fitted plot and normal Q-Q plot for the simple model.](mock-exam_files/figure-html/fig-imock-diagnostics-1.png){#fig-imock-diagnostics width=672}\n:::\n:::\n\n\n\n\n1. Read both axes of the residual-versus-fitted panel and explain what a point\n   above zero represents. **(4 points)**\n2. What pattern do you see in that panel? Name the assumption it challenges.\n   **(4 points)**\n3. Explain how to read the Q--Q plot and assess normality here. **(4 points)**\n4. Name two regression assumptions that these plots cannot establish, and\n   state what information would help assess each. **(4 points)**\n5. Would heteroskedasticity-robust standard errors repair a curved conditional\n   mean or make the slope causal? Explain. **(4 points)**\n\n::: {.callout-note collapse=\"true\"}\n## Model answer and marking guide\n\n1. The horizontal axis is model-fitted growth; the vertical axis is\n   observed-minus-fitted growth, both in percentage points (2 points). A point\n   above zero is a venture whose observed growth is higher than its fitted\n   growth (2 points).\n2. Vertical spread increases with fitted growth, creating a fan shape\n   (2 points). This challenges constant conditional variance\n   (homoskedasticity) (2 points).\n3. The Q--Q plot compares ordered residuals with values expected under a\n   normal distribution; agreement appears as points near the line (2 points).\n   The middle is reasonably aligned but tail departures suggest imperfect\n   normality and possible extreme residuals (2 points).\n4. Examples: independence requires knowledge of clustering, repeated\n   observations, or sampling order; zero conditional mean/no omitted\n   confounding requires substantive design knowledge and relevant variables;\n   correct measurement requires information about how variables were recorded\n   (2 points per valid assumption plus evidence source, maximum 4).\n5. Robust SEs can improve large-sample uncertainty estimates under\n   heteroskedasticity (2 points). They do not change the fitted conditional\n   mean, repair omitted curvature, remove confounding, or make an observational\n   coefficient causal (2 points).\n:::\n\n## Question 3: Model fit and the overall F-test — 20 points\n\nThe researcher next fits\n\n```r\nmultiple_model <- lm(\n  growth_pct ~ marketing_10k + experience_years + team_size + digital,\n  data = ventures\n)\n```\n\nR reports:\n\n```text\nResidual standard error: 4.09 on 315 degrees of freedom\nMultiple R-squared: 0.464, Adjusted R-squared: 0.457\nF-statistic: 68.10 on 4 and 315 DF, p-value: < 2.2e-16\n```\n\nFor the intercept-only model, SST = 9,831.91. For `multiple_model`,\nSSE = 5,272.57.\n\n1. Verify $R^2$ from SST and SSE. Interpret it precisely. **(6 points)**\n2. Explain why adjusted $R^2$ is lower than $R^2$, and when adjusted\n   $R^2$ is useful. **(4 points)**\n3. State the null and alternative hypotheses of the reported overall F-test.\n   Give its conclusion. **(6 points)**\n4. Explain why this F-test is not equivalent to four separate 5% t-tests.\n   **(2 points)**\n5. Does $R^2=0.464$ show that the model predicts future ventures well?\n   Explain briefly. **(2 points)**\n\n::: {.callout-note collapse=\"true\"}\n## Model answer and marking guide\n\n1. $R^2=1-5272.57/9831.91\\approx0.464$ (3 points). The fitted values explain\n   46.4% of the observed sample variation in sales-growth percentage points;\n   it is not a percentage of correct predictions (3 points).\n2. Adjusted $R^2$ penalises the addition of predictors relative to sample\n   size and can fall when a term adds little fit (2 points). It helps compare\n   models fitted to the same outcome and analysis rows, although it is not a\n   substitute for validation or substantive reasoning (2 points).\n3. $H_0:\\beta_{marketing}=\\beta_{experience}=\\beta_{team}=\\beta_{digital}=0$\n   against the alternative that at least one is non-zero (3 points). The tiny\n   p-value leads to rejection: the complete model improves on an\n   intercept-only model under the inferential conditions (3 points).\n4. The F-test is one joint test of a vector of coefficients and accounts for\n   their covariance; separate t-tests answer four individual questions and\n   create a multiple-testing problem (2 points).\n5. No. This is in-sample fit; future prediction requires an appropriate test\n   set or cross-validation and a stable target population (2 points).\n:::\n\n## Question 4: Multiple regression and a dummy predictor — 20 points\n\nThe coefficient table below comes from\n`lm(growth_pct ~ marketing_10k + experience_years + team_size + digital, data = ventures)`.\nThe reference category for `digital` is `No`.\n\n```text\n                  Estimate  Std. Error  t value  Pr(>|t|)\n(Intercept)          2.45       0.77       3.18     0.002\nmarketing_10k        1.34       0.10      13.40    <0.001\nexperience_years     0.26       0.04       6.23    <0.001\nteam_size            0.17       0.10       1.63     0.104\ndigitalYes           3.08       0.46       6.67    <0.001\n```\n\n1. Interpret `marketing_10k`, including the predictor step, outcome unit,\n   held-fixed variables, and sample. **(5 points)**\n2. Interpret `digitalYes` and name its reference category. **(4 points)**\n3. Compare two otherwise identical ventures: A spends €20,000 on marketing,\n   has 5 years of founder experience, a team of 4, and `digital = No`; B has\n   the same values except it spends €40,000 and has `digital = Yes`. Calculate\n   B's fitted growth minus A's. **(5 points)**\n4. Test $H_0:\\beta_{team\\_size}=0$ against a two-sided alternative and give\n   a careful conclusion. **(3 points)**\n5. Explain why including controls does not by itself give the marketing or\n   digital coefficients a causal interpretation. **(3 points)**\n\n::: {.callout-note collapse=\"true\"}\n## Model answer and marking guide\n\n1. Among sampled registry ventures, an additional €10,000 in annual marketing\n   spending is associated with 1.34 percentage points higher fitted sales\n   growth, holding founder experience, team size, and offering type fixed\n   (5 points).\n2. At equal marketing spending, experience, and team size, primarily digital\n   ventures have fitted growth 3.08 percentage points higher than primarily\n   physical ventures; `No` is the reference (4 points).\n3. The spending change is two units, contributing $2(1.34)=2.68$; changing\n   from `No` to `Yes` contributes 3.08. The fitted difference is\n   $2.68+3.08=5.76$ percentage points (5 points).\n4. $t=1.63$, $p=0.104>0.05$, so do not reject $H_0$. The model does not\n   provide sufficiently precise evidence of a non-zero partial team-size\n   association; it does not prove the coefficient equals zero (3 points).\n5. Controls only adjust for measured variables in the specified functional\n   form. Unmeasured confounding, reverse direction, selection, and measurement\n   error can remain in this observational study (3 points).\n:::\n\n## Question 5: Interactions, curvature, and a partial F-test — 20 points\n\nThe researcher fits the hierarchical model\n\n```r\nextended_model <- lm(\n  growth_pct ~ spend_c * digital + I(spend_c^2) + experience_years,\n  data = ventures\n)\n```\n\nwith estimates:\n\n```text\n                         Estimate\n(Intercept)                  9.20\nspend_c                      1.04\ndigitalYes                   2.96\nI(spend_c^2)                -0.11\nexperience_years             0.24\nspend_c:digitalYes           0.68\n```\n\nThe partial comparison with the additive linear model reports:\n\n```text\nAnalysis of Variance Table\n\nModel 1: growth_pct ~ spend_c + digital + experience_years\nModel 2: growth_pct ~ spend_c * digital + I(spend_c^2) + experience_years\n  Res.Df    RSS  Df  Sum of Sq    F   Pr(>F)\n1    316  5317.0\n2    314  5053.8   2     263.23  8.18  0.00035\n```\n\n1. At €40,000 of marketing spending (`spend_c = 0`), give the fitted spending\n   slope for each offering type and the fitted `Yes`--`No` difference.\n   **(6 points)**\n2. At €60,000 (`spend_c = 2`), calculate the fitted `Yes`--`No` difference.\n   **(3 points)**\n3. For a physical-offering venture, calculate the fitted change when spending\n   rises from €60,000 (`spend_c = 2`) to €70,000 (`spend_c = 3`), holding\n   experience fixed. Repeat for a digital venture. **(5 points)**\n4. State the hypotheses and conclusion of the partial F-test. **(4 points)**\n5. State the hierarchy rule and one reason not to extrapolate this quadratic\n   far beyond the observed spending range. **(2 points)**\n\n::: {.callout-note collapse=\"true\"}\n## Model answer and marking guide\n\n1. At `spend_c = 0`, the physical-offering slope is 1.04 percentage points per\n   €10,000 and the digital slope is $1.04+0.68=1.72$ (2 points each). The\n   fitted digital-minus-physical difference is 2.96 percentage points\n   (2 points).\n2. The group difference is $2.96+0.68(2)=4.32$ percentage points\n   (3 points).\n3. For physical offerings, the change from 2 to 3 is\n   $1.04(1)-0.11(3^2-2^2)=1.04-0.55=0.49$ percentage points\n   (2 points). For digital offerings, add the interaction change of 0.68, so\n   the fitted change is 1.17 percentage points (2 points). Units and the\n   held-fixed experience condition earn 1 point.\n4. $H_0:\\beta_{spend\\times digital}=\\beta_{spend^2}=0$ against at least one\n   being non-zero (2 points). Since $p=0.00035<0.05$, reject: the two added\n   terms are jointly useful beyond the additive linear model, under the model\n   conditions (2 points).\n5. Retain the component lower-order terms when including an interaction or\n   polynomial term (1 point). A polynomial can turn sharply and imply\n   unrealistic values outside the observed range (1 point).\n:::\n\nYour marks across the five questions should sum to 100. Complete the mock exam\nin R before expanding the answers. Use the marking guide to check not only\ncalculations but also units, reference groups, held-fixed statements,\nuncertainty, and causal limits.\n",
    "supporting": [
      "mock-exam_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}